[reina_four_hearts]
kind = "gameplay_triggered"
speaker = "reina"
portrait = "neutral"
local = "[Ari], hey! You ready to do a little shopping?"
next = "1"

[reina_four_hearts.1]
speaker = "holt"
portrait = "neutral"
local = "I was just telling Reina here, you two couldn't have picked a better time!"
next = "2"

[reina_four_hearts.2]
portrait = "happy"
local = "A fresh shipment came in this morning and I stocked the shelves myself!"
next = "3"

[reina_four_hearts.3]
speaker = "reina"
portrait = "wink"
local = "We've got our pick of the place, [Ari]! Let's make it count!"
prompts = [
	{ local = "Let's go with something local, a real taste of Mistria!", next = "4" },
	{ local = "You got any of those reeeeeal sour gummy candies, Holt?", next = "5" },
]

[reina_four_hearts.4]
portrait = "happy"
local = "I like the way you think!"
next = "6"

[reina_four_hearts.5]
portrait = "embarrassed"
local = "Haha, that'll certainly get the judges' attention!"
next = "6"

[reina_four_hearts.6]
portrait = "think"
local = "Now let's see..."
next = "7"

[reina_four_hearts.7]
portrait = "closed_eyes_smile"
local = "Ooh, these herbs are from Celine's garden. Would you smell that thyme!"
next = "8"

[reina_four_hearts.8]
portrait = "wink"
local = "I think we've got our seasoning!"
next = "9"

[reina_four_hearts.9]
speaker = "holt"
portrait = "happy"
local = "Thyme will tell, but I think you've made a good choice, Reina."
next = "10"

[reina_four_hearts.10]
portrait = "think"
local = "Hmm... now that I think about it, we actually got a surprise in our shipment today."
next = "11"

[reina_four_hearts.11]
portrait = "neutral"
local = "This here is a Dragon Horn Mushroom! We don't usually keep them in stock, too hard to find."
next = "12"

[reina_four_hearts.12]
speaker = "reina"
portrait = "happy"
local = "Wow! I've never heard of it before!"
next = "13"

[reina_four_hearts.13]
speaker = "holt"
portrait = "think"
local = "You need a bit of a knack to find them, Nora and I used to pick them as kids! You can eat 'em raw, but they're great sauteed, fried, really any which way."
next = "14"

[reina_four_hearts.14]
portrait = "neutral"
local = "I thought I'd just have it as a snack but..."
next = "15"

[reina_four_hearts.15]
speaker = "reina"
portrait = "neutral"
local = "It sure does look tasty..."
prompts = [
	{ local = "Why don't we give it a try?", next = "16" },
	{ local = "I be-leaf we've found our ingredient!", next = "17" },
]

[reina_four_hearts.16]
speaker = "reina"
portrait = "happy"
local = "I do love to experiment with a new ingredient!"
next = "18"

[reina_four_hearts.17]
speaker = "holt"
portrait = "happy"
local = "[Ari], that was sup-herb!"
next = "18"

[reina_four_hearts.18]
speaker = "holt"
portrait = "neutral"
local = "You two don't leave mushroom for arguments! Tell you what, that and the thyme are on the house."
next = "19"

[reina_four_hearts.19]
speaker = "reina"
portrait = "neutral"
local = "Thanks, Holt! Come on [Ari]! I've got a little stovetop set up in my room, let's get cooking!"
next = "20"

[reina_four_hearts.20]
portrait = "think"
local = "Let's see, we really want to focus on what makes Mistria special, so I think something... simple but elevated..."
prompts = [
	{ local = "Maybe as an amuse bouche?", next = "21" },
	{ local = "How about as a dessert!", next = "22" },
]

[reina_four_hearts.21]
portrait = "happy"
local = "Yeah, to get them excited for the meal to come!"
next = "23"

[reina_four_hearts.22]
portrait = "think"
local = "I bet I could get some pretty good caramelization on this mushroom that would suit a cheese plate..."
next = "23"

[reina_four_hearts.23]
portrait = "closed_eyes_smile_blush"
local = "May I present... Dragon Horn Mushroom with Thyme!"
next = "24"

[reina_four_hearts.24]
portrait = "neutral"
effect = "sparkles"
local = "Ahh, what a flavor!"
next = "25"

[reina_four_hearts.25]
portrait = "embarrassed"
effect = "drop"
local = "Thanks for your help [Ari]. It isn't that much food though, is it?"
next = "26"

[reina_four_hearts.26]
portrait = "neutral"
local = "Tell you what, there's a pot of curry from yesterday downstairs, how about I heat some up for us?"
