[reina_two_hearts]
kind = "gameplay_triggered"
speaker = "reina"
portrait = "neutral"
local = "What good timing, [Ari]! Have a seat, I think the dish should've had just enough time to cool."
next = "1"

[reina_two_hearts.1]
portrait = "happy"
local = "Tada! It's =Wild Berry Pie=, made with all local ingredients! Give it a try!"
next = "2"

[reina_two_hearts.2]
portrait = "neutral"
local = "So whatcha think? Didn't that hit the spot?"
prompts = [
	{ local = "T-this is the best slice of pie I've ever had!", next = "3" },
	{ local = "Hmm, I'm not sure. Can I have another slice?", next = "4" },
]

[reina_two_hearts.3]
portrait = "happy"
local = "That's what I like to hear! I think the Mistrian berries really make it a standout."
next = "5"

[reina_two_hearts.4]
portrait = "wink"
local = "Haha, you can't fool me! Tell you what, I'll be sure to send you home with another slice."
next = "5"

[reina_two_hearts.5]
portrait = "neutral"
local = "I'm glad you could come by, [Ari]. It's always nice to have a new palate to taste test on. I've got just about everyone's favorites memorized!"
next = "6"

[reina_two_hearts.6]
portrait = "think"
local = "Actually, Adeline has something in the works that might help spread Mistrian cooking all over the country. I'd been hoping to hear back from her today..."
next = "7"

[reina_two_hearts.7]
speaker = "adeline"
portrait = "neutral"
local = "Reina! The letter just arrived, Mistria has been accepted!"
next = "8"

[reina_two_hearts.8]
speaker = "reina"
portrait = "happy"
local = "Oh my gosh!"
next = "9"

[reina_two_hearts.9]
portrait = "neutral"
local = "Adeline entered the Inn into a culinary event that has a panel of judges traveling around the country trying all the very best food!"
next = "10"

[reina_two_hearts.10]
speaker = "adeline"
portrait = "happy"
local = "I just knew you'd get accepted! Winning could mean big things for all of Mistria!"
next = "11"

[reina_two_hearts.11]
speaker = "reina"
portrait = "think"
local = "I've got a lot of work to do to get ready. New dishes to test and perfect, and that's with keeping on top of running the Inn's kitchen to boot..."
next = "12"

[reina_two_hearts.12]
portrait = "sad"
local = "I-I may have bitten off more than I can chew."
prompts = [
	{ local = "If anyone can do it, you can Reina!", next = "13" },
	{ local = "I'm happy to help test any new dishes you whip up!", next = "14" },
]

[reina_two_hearts.13]
portrait = "blush"
local = "Do you really think so?"
next = "15"

[reina_two_hearts.14]
portrait = "neutral"
local = "I'm glad I can count on you!"
next = "15"

[reina_two_hearts.15]
speaker = "adeline"
portrait = "neutral"
local = "You can rely on me as well, Reina. I'll see if I can't wrangle up some extra tips on wowing the judges. Not that I think you'll have any trouble with that!"
next = "16"

[reina_two_hearts.16]
speaker = "reina"
portrait = "wink"
local = "Yeah, you two are right! Now, how about I cut us all some fresh slices of pie?"
