
[dragon_tablet_pt_1_follow_up_seridia]
refresh = "instantly"
priority = "max"
requires = [{ npc = "seridia" }, { dt = "part_one" }]
portrait = "neutral"
local = "Yes, Hero? What is it?"
prompts = [
	{ local = "What should I do next?", next = "1" },
	{ local = "I feel a little lost...", next = "1" },
]

[dragon_tablet_pt_1_follow_up_seridia.1]
portrait = "think"
local = "Perhaps you should $investigate the Tablet over there$..."
next = "2"

[dragon_tablet_pt_1_follow_up_seridia.2]
portrait = "neutral"
local = "I am sure that it will reveal which $offerings are needed to break the seal$."

[dragon_tablet_pt_1]
kind = "gameplay_triggered"
writes = [{ dt = "part_one" }]
actions = [{ can_talk = "seridia" }]
speaker = "seridia"
portrait = "neutral"
local = "Hero!"
next = "1"

[dragon_tablet_pt_1.1]
speaker = "seridia"
portrait = "eyes_shine"
local = "You made it!"
next = "2"

[dragon_tablet_pt_1.2]
speaker = "seridia"
portrait = "neutral"
local = "Finally... we meet face to face."
next = "3"

[dragon_tablet_pt_1.3]
speaker = "seridia"
portrait = "sad"
local = "I have long awaited your arrival."
next = "4"

[dragon_tablet_pt_1.4]
speaker = "seridia"
portrait = "hurt"
local = "Longer than you can imagine..."
next = "5"

[dragon_tablet_pt_1.5]
speaker = "seridia"
portrait = "closed_eyes"
local = "Welcome to $The Final Seal$."
next = "6"

[dragon_tablet_pt_1.6]
speaker = "seridia"
portrait = "eyes_shine"
local = "The $Gate Between Worlds$..."
next = "7"

[dragon_tablet_pt_1.7]
speaker = "seridia"
portrait = "neutral_closed"
local = "The point from which all $Magic$ originates."
next = "8"

[dragon_tablet_pt_1.8]
speaker = "seridia"
portrait = "closed_eyes"
local = "For centuries this gate remained sealed."
next = "9"

[dragon_tablet_pt_1.9]
speaker = "seridia"
portrait = "hurt"
local = "$Magic$ all but disappeared from this world."
next = "10"

[dragon_tablet_pt_1.10]
speaker = "seridia"
portrait = "closed_eyes"
local = "Its remnants scattered and broken..."
next = "11"

[dragon_tablet_pt_1.11]
speaker = "seridia"
portrait = "neutral"
local = "Until now."
next = "12"

[dragon_tablet_pt_1.12]
speaker = "seridia"
portrait = "neutral_closed"
local = "The shift began shortly before you came to Mistria. An $earthquake$ caused a $crack to appear in the Seal$."
next = "13"

[dragon_tablet_pt_1.13]
speaker = "seridia"
portrait = "think"
local = "Just big enough for $Magic$ to begin seeping through..."
next = "14"

[dragon_tablet_pt_1.14]
speaker = "seridia"
portrait = "happy"
local = "Winding its way upward, dispersing out into the land."
next = "15"

[dragon_tablet_pt_1.15]
speaker = "seridia"
portrait = "sad"
local = "But there was no one left in the world above who could recognize $Magic Essence$..."
next = "16"

[dragon_tablet_pt_1.16]
speaker = "seridia"
portrait = "neutral"
local = "That is, not until you arrived."
next = "17"

[dragon_tablet_pt_1.17]
speaker = "seridia"
portrait = "serious_think"
local = "Had you not awoken Lord Caldarus..."
next = "18"

[dragon_tablet_pt_1.18]
speaker = "seridia"
portrait = "think"
local = "Had you not heard my call from underground..."
next = "19"

[dragon_tablet_pt_1.19]
speaker = "seridia"
portrait = "sad"
local = "I-"
next = "20"

[dragon_tablet_pt_1.20]
speaker = "seridia"
portrait = "hurt"
local = "I cannot bear to think of how long that state of affairs may have lasted."
next = "21"

[dragon_tablet_pt_1.21]
speaker = "seridia"
portrait = "neutral"
local = "But you are finally here..."
next = "22"

[dragon_tablet_pt_1.22]
speaker = "seridia"
portrait = "happy"
local = "The $Hero$ I have been waiting for."
next = "23"

[dragon_tablet_pt_1.23]
speaker = "seridia"
portrait = "neutral"
local = "Come, let us make haste."
next = "24"

[dragon_tablet_pt_1.24]
speaker = "seridia"
portrait = "happy"
local = "The time has come to break $The Final Seal$."
next = "25"

[dragon_tablet_pt_1.25]
speaker = "seridia"
portrait = "neutral"
local = "I am sure that the $Dragonsworn Tablet$ will reveal your next steps."
