[post_water_seal]
kind = "gameplay_triggered"
speaker = "caldarus"
local = "Approach, [Ari]. We must speak."
next = "1"

[post_water_seal.1]
speaker = "caldarus"
local = "The $Water Seal$ has been broken. A portion of my power has returned. You have done well."
next = "2"

[post_water_seal.2]
speaker = "caldarus"
local = "I will grant you $Summon Rain$, you will be able to access this $Spell$ from your $Journal$. It can be used to $summon a brief rain storm on your farm$. Use it wisely."
next = "3"

[post_water_seal.3]
speaker = "caldarus"
local = "Some memories are returning..."
next = "4"

[post_water_seal.4]
speaker = "caldarus"
local = "There are $five seals$ in total. The earthquake must have damaged them..."
next = "5"

[post_water_seal.5]
speaker = "caldarus"
local = "The resulting flow of magic allowed me to awaken when you repaired my shrine."
next = "6"

[post_water_seal.6]
speaker = "caldarus"
local = "But who closed off the seals in the first place, or why, I cannot recall."
next = "7"

[post_water_seal.7]
speaker = "caldarus"
local = "[Ari], you must reopen the other seals. I will do all I can to aid you along the way."
next = "8"

[post_water_seal.8]
speaker = "caldarus"
local = "For now, allow me to heal you."
next = "9"

[post_water_seal.9]
speaker = "caldarus"
local = "Go with my blessing."
