[post_earth_seal]
kind = "gameplay_triggered"
speaker = "caldarus"
local = "Come here, [Ari]. I have something to say."
next = "1"

[post_earth_seal.1]
speaker = "caldarus"
local = "The $Earth Seal$ has been broken. I owe you my sincere thanks."
next = "2"

[post_earth_seal.2]
speaker = "caldarus"
local = "I will grant you $Growth$, you will be able to access this $Spell$ from your $Journal$. It can be used to $instantly grow plants in a 3x3 area$. Use it wisely."
next = "3"

[post_earth_seal.3]
speaker = "caldarus"
local = "Some memories are returning..."
next = "4"

[post_earth_seal.4]
speaker = "caldarus"
local = "The $gate between realms$ was once cared for by the $Dragon Priestesses$."
next = "5"

[post_earth_seal.5]
speaker = "caldarus"
local = "Dragons brought magic to this land through that gate eons ago."
next = "6"

[post_earth_seal.6]
speaker = "caldarus"
local = "Our bond with humankind was mutually beneficial, yet the gate must have been closed at some point. Why, and by whom?"
next = "7"

[post_earth_seal.7]
speaker = "caldarus"
local = "My memory fails me there, [Ari]."
next = "8"

[post_earth_seal.8]
speaker = "caldarus"
local = "Three seals remain. I entrust you to break them."
