[priestess_quarters_pt_1]
kind = "gameplay_triggered"
writes = [{ pq = "part_one" }]
speaker = "seridia"
portrait = "neutral"
local = "^Greetings, Hero.^"
next = "1"

[priestess_quarters_pt_1.1]
speaker = "seridia"
portrait = "neutral_closed"
local = "^You have arrived at the $Priestess Quarters$.^"
next = "2"

[priestess_quarters_pt_1.2]
speaker = "seridia"
portrait = "think"
local = "^Ah...^"
next = "3"

[priestess_quarters_pt_1.3]
speaker = "seridia"
portrait = "happy"
local = "^High-ranking priestesses once lived in this place.^"
next = "4"

[priestess_quarters_pt_1.4]
speaker = "seridia"
portrait = "think"
local = "^It was necessary, in order to remain close to the $Gate Between Worlds$.^"
next = "5"

[priestess_quarters_pt_1.5]
speaker = "seridia"
portrait = "neutral"
local = """^What you know as $"The Final Seal"$.^"""
next = "6"

[priestess_quarters_pt_1.6]
speaker = "seridia"
portrait = "think"
local = "^This door...?^"
next = "7"

[priestess_quarters_pt_1.7]
speaker = "seridia"
portrait = "happy"
local = "^No, no. $The Final Seal$ lies still farther below.^"
next = "8"

[priestess_quarters_pt_1.8]
speaker = "seridia"
portrait = "think"
local = "^However, it does appear that this door is currently blocking your descent.^"
next = "9"

[priestess_quarters_pt_1.9]
speaker = "seridia"
portrait = "sad"
local = "^And... it is $locked$.^"
next = "10"

[priestess_quarters_pt_1.10]
speaker = "seridia"
portrait = "think"
local = "^Do not look so forlorn!^"
next = "11"

[priestess_quarters_pt_1.11]
speaker = "seridia"
portrait = "neutral"
local = "^You have reached hallowed ground. There are no traps here.^"
next = "12"

[priestess_quarters_pt_1.12]
speaker = "seridia"
portrait = "happy"
local = "^The $Magic Key$ used to access the lower floors surely remains hidden in these quarters.^"
next = "13"

[priestess_quarters_pt_1.13]
speaker = "seridia"
portrait = "think"
local = "^I must begin other preparations...^"
next = "14"

[priestess_quarters_pt_1.14]
speaker = "seridia"
portrait = "sad"
local = "^So you will need to proceed through this trial alone.^"
next = "15"

[priestess_quarters_pt_1.15]
speaker = "seridia"
portrait = "neutral"
local = "^However, I am certain that you will find the $Magic Key$ in no time.^"

[priestess_quarters_pt_2_follow_up_caldarus]
refresh = "never"
requires = [{ npc = "caldarus" }, { pq = "part_two" }]
portrait = "neutral"
local = "A question? Certainly [Ari], what is it?"
next = "1"

[priestess_quarters_pt_2_follow_up_caldarus.1]
portrait = "think"
local = "You wish to know more of the $Dragon Priestesses$?"
next = "2"

[priestess_quarters_pt_2_follow_up_caldarus.2]
portrait = "sigh"
local = "Such dedicated souls."
next = "3"

[priestess_quarters_pt_2_follow_up_caldarus.3]
portrait = "think"
local = "They showed... unwavering faith in me."
next = "4"

[priestess_quarters_pt_2_follow_up_caldarus.4]
portrait = "sad"
local = "..."
next = "5"

[priestess_quarters_pt_2_follow_up_caldarus.5]
portrait = "sigh"
local = "Forgive me [Ari]. I find it painful, trying to recall their faces."
prompts = [{ local = "Forget I asked!", next = "6" }, { local = "Just focus on resting.", next = "6" }]

[priestess_quarters_pt_2_follow_up_caldarus.6]
portrait = "neutral"
local = "Thank you [Ari]."
next = "7"

[priestess_quarters_pt_2_follow_up_caldarus.7]
portrait = "smile"
local = "Perhaps when my memories are restored, I will regale you with tales of those days."

[priestess_quarters_pt_2]
kind = "gameplay_triggered"
speaker = "seridia"
portrait = "neutral"
local = "^Cleverly done, Hero!^"
next = "1"

[priestess_quarters_pt_2.1]
speaker = "seridia"
portrait = "happy"
local = "^I knew that you would pass the trial.^"
next = "2"

[priestess_quarters_pt_2.2]
speaker = "seridia"
portrait = "neutral"
local = "^The $Final Seal$ lies ahead.^"
next = "3"

[priestess_quarters_pt_2.3]
speaker = "seridia"
portrait = "neutral_closed"
local = "^Allow me to grant you a gift that will ease your final descent.^"
next = "4"

[priestess_quarters_pt_2.4]
speaker = "seridia"
portrait = "neutral"
local = "^Use the $Sacred Light Spell$ on $Dark Floors$ if you wish to pass through them more easily.^"
next = "5"

[priestess_quarters_pt_2.5]
speaker = "seridia"
portrait = "happy"
local = "^We will meet again at the bottom of the Ruins.^"
next = "6"

[priestess_quarters_pt_2.6]
speaker = "seridia"
portrait = "neutral"
local = "^I will be waiting...^"
next = "7"

[priestess_quarters_pt_2.7]
speaker = "seridia"
portrait = "happy"
local = "^And together, at long last, we will restore the power of the Dragon.^"
