[ruins_seal]
kind = "gameplay_triggered"
no_speaker = true
local = "A faint whisper breaks the silence..."
next = "1"

[ruins_seal.1]
speaker = "seridia"
local = "^Hero...^"
next = "2"

[ruins_seal.2]
local = "^You cannot proceed further... yet.^"
portrait = "sad"
next = "3"

[ruins_seal.3]
local = "^Return... later...^"
portrait = "neutral_closed"

[break_ruins_seal_pt_1]
kind = "gameplay_triggered"
speaker = "seridia"
portrait = "neutral"
local = "^Hero! Thank goodness!^"
next = "1"

[break_ruins_seal_pt_1.1]
speaker = "seridia"
portrait = "sad"
local = "^I am so glad to see that you are safe.^"
next = "2"

[break_ruins_seal_pt_1.2]
speaker = "seridia"
portrait = "think"
local = "^To think that the $Fire Seal$ would be trapped...^"
next = "3"

[break_ruins_seal_pt_1.3]
speaker = "seridia"
portrait = "sad"
local = "^I regret that I did not foresee it.^"
next = "4"

[break_ruins_seal_pt_1.4]
speaker = "seridia"
portrait = "neutral"
local = "^Yet you have survived, and succeeded in breaking the seal!^"
next = "5"

[break_ruins_seal_pt_1.5]
speaker = "seridia"
portrait = "neutral_closed"
local = "^Finally, my voice can reach you more clearly.^"
next = "6"

[break_ruins_seal_pt_1.6]
speaker = "seridia"
portrait = "embarrassed"
local = "^You have done well.^"
next = "7"

[break_ruins_seal_pt_1.7]
speaker = "seridia"
portrait = "closed_eyes"
local = "^I sense something, Hero. Draconic power...?^"
next = "8"

[break_ruins_seal_pt_1.8]
speaker = "seridia"
portrait = "think"
local = "^Faint, like a trembling pulse.^"
next = "9"

[break_ruins_seal_pt_1.9]
speaker = "seridia"
portrait = "closed_eyes"
local = "^Weak... but alive.^"
next = "10"

[break_ruins_seal_pt_1.10]
speaker = "seridia"
portrait = "serious_think"
local = "^No, it could not be.^"
next = "11"

[break_ruins_seal_pt_1.11]
speaker = "seridia"
portrait = "mad"
effect = "surprise"
local = "^!^"
next = "12"

[break_ruins_seal_pt_1.12]
speaker = "seridia"
portrait = "eyes_shine"
local = "^Lord Caldarus has materialized in physical form!?^"
next = "13"

[break_ruins_seal_pt_1.13]
speaker = "seridia"
portrait = "neutral_closed"
local = "^And he did so to save you from the $Sealing Scroll$?^"
next = "14"

[break_ruins_seal_pt_1.14]
speaker = "seridia"
portrait = "neutral"
local = "^It- it is nothing short of a miracle.^"
next = "15"

[break_ruins_seal_pt_1.15]
speaker = "seridia"
portrait = "hurt"
local = "^Yet to take such a drastic measure...^"
next = "16"

[break_ruins_seal_pt_1.16]
speaker = "seridia"
portrait = "closed_eyes"
local = "^Lord Caldarus must be protected at all costs.^"
next = "17"

[break_ruins_seal_pt_1.17]
speaker = "seridia"
portrait = "hurt"
local = "^If he were to-^"
next = "18"

[break_ruins_seal_pt_1.18]
speaker = "seridia"
portrait = "closed_eyes"
local = "^No. We shall not let any harm come to him.^"
next = "19"

[break_ruins_seal_pt_1.19]
speaker = "seridia"
portrait = "neutral"
local = "^We will need to proceed with extreme caution, Hero.^"
next = "20"

[break_ruins_seal_pt_1.20]
speaker = "seridia"
portrait = "sad"
local = "^The last seal was trapped. Surely, this one must be as well.^"
next = "21"

[break_ruins_seal_pt_1.21]
speaker = "seridia"
portrait = "closed_eyes"
local = "^Pray, do not touch anything in this room. It is not safe.^"
next = "22"

[break_ruins_seal_pt_1.22]
speaker = "seridia"
portrait = "think"
local = "^We cannot risk attempting to open the $Ruins Seal$ in the usual manner.^"
next = "23"

[break_ruins_seal_pt_1.23]
speaker = "seridia"
portrait = "sad"
local = "^You are the only one who holds hope of reaching the $Final Seal$ through the ruins beyond, for I remain incorporeal.^"
next = "24"

[break_ruins_seal_pt_1.24]
speaker = "seridia"
portrait = "hurt"
local = "^Lord Caldarus and I are relying on you.^"
next = "25"

[break_ruins_seal_pt_1.25]
speaker = "seridia"
portrait = "eyes_shine"
local = "^You are our only hope.^"
next = "26"

[break_ruins_seal_pt_1.26]
speaker = "seridia"
portrait = "serious_think"
local = "^For now, let us focus on the $Ruins Seal$.^"
next = "27"

[break_ruins_seal_pt_1.27]
speaker = "seridia"
portrait = "think"
local = "^If we cannot break through it in the typical manner...^"
next = "28"

[break_ruins_seal_pt_1.28]
speaker = "seridia"
portrait = "neutral"
local = "^Perhaps we can devise a way around it.^"
next = "29"

[break_ruins_seal_pt_1.29]
speaker = "seridia"
portrait = "happy"
local = "^So to speak.^"
next = "30"

[break_ruins_seal_pt_1.30]
speaker = "seridia"
portrait = "neutral"
local = "^The boundary between worlds grows thinner, the closer we come to the $Final Seal$.^"
next = "31"

[break_ruins_seal_pt_1.31]
speaker = "seridia"
portrait = "think"
local = "^With enough draconic $Magic$, it should be possible...^"
next = "32"

[break_ruins_seal_pt_1.32]
speaker = "seridia"
portrait = "happy"
local = "^Lord Caldarus has granted you $Dragon's Breath$, has he not?^"
next = "33"

[break_ruins_seal_pt_1.33]
speaker = "seridia"
portrait = "neutral"
local = "^Come, Hero. If we cast it in unison, I believe we can $open a portal to a nearby plane of existence$.^"
next = "34"

[break_ruins_seal_pt_1.34]
speaker = "seridia"
portrait = "neutral"
local = "^We have succeeded! Wonderful!^"
next = "35"

[break_ruins_seal_pt_1.35]
speaker = "seridia"
portrait = "neutral_closed"
local = "^Now, follow me.^"
next = "36"

[break_ruins_seal_pt_1.36]
speaker = "seridia"
portrait = "neutral_closed"
local = "^Excellent, this should do nicely.^"
next = "37"

[break_ruins_seal_pt_1.37]
speaker = "seridia"
portrait = "neutral"
local = "^Close your eyes, Hero. I shall grant you $Void Sight$.^"
next = "38"

[break_ruins_seal_pt_1.38]
speaker = "seridia"
portrait = "neutral_closed"
local = "^You will need it in order to proceed.^"
next = "39"

[break_ruins_seal_pt_1.39]
speaker = "seridia"
portrait = "neutral"
local = "^We are one step nearer to $the Magic Realm$ now, Hero.^"
next = "40"

[break_ruins_seal_pt_1.40]
speaker = "seridia"
portrait = "sad"
local = "^Of course, we cannot truly reach it from here. Not while $two seals remain closed$.^"
next = "41"

[break_ruins_seal_pt_1.41]
speaker = "seridia"
portrait = "think"
local = "^This place is more of a connection point. A field between your world and mine.^"
next = "42"

[break_ruins_seal_pt_1.42]
speaker = "seridia"
portrait = "neutral"
local = "^But that makes it... malleable.^"
next = "43"

[break_ruins_seal_pt_1.43]
speaker = "seridia"
portrait = "happy"
local = "^And that is just what we need.^"
next = "44"

[break_ruins_seal_pt_1.44]
speaker = "seridia"
portrait = "neutral"
local = "^Do you see the $Cauldron$ there?^"
next = "45"

[break_ruins_seal_pt_1.45]
speaker = "seridia"
portrait = "think"
local = "^You must gather $5 Void Stones, 5 Void Powders, 5 Void Herbs, and 5 Void Pearls$ and place them within.^"
next = "46"

[break_ruins_seal_pt_1.46]
speaker = "seridia"
portrait = "neutral"
local = "^Your new $Void Sight$ ability will allow you to $see and harvest these items throughout the Mines$.^"
next = "47"

[break_ruins_seal_pt_1.47]
speaker = "seridia"
portrait = "happy"
local = "^Once you have collected the necessary materials, we will use them to create a $Void Mass$.^"
next = "48"

[break_ruins_seal_pt_1.48]
speaker = "seridia"
portrait = "neutral"
local = "^That will be our key to safely breaking the $Ruins Seal$.^"
next = "49"

[break_ruins_seal_pt_1.49]
speaker = "seridia"
portrait = "neutral_closed"
local = "^Go now, Hero.^"
next = "50"

[break_ruins_seal_pt_1.50]
speaker = "seridia"
portrait = "sad"
local = "^But do not speak word of this to Lord Caldarus.^"
next = "51"

[break_ruins_seal_pt_1.51]
speaker = "seridia"
portrait = "hurt"
local = "^He is much too weak, and we must not tempt him to intervene again.^"
next = "52"

[break_ruins_seal_pt_1.52]
speaker = "seridia"
portrait = "neutral"
local = "^Let us protect him. He must stay safe until the $Final Seal$ is broken.^"

[break_ruins_seal_pt_2]
kind = "gameplay_triggered"
speaker = "seridia"
portrait = "neutral"
local = "^I see that you have succeeded in gathering all the necessary materials!^"
next = "1"

[break_ruins_seal_pt_2.1]
speaker = "seridia"
portrait = "happy"
local = "^Excellent work!^"
next = "2"

[break_ruins_seal_pt_2.2]
speaker = "seridia"
portrait = "neutral"
local = "^This is everything we need in order to create the $Void Mass$.^"
next = "3"

[break_ruins_seal_pt_2.3]
speaker = "seridia"
portrait = "happy"
local = "^Let us proceed.^"
next = "4"

[break_ruins_seal_pt_2.4]
speaker = "seridia"
portrait = "neutral"
local = "^Beautiful, is it not?^"
next = "5"

[break_ruins_seal_pt_2.5]
speaker = "seridia"
portrait = "closed_eyes"
local = "^Now, it is time to create our $decoy$.^"
next = "6"

[break_ruins_seal_pt_2.6]
speaker = "seridia"
portrait = "sad"
local = "^Stand back, if you would...^"
next = "7"

[break_ruins_seal_pt_2.7]
speaker = "seridia"
portrait = "neutral_closed"
local = "^I shall transform the $Void Mass$...^"
next = "8"

[break_ruins_seal_pt_2.8]
speaker = "seridia"
portrait = "neutral"
local = "^Into our $Void [Ari]$.^"
next = "9"

[break_ruins_seal_pt_2.9]
speaker = "seridia"
portrait = "sad"
local = "^Fear not!^"
next = "10"

[break_ruins_seal_pt_2.10]
speaker = "seridia"
portrait = "serious_think"
local = "^The $Void [Ari]$ is merely a tool. A means to an end.^"
next = "11"

[break_ruins_seal_pt_2.11]
speaker = "seridia"
portrait = "closed_eyes"
local = "^It is not capable of thinking, nor feeling.^"
next = "12"

[break_ruins_seal_pt_2.12]
speaker = "seridia"
portrait = "neutral"
local = "^It is a kind of shadow. It can only move at your instruction.^"
next = "13"

[break_ruins_seal_pt_2.13]
speaker = "seridia"
portrait = "happy"
local = "^We shall utilize it to open the $Ruins Seal$ without risking harm to you.^"
next = "14"

[break_ruins_seal_pt_2.14]
speaker = "seridia"
portrait = "neutral"
local = "^Come, let us return at once.^"
next = "15"

[break_ruins_seal_pt_2.15]
speaker = "seridia"
portrait = "neutral"
local = "^It is time to put our $decoy$ to the test.^"
next = "16"

[break_ruins_seal_pt_2.16]
speaker = "seridia"
portrait = "think"
local = "^If you would, please instruct the $Void [Ari]$ to take the rubbing of the $Ruins Seal Tablet$.^"
next = "17"

[break_ruins_seal_pt_2.17]
speaker = "seridia"
portrait = "neutral"
local = "^Ah...^"
next = "18"

[break_ruins_seal_pt_2.18]
speaker = "seridia"
portrait = "happy"
local = "^I am grateful that we did not attempt to have you try that directly. Would you not agree?^"
next = "19"

[break_ruins_seal_pt_2.19]
speaker = "seridia"
portrait = "happy"
local = "^Now, about the translation...^"
next = "20"

[break_ruins_seal_pt_2.20]
speaker = "seridia"
portrait = "neutral"
local = "^What is it?^"
prompts = [
	{ local = "The Witchspeak... I can read it!", next = "21" },
	{ local = "I guess I won't need a translator after all!", next = "21" },
]

[break_ruins_seal_pt_2.21]
speaker = "seridia"
portrait = "happy"
local = "^Oh my! Is that so?^"
next = "22"

[break_ruins_seal_pt_2.22]
speaker = "seridia"
portrait = "neutral"
local = "^It would seem that your proficiency in $Magic$ has grown quite significantly.^"
next = "23"

[break_ruins_seal_pt_2.23]
speaker = "seridia"
portrait = "happy"
local = "^Tell me, what are the requirements?^"
next = "24"

[break_ruins_seal_pt_2.24]
speaker = "seridia"
portrait = "think"
local = "^I see. A $Breath of Flame$, a $Smoke Moth$, a $Firesail Fish$, and a piece of $Obsidian$...^"
next = "25"

[break_ruins_seal_pt_2.25]
speaker = "seridia"
portrait = "happy"
local = "^I presume this task should be no trouble for one of your talents.^"
next = "26"

[break_ruins_seal_pt_2.26]
speaker = "seridia"
portrait = "think"
local = "^However, you will not be able to offer these items to the $Ruins Seal Tablet$ directly-^"
next = "27"

[break_ruins_seal_pt_2.27]
speaker = "seridia"
portrait = "neutral"
local = "^Instead, be sure to give them to the $Void [Ari]$.^"
next = "28"

[break_ruins_seal_pt_2.28]
speaker = "seridia"
portrait = "happy"
local = "^Once the items are gathered, it will open the seal for us.^"
next = "29"

[break_ruins_seal_pt_2.29]
speaker = "seridia"
portrait = "neutral"
local = "^Best of luck with your task. I shall await your return.^"

[break_ruins_seal_pt_3_follow_up_caldarus]
refresh = "never"
requires = [
	{ npc = "caldarus" },
	{ ruins_seal = "part_3" },
	{ ruins_seal_follow_up_bump = true }
]
portrait = "neutral"
local = "[Ari]..."
next = "1"

[break_ruins_seal_pt_3_follow_up_caldarus.1]
portrait = "sigh"
local = "My apologies, I do not feel very well today."
next = "2"

[break_ruins_seal_pt_3_follow_up_caldarus.2]
portrait = "sad"
local = "I am not sure what has come over me."
next = "3"

[break_ruins_seal_pt_3_follow_up_caldarus.3]
portrait = "think"
local = "Perhaps I just need to rest."

[break_ruins_seal_pt_3]
kind = "gameplay_triggered"
writes = [
	{ ruins_seal = "part_3", expires = "4d" },
	{ ruins_seal_follow_up_bump = true }
]
actions = [
	{ heart_points = { amount = 40, npc = "eiland" } },
	{ heart_points = { amount = 40, npc = "juniper" } }
]
speaker = "seridia"
portrait = "neutral"
local = "^You have succeeded once again!^"
next = "1"

[break_ruins_seal_pt_3.1]
speaker = "seridia"
portrait = "happy"
local = "^I see that the $Void [Ari]$ now holds the necessary offerings.^"
next = "2"

[break_ruins_seal_pt_3.2]
speaker = "seridia"
portrait = "think"
local = "^Let us keep our distance while you direct it to break the seal.^"
next = "3"

[break_ruins_seal_pt_3.3]
speaker = "seridia"
portrait = "neutral"
local = "^Go on, there is no reason to worry. You are safe.^"
next = "4"

[break_ruins_seal_pt_3.4]
speaker = "seridia"
portrait = "hurt"
local = "^Ah... well done, $Void [Ari]$.^"
next = "5"

[break_ruins_seal_pt_3.5]
speaker = "seridia"
portrait = "sad"
local = "^Thank you for fulfilling your purpose.^"
next = "6"

[break_ruins_seal_pt_3.6]
speaker = "seridia"
portrait = "neutral"
local = "^And thank you, as well.^"
next = "7"

[break_ruins_seal_pt_3.7]
speaker = "seridia"
portrait = "happy"
local = "^You have succeeded in breaking the $Ruins Seal$.^"
next = "8"

[break_ruins_seal_pt_3.8]
speaker = "seridia"
portrait = "sad"
local = "^Be sure to proceed with caution.^"
next = "9"

[break_ruins_seal_pt_3.9]
speaker = "seridia"
portrait = "hurt"
local = "^And remember, we must not burden Lord Caldarus with news of these events.^"
next = "10"

[break_ruins_seal_pt_3.10]
speaker = "seridia"
portrait = "neutral"
local = "^This last chapter of the journey... we shall see it through together.^"
next = "11"

[break_ruins_seal_pt_3.11]
speaker = "seridia"
portrait = "happy"
local = "^I shall stand by you in Lord Caldarus' stead until the $Final Seal$ is broken.^"
next = "12"

[break_ruins_seal_pt_3.12]
speaker = "seridia"
portrait = "neutral"
local = "^Go forth now...^"
next = "13"

[break_ruins_seal_pt_3.13]
speaker = "seridia"
portrait = "neutral_closed"
local = "^We shall meet again in the ruins below.^"
next = "14"

[break_ruins_seal_pt_3.14]
speaker = "seridia"
portrait = "neutral"
local = "^The time of the Dragon's full awakening draws near.^"
