[procuring_the_sealing_scroll_finished]
kind = "gameplay_triggered"
speaker = "balor"
portrait = "happy"
local = "Pure silver ingots and exceptional quality gemstones. I'm sure the seller will be very pleased."
next = "1"

[procuring_the_sealing_scroll_finished.1]
speaker = "balor"
portrait = "neutral"
local = "I'll make the exchange tonight and then $deliver the Sealing Scroll to you tomorrow$."

[procuring_the_sealing_scroll]
kind = "gameplay_triggered"
writes = [{ tft = false }]
speaker = "balor"
portrait = "neutral"
local = "There you are! Good news, I've made contact with a seller."
next = "1"

[procuring_the_sealing_scroll.1]
speaker = "balor"
portrait = "think"
local = "They've gone to some lengths to keep their identity secret, and have asked that they be paid in untraceable ingots and gemstones."
next = "2"

[procuring_the_sealing_scroll.2]
speaker = "balor"
portrait = "mad"
local = "Are you sure you're up for this?"
prompts = [
	{ local = "Yes, thank you for hunting the scroll down!", next = "3" },
	{ local = "Do you think you could do a little haggling for me?", next = "4" },
]

[procuring_the_sealing_scroll.3]
speaker = "balor"
portrait = "happy"
local = "You're very welcome, of course. It's been quite the challenge!"
next = "5"

[procuring_the_sealing_scroll.4]
speaker = "balor"
portrait = "think"
local = "I'm flattered you think so highly of my skills, but I suspect if we try to haggle, the seller will simply disappear."
next = "5"

[procuring_the_sealing_scroll.5]
speaker = "balor"
portrait = "neutral"
local = "You'll need $10 Silver Ingots$, $10 Rubies$, $10 Sapphires$, and $10 Emeralds$."
next = "6"

[procuring_the_sealing_scroll.6]
speaker = "balor"
portrait = "sigh"
local = "I know. Let's just count our blessings that they didn't ask for more."
next = "7"

[procuring_the_sealing_scroll.7]
speaker = "balor"
portrait = "neutral"
local = "I'll leave the $Payment Box$ by my wagon."

[delivering_the_sealing_scroll]
kind = "gameplay_triggered"
speaker = "balor"
portrait = "neutral"
local = "Good morning, [Ari]. I wanted to hand you the $Sealing Scroll$ personally."
next = "1"

[delivering_the_sealing_scroll.1]
speaker = "balor"
portrait = "happy"
local = "It was a pleasure doing business with you."
next = "2"

[delivering_the_sealing_scroll.2]
speaker = "balor"
portrait = "think"
local = "I'm not sure what you're planning to do with it, but the seller repeatedly warned me that it isn't to be opened under any circumstances."
next = "3"

[delivering_the_sealing_scroll.3]
speaker = "balor"
portrait = "concerned"
local = "I'm not sure I believe all their talk of curses and magic, but..."
next = "4"

[delivering_the_sealing_scroll.4]
speaker = "balor"
portrait = "mad"
local = "Better to keep yourself safe, [Ari]."
