requires = [{ adeline_has_met = false }]
start_writes = []
end_writes = []

## Warning!
##
## These schedules are heavily duplicated with other roommate variations, like the friday night one
## and the festival one. if you're going to make a change here, make sure to check if you need to
## make the same change over there!

[adeline."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "adeline_roommate" },
    { after = "10n", can_talk = "adeline" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[balor."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "balor_roommate" },
    { after = "10n", can_talk = "balor" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[caldarus."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "caldarus_roommate" },
    { after = "10n", can_talk = "caldarus" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[celine."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "celine_roommate" },
    { after = "10n", can_talk = "celine" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[eiland."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "eiland_roommate" },
    { after = "10n", can_talk = "eiland" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[hayden."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "hayden_roommate" },
    { after = "10n", can_talk = "hayden" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[juniper."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "juniper_roommate" },
    { after = "10n", can_talk = "juniper" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[march."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "march_roommate" },
    { after = "10n", can_talk = "march" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[reina."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "reina_roommate" },
    { after = "10n", can_talk = "reina" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[ryis."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "ryis_roommate" },
    { after = "10n", can_talk = "ryis" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[seridia."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "seridia_roommate" },
    { after = "10n", can_talk = "seridia" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[valen."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "valen_roommate" },
    { after = "10n", can_talk = "valen" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[dozy."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "dozy_roommate" },
    { after = "10n", can_talk = "dozy" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]

[henrietta."6:00am"]
destination = "aldaria/default"
delayed_arrival_actions = [
    { after = "10n", routine = "henrietta_roommate" },
    { after = "10n", can_talk = "henrietta" },
    { after = "5h", start_original_schedule = true },
    { after = "13h", finish_original_schedule = "Schedules/roommate_schedule" },
]
