requires = [
	{ weather = "pleasant" },
	{ caldarus_home = true },
	{ caldarus_counter = 1 }
]


# Caldarus
[caldarus."6:00am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]


[caldarus."6:18am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ routine = "caldarus_house_reading" }]

[caldarus."10:28am"]
destination = "deep_woods/routine_exit"
on_arrival_actions = [{ routine = "deep_woods_pond_wander" }]

[caldarus."2:51pm"]
destination = "caldarus_house/routine_entrance"
on_arrival_actions = [{ routine = "tea_making" }]

[caldarus."7:11pm"]
destination = "caldarus_house/Caldarus Desk Chair"

[caldarus."10:22pm"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]
on_departure_writes = [{ caldarus_counter = 2 }]
