requires = [
	{ weather = "pleasant" },
	{ caldarus_home = true },
	{ caldarus_counter = 1 }
]

# Caldarus
[caldarus."6:00am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]

[caldarus."6:32am"]
destination = "caldarus_house/Caldarus Pouf Right"

[caldarus."10:22am"]
destination = "caldarus_house/Caldarus Pouf Right"
on_arrival_actions = [{ routine = "statue_cleaning" }]

[caldarus."1:44pm"]
destination = "caldarus_house/lute_2"
on_arrival_actions = [{ animation = "lute_play" }]

[caldarus."6:12pm"]
destination = "deep_woods/Caldarus Bench Left"

[caldarus."9:55pm"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]
on_departure_writes = [{ caldarus_counter = 2 }]
