
priority = "max"
requires = [{ spring_festival_date = "1d", time = "after" }]
start_writes = [
	{ inn_counter = 0 },
	{ bathhouse_counter = 0 },
]

# adeline
[adeline."6:00am"]
destination = "town/sf_adeline_booth"

[adeline."11:32am"]
destination = "town/sf_elsie_booth"

[adeline."4:12pm"]
destination = "town/sf_eiland_booth"

[adeline."8:45pm"]
destination = "manor_house_dining_room/Table Right Seat 1"
on_arrival_actions = [{ activity = "drink" }]

# balor
[balor."6:00am"]
destination = "town/sf_balor_booth"

[balor."12:47pm"]
destination = "town/sf_terithia_chat"

[balor."8:53pm"]
destination = "inn/Top Bar Seat"
on_arrival_actions = [{ activity = "order_drink" }]

[balor."1:38am"]
destination = "balors_room/Balor Wake Point"

# celine
[celine."6:00am"]
destination = "town/sf_celine_booth"

[celine."3:08pm"]
destination = "town/sf_errol_chat"

[celine."9:11pm"]
destination = "celines_room/ArmChair Seat"
on_arrival_actions = [{ animation = "book_sit" }]

# dell
[dell."6:00am"]
destination = "town/sf_dell_booth"

[dell."1:11pm"]
destination = "town/sf_dell_booth_2"

[dell."8:07pm"]
destination = "dells_bedroom/Dell Bed"

# dozy
[dozy."6:00am"]
destination = "town/sf_dozy_wander_1"
on_arrival_actions = [{ routine = "spring_festival_dozy_wander" }]

[dozy."12:15pm"]
destination = "town/sf_dozy_stage"

[dozy."7:32pm"]
destination = "bathhouse/Dozy"
on_arrival_actions = [{ routine = "dozy_snooze" }]

# eiland
[eiland."6:00am"]
destination = "town/sf_eiland_booth"

[eiland."1:12pm"]
destination = "town/sf_reina_stage"

[eiland."8:35pm"]
destination = "manor_house_dining_room/Table Left Seat 1"
on_arrival_actions = [{ activity = "drink" }]

# elsie
[elsie."6:00am"]
destination = "town/sf_elsie_booth"

[elsie."11:35am"]
destination = "town/sf_elsie_duet"
on_arrival_actions = [{ animation = "sing" }]

[elsie."4:09pm"]
destination = "town/sf_elsie_booth"

[elsie."9:57pm"]
destination = "manor_house_dining_room/Table Right Seat 2"
on_arrival_actions = [{ activity = "drink" }]

# errol
[errol."6:00am"]
destination = "town/sf_errol_chat"

[errol."2:21pm"]
destination = "town/sf_errol_booth"

[errol."8:29pm"]
destination = "errols_bedroom/Desk Chair"

# hayden
[hayden."6:00am"]
destination = "town/sf_hayden_stage"

[hayden."11:17am"]
destination = "town/sf_hayden_booth"

[hayden."8:02pm"]
destination = "haydens_house/Couch Seat Right"
on_arrival_actions = [{ activity = "drink" }]

# hemlock
[hemlock."6:00am"]
destination = "town/sf_hemlock_play"
on_arrival_actions = [{ animation = "lute_play" }]

[hemlock."11:56am"]
destination = "town/sf_hemlock_duet"
on_arrival_actions = [{ animation = "lute_play" }]

[hemlock."4:10pm"]
destination = "town/sf_hemlock_play"
on_arrival_actions = [{ animation = "lute_play" }]

[hemlock."8:32pm"]
destination = "inn/Kid Drop Off"
on_arrival_actions = [{ routine = "inn_solo_bartend" }]

[hemlock."1:43am"]
destination = "jo_and_hemlocks_room/Hemlock Wake Point"

# henrietta
[henrietta."6:00am"]
destination = "town/sf_henrietta_stage"

[henrietta."11:18am"]
destination = "town/sf_henrietta_booth"

[henrietta."8:01pm"]
destination = "haydens_house/Hayden Kitchen"

# holt
[holt."6:00am"]
destination = "town/sf_holt_booth"

[holt."3:12pm"]
destination = "town/sf_nora_booth"

[holt."8:05pm"]
destination = "general_store_home/Upper Couch Right Seat"
on_arrival_actions = [{ activity = "drink" }]

# josephine
[josephine."6:00am"]
destination = "town/sf_josephine_booth"

[josephine."8:45pm"]
destination = "town/sf_maple_booth"

[josephine."9:43pm"]
destination = "inn/Top-Middle Bar Seat"
on_arrival_actions = [{ activity = "order_drink" }]

[josephine."1:42am"]
destination = "jo_and_hemlocks_room/Jo Wake Point"

# juniper
[juniper."6:00am"]
destination = "town/sf_juniper_chat"

[juniper."12:03pm"]
destination = "town/sf_juniper_stage"

[juniper."7:31pm"]
destination = "bathhouse/Cauldron 3"

# landen
[landen."6:00am"]
destination = "town/sf_landen_booth"

[landen."12:52pm"]
destination = "town/sf_valen_chat"

[landen."8:54pm"]
destination = "landens_house_f2/Landen Wake Point"

# luc
[luc."6:00am"]
destination = "town/sf_luc_booth"

[luc."3:45pm"]
destination = "town/sf_hayden_stage"

[luc."8:34pm"]
destination = "lucs_room/Luc Bed"

# maple
[maple."6:00am"]
destination = "town/sf_maple_booth"

[maple."8:46pm"]
destination = "maples_room/Maple Wake Point"

# march
[march."6:00am"]
destination = "town/sf_march_chat"

[march."12:59pm"]
destination = "town/sf_henrietta_stage"

[march."7:13pm"]
destination = "town/sf_march_booth"

[march."8:45pm"]
destination = "blacksmith_room_left/March Bed"

# nora
[nora."6:00am"]
destination = "town/sf_nora_booth"

[nora."3:11pm"]
destination = "town/sf_adeline_booth"

[nora."8:04pm"]
destination = "town/sf_nora_booth"

[nora."9:55pm"]
destination = "general_store_home/Armchair"
on_arrival_actions = [{ activity = "drink" }]

# olric
[olric."6:00am"]
destination = "town/sf_olric_chat"

[olric."2:22pm"]
destination = "town/sf_landen_booth"

[olric."9:15pm"]
destination = "blacksmith_room_right/Olric Wake Point"

# reina
[reina."6:00am"]
destination = "town/sf_reina_stage"

[reina."12:13pm"]
destination = "town/sf_adeline_booth"

[reina."3:08pm"]
destination = "town/sf_dell_booth"

[reina."8:23pm"]
destination = "reinas_room/Reina Wake Point"

# ryis
[ryis."6:00am"]
destination = "town/sf_ryis_stage"

[ryis."3:14pm"]
destination = "town/sf_olric_chat"

[ryis."9:12pm"]
destination = "landens_house_f2/Ryis Wake Point"

# terithia
[terithia."6:00am"]
destination = "town/sf_terithia_chat"

[terithia."12:27pm"]
destination = "town/sf_terithia_stage"

[terithia."5:12pm"]
destination = "town/sf_terithia_booth"

[terithia."9:56pm"]
destination = "manor_house_dining_room/Table Left Seat 2"
on_arrival_actions = [{ activity = "drink" }]

# valen
[valen."6:00am"]
destination = "town/sf_valen_chat"

[valen."12:28pm"]
destination = "town/sf_terithia_booth"

[valen."4:55pm"]
destination = "town/sf_balor_booth"

[valen."8:31pm"]
destination = "clinic_f2/Valen Wake Point"
