requires = [
	{ weather = "pleasant" },
	{ caldarus_seridia_town = true },
	{ seridia_is_human = true },
	{ seridia_counter = 2 },
	{ cutscene_seen_repair_the_summit_stairs = true, ignore_priority = true }
]

# Seridia
[seridia."6:00am"]
destination = "seridias_house/Seridia Wake Point"

[seridia."6:12am"]
destination = "seridias_house/seridias_house_routine_entrance_south"
on_arrival_actions = [{ routine = "seridia_coffee_making" }]

[seridia."10:11am"]
destination = "summit/seridia_summit"

[seridia."4:52pm"]
destination = "seridias_house/Seridia Desk Chair"
on_arrival_actions = [{ animation = "write_sit" }]

[seridia."10:12pm"]
destination = "seridias_house_back/Seridia Throne"
on_arrival_actions = [{ activity = "drink" }]
on_departure_writes = [{ seridia_counter = 0 }]