requires = [
	{ weather = "pleasant" },
	{ caldarus_seridia_town = true },
	{ seridia_is_human = true },
	{ seridia_counter = 1 }
]

# Seridia
[seridia."6:00am"]
destination = "seridias_house/Seridia Wake Point"

[seridia."6:18am"]
destination = "seridias_house/spell_cast_1"
on_arrival_actions = [{ routine = "seridia_spell_cast" }]
on_arrival_writes = [{ seridia_casting_spells = true }]
on_departure_writes = [{ seridia_casting_spells = false }]

[seridia."9:48am"]
destination = "seridias_house/spell_cast_1"
on_arrival_actions = [{ routine = "seridia_coffee_making" }]

[seridia."1:34pm"]
destination = "western_ruins/western_ruins_digsite_routine_entrance"
on_arrival_actions = [{ routine = "seridia_dig_site_wander" }]

[seridia."6:17pm"]
destination = "western_ruins/western_ruins_digsite_routine_exit"
on_arrival_actions = [{ routine = "seridia_western_ruins_writing" }]

[seridia."9:32pm"]
destination = "seridias_house_back/seridias_house_back_routine_entrance"
on_arrival_actions = [{ routine = "seridia_gold" }]

[seridia."12:44am"]
destination = "seridias_house_back/Seridia Throne"
on_arrival_actions = [{ activity = "drink" }]
on_departure_writes = [{ seridia_counter = 2 }]
