[adeline_two_hearts]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "neutral"
local = "[Ari], you came!"
next = "1"

[adeline_two_hearts.1]
speaker = "elsie"
portrait = "neutral"
local = "Welcome to the party, dear!"
next = "2"

[adeline_two_hearts.2]
speaker = "eiland"
portrait = "neutral"
local = "Oh no, I hope Adeline didn't bully you into this, [Ari]."
next = "3"

[adeline_two_hearts.3]
speaker = "adeline"
portrait = "think"
local = "Nonsense! Not all of us are as averse to paperwork as you, Eiland. Right, [Ari]?"
prompts = [
	{ local = "I love the smell of drying ink!", next = "4" },
	{ local = "Well, I guess I'm about to find out!", next = "5" },
]

[adeline_two_hearts.4]
speaker = "adeline"
portrait = "happy"
effect = "surprise"
local = "Oh! Me too!"
next = "6"

[adeline_two_hearts.5]
speaker = "adeline"
portrait = "happy"
local = "I'm sure you'll have a great time!"
next = "6"

[adeline_two_hearts.6]
speaker = "adeline"
portrait = "neutral"
local = "Let me take you around the room. Great Aunt Elsie is working on applying for grants from the Capital..."
next = "7"

[adeline_two_hearts.7]
speaker = "elsie"
portrait = "wink"
local = "There's certainly a trick to getting what you want out of those nobles. Unfortunately for them, I've had plenty of practice!"
next = "8"

[adeline_two_hearts.8]
speaker = "adeline"
portrait = "neutral"
local = "My dear brother is taking care of large excavation site procedural paperwork..."
next = "9"

[adeline_two_hearts.9]
speaker = "eiland"
portrait = "mad"
local = "Honestly, with the archaic way these forms have been written, you'd think they were historical artifacts themselves!"
next = "10"

[adeline_two_hearts.10]
speaker = "adeline"
portrait = "happy"
local = "And I'm handling our tax documents for the season! Sorry to hog the really fun work, everyone!"
next = "11"

[adeline_two_hearts.11]
speaker = "adeline"
portrait = "neutral"
local = "[Ari], I'd like you to come over here and review the work we've already done. It'll give you a good overview and make sure we haven't made any mistakes!"
next = "12"

[adeline_two_hearts.12]
speaker = "eiland"
portrait = "think"
local = "But you've already double checked everything, Adeline."
next = "13"

[adeline_two_hearts.13]
speaker = "adeline"
portrait = "sly"
local = "Nothing better than a triple check, it's so satisfying!"
prompts = [
	{ local = "Wow, thanks Adeline!", next = "14" },
	{ local = "Wow, uh, thanks Adeline...", next = "15" },
]

[adeline_two_hearts.14]
speaker = "adeline"
portrait = "blush"
local = "Oh, [Ari]! You're very welcome!"
next = "16"

[adeline_two_hearts.15]
speaker = "adeline"
portrait = "happy"
local = "Haha, well, I appreciate that you're willing to give it a try."
next = "16"

[adeline_two_hearts.16]
speaker = "adeline"
portrait = "neutral"
local = "And when we're done, I've ordered up a special tray of treats from the Inn to celebrate! Whoever finishes first gets first pick!"
next = "17"

[adeline_two_hearts.17]
speaker = "eiland"
portrait = "happy"
local = "Well, why didn't you say so earlier!"
