priority = "max"
requires = [{ rjt_active = true }]
start_writes = [{ rjt_start_write = true }]
end_writes = [{ rjt_end_write = true }]

[juniper."6:00am"]
destination = "bathhouse_bedroom/Crystal Ball Seat"
on_departure_writes = [{ rjt_a_d = true }]

[juniper."8:00am"]
destination = "bathhouse/Cauldron 2"
on_arrival_writes = [{ rjt_b_a = true }]
on_departure_writes = [{ rjt_b_d = true }]

[juniper."10:30am"]
destination = "inn/Top Bar Seat"
on_arrival_writes = [{ rjt_c_a = true }]
on_departure_writes = [{ rjt_c_d = true }]

[juniper."2:00pm"]
destination = "town/Fountain Meetcute 1"
on_arrival_writes = [{ rjt_d_a = true }]
on_departure_writes = [{ rjt_d_d = true }]

[juniper."8:00pm"]
destination = "bathhouse/Cauldron 2"
on_arrival_writes = [{ rjt_e_a = true }]
on_departure_writes = [{ rjt_e_d = true }]

[juniper."1:00am"]
destination = "bathhouse_bedroom/Crystal Ball Seat"
on_arrival_writes = [{ rjt_f_a = true }]
