[great_bird_1_caldarus]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Caldarus."
next = "1"

[great_bird_1_caldarus.1]
speaker = "caldarus"
portrait = "serious_blush"
local = "[Ari]... It appears that we are in the presence of the Great Bird."
next = "2"

[great_bird_1_caldarus.2]
speaker = "caldarus"
portrait = "unsure_special"
local = "Could this perhaps mean...?"
next = "3"

[great_bird_1_caldarus.3]
speaker = "great_bird"
portrait = "neutral"
local = "Your senses are sharp, Caldarus!"
next = "4"

[great_bird_1_caldarus.4]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "5"

[great_bird_1_caldarus.5]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "6"

[great_bird_1_caldarus.6]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "7"

[great_bird_1_caldarus.7]
speaker = "caldarus"
portrait = "embarrassed"
local = "What do you think would be best, [Ari]?"
prompts = [
    { local = "The Great Bird can bring the baby to us!", next = "8" },
    { local = "Actually I...", next = "15" }
]

[great_bird_1_caldarus.8]
speaker = "caldarus"
portrait = "caring_special"
local = "Yes, that seems a wise choice."
writes = [{ utero_choice = "stork" }]
next = "9"

[great_bird_1_caldarus.9]
speaker = "caldarus"
portrait = "embarrassed"
local = "If you would, Great Bird..."
next = "10"

[great_bird_1_caldarus.10]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "11"

[great_bird_1_caldarus.11]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "12"

[great_bird_1_caldarus.12]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "13"

[great_bird_1_caldarus.13]
speaker = "caldarus"
portrait = "caring_special"
local = "[Ari]... A child of our very own!"
next = "14"

[great_bird_1_caldarus.14]
speaker = "caldarus"
portrait = "laugh_special"
effect = "cheery"
local = "Can you believe it? I find myself lost for words..."

[great_bird_1_caldarus.15]
speaker = "caldarus"
portrait = "unsure_special"
local = "Yes...?"
prompts = [
    { local = "I'd like to carry the baby myself.", next = "16" },
    { local = "Nevermind, the Great Bird can deliver the baby!", next = "25" }
]

[great_bird_1_caldarus.16]
speaker = "caldarus"
portrait = "embarrassed"
local = "Are you certain, [Ari]?"
writes = [{ utero_choice = "ari" }]
next = "17"

[great_bird_1_caldarus.17]
speaker = "caldarus"
portrait = "unsure_special"
local = "You truly wish to carry our child?"
next = "18"

[great_bird_1_caldarus.18]
speaker = "caldarus"
portrait = "laugh_special"
local = "Then I shall make every effort to ensure your health and comfort."
next = "19"

[great_bird_1_caldarus.19]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "20"

[great_bird_1_caldarus.20]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "21"

[great_bird_1_caldarus.21]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "22"

[great_bird_1_caldarus.22]
speaker = "great_bird"
portrait = "happy"
local = "[spouse], be sure to show [Ari] plenty of extra care during this time."
next = "23"

[great_bird_1_caldarus.23]
speaker = "caldarus"
portrait = "laugh_special"
local = "Understood!"
next = "24"

[great_bird_1_caldarus.24]
speaker = "caldarus"
portrait = "embarrassed"
effect = "cheery"
local = "Fear not, [Ari]. I shall ensure your every desire is fullfilled."

[great_bird_1_caldarus.25]
speaker = "caldarus"
portrait = "caring_special"
local = "Yes, that seems a wise choice."
writes = [{ utero_choice = "stork" }]
next = "26"

[great_bird_1_caldarus.26]
speaker = "caldarus"
portrait = "embarrassed"
local = "If you would, Great Bird..."
next = "27"

[great_bird_1_caldarus.27]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "28"

[great_bird_1_caldarus.28]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "29"

[great_bird_1_caldarus.29]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "30"

[great_bird_1_caldarus.30]
speaker = "caldarus"
portrait = "caring_special"
local = "[Ari]... A child of our very own!"
next = "31"

[great_bird_1_caldarus.31]
speaker = "caldarus"
portrait = "laugh_special"
effect = "cheery"
local = "Can you believe it? I find myself lost for words..."
