[great_bird_1_adeline]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Adeline."
next = "1"

[great_bird_1_adeline.1]
speaker = "adeline"
portrait = "think"
local = "Um, [Ari]... are we dreaming?"
next = "2"

[great_bird_1_adeline.2]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite..."
next = "3"

[great_bird_1_adeline.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_adeline.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_adeline.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_adeline.6]
speaker = "adeline"
portrait = "embarrassed"
local = "Um, well..."
next = "7"

[great_bird_1_adeline.7]
speaker = "adeline"
portrait = "happy_blush"
local = "Actually, I think it might be nice to carry the baby myself. What do you think, [Ari]?"
prompts = [
    { local = "That sounds great!", next = "8" },
    { local = "Actually I...", next = "14" }
]

[great_bird_1_adeline.8]
speaker = "adeline"
portrait = "blush"
local = "Oh! I'm so glad! This is so exciting..."
writes = [{ utero_choice = "spouse" }]
next = "9"


[great_bird_1_adeline.9]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Adeline will carry the child."
next = "10"

[great_bird_1_adeline.10]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "11"

[great_bird_1_adeline.11]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Adeline plenty of extra care during this time, [Ari]..."
next = "12"

[great_bird_1_adeline.12]
speaker = "adeline"
portrait = "blush"
local = "A child of our own. Can you believe it?"
next = "13"

[great_bird_1_adeline.13]
speaker = "adeline"
portrait = "happy_blush"
effect = "cheery"
local = "I'm so happy!"

[great_bird_1_adeline.14]
speaker = "adeline"
portrait = "blush"
local = "What is it? Should we try another way?"
prompts = [
    { local = "Let's have the Great Bird bring the baby.", next = "15" },
    { local = "I'd like to carry the baby myself.", next = "22" },
    { local = "Actually, you can carry the baby after all.", next = "31" }
]

[great_bird_1_adeline.15]
speaker = "adeline"
portrait = "happy_blush"
local = "Oh, of course! If that's what you prefer, I'm fine with that."
writes = [{ utero_choice = "stork" }]
next = "16"

[great_bird_1_adeline.16]
speaker = "adeline"
portrait = "blush"
local = "Great Bird, will you deliver the baby to us?"
next = "17"

[great_bird_1_adeline.17]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "18"

[great_bird_1_adeline.18]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "19"

[great_bird_1_adeline.19]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "20"

[great_bird_1_adeline.20]
speaker = "adeline"
portrait = "happy_blush"
local = "This is so exciting, [Ari]! We're going to be parents!"
next = "21"

[great_bird_1_adeline.21]
speaker = "adeline"
portrait = "embarrassed"
effect = "cheery"
local = "I'm so happy..."

[great_bird_1_adeline.22]
speaker = "adeline"
portrait = "happy_blush"
local = "Oh, of course!"
writes = [{ utero_choice = "ari" }]
next = "23"

[great_bird_1_adeline.23]
speaker = "adeline"
portrait = "embarrassed"
local = "If that's what you prefer, then I'm all for it!"
next = "24"

[great_bird_1_adeline.24]
speaker = "adeline"
portrait = "blush"
local = "I'll do my best to support you through your pregnancy, [Ari]."
next = "25"

[great_bird_1_adeline.25]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "26"

[great_bird_1_adeline.26]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "27"

[great_bird_1_adeline.27]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "28"

[great_bird_1_adeline.28]
speaker = "great_bird"
portrait = "happy"
local = "Adeline, be sure to show [Ari] plenty of extra care during this time."
next = "29"

[great_bird_1_adeline.29]
speaker = "adeline"
portrait = "happy_blush"
local = "I will, I promise!"
next = "30"

[great_bird_1_adeline.30]
speaker = "adeline"
portrait = "embarrassed"
effect = "cheery"
local = "There's nothing more important to me..."


[great_bird_1_adeline.31]
speaker = "adeline"
portrait = "blush"
local = "Oh! I'm so glad! This is so exciting..."
writes = [{ utero_choice = "spouse" }]
next = "32"

[great_bird_1_adeline.32]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Adeline will carry the child."
next = "33"

[great_bird_1_adeline.33]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "34"

[great_bird_1_adeline.34]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Adeline plenty of extra care during this time, [Ari]..."
next = "35"

[great_bird_1_adeline.35]
speaker = "adeline"
portrait = "blush"
local = "A child of our own. Can you believe it?"
next = "36"

[great_bird_1_adeline.36]
speaker = "adeline"
portrait = "happy_blush"
effect = "cheery"
local = "I'm so happy!"
