[great_bird_0]
kind = "gameplay_triggered"
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari]."
next = "1"

[great_bird_0.1]
speaker = "great_bird"
portrait = "neutral_closed"
local = "Many years lie between this meeting and our last."
next = "2"

[great_bird_0.2]
speaker = "great_bird"
portrait = "neutral"
local = "You have grown well."
next = "3"

[great_bird_0.3]
speaker = "great_bird"
portrait = "neutral"
local = "No, you would not remember me."
next = "4"

[great_bird_0.4]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I am but a guide, ushering forth those who wish to be born into this world."
next = "5"

[great_bird_0.5]
speaker = "great_bird"
portrait = "neutral"
local = "Forgive me for being direct, [Ari], but I come to you now on such business."
next = "6"

[great_bird_0.6]
speaker = "great_bird"
portrait = "neutral"
local = "I am not sure whether you have ever considered starting a family..."
next = "7"

[great_bird_0.7]
speaker = "great_bird"
portrait = "neutral_closed"
local = "And I am not here to influence that decision either way."
next = "8"

[great_bird_0.8]
speaker = "great_bird"
portrait = "neutral"
local = "I am simply here to offer my guidance, should you require it."
next = "9"

[great_bird_0.9]
speaker = "great_bird"
portrait = "neutral"
local = "Please, take this."
next = "10"

[great_bird_0.10]
speaker = "great_bird"
portrait = "neutral"
local = "In the event that you desire to raise a $Child$, you will first need to $discuss the matter with [spouse]$."
next = "11"

[great_bird_0.11]
speaker = "great_bird"
portrait = "neutral_closed"
local = "It is possible that you will forget this conversation come morning..."
next = "12"

[great_bird_0.12]
speaker = "great_bird"
portrait = "neutral"
local = "To prevent that, my $Mystical Feather$ will remain with you in the waking world."
next = "13"

[great_bird_0.13]
speaker = "great_bird"
portrait = "neutral_closed"
local = "As long as you $hold this feather in your hand$, you are sure to remember this conversation. Keep it with you, if you plan to $discuss starting a family with [spouse]$."
next = "14"

[great_bird_0.14]
speaker = "great_bird"
portrait = "neutral"
local = "That concludes our business for tonight. Fare thee well, [Ari]."
prompts = [
    { local = "Goodbye! It was nice to see you!", next = "15" },
    { local = "Bye Mister Stork! Thanks for coming by!", next = "16" }
]

[great_bird_0.15]
speaker = "great_bird"
portrait = "happy"
local = "So it was..."
next = "17"

[great_bird_0.16]
speaker = "great_bird"
portrait = "neutral_closed"
local = """I am neither a "mister" nor a "stork", but I appreciate the sentiment nonetheless."""
next = "17"

[great_bird_0.17]
speaker = "great_bird"
portrait = "neutral"
local = "Until we meet again."
