[great_bird_1_celine]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Celine."
next = "1"

[great_bird_1_celine.1]
speaker = "celine"
portrait = "think"
local = "Um, [Ari]... this isn't a dream is it?"
next = "2"

[great_bird_1_celine.2]
speaker = "great_bird"
portrait = "neutral"
local = "My, you are quite observant!"
next = "3"

[great_bird_1_celine.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_celine.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_celine.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_celine.6]
speaker = "celine"
portrait = "blush_closed_eyes"
effect = "surprise"
local = "Oh!"
next = "7"

[great_bird_1_celine.7]
speaker = "celine"
portrait = "blush_special"
local = "I can carry the baby! I helped take care of Mom when she was pregnant with Dell, so I know what to expect!"
next = "8"

[great_bird_1_celine.8]
speaker = "celine"
portrait = "embarrassed"
local = "But this isn't just my decision... What do you think, [Ari]?"
prompts = [
    { local = "That sounds great!", next = "9" },
    { local = "Actually I...", next = "16" }
]

[great_bird_1_celine.9]
speaker = "celine"
portrait = "blush"
local = "Perfect, I'm so glad you think so!"
writes = [{ utero_choice = "spouse" }]
next = "10"

[great_bird_1_celine.10]
speaker = "celine"
portrait = "embarrassed"
local = "I'm so happy..."
next = "11"


[great_bird_1_celine.11]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Celine will carry the child."
next = "12"

[great_bird_1_celine.12]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "13"

[great_bird_1_celine.13]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Celine plenty of extra care during this time, [Ari]..."
next = "14"

[great_bird_1_celine.14]
speaker = "celine"
portrait = "blush"
local = "Can you believe it, [Ari]?"
next = "15"

[great_bird_1_celine.15]
speaker = "celine"
portrait = "blush_special"
effect = "cheery"
local = "We're going to have a baby!"

[great_bird_1_celine.16]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "What is it? Should we try another way?"
prompts = [
    { local = "Let's have the Great Bird bring the baby.", next = "17" },
    { local = "I'd like to carry the baby myself.", next = "24" },
    { local = "Actually, you can carry the baby after all.", next = "33" }
]

[great_bird_1_celine.17]
speaker = "celine"
portrait = "embarrassed"
local = "Of course! That sounds good to me!"
writes = [{ utero_choice = "stork" }]
next = "18"

[great_bird_1_celine.18]
speaker = "celine"
portrait = "blush"
local = "Great Bird, would you mind bringing the baby to us?"
next = "19"

[great_bird_1_celine.19]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "20"

[great_bird_1_celine.20]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "21"

[great_bird_1_celine.21]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "22"

[great_bird_1_celine.22]
speaker = "celine"
portrait = "blush"
local = "Can you believe it, [Ari]?"
next = "23"

[great_bird_1_celine.23]
speaker = "celine"
portrait = "blush_special"
effect = "cheery"
local = "We're going to have a baby!"

[great_bird_1_celine.24]
speaker = "celine"
portrait = "blush"
local = "Of course!"
writes = [{ utero_choice = "ari" }]
next = "25"

[great_bird_1_celine.25]
speaker = "celine"
portrait = "embarrassed"
local = "If that's what you want, [Ari], let's do it!"
next = "26"

[great_bird_1_celine.26]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "I'll do everything I can to support you through your pregnancy."
next = "27"

[great_bird_1_celine.27]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "28"

[great_bird_1_celine.28]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "29"

[great_bird_1_celine.29]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "30"

[great_bird_1_celine.30]
speaker = "great_bird"
portrait = "happy"
local = "Celine, be sure to show [Ari] plenty of extra care during this time."
next = "31"

[great_bird_1_celine.31]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "I will! I promise!"
next = "32"

[great_bird_1_celine.32]
speaker = "celine"
portrait = "blush_special"
effect = "cheery"
local = "Can you believe it, [Ari]? We're going to have a baby!"


[great_bird_1_celine.33]
speaker = "celine"
portrait = "blush"
local = "I'm so glad!"
writes = [{ utero_choice = "spouse" }]
next = "34"

[great_bird_1_celine.34]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Celine will carry the child."
next = "35"

[great_bird_1_celine.35]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "36"

[great_bird_1_celine.36]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Celine plenty of extra care during this time, [Ari]..."
next = "37"

[great_bird_1_celine.37]
speaker = "celine"
portrait = "blush"
local = "Can you believe it, [Ari]?"
next = "38"

[great_bird_1_celine.38]
speaker = "celine"
portrait = "blush_special"
effect = "cheery"
local = "We're going to have a baby!"
