[great_bird_1_march]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], March."
next = "1"

[great_bird_1_march.1]
speaker = "march"
portrait = "eight_heart_think"
local = "Where are we, [Ari]? Is this... a dream?"
next = "2"

[great_bird_1_march.2]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite..."
next = "3"

[great_bird_1_march.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_march.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_march.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_march.6]
speaker = "march"
portrait = "eight_heart_flustered"
local = "A child of our own..."
next = "7"

[great_bird_1_march.7]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "That little star up there?"
next = "8"

[great_bird_1_march.8]
speaker = "march"
portrait = "drunk"
local = "What do you think, [Ari]?"
prompts = [
    { local = "The Great Bird can bring the baby to us!", next = "9" },
    { local = "Actually I...", next = "16" }
]

[great_bird_1_march.9]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "Yeah! That makes sense!"
writes = [{ utero_choice = "stork" }]
next = "10"

[great_bird_1_march.10]
speaker = "march"
portrait = "eight_heart_blush"
local = "If you don't mind, Great Bird..."
next = "11"

[great_bird_1_march.11]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "12"

[great_bird_1_march.12]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "13"

[great_bird_1_march.13]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "14"

[great_bird_1_march.14]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "We're going to be parents, [Ari]!"
next = "15"

[great_bird_1_march.15]
speaker = "march"
portrait = "drunk"
effect = "cheery"
local = "We're going to have our own family!"

[great_bird_1_march.16]
speaker = "march"
portrait = "eight_heart_blush"
local = "What is it...?"
prompts = [
    { local = "I'd like to carry the baby myself.", next = "17" },
    { local = "Nevermind, the Great Bird can deliver the baby!", next = "31" }
]

[great_bird_1_march.17]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "[Ari]..."
writes = [{ utero_choice = "ari" }]
next = "18"

[great_bird_1_march.18]
speaker = "march"
portrait = "eight_heart_flustered"
local = "You're sure-"
next = "19"

[great_bird_1_march.19]
speaker = "march"
portrait = "tsundere"
local = "Um."
next = "20"

[great_bird_1_march.20]
speaker = "march"
portrait = "eight_heart_blush"
local = "You're sure you want to carry our child?"
next = "21"

[great_bird_1_march.21]
speaker = "march"
portrait = "drunk"
local = "Of course I'm okay with that!"
next = "22"

[great_bird_1_march.22]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "Just promise me you'll take things easy while you're expecting, okay?"
next = "23"

[great_bird_1_march.23]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "24"

[great_bird_1_march.24]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "25"

[great_bird_1_march.25]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "26"

[great_bird_1_march.26]
speaker = "great_bird"
portrait = "happy"
local = "[spouse], be sure to show [Ari] plenty of extra care during this time."
next = "27"

[great_bird_1_march.27]
speaker = "march"
portrait = "tsundere"
local = "What sort of guy do you think I am?"
next = "28"

[great_bird_1_march.28]
speaker = "march"
portrait = "mad_special"
local = "Of course I'm going to take care of <he>him</he><she>her</she><they>them</they><it>it</it><none>[Ari]</none>!"
next = "29"

[great_bird_1_march.29]
speaker = "march"
portrait = "tsundere"
local = "I don't want you to doubt it for a second, [Ari]..."
next = "30"

[great_bird_1_march.30]
speaker = "march"
portrait = "eight_heart_happy_blush"
effect = "cheery"
local = "I'd do anything for you and our baby!"

[great_bird_1_march.31]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "Yeah! That makes sense!"
writes = [{ utero_choice = "stork" }]
next = "32"

[great_bird_1_march.32]
speaker = "march"
portrait = "eight_heart_blush"
local = "If you don't mind, Great Bird..."
next = "33"

[great_bird_1_march.33]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "34"

[great_bird_1_march.34]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "35"

[great_bird_1_march.35]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "36"

[great_bird_1_march.36]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "We're going to be parents, [Ari]!"
next = "37"

[great_bird_1_march.37]
speaker = "march"
portrait = "drunk"
effect = "cheery"
local = "We're going to have our own family!"
