[great_bird_1_valen]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Valen."
next = "1"

[great_bird_1_valen.1]
speaker = "valen"
portrait = "think"
local = "[Ari]... it would appear we're dreaming."
next = "2"

[great_bird_1_valen.2]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite."
next = "3"

[great_bird_1_valen.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_valen.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_valen.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_valen.6]
speaker = "valen"
portrait = "embarrassed"
local = "Do you mean you would fly the baby over to us? While it's a generous offer..."
next = "7"

[great_bird_1_valen.7]
speaker = "valen"
portrait = "happy_blush"
local = "My curiosity has the better of me. I think I might prefer to carry the child myself."
next = "8"

[great_bird_1_valen.8]
speaker = "valen"
portrait = "embarrassed"
local = "Would that be okay with you, [Ari]?"
prompts = [
    { local = "That sounds great!", next = "9" },
    { local = "Actually I...", next = "16" }
]

[great_bird_1_valen.9]
speaker = "valen"
portrait = "happy_blush"
local = "You think so?"
writes = [{ utero_choice = "spouse" }]
next = "10"

[great_bird_1_valen.10]
speaker = "valen"
portrait = "embarrassed"
local = "This is so exciting!"
next = "11"

[great_bird_1_valen.11]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Valen will carry the child."
next = "12"

[great_bird_1_valen.12]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "13"

[great_bird_1_valen.13]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Valen plenty of extra care during this time, [Ari]..."
next = "14"

[great_bird_1_valen.14]
speaker = "valen"
portrait = "neutral_blush"
local = "How miraculous, [Ari]!"
next = "15"

[great_bird_1_valen.15]
speaker = "valen"
portrait = "happy_blush"
effect = "cheery"
local = "A child of our own... I'm looking forward to it."

[great_bird_1_valen.16]
speaker = "valen"
portrait = "neutral_blush"
local = "Go on, please."
prompts = [
    { local = "Let's have the Great Bird bring the baby.", next = "17" },
    { local = "I'd like to carry the baby myself.", next = "24" },
    { local = "Actually, you can carry the baby after all.", next = "34" }
]

[great_bird_1_valen.17]
speaker = "valen"
portrait = "happy_blush"
local = "Well, if you think it would be best..."
writes = [{ utero_choice = "stork" }]
next = "18"

[great_bird_1_valen.18]
speaker = "valen"
portrait = "embarrassed"
local = "Great Bird, would you mind bringing the baby to us?"
next = "19"

[great_bird_1_valen.19]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "20"

[great_bird_1_valen.20]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "21"

[great_bird_1_valen.21]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "22"

[great_bird_1_valen.22]
speaker = "valen"
portrait = "neutral_blush"
local = "How miraculous, [Ari]!"
next = "23"

[great_bird_1_valen.23]
speaker = "valen"
portrait = "happy_blush"
effect = "cheery"
local = "A child of our own... I'm looking forward to it."

[great_bird_1_valen.24]
speaker = "valen"
portrait = "happy_blush"
local = "Oh, [Ari]! Of course you can!"
writes = [{ utero_choice = "ari" }]
next = "25"

[great_bird_1_valen.25]
speaker = "valen"
portrait = "embarrassed"
local = "If that's what you want, I'm all for it."
next = "26"

[great_bird_1_valen.26]
speaker = "valen"
portrait = "caring_special"
local = "I'll do everything I can to help you throughout your pregnancy."
next = "27"

[great_bird_1_valen.27]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "28"

[great_bird_1_valen.28]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "29"

[great_bird_1_valen.29]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "30"

[great_bird_1_valen.30]
speaker = "great_bird"
portrait = "happy"
local = "Valen, be sure to show [Ari] plenty of extra care during this time."
next = "31"

[great_bird_1_valen.31]
speaker = "valen"
portrait = "caring_special"
local = "I certainly will."
next = "32"

[great_bird_1_valen.32]
speaker = "valen"
portrait = "neutral_blush"
local = "How miraculous, [Ari]!"
next = "33"

[great_bird_1_valen.33]
speaker = "valen"
portrait = "happy_blush"
effect = "cheery"
local = "A child of our own... I'm looking forward to it."

[great_bird_1_valen.34]
speaker = "valen"
portrait = "happy_blush"
local = "Are you sure?"
writes = [{ utero_choice = "spouse" }]
next = "35"

[great_bird_1_valen.35]
speaker = "valen"
portrait = "embarrassed"
local = "This is so exciting!"
next = "36"

[great_bird_1_valen.36]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Valen will carry the child."
next = "37"

[great_bird_1_valen.37]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "38"

[great_bird_1_valen.38]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Valen plenty of extra care during this time, [Ari]..."
next = "39"

[great_bird_1_valen.39]
speaker = "valen"
portrait = "neutral_blush"
local = "How miraculous, [Ari]!"
next = "40"

[great_bird_1_valen.40]
speaker = "valen"
portrait = "happy_blush"
effect = "cheery"
local = "A child of our own... I'm looking forward to it."
