[great_bird_1_eiland]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Eiland."
next = "1"

[great_bird_1_eiland.1]
speaker = "eiland"
portrait = "think"
local = "[Ari]! Is this a dream? Is that... a dragon?"
next = "2"

[great_bird_1_eiland.2]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite..."
next = "3"

[great_bird_1_eiland.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_eiland.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_eiland.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_eiland.6]
speaker = "eiland"
portrait = "embarrassed"
local = "What do you think, [Ari]? Do you have a preference?"
prompts = [
    { local = "The Great Bird can bring the baby to us!", next = "7" },
    { local = "Actually I...", next = "13" }
]

[great_bird_1_eiland.7]
speaker = "eiland"
portrait = "happy_blush"
local = "Yes, that is a reasonable choice!"
writes = [{ utero_choice = "stork" }]
next = "8"

[great_bird_1_eiland.8]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "9"

[great_bird_1_eiland.9]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "10"

[great_bird_1_eiland.10]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "11"

[great_bird_1_eiland.11]
speaker = "eiland"
portrait = "hope_special"
local = "I can hardly believe it, [Ari]!"
next = "12"

[great_bird_1_eiland.12]
speaker = "eiland"
portrait = "happy_blush"
effect = "cheery"
local = "We're going to have a baby! I'm so happy..."

[great_bird_1_eiland.13]
speaker = "eiland"
portrait = "hope_special"
local = "Do you mean...?"
prompts = [
    { local = "I'd like to carry the baby myself.", next = "14" },
    { local = "Nevermind, the Great Bird can deliver the baby!", next = "23" }
]

[great_bird_1_eiland.14]
speaker = "eiland"
portrait = "embarrassed"
local = "Really, [Ari]?"
writes = [{ utero_choice = "ari" }]
next = "15"

[great_bird_1_eiland.15]
speaker = "eiland"
portrait = "bashful"
local = "Are you sure it won't be too much for you?"
next = "16"

[great_bird_1_eiland.16]
speaker = "eiland"
portrait = "hope_special"
local = "In that case, I'll do everything in my power to ensure your health and comfort."
next = "17"

[great_bird_1_eiland.17]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "18"

[great_bird_1_eiland.18]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "19"

[great_bird_1_eiland.19]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "20"

[great_bird_1_eiland.20]
speaker = "great_bird"
portrait = "happy"
local = "[spouse], be sure to show [Ari] plenty of extra care during this time."
next = "21"

[great_bird_1_eiland.21]
speaker = "eiland"
portrait = "happy_blush"
local = "I'm on it!"
next = "22"

[great_bird_1_eiland.22]
speaker = "eiland"
portrait = "embarrassed"
effect = "cheery"
local = "Just you wait, [Ari]. I'm going to make sure your every wish is granted!"

[great_bird_1_eiland.23]
speaker = "eiland"
portrait = "happy_blush"
local = "Yes, that is a reasonable choice!"
writes = [{ utero_choice = "stork" }]
next = "24"

[great_bird_1_eiland.24]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "25"

[great_bird_1_eiland.25]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "26"

[great_bird_1_eiland.26]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "27"

[great_bird_1_eiland.27]
speaker = "eiland"
portrait = "hope_special"
local = "I can hardly believe it, [Ari]!"
next = "28"

[great_bird_1_eiland.28]
speaker = "eiland"
portrait = "happy_blush"
effect = "cheery"
local = "We're going to have a baby! I'm so happy..."
