[great_bird_1_seridia]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Seridia."
next = "1"

[great_bird_1_seridia.1]
speaker = "seridia"
portrait = "smile"
local = "Greetings, old friend."
next = "2"

[great_bird_1_seridia.2]
speaker = "great_bird"
portrait = "neutral"
local = "It has been quite some time since you were last reborn into this world, Seridia! I was beginning to worry..."
next = "3"

[great_bird_1_seridia.3]
speaker = "seridia"
portrait = "closed_eyes_brow"
local = "It... is a long story. I will tell you about it another time."
next = "4"

[great_bird_1_seridia.4]
speaker = "seridia"
portrait = "blush"
local = "In any case, I expect we have other matters to discuss this evening..."
next = "5"

[great_bird_1_seridia.5]
speaker = "great_bird"
portrait = "neutral"
local = "You are correct."
next = "6"

[great_bird_1_seridia.6]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "7"

[great_bird_1_seridia.7]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "8"

[great_bird_1_seridia.8]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "9"

[great_bird_1_seridia.9]
speaker = "seridia"
portrait = "embarrassed"
local = "I would like to carry the child myself."
next = "10"

[great_bird_1_seridia.10]
speaker = "seridia"
portrait = "closed_eyes_blush"
local = "However, this is a decision we must make together. What say you, [Ari]?"
prompts = [
    { local = "That sounds great!", next = "11" },
    { local = "Actually I...", next = "18" }
]

[great_bird_1_seridia.11]
speaker = "seridia"
portrait = "sinister_blush"
local = "Excellent!"
writes = [{ utero_choice = "spouse" }]
next = "12"

[great_bird_1_seridia.12]
speaker = "seridia"
portrait = "happy_blush"
local = "I look forward to bringing forth a new life..."
next = "13"

[great_bird_1_seridia.13]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Seridia will carry the child."
next = "14"

[great_bird_1_seridia.14]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "15"

[great_bird_1_seridia.15]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Seridia plenty of extra care during this time, [Ari]..."
next = "16"

[great_bird_1_seridia.16]
speaker = "seridia"
portrait = "happy_blush"
local = "This calls for a celebration, [Ari]!"
next = "17"

[great_bird_1_seridia.17]
speaker = "seridia"
portrait = "sinister_blush"
effect = "cheery"
local = "Our child, a new dragon, will be born to Mistria!"

[great_bird_1_seridia.18]
speaker = "seridia"
portrait = "blush"
local = "Yes?"
prompts = [
    { local = "Let's have the Great Bird bring the baby.", next = "19" },
    { local = "I'd like to carry the baby myself.", next = "26" },
    { local = "Actually, you can carry the baby after all.", next = "36" }
]

[great_bird_1_seridia.19]
speaker = "seridia"
portrait = "closed_eyes_blush"
local = "If you are certain..."
writes = [{ utero_choice = "stork" }]
next = "20"

[great_bird_1_seridia.20]
speaker = "seridia"
portrait = "blush_think"
local = "Great Bird, if you would?"
next = "21"

[great_bird_1_seridia.21]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "22"

[great_bird_1_seridia.22]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "23"

[great_bird_1_seridia.23]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "24"

[great_bird_1_seridia.24]
speaker = "seridia"
portrait = "happy_blush"
local = "This calls for a celebration, [Ari]!"
next = "25"

[great_bird_1_seridia.25]
speaker = "seridia"
portrait = "sinister_blush"
effect = "cheery"
local = "Our child, a new dragon, will be born to Mistria!"

[great_bird_1_seridia.26]
speaker = "seridia"
portrait = "sinister_blush"
local = "Ah! How careless of me."
writes = [{ utero_choice = "ari" }]
next = "27"

[great_bird_1_seridia.27]
speaker = "seridia"
portrait = "closed_eyes_blush"
local = "Of course, [Ari]. I would not deny you the joyful experience of bringing forth a life."
next = "28"

[great_bird_1_seridia.28]
speaker = "seridia"
portrait = "blush"
local = "I shall do everything in my power to ensure your pregnancy is as comfortable as possible."
next = "29"

[great_bird_1_seridia.29]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "30"

[great_bird_1_seridia.30]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "31"

[great_bird_1_seridia.31]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "32"

[great_bird_1_seridia.32]
speaker = "great_bird"
portrait = "happy"
local = "Seridia, be sure to show [Ari] plenty of extra care during this time."
next = "33"

[great_bird_1_seridia.33]
speaker = "seridia"
portrait = "blush"
local = "Certainly."
next = "34"

[great_bird_1_seridia.34]
speaker = "seridia"
portrait = "happy_blush"
local = "This calls for a celebration, [Ari]!"
next = "35"

[great_bird_1_seridia.35]
speaker = "seridia"
portrait = "sinister_blush"
effect = "cheery"
local = "Our child, a new dragon, will be born to Mistria!"

[great_bird_1_seridia.36]
speaker = "seridia"
portrait = "sinister_blush"
local = "Excellent!"
writes = [{ utero_choice = "spouse" }]
next = "37"

[great_bird_1_seridia.37]
speaker = "seridia"
portrait = "happy_blush"
local = "I look forward to bringing forth a new life..."
next = "38"

[great_bird_1_seridia.38]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Seridia will carry the child."
next = "39"

[great_bird_1_seridia.39]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "40"

[great_bird_1_seridia.40]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Seridia plenty of extra care during this time, [Ari]..."
next = "41"

[great_bird_1_seridia.41]
speaker = "seridia"
portrait = "happy_blush"
local = "This calls for a celebration, [Ari]!"
next = "42"

[great_bird_1_seridia.42]
speaker = "seridia"
portrait = "sinister_blush"
effect = "cheery"
local = "Our child, a new dragon, will be born to Mistria!"
