[great_bird_1_reina]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Reina."
next = "1"

[great_bird_1_reina.1]
speaker = "reina"
portrait = "think"
local = "Wow, would you look at all those stars!"
next = "2"

[great_bird_1_reina.2]
speaker = "reina"
portrait = "embarrassed"
local = "Are we dreaming, [Ari]...?"
next = "3"

[great_bird_1_reina.3]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite."
next = "4"

[great_bird_1_reina.4]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "5"

[great_bird_1_reina.5]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "6"

[great_bird_1_reina.6]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "7"

[great_bird_1_reina.7]
speaker = "reina"
portrait = "embarrassed"
local = "Oh!"
next = "8"

[great_bird_1_reina.8]
speaker = "reina"
portrait = "blush_think"
local = "I can carry the baby. I helped take care of Ma both times she was pregnant with my siblings, I know what to expect!"
next = "9"

[great_bird_1_reina.9]
speaker = "reina"
portrait = "embarrassed"
local = "But what do you think, [Ari]?"
prompts = [
    { local = "That sounds great!", next = "10" },
    { local = "Actually I...", next = "17" }
]

[great_bird_1_reina.10]
speaker = "reina"
portrait = "blush"
local = "I'm glad we're on the same page..."
writes = [{ utero_choice = "spouse" }]
next = "11"

[great_bird_1_reina.11]
speaker = "reina"
portrait = "blush_open_eyes"
local = "I'm so excited!"
next = "12"

[great_bird_1_reina.12]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Reina will carry the child."
next = "13"

[great_bird_1_reina.13]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "14"

[great_bird_1_reina.14]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Reina plenty of extra care during this time, [Ari]..."
next = "15"

[great_bird_1_reina.15]
speaker = "reina"
portrait = "closed_eyes_smile_blush"
local = "Can you believe it, [Ari]?"
next = "16"

[great_bird_1_reina.16]
speaker = "reina"
portrait = "blush_open_eyes"
effect = "cheery"
local = "We're going to have a baby!"

[great_bird_1_reina.17]
speaker = "reina"
portrait = "blush_open_eyes"
local = "What is it?"
prompts = [
    { local = "Let's have the Great Bird bring the baby.", next = "18" },
    { local = "I'd like to carry the baby myself.", next = "25" },
    { local = "Actually, you can carry the baby after all.", next = "34" }
]

[great_bird_1_reina.18]
speaker = "reina"
portrait = "embarrassed"
local = "Oh, of course! I'm okay with that if you prefer it."
writes = [{ utero_choice = "stork" }]
next = "19"

[great_bird_1_reina.19]
speaker = "reina"
portrait = "blush_think"
local = "Great Bird, would you mind bringing the baby to us?"
next = "20"

[great_bird_1_reina.20]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "21"

[great_bird_1_reina.21]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "22"

[great_bird_1_reina.22]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "23"

[great_bird_1_reina.23]
speaker = "reina"
portrait = "closed_eyes_smile_blush"
local = "Can you believe it, [Ari]?"
next = "24"

[great_bird_1_reina.24]
speaker = "reina"
portrait = "blush_open_eyes"
effect = "cheery"
local = "We're going to have a baby!"

[great_bird_1_reina.25]
speaker = "reina"
portrait = "blush"
local = "Of course!"
writes = [{ utero_choice = "ari" }]
next = "26"

[great_bird_1_reina.26]
speaker = "reina"
portrait = "blush_open_eyes"
local = "If that's what you would prefer to do, [Ari], let's do it."
next = "27"

[great_bird_1_reina.27]
speaker = "reina"
portrait = "closed_eyes_smile_blush"
local = "I'll do everything I can to support you through your pregnancy."
next = "28"

[great_bird_1_reina.28]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "29"

[great_bird_1_reina.29]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "30"

[great_bird_1_reina.30]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "31"

[great_bird_1_reina.31]
speaker = "great_bird"
portrait = "happy"
local = "Reina, be sure to show [Ari] plenty of extra care during this time."
next = "32"

[great_bird_1_reina.32]
speaker = "reina"
portrait = "blush_open_eyes"
local = "Of course, I will!"
next = "33"

[great_bird_1_reina.33]
speaker = "reina"
portrait = "blush"
effect = "cheery"
local = "Can you believe it, [Ari]? We're going to have a baby!"

[great_bird_1_reina.34]
speaker = "reina"
portrait = "blush"
local = "If you're sure... I'd be happy to!"
writes = [{ utero_choice = "spouse" }]
next = "35"

[great_bird_1_reina.35]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. Reina will carry the child."
next = "36"

[great_bird_1_reina.36]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "37"

[great_bird_1_reina.37]
speaker = "great_bird"
portrait = "happy"
local = "Be sure to show Reina plenty of extra care during this time, [Ari]..."
next = "38"

[great_bird_1_reina.38]
speaker = "reina"
portrait = "closed_eyes_smile_blush"
local = "Can you believe it, [Ari]?"
next = "39"

[great_bird_1_reina.39]
speaker = "reina"
portrait = "blush_open_eyes"
effect = "cheery"
local = "We're going to have a baby!"
