[great_bird_1_balor]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Balor."
next = "1"

[great_bird_1_balor.1]
speaker = "balor"
portrait = "think"
local = "[Ari]... is this a dream?"
next = "2"

[great_bird_1_balor.2]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite..."
next = "3"

[great_bird_1_balor.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_balor.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_balor.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_balor.6]
speaker = "balor"
portrait = "embarrassed"
local = "What do you think, [Ari]? What should we do?"
prompts = [
    { local = "The Great Bird can bring the baby to us!", next = "7" },
    { local = "Actually I...", next = "13" }
]

[great_bird_1_balor.7]
speaker = "balor"
portrait = "blush"
local = "Of course! That sounds like a plan to me."
writes = [{ utero_choice = "stork" }]
next = "8"

[great_bird_1_balor.8]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "9"

[great_bird_1_balor.9]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "10"

[great_bird_1_balor.10]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "11"

[great_bird_1_balor.11]
speaker = "balor"
portrait = "happy_blush"
local = "This is so exciting, [Ari]! Can you believe it?"
next = "12"

[great_bird_1_balor.12]
speaker = "balor"
portrait = "embarrassed"
effect = "cheery"
local = "We're going to have a baby of our own..."

[great_bird_1_balor.13]
speaker = "balor"
portrait = "blush"
local = "What is it? Should we try another way?"
prompts = [
    { local = "I'd like to carry the baby myself.", next = "14" },
    { local = "Nevermind, the Great Bird can deliver the baby!", next = "23" }
]

[great_bird_1_balor.14]
speaker = "balor"
portrait = "embarrassed"
local = "Really? You're sure?"
writes = [{ utero_choice = "ari" }]
next = "15"

[great_bird_1_balor.15]
speaker = "balor"
portrait = "blush"
local = "In that case..."
next = "16"

[great_bird_1_balor.16]
speaker = "balor"
portrait = "happy_blush"
local = "I promise I'll do everything I can to support you while you carry our child, [Ari]."
next = "17"

[great_bird_1_balor.17]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "18"

[great_bird_1_balor.18]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "19"

[great_bird_1_balor.19]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "20"

[great_bird_1_balor.20]
speaker = "great_bird"
portrait = "happy"
local = "[spouse], be sure to show [Ari] plenty of extra care during this time."
next = "21"

[great_bird_1_balor.21]
speaker = "balor"
portrait = "wink"
local = "Oh, absolutely!"
next = "22"

[great_bird_1_balor.22]
speaker = "balor"
portrait = "embarrassed"
effect = "cheery"
local = "Just you wait, [Ari]. I'm going to spoil you rotten!"

[great_bird_1_balor.23]
speaker = "balor"
portrait = "blush"
local = "Of course! That sounds like a plan to me."
writes = [{ utero_choice = "stork" }]
next = "24"

[great_bird_1_balor.24]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "25"

[great_bird_1_balor.25]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "26"

[great_bird_1_balor.26]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "27"

[great_bird_1_balor.27]
speaker = "balor"
portrait = "happy_blush"
local = "This is so exciting, [Ari]! Can you believe it?"
next = "28"

[great_bird_1_balor.28]
speaker = "balor"
portrait = "embarrassed"
effect = "cheery"
local = "We're going to have a baby of our own..."
