[great_bird_1_hayden]
kind = "gameplay_triggered"
writes = [{ pending_stork_visit = false }, { pregnant_line_grouping = 0 }]
speaker = "great_bird"
portrait = "neutral"
local = "Greetings, [Ari], Hayden."
next = "1"

[great_bird_1_hayden.1]
speaker = "hayden"
portrait = "think"
local = "Are we dreaming, [Ari]? And is that... a stork?"
next = "2"

[great_bird_1_hayden.2]
speaker = "great_bird"
portrait = "neutral"
local = "No, not quite... I am the Great Bird."
next = "3"

[great_bird_1_hayden.3]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I have come to you tonight to inform you that there is a $soul who wishes to join your family$."
next = "4"

[great_bird_1_hayden.4]
speaker = "great_bird"
portrait = "neutral"
local = "The moment has arrived to $choose how you would like this child to enter the world$."
next = "5"

[great_bird_1_hayden.5]
speaker = "great_bird"
portrait = "neutral_closed"
local = "I would be willing to deliver the child to you, if you would prefer it. Or perhaps..."
next = "6"

[great_bird_1_hayden.6]
speaker = "hayden"
portrait = "confident_blush"
local = "A child? A baby of our own!?"
next = "7"

[great_bird_1_hayden.7]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "Did you hear that [Ari]? What do you think?"
prompts = [
    { local = "The Great Bird can bring the baby to us!", next = "8" },
    { local = "Actually I...", next = "14" }
]

[great_bird_1_hayden.8]
speaker = "hayden"
portrait = "blush"
local = "Of course! If that's really okay with you, your birdliness..."
writes = [{ utero_choice = "stork" }]
next = "9"

[great_bird_1_hayden.9]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "10"

[great_bird_1_hayden.10]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "11"

[great_bird_1_hayden.11]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "12"

[great_bird_1_hayden.12]
speaker = "hayden"
portrait = "shy_special"
local = "[Ari]! A family of our own... Can you believe it?"
next = "13"

[great_bird_1_hayden.13]
speaker = "hayden"
portrait = "embarrassed"
effect = "cheery"
local = "It's a dream come true! I'm so excited!"

[great_bird_1_hayden.14]
speaker = "hayden"
portrait = "confident_blush"
local = "Yes...?"
prompts = [
    { local = "I'd like to carry the baby myself.", next = "15" },
    { local = "Nevermind, the Great Bird can deliver the baby!", next = "25" }
]

[great_bird_1_hayden.15]
speaker = "hayden"
portrait = "laugh_blush"
local = "Gya ha ha ha!"
writes = [{ utero_choice = "ari" }]
next = "16"

[great_bird_1_hayden.16]
speaker = "hayden"
portrait = "embarrassed"
local = "You're too cute!"
next = "17"

[great_bird_1_hayden.17]
speaker = "hayden"
portrait = "confident_blush"
local = "Let's make it happen."
next = "18"

[great_bird_1_hayden.18]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "There's nothing I want more than to start a family with you!"
next = "19"

[great_bird_1_hayden.19]
speaker = "great_bird"
portrait = "neutral"
local = "Wonderful, so it is decided. [Ari] will carry the child."
next = "20"

[great_bird_1_hayden.20]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "21"

[great_bird_1_hayden.21]
speaker = "great_bird"
portrait = "neutral"
local = "In $half a season$, you will welcome a new life into your home."
next = "22"

[great_bird_1_hayden.22]
speaker = "great_bird"
portrait = "happy"
local = "[spouse], be sure to show [Ari] plenty of extra care during this time."
next = "23"

[great_bird_1_hayden.23]
speaker = "hayden"
portrait = "confident_blush"
local = "You got it. Anything my [Ari] wants, <he>he</he><she>she</she><they>they</they><it>it</it><none>[Ari]</none> gets."
next = "24"

[great_bird_1_hayden.24]
speaker = "hayden"
portrait = "happy_arm_down_blush"
effect = "cheery"
local = "I can't believe it... I'm really going to be a dad!"

[great_bird_1_hayden.25]
speaker = "hayden"
portrait = "blush"
local = "Of course! If that's really okay with you, your birdliness..."
writes = [{ utero_choice = "stork" }]
next = "26"

[great_bird_1_hayden.26]
speaker = "great_bird"
portrait = "neutral"
local = "Certainly, I would be happy to."
next = "27"

[great_bird_1_hayden.27]
speaker = "great_bird"
portrait = "happy"
local = "Now it is simply a matter of time."
next = "28"

[great_bird_1_hayden.28]
speaker = "great_bird"
portrait = "neutral"
local = "I will return to deliver the child $half a season$ from now."
next = "29"

[great_bird_1_hayden.29]
speaker = "hayden"
portrait = "shy_special"
local = "Oh, [Ari]! A family of our own... Can you believe it?"
next = "30"

[great_bird_1_hayden.30]
speaker = "hayden"
portrait = "embarrassed"
effect = "cheery"
local = "It's a dream come true! I'm so excited!"
