#Animated Set

[animated_snow_globe]
	description = "Snow falls continuously within this decorative globe."
	icon_sprite = "spr_ui_item_furniture_animated_snow_globe"
	name = "Animated Snow Globe"
	object = "animated_snow_globe"
	value = { store = 10000, bin = 5000 }
	tags = ["furniture", "cottage_garden"]

[animated_bird_fountain]
	description = "This decorative fountain features a faux drinking bird."
	icon_sprite = "spr_ui_item_furniture_animated_bird_fountain"
	name = "Animated Bird Fountain"
	object = "animated_bird_fountain"
	value = { store = 30000, bin = 15000 }
	tags = ["furniture", "cottage_garden"]

	#craftable animated items


[animated_waterfall_v1]
	name = "Animated Waterfall"
	description = "An animated waterfall."
	icon_sprite = "spr_ui_item_decor_animated_waterfall_v1"
	value = { bin = "self.recipe*1.1" }
	object = "animated_waterfall_v1"
	recipe_key = "animated_waterfall"
	crafting_preview_sprite = "spr_ui_decor_animated_waterfall_v1_preview"
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "monster_block" },
		{ count = 5, item = "coral" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "animated_set"]

[animated_waterfall_v2]
	name = "Animated Waterfall"
	description = "A mossy animated waterfall."
	icon_sprite = "spr_ui_item_decor_animated_waterfall_v2"
	value = { bin = "self.recipe*1.1" }
	object = "animated_waterfall_v2"
	recipe_key = "animated_waterfall"
	crafting_preview_sprite = "spr_ui_decor_animated_waterfall_v2_preview"
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "monster_block" },
		{ count = 5, item = "coral" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "animated_set"]
