# <---------BASIC SET ITEMS------------->

[basic_area_rug_yellow]
	name = "Basic Area Rug"
	description = "A yellow area rug."
	icon_sprite = "spr_ui_item_furniture_basic_area_rug_v1"
	object = "basic_area_rug_yellow"
	recipe_is_default = true
	tags = ["furniture", "medium_rug", "basic_set"]
	value = { bin = "self.recipe * 1.1", store = 200 }
	recipe_key = "basic_area_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 10, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[basic_area_rug_green]
	description = "A green area rug."
	icon_sprite = "spr_ui_item_furniture_basic_area_rug_v2"
	name = "Basic Area Rug"
	object = "basic_area_rug_green"
	value = { bin = "self.recipe * 1.1", store = 200 }
	recipe_is_default = true
	tags = ["furniture", "medium_rug", "basic_set"]
	recipe_key = "basic_area_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 10, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[basic_bed_oak]
	description = "A basic oak single bed with yellow sheets."
	icon_sprite = "spr_ui_item_furniture_basic_bed_v1"
	name = "Basic Single Bed"
	object = "basic_bed_oak"
	value = { bin = "self.recipe * 1.1", store = 300 }
	recipe_is_default = true
	tags = ["furniture", "single_bed", "basic_set"]
	recipe_key = "basic_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 5, item = "fiber" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[basic_bed_walnut]
	description = "A basic walnut single bed with green sheets."
	icon_sprite = "spr_ui_item_furniture_basic_bed_v2"
	name = "Basic Single Bed"
	object = "basic_bed_walnut"
	value = { bin = "self.recipe * 1.1", store = 300 }
	recipe_is_default = true
	tags = ["furniture", "single_bed", "basic_set"]
	recipe_key = "basic_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 5, item = "fiber" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[basic_bookshelf_oak]
	description = "A basic oak bookshelf."
	icon_sprite = "spr_ui_item_furniture_basic_bookshelf_v1"
	name = "Basic Bookshelf"
	object = "basic_bookshelf_oak"
	recipe_is_default = true
	tags = ["furniture", "bookshelf", "basic_set"]
	value = { bin = "self.recipe * 1.1", store = 400 }
	recipe_key = "basic_bookshelf"
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "paper" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_bookshelf_walnut]
	description = "A basic walnut bookshelf."
	icon_sprite = "spr_ui_item_furniture_basic_bookshelf_v2"
	name = "Basic Bookshelf"
	object = "basic_bookshelf_walnut"
	value = { bin = "self.recipe * 1.1", store = 400 }
	recipe_is_default = true
	tags = ["furniture", "bookshelf", "basic_set"]
	recipe_key = "basic_bookshelf"
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "paper" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_chair_oak]
	description = "A basic oak chair."
	icon_sprite = "spr_ui_item_furniture_basic_chair_v1"
	name = "Basic Chair"
	object = "basic_chair_oak"
	recipe_is_default = true
	value = { bin = "self.recipe * 1.1", store = 150 }
	tags = ["furniture", "dining_chair", "basic_set"]
	recipe_key = "basic_chair"
	crafting_level_requirement = 1
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 2, item = "cattail" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_chair_walnut]
	description = "A basic walnut chair."
	icon_sprite = "spr_ui_item_furniture_basic_chair_v2"
	name = "Basic Chair"
	object = "basic_chair_walnut"
	value = { bin = "self.recipe * 1.1", store = 150 }
	recipe_is_default = true
	tags = ["furniture", "dining_chair", "basic_set"]
	recipe_key = "basic_chair"
	crafting_level_requirement = 1
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 2, item = "cattail" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_doormat_yellow]
	description = "A basic yellow doormat."
	icon_sprite = "spr_ui_item_furniture_basic_doormat_v1"
	name = "Basic Doormat"
	object = "basic_doormat_yellow"
	recipe_is_default = true
	value = { bin = "self.recipe * 1.1", store = 30 }
	tags = ["furniture", "small_rug", "basic_set"]
	recipe_key = "basic_doormat"
	crafting_level_requirement = 1
	recipe = [{ count = 5, item = "hay" }, { hours = 0, minutes = 20 }]

[basic_doormat_green]
	description = "A basic green doormat."
	icon_sprite = "spr_ui_item_furniture_basic_doormat_v2"
	name = "Basic Doormat"
	object = "basic_doormat_green"
	value = { bin = "self.recipe * 1.1", store = 30 }
	recipe_is_default = true
	recipe_key = "basic_doormat"
	tags = ["furniture", "small_rug", "basic_set"]
	crafting_level_requirement = 1
	recipe = [{ count = 5, item = "hay" }, { hours = 0, minutes = 20 }]

[basic_bed_double_oak]
	description = "A basic oak double bed with yellow sheets."
	icon_sprite = "spr_ui_item_furniture_basic_double_bed_v1"
	name = "Basic Double Bed"
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "basic_double_bed_oak"
	recipe_is_default = true
	recipe_key = "basic_bed_double"
	tags = ["furniture", "double_bed", "basic_set"]
	crafting_level_requirement = 8
	recipe = [
		{ count = 50, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 10, item = "cattail" },
		{ count = 10, item = "fiber" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[basic_bed_double_walnut]
	description = "A basic walnut double bed with green sheets."
	icon_sprite = "spr_ui_item_furniture_basic_double_bed_v2"
	name = "Basic Double Bed"
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "basic_double_bed_walnut"
	recipe_key = "basic_bed_double"
	recipe_is_default = true
	tags = ["furniture", "double_bed", "basic_set"]
	crafting_level_requirement = 8
	recipe = [
		{ count = 50, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 10, item = "cattail" },
		{ count = 10, item = "fiber" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[basic_dresser_oak]
	description = "A basic oak dresser."
	icon_sprite = "spr_ui_item_furniture_basic_dresser_v1"
	name = "Basic Dresser"
	value = { bin = "self.recipe * 1.1", store = 150 }
	object = "basic_dresser_oak"
	recipe_is_default = true
	recipe_key = "basic_dresser"
	tags = ["furniture", "drawer", "basic_set"]
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_dresser_walnut]
	description = "A basic walnut dresser."
	icon_sprite = "spr_ui_item_furniture_basic_dresser_v2"
	name = "Basic Dresser"
	value = { bin = "self.recipe * 1.1", store = 150 }
	object = "basic_dresser_walnut"
	recipe_is_default = true
	recipe_key = "basic_dresser"
	tags = ["furniture", "drawer", "basic_set"]
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_flooring_oak]
	description = "Basic oak flooring for your home."
	icon_sprite = "spr_ui_item_furniture_basic_flooring_v1"
	name = "Basic Flooring"
	value = { bin = "self.recipe * 1.1", store = 100 }
	flooring = "basic_v1"
	recipe_is_default = true
	recipe_key = "basic_flooring"
	crafting_preview_sprite = "spr_ui_furniture_basic_floor_v1_preview"
	tags = ["furniture", "wood_flooring", "basic_set"]
	crafting_level_requirement = 1
	recipe = [{ count = 20, item = "basic_wood" }, { hours = 0, minutes = 20 }]

[basic_flooring_walnut]
	description = "Basic walnut flooring for your home."
	icon_sprite = "spr_ui_item_furniture_basic_flooring_v2"
	name = "Basic Flooring"
	value = { bin = "self.recipe * 1.1", store = 100 }
	flooring = "basic_v2"
	recipe_is_default = true
	recipe_key = "basic_flooring"
	crafting_preview_sprite = "spr_ui_furniture_basic_floor_v2_preview"
	tags = ["furniture", "wood_flooring", "basic_set"]
	crafting_level_requirement = 1
	recipe = [{ count = 20, item = "basic_wood" }, { hours = 0, minutes = 20 }]

[basic_flower_pot_orange]
	description = "A basic orange flower pot for decoration."
	icon_sprite = "spr_ui_item_furniture_basic_flower_pot_v1"
	name = "Basic Flower Pot"
	value = { bin = "self.recipe * 1.1", store = 100 }
	object = "basic_flower_pot_orange"
	recipe_is_default = true
	recipe_key = "basic_flower_pot"
	tags = ["furniture", "tabletop_plant", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "sod" },
		{ count = 1, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[basic_flower_pot_white]
	description = "A basic white flower pot for decoration."
	icon_sprite = "spr_ui_item_furniture_basic_flower_pot_v2"
	name = "Basic Flower Pot"
	value = { bin = "self.recipe * 1.1", store = 100 }
	object = "basic_flower_pot_white"
	recipe_is_default = true
	recipe_key = "basic_flower_pot"
	tags = ["furniture", "tabletop_plant", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "sod" },
		{ count = 1, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[basic_nightstand_oak]
	description = "A basic oak nightstand."
	icon_sprite = "spr_ui_item_furniture_basic_nightstand_v1"
	name = "Basic Nightstand"
	object = "basic_nightstand_oak"
	value = { bin = "self.recipe * 1.1", store = 150 }
	recipe_is_default = true
	recipe_key = "basic_nightstand"
	tags = ["furniture", "nightstand", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_nightstand_walnut]
	description = "A basic walnut nightstand."
	icon_sprite = "spr_ui_item_furniture_basic_nightstand_v2"
	name = "Basic Nightstand"
	value = { bin = "self.recipe * 1.1", store = 150 }
	object = "basic_nightstand_walnut"
	recipe_is_default = true
	recipe_key = "basic_nightstand"
	tags = ["furniture", "nightstand", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[basic_oil_lamp_grey]
	description = "A basic grey oil lamp."
	icon_sprite = "spr_ui_item_furniture_basic_oil_lamp_v1"
	name = "Basic Oil Lamp"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "basic_oil_lamp_grey"
	recipe_is_default = true
	recipe_key = "basic_oil_lamp"
	tags = ["furniture", "table_lighting", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "oil" },
		{ hours = 0, minutes = 20 },
	]

[basic_oil_lamp_yellow]
	description = "A basic yellow oil lamp."
	icon_sprite = "spr_ui_item_furniture_basic_oil_lamp_v2"
	name = "Basic Oil Lamp"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "basic_oil_lamp_yellow"
	recipe_is_default = true
	recipe_key = "basic_oil_lamp"
	tags = ["furniture", "table_lighting", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "oil" },
		{ hours = 0, minutes = 20 },
	]

[basic_table_oak]
	description = "A basic oak table."
	icon_sprite = "spr_ui_item_furniture_basic_table_v1"
	name = "Basic Table"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "basic_table_oak"
	recipe_is_default = true
	recipe_key = "basic_table"
	tags = ["furniture", "dining_table", "basic_set"]
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 3, item = "paper" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]


[basic_table_walnut]
	description = "A basic walnut table."
	icon_sprite = "spr_ui_item_furniture_basic_table_v2"
	name = "Basic Table"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "basic_table_walnut"
	recipe_is_default = true
	recipe_key = "basic_table"
	tags = ["furniture", "dining_table", "basic_set"]
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 3, item = "paper" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[basic_wall_window_oak]
	description = "A basic oak window with yellow curtains."
	icon_sprite = "spr_ui_item_furniture_basic_wall_window_v1"
	name = "Basic Window"
	value = { bin = "self.recipe * 1.1", store = 150 }
	object = "basic_wall_window_oak"
	recipe_is_default = true
	recipe_key = "basic_wall_window"
	tags = ["furniture", "window", "basic_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[basic_wall_window_walnut]
	description = "A basic walnut window with green curtains."
	icon_sprite = "spr_ui_item_furniture_basic_wall_window_v2"
	name = "Basic Window"
	value = { bin = "self.recipe * 1.1", store = 150 }
	object = "basic_wall_window_walnut"
	recipe_is_default = true
	recipe_key = "basic_wall_window"
	crafting_level_requirement = 2
	tags = ["furniture", "window", "basic_set"]
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[basic_wallpaper_oak]
	description = "Basic oak wallpaper for your home."
	icon_sprite = "spr_ui_item_furniture_basic_wallpaper_v1"
	name = "Basic Wallpaper"
	value = { bin = "self.recipe * 1.1", store = 240 }
	wallpaper = "basic_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	recipe_is_default = true
	recipe_key = "basic_wallpaper"
	crafting_preview_sprite = "spr_ui_furniture_basic_wall_v1_preview"
	tags = ["furniture", "wallpaper", "basic_set"]
	crafting_level_requirement = 1
	recipe = [{ count = 5, item = "paper" }, { hours = 0, minutes = 20 }]

[basic_wallpaper_walnut]
	description = "Basic walnut wallpaper for your home."
	icon_sprite = "spr_ui_item_furniture_basic_wallpaper_v2"
	name = "Basic Wallpaper"
	value = { bin = "self.recipe * 1.1", store = 240 }
	wallpaper = "basic_v2"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	recipe_is_default = true
	recipe_key = "basic_wallpaper"
	crafting_preview_sprite = "spr_ui_furniture_basic_wall_v2_preview"
	tags = ["furniture", "wallpaper", "basic_set"]
	crafting_level_requirement = 1
	recipe = [{ count = 5, item = "paper" }, { hours = 0, minutes = 20 }]
