# <---------BASIC CHEST SET ITEMS------------->

[basic_wood_chest_dark] #01
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v01"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_dark"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_light] #02
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v02"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_light"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_medium] #03
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v03"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_medium"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_witch_queen] #04
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v04"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_witch_queen"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_black] #05
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v05"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_black"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_cottage] #06
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v06"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_cottage"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_haunted_attic] #07
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v07"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_haunted_attic"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_red] #08
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v08"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_red"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_orange] #09
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v09"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_orange"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_yellow] #10
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v10"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_yellow"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_green] #11
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v11"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_green"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_blue] #12
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v12"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_blue"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_purple] #13
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v13"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_purple"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_pink] #14
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v14"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_pink"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"

[basic_wood_chest_white] #15
	description = "A placeable basic wooden chest."
	icon_sprite = "spr_ui_item_furniture_basic_chest_v15"
	name = "Basic Wood Chest"
	recipe_is_default = true
	object = "basic_wood_chest_white"
	value = { bin = "self.recipe * 1.1", store = 250 }
	tags = ["furniture", "basic_chest_set", "chest_and_storage"]
	crafting_level_requirement = 4
	recipe = [{ count = 30, item = "basic_wood" }, { hours = 0, minutes = 30 }]
	recipe_key = "basic_wood_chest"
