#------------bonsai set
# found in Balor's wagon

# bonsai accessory plants

[bonsai_accessory_plant_v1]

	name = "Accessory Plant"
	description = "A small plant to accompany a bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_accessory_plant_v1"
	value = { store = 300 }
	object = "bonsai_accessory_plant_v1"
	tags = ["furniture", "tabletop_plant", "bonsai_set"]

[bonsai_accessory_plant_v2]

	name = "Accessory Plant"
	description = "A small plant to accompany a bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_accessory_plant_v2"
	value = { store = 300 }
	object = "bonsai_accessory_plant_v2"
	tags = ["furniture", "tabletop_plant", "bonsai_set"]

[bonsai_accessory_plant_v3]
	
	name = "Accessory Plant"
	description = "A small plant to accompany a bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_accessory_plant_v3"
	value = { store = 300 }
	object = "bonsai_accessory_plant_v3"
	tags = ["furniture", "tabletop_plant", "bonsai_set"]

	# large bonsai

[bonsai_large_v1]

	name = "Large Redwood Bonsai"
	description = "A large redwood bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_large_v1"
	value = { store = 1200 }
	object = "bonsai_large_v1"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_large_v2]

	name = "Large Cherry Bonsai"
	description = "A large decorative cherry bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_large_v2"
	value = { store = 1200 }
	object = "bonsai_large_v2"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_large_v3]

	name = "Large Juniper Bonsai"
	description = "A large juniper bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_large_v3"
	value = { store = 1200 }
	object = "bonsai_large_v3"
	tags = ["furniture", "potted_tree", "bonsai_set"]

	# medium bonsai

[bonsai_medium_v1]

	name = "Medium Elm Bonsai"
	description = "A medium elm bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_medium_v1"
	value = { store = 900 }
	object = "bonsai_medium_v1"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_medium_v2]

	name = "Medium Rowan Bonsai"
	description = "A medium rowan bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_medium_v2"
	value = { store = 900 }
	object = "bonsai_medium_v2"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_medium_v3]

	name = "Medium Plum Bonsai"
	description = "A medium decorative plum bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_medium_v3"
	value = { store = 900 }
	object = "bonsai_medium_v3"
	tags = ["furniture", "potted_tree", "bonsai_set"]

	# small bonsai

[bonsai_small_v1]

	name = "Small Rare Plum Bonsai"
	description = "A small decorative rare plum bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_small_v1"
	value = { store = 600 }
	object = "bonsai_small_v1"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_small_v2]

	name = "Small Apple Bonsai"
	description = "A small decorative apple bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_small_v2"
	value = { store = 600 }
	object = "bonsai_small_v2"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_small_v3]

	name = "Small Ornament Bonsai"
	description = "A small ornament bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_small_v3"
	value = { store = 600 }
	object = "bonsai_small_v3"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[bonsai_small_v4]

	name = "Small Maple Bonsai"
	description = "A small maple bonsai."
	icon_sprite = "spr_ui_item_decor_bonsai_small_v4"
	value = { store = 600 }
	object = "bonsai_small_v4"
	tags = ["furniture", "potted_tree", "bonsai_set"]

	# potted landscape

[potted_landscape_v1]

	name = "Cliff Landscape"
	description = "A miniature cliff landscape displayed on a low table."
	icon_sprite = "spr_ui_item_decor_bonsai_potted_landscape_v1"
	value = { store = 1200 }
	object = "potted_landscape_v1"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[potted_landscape_v2]

	name = "Forest Floor Landscape"
	description = "A miniature forest floor landscape displayed on a low table."
	icon_sprite = "spr_ui_item_decor_bonsai_potted_landscape_v2"
	value = { store = 1200 }
	object = "potted_landscape_v2"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[potted_landscape_v3]

	name = "Fallen Tree Landscape"
	description = "A miniature fallen tree landscape displayed on a low table."
	icon_sprite = "spr_ui_item_decor_bonsai_potted_landscape_v3"
	value = { store = 1200 }
	object = "potted_landscape_v3"
	tags = ["furniture", "potted_tree", "bonsai_set"]

[potted_landscape_v4]

	name = "Fall Leaves Landscape"
	description = "A miniature fall leaves landscape displayed on a low table."
	icon_sprite = "spr_ui_item_decor_bonsai_potted_landscape_v4"
	value = { store = 1200 }
	object = "potted_landscape_v4"
	tags = ["furniture", "potted_tree", "bonsai_set"]

	#jadeite items

[jadeite_cabbage]

	name = "Jadeite Cabbage"
	description = "A large cabbage sculpted in jadeite."
	icon_sprite = "spr_ui_item_decor_jadeite_cabbage"
	value = { store = 500 }
	object = "jadeite_cabbage"
	tags = ["furniture", "misc_decor", "bonsai_set"]

[jadeite_daikon]

	name = "Jadeite Daikon"
	description = "A large daikon sculpted in jadeite."
	icon_sprite = "spr_ui_item_decor_jadeite_daikon"
	value = { store = 500 }
	object = "jadeite_daikon"
	tags = ["furniture", "misc_decor", "bonsai_set"]

	# strange garden stone

[strange_garden_stone_v1]

	name = "Strange Garden Stone"
	description = "A strange decorative stone taken from a lake."
	icon_sprite = "spr_ui_item_decor_strange_garden_stone_v1"
	value = { store = 500 }
	object = "strange_garden_stone_v1"
	tags = ["furniture", "misc_outdoor_decor", "bonsai_set"]

[strange_garden_stone_v2]

	name = "Strange Garden Stone"
	description = "A strange decorative stone taken from a lake."
	icon_sprite = "spr_ui_item_decor_strange_garden_stone_v2"
	value = { store = 500 }
	object = "strange_garden_stone_v2"
	tags = ["furniture", "misc_outdoor_decor", "bonsai_set"]

	# bonsai stands

[bonsai_high_stand_light_brown]

	name = "Tall Display Stand"
	description = "A tall oak stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_high_stand_light_brown"
	value = { store = 500 }
	object = "bonsai_high_stand_light_brown"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_stand_light_brown]

	name = "Short Display Stand"
	description = "A short oak stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_stand_light_brown"
	value = { store = 500 }
	object = "bonsai_low_stand_light_brown"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_cabinet_light_brown]

	name = "Short Display Cabinet"
	description = "A short oak cabinet for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_cabinet_light_brown"
	value = { store = 500 }
	object = "bonsai_low_cabinet_light_brown"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_low_table_light_brown]

	name = "Short Display Table"
	description = "A short oak table for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_table_light_brown"
	value = { store = 500 }
	object = "bonsai_low_table_light_brown"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_high_stand_brown]

	name = "Tall Display Stand"
	description = "A tall walnut stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_high_stand_dark_brown"
	value = { store = 500 }
	object = "bonsai_high_stand_brown"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_stand_brown]

	name = "Short Display Stand"
	description = "A short walnut stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_stand_dark_brown"
	value = { store = 500 }
	object = "bonsai_low_stand_brown"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_cabinet_brown]

	name = "Short Display Cabinet"
	description = "A short walnut cabinet for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_cabinet_dark_brown"
	value = { store = 500 }
	object = "bonsai_low_cabinet_brown"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_low_table_brown]

	name = "Short Display Table"
	description = "A short walnut table for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_table_dark_brown"
	value = { store = 500 }
	object = "bonsai_low_table_brown"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_high_stand_white]

	name = "Tall Display Stand"
	description = "A tall white stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_high_stand_white"
	value = { store = 500 }
	object = "bonsai_high_stand_white"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_stand_white]

	name = "Short Display Stand"
	description = "A short white stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_stand_white"
	value = { store = 500 }
	object = "bonsai_low_stand_white"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_cabinet_white]

	name = "Short Display Cabinet"
	description = "A short white cabinet for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_cabinet_white"
	value = { store = 500 }
	object = "bonsai_low_cabinet_white"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_low_table_white]

	name = "Short Display Table"
	description = "A short white table for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_table_white"
	value = { store = 500 }
	object = "bonsai_low_table_white"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_high_stand_black]

	name = "Tall Display Stand"
	description = "A tall black stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_high_stand_black"
	value = { store = 500 }
	object = "bonsai_high_stand_black"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_stand_black]

	name = "Short Display Stand"
	description = "A short black stand for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_stand_black"
	value = { store = 500 }
	object = "bonsai_low_stand_black"
	tags = ["furniture", "side_table", "bonsai_set"]

[bonsai_low_cabinet_black]

	name = "Short Display Cabinet"
	description = "A short black cabinet for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_cabinet_black"
	value = { store = 500 }
	object = "bonsai_low_cabinet_black"
	tags = ["furniture", "coffee_table", "bonsai_set"]

[bonsai_low_table_black]

	name = "Short Display Table"
	description = "A short black table for displaying precious objects."
	icon_sprite = "spr_ui_item_decor_bonsai_low_table_black"
	value = { store = 500 }
	object = "bonsai_low_table_black"
	tags = ["furniture", "coffee_table", "bonsai_set"]
