# <---------CAVERN SET ITEMS (EARTH BIOME)------------>

[cavern_crystal_lamp_green]
	icon_sprite = "spr_ui_item_furniture_crystal_lamp_green"
	name = "Glowing Crystal Lamp"
	description = "A shard of glowing green crystal."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_crystal_lamp_green"
	recipe_key = "cavern_crystal_lamp"
	crafting_preview_sprite = "spr_ui_furniture_deep_earth_crystal_lamp_green_preview"
	crafting_level_requirement = 10
	recipe = [
		{ count = 15, item = "crystal" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "cavern_set", "table_lighting"]

[cavern_mushroom_stool_green]
	icon_sprite = "spr_ui_item_furniture_mushroom_stool_green"
	name = "Mushroom Stool"
	description = "A green mushroom stool."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_mushroom_stool_green"
	recipe_key = "cavern_mushroom_stool"
	crafting_level_requirement = 12
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 2, item = "earthshroom" },
		{ count = 2, item = "wild_mushroom" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "stool"]

[cavern_crystal_lamp_pink]
	icon_sprite = "spr_ui_item_furniture_crystal_lamp_pink"
	name = "Glowing Crystal Lamp"
	description = "A shard of glowing pink crystal."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_crystal_lamp_pink"
	recipe_key = "cavern_crystal_lamp"
	crafting_preview_sprite = "spr_ui_furniture_deep_earth_crystal_lamp_pink_preview"
	crafting_level_requirement = 10
	recipe = [
		{ count = 15, item = "crystal" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "cavern_set", "table_lighting"]

[cavern_mushroom_stool_pink]
	icon_sprite = "spr_ui_item_furniture_mushroom_stool_pink"
	name = "Mushroom Stool"
	description = "A pink mushroom stool."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_mushroom_stool_pink"
	recipe_key = "cavern_mushroom_stool"
	crafting_level_requirement = 12
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 2, item = "earthshroom" },
		{ count = 2, item = "wild_mushroom" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "stool"]

[cavern_crystal_lamp_purple]
	icon_sprite = "spr_ui_item_furniture_crystal_lamp_purple"
	name = "Glowing Crystal Lamp"
	description = "A shard of glowing white crystal."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_crystal_lamp_purple"
	recipe_key = "cavern_crystal_lamp"
	crafting_preview_sprite = "spr_ui_furniture_deep_earth_crystal_lamp_purple_preview"
	crafting_level_requirement = 10
	recipe = [
		{ count = 15, item = "crystal" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "cavern_set", "table_lighting"]

[cavern_mushroom_stool_purple]
	icon_sprite = "spr_ui_item_furniture_mushroom_stool_purple"
	name = "Mushroom Stool"
	description = "A purple mushroom stool."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_mushroom_stool_purple"
	recipe_key = "cavern_mushroom_stool"
	crafting_level_requirement = 12
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 2, item = "earthshroom" },
		{ count = 2, item = "wild_mushroom" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "stool"]

[cavern_emerald_rock]
	icon_sprite = "spr_ui_item_furniture_emerald_rock"
	name = "Ornamental Emerald Rock"
	description = "A decorative emerald rock."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_emerald_rock"
	crafting_level_requirement = 8
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "ore_emerald" },
		{ count = 3, item = "wild_mushroom" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "cavern_set", "misc_furniture"]

[cavern_silver_node]
	icon_sprite = "spr_ui_item_furniture_silver_node"
	name = "Ornamental Silver Node"
	description = "A decorative silver node."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_silver_node"
	crafting_level_requirement = 8
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 10, item = "ore_silver" },
		{ count = 3, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "cavern_set", "misc_furniture"]

[cavern_hewn_rock_bookshelf]
	icon_sprite = "spr_ui_item_furniture_hewn_rock_bookshelf"
	name = "Hewn Rock Bookshelf"
	description = "A hewn rock bookshelf."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_hewn_rock_bookshelf"
	crafting_level_requirement = 14
	recipe = [
		{ count = 25, item = "ore_stone" },
		{ count = 5, item = "paper" },
		{ count = 2, item = "earthshroom" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "bookshelf"]

[cavern_hewn_rock_table]
	icon_sprite = "spr_ui_item_furniture_hewn_stone_table"
	name = "Hewn Rock Table"
	description = "A hewn rock table."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_hewn_rock_table"
	crafting_level_requirement = 14
	recipe = [
		{ count = 40, item = "ore_stone" },
		{ count = 5, item = "ore_iron" },
		{ count = 3, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "coffee_table"]

[cavern_stone_arch]
	icon_sprite = "spr_ui_item_furniture_stone_arch"
	name = "Stalactite Arch"
	description = "A stone arch with stalactites."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_stone_arch"
	crafting_level_requirement = 16
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 10, item = "crystal" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "cavern_set", "misc_outdoor_decor"]

[cavern_wall_brazier_purple]
	icon_sprite = "spr_ui_item_furniture_wall_brazier_purple"
	name = "Wall Brazier"
	description = "A wall brazier filled with purple flames."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_wall_brazier_purple"
	recipe_key = "cavern_wall_brazier"
	#crafting_preview_sprite = "spr_furniture_deep_earth_wall_brazier_purple_spring_on"
	crafting_level_requirement = 8
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 3, item = "peat" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "wall_lighting"]

[cavern_wall_brazier_orange]
	icon_sprite = "spr_ui_item_furniture_wall_brazier_orange"
	name = "Wall Brazier"
	description = "A wall brazier filled with orange flames."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_wall_brazier_orange"
	recipe_key = "cavern_wall_brazier"
	#crafting_preview_sprite = "spr_furniture_deep_earth_wall_brazier_orange_spring_on"
	crafting_level_requirement = 8
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 3, item = "peat" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "wall_lighting"]

[cavern_wall_brazier_blue]
	icon_sprite = "spr_ui_item_furniture_wall_brazier_blue"
	name = "Wall Brazier"
	description = "A wall brazier filled with blue flames."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_wall_brazier_blue"
	recipe_key = "cavern_wall_brazier"
	#crafting_preview_sprite = "spr_furniture_deep_earth_wall_brazier_blue_spring_on"
	crafting_level_requirement = 8
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 3, item = "peat" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "wall_lighting"]

[cavern_floor_brazier_purple]
	icon_sprite = "spr_ui_item_furniture_floor_brazier_purple"
	name = "Floor Brazier"
	description = "A floor brazier filled with purple flames."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_floor_brazier_purple"
	recipe_key = "cavern_floor_brazier"
	#crafting_preview_sprite = "spr_furniture_deep_earth_floor_brazier_purple_spring_on"
	crafting_level_requirement = 10
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 3, item = "peat" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "cavern_set", "floor_lighting"]

[cavern_floor_brazier_blue]
	icon_sprite = "spr_ui_item_furniture_floor_brazier_blue"
	name = "Floor Brazier"
	description = "A floor brazier filled with blue flames."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_floor_brazier_blue"
	recipe_key = "cavern_floor_brazier"
	#crafting_preview_sprite = "spr_furniture_deep_earth_floor_brazier_blue_spring_on"
	crafting_level_requirement = 10
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 3, item = "peat" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "cavern_set", "floor_lighting"]

[cavern_floor_brazier_orange]
	icon_sprite = "spr_ui_item_furniture_floor_brazier_orange"
	name = "Floor Brazier"
	description = "A floor brazier filled with orange flames."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_floor_brazier_orange"
	recipe_key = "cavern_floor_brazier"
	#crafting_preview_sprite = "spr_furniture_deep_earth_floor_brazier_orange_spring_on"
	crafting_level_requirement = 10
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 3, item = "peat" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "cavern_set", "floor_lighting"]

[cavern_mossy_rug_v1]
	icon_sprite = "spr_ui_item_furniture_mossy_rug_v1"
	name = "Mossy Rug"
	description = "A cool-toned green moss rug."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_mossy_rug_v1"
	recipe_key = "cavern_mossy_rug"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "feather" },
		{ count = 3, item = "narrows_moss" },
		{ count = 2, item = "shale_grass" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "medium_rug"]

[cavern_mossy_rug_v2]
	icon_sprite = "spr_ui_item_furniture_mossy_rug_v2"
	name = "Mossy Rug"
	description = "A warm-toned green moss rug."
	value = { bin = "self.recipe * 1.1" }
	object = "cavern_mossy_rug_v2"
	recipe_key = "cavern_mossy_rug"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "feather" },
		{ count = 3, item = "narrows_moss" },
		{ count = 2, item = "shale_grass" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "medium_rug"]

[cavern_rock_wallpaper]
	icon_sprite = "spr_ui_item_furniture_wallpaper_deep_earth"
	name = "Rock Wall"
	description = "A wallpaper that mimics the look of the Deep Earth."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "cavern"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_wallpaper_deep_earth_preview"
	crafting_level_requirement = 10
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "ore_silver" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "wallpaper"]

[cavern_rock_flooring]
	icon_sprite = "spr_ui_item_furniture_flooring_deep_earth"
	name = "Rock Floor"
	description = "A rock floor that mimics the look of the Deep Earth."
	value = { bin = "self.recipe * 1.1" }
	flooring = "cavern"
	crafting_preview_sprite = "spr_ui_furniture_flooring_deep_earth_preview"
	crafting_level_requirement = 10
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 10, item = "crystal" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "cavern_set", "novelty_flooring"]
