[cherry_wallpaper]
	icon_sprite = "spr_ui_item_furniture_cherry_wallpaper"
	name = "Cherry Wallpaper"
	description = "A pink wallpaper with a cute cherry print."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "cherry"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_cherry_wall_preview"
	tags = ["furniture", "wallpaper", "cherry_set"]
	recipe_key = "cherry_wallpaper"
	crafting_level_requirement = 14
	recipe = [
		{ count = 3, item = "cherry" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 20 },
	]

[cherry_flooring]
	icon_sprite = "spr_ui_item_furniture_cherry_flooring"
	name = "Cherry Flooring"
	description = "Pink herringbone flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "cherry"
	crafting_preview_sprite = "spr_ui_furniture_cherry_floor_preview"
	tags = ["furniture", "wood_flooring", "cherry_set"]
	recipe_key = "cherry_flooring"
	crafting_level_requirement = 14
	recipe = [
		{ count = 3, item = "cherry" },
		{ count = 5, item = "hard_wood" },
		{ hours = 0, minutes = 20 },
	]

[cherry_rug]
	icon_sprite = "spr_ui_item_furniture_cherry_rug"
	name = "Cherry Rug"
	description = "A cute cherry-shaped rug."
	value = { bin = "self.recipe * 1.1" }
	object = "cherry_rug"
	tags = ["furniture", "medium_rug", "cherry_set"]
	recipe_key = "cherry_rug"
	crafting_level_requirement = 16
	recipe = [
		{ count = 6, item = "cherry" },
		{ count = 3, item = "rabbit_wool" },
		{ hours = 0, minutes = 20 },
	]


[cherry_chair]
	icon_sprite = "spr_ui_item_furniture_cherry_chair"
	name = "Cherry Chair"
	description = "A large cozy chair shaped like a cherry."
	value = { bin = "self.recipe * 1.1" }
	object = "cherry_chair"
	tags = ["furniture", "accent_chair", "cherry_set"]
	recipe_key = "cherry_chair"
	crafting_level_requirement = 18
	recipe = [
		{ count = 6, item = "cherry" },
		{ count = 3, item = "rabbit_wool" },
		{ count = 3, item = "hard_wood" },
		{ hours = 0, minutes = 30 },
	]

[cherry_table]
	icon_sprite = "spr_ui_item_furniture_cherry_table"
	name = "Cherry Table"
	description = "A cute cherry-themed table."
	value = { bin = "self.recipe * 1.1" }
	object = "cherry_table"
	tags = ["furniture", "coffee_table", "cherry_set"]
	recipe_key = "cherry_table"
	crafting_level_requirement = 18
	recipe = [
		{ count = 6, item = "cherry" },
		{ count = 3, item = "rabbit_wool" },
		{ count = 3, item = "hard_wood" },
		{ hours = 0, minutes = 30 },
	]

[cherry_table_lamp]
	icon_sprite = "spr_ui_item_furniture_cherry_table_lamp"
	name = "Cherry Table Lamp"
	description = "A cute cherry-shaped lamp."
	value = { bin = "self.recipe * 1.1" }
	object = "cherry_table_lamp"
	tags = ["furniture", "table_lighting", "cherry_set"]
	recipe_key = "cherry_table_lamp"
	crafting_preview_sprite = "spr_ui_furniture_cherry_table_lamp_preview"
	crafting_level_requirement = 16
	recipe = [
		{ count = 4, item = "cherry" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[cherry_fruit_bowl]
	icon_sprite = "spr_ui_item_furniture_cherry_fruit_bowl"
	name = "Cherry Fruit Bowl"
	description = "A decorative bowl full of cherries."
	value = { bin = "self.recipe * 1.1" }
	object = "cherry_fruit_bowl"
	tags = ["furniture", "kitchen_decor", "cherry_set"]
	recipe_key = "cherry_fruit_bowl"
	crafting_level_requirement = 14
	recipe = [
		{ count = 4, item = "cherry" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[cherry_bonsai]
	icon_sprite = "spr_ui_item_furniture_cherry_bonsai"
	name = "Cherry Bonsai"
	description = "A decorative miniature cherry tree."
	value = { bin = "self.recipe * 1.1" }
	object = "cherry_bonsai"
	tags = ["furniture", "potted_tree", "cherry_set"]
	recipe_key = "cherry_bonsai"
	crafting_level_requirement = 16
	recipe = [
		{ count = 1, item = "sapling_cherry" },
		{ count = 1, item = "sod" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 30 },
	]
