# COOKING SET DECOR
[cooking_frying_pan_v1]
	icon_sprite = "spr_ui_item_decor_cooking_frying_pan_v1"
	name = "Frying Pan"
	description = "A decorative blue frying pan."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_frying_pan_v1"
	recipe_key = "cooking_frying_pan"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "silver_ingot" },
		{ count = 4, item = "coral" },
		{ hours = 0, minutes = 20 },
	]

[cooking_frying_pan_v2]
	icon_sprite = "spr_ui_item_decor_cooking_frying_pan_v2"
	name = "Frying Pan"
	description = "A decorative gold frying pan."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_frying_pan_v2"
	recipe_key = "cooking_frying_pan"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "gold_ingot" },
		{ count = 4, item = "crystal" },
		{ hours = 0, minutes = 20 },
	]

[cooking_frying_pan_v3]
	icon_sprite = "spr_ui_item_decor_cooking_frying_pan_v3"
	name = "Frying Pan"
	description = "A decorative cast iron frying pan."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_frying_pan_v3"
	recipe_key = "cooking_frying_pan"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 4, item = "obsidian" },
		{ hours = 0, minutes = 20 },
	]


[cooking_stockpot_v1]
	icon_sprite = "spr_ui_item_decor_cooking_stockpot_v1"
	name = "Stockpot"
	description = "A decorative blue stockpot."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_stockpot_v1"
	recipe_key = "cooking_stockpot"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 2, item = "silver_ingot" },
		{ count = 6, item = "coral" },
		{ hours = 0, minutes = 20 },
	]


[cooking_stockpot_v2]
	icon_sprite = "spr_ui_item_decor_cooking_stockpot_v2"
	name = "Stockpot"
	description = "A decorative gold stockpot."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_stockpot_v2"
	recipe_key = "cooking_stockpot"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 2, item = "gold_ingot" },
		{ count = 6, item = "crystal" },
		{ hours = 0, minutes = 20 },
	]

[cooking_stockpot_v3]
	icon_sprite = "spr_ui_item_decor_cooking_stockpot_v3"
	name = "Stockpot"
	description = "A decorative cast iron stockpot."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_stockpot_v3"
	recipe_key = "cooking_stockpot"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 6, item = "obsidian" },
		{ hours = 0, minutes = 20 },
	]

[cooking_tea_kettle_v1]
	icon_sprite = "spr_ui_item_decor_cooking_tea_kettle_v1"
	name = "Tea Kettle"
	description = "A decorative gold kettle."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_tea_kettle_v1"
	recipe_key = "cooking_tea_kettle"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 3, item = "gold_ingot" },
		{ hours = 0, minutes = 10 },
	]

[cooking_tea_kettle_v2]
	icon_sprite = "spr_ui_item_decor_cooking_tea_kettle_v2"
	name = "Tea Kettle"
	description = "A decorative copper kettle."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_tea_kettle_v2"
	recipe_key = "cooking_tea_kettle"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 3, item = "copper_ingot" },
		{ hours = 0, minutes = 10 },
	]

[cooking_tea_kettle_v3]
	icon_sprite = "spr_ui_item_decor_cooking_tea_kettle_v3"
	name = "Tea Kettle"
	description = "A decorative silver kettle."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_tea_kettle_v3"
	recipe_key = "cooking_tea_kettle"
	tags = ["furniture", "kitchen_decor", "cooking_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 3, item = "silver_ingot" },
		{ hours = 0, minutes = 10 },
	]

[cooking_hanging_pans_v1]
	icon_sprite = "spr_ui_item_decor_cooking_hanging_pans_v1"
	name = "Hanging Pans"
	description = "Wall decor featuring two hanging pans."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_hanging_pans_v1"
	recipe_key = "cooking_hanging_pans"
	tags = ["furniture", "kitchen_decor", "wall_hanging", "cooking_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 2, item = "iron_ingot" },
		{ hours = 0, minutes = 20 },
	]

[cooking_hanging_pans_v2]
	icon_sprite = "spr_ui_item_decor_cooking_hanging_pans_v2"
	name = "Hanging Pans"
	description = "Wall decor featuring a hanging pan and accessories."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cooking_hanging_pans_v2"
	recipe_key = "cooking_hanging_pans"
	tags = ["furniture", "kitchen_decor", "wall_hanging", "cooking_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 2, item = "iron_ingot" },
		{ hours = 0, minutes = 20 },
	]
