#----------COTTAGE GARDEN DECOR SET

[cottage_garden_planter_v1]
	name = "Cottage Garden Planter"
	icon_sprite = "spr_ui_item_decor_cottage_garden_planter_v1"
	description = "A cottage garden planter made with warm-toned stone."
	object = "cottage_garden_planter_v1"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 22
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 2, item = "sod" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_planter"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_planter_v2]
	name = "Cottage Garden Planter"
	icon_sprite = "spr_ui_item_decor_cottage_garden_planter_v2"
	description = "A cottage garden planter made with neutral-toned stone."
	object = "cottage_garden_planter_v2"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 22
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 2, item = "sod" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_planter"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_planter_v3]
	name = "Cottage Garden Planter"
	icon_sprite = "spr_ui_item_decor_cottage_garden_planter_v3"
	description = "A cottage garden planter made with cool-toned stone."
	object = "cottage_garden_planter_v3"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 22
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 2, item = "sod" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_planter"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_trellis_v1]
	name = "Cottage Garden Trellis"
	icon_sprite = "spr_ui_item_decor_cottage_garden_trellis_v1"
	description = "A pretty off-white garden trellis."
	object = "cottage_garden_trellis_v1"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 24
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "basic_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_trellis"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_trellis_v2]
	name = "Cottage Garden Trellis"
	icon_sprite = "spr_ui_item_decor_cottage_garden_trellis_v2"
	description = "A pretty off-white garden trellis covered in flowering ivy."
	object = "cottage_garden_trellis_v2"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 24
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "small_grass_starter" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_trellis"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_trellis_v3]
	name = "Cottage Garden Trellis"
	icon_sprite = "spr_ui_item_decor_cottage_garden_trellis_v3"
	description = "A pretty off-white garden trellis lined with potted plants."
	object = "cottage_garden_trellis_v3"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 24
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "sod" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_trellis"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_workbench_v1]
	name = "Cottage Garden Workbench"
	icon_sprite = "spr_ui_item_decor_cottage_garden_workbench_v1"
	description = "A clean and tidy garden workbench."
	object = "cottage_garden_workbench_v1"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 26
	recipe = [
		{ count = 6, item = "hard_wood" },
		{ count = 2, item = "basic_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_workbench"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_workbench_v2]
	name = "Cottage Garden Workbench"
	icon_sprite = "spr_ui_item_decor_cottage_garden_workbench_v2"
	description = "A charmingly cluttered garden workbench."
	object = "cottage_garden_workbench_v2"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 26
	recipe = [
		{ count = 6, item = "hard_wood" },
		{ count = 2, item = "sod" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_workbench"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_arch_v1]
	name = "Cottage Garden Arch"
	icon_sprite = "spr_ui_item_decor_cottage_garden_arch_v1"
	description = "A pretty off-white garden arch."
	object = "cottage_garden_arch_v1"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 28
	recipe = [
		{ count = 8, item = "hard_wood" },
		{ count = 4, item = "basic_wood" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_arch"
	tags = ["furniture", "garden_decor", "cottage_garden"]


[cottage_garden_arch_v2]
	name = "Cottage Garden Arch"
	icon_sprite = "spr_ui_item_decor_cottage_garden_arch_v2"
	description = "A pretty off-white garden arch, covered with ivy."
	object = "cottage_garden_arch_v2"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 28
	recipe = [
		{ count = 8, item = "hard_wood" },
		{ count = 4, item = "small_grass_starter" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_arch"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_shed_v1]
	name = "Cottage Garden Shed"
	icon_sprite = "spr_ui_item_decor_cottage_garden_shed_v1"
	description = "A pretty off-white garden shed."
	object = "cottage_garden_shed_v1"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 4, item = "basic_wood" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_shed"
	tags = ["furniture", "garden_decor", "cottage_garden"]

[cottage_garden_shed_v2]
	name = "Cottage Garden Shed"
	icon_sprite = "spr_ui_item_decor_cottage_garden_shed_v2"
	description = "A pretty off-white garden shed, covered with ivy."
	object = "cottage_garden_shed_v2"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 4, item = "small_grass_starter" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "cottage_garden_shed"
	tags = ["furniture", "garden_decor", "cottage_garden"]
