#COUNTER SET

[counter_basic_v1]
	name = "Basic Counter"
	description = "An oak basic counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_basic_v1"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_basic_v1"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_basic_preview_v1"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_basic_v2]
	name = "Basic Counter"
	description = "A walnut basic counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_basic_v2"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_basic_v2"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_basic_preview_v2"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cabin_walnut]
	name = "Cabin Counter"
	description = "A walnut cabin counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cabin_walnut"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cabin_walnut"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cabin_preview_walnut"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cabin_oak]
	name = "Cabin Counter"
	description = "An oak cabin counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cabin_oak"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cabin_oak"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cabin_preview_oak"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cabin_cherry]
	name = "Cabin Counter"
	description = "A cherry cabin counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cabin_cherry"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cabin_cherry"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cabin_preview_cherry"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cake_strawberry]
	name = "Cake Counter"
	description = "A strawberry cake counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cake_strawberry"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cake_strawberry"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cake_preview_strawberry"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cake_chocolate]
	name = "Cake Counter"
	description = "A mocha cake counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cake_chocolate"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cake_chocolate"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cake_preview_chocolate"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cake_double_chocolate]
	name = "Cake Counter"
	description = "A chocolate cake counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cake_double_chocolate"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cake_double_chocolate"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cake_preview_double_chocolate"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cottage_v1]
	name = "Lovely Cottage Counter"
	description = "A sage lovely cottage counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cottage_v1"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cottage_v1"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cottage_preview_v1"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_cottage_v2]
	name = "Lovely Cottage Counter"
	description = "A pink lovely cottage counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_cottage_v2"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "counter_cottage_v2"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_decor_counter_cottage_preview_v2"
	recipe = [
		{ count = 5, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]
