# CRAFT SET DECOR

[craft_rug_v1]
	icon_sprite = "spr_ui_item_decor_craft_rug_v1"
	name = "Craft Crochet Rug"
	description = "A crafty blue and red crochet rug."
	value = { bin = "self.recipe * 1.1", store = 1800 }
	object = "craft_rug_v1"
	recipe_key = "craft_rug"
	tags = ["furniture", "medium_rug", "craft_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 2, item = "golden_alpaca_wool" },
		{ count = 2, item = "golden_sheep_wool" },
		{ hours = 0, minutes = 20 },
	]

[craft_rug_v2]
	icon_sprite = "spr_ui_item_decor_craft_rug_v2"
	name = "Craft Crochet Rug"
	description = "A crafty purple and pink crochet rug."
	value = { bin = "self.recipe * 1.1", store = 1800 }
	object = "craft_rug_v2"
	recipe_key = "craft_rug"
	tags = ["furniture", "medium_rug", "craft_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 2, item = "golden_alpaca_wool" },
		{ count = 2, item = "golden_sheep_wool" },
		{ hours = 0, minutes = 20 },
	]

[craft_rug_v3]
	icon_sprite = "spr_ui_item_decor_craft_rug_v3"
	name = "Craft Crochet Rug"
	description = "A crafty green and brown crochet rug."
	value = { bin = "self.recipe * 1.1", store = 1800 }
	object = "craft_rug_v3"
	recipe_key = "craft_rug"
	tags = ["furniture", "medium_rug", "craft_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 2, item = "golden_alpaca_wool" },
		{ count = 2, item = "golden_sheep_wool" },
		{ hours = 0, minutes = 20 },
	]

[craft_yarn_basket_v1]
	icon_sprite = "spr_ui_item_decor_craft_yarn_basket_v1"
	name = "Craft Yarn Basket"
	description = "A crafty light brown basket full of yarn."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_yarn_basket_v1"
	recipe_key = "craft_yarn_basket"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 2, item = "hay" },
		{ hours = 0, minutes = 20 },
	]

[craft_yarn_basket_v2]
	icon_sprite = "spr_ui_item_decor_craft_yarn_basket_v2"
	name = "Craft Yarn Basket"
	description = "A crafty white basket full of yarn."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_yarn_basket_v2"
	recipe_key = "craft_yarn_basket"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 2, item = "hay" },
		{ hours = 0, minutes = 20 },
	]

[craft_yarn_basket_v3]
	icon_sprite = "spr_ui_item_decor_craft_yarn_basket_v3"
	name = "Craft Yarn Basket"
	description = "A crafty dark brown basket full of yarn."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_yarn_basket_v3"
	recipe_key = "craft_yarn_basket"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 2, item = "hay" },
		{ hours = 0, minutes = 20 },
	]

[craft_fabric_rack_v1]
	icon_sprite = "spr_ui_item_decor_craft_fabric_rack_v1"
	name = "Craft Fabric Rack"
	description = "A crafty light brown fabric rack."
	value = { bin = "self.recipe * 1.1", store = 1000 }
	object = "craft_fabric_rack_v1"
	recipe_key = "craft_fabric_rack"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 44
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ hours = 0, minutes = 30 },
	]

[craft_fabric_rack_v2]
	icon_sprite = "spr_ui_item_decor_craft_fabric_rack_v2"
	name = "Craft Fabric Rack"
	description = "A crafty white fabric rack."
	value = { bin = "self.recipe * 1.1", store = 1000 }
	object = "craft_fabric_rack_v2"
	recipe_key = "craft_fabric_rack"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 44
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ hours = 0, minutes = 30 },
	]

[craft_fabric_rack_v3]
	icon_sprite = "spr_ui_item_decor_craft_fabric_rack_v3"
	name = "Craft Fabric Rack"
	description = "A crafty dark brown fabric rack."
	value = { bin = "self.recipe * 1.1", store = 1000 }
	object = "craft_fabric_rack_v3"
	recipe_key = "craft_fabric_rack"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 44
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ hours = 0, minutes = 30 },
	]

[craft_closed_sewing_tin_v1]
	icon_sprite = "spr_ui_item_decor_craft_closed_sewing_tin_v1"
	name = "Craft Sewing Tin"
	description = "A closed blue sewing tin."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_closed_sewing_tin_v1"
	recipe_key = "craft_sewing_tin"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "horse_hair" },
		{ count = 1, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]

[craft_closed_sewing_tin_v2]
	icon_sprite = "spr_ui_item_decor_craft_closed_sewing_tin_v2"
	name = "Craft Sewing Tin"
	description = "A closed pink sewing tin."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_closed_sewing_tin_v2"
	recipe_key = "craft_sewing_tin"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "horse_hair" },
		{ count = 1, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]

[craft_closed_sewing_tin_v3]
	icon_sprite = "spr_ui_item_decor_craft_closed_sewing_tin_v3"
	name = "Craft Sewing Tin"
	description = "A closed green sewing tin."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_closed_sewing_tin_v3"
	recipe_key = "craft_sewing_tin"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "horse_hair" },
		{ count = 1, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]

[craft_open_sewing_tin_v1]
	icon_sprite = "spr_ui_item_decor_craft_open_sewing_tin_v1"
	name = "Craft Sewing Tin"
	description = "An open blue sewing tin."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_open_sewing_tin_v1"
	recipe_key = "craft_sewing_tin"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "horse_hair" },
		{ count = 1, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]

[craft_open_sewing_tin_v2]
	icon_sprite = "spr_ui_item_decor_craft_open_sewing_tin_v2"
	name = "Craft Sewing Tin"
	description = "An open pink sewing tin."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_open_sewing_tin_v2"
	recipe_key = "craft_sewing_tin"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "horse_hair" },
		{ count = 1, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]

[craft_open_sewing_tin_v3]
	icon_sprite = "spr_ui_item_decor_craft_open_sewing_tin_v3"
	name = "Craft Sewing Tin"
	description = "An open green sewing tin."
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "craft_open_sewing_tin_v3"
	recipe_key = "craft_sewing_tin"
	tags = ["furniture", "misc_decor", "craft_set"]
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "horse_hair" },
		{ count = 1, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
