#crystal resonators

[crystal_resonator_red]
	name = "Red Crystal Resonator"
	description = "A red Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_red"
	object = "crystal_resonator_red"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_orange]
	name = "Orange Crystal Resonator"
	description = "An orange Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_orange"
	object = "crystal_resonator_orange"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_gold]
	name = "Gold Crystal Resonator"
	description = "A gold Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_gold"
	object = "crystal_resonator_gold"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_green]
	name = "Green Crystal Resonator"
	description = "A green Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_green"
	object = "crystal_resonator_green"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_blue]
	name = "Blue Crystal Resonator"
	description = "A blue Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_blue"
	object = "crystal_resonator_blue"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_purple]
	name = "Purple Crystal Resonator"
	description = "A purple Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_purple"
	object = "crystal_resonator_purple"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_silver]
	name = "Silver Crystal Resonator"
	description = "A silver Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_silver"
	object = "crystal_resonator_silver"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_black]
	name = "Black Crystal Resonator"
	description = "A black Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_black"
	object = "crystal_resonator_black"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_void]
	name = "Void Crystal Resonator"
	description = "A void Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_void"
	object = "crystal_resonator_void"
	value = { store = 20000 }
	tags = ["furniture"]

[crystal_resonator_pink]
	name = "Pink Crystal Resonator"
	description = "A pink Crystal Resonator. Place it in a room to override its music with a Song Crystal of choice!"
	icon_sprite = "spr_ui_item_object_crystal_resonator_pink"
	object = "crystal_resonator_pink"
	value = { store = 20000 }
	tags = ["furniture"]
