# <---------DECOR ORNATE RUG SET ITEMS------------->

[ornate_rug_small_red]
	icon_sprite = "spr_ui_item_decor_ornate_rug_small_red"
	name = "Ornate Small Rug"
	description = "A small red ornate rug with a rectangular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_small_red"
	tags = ["furniture", "small_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_small"
	crafting_level_requirement = 4
	recipe = [
		{ count = 1, item = "rabbit_wool" },
		{ count = 1, item = "ore_ruby" },
		{ hours = 0, minutes = 20 },
	]

[ornate_rug_medium_round_red]
	icon_sprite = "spr_ui_item_decor_ornate_rug_medium_round_red"
	name = "Ornate Medium Round Rug"
	description = "A medium sized red ornate rug with a circular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_medium_round_red"
	tags = ["furniture", "medium_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_medium_round"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "ore_ruby" },
		{ hours = 0, minutes = 30 },
	]

[ornate_rug_medium_square_red]
	icon_sprite = "spr_ui_item_decor_ornate_rug_medium_square_red"
	name = "Ornate Medium Square Rug"
	description = "A medium sized red ornate rug with a square shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_medium_square_red"
	tags = ["furniture", "medium_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_medium_square"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "ore_ruby" },
		{ hours = 0, minutes = 30 },
	]

[ornate_rug_large_round_red]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_round_red"
	name = "Ornate Large Round Rug"
	description = "A large sized red ornate rug with a round shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_large_round_red"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_round"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "ore_ruby" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_large_square_red]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_square_red"
	name = "Ornate Large Square Rug"
	description = "A large sized red ornate rug with a square shape."
	value = { bin = "self.recipe * 1.1", store = 700 }
	object = "ornate_rug_large_square_red"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_square"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "ore_ruby" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_large_rectangle_red]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_rectangle_red"
	name = "Ornate Large Rectangle Rug"
	description = "A large sized red ornate rug with a rectangular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_large_rectangle_red"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_rectangle"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "ore_ruby" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_small_blue]
	icon_sprite = "spr_ui_item_decor_ornate_rug_small_blue"
	name = "Ornate Small Rug"
	description = "A small blue ornate rug with a rectangular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_small_blue"
	tags = ["furniture", "small_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_small"
	crafting_level_requirement = 4
	recipe = [
		{ count = 1, item = "rabbit_wool" },
		{ count = 1, item = "ore_sapphire" },
		{ hours = 0, minutes = 20 },
	]

[ornate_rug_medium_round_blue]
	icon_sprite = "spr_ui_item_decor_ornate_rug_medium_round_blue"
	name = "Ornate Medium Round Rug"
	description = "A medium sized blue ornate rug with a circular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_medium_round_blue"
	tags = ["furniture", "medium_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_medium_round"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "ore_sapphire" },
		{ hours = 0, minutes = 30 },
	]

[ornate_rug_medium_square_blue]
	icon_sprite = "spr_ui_item_decor_ornate_rug_medium_square_blue"
	name = "Ornate Medium Square Rug"
	description = "A medium sized blue ornate rug with a square shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_medium_square_blue"
	tags = ["furniture", "medium_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_medium_square"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "ore_sapphire" },
		{ hours = 0, minutes = 30 },
	]

[ornate_rug_large_round_blue]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_round_blue"
	name = "Ornate Large Round Rug"
	description = "A large sized blue ornate rug with a round shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_large_round_blue"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_round"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "ore_sapphire" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_large_square_blue]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_square_blue"
	name = "Ornate Large Square Rug"
	description = "A large sized blue ornate rug with a square shape."
	value = { bin = "self.recipe * 1.1", store = 700 }
	object = "ornate_rug_large_square_blue"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_square"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "ore_sapphire" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_large_rectangle_blue]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_rectangle_blue"
	name = "Ornate Large Rectangle Rug"
	description = "A large sized blue ornate rug with a rectangular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_large_rectangle_blue"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_rectangle"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "ore_sapphire" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_small_cream]
	icon_sprite = "spr_ui_item_decor_ornate_rug_small_cream"
	name = "Ornate Small Rug"
	value = { bin = "self.recipe * 1.1" }
	description = "A small cream colored ornate rug with a rectangular shape."
	object = "ornate_rug_small_cream"
	tags = ["furniture", "small_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_small"
	crafting_level_requirement = 4
	recipe = [
		{ count = 1, item = "rabbit_wool" },
		{ count = 1, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]

[ornate_rug_medium_round_cream]
	icon_sprite = "spr_ui_item_decor_ornate_rug_medium_round_cream"
	name = "Ornate Medium Round Rug"
	description = "A medium sized cream colored ornate rug with a circular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_medium_round_cream"
	tags = ["furniture", "medium_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_medium_round"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 30 },
	]

[ornate_rug_medium_square_cream]
	icon_sprite = "spr_ui_item_decor_ornate_rug_medium_square_cream"
	name = "Ornate Medium Square Rug"
	description = "A medium sized cream colored ornate rug with a square shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_medium_square_cream"
	tags = ["furniture", "medium_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_medium_square"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 30 },
	]

[ornate_rug_large_round_cream]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_round_cream"
	name = "Ornate Large Round Rug"
	description = "A large sized cream colored ornate rug with a round shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_large_round_cream"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_round"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "duck_feather" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_large_square_cream]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_square_cream"
	name = "Ornate Large Square Rug"
	description = "A large sized cream colored ornate rug with a square shape."
	value = { bin = "self.recipe * 1.1", store = 700 }
	object = "ornate_rug_large_square_cream"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_square"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "duck_feather" },
		{ hours = 0, minutes = 40 },
	]

[ornate_rug_large_rectangle_cream]
	icon_sprite = "spr_ui_item_decor_ornate_rug_large_rectangle_cream"
	name = "Ornate Large Rectangle Rug"
	description = "A large sized cream colored ornate rug with a rectangular shape."
	value = { bin = "self.recipe * 1.1" }
	object = "ornate_rug_large_rectangle_cream"
	tags = ["furniture", "large_rug", "ornate_rug_set"]
	recipe_key = "ornate_rug_large_rectangle"
	crafting_level_requirement = 8
	recipe = [
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "duck_feather" },
		{ hours = 0, minutes = 40 },
	]
