# <---------DECOR PICNIC SET ITEMS------------->

[picnic_basket_pink]
	icon_sprite = "spr_ui_item_picnic_basket_pink"
	name = "Picnic Basket"
	description = "A cute decorative picnic basket with pink accents."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_basket_pink"
	tags = ["furniture", "misc_outdoor_decor", "picnic_decor_set"]
	recipe_key = "picnic_basket"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "hay" },
		{ count = 1, item = "paper" },
		{ hours = 0, minutes = 20 },
	]

[picnic_basket_yellow]
	icon_sprite = "spr_ui_item_picnic_basket_yellow"
	description = "A cute decorative picnic basket with yellow accents."
	name = "Picnic Basket"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_basket_yellow"
	tags = ["furniture", "misc_outdoor_decor", "picnic_decor_set"]
	recipe_key = "picnic_basket"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "hay" },
		{ count = 1, item = "paper" },
		{ hours = 0, minutes = 20 },
	]

[picnic_basket_red]
	icon_sprite = "spr_ui_item_picnic_basket_red"
	description = "A cute decorative picnic basket with red accents."
	name = "Picnic Basket"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_basket_red"
	tags = ["furniture", "misc_outdoor_decor", "picnic_decor_set"]
	recipe_key = "picnic_basket"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "hay" },
		{ count = 1, item = "paper" },
		{ hours = 0, minutes = 20 },
	]

[picnic_pie_plate_pink]
	icon_sprite = "spr_ui_item_picnic_pie_plate_pink"
	name = "Picnic Display Pie"
	description = "A decorative pie plate with pink accents."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "picnic_pie_plate_pink"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	recipe_key = "picnic_pie_plate"
	crafting_level_requirement = 2
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 1, item = "flour" },
		{ count = 1, item = "sugar" },
		{ hours = 0, minutes = 30 },
	]

[picnic_pie_plate_red]
	icon_sprite = "spr_ui_item_picnic_pie_plate_red"
	name = "Picnic Display Pie"
	description = "A decorative pie plate with red accents."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "picnic_pie_plate_red"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	recipe_key = "picnic_pie_plate"
	crafting_level_requirement = 2
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 1, item = "flour" },
		{ count = 1, item = "sugar" },
		{ hours = 0, minutes = 30 },
	]

[picnic_pie_plate_yellow]
	icon_sprite = "spr_ui_item_picnic_pie_plate_yellow"
	name = "Picnic Display Pie"
	description = "A decorative pie plate with yellow accents."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "picnic_pie_plate_yellow"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	recipe_key = "picnic_pie_plate"
	crafting_level_requirement = 2
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 1, item = "flour" },
		{ count = 1, item = "sugar" },
		{ hours = 0, minutes = 30 },
	]

[picnic_place_setting_red]
	icon_sprite = "spr_ui_item_picnic_place_setting_red"
	name = "Picnic Place Setting"
	description = "A picnic place setting with red accents."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_place_setting_red"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	recipe_key = "picnic_place_setting"
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[picnic_place_setting_yellow]
	icon_sprite = "spr_ui_item_picnic_place_setting_yellow"
	name = "Picnic Place Setting"
	description = "A picnic place setting with yellow accents."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_place_setting_yellow"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	recipe_key = "picnic_place_setting"
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[picnic_place_setting_pink]
	icon_sprite = "spr_ui_item_picnic_place_setting_pink"
	name = "Picnic Place Setting"
	description = "A picnic place setting with pink accents."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_place_setting_pink"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	recipe_key = "picnic_place_setting"
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "iron_ingot" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[picnic_rug_red]
	icon_sprite = "spr_ui_item_picnic_rug_red"
	name = "Picnic Blanket"
	description = "A cute red gingham picnic blanket."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_rug_red"
	tags = ["furniture", "medium_rug", "picnic_decor_set"]
	recipe_key = "picnic_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "fiber" },
		{ count = 5, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[picnic_rug_yellow]
	icon_sprite = "spr_ui_item_picnic_rug_yellow"
	name = "Picnic Blanket"
	description = "A cute yellow gingham picnic blanket."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_rug_yellow"
	tags = ["furniture", "medium_rug", "picnic_decor_set"]
	recipe_key = "picnic_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "fiber" },
		{ count = 5, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[picnic_rug_pink]
	icon_sprite = "spr_ui_item_picnic_rug_pink"
	name = "Picnic Blanket"
	description = "A cute pink gingham picnic blanket."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_rug_pink"
	tags = ["furniture", "medium_rug", "picnic_decor_set"]
	recipe_key = "picnic_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "fiber" },
		{ count = 5, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[picnic_donut_plate]
	icon_sprite = "spr_ui_item_picnic_snack_plate_pink"
	name = "Picnic Display Donuts"
	description = "A decorative donut plate."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "picnic_donut_plate"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "flour" },
		{ hours = 0, minutes = 20 },
	]

[picnic_hamburger_plate]
	icon_sprite = "spr_ui_item_picnic_snack_plate_yellow"
	name = "Picnic Display Burgers"
	description = "A decorative burger plate."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "picnic_hamburger_plate"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "flour" },
		{ hours = 0, minutes = 20 },
	]

[picnic_sandwich_plate]
	icon_sprite = "spr_ui_item_picnic_snack_plate_red"
	name = "Picnic Display Sandwiches"
	description = "A decorative sandwich plate."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "picnic_sandwich_plate"
	tags = ["furniture", "kitchen_decor", "picnic_decor_set"]
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "flour" },
		{ hours = 0, minutes = 20 },
	]

[picnic_sunflower_vase_pink]
	icon_sprite = "spr_ui_item_picnic_sunflower_vase_pink"
	name = "Picnic Sunflower Vase"
	description = "A pretty vase of sunflowers with a pink accent."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_sunflower_vase_pink"
	tags = ["furniture", "tabletop_plant", "picnic_decor_set"]
	recipe_key = "picnic_sunflower_vase"
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 2, item = "sunflower" },
		{ hours = 0, minutes = 20 },
	]

[picnic_sunflower_vase_red]
	icon_sprite = "spr_ui_item_picnic_sunflower_vase_red"
	name = "Picnic Sunflower Vase"
	description = "A pretty vase of sunflowers with a red accent."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_sunflower_vase_red"
	tags = ["furniture", "tabletop_plant", "picnic_decor_set"]
	recipe_key = "picnic_sunflower_vase"
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 2, item = "sunflower" },
		{ hours = 0, minutes = 20 },
	]

[picnic_sunflower_vase_yellow]
	icon_sprite = "spr_ui_item_picnic_sunflower_vase_yellow"
	name = "Picnic Sunflower Vase"
	description = "A pretty vase of sunflowers with a yellow accent."
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "picnic_sunflower_vase_yellow"
	tags = ["furniture", "tabletop_plant", "picnic_decor_set"]
	recipe_key = "picnic_sunflower_vase"
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 2, item = "sunflower" },
		{ hours = 0, minutes = 20 },
	]
