# <---------WORN SET ITEMS (DEFAULT ITEMS THE PLAYER STARTS WITH)------------->


[journal]
	icon_sprite = "spr_ui_item_object_journal"
	name = "Diary"
	value = { bin = "self.recipe * 1.1" }
	object = "journal"
	description = "A simple diary used for recording your journey."
	tags = ["furniture", "journal", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 5, item = "paper" }, { hours = 0, minutes = 20 }]

[worn_bed]
	icon_sprite = "spr_ui_item_furniture_default_bed_v1"
	name = "Worn Bed"
	description = "A worn bed with a cozy old quilt."
	value = { bin = "self.recipe * 1.1", store = 180 }
	object = "worn_bed"
	tags = ["furniture", "single_bed", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [
		{ count = 35, item = "basic_wood" },
		{ count = 3, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[worn_chair]
	icon_sprite = "spr_ui_item_furniture_default_chair_v1"
	name = "Worn Chair"
	description = "A worn wooden chair."
	value = { bin = "self.recipe * 1.1", store = 100 }
	object = "worn_chair"
	tags = ["furniture", "dining_chair", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 20, item = "basic_wood" }, { hours = 0, minutes = 10 }]

[worn_fireplace]
	icon_sprite = "spr_ui_item_furniture_default_fireplace_v1"
	name = "Worn Fireplace"
	description = "A worn stone fireplace."
	value = { bin = "self.recipe * 1.1", store = 180 }
	object = "worn_fireplace"
	tags = ["furniture", "misc_furniture", "default_set"]
	recipe_is_default = true
	crafting_preview_sprite = "spr_ui_furniture_default_fireplace_v1_preview"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 30, item = "ore_stone" },
		{ hours = 0, minutes = 20 },
	]

[worn_nightstand]
	icon_sprite = "spr_ui_item_furniture_default_nightstand_v1"
	name = "Worn Nightstand"
	description = "A worn wooden nightstand."
	value = { bin = "self.recipe * 1.1", store = 80 }
	object = "worn_nightstand"
	tags = ["furniture", "nightstand", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 15, item = "basic_wood" }, { hours = 0, minutes = 10 }]

[worn_table]
	icon_sprite = "spr_ui_item_furniture_default_table_v1"
	name = "Worn Table"
	description = "A worn wooden table."
	value = { bin = "self.recipe * 1.1", store = 90 }
	object = "worn_table"
	tags = ["furniture", "dining_table", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 20, item = "basic_wood" }, { hours = 0, minutes = 10 }]

[worn_window]
	icon_sprite = "spr_ui_item_furniture_default_wall_window_v1"
	name = "Worn Window"
	description = "A worn wooden window."
	value = { bin = "self.recipe * 1.1", store = 80 }
	object = "worn_window"
	tags = ["furniture", "window", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 3, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[worn_wallpaper]
	icon_sprite = "spr_ui_item_furniture_default_wallpaper_v1"
	wallpaper = "default_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	name = "Worn Wallpaper"
	description = "Worn stone wallpaper."
	value = { bin = "self.recipe * 1.1", store = 130 }
	tags = ["furniture", "wallpaper", "default_set"]
	recipe_is_default = true
	crafting_preview_sprite = "spr_ui_furniture_default_wall_v1_preview"
	crafting_level_requirement = 1
	recipe = [{ count = 3, item = "paper" }, { hours = 0, minutes = 10 }]

[worn_flooring]
	name = "Worn Flooring"
	value = { bin = "self.recipe * 1.1", store = 50 }
	description = "Worn wood flooring."
	icon_sprite = "spr_ui_item_furniture_default_flooring_v1"
	flooring = "default_v1"
	tags = ["furniture", "wood_flooring", "default_set"]
	recipe_is_default = true
	crafting_preview_sprite = "spr_ui_furniture_default_floor_v1_preview"
	crafting_level_requirement = 1
	recipe = [{ count = 10, item = "basic_wood" }, { hours = 0, minutes = 10 }]

[worn_well]
	description = "A worn-down well."
	icon_sprite = "spr_ui_item_furniture_worn_well"
	name = "Worn Well"
	value = { bin = "self.recipe * 1.1", store = 60 }
	object = "worn_well"
	tags = ["furniture", "farm_decor", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 10, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

[worn_garden_lamp]
	description = "A worn garden lamp."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_default_worn_garden_light"
	object = "worn_garden_lamp"
	recipe_is_default = true
	name = "Worn Garden Lamp"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "default_set", "floor_lighting"]

[worn_rug]
	description = "A worn green rug."
	icon_sprite = "spr_ui_item_furniture_default_worn_rug"
	name = "Worn Rug"
	value = { bin = "self.recipe * 1.1", store = 100 }
	object = "worn_rug"
	tags = ["furniture", "medium_rug", "default_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 5, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]
