#buy from wheedle only, not craftable

# Deluxe Chest Set

[deluxe_storage_chest_red]
	description = "A red deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_red"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_red"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_orange]
	description = "An orange deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_orange"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_orange"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_gold]
	description = "A gold deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_gold"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_gold"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_green]
	description = "A green deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_green"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_green"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_aqua]
	description = "An aqua deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_aqua"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_aqua"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_blue]
	description = "A blue deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_blue"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_blue"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_purple]
	description = "A purple deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_purple"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_purple"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_pink]
	description = "A pink deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_pink"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_pink"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_black]
	description = "A black deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_black"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_black"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_gray]
	description = "A gray deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_gray"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_gray"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_white]
	description = "A white deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_white"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_white"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_light_brown]
	description = "A light brown deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_light_brown"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_light_brown"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_storage_chest_dark_brown]
	description = "A dark brown deluxe storage chest with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_storage_chest_dark_brown"
	name = "Deluxe Storage Chest"
	object = "deluxe_storage_chest_dark_brown"
	value = { store = 10000, bin = 9000 }
	tags = ["furniture", "deluxe_chest_set"]

	# ICE BOXES

[deluxe_icebox_white]
	description = "A white deluxe icebox with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_icebox_white"
	name = "Deluxe Icebox"
	object = "deluxe_icebox_white"
	value = { store = 12000, bin = 10000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_icebox_pink]
	description = "A pink deluxe icebox with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_icebox_pink"
	name = "Deluxe Icebox"
	object = "deluxe_icebox_pink"
	value = { store = 12000, bin = 10000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_icebox_blue]
	description = "A blue deluxe icebox with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_icebox_blue"
	name = "Deluxe Icebox"
	object = "deluxe_icebox_blue"
	value = { store = 12000, bin = 10000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_icebox_yellow]
	description = "A yellow deluxe icebox with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_icebox_yellow"
	name = "Deluxe Icebox"
	object = "deluxe_icebox_yellow"
	value = { store = 12000, bin = 10000 }
	tags = ["furniture", "deluxe_chest_set"]

[deluxe_icebox_green]
	description = "A green deluxe icebox with an extra-large storage capacity."
	icon_sprite = "spr_ui_item_furniture_deluxe_icebox_green"
	name = "Deluxe Icebox"
	object = "deluxe_icebox_green"
	value = { store = 12000, bin = 10000 }
	tags = ["furniture", "deluxe_chest_set"]
