# <---------DINGY FURNITURE SET------------->

[dingy_flooring_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_flooring_v1"
	name = "Dirty Tiles Flooring"
	description = "This tiled floor has seen better days."
	value = { bin = 1 }
	flooring = "dingy_v1"
	tags = ["furniture", "tile_flooring", "dingy_set"]

[dingy_flooring_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_flooring_v2"
	name = "Dirty Tiles Flooring"
	description = "This tiled floor has seen better days."
	value = { bin = 1 }
	flooring = "dingy_v2"
	tags = ["furniture", "tile_flooring", "dingy_set"]

[dingy_wallpaper_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_wallpaper_v1"
	name = "Peeling Wallpaper"
	description = "A faded and peeling wallpaper."
	value = { bin = 1 }
	wallpaper = "dingy_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	tags = ["furniture", "wallpaper", "dingy_set"]

[dingy_wallpaper_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_wallpaper_v2"
	name = "Peeling Wallpaper"
	description = "A faded and peeling wallpaper."
	value = { bin = 1 }
	wallpaper = "dingy_v2"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	tags = ["furniture", "wallpaper", "dingy_set"]

[dingy_rug_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_tattered_rug_v1"
	name = "Tattered Rug"
	description = "A threadbare and tattered rug."
	value = { bin = 1 }
	object = "dingy_rug_v1"
	tags = ["furniture", "medium_rug", "dingy_set"]

[dingy_rug_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_tattered_rug_v2"
	name = "Tattered Rug"
	description = "A threadbare and tattered rug."
	value = { bin = 1 }
	object = "dingy_rug_v2"
	tags = ["furniture", "medium_rug", "dingy_set"]

[dingy_table_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_rickety_table_v1"
	name = "Rickety Table"
	description = "A table with one leg that's shorter than the others."
	value = { bin = 1 }
	object = "dingy_table_v1"
	tags = ["furniture", "dining_table", "dingy_set"]

[dingy_table_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_rickety_table_v2"
	name = "Rickety Table"
	description = "A table with one leg that's shorter than the others."
	value = { bin = 1 }
	object = "dingy_table_v2"
	tags = ["furniture", "dining_table", "dingy_set"]

[dingy_chair_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_cardboard_box_chair_v1"
	name = "Cardboard Box Chair"
	description = "An improvised chair made from a cardboard box."
	value = { bin = 1 }
	object = "dingy_chair_v1"
	tags = ["furniture", "dining_chair", "dingy_set"]

[dingy_chair_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_cardboard_box_chair_v2"
	name = "Cardboard Box Chair"
	description = "An improvised chair made from a cardboard box."
	value = { bin = 1 }
	object = "dingy_chair_v2"
	tags = ["furniture", "dining_chair", "dingy_set"]

[dingy_couch_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_springs_couch_v1"
	name = "Broken Springs Couch"
	description = "An uncomfortable couch that's beyond repair."
	value = { bin = 1 }
	object = "dingy_couch_v1"
	tags = ["furniture", "sofa", "dingy_set"]

[dingy_couch_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_springs_couch_v2"
	name = "Broken Springs Couch"
	description = "An uncomfortable couch that's beyond repair."
	value = { bin = 1 }
	object = "dingy_couch_v2"
	tags = ["furniture", "sofa", "dingy_set"]

[dingy_window_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_window_v1"
	name = "Broken Window"
	description = "Many of the panes of this window are broken."
	value = { bin = 1 }
	object = "dingy_window_v1"
	tags = ["furniture", "window", "dingy_set"]

[dingy_window_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_window_v2"
	name = "Broken Window"
	description = "Many of the panes of this window are broken."
	value = { bin = 1 }
	object = "dingy_window_v2"
	tags = ["furniture", "window", "dingy_set"]

[dingy_string_lights_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_mostly_broken_string_lights_v1"
	name = "Mostly Broken String Lights"
	description = "These stringlights are nearly useless."
	value = { bin = 1 }
	object = "dingy_string_lights_v1"
	tags = ["furniture", "wall_lighting", "dingy_set"]

[dingy_string_lights_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_mostly_broken_string_lights_v2"
	name = "Mostly Broken String Lights"
	description = "These stringlights are nearly useless."
	value = { bin = 1 }
	object = "dingy_string_lights_v2"
	tags = ["furniture", "wall_lighting", "dingy_set"]

[dingy_broken_plate_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_plate_v1"
	name = "Broken Plate"
	description = "A broken plate."
	value = { bin = 1 }
	object = "dingy_broken_plate_v1"
	tags = ["furniture", "kitchen_decor", "dingy_set"]

[dingy_broken_plate_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_plate_v2"
	name = "Broken Plate"
	description = "A broken plate."
	value = { bin = 1 }
	object = "dingy_broken_plate_v2"
	tags = ["furniture", "kitchen_decor", "dingy_set"]

[dingy_broken_bottle_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_bottle_v1"
	name = "Broken Bottle"
	description = "A broken bottle."
	value = { bin = 1 }
	object = "dingy_broken_bottle_v1"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_broken_bottle_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_broken_bottle_v2"
	name = "Broken Bottle"
	description = "A broken bottle."
	value = { bin = 1 }
	object = "dingy_broken_bottle_v2"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_chipped_cup_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_chipped_cup_v1"
	name = "Chipped Cup"
	description = "A chipped cup."
	value = { bin = 1 }
	object = "dingy_chipped_cup_v1"
	tags = ["furniture", "kitchen_decor", "dingy_set"]

[dingy_chipped_cup_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_chipped_cup_v2"
	name = "Chipped Cup"
	description = "A chipped cup."
	value = { bin = 1 }
	object = "dingy_chipped_cup_v2"
	tags = ["furniture", "kitchen_decor", "dingy_set"]

[dingy_pile_of_newspapers_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_pile_of_newspapers_v1"
	name = "Pile of Newspapers"
	description = "A pile of very old newspapers."
	value = { bin = 1 }
	object = "dingy_pile_of_newspapers_v1"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_pile_of_newspapers_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_pile_of_newspapers_v2"
	name = "Pile of Newspapers"
	description = "A pile of very old newspapers."
	value = { bin = 1 }
	object = "dingy_pile_of_newspapers_v2"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_pile_of_laundry_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_pile_of_laundry_v1"
	name = "Pile of Laundry"
	description = "A messy pile of unfolded laundry."
	value = { bin = 1 }
	object = "dingy_pile_of_laundry_v1"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_pile_of_laundry_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_pile_of_laundry_v2"
	name = "Pile of Laundry"
	description = "A messy pile of unfolded laundry."
	value = { bin = 1 }
	object = "dingy_pile_of_laundry_v2"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_garbage_bag_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_garbage_bag_v1"
	name = "Garbage Bag"
	description = "A full bag of garbage."
	value = { bin = 1 }
	object = "dingy_garbage_bag_v1"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_garbage_bag_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_garbage_bag_v2"
	name = "Garbage Bag"
	description = "A full bag of garbage."
	value = { bin = 1 }
	object = "dingy_garbage_bag_v2"
	tags = ["furniture", "misc_decor", "dingy_set"]

[dingy_mouse_hole_v1]
	icon_sprite = "spr_ui_item_furniture_dingy_mouse_hole_v1"
	name = "Mouse Hole"
	description = "The entrance to a cozy mouse home."
	value = { bin = 1 }
	object = "dingy_mouse_hole_v1"
	tags = ["furniture", "misc_wall_decor", "dingy_set"]

[dingy_mouse_hole_v2]
	icon_sprite = "spr_ui_item_furniture_dingy_mouse_hole_v2"
	name = "Mouse Hole"
	description = "The entrance to a cozy mouse home."
	value = { bin = 1 }
	object = "dingy_mouse_hole_v2"
	tags = ["furniture", "misc_wall_decor", "dingy_set"]
