#------------- WISHING WELL DRAGON SET

[dragon_ruins_pillar_v1]
	name = "Dragon Ruins Pillar"
	description = "A purple pillar with a dragon scale motif."
	icon_sprite = "spr_ui_item_decor_dragon_ruins_pillar_v1"
	value = { bin = 300}
	object = "dragon_ruins_pillar_v1"
	tags = ["furniture", "misc_furniture", "dragon_wishing_well_set"]

[dragon_ruins_pillar_v2]
	name = "Dragon Ruins Pillar"
	description = "A purple pillar with a dragon scale motif and gold accents."
	icon_sprite = "spr_ui_item_decor_dragon_ruins_pillar_v2"
	value = { bin = 300}
	object = "dragon_ruins_pillar_v2"
	tags = ["furniture", "misc_furniture", "dragon_wishing_well_set"]

[dragon_road_wall]
	name = "Dragon Road Wall"
	description = "A purple stone wall modeled after a dragon spine. Place two or more to connect them!"
	icon_sprite = "spr_ui_item_decor_dragon_road_wall"
	value = { bin = 80}
	object = "dragon_road_wall"
	tags = ["furniture", "fencing", "dragon_wishing_well_set"]

[dragon_wall_head_piece]
	name = "Dragon Wall Head Piece"
	description = "A purple stone sculpture of a dragon's head. Can be placed at the end of the Dragon Road Wall."
	icon_sprite = "spr_ui_item_decor_dragon_wall_head_piece"
	value = { bin = 400}
	object = "dragon_wall_head_piece"
	tags = ["furniture", "misc_outdoor_decor", "dragon_wishing_well_set"]

[dragon_wall_tail_piece]
	name = "Dragon Wall Tail Piece"
	description = "A purple stone sculpture of a dragon's tail. Can be placed at the end of the Dragon Road Wall."
	icon_sprite = "spr_ui_item_decor_dragon_wall_tail_piece"
	value = { bin = 400}
	object = "dragon_wall_tail_piece"
	tags = ["furniture", "misc_outdoor_decor", "dragon_wishing_well_set"]

[dragon_talon_chair]
	name = "Talon Chair"
	description = "A purple chair in the shape of a hand with talons."
	icon_sprite = "spr_ui_item_decor_dragon_talon_chair"
	value = { bin = 500}
	object = "dragon_talon_chair"
	tags = ["furniture", "accent_chair", "dragon_wishing_well_set"]

[dragon_water_altar_v1]
	name = "Water Altar"
	description = "A golden water altar."
	icon_sprite = "spr_ui_item_decor_dragon_water_altar_v1"
	value = { bin = 300}
	object = "dragon_water_altar_v1"
	tags = ["furniture", "misc_decor", "dragon_wishing_well_set"]

[dragon_water_altar_v2]
	name = "Water Altar"
	description = "A golden water altar with pink accents."
	icon_sprite = "spr_ui_item_decor_dragon_water_altar_v2"
	value = { bin = 300}
	object = "dragon_water_altar_v2"
	tags = ["furniture", "misc_decor", "dragon_wishing_well_set"]

[dragon_chest]
	name = "Dragon Chest"
	description = "A pink chest decorated with dragon carvings. It has an extra-large storage capacity."
	icon_sprite = "spr_ui_item_decor_dragon_chest"
	value = { bin = 300}
	object = "dragon_chest"
	tags = ["furniture", "chest_and_storage", "dragon_wishing_well_set"]

[dragon_lamp]
	name = "Dragon Lamp"
	description = "A dragon-shaped lamp."
	icon_sprite = "spr_ui_item_decor_dragon_lamp"
	value = { bin = 300}
	object = "dragon_lamp"
	tags = ["furniture", "floor_lighting", "dragon_wishing_well_set"]

[dragon_stained_glass_window_v1]
	name = "Dragon Stained Glass Window"
	description = "A pink stained glass window with dragon figures."
	icon_sprite = "spr_ui_item_decor_dragon_stained_glass_window_v1"

	value = { bin = 300}
	object = "dragon_stained_glass_window_v1"
	tags = ["furniture", "window", "dragon_wishing_well_set"]

[dragon_stained_glass_window_v2]
	name = "Dragon Stained Glass Window"
	description = "A purple stained glass window with dragon figures."
	icon_sprite = "spr_ui_item_decor_dragon_stained_glass_window_v2"
	value = { bin = 300}
	object = "dragon_stained_glass_window_v2"
	tags = ["furniture", "window", "dragon_wishing_well_set"]

[dragon_fireplace]
	name = "Dragon Fireplace"
	description = "A purple and gold fireplace with dragon figures."
	icon_sprite = "spr_ui_item_decor_dragon_fireplace"
	value = { bin = 300}
	object = "dragon_fireplace"
	tags = ["furniture", "misc_furniture", "dragon_wishing_well_set"]

[large_dragon_rug]
	name = "Large Dragon Rug"
	description = "A large purple rug with dragon figures."
	icon_sprite = "spr_ui_item_decor_large_dragon_rug"
	value = { bin = 200}
	object = "large_dragon_rug"
	tags = ["furniture", "large_rug", "dragon_wishing_well_set"]

[medium_dragon_rug]
	name = "Large Dragon Rug"
	description = "A medium pink rug with dragon figures."
	icon_sprite = "spr_ui_item_decor_medium_dragon_rug"
	value = { bin = 200}
	object = "medium_dragon_rug"
	tags = ["furniture", "medium_rug", "dragon_wishing_well_set"]

[dragon_relief_wallpaper]
	name = "Dragon Relief Wallpaper"
	description = "Purple and gold wallpaper with a dragon pattern."
	icon_sprite = "spr_ui_item_decor_dragon_relief_wallpaper"
	value = { bin = 200}
	wallpaper = "wishing_well_dragon"
	tags = ["furniture", "wallpaper", "dragon_wishing_well_set"]

[dragon_mosaic_flooring]
	name = "Dragon Mosaic Flooring"
	description = "Purple flooring with a dragon scale pattern."
	icon_sprite = "spr_ui_item_decor_dragon_mosaic_flooring"
	value = { bin = 200}
	flooring = "wishing_well_dragon"
	tags = ["furniture", "novelty_flooring", "dragon_wishing_well_set"]