# DRAGON ALTAR SET

[dragon_altar_water]
	name = "Dragon Claw Altar"
	description = "A replica dragon claw altar, matching the water seal room."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "ore_silver" },
		{ count = 5, item = "crystal" },
		{ count = 3, item = "monster_wing" },
		{ hours = 0, minutes = 30 },
	]
	object = "dragon_altar_water"
	recipe_key = "dragon_altar"
	icon_sprite = "spr_ui_item_decor_water_seal_altar"
	tags = ['furniture', 'dragon_altar_set', 'misc_decor']

[dragon_altar_earth]
	name = "Dragon Claw Altar"
	description = "A replica dragon claw altar, matching the earth seal room."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "ore_silver" },
		{ count = 5, item = "crystal" },
		{ count = 3, item = "monster_wing" },
		{ hours = 0, minutes = 30 },
	]
	object = "dragon_altar_earth"
	recipe_key = "dragon_altar"
	icon_sprite = "spr_ui_item_decor_earth_seal_altar"
	tags = ['furniture', 'dragon_altar_set', 'misc_decor']

[dragon_altar_fire]
	name = "Dragon Claw Altar"
	description = "A replica dragon claw altar, matching the fire seal room."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "ore_silver" },
		{ count = 5, item = "crystal" },
		{ count = 3, item = "monster_wing" },
		{ hours = 0, minutes = 30 },
	]
	object = "dragon_altar_fire"
	recipe_key = "dragon_altar"
	icon_sprite = "spr_ui_item_decor_fire_seal_altar"
	tags = ['furniture', 'dragon_altar_set', 'misc_decor']


[dragon_altar_ruins]
	name = "Dragon Claw Altar"
	description = "A replica dragon claw altar, matching the ruins seal room."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "ore_silver" },
		{ count = 5, item = "crystal" },
		{ count = 3, item = "monster_wing" },
		{ hours = 0, minutes = 30 },
	]
	object = "dragon_altar_ruins"
	recipe_key = "dragon_altar"
	icon_sprite = "spr_ui_item_decor_ruins_seal_altar"
	tags = ['furniture', 'dragon_altar_set', 'misc_decor']
