[emerald_bed_v1]
	description = "An ornate emerald bed with gold detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_bed_v1"
	name = "Emerald Single Bed"
	object = "emerald_bed_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "emerald_set"]
	recipe_key = "emerald_bed"
	crafting_level_requirement = 36
	recipe = [
		{ count = 15, item = "hard_wood" },
		{ count = 10, item = "ore_emerald" },
		{ count = 5, item = "gold_ingot" },
		{ count = 5, item = "golden_duck_feather" },
		{ hours = 0, minutes = 40 },
	]

[emerald_bed_v2]
	description = "An ornate emerald bed with wood detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_bed_v2"
	name = "Emerald Single Bed"
	object = "emerald_bed_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "emerald_set"]
	recipe_key = "emerald_bed"
	crafting_level_requirement = 36
	recipe = [
		{ count = 15, item = "hard_wood" },
		{ count = 10, item = "ore_emerald" },
		{ count = 3, item = "gold_ingot" },
		{ count = 3, item = "golden_duck_feather" },
		{ hours = 0, minutes = 40 },
	]

[emerald_double_bed_v1]
	description = "An ornate emerald double bed with gold detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_double_bed_v1"
	name = "Emerald Double Bed"
	object = "emerald_double_bed_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "emerald_set"]
	recipe_key = "emerald_bed"
	crafting_level_requirement = 38
	recipe = [
		{ count = 30, item = "hard_wood" },
		{ count = 15, item = "ore_emerald" },
		{ count = 6, item = "gold_ingot" },
		{ count = 6, item = "golden_duck_feather" },
		{ hours = 0, minutes = 40 },
	]

[emerald_double_bed_v2]
	description = "An ornate emerald double bed with wood detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_double_bed_v2"
	name = "Emerald Double Bed"
	object = "emerald_double_bed_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "emerald_set"]
	recipe_key = "emerald_bed"
	crafting_level_requirement = 38
	recipe = [
		{ count = 30, item = "hard_wood" },
		{ count = 15, item = "ore_emerald" },
		{ count = 6, item = "gold_ingot" },
		{ count = 6, item = "golden_duck_feather" },
		{ hours = 0, minutes = 40 },
	]

[emerald_chair_v1]
	description = "An ornate emerald chair with gold detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_chair_v1"
	name = "Emerald Chair"
	object = "emerald_chair_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_chair", "emerald_set"]
	recipe_key = "emerald_chair"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 5, item = "ore_emerald" },
		{ count = 2, item = "gold_ingot" },
		{ count = 2, item = "golden_bristle" },
		{ hours = 0, minutes = 40 },
	]

[emerald_chair_v2]
	description = "An ornate emerald chair with wood detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_chair_v2"
	name = "Emerald Chair"
	object = "emerald_chair_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_chair", "emerald_set"]
	recipe_key = "emerald_chair"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 5, item = "ore_emerald" },
		{ count = 2, item = "gold_ingot" },
		{ count = 2, item = "golden_bristle" },
		{ hours = 0, minutes = 40 },
	]

[emerald_nightstand_v1]
	description = "An ornate emerald nightstand with gold detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_nightstand_v1"
	name = "Emerald Nightstand"
	object = "emerald_nightstand_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "nightstand", "emerald_set"]
	recipe_key = "emerald_nightstand"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 5, item = "ore_emerald" },
		{ count = 3, item = "gold_ingot" },
		{ hours = 0, minutes = 30 },
	]

[emerald_nightstand_v2]
	description = "An ornate emerald nightstand with wood detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_nightstand_v2"
	name = "Emerald Nightstand"
	object = "emerald_nightstand_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "nightstand", "emerald_set"]
	recipe_key = "emerald_nightstand"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 5, item = "ore_emerald" },
		{ count = 3, item = "gold_ingot" },
		{ hours = 0, minutes = 30 },
	]

[emerald_rug_v1]
	description = "An ornate emerald rug with cream detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_rug_v1"
	name = "Emerald Rug"
	object = "emerald_rug_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "medium_rug", "emerald_set"]
	recipe_key = "emerald_rug"
	crafting_level_requirement = 32
	recipe = [
		{ count = 3, item = "ore_emerald" },
		{ count = 3, item = "golden_alpaca_wool" },
		{ count = 3, item = "golden_sheep_wool" },
		{ count = 3, item = "golden_rabbit_wool" },
		{ hours = 0, minutes = 40 },
	]

[emerald_rug_v2]
	description = "An ornate emerald rug with dark green detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_rug_v2"
	name = "Emerald Rug"
	object = "emerald_rug_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "medium_rug", "emerald_set"]
	recipe_key = "emerald_rug"
	crafting_level_requirement = 32
	recipe = [
		{ count = 3, item = "ore_emerald" },
		{ count = 3, item = "golden_alpaca_wool" },
		{ count = 3, item = "golden_sheep_wool" },
		{ count = 3, item = "golden_rabbit_wool" },
		{ hours = 0, minutes = 40 },
	]

[emerald_wallpaper_v1]
	description = "Ornate emerald colored wallpaper with gold detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_wallpaper_v1"
	name = "Emerald Wallpaper"
	wallpaper = "emerald_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	value = { bin = "self.recipe * 1.1" }
	crafting_preview_sprite = "spr_ui_furniture_emerald_wall_v1_preview"
	tags = ["furniture", "wallpaper", "emerald_set"]
	recipe_key = "emerald_wallpaper"
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 5, item = "ore_emerald" },
		{ count = 3, item = "gold_ingot" },
		{ hours = 0, minutes = 30 },
	]

[emerald_wallpaper_v2]
	description = "Ornate cream colored wallpaper with white detailing."
	icon_sprite = "spr_ui_item_furniture_emerald_wallpaper_v2"
	name = "Emerald Wallpaper"
	wallpaper = "emerald_v2"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	value = { bin = "self.recipe * 1.1" }
	crafting_preview_sprite = "spr_ui_furniture_emerald_wall_v2_preview"
	tags = ["furniture", "wallpaper", "emerald_set"]
	recipe_key = "emerald_wallpaper"
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 5, item = "ore_emerald" },
		{ count = 3, item = "gold_ingot" },
		{ hours = 0, minutes = 30 },
	]
