# <---------EXPLORER SET ITEMS (MUSEUM REWARDS)------------->

[explorer_flooring_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_flooring_beige"
	name = "Explorer Flooring"
	description = "Cracked beige tile flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "explorer_v2"
	crafting_preview_sprite = "spr_ui_furniture_explorer_floor_beige_preview"
	tags = ["furniture", "tile_flooring", "explorer_set"]
	recipe_key = "explorer_flooring"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[explorer_flooring_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_flooring_brown"
	name = "Explorer Flooring"
	description = "Cracked gray tile flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "explorer_v1"
	crafting_preview_sprite = "spr_ui_furniture_explorer_floor_brown_preview"
	tags = ["furniture", "tile_flooring", "explorer_set"]
	recipe_key = "explorer_flooring"
	crafting_level_requirement = 1
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 5, item = "sod" },
		{ hours = 0, minutes = 20 },
	]

[explorer_flooring_green]
	icon_sprite = "spr_ui_item_furniture_explorer_flooring_green"
	name = "Explorer Flooring"
	description = "Cracked green-gray tile flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "explorer_v3"
	crafting_preview_sprite = "spr_ui_furniture_explorer_floor_green_preview"
	tags = ["furniture", "tile_flooring", "explorer_set"]
	recipe_key = "explorer_flooring"
	crafting_level_requirement = 1
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 5, item = "sod" },
		{ hours = 0, minutes = 20 },
	]

[explorer_wallpaper_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_wallpaper_beige"
	name = "Explorer Wallpaper"
	description = "A wallpaper that resembles a scholarly beige bookshelf."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "explorer_v2"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_explorer_wall_beige_preview"
	tags = ["furniture", "wallpaper", "explorer_set"]
	recipe_key = "explorer_wallpaper"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 10, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

[explorer_wallpaper_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_wallpaper_brown"
	name = "Explorer Wallpaper"
	description = "A wallpaper that resembles a scholarly brown bookshelf."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "explorer_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_explorer_wall_brown_preview"
	tags = ["furniture", "wallpaper", "explorer_set"]
	recipe_key = "explorer_wallpaper"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 10, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

[explorer_wallpaper_green]
	icon_sprite = "spr_ui_item_furniture_explorer_wallpaper_green"
	name = "Explorer Wallpaper"
	description = "A wallpaper that resembles a scholarly green bookshelf."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "explorer_v3"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_explorer_wall_green_preview"
	tags = ["furniture", "wallpaper", "explorer_set"]
	recipe_key = "explorer_wallpaper"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 10, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

[explorer_bed_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_bed_beige"
	name = "Explorer Bed"
	description = "An explorer's bed with striped brown sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_bed_beige"
	tags = ["furniture", "single_bed", "explorer_set"]
	recipe_key = "explorer_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ count = 1, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[explorer_double_bed_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_double_bed_beige"
	name = "Explorer Double Bed"
	description = "An explorer's double bed with striped brown sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_double_bed_beige"
	tags = ["furniture", "double_bed", "explorer_set"]
	recipe_key = "explorer_double_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "bull_horn" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[explorer_chair_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_chair_beige"
	name = "Explorer Chair"
	description = "A comfy brown explorer's chair."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_chair_beige"
	tags = ["furniture", "accent_chair", "explorer_set"]
	recipe_key = "explorer_chair"
	crafting_level_requirement = 2
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 2, item = "horse_hair" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[explorer_globe_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_globe_beige"
	name = "Explorer Globe"
	description = "A golden explorer's globe."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_globe_beige"
	tags = ["furniture", "misc_furniture", "explorer_set"]
	recipe_key = "explorer_globe"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 5, item = "shard_mass" },
		{ hours = 0, minutes = 20 },
	]

[explorer_lamp_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_lamp_beige"
	name = "Explorer Lamp"
	description = "A brown explorer's standing lamp."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_lamp_beige"
	tags = ["furniture", "floor_lighting", "explorer_set"]
	recipe_key = "explorer_lamp"
	crafting_preview_sprite = "spr_ui_furniture_explorer_lamp_beige_preview"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 1, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[explorer_rug_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_rug_beige"
	name = "Explorer Rug"
	description = "A well-worn brown explorer's rug."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_rug_beige"
	tags = ["furniture", "large_rug", "explorer_set"]
	recipe_key = "explorer_rug"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 1, item = "horse_hair" },
		{ hours = 0, minutes = 20 },
	]

[explorer_trunk_table_beige]
	icon_sprite = "spr_ui_item_furniture_explorer_trunk_table_beige"
	name = "Explorer Trunk Table"
	description = "A sturdy explorer's beige trunk table."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_trunk_table_beige"
	tags = ["furniture", "coffee_table", "explorer_set"]
	recipe_key = "explorer_trunk_table"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[explorer_bed_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_bed_brown"
	name = "Explorer Bed"
	description = "An explorer's bed with striped beige sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_bed_brown"
	tags = ["furniture", "single_bed", "explorer_set"]
	recipe_key = "explorer_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ count = 1, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[explorer_double_bed_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_double_bed_brown"
	name = "Explorer Double Bed"
	description = "An explorer's double bed with striped beige sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_double_bed_brown"
	tags = ["furniture", "double_bed", "explorer_set"]
	recipe_key = "explorer_double_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "bull_horn" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[explorer_chair_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_chair_brown"
	name = "Explorer Chair"
	description = "A comfy beige explorer's chair."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_chair_brown"
	tags = ["furniture", "accent_chair", "explorer_set"]
	recipe_key = "explorer_chair"
	crafting_level_requirement = 2
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 2, item = "horse_hair" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[explorer_globe_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_globe_brown"
	name = "Explorer Globe"
	description = "A gray explorer's globe."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_globe_brown"
	tags = ["furniture", "misc_furniture", "explorer_set"]
	recipe_key = "explorer_globe"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 5, item = "shard_mass" },
		{ hours = 0, minutes = 20 },
	]

[explorer_lamp_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_lamp_brown"
	name = "Explorer Lamp"
	description = "A beige explorer's standing lamp."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_lamp_brown"
	tags = ["furniture", "floor_lighting", "explorer_set"]
	recipe_key = "explorer_lamp"
	crafting_preview_sprite = "spr_ui_furniture_explorer_lamp_brown_preview"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 1, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[explorer_rug_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_rug_brown"
	name = "Explorer Rug"
	description = "A well-worn beige explorer's rug."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_rug_brown"
	tags = ["furniture", "large_rug", "explorer_set"]
	recipe_key = "explorer_rug"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 1, item = "horse_hair" },
		{ hours = 0, minutes = 20 },
	]

[explorer_trunk_table_brown]
	icon_sprite = "spr_ui_item_furniture_explorer_trunk_table_brown"
	name = "Explorer Trunk Table"
	description = "A sturdy explorer's brown trunk table."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_trunk_table_brown"
	tags = ["furniture", "coffee_table", "explorer_set"]
	recipe_key = "explorer_trunk_table"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[explorer_bed_green]
	icon_sprite = "spr_ui_item_furniture_explorer_bed_green"
	name = "Explorer Bed"
	description = "An explorer's bed with striped green sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_bed_green"
	tags = ["furniture", "single_bed", "explorer_set"]
	recipe_key = "explorer_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ count = 1, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[explorer_double_bed_green]
	icon_sprite = "spr_ui_item_furniture_explorer_double_bed_green"
	name = "Explorer Double Bed"
	description = "An explorer's double bed with striped green sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_double_bed_green"
	tags = ["furniture", "double_bed", "explorer_set"]
	recipe_key = "explorer_double_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "bull_horn" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[explorer_chair_green]
	icon_sprite = "spr_ui_item_furniture_explorer_chair_green"
	name = "Explorer Chair"
	description = "A comfy green explorer's chair."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_chair_green"
	tags = ["furniture", "accent_chair", "explorer_set"]
	recipe_key = "explorer_chair"
	crafting_level_requirement = 2
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 2, item = "horse_hair" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[explorer_globe_green]
	icon_sprite = "spr_ui_item_furniture_explorer_globe_green"
	name = "Explorer Globe"
	description = "A green-gray explorer's globe."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_globe_green"
	tags = ["furniture", "misc_furniture", "explorer_set"]
	recipe_key = "explorer_globe"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 5, item = "shard_mass" },
		{ hours = 0, minutes = 20 },
	]

[explorer_lamp_green]
	icon_sprite = "spr_ui_item_furniture_explorer_lamp_green"
	name = "Explorer Lamp"
	description = "A green explorer's standing lamp."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_lamp_green"
	tags = ["furniture", "floor_lighting", "explorer_set"]
	recipe_key = "explorer_lamp"
	crafting_preview_sprite = "spr_ui_furniture_explorer_lamp_green_preview"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 1, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[explorer_rug_green]
	icon_sprite = "spr_ui_item_furniture_explorer_rug_green"
	name = "Explorer Rug"
	description = "A well-worn green explorer's rug."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_rug_green"
	tags = ["furniture", "large_rug", "explorer_set"]
	recipe_key = "explorer_rug"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 1, item = "horse_hair" },
		{ hours = 0, minutes = 20 },
	]

[explorer_trunk_table_green]
	icon_sprite = "spr_ui_item_furniture_explorer_trunk_table_green"
	name = "Explorer Trunk Table"
	description = "A sturdy explorer's green trunk table."
	value = { bin = "self.recipe * 1.1" }
	object = "explorer_trunk_table_green"
	tags = ["furniture", "coffee_table", "explorer_set"]
	recipe_key = "explorer_trunk_table"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]
