[fall_bed_red]
	description = "A cozy single bed with red gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_bed_red"
	name = "Fall Single Bed"
	object = "fall_bed_red"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "fall_set"]
	recipe_key = "fall_single_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]

[fall_bed_orange]
	description = "A cozy single bed with orange gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_bed_orange"
	name = "Fall Single Bed"
	object = "fall_bed_orange"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "fall_set"]
	recipe_key = "fall_single_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]

[fall_bed_yellow]
	description = "A cozy single bed with yellow gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_bed_yellow"
	name = "Fall Single Bed"
	object = "fall_bed_yellow"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "fall_set"]
	recipe_key = "fall_single_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]

[fall_bed_cream]
	description = "A cozy single bed with cream gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_bed_cream"
	name = "Fall Single Bed"
	object = "fall_bed_cream"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "fall_set"]
	recipe_key = "fall_single_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "alpaca_wool" },
		{ count = 3, item = "sheep_wool" },
		{ count = 3, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]

[fall_double_bed_red]
	description = "A cozy double bed with red gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_double_bed_red"
	name = "Fall Double Bed"
	object = "fall_double_bed_red"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "fall_set"]
	recipe_key = "fall_double_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 30, item = "hard_wood" },
		{ count = 5, item = "alpaca_wool" },
		{ count = 5, item = "sheep_wool" },
		{ count = 5, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]

[fall_double_bed_orange]
	description = "A cozy double bed with orange gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_double_bed_orange"
	name = "Fall Double Bed"
	object = "fall_double_bed_orange"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "fall_set"]
	recipe_key = "fall_double_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 30, item = "hard_wood" },
		{ count = 5, item = "alpaca_wool" },
		{ count = 5, item = "sheep_wool" },
		{ count = 5, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]


[fall_double_bed_yellow]
	description = "A cozy double bed with yellow gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_double_bed_yellow"
	name = "Fall Double Bed"
	object = "fall_double_bed_yellow"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "fall_set"]
	recipe_key = "fall_double_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 30, item = "hard_wood" },
		{ count = 5, item = "alpaca_wool" },
		{ count = 5, item = "sheep_wool" },
		{ count = 5, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]


[fall_double_bed_cream]
	description = "A cozy double bed with cream gingham blankets and a built-in shelf."
	icon_sprite = "spr_ui_item_furniture_fall_double_bed_cream"
	name = "Fall Double Bed"
	object = "fall_double_bed_cream"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "fall_set"]
	recipe_key = "fall_double_bed"
	crafting_level_requirement = 26
	recipe = [
		{ count = 30, item = "hard_wood" },
		{ count = 5, item = "alpaca_wool" },
		{ count = 5, item = "sheep_wool" },
		{ count = 5, item = "essence_drop" },
		{ hours = 0, minutes = 40 },
	]


[fall_table_orange]
	description = "A cozy dining table with an orange gingham tablecloth."
	icon_sprite = "spr_ui_item_furniture_fall_table_orange"
	name = "Fall Dining Table"
	object = "fall_table_orange"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_table", "fall_set"]
	recipe_key = "fall_table"
	crafting_level_requirement = 24
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "rabbit_wool" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]

[fall_table_red]
	description = "A cozy dining table with a red gingham tablecloth."
	icon_sprite = "spr_ui_item_furniture_fall_table_red"
	name = "Fall Dining Table"
	object = "fall_table_red"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_table", "fall_set"]
	recipe_key = "fall_table"
	crafting_level_requirement = 24
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "rabbit_wool" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]

[fall_table_yellow]
	description = "A cozy dining table with a yellow gingham tablecloth."
	icon_sprite = "spr_ui_item_furniture_fall_table_yellow"
	name = "Fall Dining Table"
	object = "fall_table_yellow"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_table", "fall_set"]
	recipe_key = "fall_table"
	crafting_level_requirement = 24
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "rabbit_wool" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]

[fall_table_cream]
	description = "A cozy dining table with a cream gingham tablecloth."
	icon_sprite = "spr_ui_item_furniture_fall_table_cream"
	name = "Fall Dining Table"
	object = "fall_table_cream"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_table", "fall_set"]
	recipe_key = "fall_table"
	crafting_level_requirement = 24
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 3, item = "rabbit_wool" },
		{ count = 2, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
