# <---------HAUNTED ATTIC SET ITEMS------------->

[haunted_attic_armoire_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_armoire_dusty"
	name = "Haunted Attic Armoire"
	value = { bin = "self.recipe * 1.1", store = 400 }
	description = "An old fashioned armoire draped in an off-white cloth."
	object = "haunted_attic_armoire_dusty"
	tags = ["furniture", "armoire", "haunted_attic_set"]
	recipe_key = "haunted_attic_armoire"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "alpaca_wool" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_armoire_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_armoire_dark"
	name = "Haunted Attic Armoire"
	value = { bin = "self.recipe * 1.1", store = 400 }
	description = "An old fashioned armoire draped in a purple cloth."
	object = "haunted_attic_armoire_dark"
	tags = ["furniture", "armoire", "haunted_attic_set"]
	recipe_key = "haunted_attic_armoire"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "alpaca_wool" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 20 },
	]


[haunted_attic_bed_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_bed_dusty"
	name = "Haunted Attic Bed"
	value = { bin = "self.recipe * 1.1", store = 600 }
	description = "An old fashioned single bed with a blue-gray patterned cover."
	object = "haunted_attic_bed_dusty"
	tags = ["furniture", "single_bed", "haunted_attic_set"]
	recipe_key = "haunted_attic_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[haunted_attic_bed_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_bed_dark"
	name = "Haunted Attic Bed"
	value = { bin = "self.recipe * 1.1", store = 600 }
	description = "An old fashioned single bed with a purple patterned cover."
	object = "haunted_attic_bed_dark"
	tags = ["furniture", "single_bed", "haunted_attic_set"]
	recipe_key = "haunted_attic_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "bull_horn" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[haunted_attic_candle_single]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_candle_1"
	name = "Melted Candle"
	value = { bin = "self.recipe * 1.1", store = 250 }
	description = "A single off-white candle that looks partially melted."
	object = "haunted_attic_candle_single"
	tags = ["furniture", "table_lighting", "haunted_attic_set"]
	recipe_key = "haunted_attic_candle_single"
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "peat" },
		{ count = 1, item = "oil" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_candle_single_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_candle_1_dark"
	name = "Melted Candle"
	value = { bin = "self.recipe * 1.1", store = 250 }
	description = "A single purple candle that looks partially melted."
	object = "haunted_attic_candle_single_dark"
	tags = ["furniture", "table_lighting", "haunted_attic_set"]
	recipe_key = "haunted_attic_candle_single"
	crafting_level_requirement = 2
	recipe = [
		{ count = 1, item = "peat" },
		{ count = 1, item = "oil" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_candle_cluster]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_candle_3"
	name = "Melted Candle Cluster"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "A group of off-white candles that look partially melted."
	object = "haunted_attic_candle_cluster"
	tags = ["furniture", "table_lighting", "haunted_attic_set"]
	recipe_key = "haunted_attic_candle_cluster"
	crafting_level_requirement = 4
	recipe = [
		{ count = 2, item = "peat" },
		{ count = 1, item = "oil" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_candle_cluster_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_candle_3_dark"
	name = "Melted Candle Cluster"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "A group of purple candles that look partially melted."
	object = "haunted_attic_candle_cluster_dark"
	tags = ["furniture", "table_lighting", "haunted_attic_set"]
	recipe_key = "haunted_attic_candle_cluster"
	crafting_level_requirement = 4
	recipe = [
		{ count = 2, item = "peat" },
		{ count = 1, item = "oil" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_chair_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_chair_dusty"
	name = "Haunted Attic Chair"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "An old fashioned chair with a blue-gray patterned seat."
	object = "haunted_attic_chair_dusty"
	tags = ["furniture", "dining_chair", "haunted_attic_set"]
	recipe_key = "haunted_attic_chair"
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "fiber" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_chair_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_chair_dark"
	name = "Haunted Attic Chair"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "An old fashioned chair with a purple patterned seat."
	object = "haunted_attic_chair_dark"
	tags = ["furniture", "dining_chair", "haunted_attic_set"]
	recipe_key = "haunted_attic_chair"
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "fiber" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_double_bed_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_double_bed_dusty"
	name = "Haunted Attic Double Bed"
	value = { bin = "self.recipe * 1.1", store = 800 }
	description = "An old fashioned double bed with a blue-gray patterned cover."
	object = "haunted_attic_double_bed_dusty"
	tags = ["furniture", "double_bed", "haunted_attic_set"]
	recipe_key = "haunted_attic_double_bed"
	crafting_level_requirement = 10
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 5, item = "cattail" },
		{ count = 2, item = "bull_horn" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[haunted_attic_double_bed_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_double_bed_dark"
	name = "Haunted Attic Double Bed"
	value = { bin = "self.recipe * 1.1", store = 800 }
	description = "An old fashioned double bed with a purple patterned cover."
	object = "haunted_attic_double_bed_dark"
	tags = ["furniture", "double_bed", "haunted_attic_set"]
	recipe_key = "haunted_attic_double_bed"
	crafting_level_requirement = 10
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 5, item = "cattail" },
		{ count = 2, item = "bull_horn" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[haunted_attic_dress_form_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_dress_form_dusty"
	name = "Haunted Attic Dress Form"
	value = { bin = "self.recipe * 1.1", store = 350 }
	description = "An old fashioned off-white dress form."
	object = "haunted_attic_dress_form_dusty"
	tags = ["furniture", "misc_furniture", "haunted_attic_set"]
	recipe_key = "haunted_attic_dress_form"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_dress_form_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_dress_form_dark"
	name = "Haunted Attic Dress Form"
	value = { bin = "self.recipe * 1.1", store = 350 }
	description = "An old fashioned purple dress form."
	object = "haunted_attic_dress_form_dark"
	tags = ["furniture", "misc_furniture", "haunted_attic_set"]
	recipe_key = "haunted_attic_dress_form"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "rabbit_wool" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_nightstand_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_nightstand_dusty"
	name = "Haunted Attic Nightstand"
	value = { bin = "self.recipe * 1.1", store = 350 }
	description = "An old fashioned nightstand with a dusty warm-tone color."
	object = "haunted_attic_nightstand_dusty"
	tags = ["furniture", "nightstand", "haunted_attic_set"]
	recipe_key = "haunted_attic_nightstand"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_nightstand_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_nightstand_dark"
	name = "Haunted Attic Nightstand"
	value = { bin = "self.recipe * 1.1", store = 350 }
	description = "An old fashioned nightstand with a dusty cool-tone color."
	object = "haunted_attic_nightstand_dark"
	tags = ["furniture", "nightstand", "haunted_attic_set"]
	recipe_key = "haunted_attic_nightstand"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_rocking_chair_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_rocking_chair_dusty"
	name = "Haunted Attic Rocking Chair"
	value = { bin = "self.recipe * 1.1", store = 500 }
	description = "An old fashioned rocking chair with a blue-gray patterned seat."
	object = "haunted_attic_rocking_chair_dusty"
	tags = ["furniture", "misc_seating", "haunted_attic_set"]
	recipe_key = "haunted_attic_rocking_chair"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 2, item = "sheep_wool" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[haunted_attic_rocking_chair_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_rocking_chair_dark"
	name = "Haunted Attic Rocking Chair"
	value = { bin = "self.recipe * 1.1", store = 500 }
	description = "An old fashioned rocking chair with a purple patterned seat."
	object = "haunted_attic_rocking_chair_dark"
	tags = ["furniture", "misc_seating", "haunted_attic_set"]
	recipe_key = "haunted_attic_rocking_chair"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 2, item = "sheep_wool" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 40 },
	]


[haunted_attic_table_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_table_dusty"
	name = "Haunted Attic Table"
	value = { bin = "self.recipe * 1.1", store = 500 }
	description = "An old fashioned table with a patched off-white tablecloth."
	object = "haunted_attic_table_dusty"
	tags = ["furniture", "dining_table", "haunted_attic_set"]
	recipe_key = "haunted_attic_table"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "sheep_wool" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_table_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_table_dark"
	name = "Haunted Attic Table"
	value = { bin = "self.recipe * 1.1", store = 500 }
	description = "An old fashioned table with a patched purple tablecloth."
	object = "haunted_attic_table_dark"
	tags = ["furniture", "dining_table", "haunted_attic_set"]
	recipe_key = "haunted_attic_table"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 1, item = "sheep_wool" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_wall_cobweb_left]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_cobweb_left"
	name = "Cobweb Left"
	value = { bin = "self.recipe * 1.1", store = 150 }
	description = "A decorative white cobweb, left version."
	object = "haunted_attic_wall_cobweb_left"
	tags = ["furniture", "misc_wall_decor", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_cobweb_left"
	crafting_level_requirement = 1
	recipe = [
		{ count = 2, item = "monster_powder" },
		{ count = 2, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_wall_cobweb_left_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_cobweb_left_dark"
	name = "Cobweb Left"
	value = { bin = "self.recipe * 1.1", store = 150 }
	description = "A decorative purple cobweb, left version."
	object = "haunted_attic_wall_cobweb_left_dark"
	tags = ["furniture", "misc_wall_decor", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_cobweb_left"
	crafting_level_requirement = 1
	recipe = [
		{ count = 2, item = "monster_powder" },
		{ count = 2, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_wall_cobweb_right]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_cobweb_right"
	name = "Cobweb Right"
	value = { bin = "self.recipe * 1.1", store = 150 }
	description = "A decorative white cobweb, right version."
	object = "haunted_attic_wall_cobweb_right"
	tags = ["furniture", "misc_wall_decor", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_cobweb_right"
	crafting_level_requirement = 1
	recipe = [
		{ count = 2, item = "monster_powder" },
		{ count = 2, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_wall_cobweb_right_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_cobweb_right_dark"
	name = "Cobweb Right"
	value = { bin = "self.recipe * 1.1", store = 150 }
	description = "A decorative purple cobweb, right version."
	object = "haunted_attic_wall_cobweb_right_dark"
	tags = ["furniture", "misc_wall_decor", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_cobweb_right"
	crafting_level_requirement = 1
	recipe = [
		{ count = 2, item = "monster_powder" },
		{ count = 2, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_wall_shelf_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_wall_shelf_dusty"
	name = "Haunted Attic Wall Shelf"
	value = { bin = "self.recipe * 1.1", store = 250 }
	description = "A strangely decorated wall shelf with a dusty warm-tone color."
	object = "haunted_attic_wall_shelf_dusty"
	tags = ["furniture", "wall_shelf", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_shelf"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 3, item = "paper" },
		{ count = 3, item = "shards" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_wall_shelf_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_wall_shelf_dark"
	name = "Haunted Attic Wall Shelf"
	value = { bin = "self.recipe * 1.1", store = 250 }
	description = "A strangely decorated wall shelf with a dusty cool-tone color."
	object = "haunted_attic_wall_shelf_dark"
	tags = ["furniture", "wall_shelf", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_shelf"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 3, item = "paper" },
		{ count = 3, item = "shards" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_wall_window_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_wall_window_dusty"
	name = "Haunted Attic Window"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "An old fashioned arched window with a dusty warm-tone color."
	object = "haunted_attic_wall_window_dusty"
	tags = ["furniture", "window", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_window"
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_wall_window_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_wall_window_dark"
	name = "Haunted Attic Window"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "An old fashioned arched window with a dusty cool-tone color."
	object = "haunted_attic_wall_window_dark"
	tags = ["furniture", "window", "haunted_attic_set"]
	recipe_key = "haunted_attic_wall_window"
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 1, item = "iron_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 30 },
	]

[haunted_attic_wallpaper_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_wallpaper_dusty"
	name = "Haunted Attic Wallpaper"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "An old fashioned off-white wallpaper with wood beams."
	wallpaper = "haunted_attic_dusty"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_haunted_attic_wall_dusty_preview"
	tags = ["furniture", "wallpaper", "haunted_attic_set"]
	recipe_key = "haunted_attic_wallpaper"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 2, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_wallpaper_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_wallpaper_dark"
	name = "Haunted Attic Wallpaper"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "An old fashioned purple wallpaper with wood beams."
	wallpaper = "haunted_attic_dark"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_haunted_attic_wall_dark_preview"
	tags = ["furniture", "wallpaper", "haunted_attic_set"]
	recipe_key = "haunted_attic_wallpaper"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 2, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]

[haunted_attic_flooring_dusty]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_flooring_dusty"
	name = "Haunted Attic Flooring"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "Old fashioned herringbone flooring with a dusty warm-tone color."
	flooring = "haunted_attic_dusty"
	crafting_preview_sprite = "spr_ui_furniture_haunted_attic_floor_dusty_preview"
	tags = ["furniture", "wood_flooring", "haunted_attic_set"]
	recipe_key = "haunted_attic_flooring"
	crafting_level_requirement = 2
	recipe = [{ count = 25, item = "basic_wood" }, { hours = 0, minutes = 20 }]

[haunted_attic_flooring_dark]
	icon_sprite = "spr_ui_item_furniture_haunted_attic_flooring_dark"
	name = "Haunted Attic Flooring"
	value = { bin = "self.recipe * 1.1", store = 300 }
	description = "Old fashioned herringbone flooring with a dusty cool-tone color."
	flooring = "haunted_attic_dark"
	crafting_preview_sprite = "spr_ui_furniture_haunted_attic_floor_dark_preview"
	tags = ["furniture", "wood_flooring", "haunted_attic_set"]
	recipe_key = "haunted_attic_flooring"
	crafting_level_requirement = 2
	recipe = [{ count = 25, item = "basic_wood" }, { hours = 0, minutes = 20 }]
