
# KITCHEN SET DECOR

[kitchen_scale_yellow]
	icon_sprite = "spr_ui_item_decor_kitchen_scale_yellow"
	name = "Kitchen Scale"
	description = "A decorative yellow kitchen scale."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_scale_yellow"
	recipe_key = "kitchen_scale"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_scale_pink]
	icon_sprite = "spr_ui_item_decor_kitchen_scale_pink"
	name = "Kitchen Scale"
	description = "A decorative pink kitchen scale."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_scale_pink"
	recipe_key = "kitchen_scale"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_scale_orange]
	icon_sprite = "spr_ui_item_decor_kitchen_scale_orange"
	name = "Kitchen Scale"
	description = "A decorative orange kitchen scale."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_scale_orange"
	recipe_key = "kitchen_scale"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_scale_blue]
	icon_sprite = "spr_ui_item_decor_kitchen_scale_blue"
	name = "Kitchen Scale"
	description = "A decorative blue kitchen scale."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_scale_blue"
	recipe_key = "kitchen_scale"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_utensil_holder_pink]
	icon_sprite = "spr_ui_item_decor_kitchen_utensil_holder_pink"
	name = "Utensil Holder"
	description = "A decorative pink utensil holder."
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "kitchen_utensil_holder_pink"
	recipe_key = "kitchen_utensil_holder"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 4, item = "clay" },
		{ hours = 0, minutes = 30 },
	]

[kitchen_utensil_holder_white]
	icon_sprite = "spr_ui_item_decor_kitchen_utensil_holder_white"
	name = "Utensil Holder"
	description = "A decorative white utensil holder."
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "kitchen_utensil_holder_white"
	recipe_key = "kitchen_utensil_holder"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 4, item = "clay" },
		{ hours = 0, minutes = 30 },
	]

[kitchen_utensil_holder_green]
	icon_sprite = "spr_ui_item_decor_kitchen_utensil_holder_green"
	name = "Utensil Holder"
	description = "A decorative green utensil holder."
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "kitchen_utensil_holder_green"
	recipe_key = "kitchen_utensil_holder"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 4, item = "clay" },
		{ hours = 0, minutes = 30 },
	]

[kitchen_utensil_holder_blue]
	icon_sprite = "spr_ui_item_decor_kitchen_utensil_holder_blue"
	name = "Utensil Holder"
	description = "A decorative blue utensil holder."
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "kitchen_utensil_holder_blue"
	recipe_key = "kitchen_utensil_holder"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 4, item = "clay" },
		{ hours = 0, minutes = 30 },
	]

[kitchen_salt_and_pepper_shakers]
	icon_sprite = "spr_ui_item_decor_kitchen_salt_and_pepper_shakers"
	name = "Salt & Pepper Shakers"
	description = "A decorative salt & pepper shaker set."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_salt_and_pepper_shakers"
	recipe_key = "kitchen_salt_and_pepper_shakers"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 16
	recipe = [
		{ count = 2, item = "rock_salt" },
		{ count = 2, item = "chili_pepper" },
		{ hours = 0, minutes = 10 },
	]

[kitchen_herb_planter_v1]
	icon_sprite = "spr_ui_item_decor_kitchen_herb_planter_v1"
	name = "Herb Planter"
	description = "A decorative white and blue herb planter."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_herb_planter_v1"
	recipe_key = "kitchen_herb_planter"
	tags = ["furniture", "kitchen_decor", "tabletop_plant", "kitchen_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 2, item = "oregano" },
		{ count = 2, item = "sage" },
		{ count = 2, item = "sod" },
		{ count = 2, item = "clay" },
		{ hours = 0, minutes = 40 },
	]

[kitchen_herb_planter_v2]
	icon_sprite = "spr_ui_item_decor_kitchen_herb_planter_v2"
	name = "Herb Planter"
	description = "A decorative gold and green herb planter."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_herb_planter_v2"
	recipe_key = "kitchen_herb_planter"
	tags = ["furniture", "kitchen_decor", "tabletop_plant", "kitchen_set"]
	crafting_level_requirement = 24
	recipe = [
		{ count = 2, item = "basil" },
		{ count = 2, item = "thyme" },
		{ count = 2, item = "sod" },
		{ count = 2, item = "clay" },
		{ hours = 0, minutes = 40 },
	]

[kitchen_oil_and_vinegar_basket_v1]
	icon_sprite = "spr_ui_item_decor_kitchen_oil_and_vinegar_basket_v1"
	name = "Oil & Vinegar Basket"
	description = "A decorative white oil & vinegar basket."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_oil_and_vinegar_basket_v1"
	recipe_key = "kitchen_oil_and_vinegar_basket"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 2, item = "oil" },
		{ count = 2, item = "white_wine" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_oil_and_vinegar_basket_v2]
	icon_sprite = "spr_ui_item_decor_kitchen_oil_and_vinegar_basket_v2"
	name = "Oil & Vinegar Basket"
	description = "A decorative brown oil & vinegar basket."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_oil_and_vinegar_basket_v2"
	recipe_key = "kitchen_oil_and_vinegar_basket"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 2, item = "oil" },
		{ count = 2, item = "white_wine" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_mixing_bowls_v1]
	icon_sprite = "spr_ui_item_decor_kitchen_mixing_bowls_v1"
	name = "Mixing Bowls"
	description = "A set of decorative blue mixing bowls."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_mixing_bowls_v1"
	recipe_key = "kitchen_mixing_bowls"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 5, item = "crystal" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_mixing_bowls_v2]
	icon_sprite = "spr_ui_item_decor_kitchen_mixing_bowls_v2"
	name = "Mixing Bowls"
	description = "A set of decorative green and gold mixing bowls."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_mixing_bowls_v2"
	recipe_key = "kitchen_mixing_bowls"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 5, item = "crystal" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_mixing_bowls_v3]
	icon_sprite = "spr_ui_item_decor_kitchen_mixing_bowls_v3"
	name = "Mixing Bowls"
	description = "A set of decorative pink and white mixing bowls."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_mixing_bowls_v3"
	recipe_key = "kitchen_mixing_bowls"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 5, item = "crystal" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_mixing_bowls_v4]
	icon_sprite = "spr_ui_item_decor_kitchen_mixing_bowls_v4"
	name = "Mixing Bowls"
	description = "A set of decorative orange, yellow, and white mixing bowls."
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "kitchen_mixing_bowls_v4"
	recipe_key = "kitchen_mixing_bowls"
	tags = ["furniture", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 22
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 5, item = "crystal" },
		{ hours = 0, minutes = 20 },
	]

[kitchen_garlic_braid]
	icon_sprite = "spr_ui_item_decor_kitchen_garlic_braid"
	name = "Garlic Braid"
	description = "A decorative braid of garlic that can be hung on your wall."
	value = { bin = "self.recipe * 1.1", store = 500 }
	object = "kitchen_garlic_braid"
	recipe_key = "kitchen_garlic_braid"
	tags = ["furniture", "kitchen_decor", "misc_wall_decor", "kitchen_set"]
	crafting_level_requirement = 18
	recipe = [
		{ count = 4, item = "garlic" },
		{ hours = 0, minutes = 10 },
	]

[kitchen_hanging_onion_basket]
	icon_sprite = "spr_ui_item_decor_kitchen_hanging_onion_basket"
	name = "Hanging Onion Basket"
	description = "A decorative onion basket that can be hung on your wall."
	value = { bin = "self.recipe * 1.1", store = 500 }
	object = "kitchen_hanging_onion_basket"
	recipe_key = "kitchen_hanging_onion_basket"
	tags = ["furniture", "kitchen_decor", "misc_wall_decor", "kitchen_set"]
	crafting_level_requirement = 18
	recipe = [
		{ count = 4, item = "onion" },
		{ hours = 0, minutes = 10 },
	]

	# Champions Kitchen

[champions_kitchen_blue]
	description = "A blue champion's kitchen used for making 1-5 star dishes."
	icon_sprite = "spr_ui_item_kitchen_tier_3_champion_blue"
	minimum_cooking_level = 30
	name = "Champion's Kitchen"
	object = "champions_kitchen_blue"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "champions_kitchen"
	tags = ["furniture", "misc_functional", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 60
	recipe = [
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "iron_ingot" },
		{ count = 2, item = "silver_ingot" },
		{ count = 2, item = "gold_ingot" },
		{ count = 10, item = "peat" },
		{ hours = 0, minutes = 50 },
	]

[champions_kitchen_pink]
	description = "A pink champion's kitchen used for making 1-5 star dishes."
	icon_sprite = "spr_ui_item_kitchen_tier_3_champion_pink"
	minimum_cooking_level = 30
	name = "Champion's Kitchen"
	object = "champions_kitchen_pink"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "champions_kitchen"
	tags = ["furniture", "misc_functional", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 60
	recipe = [
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "iron_ingot" },
		{ count = 2, item = "silver_ingot" },
		{ count = 2, item = "gold_ingot" },
		{ count = 10, item = "peat" },
		{ hours = 0, minutes = 50 },
	]

[champions_kitchen_yellow]
	description = "A gold champion's kitchen used for making 1-5 star dishes."
	icon_sprite = "spr_ui_item_kitchen_tier_3_champion_yellow"
	minimum_cooking_level = 30
	name = "Champion's Kitchen"
	object = "champions_kitchen_yellow"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "champions_kitchen"
	tags = ["furniture", "misc_functional", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 60
	recipe = [
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "iron_ingot" },
		{ count = 2, item = "silver_ingot" },
		{ count = 2, item = "gold_ingot" },
		{ count = 10, item = "peat" },
		{ hours = 0, minutes = 50 },
	]

[champions_kitchen_green]
	description = "A green champion's kitchen used for making 1-5 star dishes."
	icon_sprite = "spr_ui_item_kitchen_tier_3_champion_green"
	minimum_cooking_level = 30
	name = "Champion's Kitchen"
	object = "champions_kitchen_green"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "champions_kitchen"
	tags = ["furniture", "misc_functional", "kitchen_decor", "kitchen_set"]
	crafting_level_requirement = 60
	recipe = [
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "iron_ingot" },
		{ count = 2, item = "silver_ingot" },
		{ count = 2, item = "gold_ingot" },
		{ count = 10, item = "peat" },
		{ hours = 0, minutes = 50 },
	]

	# CHAMPIONS COUNTERS

[counter_kitchen_pink]
	name = "Champion's Kitchen Counter"
	description = "A pink kitchen counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_kitchen_pink"
	value = { bin = "self.recipe * 1.1" }
	object = "counter_kitchen_pink"
	recipe_key = "counter_kitchen"
	crafting_level_requirement = 40
	crafting_preview_sprite = "spr_ui_decor_counter_kitchen_preview_pink"
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_kitchen_blue]
	name = "Champion's Kitchen Counter"
	description = "A blue kitchen counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_kitchen_blue"
	value = { bin = "self.recipe * 1.1" }
	object = "counter_kitchen_blue"
	recipe_key = "counter_kitchen"
	crafting_level_requirement = 40
	crafting_preview_sprite = "spr_ui_decor_counter_kitchen_preview_blue"
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_kitchen_yellow]
	name = "Champion's Kitchen Counter"
	description = "A gold kitchen counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_kitchen_yellow"
	value = { bin = "self.recipe * 1.1" }
	object = "counter_kitchen_yellow"
	recipe_key = "counter_kitchen"
	crafting_level_requirement = 40
	crafting_preview_sprite = "spr_ui_decor_counter_kitchen_preview_yellow"
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]

[counter_kitchen_green]
	name = "Champion's Kitchen Counter"
	description = "A green kitchen counter piece. Place two or more together to connect them!"
	icon_sprite = "spr_ui_item_decor_counter_kitchen_green"
	value = { bin = "self.recipe * 1.1" }
	object = "counter_kitchen_green"
	recipe_key = "counter_kitchen"
	crafting_level_requirement = 40
	crafting_preview_sprite = "spr_ui_decor_counter_kitchen_preview_green"
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "counters", "counter_set"]
