# <---------LAVA CAVE SET ITEMS ------------>

[lava_caves_diamond_rock]
	icon_sprite = "spr_ui_item_furniture_diamond_rock"
	name = "Ornamental Diamond Rock"
	description = "A decorative diamond rock."
	value = { bin = "self.recipe * 1.1" }
	object = "lava_caves_diamond_rock"
	crafting_level_requirement = 18
	recipe = [
		{ count = 3, item = "ore_diamond" },
		{ count = 3, item = "refined_stone" },
		{ count = 2, item = "glass" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "lava_set", "misc_furniture"]

[lava_caves_gold_node]
	icon_sprite = "spr_ui_item_furniture_gold_node"
	name = "Ornamental Gold Node"
	description = "A decorative gold node."
	value = { bin = "self.recipe * 1.1" }
	object = "lava_caves_gold_node"
	crafting_level_requirement = 18
	recipe = [
		{ count = 10, item = "ore_gold" },
		{ count = 5, item = "refined_stone" },
		{ count = 2, item = "monster_whisker" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "lava_set", "misc_furniture"]

[lava_caves_stone_arch]
	icon_sprite = "spr_ui_item_furniture_lava_caves_stone_beam"
	name = "Lava Rock Arch"
	description = "A stone arch from the Lava Caves."
	value = { bin = "self.recipe * 1.1" }
	object = "lava_caves_stone_arch"
	crafting_level_requirement = 18
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "obsidian" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "lava_set", "misc_outdoor_decor"]

[lava_caves_wallpaper]
	icon_sprite = "spr_ui_item_furniture_lava_caves_wallpaper"
	name = "Lava Rock Wall"
	description = "A wallpaper that mimics the look of the Lava Caves."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "lava"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_wallpaper_lava_caves_preview"
	crafting_level_requirement = 20
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 2, item = "monster_whisker" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "lava_set", "wallpaper"]

[lava_caves_flooring]
	icon_sprite = "spr_ui_item_furniture_lava_caves_flooring"
	name = "Lava Rock Floor"
	description = "A rock floor that mimics the look of the Lava Caves."
	value = { bin = "self.recipe * 1.1" }
	flooring = "lava"
	crafting_preview_sprite = "spr_ui_furniture_flooring_lava_caves_preview"
	crafting_level_requirement = 18
	recipe = [
		{ count = 10, item = "obsidian" },
		{ count = 2, item = "refined_stone" },
		{ count = 2, item = "monster_whisker" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "lava_set", "novelty_flooring"]

[lava_caves_obsidian_fence_purple]
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_fence_purple"
	name = "Obsidian Fence"
	description = "A piece of purple-black obsidian fencing."
	value = { bin = "self.recipe * 1.1" }
	object = "lava_caves_obsidian_fence_purple"
	crafting_preview_sprite = "spr_ui_furniture_lava_caves_obsidian_fence_preview_purple"
	crafting_level_requirement = 20
	recipe_key = "lava_caves_fence"
	recipe = [
		{ count = 2, item = "obsidian" },
		{ count = 1, item = "sap" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "lava_set", "fencing"]

[lava_caves_obsidian_fence_blue]
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_fence_blue"
	name = "Obsidian Fence"
	description = "A piece of blue-black obsidian fencing."
	value = { bin = "self.recipe * 1.1" }
	object = "lava_caves_obsidian_fence_blue"
	crafting_preview_sprite = "spr_ui_furniture_lava_caves_obsidian_fence_preview_blue"
	crafting_level_requirement = 20
	recipe_key = "lava_caves_fence"
	recipe = [
		{ count = 2, item = "obsidian" },
		{ count = 1, item = "sap" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "lava_set", "fencing"]

[lava_caves_obsidian_bed_blue]
	description = "A luxurious bed with an obsidian headboard and blue-black quilted blankets."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_bed_blue"
	name = "Obsidian Bed"
	object = "lava_caves_obsidian_bed_blue"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "lava_set"]
	recipe_key = "lava_caves_bed"
	crafting_level_requirement = 30
	recipe = [
		{ count = 25, item = "obsidian" },
		{ count = 15, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ count = 4, item = "alpaca_wool" },
		{ count = 4, item = "monster_whisker" },
		{ hours = 0, minutes = 50 },
	]

[lava_caves_obsidian_bed_purple]
	description = "A luxurious bed with an obsidian headboard and purple-black quilted blankets."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_bed_purple"
	name = "Obsidian Bed"
	object = "lava_caves_obsidian_bed_purple"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "lava_set"]
	recipe_key = "lava_caves_bed"
	crafting_level_requirement = 30
	recipe = [
		{ count = 25, item = "obsidian" },
		{ count = 15, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ count = 4, item = "alpaca_wool" },
		{ count = 4, item = "monster_whisker" },
		{ hours = 0, minutes = 50 },
	]

[lava_caves_obsidian_double_bed_blue]
	description = "A luxurious bed with an obsidian headboard and blue-black quilted blankets."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_double_bed_blue"
	name = "Obsidian Double Bed"
	object = "lava_caves_obsidian_double_bed_blue"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "lava_set"]
	recipe_key = "lava_caves_bed"
	crafting_level_requirement = 30
	recipe = [
		{ count = 30, item = "obsidian" },
		{ count = 25, item = "hard_wood" },
		{ count = 15, item = "refined_stone" },
		{ count = 6, item = "alpaca_wool" },
		{ count = 6, item = "monster_whisker" },
		{ hours = 0, minutes = 50 },
	]

[lava_caves_obsidian_double_bed_purple]
	description = "A luxurious bed with an obsidian headboard and purple-black quilted blankets."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_double_bed_purple"
	name = "Obsidian Double Bed"
	object = "lava_caves_obsidian_double_bed_purple"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "lava_set"]
	recipe_key = "lava_caves_bed"
	crafting_level_requirement = 30
	recipe = [
		{ count = 30, item = "obsidian" },
		{ count = 25, item = "hard_wood" },
		{ count = 15, item = "refined_stone" },
		{ count = 6, item = "alpaca_wool" },
		{ count = 6, item = "monster_whisker" },
		{ hours = 0, minutes = 50 },
	]

[lava_caves_obsidian_chair_blue]
	description = "A faceted blue-black obsidian chair."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_chair_blue"
	name = "Obsidian Chair"
	object = "lava_caves_obsidian_chair_blue"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_chair", "lava_set"]
	recipe_key = "lava_caves_chair"
	crafting_level_requirement = 26
	recipe = [
		{ count = 20, item = "obsidian" },
		{ count = 10, item = "hard_wood" },
		{ count = 5, item = "refined_stone" },
		{ count = 4, item = "ore_gold" },
		{ hours = 0, minutes = 40 },
	]

[lava_caves_obsidian_chair_purple]
	description = "A faceted purple-black obsidian chair."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_chair_purple"
	name = "Obsidian Chair"
	object = "lava_caves_obsidian_chair_purple"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "dining_chair", "lava_set"]
	recipe_key = "lava_caves_chair"
	crafting_level_requirement = 26
	recipe = [
		{ count = 20, item = "obsidian" },
		{ count = 10, item = "hard_wood" },
		{ count = 5, item = "refined_stone" },
		{ count = 4, item = "ore_gold" },
		{ hours = 0, minutes = 40 },
	]

[lava_caves_obsidian_table_blue]
	description = "A faceted blue-black obsidian table."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_table_blue"
	name = "Obsidian Table"
	object = "lava_caves_obsidian_table_blue"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "coffee_table", "lava_set"]
	recipe_key = "lava_caves_table"
	crafting_level_requirement = 28
	recipe = [
		{ count = 25, item = "obsidian" },
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "ore_gold" },
		{ hours = 0, minutes = 30 },
	]

[lava_caves_obsidian_table_purple]
	description = "A faceted purple-black obsidian table."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_table_purple"
	name = "Obsidian Table"
	object = "lava_caves_obsidian_table_purple"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "coffee_table", "lava_set"]
	recipe_key = "lava_caves_table"
	crafting_level_requirement = 28
	recipe = [
		{ count = 25, item = "obsidian" },
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "ore_gold" },
		{ hours = 0, minutes = 30 },
	]

[lava_caves_obsidian_storage_chest_blue]
	description = "A faceted blue-black obsidian storage chest with a large storage capacity."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_storage_chest_blue"
	name = "Obsidian Storage Chest"
	object = "lava_caves_obsidian_storage_chest_blue"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "chest_and_storage", "lava_set"]
	recipe_key = "lava_caves_chest"
	crafting_level_requirement = 26
	recipe = [
		{ count = 15, item = "obsidian" },
		{ count = 10, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ count = 4, item = "ore_gold" },
		{ hours = 0, minutes = 40 },
	]

[lava_caves_obsidian_storage_chest_purple]
	description = "A faceted purple-black obsidian storage chest with a large storage capacity."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_storage_chest_purple"
	name = "Obsidian Storage Chest"
	object = "lava_caves_obsidian_storage_chest_purple"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "chest_and_storage", "lava_set"]
	recipe_key = "lava_caves_chest"
	crafting_level_requirement = 26
	recipe = [
		{ count = 15, item = "obsidian" },
		{ count = 10, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ count = 4, item = "ore_gold" },
		{ hours = 0, minutes = 40 },
	]

[lava_caves_obsidian_floor_lamp_blue]
	description = "A faceted blue-black obsidian floor lamp."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_floor_lamp_blue"
	name = "Obsidian Floor Lamp"
	object = "lava_caves_obsidian_floor_lamp_blue"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "floor_lighting", "lava_set"]
	recipe_key = "lava_caves_floor_lamp"
	crafting_preview_sprite = "spr_ui_furniture_lava_caves_obsidian_floor_lamp_blue_preview"
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "obsidian" },
		{ count = 2, item = "refined_stone" },
		{ count = 2, item = "monster_core" },
		{ count = 1, item = "monster_whisker" },
		{ hours = 0, minutes = 40 },
	]

[lava_caves_obsidian_floor_lamp_purple]
	description = "A faceted purple-black obsidian floor lamp."
	icon_sprite = "spr_ui_item_furniture_lava_caves_obsidian_floor_lamp_purple"
	name = "Obsidian Floor Lamp"
	object = "lava_caves_obsidian_floor_lamp_purple"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "floor_lighting", "lava_set"]
	recipe_key = "lava_caves_floor_lamp"
	crafting_preview_sprite = "spr_ui_furniture_lava_caves_obsidian_floor_lamp_purple_preview"
	crafting_level_requirement = 24
	recipe = [
		{ count = 10, item = "obsidian" },
		{ count = 2, item = "refined_stone" },
		{ count = 2, item = "monster_core" },
		{ count = 1, item = "monster_whisker" },
		{ hours = 0, minutes = 40 },
	]
