[lemon_wallpaper]
	icon_sprite = "spr_ui_item_furniture_lemon_wallpaper"
	name = "Lemon Wallpaper"
	description = "A pale yellow wallpaper with a cute lemon print."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "lemon"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_lemon_wall_preview"
	tags = ["furniture", "wallpaper", "lemon_set"]
	recipe_key = "lemon_wallpaper"
	crafting_level_requirement = 14
	recipe = [
		{ count = 3, item = "lemon" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 20 },
	]


[lemon_flooring]
	icon_sprite = "spr_ui_item_furniture_lemon_flooring"
	name = "Lemon Flooring"
	description = "Pretty lemon flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "lemon"
	crafting_preview_sprite = "spr_ui_furniture_lemon_floor_preview"
	tags = ["furniture", "carpet_flooring", "lemon_set"]
	recipe_key = "lemon_flooring"
	crafting_level_requirement = 14
	recipe = [
		{ count = 3, item = "lemon" },
		{ count = 1, item = "rabbit_wool" },
		{ hours = 0, minutes = 20 },
	]

[lemon_rug]
	icon_sprite = "spr_ui_item_furniture_lemon_rug"
	name = "Lemon Rug"
	description = "A cute rug shaped like a lemon slice."
	value = { bin = "self.recipe * 1.1" }
	object = "lemon_rug"
	tags = ["furniture", "medium_rug", "lemon_set"]
	recipe_key = "lemon_rug"
	crafting_level_requirement = 14
	recipe = [
		{ count = 3, item = "lemon" },
		{ count = 1, item = "rabbit_wool" },
		{ hours = 0, minutes = 20 },
	]


[lemon_stool]
	icon_sprite = "spr_ui_item_furniture_lemon_stool"
	name = "Lemon Stool"
	description = "A stool shaped like half of a lemon."
	value = { bin = "self.recipe * 1.1" }
	object = "lemon_stool"
	tags = ["furniture", "stool", "lemon_set"]
	recipe_key = "lemon_stool"
	crafting_level_requirement = 16
	recipe = [
		{ count = 4, item = "lemon" },
		{ count = 3, item = "hard_wood" },
		{ hours = 0, minutes = 20 },
	]

[lemon_table]
	icon_sprite = "spr_ui_item_furniture_lemon_table"
	name = "Lemon Table"
	description = "A table shaped like a slice of lemon."
	value = { bin = "self.recipe * 1.1" }
	object = "lemon_table"
	tags = ["furniture", "dining_table", "lemon_set"]
	recipe_key = "lemon_table"
	crafting_level_requirement = 16
	recipe = [
		{ count = 6, item = "lemon" },
		{ count = 5, item = "hard_wood" },
		{ hours = 0, minutes = 20 },
	]

[lemon_table_lamp]
	icon_sprite = "spr_ui_item_furniture_lemon_table_lamp"
	name = "Lemon Table Lamp"
	description = "A cute lemon-shaped lamp."
	value = { bin = "self.recipe * 1.1" }
	object = "lemon_table_lamp"
	tags = ["furniture", "table_lighting", "lemon_set"]
	recipe_key = "lemon_table_lamp"
	crafting_preview_sprite = "spr_ui_furniture_lemon_table_lamp_preview"
	crafting_level_requirement = 16
	recipe = [
		{ count = 4, item = "lemon" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[lemon_fruit_bowl]
	icon_sprite = "spr_ui_item_furniture_lemon_fruit_bowl"
	name = "Lemon Fruit Bowl"
	description = "A decorative bowl full of lemons."
	value = { bin = "self.recipe * 1.1" }
	object = "lemon_fruit_bowl"
	tags = ["furniture", "kitchen_decor", "lemon_set"]
	recipe_key = "lemon_fruit_bowl"
	crafting_level_requirement = 14
	recipe = [
		{ count = 4, item = "lemon" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 20 },
	]

[lemon_bonsai]
	icon_sprite = "spr_ui_item_furniture_lemon_bonsai"
	name = "Lemon Bonsai"
	description = "A decorative miniature lemon tree."
	value = { bin = "self.recipe * 1.1" }
	object = "lemon_bonsai"
	tags = ["furniture", "potted_tree", "lemon_set"]
	recipe_key = "lemon_bonsai"
	crafting_level_requirement = 16
	recipe = [
		{ count = 1, item = "sapling_lemon" },
		{ count = 1, item = "sod" },
		{ count = 3, item = "clay" },
		{ hours = 0, minutes = 30 },
	]
