# <---------LOVELY COTTAGE ITEMS------------->

[lovely_cottage_scroll_bundle]
	name = "Lovely Cottage Scroll Bundle"
	description = "Use this scroll to unlock the crafting recipes for the Lovely Cottage furniture set!"
	icon_sprite = "spr_ui_item_setscroll_lovelycottage"
	soulbind = "forever"
	set_unlock = "lovely_cottage_set"
	value = { store = 1000 }
	tags = ["scroll", "blacklist_popup"]

[cottage_bed_oak]
	description = "A lovely single bed with soft pink floral sheets."
	icon_sprite = "spr_ui_item_furniture_cottage_bed_v1"
	name = "Lovely Cottage Single Bed"
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "cottage_bed_white"
	tags = ["furniture", "single_bed", "lovely_cottage_set"]
	recipe_key = "cottage_bed"
	crafting_level_requirement = 10
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 5, item = "feather" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[cottage_bed_ash]
	description = "A lovely single bed with white floral sheets."
	icon_sprite = "spr_ui_item_furniture_cottage_bed_v2"
	name = "Lovely Cottage Single Bed"
	value = { bin = "self.recipe * 1.1", store = 600 }
	object = "cottage_bed_pink"
	tags = ["furniture", "single_bed", "lovely_cottage_set"]
	recipe_key = "cottage_bed"
	crafting_level_requirement = 10
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 5, item = "feather" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[cottage_chair_oak]
	description = "A lovely oak wood chair with a soft pink cushion."
	icon_sprite = "spr_ui_item_furniture_cottage_chair_v1"
	name = "Lovely Cottage Chair"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_chair_pink"
	tags = ["furniture", "dining_chair", "lovely_cottage_set"]
	recipe_key = "cottage_chair"
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[cottage_chair_ash]
	description = "A lovely ash wood chair with a sage green cushion."
	icon_sprite = "spr_ui_item_furniture_cottage_chair_v2"
	name = "Lovely Cottage Chair"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_chair_white"
	tags = ["furniture", "dining_chair", "lovely_cottage_set"]
	recipe_key = "cottage_chair"
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[cottage_bed_double_oak]
	description = "A lovely double bed with soft pink floral sheets."
	icon_sprite = "spr_ui_item_furniture_cottage_double_bed_v1"
	name = "Lovely Cottage Double Bed"
	value = { bin = "self.recipe * 1.1", store = 800 }
	object = "cottage_double_bed_white"
	tags = ["furniture", "double_bed", "lovely_cottage_set"]
	recipe_key = "cottage_bed_double"
	crafting_level_requirement = 12
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 10, item = "cattail" },
		{ count = 5, item = "feather" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[cottage_bed_double_ash]
	description = "A lovely double bed with white floral sheets."
	icon_sprite = "spr_ui_item_furniture_cottage_double_bed_v2"
	name = "Lovely Cottage Double Bed"
	value = { bin = "self.recipe * 1.1", store = 800 }
	object = "cottage_double_bed_pink"
	tags = ["furniture", "double_bed", "lovely_cottage_set"]
	recipe_key = "cottage_bed_double"
	crafting_level_requirement = 12
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 10, item = "cattail" },
		{ count = 5, item = "feather" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[cottage_dresser_oak]
	description = "A lovely dresser painted antique white and sage green."
	icon_sprite = "spr_ui_item_furniture_cottage_dresser_v1"
	name = "Lovely Cottage Dresser"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_dresser_white"
	tags = ["furniture", "drawer", "lovely_cottage_set"]
	recipe_key = "cottage_dresser"
	crafting_level_requirement = 8
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[cottage_dresser_ash]
	description = "A lovely dresser painted antique white and soft pink."
	icon_sprite = "spr_ui_item_furniture_cottage_dresser_v2"
	name = "Lovely Cottage Dresser"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_dresser_pink"
	tags = ["furniture", "drawer", "lovely_cottage_set"]
	recipe_key = "cottage_dresser"
	crafting_level_requirement = 8
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[cottage_flooring_oak]
	description = "Lovely oak wood flooring for your dream cottage."
	icon_sprite = "spr_ui_item_furniture_cottage_flooring_v1"
	name = "Lovely Cottage Flooring"
	value = { bin = "self.recipe * 1.1", store = 200 }
	flooring = "cottage_v1"
	crafting_preview_sprite = "spr_ui_furniture_cottage_floor_v1_preview"
	tags = ["furniture", "wood_flooring", "lovely_cottage_set"]
	recipe_key = "cottage_flooring"
	crafting_level_requirement = 2
	recipe = [{ count = 25, item = "basic_wood" }, { hours = 0, minutes = 20 }]

[cottage_flooring_ash]
	description = "Lovely ash wood flooring for your dream cottage."
	icon_sprite = "spr_ui_item_furniture_cottage_flooring_v2"
	name = "Lovely Cottage Flooring"
	value = { bin = "self.recipe * 1.1", store = 200 }
	flooring = "cottage_v2"
	crafting_preview_sprite = "spr_ui_furniture_cottage_floor_v2_preview"
	tags = ["furniture", "wood_flooring", "lovely_cottage_set"]
	recipe_key = "cottage_flooring"
	crafting_level_requirement = 2
	recipe = [{ count = 25, item = "basic_wood" }, { hours = 0, minutes = 20 }]

[cottage_nightstand_oak]
	description = "A lovely nightstand painted antique white and sage green."
	icon_sprite = "spr_ui_item_furniture_cottage_nightstand_v1"
	name = "Lovely Cottage Nightstand"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_nightstand_green"
	tags = ["furniture", "nightstand", "lovely_cottage_set"]
	recipe_key = "cottage_nightstand"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[cottage_nightstand_ash]
	description = "A lovely nightstand painted antique white and soft pink."
	icon_sprite = "spr_ui_item_furniture_cottage_nightstand_v2"
	name = "Lovely Cottage Nightstand"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_nightstand_pink"
	tags = ["furniture", "nightstand", "lovely_cottage_set"]
	recipe_key = "cottage_nightstand"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "ore_stone" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[cottage_plant_shelf_oak]
	description = "A lovely oak wood & antique white plant shelf."
	icon_sprite = "spr_ui_item_furniture_cottage_plant_shelf_v1"
	name = "Lovely Cottage Plant Shelf"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "cottage_plant_shelf_tall"
	tags = ["furniture", "misc_plant", "lovely_cottage_set"]
	recipe_key = "cottage_plant_shelf"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 4, item = "clay" },
		{ count = 4, item = "sod" },
		{ hours = 0, minutes = 30 },
	]

[cottage_plant_shelf_ash]
	description = "A lovely ash wood & antique white plant shelf."
	icon_sprite = "spr_ui_item_furniture_cottage_plant_shelf_v2"
	name = "Lovely Cottage Plant Shelf"
	value = { bin = "self.recipe * 1.1", store = 400 }
	object = "cottage_plant_shelf_wide"
	tags = ["furniture", "misc_plant", "lovely_cottage_set"]
	recipe_key = "cottage_plant_shelf"
	crafting_level_requirement = 4
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 4, item = "clay" },
		{ count = 4, item = "sod" },
		{ hours = 0, minutes = 30 },
	]

[cottage_potted_fig_oak]
	description = "A lovely fig tree in an antique white & oak wood base."
	icon_sprite = "spr_ui_item_furniture_cottage_potted_fig_v1"
	name = "Lovely Cottage Potted Fig"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "cottage_potted_fig"
	tags = ["furniture", "potted_tree", "lovely_cottage_set"]
	recipe_key = "cottage_potted_fig"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 2, item = "clay" },
		{ count = 2, item = "sod" },
		{ hours = 0, minutes = 30 },
	]

[cottage_potted_fig_ash]
	description = "A lovely fig tree in a brown & ash wood base."
	icon_sprite = "spr_ui_item_furniture_cottage_potted_fig_v2"
	name = "Lovely Cottage Potted Fig"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "cottage_potted_fiddle_leaf"
	tags = ["furniture", "potted_tree", "lovely_cottage_set"]
	recipe_key = "cottage_potted_fig"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "basic_wood" },
		{ count = 2, item = "clay" },
		{ count = 2, item = "sod" },
		{ hours = 0, minutes = 30 },
	]

[cottage_rug_oak]
	description = "A lovely antique white rug with green and pink accents."
	icon_sprite = "spr_ui_item_furniture_cottage_rug_v1"
	name = "Lovely Cottage Rug"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_rug_green"
	tags = ["furniture", "medium_rug", "lovely_cottage_set"]
	recipe_key = "cottage_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 10, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[cottage_rug_ash]
	description = "A lovely pink rug with green and white accents."
	icon_sprite = "spr_ui_item_furniture_cottage_rug_v2"
	name = "Lovely Cottage Rug"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_rug_pink"
	tags = ["furniture", "medium_rug", "lovely_cottage_set"]
	recipe_key = "cottage_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 10, item = "cattail" },
		{ hours = 0, minutes = 20 },
	]

[cottage_table_oak]
	description = "A lovely oak wood table with a scalloped edge."
	icon_sprite = "spr_ui_item_furniture_cottage_table_v1"
	name = "Lovely Cottage Table"
	value = { bin = "self.recipe * 1.1", store = 500 }
	object = "cottage_table_wood"
	tags = ["furniture", "dining_table", "lovely_cottage_set"]
	recipe_key = "cottage_table"
	crafting_level_requirement = 8
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 10, item = "ore_stone" },
		{ count = 1, item = "copper_ingot" },
		{ count = 10, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[cottage_table_ash]
	description = "A lovely table with an antique white & sage green tablecloth."
	icon_sprite = "spr_ui_item_furniture_cottage_table_v2"
	name = "Lovely Cottage Table"
	value = { bin = "self.recipe * 1.1", store = 500 }
	object = "cottage_table_white"
	tags = ["furniture", "dining_table", "lovely_cottage_set"]
	recipe_key = "cottage_table"
	crafting_level_requirement = 8
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 10, item = "ore_stone" },
		{ count = 1, item = "copper_ingot" },
		{ count = 10, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[cottage_wall_flowers_oak]
	description = "A lovely bouquet of dried yellow flowers to hang on your wall."
	icon_sprite = "spr_ui_item_furniture_cottage_wall_flowers_v1"
	name = "Lovely Cottage Wall Flowers"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "cottage_wall_flowers_green"
	tags = ["furniture", "wall_hanging", "lovely_cottage_set"]
	recipe_key = "cottage_wall_flowers"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 2, item = "hay" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 30 },
	]

[cottage_wall_flowers_ash]
	description = "A lovely bouquet of dried pink flowers to hang on your wall."
	icon_sprite = "spr_ui_item_furniture_cottage_wall_flowers_v2"
	name = "Lovely Cottage Wall Flowers"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "cottage_wall_flowers_pink"
	tags = ["furniture", "wall_hanging", "lovely_cottage_set"]
	recipe_key = "cottage_wall_flowers"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 2, item = "hay" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 30 },
	]

[cottage_wall_window_oak]
	description = "A lovely oak wood window dressed in white curtains with a pink trim."
	icon_sprite = "spr_ui_item_furniture_cottage_wall_window_v1"
	name = "Lovely Cottage Window"
	value = { bin = "self.recipe * 1.1", store = 350 }
	object = "cottage_wall_window_white"
	tags = ["furniture", "window", "lovely_cottage_set"]
	recipe_key = "cottage_wall_window"
	crafting_level_requirement = 6
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 1, item = "copper_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 30 },
	]

[cottage_wall_window_ash]
	description = "A lovely ash wood window dressed in pink curtains with a white trim."
	icon_sprite = "spr_ui_item_furniture_cottage_wall_window_v2"
	name = "Lovely Cottage Window"
	value = { bin = "self.recipe * 1.1", store = 350 }
	object = "cottage_wall_window_pink"
	tags = ["furniture", "window", "lovely_cottage_set"]
	recipe_key = "cottage_wall_window"
	crafting_level_requirement = 6
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 1, item = "copper_ingot" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 30 },
	]

[cottage_wallpaper_oak]
	description = "Lovely antique white and oak panel wallpaper for your dream cottage."
	icon_sprite = "spr_ui_item_furniture_cottage_wallpaper_v1"
	name = "Lovely Cottage Wallpaper"
	value = { bin = "self.recipe * 1.1", store = 200 }
	wallpaper = "cottage_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_cottage_wall_v1_preview"
	tags = ["furniture", "wallpaper", "lovely_cottage_set"]
	recipe_key = "cottage_wallpaper"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 15, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

[cottage_wallpaper_ash]
	description = "Lovely sage green and ash panel wallpaper for your dream cottage."
	icon_sprite = "spr_ui_item_furniture_cottage_wallpaper_v2"
	name = "Lovely Cottage Wallpaper"
	value = { bin = "self.recipe * 1.1", store = 200 }
	wallpaper = "cottage_v2"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_cottage_wall_v2_preview"
	tags = ["furniture", "wallpaper", "lovely_cottage_set"]
	recipe_key = "cottage_wallpaper"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 15, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

	# NEW ADDITIONS

[cottage_fridge_oak]
	description = "A lovely white icebox with a large storage capacity."
	icon_sprite = "spr_ui_item_furniture_cottage_fridge_v1"
	name = "Lovely Cottage Icebox"
	value = { bin = "self.recipe * 1.1", store = 1000 }
	object = "cottage_fridge_v1"
	tags = ["furniture", "chest_and_storage", "lovely_cottage_set"]
	recipe_key = "cottage_fridge"
	crafting_level_requirement = 10
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 2, item = "ice_block" },
		{ hours = 0, minutes = 20 },
	]

[cottage_fridge_ash]
	description = "A lovely soft pink icebox with a large storage capacity."
	icon_sprite = "spr_ui_item_furniture_cottage_fridge_v2"
	name = "Lovely Cottage Icebox"
	value = { bin = "self.recipe * 1.1", store = 1000 }
	object = "cottage_fridge_v2"
	tags = ["furniture", "chest_and_storage", "lovely_cottage_set"]
	recipe_key = "cottage_fridge"
	crafting_level_requirement = 10
	recipe = [
		{ count = 2, item = "iron_ingot" },
		{ count = 2, item = "ice_block" },
		{ hours = 0, minutes = 20 },
	]

[cottage_potted_flowers_oak]
	description = "A lovely pot of white flowers."
	icon_sprite = "spr_ui_item_furniture_cottage_potted_flowers_v1"
	name = "Lovely Cottage Potted Flowers"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_potted_flowers_v1"
	tags = ["furniture", "tabletop_plant", "lovely_cottage_set"]
	recipe_key = "cottage_potted_flowers"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 1, item = "small_grass_starter" },
		{ hours = 0, minutes = 20 },
	]

[cottage_potted_flowers_ash]
	description = "A lovely pot of soft pink flowers."
	icon_sprite = "spr_ui_item_furniture_cottage_potted_flowers_v2"
	name = "Lovely Cottage Potted Flowers"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "cottage_potted_flowers_v2"
	tags = ["furniture", "tabletop_plant", "lovely_cottage_set"]
	recipe_key = "cottage_potted_flowers"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "clay" },
		{ count = 1, item = "small_grass_starter" },
		{ hours = 0, minutes = 20 },
	]
