[mermaid_bed_v1]
	description = "A purple & mint mermaid bed with a shell headboard and gold trim."
	icon_sprite = "spr_ui_item_furniture_mermaid_bed_v1"
	name = "Mermaid Single Bed"
	object = "mermaid_bed_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "mermaid_set"]
	recipe_key = "mermaid_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 3, item = "gold_ingot" },
		{ count = 4, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]

[mermaid_bed_v2]
	description = "A pink & purple mermaid bed with a shell headboard and gold trim."
	icon_sprite = "spr_ui_item_furniture_mermaid_bed_v2"
	name = "Mermaid Single Bed"
	object = "mermaid_bed_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "mermaid_set"]
	recipe_key = "mermaid_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 3, item = "gold_ingot" },
		{ count = 4, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]


[mermaid_bed_v3]
	description = "A pink & mint mermaid bed with a shell headboard and gold trim."
	icon_sprite = "spr_ui_item_furniture_mermaid_bed_v3"
	name = "Mermaid Single Bed"
	object = "mermaid_bed_v3"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "single_bed", "mermaid_set"]
	recipe_key = "mermaid_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "hard_wood" },
		{ count = 3, item = "gold_ingot" },
		{ count = 4, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]


[mermaid_double_bed_v1]
	description = "A purple & mint mermaid double bed with a shell headboard and gold trim."
	icon_sprite = "spr_ui_item_furniture_mermaid_double_bed_v1"
	name = "Mermaid Double Bed"
	object = "mermaid_double_bed_v1"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "mermaid_set"]
	recipe_key = "mermaid_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 6, item = "gold_ingot" },
		{ count = 4, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]


[mermaid_double_bed_v2]
	description = "A pink & purple mermaid double bed with a shell headboard and gold trim."
	icon_sprite = "spr_ui_item_furniture_mermaid_double_bed_v2"
	name = "Mermaid Double Bed"
	object = "mermaid_double_bed_v2"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "mermaid_set"]
	recipe_key = "mermaid_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 6, item = "gold_ingot" },
		{ count = 4, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]

[mermaid_double_bed_v3]
	description = "A pink & mint mermaid double bed with a shell headboard and gold trim."
	icon_sprite = "spr_ui_item_furniture_mermaid_double_bed_v3"
	name = "Mermaid Double Bed"
	object = "mermaid_double_bed_v3"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "mermaid_set"]
	recipe_key = "mermaid_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 6, item = "gold_ingot" },
		{ count = 4, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]
