# <---------MINESHAFT SET ITEMS (UPPER MINES BIOME)------------>

[mines_wooden_arch]
	icon_sprite = "spr_ui_item_furniture_mines_wooden_arch"
	name = "Mines Arch"
	description = "A wooden mineshaft arch."
	object = "mines_wooden_arch"
	value = { bin = "self.recipe * 1.1" }
	crafting_level_requirement = 6
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "sap" },
		{ count = 3, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "misc_outdoor_decor"]

[miners_copper_node]
	description = "A decorative copper node."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_copper_node"
	object = "miners_copper_node"
	name = "Ornamental Copper Node"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 10, item = "ore_copper" },
		{ count = 3, item = "monster_powder" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "misc_furniture"]

[miners_ruby_rock]
	description = "A decorative ruby rock."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_ruby_rock"
	object = "miners_ruby_rock"
	name = "Ornamental Ruby Rock"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "ore_ruby" },
		{ count = 3, item = "red_toadstool" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "misc_furniture"]

[miners_minecart_v1]
	description = "A decorative minecart with a worn look."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_minecart_v1"
	object = "miners_minecart_v1"
	name = "Minecart"
	recipe_key = "minecart"
	crafting_level_requirement = 4
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "misc_furniture"]

[miners_minecart_v2]
	description = "A decorative minecart with a clean look."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_minecart_v2"
	object = "miners_minecart_v2"
	name = "Minecart"
	recipe_key = "minecart"
	crafting_level_requirement = 4
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "misc_furniture"]

[miners_crate_chair_v1]
	description = "A crate-like chair with a warm-tone hue."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_crate_chair_v1"
	object = "miners_crate_chair_v1"
	name = "Mines Crate Chair"
	recipe_key = "miners_crate_chair"
	crafting_level_requirement = 2
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "sap" },
		{ count = 3, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "stool"]

[miners_crate_chair_v2]
	description = "A crate-like chair with a cool-tone hue."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_crate_chair_v2"
	object = "miners_crate_chair_v2"
	name = "Mines Crate Chair"
	recipe_key = "miners_crate_chair"
	crafting_level_requirement = 2
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "sap" },
		{ count = 3, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "stool"]

[miners_crate_chest_v1]
	description = "A crate-like storage chest with a warm-tone hue."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_crate_chest_v1"
	object = "miners_crate_chest_v1"
	name = "Mines Storage Chest"
	recipe_key = "miners_crate_chest"
	crafting_level_requirement = 2
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 10, item = "ore_stone" },
		{ count = 2, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "chest_and_storage"]

[miners_crate_chest_v2]
	description = "A crate-like storage chest with a cool-tone hue."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_crate_chest_v2"
	object = "miners_crate_chest_v2"
	name = "Mines Storage Chest"
	recipe_key = "miners_crate_chest"
	crafting_level_requirement = 2
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 10, item = "ore_stone" },
		{ count = 2, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "chest_and_storage"]

[miners_floor_lamp_v1]
	description = "A mineshaft floor lamp with a clean look."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_floor_lamp_v1"
	object = "miners_floor_lamp_v1"
	name = "Mines Floor Lamp"
	recipe_key = "miners_floor_lamp"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "floor_lighting"]

[miners_floor_lamp_v2]
	description = "A mineshaft floor lamp with a worn look."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_floor_lamp_v2"
	object = "miners_floor_lamp_v2"
	name = "Mines Floor Lamp"
	recipe_key = "miners_floor_lamp"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "floor_lighting"]

[miners_wall_lamp_v1]
	description = "A mineshaft wall lamp with a clean look."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_wall_lamp_v1"
	object = "miners_wall_lamp_v1"
	name = "Mines Wall Lamp"
	recipe_key = "miners_wall_lamp"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "wall_lighting"]

[miners_wall_lamp_v2]
	description = "A mineshaft wall lamp with a worn look."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_wall_lamp_v2"
	object = "miners_wall_lamp_v2"
	name = "Mines Wall Lamp"
	recipe_key = "miners_wall_lamp"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "wall_lighting"]

[miners_shelves_v1]
	description = "Industrial shelves with a warm-tone hue."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_shelves_v1"
	object = "miners_shelves_v1"
	name = "Mines Shelf"
	recipe_key = "miners_shelves"
	crafting_level_requirement = 6
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 10, item = "ore_stone" },
		{ count = 5, item = "ore_copper" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "mineshaft_set", "bookshelf"]

[miners_shelves_v2]
	description = "Industrial shelves with a cool-tone hue."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_miners_shelves_v2"
	object = "miners_shelves_v2"
	name = "Mines Shelf"
	recipe_key = "miners_shelves"
	crafting_level_requirement = 6
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 10, item = "ore_stone" },
		{ count = 5, item = "ore_copper" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "mineshaft_set", "bookshelf"]

[miners_flooring]
	description = "Dirt flooring for your home."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_mines_dirt_flooring"
	flooring = "mineshaft"
	name = "Mines Flooring"
	crafting_preview_sprite = "spr_ui_furniture_mines_flooring_preview"
	crafting_level_requirement = 1
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "sod" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "novelty_flooring"]

[miners_wallpaper]
	description = "Cave wall wallpaper for your home."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_mines_wallpaper"
	wallpaper = "mineshaft"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	name = "Mines Wall"
	crafting_preview_sprite = "spr_ui_furniture_mines_wall_preview"
	crafting_level_requirement = 1
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "sod" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "mineshaft_set", "wallpaper"]
