[mistria_wall_map_v1]
	icon_sprite = "spr_ui_item_decor_mistria_wall_map"
	name = "Mistria Wall Map"
	description = "A map that depicts Mistria. You can see your house from here!"
	object = "mistria_wall_map_v1"
	tags = ["furniture", "mistrian_history_set", "wall_hanging"]
	value = { bin = "self.recipe*1.1" }
	recipe_key = "mistria_wall_map"
	recipe = [
		{ count = 20, item = "paper" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 10


[mistria_history_book_v1]
	icon_sprite = "spr_ui_item_decor_mistria_history_book"
	name = "Mistria History Book"
	description = "A decorative book detailing several hundred years of Mistria's history."
	object = "mistria_history_book_v1"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	value = { bin = "self.recipe*1.1" }
	recipe_key = "mistria_history_book"
	recipe = [
		{ count = 20, item = "paper" },
		{ count = 5, item = "monster_powder" },
		{ hours = 1, minutes = 0 },
	]
	crafting_level_requirement = 12

[ornate_flagstone_v1]
	icon_sprite = "spr_ui_item_ornate_flagstone_v1"
	name = "Ornate Flagstone"
	description = "An ornate flagstone."
	object = "ornate_flagstone_v1"
	tags = ["furniture", "mistrian_history_set", "ground_decor"]
	recipe_key = "ornate_flagstone"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 1, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 12

[dragon_priestess_fountain_v1]
	icon_sprite = "spr_ui_item_dragon_priestess_fountain_v1"
	name = "Dragon Priestess Fountain"
	description = "A small fountain that features a Dragon Priestess."
	object = "dragon_priestess_fountain_v1"
	tags = ["furniture", "mistrian_history_set", "misc_outdoor_decor"]
	recipe_key = "dragon_priestess_fountain"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 4, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 14

[stone_dragon_figure_v1]
	icon_sprite = "spr_ui_item_decor_stone_dragon_figure_v1"
	name = "Stone Dragon Figure"
	description = "A small decorative stone dragon figure."
	object = "stone_dragon_figure_v1"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	recipe_key = "stone_dragon_figure"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 4, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 14

[ornate_flagstone_v2]
	icon_sprite = "spr_ui_item_ornate_flagstone_v2"
	name = "Ornate Flagstone"
	description = "An ornate flagstone."
	object = "ornate_flagstone_v2"
	tags = ["furniture", "mistrian_history_set", "ground_decor"]
	recipe_key = "ornate_flagstone"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 1, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 12

[dragon_priestess_fountain_v2]
	icon_sprite = "spr_ui_item_dragon_priestess_fountain_v2"
	name = "Dragon Priestess Fountain"
	description = "A small fountain that features a Dragon Priestess."
	object = "dragon_priestess_fountain_v2"
	tags = ["furniture", "mistrian_history_set", "misc_outdoor_decor"]
	recipe_key = "dragon_priestess_fountain"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 4, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 14

[stone_dragon_figure_v2]
	icon_sprite = "spr_ui_item_decor_stone_dragon_figure_v2"
	name = "Stone Dragon Figure"
	description = "A small decorative stone dragon figure."
	object = "stone_dragon_figure_v2"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	recipe_key = "stone_dragon_figure"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 4, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 14

[ornate_flagstone_v3]
	icon_sprite = "spr_ui_item_ornate_flagstone_v3"
	name = "Ornate Flagstone"
	description = "An ornate flagstone."
	object = "ornate_flagstone_v3"
	tags = ["furniture", "mistrian_history_set", "ground_decor"]
	recipe_key = "ornate_flagstone"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 1, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 12

[dragon_priestess_fountain_v3]
	icon_sprite = "spr_ui_item_dragon_priestess_fountain_v3"
	name = "Dragon Priestess Fountain"
	description = "A small fountain that features a Dragon Priestess."
	object = "dragon_priestess_fountain_v3"
	tags = ["furniture", "mistrian_history_set", "misc_outdoor_decor"]
	recipe_key = "dragon_priestess_fountain"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 4, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 14

[stone_dragon_figure_v3]
	icon_sprite = "spr_ui_item_decor_stone_dragon_figure_v3"
	name = "Stone Dragon Figure"
	description = "A small decorative stone dragon figure."
	object = "stone_dragon_figure_v3"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	recipe_key = "stone_dragon_figure"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 4, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 14

[dragon_statue_replica_v1]
	icon_sprite = "spr_ui_item_dragon_statue_replica_v1"
	name = "Dragon Statue"
	description = "A figure of a dragon, carved from warm-toned stone."
	object = "dragon_statue_replica_v1"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	recipe_key = "dragon_statue_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 100, item = "ore_stone" },
		{ count = 2, item = "monster_core" },
		{ count = 2, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 20

[dragon_statue_replica_v2]
	icon_sprite = "spr_ui_item_dragon_statue_replica_v2"
	name = "Dragon Statue"
	description = "A figure of a dragon, carved from cool-toned stone."
	object = "dragon_statue_replica_v2"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	recipe_key = "dragon_statue_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 100, item = "ore_stone" },
		{ count = 2, item = "monster_core" },
		{ count = 2, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 20

[mistria_history_scroll_v1]
	icon_sprite = "spr_ui_item_decor_mistria_history_scroll"
	name = "Caldosian Decorative Scroll"
	description = "A decorative Caldosian scroll."
	object = "mistria_history_scroll_v1"
	tags = ["furniture", "mistrian_history_set", "misc_decor"]
	value = { bin = "self.recipe*1.1" }
	recipe_key = "mistria_history_scroll"
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 2, item = "shard_mass" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 12

	#new items added from no set

	# <---------REPLICA ALDA POTS------------->

[alda_pot_replica_blue]
	icon_sprite = "spr_ui_item_alda_pot_replica_blue"
	name = "Large Alda Pot"
	description = "A blue colored replica of an Alda Pot artifact."
	object = "alda_pot_replica_blue"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	recipe_key = "alda_pot_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 12

[alda_pot_replica_green]
	icon_sprite = "spr_ui_item_alda_pot_replica_green"
	name = "Large Alda Pot"
	description = "A green colored replica of an Alda Pot artifact."
	object = "alda_pot_replica_green"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	recipe_key = "alda_pot_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 12

[alda_pot_replica_red]
	icon_sprite = "spr_ui_item_alda_pot_replica_red"
	name = "Large Alda Pot"
	description = "A red colored replica of an Alda Pot artifact."
	object = "alda_pot_replica_red"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	recipe_key = "alda_pot_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 12

[alda_pot_replica_purple]
	icon_sprite = "spr_ui_item_alda_pot_replica_purple"
	name = "Large Alda Pot"
	description = "A purple colored replica of an Alda Pot artifact."
	object = "alda_pot_replica_purple"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	recipe_key = "alda_pot_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 12

[alda_pot_replica_gold]
	icon_sprite = "spr_ui_item_alda_pot_replica_gold"
	name = "Large Alda Pot"
	description = "A gold colored replica of an Alda Pot artifact."
	object = "alda_pot_replica_gold"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	recipe_key = "alda_pot_replica"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 12

[gryphon_statue_replica_v1]
	icon_sprite = "spr_ui_item_decor_gryphon_statue_v1"
	name = "Gryphon Statue Replica"
	description = "A replica of an ancient stone gryphon."
	object = "gryphon_statue_replica_v1"
	tags = ["furniture", "misc_outdoor_decor", "mistrian_history_set"]
	recipe_key = "gryphon_statue_replica"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 3, item = "monster_shell" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]

[gryphon_statue_replica_v2]
	icon_sprite = "spr_ui_item_decor_gryphon_statue_v2"
	name = "Gryphon Statue Replica"
	description = "A replica of an ancient stone gryphon."
	object = "gryphon_statue_replica_v2"
	tags = ["furniture", "misc_outdoor_decor", "mistrian_history_set"]
	recipe_key = "gryphon_statue_replica"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 3, item = "monster_shell" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]

[gryphon_statue_replica_v3]
	icon_sprite = "spr_ui_item_decor_gryphon_statue_v3"
	name = "Gryphon Statue Replica"
	description = "A replica of an ancient stone gryphon."
	object = "gryphon_statue_replica_v3"
	tags = ["furniture", "misc_outdoor_decor", "mistrian_history_set"]
	recipe_key = "gryphon_statue_replica"
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 3, item = "monster_shell" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]

[broken_pillar_v1_white]
	name = "Broken Pillar"
	description = "A tall white broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v1_white"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v1_white"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v2_white]
	name = "Broken Pillar"
	description = "A short white broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v2_white"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v2_white"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v1_green]
	name = "Broken Pillar"
	description = "A tall green broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v1_green"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v1_green"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v2_green]
	name = "Broken Pillar"
	description = "A short green broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v2_green"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v2_green"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v1_tan]
	name = "Broken Pillar"
	description = "A tall tan broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v1_tan"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v1_tan"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v2_tan]
	name = "Broken Pillar"
	description = "A short tan broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v2_tan"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v2_tan"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v1_gray]
	name = "Broken Pillar"
	description = "A tall gray broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v1_gray"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v1_gray"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]

[broken_pillar_v2_gray]
	name = "Broken Pillar"
	description = "A short gray broken pillar."
	icon_sprite = "spr_ui_item_decor_broken_pillar_v2_gray"
	value = { bin = "self.recipe*1.1" }
	object = "broken_pillar_v2_gray"
	recipe_key = "broken_pillar"
	crafting_level_requirement = 46
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "crystal" },
		{ count = 5, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
