# --MIST SET--

[mist_bed_v1]
	icon_sprite = "spr_ui_item_furniture_mist_bed_v1"
	name = "Mist Bed"
	description = "A cloudlike bed with sparkly print sheets, perfect for daydreaming on."
	value = { bin = 400 }
	object = "mist_bed_v1"
	tags = ["furniture", "mist_set"]

[mist_bed_v2]
	icon_sprite = "spr_ui_item_furniture_mist_bed_v2"
	name = "Mist Bed"
	description = "A cloudlike bed with moon print sheets, perfect for daydreaming on."
	value = { bin = 400 }
	object = "mist_bed_v2"
	tags = ["furniture", "mist_set"]

[mist_bed_v3]
	icon_sprite = "spr_ui_item_furniture_mist_bed_v3"
	name = "Mist Bed"
	description = "A cloudlike bed with raindrop print sheets, perfect for daydreaming on."
	value = { bin = 400 }
	object = "mist_bed_v3"
	tags = ["furniture", "mist_set"]

[mist_bed_v4]
	icon_sprite = "spr_ui_item_furniture_mist_bed_v4"
	name = "Mist Bed"
	description = "A cloudlike bed with lightning print sheets, perfect for daydreaming on."
	value = { bin = 400 }
	object = "mist_bed_v4"
	tags = ["furniture", "mist_set"]

[mist_double_bed_v1]
	icon_sprite = "spr_ui_item_furniture_mist_double_bed_v1"
	name = "Mist Double Bed"
	description = "A cloudlike double bed with sparkly print sheets, perfect for daydreaming on."
	value = { bin = 600 }
	object = "mist_double_bed_v1"
	tags = ["furniture", "mist_set"]

[mist_double_bed_v2]
	icon_sprite = "spr_ui_item_furniture_mist_double_bed_v2"
	name = "Mist Double Bed"
	description = "A cloudlike double bed with moon print sheets, perfect for daydreaming on."
	value = { bin = 600 }
	object = "mist_double_bed_v2"
	tags = ["furniture", "mist_set"]

[mist_double_bed_v3]
	icon_sprite = "spr_ui_item_furniture_mist_double_bed_v3"
	name = "Mist Double Bed"
	description = "A cloudlike double bed with raindrop print sheets, perfect for daydreaming on."
	value = { bin = 600 }
	object = "mist_double_bed_v3"
	tags = ["furniture", "mist_set"]

[mist_double_bed_v4]
	icon_sprite = "spr_ui_item_furniture_mist_double_bed_v4"
	name = "Mist Double Bed"
	description = "A cloudlike double bed with lightning print sheets, perfect for daydreaming on."
	value = { bin = 600 }
	object = "mist_double_bed_v4"
	tags = ["furniture", "mist_set"]

[mist_pet_bed_v1]
	icon_sprite = "spr_ui_item_furniture_mist_pet_bed_v1"
	name = "Mist Pet Bed"
	description = "A cloudlike purple pet bed, perfect for your pet to daydream on."
	value = { bin = 300 }
	object = "mist_pet_bed_v1"
	tags = ["furniture", "mist_set"]

[mist_pet_bed_v2]
	icon_sprite = "spr_ui_item_furniture_mist_pet_bed_v2"
	name = "Mist Pet Bed"
	description = "A cloudlike blue and yellow pet bed, perfect for your pet to daydream on."
	value = { bin = 300 }
	object = "mist_pet_bed_v2"
	tags = ["furniture", "mist_set"]

[mist_pet_bed_v3]
	icon_sprite = "spr_ui_item_furniture_mist_pet_bed_v3"
	name = "Mist Pet Bed"
	description = "A cloudlike gray pet bed, perfect for your pet to daydream on."
	value = { bin = 300 }
	object = "mist_pet_bed_v3"
	tags = ["furniture", "mist_set"]

[mist_pet_bed_v4]
	icon_sprite = "spr_ui_item_furniture_mist_pet_bed_v4"
	name = "Mist Pet Bed"
	description = "A cloudlike purple-blue and yellow pet bed, perfect for your pet to daydream on."
	value = { bin = 300 }
	object = "mist_pet_bed_v4"
	tags = ["furniture", "mist_set"]

[mist_rug_v1]
	icon_sprite = "spr_ui_item_furniture_mist_rug_v1"
	name = "Mist Rug"
	description = "A comfy purple cloudlike rug."
	value = { bin = 300 }
	object = "mist_rug_v1"
	tags = ["furniture", "mist_set"]

[mist_rug_v2]
	icon_sprite = "spr_ui_item_furniture_mist_rug_v2"
	name = "Mist Rug"
	description = "A comfy white cloudlike rug."
	value = { bin = 300 }
	object = "mist_rug_v2"
	tags = ["furniture", "mist_set"]

[mist_rug_v3]
	icon_sprite = "spr_ui_item_furniture_mist_rug_v3"
	name = "Mist Rug"
	description = "A comfy gray cloudlike rug."
	value = { bin = 300 }
	object = "mist_rug_v3"
	tags = ["furniture", "mist_set"]

[mist_rug_v4]
	icon_sprite = "spr_ui_item_furniture_mist_rug_v4"
	name = "Mist Rug"
	description = "A comfy purple-blue cloudlike rug."
	value = { bin = 300 }
	object = "mist_rug_v4"
	tags = ["furniture", "mist_set"]

[mist_cushion_v1]
	icon_sprite = "spr_ui_item_furniture_mist_cushion_v1"
	name = "Mist Cushion"
	description = "A comfy purple cloudlike cushion."
	value = { bin = 200 }
	object = "mist_cushion_v1"
	tags = ["furniture", "mist_set"]

[mist_cushion_v2]
	icon_sprite = "spr_ui_item_furniture_mist_cushion_v2"
	name = "Mist Cushion"
	description = "A comfy blue cloudlike cushion."
	value = { bin = 200 }
	object = "mist_cushion_v2"
	tags = ["furniture", "mist_set"]

[mist_cushion_v3]
	icon_sprite = "spr_ui_item_furniture_mist_cushion_v3"
	name = "Mist Cushion"
	description = "A comfy gray cloudlike cushion."
	value = { bin = 200 }
	object = "mist_cushion_v3"
	tags = ["furniture", "mist_set"]

[mist_cushion_v4]
	icon_sprite = "spr_ui_item_furniture_mist_cushion_v4"
	name = "Mist Cushion"
	description = "A comfy purple-blue cloudlike cushion."
	value = { bin = 200 }
	object = "mist_cushion_v4"
	tags = ["furniture", "mist_set"]

[mist_lamp_v1]
	icon_sprite = "spr_ui_item_furniture_mist_lamp_v1"
	name = "Mist Lamp"
	description = "A floating purple cloud of mist that glows from within."
	value = { bin = 400 }
	object = "mist_lamp_v1"
	tags = ["furniture", "mist_set"]

[mist_lamp_v2]
	icon_sprite = "spr_ui_item_furniture_mist_lamp_v2"
	name = "Mist Lamp"
	description = "A floating blue cloud of mist that glows from within."
	value = { bin = 400 }
	object = "mist_lamp_v2"
	tags = ["furniture", "mist_set"]

[mist_lamp_v3]
	icon_sprite = "spr_ui_item_furniture_mist_lamp_v3"
	name = "Mist Lamp"
	description = "A floating gray cloud of mist that glows from within."
	value = { bin = 400 }
	object = "mist_lamp_v3"
	tags = ["furniture", "mist_set"]

[mist_lamp_v4]
	icon_sprite = "spr_ui_item_furniture_mist_lamp_v4"
	name = "Mist Lamp"
	description = "A floating purple-blue cloud of mist that glows from within."
	value = { bin = 400 }
	object = "mist_lamp_v4"
	tags = ["furniture", "mist_set"]

[mist_storage_chest_v1]
	icon_sprite = "spr_ui_item_furniture_mist_storage_chest_v1"
	name = "Mist Storage Chest"
	description = "An extra-large storage chest that looks just like a purple Mist Spot."
	value = { bin = 500 }
	object = "mist_storage_chest_v1"
	tags = ["furniture", "mist_set"]

[mist_storage_chest_v2]
	icon_sprite = "spr_ui_item_furniture_mist_storage_chest_v2"
	name = "Mist Storage Chest"
	description = "An extra-large storage chest that looks just like a white Mist Spot."
	value = { bin = 500 }
	object = "mist_storage_chest_v2"
	tags = ["furniture", "mist_set"]

[mist_storage_chest_v3]
	icon_sprite = "spr_ui_item_furniture_mist_storage_chest_v3"
	name = "Mist Storage Chest"
	description = "An extra-large storage storage chest that looks just like a gray Mist Spot."
	value = { bin = 500 }
	object = "mist_storage_chest_v3"
	tags = ["furniture", "mist_set"]

[mist_storage_chest_v4]
	icon_sprite = "spr_ui_item_furniture_mist_storage_chest_v4"
	name = "Mist Storage Chest"
	description = "An extra-large storage chest that looks just like a purple-blue Mist Spot."
	value = { bin = 500 }
	object = "mist_storage_chest_v4"
	tags = ["furniture", "mist_set"]
