# Monster Set Furniture - rewards from Stillwell

#sapling beanbag chairs

[sapling_beanbag_chair_green]
	name = "Sapling Beanbag Chair"
	recipe_key = "sapling_beanbag_chair"
	icon_sprite = "spr_ui_item_furniture_sapling_beanbag_chair_green"
	object = "sapling_beanbag_chair_green"
	description = "A green beanbag chair that looks like a Sapling monster."
	value = { bin = "self.recipe * 1.1" }
	recipe = [
		{ count = 20, item = "sap" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40
	tags = ["furniture", "monster_set", "accent_chair"]

[sapling_beanbag_chair_blue]
	name = "Sapling Beanbag Chair"
	recipe_key = "sapling_beanbag_chair"
	icon_sprite = "spr_ui_item_furniture_sapling_beanbag_chair_blue"
	object = "sapling_beanbag_chair_blue"
	description = "A blue beanbag chair that looks like a Sapling monster."
	value = { bin = "self.recipe * 1.1" }
	recipe = [
		{ count = 20, item = "sap" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40
	tags = ["furniture", "monster_set", "accent_chair"]

[sapling_beanbag_chair_purple]
	name = "Sapling Beanbag Chair"
	recipe_key = "sapling_beanbag_chair"
	icon_sprite = "spr_ui_item_furniture_sapling_beanbag_chair_purple"
	object = "sapling_beanbag_chair_purple"
	description = "A purple beanbag chair that looks like a Sapling monster."
	value = { bin = "self.recipe * 1.1" }
	recipe = [
		{ count = 20, item = "sap" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40
	tags = ["furniture", "monster_set", "accent_chair"]

[sapling_beanbag_chair_orange]
	name = "Sapling Beanbag Chair"
	recipe_key = "sapling_beanbag_chair"
	icon_sprite = "spr_ui_item_furniture_sapling_beanbag_chair_orange"
	object = "sapling_beanbag_chair_orange"
	description = "An orange beanbag chair that looks like a Sapling monster."
	value = { bin = "self.recipe * 1.1" }
	recipe = [
		{ count = 20, item = "sap" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40
	tags = ["furniture", "monster_set", "accent_chair"]

[sapling_beanbag_chair_pink]
	name = "Sapling Beanbag Chair"
	recipe_key = "sapling_beanbag_chair"
	icon_sprite = "spr_ui_item_furniture_sapling_beanbag_chair_pink"
	object = "sapling_beanbag_chair_pink"
	description = "A pink beanbag chair that looks like a Sapling monster."
	value = { bin = "self.recipe * 1.1" }
	recipe = [
		{ count = 20, item = "sap" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40
	tags = ["furniture", "monster_set", "accent_chair"]

	# rock clod gardens

[rock_clod_garden_brown]
	icon_sprite = "spr_ui_item_furniture_rockclod_garden_brown"
	name = "Rock Clod Garden"
	recipe_key = "rock_clod_garden"
	description = "A decorative rock garden, with miniature gray-brown Rock Clods."
	value = { bin = "self.recipe * 1.1" }
	object = "rock_clod_garden_brown"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "monster_set"]

[rock_clod_garden_navy]
	icon_sprite = "spr_ui_item_furniture_rockclod_garden_navy"
	name = "Rock Clod Garden"
	recipe_key = "rock_clod_garden"
	description = "A decorative rock garden, with miniature navy Rock Clods."
	value = { bin = "self.recipe * 1.1" }
	object = "rock_clod_garden_navy"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "monster_set"]

[rock_clod_garden_green]
	icon_sprite = "spr_ui_item_furniture_rockclod_garden_green"
	name = "Rock Clod Garden"
	recipe_key = "rock_clod_garden"
	description = "A decorative rock garden, with miniature green Rock Clods."
	value = { bin = "self.recipe * 1.1" }
	object = "rock_clod_garden_green"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "monster_set"]

[rock_clod_garden_red]
	icon_sprite = "spr_ui_item_furniture_rockclod_garden_red"
	name = "Rock Clod Garden"
	recipe_key = "rock_clod_garden"
	description = "A decorative rock garden, with miniature red Rock Clods."
	value = { bin = "self.recipe * 1.1" }
	object = "rock_clod_garden_red"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "monster_set"]

	# Mushroom Sofas

[mushroom_sofa_red]
	icon_sprite = "spr_ui_item_furniture_mushroom_sofa_red"
	name = "Mushroom Sofa"
	description = "A sofa with a red Mushroom monster inspired design."
	value = { bin = "self.recipe * 1.1" }
	object = "mushroom_sofa_red"
	tags = ["furniture", "sofa", "monster_set"]
	recipe_key = "mushroom_sofa"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "wild_mushroom" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]

[mushroom_sofa_green]
	icon_sprite = "spr_ui_item_furniture_mushroom_sofa_green"
	name = "Mushroom Sofa"
	description = "A sofa with a green Mushroom monster inspired design."
	value = { bin = "self.recipe * 1.1" }
	object = "mushroom_sofa_green"
	tags = ["furniture", "sofa", "monster_set"]
	recipe_key = "mushroom_sofa"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "wild_mushroom" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]

[mushroom_sofa_blue]
	icon_sprite = "spr_ui_item_furniture_mushroom_sofa_blue"
	name = "Mushroom Sofa"
	description = "A sofa with a blue Mushroom monster inspired design."
	value = { bin = "self.recipe * 1.1" }
	object = "mushroom_sofa_blue"
	tags = ["furniture", "sofa", "monster_set"]
	recipe_key = "mushroom_sofa"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "wild_mushroom" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]

[mushroom_sofa_purple]
	icon_sprite = "spr_ui_item_furniture_mushroom_sofa_purple"
	name = "Mushroom Sofa"
	description = "A sofa with a purple Mushroom monster inspired design."
	value = { bin = "self.recipe * 1.1" }
	object = "mushroom_sofa_purple"
	tags = ["furniture", "sofa", "monster_set"]
	recipe_key = "mushroom_sofa"
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "wild_mushroom" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 20 },
	]

	# Enchantern Lamps

[enchantern_lamp_yellow]
	icon_sprite = "spr_ui_item_furniture_enchantern_lamp_yellow"
	name = "Enchantern Lamp"
	description = "A lamp that looks like an Enchantern with a yellow glow."
	value = { bin = "self.recipe * 1.1" }
	object = "enchantern_lamp_yellow"
	crafting_preview_sprite = "spr_ui_furniture_enchantern_lamp_yellow_preview"
	recipe_key = "enchantern_lamp"
	tags = ["furniture", "floor_lighting", "monster_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 10, item = "glass" },
		{ count = 5, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]

[enchantern_lamp_blue]
	icon_sprite = "spr_ui_item_furniture_enchantern_lamp_blue"
	name = "Enchantern Lamp"
	description = "A lamp that looks like an Enchantern with a blue glow."
	value = { bin = "self.recipe * 1.1" }
	object = "enchantern_lamp_blue"
	crafting_preview_sprite = "spr_ui_furniture_enchantern_lamp_blue_preview"
	recipe_key = "enchantern_lamp"
	tags = ["furniture", "floor_lighting", "monster_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 10, item = "glass" },
		{ count = 5, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]

	# Stalagmite spike tiles

[stalagmite_tile_blue]
	icon_sprite = "spr_ui_item_furniture_stalagmite_spike_tile_blue"
	name = "Stalagmite Spike Tile"
	description = "A spikey blue Stalagmite floor tile."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 1, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	recipe_key = "stalagmite_spike_tile"
	object = "stalagmite_tile_blue"
	tags = ["furniture", "monster_set", "ground_decor"]

[stalagmite_tile_green]
	icon_sprite = "spr_ui_item_furniture_stalagmite_spike_tile_green"
	name = "Stalagmite Spike Tile"
	description = "A spikey green Stalagmite floor tile."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 1, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	recipe_key = "stalagmite_spike_tile"
	object = "stalagmite_tile_green"
	tags = ["furniture", "monster_set", "ground_decor"]

[stalagmite_tile_purple]
	icon_sprite = "spr_ui_item_furniture_stalagmite_spike_tile_purple"
	name = "Stalagmite Spike Tile"
	description = "A spikey purple Stalagmite floor tile."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 1, item = "monster_horn" },
		{ hours = 0, minutes = 20 },
	]
	recipe_key = "stalagmite_spike_tile"
	object = "stalagmite_tile_purple"
	tags = ["furniture", "monster_set", "ground_decor"]

	# Essence Bat garlands

[essence_bat_garland_purple]
	icon_sprite = "spr_ui_item_furniture_essence_bat_garland_purple"
	name = "Essence Bat Garland"
	description = "A paper cut-out garland inspired by purple Essence Bats."
	object = "essence_bat_garland_purple"

	tags = ["furniture", "monster_set", "wall_hanging"]
	value = { bin = "self.recipe*1.1" }
	recipe_key = "essence_bat_garland"
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 5, item = "monster_wing" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40

[essence_bat_garland_blue]
	icon_sprite = "spr_ui_item_furniture_essence_bat_garland_blue"
	name = "Essence Bat Garland"
	description = "A paper cut-out garland inspired by blue Essence Bats."
	object = "essence_bat_garland_blue"
	tags = ["furniture", "monster_set", "wall_hanging"]
	value = { bin = "self.recipe*1.1" }
	recipe_key = "essence_bat_garland"
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 5, item = "monster_wing" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40

	# 	# Mimic Chest

[mimic_storage_chest]
	icon_sprite = "spr_ui_item_furniture_mimic_storage_chest"
	name = "Mimic Storage Chest"
	description = "A storage chest that looks like a Mimic monster. Has an extra-large storage capacity."
	object = "mimic_storage_chest"
	value = { bin = "self.recipe*1.1" }
	tags = ["furniture", "monster_set"]
	recipe_key = "mimic_storage_chest"
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "dragon_forged_powder" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 40

	# Flame Spirit lamps

[flame_spirit_lamp_orange]
	icon_sprite = "spr_ui_item_furniture_flame_spirit_lamp_orange"
	name = "Flame Spirit Lamp"
	description = "A lamp that looks like an orange Flame Spirit."
	value = { bin = "self.recipe * 1.1" }
	object = "flame_spirit_lamp_orange"
	crafting_preview_sprite = "spr_ui_furniture_flame_spirit_lamp_orange_preview"
	recipe_key = "flame_spirit_lamp"
	tags = ["furniture", "table_lighting", "monster_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 5, item = "peat" },
		{ count = 5, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]

[flame_spirit_lamp_purple]
	icon_sprite = "spr_ui_item_furniture_flame_spirit_lamp_purple"
	name = "Flame Spirit Lamp"
	description = "A lamp that looks like a purple Flame Spirit."
	value = { bin = "self.recipe * 1.1" }
	object = "flame_spirit_lamp_purple"
	crafting_preview_sprite = "spr_ui_furniture_flame_spirit_lamp_purple_preview"
	recipe_key = "flame_spirit_lamp"
	tags = ["furniture", "table_lighting", "monster_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 5, item = "peat" },
		{ count = 5, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]

	# Lava Cat beds

[lava_cat_bed_orange]
	icon_sprite = "spr_ui_item_furniture_lava_cat_double_bed_orange"
	name = "Lava Cat Double Bed"
	description = "A double bed with a Lava Cat inspired design."
	object = "lava_cat_bed_orange"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "monster_set"]
	recipe_key = "lava_cat_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "peat" },
		{ count = 10, item = "obsidian" },
		{ count = 5, item = "monster_whisker" },
		{ hours = 0, minutes = 30 },
	]

[lava_cat_bed_void]
	icon_sprite = "spr_ui_item_furniture_lava_cat_double_bed_void"
	name = "Lava Cat Double Bed"
	description = "A double bed with a Void Cat inspired design."
	object = "lava_cat_bed_void"
	value = { bin = "self.recipe * 1.1" }
	tags = ["furniture", "double_bed", "monster_set"]
	recipe_key = "lava_cat_bed"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "peat" },
		{ count = 10, item = "obsidian" },
		{ count = 5, item = "monster_whisker" },
		{ hours = 0, minutes = 30 },
	]

	# Floating Tome lamp

[floating_tome_lamp]
	icon_sprite = "spr_ui_item_furniture_floating_tome_lamp"
	name = "Floating Tome Lamp"
	description = "A floating lamp that looks like a Flying Tome monster."
	value = { bin = "self.recipe * 1.1" }
	object = "floating_tome_lamp"
	crafting_preview_sprite = "spr_ui_furniture_floating_tome_lamp_preview"
	tags = ["furniture", "floor_lighting", "monster_set"]
	recipe_key = "floating_tome_lamp"
	crafting_level_requirement = 40
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 5, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]

	# Rock Stack shelf

[rock_stack_shelf]
	icon_sprite = "spr_ui_item_furniture_rock_stack_shelf"
	name = "Rock Stack Shelf"
	description = "A bookshelf held together with miniature Rock Stacks."
	value = { bin = "self.recipe*1.1" }
	object = "rock_stack_shelf"
	recipe_key = "rock_stack_shelf"
	crafting_level_requirement = 40
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "monster_block" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "bookshelf", "monster_set"]

	# void gryphon statues

[void_gryphon_statue_purple]
	icon_sprite = "spr_ui_item_furniture_void_gryphon_statue_purple"
	name = "Void Gryphon Statue"
	description = "A purple void Gryphon Statue."
	value = { bin = "self.recipe*1.1" }
	object = "void_gryphon_statue_purple"
	recipe_key = "void_gryphon_statue"
	crafting_level_requirement = 40
	recipe = [
		{ count = 40, item = "voidite" },
		{ count = 2, item = "void_herb" },
		{ count = 2, item = "void_pearl" },
		{ count = 2, item = "void_powder" },
		{ count = 2, item = "void_stone" },
		{ hours = 0, minutes = 50 },
	]
	tags = ["furniture", "misc_decor", "monster_set"]

[void_gryphon_statue_blue]
	icon_sprite = "spr_ui_item_furniture_void_gryphon_statue_blue"
	name = "Void Gryphon Statue"
	description = "A blue void Gryphon Statue."
	value = { bin = "self.recipe*1.1" }
	object = "void_gryphon_statue_blue"
	recipe_key = "void_gryphon_statue"
	crafting_level_requirement = 40
	recipe = [
		{ count = 40, item = "voidite" },
		{ count = 2, item = "void_herb" },
		{ count = 2, item = "void_pearl" },
		{ count = 2, item = "void_powder" },
		{ count = 2, item = "void_stone" },
		{ hours = 0, minutes = 50 },
	]
	tags = ["furniture", "misc_decor", "monster_set"]
