#Museum Rewards

[obelisk_beige]
	description = "A large beige obelisk."
	icon_sprite = "spr_ui_item_decor_obelisk_beige"
	name = "Obelisk"
	object = "obelisk_beige"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "obelisk"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	crafting_level_requirement = 52
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "crystal" },
		{ count = 10, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]

[obelisk_black]
	description = "A large black obelisk."
	icon_sprite = "spr_ui_item_decor_obelisk_black"
	name = "Obelisk"
	object = "obelisk_black"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "obelisk"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	crafting_level_requirement = 52
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "crystal" },
		{ count = 10, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]

[obelisk_pink]
	description = "A large pink obelisk."
	icon_sprite = "spr_ui_item_decor_obelisk_pink"
	name = "Obelisk"
	object = "obelisk_pink"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "obelisk"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	crafting_level_requirement = 52
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "crystal" },
		{ count = 10, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]

[obelisk_white]
	description = "A large white obelisk."
	icon_sprite = "spr_ui_item_decor_obelisk_white"
	name = "Obelisk"
	object = "obelisk_white"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "obelisk"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	crafting_level_requirement = 52
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "crystal" },
		{ count = 10, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]

[obelisk_teal]
	description = "A large teal obelisk."
	icon_sprite = "spr_ui_item_decor_obelisk_teal"
	name = "Obelisk"
	object = "obelisk_teal"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "obelisk"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	crafting_level_requirement = 52
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "crystal" },
		{ count = 10, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]

[obelisk_plum]
	description = "A large plum obelisk."
	icon_sprite = "spr_ui_item_decor_obelisk_plum"
	name = "Obelisk"
	object = "obelisk_plum"
	value = { bin = "self.recipe * 1.1" }
	recipe_key = "obelisk"
	tags = ["furniture", "misc_decor", "mistrian_history_set"]
	crafting_level_requirement = 52
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "crystal" },
		{ count = 10, item = "obsidian" },
		{ hours = 0, minutes = 30 },
	]
