[pink_pet_bed]
	name = "Pink Pet Bed"
	description = "A decorative pink pet bed. It's very cute!"
	icon_sprite = "spr_ui_item_decor_pink_pet_bed"
	object = "pink_pet_bed"
	value = { bin = 250, store = 500 }

[blue_pet_bed]
	name = "Blue Pet Bed"
	description = "A decorative blue pet bed. It's very cute!"
	icon_sprite = "spr_ui_item_decor_blue_pet_bed"
	object = "blue_pet_bed"
	value = { bin = 250, store = 500 }

[cream_pet_bed]
	name = "Cream Pet Bed"
	description = "A decorative cream pet bed. It's very cute!"
	icon_sprite = "spr_ui_item_decor_cream_pet_bed"
	object = "cream_pet_bed"
	value = { bin = 250, store = 500 }

[cream_pet_dish]
	name = "Cream Pet Dish"
	description = "A decorative cream pet dish. It's very cute!"
	icon_sprite = "spr_ui_item_decor_cream_pet_dish"
	object = "cream_pet_dish"
	value = { bin = 250, store = 500 }

[pink_pet_dish]
	name = "Pink Pet Dish"
	description = "A decorative pink pet dish. It's very cute!"
	icon_sprite = "spr_ui_item_decor_pink_pet_dish"
	object = "pink_pet_dish"
	value = { bin = 250, store = 500 }

[blue_pet_dish]
	name = "Blue Pet Dish"
	description = "A decorative blue pet dish. It's very cute!"
	icon_sprite = "spr_ui_item_decor_blue_pet_dish"
	object = "blue_pet_dish"
	value = { bin = 250, store = 500 }