[pirate_wall_flag_v1]
	icon_sprite = "spr_ui_item_furniture_pirate_wall_flag_v1"
	name = "Pirate Flag"
	description = "A worn black pirate flag."
	object = "pirate_wall_flag_v1"
	tags = ["furniture", "wall_hanging", "pirate_set"]
	value = { bin = 120 }

[pirate_wall_flag_v2]
	icon_sprite = "spr_ui_item_furniture_pirate_wall_flag_v2"
	name = "Pirate Flag"
	description = "A worn brown pirate flag."
	object = "pirate_wall_flag_v2"
	tags = ["furniture", "wall_hanging", "pirate_set"]
	value = { bin = 120 }

[pirate_ship_in_a_bottle_v1]
	icon_sprite = "spr_ui_item_furniture_pirate_ship_in_a_bottle_v1"
	name = "Ship in a Bottle"
	description = "A tiny brown pirate ship in a bottle."
	object = "pirate_ship_in_a_bottle_v1"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 150 }


[pirate_ship_in_a_bottle_v2]
	icon_sprite = "spr_ui_item_furniture_pirate_ship_in_a_bottle_v2"
	name = "Ship in a Bottle"
	description = "A tiny yellow pirate ship in a bottle."
	object = "pirate_ship_in_a_bottle_v2"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 150 }

[pirate_counterfeit_gold_pile_v1]
	icon_sprite = "spr_ui_item_furniture_pirate_counterfeit_gold_pile_v1"
	name = "Counterfeit Gold Pile"
	description = "These gold colored coins are clearly fake, but still shine alluringly."
	object = "pirate_counterfeit_gold_pile_v1"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 10 }

[pirate_counterfeit_gold_pile_v2]
	icon_sprite = "spr_ui_item_furniture_pirate_counterfeit_gold_pile_v2"
	name = "Counterfeit Gold Pile"
	description = "These pink-tinged coins are clearly fake, but still shine alluringly."
	object = "pirate_counterfeit_gold_pile_v2"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 10 }

[pirate_anchor_v1]
	icon_sprite = "spr_ui_item_furniture_pirate_anchor_v1"
	name = "Anchor"
	description = "An cool-toned old anchor."
	object = "pirate_anchor_v1"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 150 }

[pirate_anchor_v2]
	icon_sprite = "spr_ui_item_furniture_pirate_anchor_v2"
	name = "Anchor"
	description = "An warm-toned old anchor."
	object = "pirate_anchor_v2"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 150 }

[pirate_nautical_compass_v1]
	icon_sprite = "spr_ui_item_furniture_pirate_nautical_compass_v1"
	name = "Nautical Compass"
	description = "A green nautical compass."
	object = "pirate_nautical_compass_v1"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 125 }

[pirate_nautical_compass_v2]
	icon_sprite = "spr_ui_item_furniture_pirate_nautical_compass_v2"
	name = "Nautical Compass"
	description = "A yellow nautical compass."
	object = "pirate_nautical_compass_v2"
	tags = ["furniture", "misc_decor", "pirate_set"]
	value = { bin = 125 }
