# --RUINS FURNITURE--

[ruins_pink_diamond_rock]
	icon_sprite = "spr_ui_item_furniture_pink_diamond_rock"
	name = "Ornamental Pink Diamond Rock"
	description = "A decorative pink diamond rock."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pink_diamond_rock"
	crafting_level_requirement = 28
	recipe = [
		{ count = 3, item = "ore_pink_diamond" },
		{ count = 3, item = "refined_stone" },
		{ count = 2, item = "void_stone" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "misc_furniture"]

[ruins_mistril_node]
	icon_sprite = "spr_ui_item_furniture_mistril_node"
	name = "Ornamental Mistril Node"
	description = "A decorative mistril node."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_mistril_node"
	crafting_level_requirement = 28
	recipe = [
		{ count = 10, item = "ore_mistril" },
		{ count = 5, item = "refined_stone" },
		{ count = 2, item = "void_stone" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "misc_furniture"]

[ruins_wallpaper]
	icon_sprite = "spr_ui_item_furniture_ruins_wallpaper"
	name = "Ruins Wall"
	description = "A wallpaper that mimics the look of the Ruins."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "ruins"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_wallpaper_ruins_preview"
	crafting_level_requirement = 30
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 2, item = "void_powder" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "wallpaper"]

[ruins_flooring]
	icon_sprite = "spr_ui_item_furniture_ruins_flooring"
	name = "Ruins Floor"
	description = "A stone floor that mimics the look of the Ruins."
	value = { bin = "self.recipe * 1.1" }
	flooring = "ruins"
	crafting_preview_sprite = "spr_ui_furniture_flooring_ruins_preview"
	crafting_level_requirement = 30
	recipe = [
		{ count = 10, item = "void_pearl" },
		{ count = 2, item = "refined_stone" },
		{ count = 2, item = "ore_mistril" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "novelty_flooring"]

[ruins_stone_arch]
	icon_sprite = "spr_ui_item_furniture_ruins_stone_arch"
	name = "Ruins Stone Arch"
	description = "A stone arch from the Ruins."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_stone_arch"
	crafting_level_requirement = 42
	recipe = [
		{ count = 20, item = "refined_stone" },
		{ count = 10, item = "voidite" },
		{ count = 3, item = "monster_block" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "misc_outdoor_decor"]

[ruins_pot1]
	icon_sprite = "spr_ui_item_furniture_ruins_pot1"
	name = "Ruins Pot"
	description = "A white goblet-shaped clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot1"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_white"

[ruins_pot2]
	icon_sprite = "spr_ui_item_furniture_ruins_pot2"
	name = "Ruins Pot"
	description = "An orange gourd-shaped clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot2"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_orange"

[ruins_pot3]
	icon_sprite = "spr_ui_item_furniture_ruins_pot3"
	name = "Ruins Pot"
	description = "A simple orange clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot3"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_orange"

[ruins_pot4]
	icon_sprite = "spr_ui_item_furniture_ruins_pot4"
	name = "Ruins Pot"
	description = "A white gourd-shaped clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot4"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_white"

[ruins_pot5]
	icon_sprite = "spr_ui_item_furniture_ruins_pot5"
	name = "Ruins Pot"
	description = "A small cracked purple clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot5"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_blue"

[ruins_pot6]
	icon_sprite = "spr_ui_item_furniture_ruins_pot6"
	name = "Ruins Pot"
	description = "A small cracked blue clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot6"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_blue"

[ruins_pot7]
	icon_sprite = "spr_ui_item_furniture_ruins_pot7"
	name = "Ruins Pot"
	description = "A small purple clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot7"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_blue"

[ruins_pot8]
	icon_sprite = "spr_ui_item_furniture_ruins_pot8"
	name = "Ruins Pot"
	description = "A simple gray clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot8"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_white"

[ruins_pot9]
	icon_sprite = "spr_ui_item_furniture_ruins_pot9"
	name = "Ruins Pot"
	description = "A large orange clay pot."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_pot9"
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "clay" },
		{ count = 5, item = "shards" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "ruins_set", "misc_decor"]
	recipe_key = "ruins_pot_orange"

[ruins_crystal_light]
	icon_sprite = "spr_ui_item_furniture_ruins_crystal_light"
	name = "Ruins Crystal Light"
	description = "A crystal light that glows pink when lit."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_crystal_light"
	crafting_preview_sprite = "spr_ui_furniture_ruins_crystal_light_preview"
	crafting_level_requirement = 42
	recipe = [
		{ count = 8, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 5, item = "crystal" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "floor_lighting"]

[ruins_wall_crystal_light]
	icon_sprite = "spr_ui_item_furniture_ruins_wall_crystal_light"
	name = "Ruins Crystal Wall Light"
	description = "A crystal wall light that glows pink when lit."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_wall_crystal_light"
	crafting_preview_sprite = "spr_ui_furniture_ruins_wall_crystal_light_preview"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 3, item = "crystal" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "wall_lighting"]

[ruins_floor_brazier_purple]
	icon_sprite = "spr_ui_item_furniture_ruins_floor_brazier_v1"
	name = "Ruins Floor Brazier"
	description = "A floor brazier filled with purple flames."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_floor_brazier_purple"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 4, item = "peat" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "floor_lighting"]

[ruins_floor_brazier_orange]
	icon_sprite = "spr_ui_item_furniture_ruins_floor_brazier_v2"
	name = "Ruins Floor Brazier"
	description = "A floor brazier filled with orange flames."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_floor_brazier_orange"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 4, item = "peat" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "floor_lighting"]

[ruins_floor_brazier_blue]
	icon_sprite = "spr_ui_item_furniture_ruins_floor_brazier_v3"
	name = "Ruins Floor Brazier"
	description = "A floor brazier filled with blue flames."
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_floor_brazier_blue"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 4, item = "peat" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "floor_lighting"]

[ruins_window_v1]
	icon_sprite = "spr_ui_item_furniture_ruins_window_v1"
	name = "Ruins Window"
	description = "A stone-framed window to the void. Interact when placed to toggle its animation!"
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_window_v1"
	crafting_preview_sprite = "spr_ui_furniture_ruins_window_v1_preview"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 15, item = "voidite" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "window"]

[ruins_window_v2]
	icon_sprite = "spr_ui_item_furniture_ruins_window_v2"
	name = "Ruins Window"
	description = "A purple-framed window to the void. Interact when placed to toggle its animation!"
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_window_v2"
	crafting_preview_sprite = "spr_ui_furniture_ruins_window_v2_preview"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 15, item = "voidite" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "window"]

[ruins_window_v3]
	icon_sprite = "spr_ui_item_furniture_ruins_window_v3"
	name = "Ruins Window"
	description = "A wood-framed window to the void. Interact when placed to toggle its animation!"
	value = { bin = "self.recipe * 1.1" }
	object = "ruins_window_v3"
	crafting_preview_sprite = "spr_ui_furniture_ruins_window_v3_preview"
	crafting_level_requirement = 42
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 15, item = "voidite" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "ruins_set", "window"]
