# STAR FESTIVAL FURNITURE

[star_lantern_yellow]
	name = "Star Lantern"
	description = "A Shooting Star Festival lantern with a yellow star detail."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 1, item = "silver_ingot" },
		{ count = 1, item = "monster_core" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	object = "star_lantern_yellow"
	recipe_key = "star_lantern"
	icon_sprite = "spr_ui_item_decor_star_lantern_yellow"
	tags = ['furniture', 'star_festival_set', "floor_lighting"]

[star_lantern_white]
	name = "Star Lantern"
	description = "A Shooting Star Festival lantern with a white star detail."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 1, item = "silver_ingot" },
		{ count = 1, item = "monster_core" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	object = "star_lantern_white"
	recipe_key = "star_lantern"
	icon_sprite = "spr_ui_item_decor_star_lantern_white"
	tags = ['furniture', 'star_festival_set', "floor_lighting"]

[star_lantern_pink]
	name = "Star Lantern"
	description = "A Shooting Star Festival lantern with a pink star detail."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 1, item = "silver_ingot" },
		{ count = 1, item = "monster_core" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	object = "star_lantern_pink"
	recipe_key = "star_lantern"
	icon_sprite = "spr_ui_item_decor_star_lantern_pink"
	tags = ['furniture', 'star_festival_set', "floor_lighting"]

[star_lantern_purple]
	name = "Star Lantern"
	description = "A Shooting Star Festival lantern with a purple star detail."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 1, item = "silver_ingot" },
		{ count = 1, item = "monster_core" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	object = "star_lantern_purple"
	recipe_key = "star_lantern"
	icon_sprite = "spr_ui_item_decor_star_lantern_purple"
	tags = ['furniture', 'star_festival_set', "floor_lighting"]

[star_lantern_blue]
	name = "Star Lantern"
	description = "A Shooting Star Festival lantern with a blue star detail."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 1, item = "silver_ingot" },
		{ count = 1, item = "monster_core" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 30 },
	]
	object = "star_lantern_blue"
	recipe_key = "star_lantern"
	icon_sprite = "spr_ui_item_decor_star_lantern_blue"
	tags = ['furniture', 'star_festival_set', "floor_lighting"]


[star_viewing_blanket_yellow]
	name = "Star Viewing Blanket"
	description = "A Shooting Star Festival blanket in yellow."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_viewing_blanket_yellow"
	recipe_key = "star_viewing_blanket"
	icon_sprite = "spr_ui_item_decor_star_viewing_blanket_yellow"
	tags = ['furniture', 'star_festival_set', 'medium_rug']

[star_viewing_blanket_pink]
	name = "Star Viewing Blanket"
	description = "A Shooting Star Festival blanket in pink."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_viewing_blanket_pink"
	recipe_key = "star_viewing_blanket"
	icon_sprite = "spr_ui_item_decor_star_viewing_blanket_pink"
	tags = ['furniture', 'star_festival_set', 'medium_rug']

[star_viewing_blanket_purple]
	name = "Star Viewing Blanket"
	description = "A Shooting Star Festival blanket in purple."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_viewing_blanket_purple"
	recipe_key = "star_viewing_blanket"
	icon_sprite = "spr_ui_item_decor_star_viewing_blanket_purple"
	tags = ['furniture', 'star_festival_set', 'medium_rug']

[star_viewing_blanket_blue]
	name = "Star Viewing Blanket"
	description = "A Shooting Star Festival blanket in blue."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "sheep_wool" },
		{ count = 1, item = "essence_drop" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_viewing_blanket_blue"
	recipe_key = "star_viewing_blanket"
	icon_sprite = "spr_ui_item_decor_star_viewing_blanket_blue"
	tags = ['furniture', 'star_festival_set', 'medium_rug']


[star_cushion_yellow]
	name = "Star Cushion"
	description = "A Shooting Star Festival cushion in yellow."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_cushion_yellow"
	recipe_key = "star_cushion"
	icon_sprite = "spr_ui_item_decor_star_cushion_yellow"
	tags = ['furniture', 'star_festival_set', 'misc_seating']

[star_cushion_white]
	name = "Star Cushion"
	description = "A Shooting Star Festival cushion in white."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_cushion_white"
	recipe_key = "star_cushion"
	icon_sprite = "spr_ui_item_decor_star_cushion_white"
	tags = ['furniture', 'star_festival_set', 'misc_seating']

[star_cushion_pink]
	name = "Star Cushion"
	description = "A Shooting Star Festival cushion in pink."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_cushion_pink"
	recipe_key = "star_cushion"
	icon_sprite = "spr_ui_item_decor_star_cushion_pink"
	tags = ['furniture', 'star_festival_set', 'misc_seating']

[star_cushion_purple]
	name = "Star Cushion"
	description = "A Shooting Star Festival cushion in purple."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_cushion_purple"
	recipe_key = "star_cushion"
	icon_sprite = "spr_ui_item_decor_star_cushion_purple"
	tags = ['furniture', 'star_festival_set', 'misc_seating']

[star_cushion_light_blue]
	name = "Star Cushion"
	description = "A Shooting Star Festival cushion in light blue."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_cushion_light_blue"
	recipe_key = "star_cushion"
	icon_sprite = "spr_ui_item_decor_star_cushion_light_blue"
	tags = ['furniture', 'star_festival_set', 'misc_seating']

[star_cushion_blue]
	name = "Star Cushion"
	description = "A Shooting Star Festival cushion in blue."
	value = { bin = "self.recipe*1.1" }
	crafting_level_requirement = 15
	recipe = [
		{ count = 2, item = "rabbit_wool" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]
	object = "star_cushion_blue"
	recipe_key = "star_cushion"
	icon_sprite = "spr_ui_item_decor_star_cushion_blue"
	tags = ['furniture', 'star_festival_set', 'misc_seating']
