
# ADELINE SPOUSE FURNITURE

[adeline_desk]
	name = "Adeline's Desk"
	description = "Adeline's desk. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_adeline_desk"
	object = "adeline_desk"
	soulbind = "forever"
	tags = ["adeline_furniture"]

[adeline_chair]
	name = "Adeline's Comfy Chair"
	description = "Adeline's comfy chair. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_adeline_chair"
	object = "adeline_chair"
	soulbind = "forever"
	tags = ["adeline_furniture"]

[adeline_hobby_table]
	name = "Adeline's Hobby Table"
	description = "Adeline's hobby table. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_adeline_hobby_table"
	object = "adeline_hobby_table"
	soulbind = "forever"
	tags = ["adeline_furniture"]

	# BALOR SPOUSE FURNITURE

[balor_desk]
	name = "Balor's Desk"
	description = "Balor's desk. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_balor_desk"
	object = "balor_desk"
	soulbind = "forever"
	tags = ["balor_furniture"]

[balor_chair]
	name = "Balor's Comfy Chair"
	description = "Balor's comfy chair. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_balor_chair"
	object = "balor_chair"
	soulbind = "forever"
	tags = ["balor_furniture"]

[balor_gem_station]
	name = "Balor's Gem Station"
	description = "Balor's gem station. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_balor_gem_station"
	object = "balor_gem_station"
	soulbind = "forever"
	tags = ["balor_furniture"]

	# CALDARUS SPOUSE FURNITURE

[caldarus_desk]
	name = "Caldarus' Desk"
	description = "Caldarus' desk. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_caldarus_desk"
	object = "caldarus_desk"
	soulbind = "forever"
	tags = ["caldarus_furniture"]

[caldarus_chair]
	name = "Caldarus' Comfy Chair"
	description = "Caldarus' comfy chair. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_caldarus_chair"
	object = "caldarus_chair"
	soulbind = "forever"
	tags = ["caldarus_furniture"]

[caldarus_music_station]
	name = "Caldarus' Music Station"
	description = "Caldarus' music station. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_caldarus_music_station"
	object = "caldarus_music_station"
	soulbind = "forever"
	tags = ["caldarus_furniture"]

	# CELINE SPOUSE FURNITURE

[celine_desk]
	name = "Celine's Desk"
	description = "Celine's desk. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_celine_desk"
	object = "celine_desk"
	soulbind = "forever"
	tags = ["celine_furniture"]

[celine_chair]
	name = "Celine's Comfy Chair"
	description = "Celine's comfy chair. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_celine_chair"
	object = "celine_chair"
	soulbind = "forever"
	tags = ["celine_furniture"]

[celine_garden_shelf]
	name = "Celine's Garden Shelf"
	description = "Celine's garden shelf. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_celine_garden_shelves"
	object = "celine_garden_shelf"
	soulbind = "forever"
	tags = ["celine_furniture"]

	# EILAND SPOUSE FURNITURE

[eiland_desk]
	name = "Eiland's Desk"
	description = "Eiland's desk. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_eiland_desk"
	object = "eiland_desk"
	soulbind = "forever"
	tags = ["eiland_furniture"]

[eiland_chair]
	name = "Eiland's Comfy Chair"
	description = "Eiland's comfy chair. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_eiland_bench"
	object = "eiland_chair"
	soulbind = "forever"
	tags = ["eiland_furniture"]

[eiland_artifact_shelf]
	name = "Eiland's Artifact Shelf"
	description = "Eiland's artifact shelf. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_eiland_artifact_shelf"
	object = "eiland_artifact_shelf"
	soulbind = "forever"
	tags = ["eiland_furniture"]

	# HAYDEN SPOUSE FURNITURE

[hayden_desk]
	name = "Hayden's Desk"
	description = "Hayden's desk. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_hayden_desk"
	object = "hayden_desk"
	soulbind = "forever"
	tags = ["hayden_furniture"]

[hayden_chair]
	name = "Hayden's Comfy Chair"
	description = "Hayden's comfy chair. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_hayden_chair"
	object = "hayden_chair"
	soulbind = "forever"
	tags = ["hayden_furniture"]

[hayden_indoor_garden]
	name = "Hayden's Indoor Garden"
	description = "Hayden's indoor garden. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_hayden_crop_station"
	object = "hayden_indoor_garden"
	soulbind = "forever"
	tags = ["hayden_furniture"]

	# JUNIPER SPOUSE FURNITURE

[juniper_desk]
	name = "Juniper's Desk"
	description = "Juniper's desk. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_juniper_desk"
	object = "juniper_desk"
	soulbind = "forever"
	tags = ["juniper_furniture"]

[juniper_chair]
	name = "Juniper's Comfy Chair"
	description = "Juniper's comfy chair. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_juniper_chair"
	object = "juniper_chair"
	soulbind = "forever"
	tags = ["juniper_furniture"]

[juniper_cauldron]
	name = "Juniper's Cauldron"
	description = "Juniper's cauldron. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_juniper_cauldron"
	object = "juniper_cauldron"
	soulbind = "forever"
	tags = ["juniper_furniture"]

[dozy_pet_bed]
	name = "Dozy's Dog Bed"
	description = "Dozy's dog bed. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_dozy_pet_bed"
	object = "dozy_pet_bed"
	soulbind = "forever"
	tags = ["dozy_furniture"]


	# MARCH SPOUSE FURNITURE

[march_desk]
	name = "March's Desk"
	description = "March's desk. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_march_desk"
	object = "march_desk"
	soulbind = "forever"
	tags = ["march_furniture"]

[march_chair]
	name = "March's Comfy Chair"
	description = "March's comfy chair. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_march_chair"
	object = "march_chair"
	soulbind = "forever"
	tags = ["march_furniture"]

[march_forge]
	name = "March's Forge"
	description = "March's forge. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_march_forge"
	object = "march_forge"
	soulbind = "forever"
	tags = ["march_furniture"]

	# REINA SPOUSE FURNITURE

[reina_desk]
	name = "Reina's Desk"
	description = "Reina's desk. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_reina_desk"
	object = "reina_desk"
	soulbind = "forever"
	tags = ["reina_furniture"]

[reina_chair]
	name = "Reina's Comfy Chair"
	description = "Reina's comfy chair. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_reina_chair"
	object = "reina_chair"
	soulbind = "forever"
	tags = ["reina_furniture"]

[reina_test_kitchen]
	name = "Reina's Test Kitchen"
	description = "Reina's test kitchen. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_reina_kitchen"
	object = "reina_test_kitchen"
	soulbind = "forever"
	tags = ["reina_furniture"]

	# RYIS SPOUSE FURNITURE

[ryis_desk]
	name = "Ryis' Desk"
	description = "Ryis' desk. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_ryis_desk"
	object = "ryis_desk"
	soulbind = "forever"
	tags = ["ryis_furniture"]

[ryis_chair]
	name = "Ryis' Comfy Chair"
	description = "Ryis' comfy chair. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_ryis_rocking_chair"
	object = "ryis_chair"
	soulbind = "forever"
	tags = ["ryis_furniture"]

[ryis_crafting_station]
	name = "Ryis' Crafting Station"
	description = "Ryis' crafting station. Place it in your house so he can use it!"
	icon_sprite = "spr_ui_item_furniture_ryis_crafting_table"
	object = "ryis_crafting_station"
	soulbind = "forever"
	tags = ["ryis_furniture"]

	# SERIDIA SPOUSE FURNITURE

[seridia_desk]
	name = "Seridia's Desk"
	description = "Seridia's desk. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_seridia_desk"
	object = "seridia_desk"
	soulbind = "forever"
	tags = ["seridia_furniture"]

[seridia_chair]
	name = "Seridia's Comfy Chair"
	description = "Seridia's comfy chair. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_seridia_chair"
	object = "seridia_chair"
	soulbind = "forever"
	tags = ["seridia_furniture"]

[seridia_magic_fire]
	name = "Seridia's Magic Fire"
	description = "Seridia's Magic Fire. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_seridia_magic_fire"
	object = "seridia_magic_fire"
	soulbind = "forever"
	tags = ["seridia_furniture"]

	# VALEN SPOUSE FURNITURE

[valen_desk]
	name = "Valen's Desk"
	description = "Valen's desk. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_valen_desk"
	object = "valen_desk"
	soulbind = "forever"
	tags = ["valen_furniture"]

[valen_chair]
	name = "Valen's Comfy Chair"
	description = "Valen's comfy chair. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_valen_chair"
	object = "valen_chair"
	soulbind = "forever"
	tags = ["valen_furniture"]

[valen_workstation]
	name = "Valen's Workstation"
	description = "Valen's workstation. Place it in your house so she can use it!"
	icon_sprite = "spr_ui_item_furniture_valen_potion_station"
	object = "valen_workstation"
	soulbind = "forever"
	tags = ["valen_furniture"]
