# <---------SPRING FESTIVAL SET ITEMS------------->

[spring_festival_planter]
	name = "Breath of Spring Planter"
	description = "A cute white and pink planter vase full of breath of spring flowers."
	value = { bin = 250, store = 500 }
	icon_sprite = "spr_ui_item_decor_spring_festival_planter"
	object = "spring_festival_planter"
	tags = ["furniture"]

[spring_festival_large_planter]
	name = "Breath of Spring Large Planter"
	description = "A large white and pink planter full of breath of spring flowers."
	value = { bin = 350, store = 700 }
	icon_sprite = "spr_ui_item_decor_spring_festival_large_planter"
	object = "spring_festival_large_planter"
	tags = ["furniture"]

[spring_festival_basket]
	name = "Breath of Spring Basket"
	description = "A cute white and pink basket full of breath of spring flowers."
	value = { bin = 250, store = 500 }
	icon_sprite = "spr_ui_item_decor_spring_festival_basket"
	object = "spring_festival_basket"
	tags = ["furniture"]

[spring_festival_flower_chest]
	name = "Breath of Spring Storage Chest"
	description = "A cute pink floral storage chest with a large storage capacity."
	value = { bin = 250, store = 1000 }
	icon_sprite = "spr_ui_item_decor_spring_festival_flower_chest"
	object = "spring_festival_flower_chest"
	tags = ["furniture"]

[spring_festival_wreath]
	name = "Breath of Spring Wreath"
	description = "A lovely wreath featuring breath of spring flowers and a large pink bow."
	value = { bin = 100, store = 200 }
	icon_sprite = "spr_ui_item_decor_spring_festival_wreath"
	object = "spring_festival_wreath"
	tags = ["furniture"]

[spring_festival_breath_of_spring_wreath]
	name = "Deluxe Breath of Spring Wreath"
	description = "A deluxe wreath made of large breath of spring flowers woven together."
	value = { bin = 150, store = 300 }
	icon_sprite = "spr_ui_item_decor_spring_festival_breath_of_spring_wreath"
	object = "spring_festival_breath_of_spring_wreath"
	tags = ["furniture"]
