# <---------SPRING SET ITEMS (MUSEUM REWARDS)------------->

[spring_bed_orange]
	icon_sprite = "spr_ui_item_furniture_spring_bed_orange"
	name = "Spring Bed"
	description = "A spring themed bed with yellow petal patterned sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_bed_orange"
	tags = ["furniture", "single_bed", "spring_set"]
	recipe_key = "spring_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "daffodil" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_double_bed_orange]
	icon_sprite = "spr_ui_item_furniture_spring_double_bed_orange"
	name = "Spring Double Bed"
	description = "A spring themed double bed with yellow petal patterned sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_double_bed_orange"
	tags = ["furniture", "double_bed", "spring_set"]
	recipe_key = "spring_double_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 5, item = "cattail" },
		{ count = 2, item = "daffodil" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_flooring_orange]
	icon_sprite = "spr_ui_item_furniture_spring_flooring_orange"
	name = "Spring Flooring"
	description = "Light yellow-orange wood flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "spring_orange"
	crafting_preview_sprite = "spr_ui_furniture_spring_floor_orange_preview"
	tags = ["furniture", "wood_flooring", "spring_set"]
	recipe_key = "spring_flooring"
	crafting_level_requirement = 1
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 1, item = "ore_copper" },
		{ hours = 0, minutes = 20 },
	]

[spring_lamp_orange]
	icon_sprite = "spr_ui_item_furniture_spring_lamp_orange"
	name = "Spring Lamp"
	description = "A yellow lamp in the shape of a vase of flowers."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_lamp_orange"
	tags = ["furniture", "table_lighting", "spring_set"]
	recipe_key = "spring_lamp"
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[spring_potted_tree_orange]
	icon_sprite = "spr_ui_item_furniture_spring_potted_tree_orange"
	name = "Spring Potted Tree"
	description = "A flowering tree in a yellow-orange pot."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_potted_tree_orange"
	tags = ["furniture", "potted_tree", "spring_set"]
	recipe_key = "spring_potted_tree"
	crafting_level_requirement = 4
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 2, item = "sod" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 30 },
	]

[spring_rug_orange]
	icon_sprite = "spr_ui_item_furniture_spring_rug_orange"
	name = "Spring Flower Rug"
	description = "A yellow rug in the shape of a flower."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_rug_orange"
	tags = ["furniture", "medium_rug", "spring_set"]
	recipe_key = "spring_rug"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 2, item = "feather" },
		{ count = 1, item = "daffodil" },
		{ hours = 0, minutes = 30 },
	]

[spring_sofa_orange]
	icon_sprite = "spr_ui_item_furniture_spring_sofa_orange"
	name = "Spring Sofa"
	description = "A pretty yellow sofa."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_sofa_orange"
	tags = ["furniture", "sofa", "spring_set"]
	recipe_key = "spring_sofa"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "daffodil" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_wallpaper_orange]
	icon_sprite = "spr_ui_item_furniture_spring_wallpaper_orange"
	name = "Spring Wallpaper"
	description = "A light yellow-orange petal patterned wallpaper."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "spring_orange"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_spring_wall_orange_preview"
	tags = ["furniture", "wallpaper", "spring_set"]
	recipe_key = "spring_wallpaper"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 3, item = "daffodil" },
		{ hours = 0, minutes = 20 },
	]

[spring_bed_pink]
	icon_sprite = "spr_ui_item_furniture_spring_bed_pink"
	name = "Spring Bed"
	description = "A spring themed bed with pink petal patterned sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_bed_pink"
	tags = ["furniture", "single_bed", "spring_set"]
	recipe_key = "spring_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "tulip" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_double_bed_pink]
	icon_sprite = "spr_ui_item_furniture_spring_double_bed_pink"
	name = "Spring Double Bed"
	description = "A spring themed double bed with pink petal patterned sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_double_bed_pink"
	tags = ["furniture", "double_bed", "spring_set"]
	recipe_key = "spring_double_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 5, item = "cattail" },
		{ count = 2, item = "tulip" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_flooring_pink]
	icon_sprite = "spr_ui_item_furniture_spring_flooring_pink"
	name = "Spring Flooring"
	description = "Pink wood flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "spring_pink"
	crafting_preview_sprite = "spr_ui_furniture_spring_floor_pink_preview"
	tags = ["furniture", "wood_flooring", "spring_set"]
	recipe_key = "spring_flooring"
	crafting_level_requirement = 1
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 1, item = "ore_ruby" },
		{ hours = 0, minutes = 20 },
	]

[spring_lamp_pink]
	icon_sprite = "spr_ui_item_furniture_spring_lamp_pink"
	name = "Spring Lamp"
	description = "A pink lamp in the shape of a vase of flowers."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_lamp_pink"
	tags = ["furniture", "table_lighting", "spring_set"]
	recipe_key = "spring_lamp"
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[spring_potted_tree_pink]
	icon_sprite = "spr_ui_item_furniture_spring_potted_tree_pink"
	name = "Spring Potted Tree"
	description = "A flowering tree in a pink pot."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_potted_tree_pink"
	tags = ["furniture", "potted_tree", "spring_set"]
	recipe_key = "spring_potted_tree"
	crafting_level_requirement = 4
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 2, item = "sod" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 30 },
	]

[spring_rug_pink]
	icon_sprite = "spr_ui_item_furniture_spring_rug_pink"
	name = "Spring Flower Rug"
	description = "A light pink rug in the shape of a flower."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_rug_pink"
	tags = ["furniture", "medium_rug", "spring_set"]
	recipe_key = "spring_rug"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 2, item = "feather" },
		{ count = 1, item = "tulip" },
		{ hours = 0, minutes = 30 },
	]

[spring_sofa_pink]
	icon_sprite = "spr_ui_item_furniture_spring_sofa_pink"
	name = "Spring Sofa"
	description = "A pretty pink sofa."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_sofa_pink"
	tags = ["furniture", "sofa", "spring_set"]
	recipe_key = "spring_sofa"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "tulip" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_wallpaper_pink]
	icon_sprite = "spr_ui_item_furniture_spring_wallpaper_pink"
	name = "Spring Wallpaper"
	description = "A pink petal patterned wallpaper."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "spring_pink"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_spring_wall_pink_preview"
	tags = ["furniture", "wallpaper", "spring_set"]
	recipe_key = "spring_wallpaper"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 3, item = "tulip" },
		{ hours = 0, minutes = 20 },
	]

[spring_bed_purple]
	icon_sprite = "spr_ui_item_furniture_spring_bed_purple"
	name = "Spring Bed"
	description = "A spring themed bed with purple petal patterned sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_bed_purple"
	tags = ["furniture", "single_bed", "spring_set"]
	recipe_key = "spring_bed"
	crafting_level_requirement = 6
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "lilac" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_double_bed_purple]
	icon_sprite = "spr_ui_item_furniture_spring_double_bed_purple"
	name = "Spring Double Bed"
	description = "A spring themed double bed with purple petal patterned sheets."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_double_bed_purple"
	tags = ["furniture", "double_bed", "spring_set"]
	recipe_key = "spring_double_bed"
	crafting_level_requirement = 8
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 5, item = "cattail" },
		{ count = 2, item = "lilac" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_flooring_purple]
	icon_sprite = "spr_ui_item_furniture_spring_flooring_purple"
	name = "Spring Flooring"
	description = "Purple wood flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "spring_purple"
	crafting_preview_sprite = "spr_ui_furniture_spring_floor_purple_preview"
	tags = ["furniture", "wood_flooring", "spring_set"]
	recipe_key = "spring_flooring"
	crafting_level_requirement = 1
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 1, item = "ore_sapphire" },
		{ hours = 0, minutes = 20 },
	]

[spring_lamp_purple]
	icon_sprite = "spr_ui_item_furniture_spring_lamp_purple"
	name = "Spring Lamp"
	description = "A purple lamp in the shape of a vase of flowers."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_lamp_purple"
	tags = ["furniture", "table_lighting", "spring_set"]
	recipe_key = "spring_lamp"
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 3, item = "glass" },
		{ count = 1, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]

[spring_potted_tree_purple]
	icon_sprite = "spr_ui_item_furniture_spring_potted_tree_purple"
	name = "Spring Potted Tree"
	description = "A flowering tree in a purple pot."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_potted_tree_purple"
	tags = ["furniture", "potted_tree", "spring_set"]
	recipe_key = "spring_potted_tree"
	crafting_level_requirement = 4
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 2, item = "sod" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 30 },
	]

[spring_rug_purple]
	icon_sprite = "spr_ui_item_furniture_spring_rug_purple"
	name = "Spring Flower Rug"
	description = "A purple rug in the shape of a flower."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_rug_purple"
	tags = ["furniture", "medium_rug", "spring_set"]
	recipe_key = "spring_rug"
	crafting_level_requirement = 1
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 2, item = "feather" },
		{ count = 1, item = "lilac" },
		{ hours = 0, minutes = 30 },
	]

[spring_sofa_purple]
	icon_sprite = "spr_ui_item_furniture_spring_sofa_purple"
	name = "Spring Sofa"
	description = "A pretty purple sofa."
	value = { bin = "self.recipe * 1.1" }
	object = "spring_sofa_purple"
	tags = ["furniture", "sofa", "spring_set"]
	recipe_key = "spring_sofa"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 5, item = "cattail" },
		{ count = 1, item = "lilac" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[spring_wallpaper_purple]
	icon_sprite = "spr_ui_item_furniture_spring_wallpaper_purple"
	name = "Spring Wallpaper"
	description = "A light purple petal patterned wallpaper."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "spring_purple"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_spring_wall_purple_preview"
	tags = ["furniture", "wallpaper", "spring_set"]
	recipe_key = "spring_wallpaper"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 3, item = "lilac" },
		{ hours = 0, minutes = 20 },
	]
