# <---------STARTER FARM SET------------->

[campfire]
	icon_sprite = "spr_ui_item_decor_beach_campfire"
	name = "Campfire"
	value = { bin = "self.recipe * 1.1", store = 200 }
	description = "This crackling campfire is perfectly cozy."
	recipe_is_default = true
	object = "campfire"
	#crafting_preview_sprite = "spr_beach_campfire_spring_on"
	crafting_level_requirement = 4
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 30, item = "basic_wood" },
		{ count = 3, item = "peat" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "farm_decor", "starter_farm_set"]

[starter_potted_plant]
	description = "Freshly potted yellow flowers."
	icon_sprite = "spr_ui_item_decor_starter_potted_plant"
	name = "Potted Plant"
	value = { bin = "self.recipe * 1.1", store = 100 }
	object = "starter_potted_plant"
	tags = ["furniture", "tabletop_plant", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 2
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 3, item = "sod" },
		{ hours = 0, minutes = 30 },
	]

[starter_scarecrow]
	description = "A friendly scarecrow."
	icon_sprite = "spr_ui_item_decor_starter_scarecrow"
	name = "Scarecrow"
	value = { bin = "self.recipe * 1.1", store = 160 }
	object = "starter_scarecrow"
	tags = ["furniture", "farm_decor", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 15, item = "hay" },
		{ count = 10, item = "fiber" },
		{ hours = 0, minutes = 30 },
	]

[starter_bird_house_red] # needs description, recipe, value
	description = "A simple birdhouse. Wild birds like to perch on it."
	icon_sprite = "spr_ui_item_decor_starter_bird_house_red"
	name = "Birdhouse"
	value = { bin = "self.recipe * 1.1", store = 160 }
	object = "starter_bird_house_red"
	tags = ["furniture", "farm_decor", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "basic_wood" },
		{ count = 15, item = "ore_stone" },
		{ count = 10, item = "hay" },
		{ hours = 0, minutes = 30 },
	]


[starter_stone_path]
	description = "Paved stones for making paths."
	icon_sprite = "spr_ui_item_decor_starter_stone_path_single"
	name = "Stone Path"
	value = { bin = "self.recipe * 1.1", store = 10 }
	object = "starter_stone_path_single"
	tags = ["furniture", "ground_decor", "stone_path", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 2, item = "ore_stone" }, { hours = 0, minutes = 10 }]

[starter_stone_path_double]
	description = "Paved stones for making paths."
	icon_sprite = "spr_ui_item_decor_starter_stone_path"
	name = "Stone Path"
	value = { bin = "self.recipe * 1.1", store = 10 }
	object = "starter_stone_path_double"
	tags = ["furniture", "ground_decor", "stone_path", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 2, item = "ore_stone" }, { hours = 0, minutes = 10 }]

[starter_well]
	description = "Well, well, well, if it isn't... a well."
	icon_sprite = "spr_ui_item_decor_starter_well"
	name = "Water Well"
	value = { bin = "self.recipe * 1.1", store = 300 }
	object = "starter_well"
	tags = ["furniture", "farm_decor", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 2
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 20, item = "basic_wood" },
		{ hours = 0, minutes = 20 },
	]

[starter_wheelbarrow]
	description = "A wheelbarrow filled with a variety of spring flowers."
	icon_sprite = "spr_ui_item_decor_starter_wheelbarrow"
	name = "Wheelbarrow"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "starter_wheelbarrow"
	tags = ["furniture", "garden_decor", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 4
	recipe = [
		{ count = 25, item = "basic_wood" },
		{ count = 1, item = "lilac" },
		{ count = 1, item = "tulip" },
		{ count = 1, item = "dandelion" },
		{ hours = 0, minutes = 40 },
	]

[starter_wood_fence]
	description = "A simple wooden fence."
	icon_sprite = "spr_ui_item_decor_starter_wood_fence"
	crafting_preview_sprite = "spr_ui_decor_wooden_fence_preview"
	name = "Wooden Fence"
	value = { bin = "self.recipe * 1.1", store = 20 }
	object = "starter_wood_fence"
	tags = ["furniture", "fencing", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 1
	recipe = [{ count = 2, item = "basic_wood" }, { hours = 0, minutes = 10 }]

[starter_shipping_box]
	description = "A placeable shipping bin. Put items inside to sell them overnight."
	icon_sprite = "spr_ui_item_basic_misc_shipping_bin"
	name = "Shipping Bin"
	object = "starter_shipping_box"
	tags = ["furniture", "chest_and_storage", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 4
	recipe = [{ count = 100, item = "basic_wood" }, { hours = 0, minutes = 10 }]
	value = { bin = "self.recipe * 1.1", store = 500 }

[spooky_haybale]
	description = "For those who love hay."
	icon_sprite = "spr_ui_item_decor_spooky_haybale"
	name = "Hay Bale"
	value = { bin = "self.recipe * 1.1", store = 200 }
	object = "spooky_haybale"
	tags = ["furniture", "farm_decor", "starter_farm_set"]
	crafting_level_requirement = 2
	recipe_is_default = true
	recipe = [
		{ count = 10, item = "hay" },
		{ hours = 0, minutes = 20 },
	]

[dirt_clear]
	name = "Dirt Tile Clear"
	description = "Use this item to clear decorative details from a dirt tile."
	icon_sprite = "spr_ui_item_decor_starter_dirt_clear"
	crafting_preview_sprite = "spr_ui_decor_dirt_clear_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "dirt_normal", ground_kind = "dirt" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[dirt_dot_one]
	name = "Dirt Tile 1 Dot"
	description = "Use this item to add a single dot detail to a dirt tile."
	icon_sprite = "spr_ui_item_decor_starter_dirt_dot_one"
	crafting_preview_sprite = "spr_ui_decor_dirt_dot_one_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "dirt_variant_one", ground_kind = "dirt" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[dirt_dot_two]
	name = "Dirt Tile 2 Dots"
	description = "Use this item to add two dot details to a dirt tile."
	icon_sprite = "spr_ui_item_decor_starter_dirt_dot_two"
	crafting_preview_sprite = "spr_ui_decor_dirt_dot_two_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "dirt_variant_two", ground_kind = "dirt" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[dirt_dot_three]
	name = "Dirt Tile 3 Dots"
	description = "Use this item to add three dot details to a dirt tile."
	icon_sprite = "spr_ui_item_decor_starter_dirt_dot_three"
	crafting_preview_sprite = "spr_ui_decor_dirt_dot_three_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "dirt_variant_three", ground_kind = "dirt" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[field_clear]
	name = "Grass Tile Clear"
	description = "Use this item to clear decorative details from a grass tile."
	icon_sprite = "spr_ui_item_decor_starter_field_clear"
	crafting_preview_sprite = "spr_ui_decor_field_clear_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "grass_normal", ground_kind = "grass" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[field_flower]
	name = "Grass Tile Flower"
	description = "Use this item to add a single flower detail to a grass tile."
	icon_sprite = "spr_ui_item_decor_starter_field_flower"
	crafting_preview_sprite = "spr_ui_decor_field_flower_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "flower_variant_one", ground_kind = "grass" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[field_flower_two]
	name = "Grass Tile 2 Flowers"
	description = "Use this item to add two flower details to a grass tile."
	icon_sprite = "spr_ui_item_decor_starter_field_flower_two"
	crafting_preview_sprite = "spr_ui_decor_field_flower_two_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "flower_variant_two", ground_kind = "grass" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[field_grass]
	name = "Grass Tile Blades"
	description = "Use this item to add a grass blade detail to a grass tile."
	icon_sprite = "spr_ui_item_decor_starter_field_grass"
	crafting_preview_sprite = "spr_ui_decor_field_grass_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "grass_variant_one", ground_kind = "grass" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[field_grass_two]
	name = "Field Grass 2 Blades"
	description = "Use this item to add two grass blade details to a grass tile."
	icon_sprite = "spr_ui_item_decor_starter_field_grass_two"
	crafting_preview_sprite = "spr_ui_decor_field_grass_two_preview"
	value = { bin = "self.recipe * 1.1", store = 10 }
	tags = ["furniture", "ground_decor", "starter_farm_set"]
	tile_placement = { index = "grass_variant_two", ground_kind = "grass" }
	crafting_level_requirement = 1
	recipe = [{ count = 1, item = "sod" }, { hours = 0, minutes = 10 }]
	recipe_is_default = true

[farm_bridge]
	name = "Starter Farm Bridge"
	description = "A basic farm bridge. Place it over water to connect farm areas."
	icon_sprite = "spr_ui_item_decor_starter_bridge"
	value = { bin = "self.recipe*1.1" }
	object = "farm_bridge"
	crafting_level_requirement = 20
	crafting_preview_sprite = "spr_ui_object_basic_bridge_preview"
	recipe = [
		{ count = 20, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ hours = 0, minutes = 20 },
	]
	recipe_key = "farm_bridge"
	tags = ["furniture", "misc_functional"]

	#added from no set

[picket_fence]
	description = "A placeable picket fence."
	icon_sprite = "spr_ui_item_fence_picket"
	crafting_preview_sprite = "spr_ui_decor_picket_fence_preview"
	name = "Picket Fence"
	object = "picket_fence"
	tags = ["furniture", "fencing", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 2
	value = { bin = "self.recipe * 1.1" }
	recipe = [{ count = 1, item = "hard_wood" }, { hours = 0, minutes = 10 }]


[stone_wall]
	description = "Stone wall fencing made by carefully arranging stones by hand."
	icon_sprite = "spr_ui_item_fence_stone_wall"
	crafting_preview_sprite = "spr_ui_decor_stone_wall_preview"
	name = "Stone Wall"
	object = "stone_wall"
	tags = ["furniture", "fencing", "starter_farm_set"]
	recipe_is_default = true
	crafting_level_requirement = 4
	recipe = [{ count = 5, item = "ore_stone" }, { hours = 0, minutes = 10 }]
	value = { bin = "self.recipe * 1.1" }

	# <---------FARM HOUSE------------->

[farm_house_calendar] #in game
	description = "A placeable farmhouse calendar."
	icon_sprite = "spr_ui_item_object_wall_calendar"
	name = "Farmhouse Calendar"
	object = "farm_house_calendar"
	tags = ["furniture", "calendar", "starter_farm_set"]
	recipe_is_default = true
	value = { bin = "self.recipe * 1.1" }
	crafting_level_requirement = 1
	recipe = [{ count = 5, item = "paper" }, { hours = 0, minutes = 10 }]
