# stone decor set

[stone_table_v1]
	icon_sprite = "spr_ui_item_decor_stone_table_v1"
	name = "Stone Table"
	description = "A small stone table."
	object = "stone_table_v1"
	tags = ["furniture", "stone_garden_set", "side_table"]
	recipe_key = "stone_table"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 8

[stone_lamp_v1]
	icon_sprite = "spr_ui_item_decor_stone_lamp_v1"
	name = "Stone Lamp"
	description = "A stone lamp."
	object = "stone_lamp_v1"
	tags = ["furniture", "stone_garden_set", "floor_lighting"]
	recipe_key = "stone_lamp"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 6

[stone_bench_v1]
	icon_sprite = "spr_ui_item_decor_stone_bench_v1"
	name = "Stone Bench"
	description = "A stone bench."
	object = "stone_bench_v1"
	tags = ["furniture", "stone_garden_set", "misc_seating"]
	recipe_key = "stone_bench"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 1

[large_paving_stone_v1]
	icon_sprite = "spr_ui_item_decor_large_paving_stone_v1"
	name = "Large Paving Stone"
	description = "A large paving stone."
	object = "large_paving_stone_v1"
	tags = ["furniture", "stone_garden_set", "ground_decor", "stone_path"]
	recipe_key = "large_paving_stone"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 1, item = "peat" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 4

[stone_storage_chest_v1]
	icon_sprite = "spr_ui_item_decor_stone_storage_chest_v1"
	name = "Stone Storage Chest"
	description = "A stone storage chest with a large storage capacity."
	object = "stone_storage_chest_v1"
	tags = ["furniture", "stone_garden_set", "chest_and_storage"]
	recipe_key = "stone_storage_chest"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "monster_fang" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 10

[stone_table_v2]
	icon_sprite = "spr_ui_item_decor_stone_table_v2"
	name = "Stone Table"
	description = "A small stone table."
	object = "stone_table_v2"
	tags = ["furniture", "stone_garden_set", "side_table"]
	recipe_key = "stone_table"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 8

[stone_lamp_v2]
	icon_sprite = "spr_ui_item_decor_stone_lamp_v2"
	name = "Stone Lamp"
	description = "A stone lamp."
	object = "stone_lamp_v2"
	tags = ["furniture", "stone_garden_set", "floor_lighting"]
	recipe_key = "stone_lamp"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 6

[stone_bench_v2]
	icon_sprite = "spr_ui_item_decor_stone_bench_v2"
	name = "Stone Bench"
	description = "A stone bench."
	object = "stone_bench_v2"
	tags = ["furniture", "stone_garden_set", "misc_seating"]
	recipe_key = "stone_bench"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 1

[large_paving_stone_v2]
	icon_sprite = "spr_ui_item_decor_large_paving_stone_v2"
	name = "Large Paving Stone"
	description = "A large paving stone."
	object = "large_paving_stone_v2"
	tags = ["furniture", "stone_garden_set", "ground_decor", "stone_path"]
	recipe_key = "large_paving_stone"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 1, item = "peat" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 4

[stone_storage_chest_v2]
	icon_sprite = "spr_ui_item_decor_stone_storage_chest_v2"
	name = "Stone Storage Chest"
	description = "A stone storage chest with a large storage capacity."
	object = "stone_storage_chest_v2"
	tags = ["furniture", "stone_garden_set", "chest_and_storage"]
	recipe_key = "stone_storage_chest"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "monster_fang" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 10

[stone_table_v3]
	icon_sprite = "spr_ui_item_decor_stone_table_v3"
	name = "Stone Table"
	description = "A small stone table."
	object = "stone_table_v3"
	tags = ["furniture", "stone_garden_set", "side_table"]
	recipe_key = "stone_table"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 8

[stone_lamp_v3]
	icon_sprite = "spr_ui_item_decor_stone_lamp_v3"
	name = "Stone Lamp"
	description = "A stone lamp."
	object = "stone_lamp_v3"
	tags = ["furniture", "stone_garden_set", "floor_lighting"]
	recipe_key = "stone_lamp"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 6

[stone_bench_v3]
	icon_sprite = "spr_ui_item_decor_stone_bench_v3"
	name = "Stone Bench"
	description = "A stone bench."
	object = "stone_bench_v3"
	tags = ["furniture", "stone_garden_set", "misc_seating"]
	recipe_key = "stone_bench"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 30, item = "ore_stone" },
		{ count = 2, item = "sap" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 1

[large_paving_stone_v3]
	icon_sprite = "spr_ui_item_decor_large_paving_stone_v3"
	name = "Large Paving Stone"
	description = "A large paving stone."
	object = "large_paving_stone_v3"
	tags = ["furniture", "stone_garden_set", "ground_decor", "stone_path"]
	recipe_key = "large_paving_stone"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 1, item = "peat" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 4

[stone_storage_chest_v3]
	icon_sprite = "spr_ui_item_decor_stone_storage_chest_v3"
	name = "Stone Storage Chest"
	description = "A stone storage chest with a large storage capacity."
	object = "stone_storage_chest_v3"
	tags = ["furniture", "stone_garden_set", "chest_and_storage"]
	recipe_key = "stone_storage_chest"
	value = { bin = "self.recipe*1.1" }
	recipe = [
		{ count = 50, item = "ore_stone" },
		{ count = 2, item = "copper_ingot" },
		{ count = 2, item = "monster_fang" },
		{ hours = 0, minutes = 20 },
	]
	crafting_level_requirement = 10
