# <---------SUMMER SET ITEMS (MUSEUM REWARDS)------------->

[summer_bed_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_bed_yellow"
	name = "Summer Bed"
	description = "A white linen bed with a yellow flower vine wrapped around the headboard."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_bed_yellow"
	tags = ["furniture", "single_bed", "summer_set"]
	recipe_key = "summer_bed"
	crafting_level_requirement = 12
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 2, item = "duck_feather" },
		{ count = 1, item = "daisy" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[summer_chair_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_chair_yellow"
	name = "Summer Chair"
	description = "A white lawn chair."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_chair_yellow"
	tags = ["furniture", "accent_chair", "summer_set"]
	recipe_key = "summer_chair"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]

[summer_double_bed_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_double_bed_yellow"
	name = "Summer Double Bed"
	description = "A white linen double bed with a yellow flower vine wrapped around the headboard."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_double_bed_yellow"
	tags = ["furniture", "double_bed", "summer_set"]
	recipe_key = "summer_double_bed"
	crafting_level_requirement = 14
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 4, item = "duck_feather" },
		{ count = 2, item = "daisy" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[summer_flooring_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_flooring_yellow"
	name = "Summer Flooring"
	description = "A cool-toned grassy floor speckled with blue flowers."
	value = { bin = "self.recipe * 1.1" }
	flooring = "summer_yellow"
	crafting_preview_sprite = "spr_ui_furniture_summer_floor_yellow_preview"
	tags = ["furniture", "novelty_flooring", "summer_set"]
	recipe_key = "summer_flooring"
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "sod" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 20 },
	]

[summer_jar_lamp_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_jar_lamp_yellow"
	#crafting_preview_sprite = "spr_furniture_summer_jar_lamp_yellow_on"
	name = "Summer Jar Lamp"
	description = "A lamp that mimics a jar full of yellow fireflies."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_jar_lamp_yellow"
	tags = ["furniture", "table_lighting", "summer_set"]
	recipe_key = "summer_jar_lamp"
	crafting_level_requirement = 4
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 1, item = "firefly" },
		{ hours = 0, minutes = 20 },
	]

[summer_rug_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_rug_yellow"
	name = "Summer Flower Rug"
	description = "A yellow rug in the shape of a sunflower."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_rug_yellow"
	tags = ["furniture", "medium_rug", "summer_set"]
	recipe_key = "summer_rug"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 1, item = "sunflower" },
		{ hours = 0, minutes = 20 },
	]

[summer_table_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_table_yellow"
	name = "Summer Table"
	description = "A white wooden table."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_table_yellow"
	tags = ["furniture", "dining_table", "summer_set"]
	recipe_key = "summer_table"
	crafting_level_requirement = 8
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "silver_ingot" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[summer_wallpaper_yellow]
	icon_sprite = "spr_ui_item_furniture_summer_wallpaper_yellow"
	name = "Summer Wallpaper"
	description = "A wallpaper that looks like a trellis with yellow flowers growing on it."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "summer_yellow"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_summer_wallpaper_yellow_preview"
	tags = ["furniture", "wallpaper", "summer_set"]
	recipe_key = "summer_wallpaper"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 3, item = "daisy" },
		{ hours = 0, minutes = 20 },
	]

[summer_bed_red]
	icon_sprite = "spr_ui_item_furniture_summer_bed_red"
	name = "Summer Bed"
	description = "A white linen bed with a red flower vine wrapped around the headboard."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_bed_red"
	tags = ["furniture", "single_bed", "summer_set"]
	recipe_key = "summer_bed"
	crafting_level_requirement = 12
	recipe = [
		{ count = 40, item = "basic_wood" },
		{ count = 2, item = "duck_feather" },
		{ count = 1, item = "cosmos" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 40 },
	]

[summer_chair_red]
	icon_sprite = "spr_ui_item_furniture_summer_chair_red"
	name = "Summer Chair"
	description = "A white lawn chair with a pink cushion."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_chair_red"
	tags = ["furniture", "accent_chair", "summer_set"]
	recipe_key = "summer_chair"
	crafting_level_requirement = 6
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 2, item = "duck_feather" },
		{ hours = 0, minutes = 20 },
	]

[summer_double_bed_red]
	icon_sprite = "spr_ui_item_furniture_summer_double_bed_red"
	name = "Summer Double Bed"
	description = "A white linen double bed with a red flower vine wrapped around the headboard."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_double_bed_red"
	tags = ["furniture", "double_bed", "summer_set"]
	recipe_key = "summer_double_bed"
	crafting_level_requirement = 14
	recipe = [
		{ count = 60, item = "basic_wood" },
		{ count = 4, item = "hard_wood" },
		{ count = 4, item = "duck_feather" },
		{ count = 2, item = "cosmos" },
		{ count = 6, item = "sap" },
		{ hours = 0, minutes = 50 },
	]

[summer_flooring_red]
	icon_sprite = "spr_ui_item_furniture_summer_flooring_red"
	name = "Summer Flooring"
	description = "A warm-toned grassy floor speckled with white flowers."
	value = { bin = "self.recipe * 1.1" }
	flooring = "summer_red"
	crafting_preview_sprite = "spr_ui_furniture_summer_floor_red_preview"
	tags = ["furniture", "novelty_flooring", "summer_set"]
	recipe_key = "summer_flooring"
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "sod" },
		{ count = 2, item = "small_grass_starter" },
		{ hours = 0, minutes = 20 },
	]

[summer_jar_lamp_red]
	icon_sprite = "spr_ui_item_furniture_summer_jar_lamp_red"
	#crafting_preview_sprite = "spr_furniture_summer_jar_lamp_red_on"
	name = "Summer Jar Lamp"
	description = "A lamp that mimics a jar full of red fireflies."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_jar_lamp_red"
	tags = ["furniture", "table_lighting", "summer_set"]
	recipe_key = "summer_jar_lamp"
	crafting_level_requirement = 4
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 1, item = "firefly" },
		{ hours = 0, minutes = 20 },
	]

[summer_rug_red]
	icon_sprite = "spr_ui_item_furniture_summer_rug_red"
	name = "Summer Flower Rug"
	description = "A red rug in the shape of a cosmos flower."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_rug_red"
	tags = ["furniture", "medium_rug", "summer_set"]
	recipe_key = "summer_rug"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 1, item = "cosmos" },
		{ hours = 0, minutes = 20 },
	]

[summer_table_red]
	icon_sprite = "spr_ui_item_furniture_summer_table_red"
	name = "Summer Table"
	description = "A white wooden table with a red tablecloth."
	value = { bin = "self.recipe * 1.1" }
	object = "summer_table_red"
	tags = ["furniture", "dining_table", "summer_set"]
	recipe_key = "summer_table"
	crafting_level_requirement = 8
	recipe = [
		{ count = 30, item = "basic_wood" },
		{ count = 1, item = "silver_ingot" },
		{ count = 3, item = "sap" },
		{ hours = 0, minutes = 30 },
	]

[summer_wallpaper_red]
	icon_sprite = "spr_ui_item_furniture_summer_wallpaper_red"
	name = "Summer Wallpaper"
	description = "A wallpaper that looks like a trellis with red flowers growing on it."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "summer_red"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_summer_wallpaper_red_preview"
	tags = ["furniture", "wallpaper", "summer_set"]
	recipe_key = "summer_wallpaper"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 3, item = "cosmos" },
		{ hours = 0, minutes = 20 },
	]
