# tabletop clutter set

[coffee_mug_v1]
	icon_sprite = "spr_ui_item_decor_coffee_v1"
	name = "Coffee Mug"
	description = "A decorative green coffee mug."
	value = { bin = "self.recipe * 1.1" }
	object = "coffee_mug_v1"
	recipe_key = "coffee_mug"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "coffee" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]


[coffee_mug_v2]
	icon_sprite = "spr_ui_item_decor_coffee_v2"
	name = "Coffee Mug"
	description = "A decorative white coffee mug."
	value = { bin = "self.recipe * 1.1" }
	object = "coffee_mug_v2"
	recipe_key = "coffee_mug"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "coffee" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]


[coffee_mug_v3]
	icon_sprite = "spr_ui_item_decor_coffee_v3"
	name = "Coffee Mug"
	description = "A decorative red coffee mug."
	value = { bin = "self.recipe * 1.1" }
	object = "coffee_mug_v3"
	recipe_key = "coffee_mug"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "coffee" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]


[espresso_cup_v1]
	icon_sprite = "spr_ui_item_decor_espresso_v1"
	name = "Espresso Cup"
	description = "A decorative green espresso cup."
	value = { bin = "self.recipe * 1.1" }
	object = "espresso_cup_v1"
	recipe_key = "espresso_cup"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 1, item = "coffee" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]


[espresso_cup_v2]
	icon_sprite = "spr_ui_item_decor_espresso_v2"
	name = "Espresso Cup"
	description = "A decorative white espresso cup."
	value = { bin = "self.recipe * 1.1" }
	object = "espresso_cup_v2"
	recipe_key = "espresso_cup"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 1, item = "coffee" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[espresso_cup_v3]
	icon_sprite = "spr_ui_item_decor_espresso_v3"
	name = "Espresso Cup"
	description = "A decorative red espresso cup."
	value = { bin = "self.recipe * 1.1" }
	object = "espresso_cup_v3"
	recipe_key = "espresso_cup"
	crafting_level_requirement = 6
	recipe = [
		{ count = 2, item = "clay" },
		{ count = 1, item = "coffee" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

	#NEW ADDITIONS

[basket]
	icon_sprite = "spr_ui_item_decor_clutter_basket"
	name = "Basket"
	description = "A decorative woven basket."
	value = { bin = "self.recipe * 1.1" }
	object = "basket"
	recipe_key = "basket"
	crafting_level_requirement = 4
	recipe = [
		{ count = 10, item = "hay" },
		{ count = 5, item = "fiber" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[beer_mug]
	icon_sprite = "spr_ui_item_decor_clutter_beer"
	name = "Beer Mug"
	description = "A decorative beer mug."
	value = { bin = "self.recipe * 1.1" }
	object = "beer_mug"
	recipe_key = "beer_mug"
	crafting_level_requirement = 6
	recipe = [
		{ count = 1, item = "beer" },
		{ count = 3, item = "glass" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[box_medium_v1]
	icon_sprite = "spr_ui_item_decor_clutter_box_medium_v1"
	name = "Medium Box"
	description = "A medium sized decorative box."
	value = { bin = "self.recipe * 1.1" }
	object = "box_medium_v1"
	recipe_key = "box_medium"
	crafting_level_requirement = 8
	recipe = [
		{ count = 10, item = "paper" },
		{ count = 1, item = "sap" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[box_small_v1]
	icon_sprite = "spr_ui_item_decor_clutter_box_small_v1"
	name = "Small Box"
	description = "A small decorative blue box."
	value = { bin = "self.recipe * 1.1" }
	object = "box_small_v1"
	recipe_key = "box_small"
	crafting_level_requirement = 6
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 1, item = "sap" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[box_small_v2]
	icon_sprite = "spr_ui_item_decor_clutter_box_small_v2"
	name = "Small Box"
	description = "A small decorative purple box."
	value = { bin = "self.recipe * 1.1" }
	object = "box_small_v2"
	recipe_key = "box_small"
	crafting_level_requirement = 6
	recipe = [
		{ count = 5, item = "paper" },
		{ count = 1, item = "sap" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[candle]
	icon_sprite = "spr_ui_item_decor_clutter_candle"
	name = "Candle"
	description = "A decorative candle."
	value = { bin = "self.recipe * 1.1" }
	object = "candle"
	recipe_key = "candle"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[candle_chamberstick]
	icon_sprite = "spr_ui_item_decor_clutter_candle_chamberstick"
	name = "Candle Chamberstick"
	description = "A decorative candle chamberstick."
	value = { bin = "self.recipe * 1.1" }
	object = "candle_chamberstick"
	recipe_key = "candle_chamberstick"
	crafting_level_requirement = 2
	recipe = [
		{ count = 5, item = "sap" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[glass_absinthe]
	icon_sprite = "spr_ui_item_decor_clutter_glass_absinthe"
	name = "Absinthe Glass"
	description = "A decorative absinthe glass."
	value = { bin = "self.recipe * 1.1" }
	object = "glass_absinthe"
	recipe_key = "glass_absinthe"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 1, item = "ore_emerald" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[glass_cocktail]
	icon_sprite = "spr_ui_item_decor_clutter_glass_cocktail"
	name = "Cocktail Glass"
	description = "A decorative cocktail glass."
	value = { bin = "self.recipe * 1.1" }
	object = "glass_cocktail"
	recipe_key = "glass_cocktail"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 1, item = "orange" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[glass_lemonade]
	icon_sprite = "spr_ui_item_decor_clutter_glass_lemonade"
	name = "Lemonade Glass"
	description = "A decorative lemonade glass."
	value = { bin = "self.recipe * 1.1" }
	object = "glass_lemonade"
	recipe_key = "glass_lemonade"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 1, item = "lemon" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[glass_milk]
	icon_sprite = "spr_ui_item_decor_clutter_glass_milk"
	name = "Milk Glass"
	description = "A decorative milk glass."
	value = { bin = "self.recipe * 1.1" }
	object = "glass_milk"
	recipe_key = "glass_milk"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 1, item = "cow_milk" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[glass_water]
	icon_sprite = "spr_ui_item_decor_clutter_glass_water"
	name = "Water Glass"
	description = "A decorative water glass."
	value = { bin = "self.recipe * 1.1" }
	object = "glass_water"
	recipe_key = "glass_water"
	crafting_level_requirement = 4
	recipe = [
		{ count = 3, item = "glass" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[glass_whisky]
	icon_sprite = "spr_ui_item_decor_clutter_glass_whisky"
	name = "Whisky Glass"
	description = "A decorative whisky glass."
	value = { bin = "self.recipe * 1.1" }
	object = "glass_whisky"
	recipe_key = "glass_whisky"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "glass" },
		{ count = 2, item = "ice_block" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[green_bottle]
	icon_sprite = "spr_ui_item_decor_clutter_green_bottle"
	name = "Green Bottle"
	description = "A decorative green bottle."
	value = { bin = "self.recipe * 1.1" }
	object = "green_bottle"
	recipe_key = "green_bottle"
	crafting_level_requirement = 4
	recipe = [
		{ count = 1, item = "beer" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[jar_large]
	icon_sprite = "spr_ui_item_decor_clutter_jar_large"
	name = "Large Jar"
	description = "A large decorative glass jar."
	value = { bin = "self.recipe * 1.1" }
	object = "jar_large"
	recipe_key = "jar_large"
	crafting_level_requirement = 8
	recipe = [
		{ count = 15, item = "glass" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[jar_medium]
	icon_sprite = "spr_ui_item_decor_clutter_jar_medium"
	name = "Medium Jar"
	description = "A medium sized decorative glass jar."
	value = { bin = "self.recipe * 1.1" }
	object = "jar_medium"
	recipe_key = "jar_medium"
	crafting_level_requirement = 6
	recipe = [
		{ count = 10, item = "glass" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[jar_pair]
	icon_sprite = "spr_ui_item_decor_clutter_jar_pair"
	name = "Pair of Jars"
	description = "A pair of decorative glass jars."
	value = { bin = "self.recipe * 1.1" }
	object = "jar_pair"
	recipe_key = "jar_pair"
	crafting_level_requirement = 8
	recipe = [
		{ count = 15, item = "glass" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[jar_small]
	icon_sprite = "spr_ui_item_decor_clutter_jar_small"
	name = "Small Jar"
	description = "A small decorative glass jar."
	value = { bin = "self.recipe * 1.1" }
	object = "jar_small"
	recipe_key = "jar_small"
	crafting_level_requirement = 4
	recipe = [
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[notepad_white]
	icon_sprite = "spr_ui_item_decor_clutter_notepad_white"
	name = "Notepad"
	description = "A decorative white notepad."
	value = { bin = "self.recipe * 1.1" }
	object = "notepad_white"
	recipe_key = "notepad"
	crafting_level_requirement = 8
	recipe = [
		{ count = 10, item = "paper" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[notepad_yellow]
	icon_sprite = "spr_ui_item_decor_clutter_notepad_yellow"
	name = "Notepad"
	description = "A decorative yellow notepad."
	value = { bin = "self.recipe * 1.1" }
	object = "notepad_yellow"
	recipe_key = "notepad"
	crafting_level_requirement = 8
	recipe = [
		{ count = 10, item = "paper" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[paper_stack]
	icon_sprite = "spr_ui_item_decor_clutter_paper_stack"
	name = "Paper Stack"
	description = "A decorative stack of paper."
	value = { bin = "self.recipe * 1.1" }
	object = "paper_stack"
	recipe_key = "paper_stack"
	crafting_level_requirement = 8
	recipe = [
		{ count = 10, item = "paper" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[small_vase_v1]
	icon_sprite = "spr_ui_item_decor_clutter_small_vase_v1"
	name = "Small Vase"
	description = "A small white vase with a decorative sprout."
	value = { bin = "self.recipe * 1.1" }
	object = "small_vase_v1"
	recipe_key = "small_vase"
	crafting_level_requirement = 10
	recipe = [
		{ count = 4, item = "clay" },
		{ count = 1, item = "small_grass_starter" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[small_vase_v2]
	icon_sprite = "spr_ui_item_decor_clutter_small_vase_v2"
	name = "Small Vase"
	description = "A small terracotta vase with decorative flower."
	value = { bin = "self.recipe * 1.1" }
	object = "small_vase_v2"
	recipe_key = "small_vase"
	crafting_level_requirement = 10
	recipe = [
		{ count = 4, item = "clay" },
		{ count = 1, item = "small_grass_starter" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[small_vase_v3]
	icon_sprite = "spr_ui_item_decor_clutter_small_vase_v3"
	name = "Small Vase"
	description = "A small purple vase with decorative grass."
	value = { bin = "self.recipe * 1.1" }
	object = "small_vase_v3"
	recipe_key = "small_vase"
	crafting_level_requirement = 10
	recipe = [
		{ count = 4, item = "clay" },
		{ count = 3, item = "hay" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[small_vase_v4]
	icon_sprite = "spr_ui_item_decor_clutter_small_vase_v4"
	name = "Small Vase"
	description = "A small black vase with decorative grass."
	value = { bin = "self.recipe * 1.1" }
	object = "small_vase_v4"
	recipe_key = "small_vase"
	crafting_level_requirement = 10
	recipe = [
		{ count = 4, item = "clay" },
		{ count = 3, item = "hay" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[tea_black]
	icon_sprite = "spr_ui_item_decor_clutter_tea_black"
	name = "Black Tea Cup"
	description = "A decorative cup of black tea."
	value = { bin = "self.recipe * 1.1" }
	object = "tea_black"
	recipe_key = "tea_black"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "tea" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[tea_green]
	icon_sprite = "spr_ui_item_decor_clutter_tea_green"
	name = "Green Tea Cup"
	description = "A decorative cup of green tea."
	value = { bin = "self.recipe * 1.1" }
	object = "tea_green"
	recipe_key = "tea_green"
	crafting_level_requirement = 6
	recipe = [
		{ count = 3, item = "clay" },
		{ count = 1, item = "tea" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[wine_glass_red]
	icon_sprite = "spr_ui_item_decor_clutter_wine_glass_red"
	name = "Red Wine Glass"
	description = "A decorative glass of red wine."
	value = { bin = "self.recipe * 1.1" }
	object = "wine_glass_red"
	recipe_key = "wine_glass_red"
	crafting_level_requirement = 6
	recipe = [
		{ count = 1, item = "red_wine" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[wine_glass_rose]
	icon_sprite = "spr_ui_item_decor_clutter_wine_glass_rose"
	name = "Rose Wine Glass"
	description = "A decorative glass of rose wine."
	value = { bin = "self.recipe * 1.1" }
	object = "wine_glass_rose"
	recipe_key = "wine_glass_rose"
	crafting_level_requirement = 6
	recipe = [
		{ count = 1, item = "red_wine" },
		{ count = 1, item = "white_wine" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]

[wine_glass_white]
	icon_sprite = "spr_ui_item_decor_clutter_wine_glass_white"
	name = "White Wine Glass"
	description = "A decorative white wine glass."
	value = { bin = "self.recipe * 1.1" }
	object = "wine_glass_white"
	recipe_key = "wine_glass_white"
	crafting_level_requirement = 6
	recipe = [
		{ count = 1, item = "white_wine" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "misc_decor", "tabletop_clutter"]
