# <---------TIDE SET ITEMS (TIDE CAVERNS BIOME)------------>

[coral_lamp_blue]
	name = "Coral Lamp"
	description = "A blue coral lamp."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_lamp_blue"
	tags = ["furniture", "tide_caverns_set", "table_lighting"]
	object = "coral_lamp_blue"
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "coral" },
		{ count = 5, item = "glass" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_lamp"

[coral_chair_blue]
	name = "Coral Chair"
	description = "A blue coral chair."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_chair_blue"
	tags = ["furniture", "tide_caverns_set", "dining_chair"]
	object = "coral_chair_blue"
	crafting_level_requirement = 6
	recipe = [
		{ count = 15, item = "coral" },
		{ count = 5, item = "sap" },
		{ count = 3, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_chair"

[coral_table_blue]
	name = "Coral Table"
	description = "A blue coral table."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_table_blue"
	tags = ["furniture", "tide_caverns_set", "coffee_table"]
	object = "coral_table_blue"
	crafting_level_requirement = 8
	recipe = [
		{ count = 20, item = "coral" },
		{ count = 5, item = "glass" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_table"

[coral_storage_chest_blue]
	name = "Coral Storage Chest"
	description = "A blue coral chest with a large storage capacity."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_storage_chest_blue"
	tags = ["furniture", "tide_caverns_set", "chest_and_storage"]
	object = "coral_storage_chest_blue"
	crafting_level_requirement = 6
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "coral" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_storage_chest"

[coral_lamp_purple]
	name = "Coral Lamp"
	description = "A purple coral lamp."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_lamp_purple"
	tags = ["furniture", "tide_caverns_set", "table_lighting"]
	object = "coral_lamp_purple"
	crafting_level_requirement = 4
	recipe = [
		{ count = 15, item = "coral" },
		{ count = 5, item = "glass" },
		{ count = 2, item = "monster_core" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_lamp"

[coral_chair_purple]
	name = "Coral Chair"
	description = "A purple coral chair."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_chair_purple"
	tags = ["furniture", "tide_caverns_set", "dining_chair"]
	object = "coral_chair_purple"
	crafting_level_requirement = 6
	recipe = [
		{ count = 15, item = "coral" },
		{ count = 5, item = "sap" },
		{ count = 3, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_chair"

[coral_table_purple]
	name = "Coral Table"
	description = "A purple coral table."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_table_purple"
	tags = ["furniture", "tide_caverns_set", "coffee_table"]
	object = "coral_table_purple"
	crafting_level_requirement = 8
	recipe = [
		{ count = 20, item = "coral" },
		{ count = 5, item = "glass" },
		{ count = 3, item = "monster_horn" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_table"

[coral_storage_chest_purple]
	name = "Coral Storage Chest"
	description = "A purple coral chest with a large storage capacity."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_storage_chest_purple"
	tags = ["furniture", "tide_caverns_set", "chest_and_storage"]
	object = "coral_storage_chest_purple"
	crafting_level_requirement = 6
	recipe = [
		{ count = 20, item = "basic_wood" },
		{ count = 5, item = "coral" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	recipe_key = "coral_storage_chest"

[sand_rug]
	name = "Sand Rug"
	description = "A sandy rug that mimics the beach."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_sand_rug"
	tags = ["furniture", "tide_caverns_set", "medium_rug"]
	object = "sand_rug"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "fiber" },
		{ count = 2, item = "feather" },
		{ hours = 0, minutes = 20 },
	]

[low_tide_flooring]
	name = "Low Tide Flooring"
	description = "A rock floor that mimics the look of the Tide Caverns."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_tide_flooring"
	tags = ["furniture", "tide_caverns_set", "novelty_flooring"]
	flooring = "tide_caverns"
	crafting_level_requirement = 4
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 3, item = "spirula_shell" },
		{ count = 3, item = "pink_scallop_shell" },
		{ hours = 0, minutes = 30 },
	]
	crafting_preview_sprite = "spr_ui_furniture_flooring_tide_caverns_preview"

[tide_touched_cavern_wall]
	name = "Tide-Touched Cavern Wall"
	description = "A wallpaper that mimics the look of the Tide Caverns."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_tide_wallpaper"
	tags = ["furniture", "tide_caverns_set", "wallpaper"]
	wallpaper = "tide_caverns"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_level_requirement = 4
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 5, item = "ore_iron" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]
	crafting_preview_sprite = "spr_ui_furniture_wallpaper_tide_caverns_preview"

[ornamental_iron_node]
	name = "Ornamental Iron Node"
	description = "A decorative iron node."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_iron_node"
	tags = ["furniture", "tide_caverns_set", "misc_furniture"]
	object = "ornamental_iron_node"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 10, item = "ore_iron" },
		{ count = 3, item = "monster_powder" },
		{ hours = 0, minutes = 30 },
	]

[ornamental_sapphire_rock]
	name = "Ornamental Sapphire Rock"
	description = "A decorative sapphire rock."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_sapphire_rock"
	tags = ["furniture", "tide_caverns_set", "misc_furniture"]
	object = "ornamental_sapphire_rock"
	crafting_level_requirement = 2
	recipe = [
		{ count = 10, item = "ore_stone" },
		{ count = 3, item = "ore_sapphire" },
		{ count = 3, item = "glowing_mushroom" },
		{ hours = 0, minutes = 30 },
	]

[coral_stone_archway]
	name = "Coral-Stone Arch"
	description = "A stone archway with coral at its base."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_furniture_coral_arch"
	tags = ["furniture", "tide_caverns_set", "misc_outdoor_decor"]
	object = "coral_stone_archway"
	crafting_level_requirement = 14
	recipe = [
		{ count = 20, item = "ore_stone" },
		{ count = 10, item = "coral" },
		{ count = 3, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
