	# TRAINING DUMMIES

[training_dummy_sapling]
	icon_sprite = "spr_ui_item_decor_training_dummy_sapling"
	name = "Training Dummy"
	description = "A training dummy that looks like a Sapling."
	object = "training_dummy_sapling"
	tags = ["furniture", "training_dummy_set", "misc_decor"]
	recipe_key = "training_dummy"
	value = { bin = "self.recipe*1.1" }
	recipe = [ # TEMP RECIPE
		{ count = 30, item = "basic_wood" },
		{ count = 10, item = "fiber" },
		{ count = 5, item = "monster_fang" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 6

[training_dummy_mushroom]
	icon_sprite = "spr_ui_item_decor_training_dummy_mushroom"
	name = "Training Dummy"
	description = "A training dummy that looks like a Mushroom Monster."
	object = "training_dummy_mushroom"
	tags = ["furniture", "training_dummy_set", "misc_decor"]
	recipe_key = "training_dummy"
	value = { bin = "self.recipe*1.1" }
	recipe = [ # TEMP RECIPE
		{ count = 30, item = "basic_wood" },
		{ count = 10, item = "fiber" },
		{ count = 5, item = "monster_powder" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 6

[training_dummy_clod]
	icon_sprite = "spr_ui_item_decor_training_dummy_rockclod"
	name = "Training Dummy"
	description = "A training dummy that looks like a Rock Clod."
	object = "training_dummy_clod"
	tags = ["furniture", "training_dummy_set", "misc_decor"]
	recipe_key = "training_dummy"
	value = { bin = "self.recipe*1.1" }
	recipe = [ # TEMP RECIPE
		{ count = 30, item = "basic_wood" },
		{ count = 10, item = "fiber" },
		{ count = 5, item = "monster_shell" },
		{ hours = 0, minutes = 30 },
	]
	crafting_level_requirement = 6