[void_throne_one_v1]
	name = "Void Throne"
	description = "A purple throne formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_throne_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_throne_one_v1"
	recipe_key = "void_throne_1"
	crafting_level_requirement = 34
	recipe = [
		{ count = 20, item = "voidite" },
		{ count = 5, item = "void_powder" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_seating", "void_set"]

[void_throne_one_v2]
	name = "Void Throne"
	description = "A blue throne formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_throne_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_throne_one_v2"
	recipe_key = "void_throne_1"
	crafting_level_requirement = 34
	recipe = [
		{ count = 20, item = "voidite" },
		{ count = 5, item = "void_powder" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_seating", "void_set"]

[void_throne_two_v1]
	name = "Void Throne II"
	description = "A truly cursed object (purple version)."
	icon_sprite = "spr_ui_item_furniture_void_throne_2_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_throne_two_v1"
	recipe_key = "void_throne_2"
	crafting_level_requirement = 36
	recipe = [
		{ count = 20, item = "voidite" },
		{ count = 5, item = "void_pearl" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_furniture", "void_set"]

[void_throne_two_v2]
	name = "Void Throne II"
	description = "A truly cursed object (blue version)."
	icon_sprite = "spr_ui_item_furniture_void_throne_2_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_throne_two_v2"
	recipe_key = "void_throne_2"
	crafting_level_requirement = 36
	recipe = [
		{ count = 20, item = "voidite" },
		{ count = 5, item = "void_pearl" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "misc_furniture", "void_set"]

[void_lamp_v1]
	name = "Void Lamp"
	description = "A purple lamp formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_lamp_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_lamp_v1"
	recipe_key = "void_lamp"
	crafting_preview_sprite = "spr_ui_furniture_void_lamp_v1_preview"
	crafting_level_requirement = 32
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "monster_core" },
		{ count = 5, item = "void_stone" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "floor_lighting", "void_set"]

[void_lamp_v2]
	name = "Void Lamp"
	description = "A blue lamp formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_lamp_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_lamp_v2"
	recipe_key = "void_lamp"
	crafting_preview_sprite = "spr_ui_furniture_void_lamp_v2_preview"
	crafting_level_requirement = 32
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "monster_core" },
		{ count = 5, item = "void_stone" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "floor_lighting", "void_set"]

[void_fireplace_v1]
	name = "Void Fireplace"
	description = "A purple fireplace formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_fireplace_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_fireplace_v1"
	recipe_key = "void_fireplace"
	crafting_preview_sprite = "spr_ui_furniture_void_fireplace_v1_preview"
	crafting_level_requirement = 40
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 5, item = "monster_core" },
		{ count = 5, item = "void_stone" },
		{ count = 5, item = "void_herb" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "misc_furniture", "void_set"]

[void_fireplace_v2]
	name = "Void Fireplace"
	description = "A blue fireplace formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_fireplace_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_fireplace_v2"
	recipe_key = "void_fireplace"
	crafting_preview_sprite = "spr_ui_furniture_void_fireplace_v2_preview"
	crafting_level_requirement = 40
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 5, item = "monster_core" },
		{ count = 5, item = "void_stone" },
		{ count = 5, item = "void_herb" },
		{ hours = 0, minutes = 40 },
	]
	tags = ["furniture", "misc_furniture", "void_set"]

[void_storage_chest_v1]
	name = "Void Storage Chest"
	description = "An extra-large storage chest formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_chest_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_storage_chest_v1"
	recipe_key = "void_storage_chest"
	crafting_level_requirement = 38
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 5, item = "void_pearl" },
		{ count = 5, item = "void_powder" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "chest_and_storage", "void_set"]

[void_storage_chest_v2]
	name = "Void Storage Chest"
	description = "An extra-large storage chest formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_chest_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_storage_chest_v2"
	recipe_key = "void_storage_chest"
	crafting_level_requirement = 38
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 5, item = "void_pearl" },
		{ count = 5, item = "void_powder" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "chest_and_storage", "void_set"]

[void_wallpaper_v1]
	icon_sprite = "spr_ui_item_furniture_void_wallpaper_v1"
	name = "Void Wall"
	description = "A purple star wallpaper formed from the void."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "void_v1"
	recipe_key = "void_wallpaper"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_void_wall_v1_preview"
	crafting_level_requirement = 32
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "void_powder" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "void_set", "wallpaper"]

[void_wallpaper_v2]
	icon_sprite = "spr_ui_item_furniture_void_wallpaper_v2"
	name = "Void Wall"
	description = "A blue star wallpaper formed from the void."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "void_v2"
	recipe_key = "void_wallpaper"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_void_wall_v2_preview"
	crafting_level_requirement = 32
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "void_powder" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "void_set", "wallpaper"]

[void_flooring_v1]
	icon_sprite = "spr_ui_item_furniture_void_flooring_v1"
	name = "Void Floor"
	description = "Purple star flooring formed from the void."
	value = { bin = "self.recipe * 1.1" }
	flooring = "void_v1"
	recipe_key = "void_flooring"
	crafting_preview_sprite = "spr_ui_furniture_void_floor_v1_preview"
	crafting_level_requirement = 32
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "void_herb" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "void_set", "novelty_flooring"]

[void_flooring_v2]
	icon_sprite = "spr_ui_item_furniture_void_flooring_v2"
	name = "Void Floor"
	description = "Blue star flooring formed from the void."
	value = { bin = "self.recipe * 1.1" }
	flooring = "void_v2"
	recipe_key = "void_flooring"
	crafting_preview_sprite = "spr_ui_furniture_void_floor_v2_preview"
	crafting_level_requirement = 32
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "void_herb" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "void_set", "novelty_flooring"]

[void_window_v1]
	name = "Void Window"
	description = "A purple window formed from the void. Interact when placed to toggle its animation!"
	icon_sprite = "spr_ui_item_furniture_void_window_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_window_v1"
	recipe_key = "void_window"
	crafting_preview_sprite = "spr_ui_furniture_void_window_v1_preview"
	crafting_level_requirement = 44
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 5, item = "void_stone" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "window", "void_set"]

[void_window_v2]
	name = "Void Window"
	description = "A blue window formed from the void. Interact when placed to toggle its animation!"
	icon_sprite = "spr_ui_item_furniture_void_window_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_window_v2"
	recipe_key = "void_window"
	crafting_preview_sprite = "spr_ui_furniture_void_window_v2_preview"
	crafting_level_requirement = 44
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 5, item = "void_stone" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "window", "void_set"]

[void_flagstone_small_v1]
	name = "Small Void Flagstone"
	description = "A small purple flagstone formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_flagstone_small_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_flagstone_small_v1"
	recipe_key = "void_flagstone_small"
	crafting_level_requirement = 30
	recipe = [
		{ count = 5, item = "voidite" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "ground_decor", "void_set"]

[void_flagstone_small_v2]
	name = "Small Void Flagstone"
	description = "A small blue flagstone formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_flagstone_small_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_flagstone_small_v2"
	recipe_key = "void_flagstone_small"
	crafting_level_requirement = 30
	recipe = [
		{ count = 5, item = "voidite" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "ground_decor", "void_set"]

[void_flagstone_large_v1]
	name = "Large Void Flagstone"
	description = "A large purple flagstone formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_flagstone_large_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_flagstone_large_v1"
	recipe_key = "void_flagstone_large"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "voidite" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "ground_decor", "void_set"]

[void_flagstone_large_v2]
	name = "Large Void Flagstone"
	description = "A large blue flagstone formed from the void."
	icon_sprite = "spr_ui_item_furniture_void_flagstone_large_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_flagstone_large_v2"
	recipe_key = "void_flagstone_large"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "voidite" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["furniture", "ground_decor", "void_set"]

# Below not included in void_set crafting bundle

[void_bonsai_v1]
	name = "Void Bonsai"
	description = "A purple bonsai formed from the void."
	icon_sprite = "spr_ui_item_decor_bonsai_void_v1"
	value = { bin = "self.recipe*1.1" }
	object = "void_bonsai_v1"
	recipe_key = "void_bonsai"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "void_herb" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "potted_tree"]


[void_bonsai_v2]
	name = "Void Bonsai"
	description = "A blue bonsai formed from the void."
	icon_sprite = "spr_ui_item_decor_bonsai_void_v2"
	value = { bin = "self.recipe*1.1" }
	object = "void_bonsai_v2"
	recipe_key = "void_bonsai"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 5, item = "void_herb" },
		{ hours = 0, minutes = 20 },
	]
	tags = ["furniture", "potted_tree"]
