[water_sprite_statue_v1]
	name = "Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 2 tile radius."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_object_water_sprite_statue_v1"
	object = "water_sprite_statue_v1"
	tags = ["furniture", "automation"]
	recipe_key = "water_sprite"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ essence = 50 },
		{ count = 3, item = "ash_mushroom" },
		{ hours = 0, minutes = 30 },
	]


[water_sprite_statue_v2]
	name = "Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 2 tile radius."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_object_water_sprite_statue_v2"
	object = "water_sprite_statue_v2"
	tags = ["furniture", "automation"]
	recipe_key = "water_sprite"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ essence = 50 },
		{ count = 3, item = "purple_mushroom" },
		{ hours = 0, minutes = 30 },
	]

[water_sprite_statue_v3]
	name = "Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 2 tile radius."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_object_water_sprite_statue_v3"
	object = "water_sprite_statue_v3"
	tags = ["furniture", "automation"]
	recipe_key = "water_sprite"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ essence = 50 },
		{ count = 3, item = "temple_flower" },
		{ hours = 0, minutes = 30 },
	]

[water_sprite_statue_v4]
	name = "Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 2 tile radius."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_object_water_sprite_statue_v4"
	object = "water_sprite_statue_v4"
	tags = ["furniture", "automation"]
	recipe_key = "water_sprite"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ essence = 50 },
		{ count = 3, item = "sea_grapes" },
		{ hours = 0, minutes = 30 },
	]

[water_sprite_statue_v5]
	name = "Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 2 tile radius."
	value = { bin = "self.recipe * 1.1" }
	icon_sprite = "spr_ui_item_object_water_sprite_statue_v5"
	object = "water_sprite_statue_v5"
	tags = ["furniture", "automation"]
	recipe_key = "water_sprite"
	crafting_level_requirement = 20
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ essence = 50 },
		{ count = 3, item = "thorn_vine" },
		{ hours = 0, minutes = 30 },
	]

	# Large ones

[water_sprite_statue_large_v1]
	name = "Large Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 3 tile radius."
	icon_sprite = "spr_ui_item_object_water_sprite_statue_large_v1"
	value = { bin = "self.recipe*1.1" }
	object = "water_sprite_statue_large_v1"
	recipe_key = "water_sprite_large"
	crafting_level_requirement = 30
	recipe = [
		{ count = 15, item = "refined_stone" },
		{ essence = 75 },
		{ count = 3, item = "breath_of_fire" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "automation"]

[water_sprite_statue_large_v2]
	name = "Large Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 3 tile radius."
	icon_sprite = "spr_ui_item_object_water_sprite_statue_large_v2"
	value = { bin = "self.recipe*1.1" }
	object = "water_sprite_statue_large_v2"
	recipe_key = "water_sprite_large"
	crafting_level_requirement = 30
	recipe = [
		{ count = 15, item = "refined_stone" },
		{ essence = 75 },
		{ count = 3, item = "lava_chestnuts" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "automation"]

[water_sprite_statue_large_v3]
	name = "Large Water Sprite Statue"
	description = "Place and apply an Essence Stone to automatically water crops in a 3 tile radius."
	icon_sprite = "spr_ui_item_object_water_sprite_statue_large_v3"
	value = { bin = "self.recipe*1.1" }
	object = "water_sprite_statue_large_v3"
	recipe_key = "water_sprite_large"
	crafting_level_requirement = 30
	recipe = [
		{ count = 15, item = "refined_stone" },
		{ essence = 75 },
		{ count = 3, item = "flame_pepper" },
		{ hours = 0, minutes = 30 },
	]
	tags = ["furniture", "automation"]
