# <---------WITCH QUEEN SET ITEMS------------>

[witch_queen_flooring_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_flooring_v1"
	name = "Witch Queen Flooring"
	description = "Ancient black tile flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "witch_queen_v1"
	crafting_preview_sprite = "spr_ui_furniture_witch_queen_floor_v1_preview"
	tags = ["furniture", "tile_flooring", "witch_queen_set"]
	recipe_key = "witch_queen_flooring"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 2, item = "shard_mass" },
		{ count = 2, item = "void_powder" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_flooring_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_flooring_v2"
	name = "Witch Queen Flooring"
	description = "Ancient dark purple tile flooring."
	value = { bin = "self.recipe * 1.1" }
	flooring = "witch_queen_v2"
	crafting_preview_sprite = "spr_ui_furniture_witch_queen_floor_v2_preview"
	tags = ["furniture", "tile_flooring", "witch_queen_set"]
	recipe_key = "witch_queen_flooring"
	crafting_level_requirement = 34
	recipe = [
		{ count = 10, item = "voidite" },
		{ count = 2, item = "shard_mass" },
		{ count = 2, item = "void_powder" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_wallpaper_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_wallpaper_v1"
	name = "Witch Queen Wallpaper"
	description = "A wallpaper that mimics the purple curtains of the Witch Queen's court."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "witch_queen_v1"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_witch_queen_wall_v1_preview"
	tags = ["furniture", "wallpaper", "witch_queen_set"]
	recipe_key = "witch_queen_wallpaper"
	crafting_level_requirement = 36
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 2, item = "monster_block" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_wallpaper_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_wallpaper_v2"
	name = "Witch Queen Wallpaper"
	description = "A wallpaper that mimics the peach curtains of the Witch Queen's court."
	value = { bin = "self.recipe * 1.1" }
	wallpaper = "witch_queen_v2"
	door_mold = "spr_carpenter_house_f2_doorway2_spring"
	crafting_preview_sprite = "spr_ui_furniture_witch_queen_wall_v2_preview"
	tags = ["furniture", "wallpaper", "witch_queen_set"]
	recipe_key = "witch_queen_wallpaper"
	crafting_level_requirement = 36
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 2, item = "monster_block" },
		{ count = 5, item = "paper" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_bed_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_bed_v1"
	name = "Witch Queen Bed"
	description = "An opulent cool-toned bed fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_bed_v1"
	recipe_key = "witch_queen_bed"
	tags = ["furniture", "single_bed", "witch_queen_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 15, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ count = 4, item = "monster_whisker" },
		{ count = 4, item = "monster_block" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_bed_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_bed_v2"
	name = "Witch Queen Bed"
	description = "An opulent warm-toned bed fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_bed_v2"
	recipe_key = "witch_queen_bed"
	tags = ["furniture", "single_bed", "witch_queen_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 15, item = "hard_wood" },
		{ count = 10, item = "refined_stone" },
		{ count = 4, item = "monster_whisker" },
		{ count = 4, item = "monster_block" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_double_bed_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_double_bed_v1"
	name = "Witch Queen Double Bed"
	description = "An opulent cool-toned double bed fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_double_bed_v1"
	recipe_key = "witch_queen_double_bed"
	tags = ["furniture", "double_bed", "witch_queen_set"]
	crafting_level_requirement = 44
	recipe = [
		{ count = 30, item = "voidite" },
		{ count = 25, item = "hard_wood" },
		{ count = 15, item = "refined_stone" },
		{ count = 6, item = "monster_whisker" },
		{ count = 6, item = "monster_block" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_double_bed_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_double_bed_v2"
	name = "Witch Queen Double Bed"
	description = "An opulent warm-toned double bed fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_double_bed_v2"
	recipe_key = "witch_queen_double_bed"
	tags = ["furniture", "double_bed", "witch_queen_set"]
	crafting_level_requirement = 44
	recipe = [
		{ count = 30, item = "voidite" },
		{ count = 25, item = "hard_wood" },
		{ count = 15, item = "refined_stone" },
		{ count = 6, item = "monster_whisker" },
		{ count = 6, item = "monster_block" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_cauldron_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_cauldron_v1"
	name = "Witch Queen Cauldron"
	description = "A cool-toned cauldron filled with green liquid."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_cauldron_v1"
	recipe_key = "witch_queen_cauldron"
	tags = ["furniture", "misc_furniture", "witch_queen_set"]
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "iron_ingot" },
		{ count = 5, item = "shards" },
		{ count = 3, item = "monster_powder" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_cauldron_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_cauldron_v2"
	name = "Witch Queen Cauldron"
	description = "A warm-toned cauldron filled with purple liquid."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_cauldron_v2"
	recipe_key = "witch_queen_cauldron"
	tags = ["furniture", "misc_furniture", "witch_queen_set"]
	crafting_level_requirement = 42
	recipe = [
		{ count = 10, item = "iron_ingot" },
		{ count = 5, item = "shards" },
		{ count = 3, item = "monster_powder" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_chair_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_chair_v1"
	name = "Witch Queen Chair"
	description = "An opulent cool-toned chair fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_chair_v1"
	recipe_key = "witch_queen_chair"
	tags = ["furniture", "dining_chair", "witch_queen_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "voidite" },
		{ count = 2, item = "void_stone" },
		{ count = 5, item = "refined_stone" },
		{ count = 4, item = "ore_mistril" },
		{ hours = 0, minutes = 40 },
	]

[witch_queen_chair_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_chair_v2"
	name = "Witch Queen Chair"
	description = "An opulent warm-toned chair fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_chair_v2"
	recipe_key = "witch_queen_chair"
	tags = ["furniture", "dining_chair", "witch_queen_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 20, item = "voidite" },
		{ count = 2, item = "void_stone" },
		{ count = 5, item = "refined_stone" },
		{ count = 4, item = "ore_mistril" },
		{ hours = 0, minutes = 40 },
	]

[witch_queen_dressing_table_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_dressing_table_v1"
	name = "Witch Queen Dressing Table"
	description = "An opulent cool-toned dressing table fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_dressing_table_v1"
	recipe_key = "witch_queen_dressing_table"
	tags = ["furniture", "dressing_table", "witch_queen_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 40 },
	]

[witch_queen_dressing_table_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_dressing_table_v2"
	name = "Witch Queen Dressing Table"
	description = "An opulent warm-toned dressing table fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_dressing_table_v2"
	recipe_key = "witch_queen_dressing_table"
	tags = ["furniture", "dressing_table", "witch_queen_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 25, item = "voidite" },
		{ count = 10, item = "refined_stone" },
		{ count = 5, item = "ore_mistril" },
		{ count = 5, item = "glass" },
		{ hours = 0, minutes = 40 },
	]

[witch_queen_moon_lamp_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_moon_lamp_v1"
	name = "Witch Queen Moon Lamp"
	description = "A cool-toned lamp in the shape of the full moon."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_moon_lamp_v1"
	recipe_key = "witch_queen_moon_lamp"
	tags = ["furniture", "floor_lighting", "witch_queen_set"]
	crafting_preview_sprite = "spr_ui_furniture_witch_queen_moon_lamp_v1_preview"
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "dragon_forged_core" },
		{ count = 1, item = "void_pearl" },
		{ count = 1, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_moon_lamp_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_moon_lamp_v2"
	name = "Witch Queen Moon Lamp"
	description = "A warm-toned lamp in the shape of the full moon."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_moon_lamp_v2"
	recipe_key = "witch_queen_moon_lamp"
	tags = ["furniture", "floor_lighting", "witch_queen_set"]
	crafting_preview_sprite = "spr_ui_furniture_witch_queen_moon_lamp_v2_preview"
	crafting_level_requirement = 38
	recipe = [
		{ count = 1, item = "dragon_forged_core" },
		{ count = 1, item = "void_pearl" },
		{ count = 1, item = "shard_mass" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_nightstand_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_nightstand_v1"
	name = "Witch Queen Nightstand"
	description = "An opulent cool-toned nightstand fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_nightstand_v1"
	recipe_key = "witch_queen_nightstand"
	tags = ["furniture", "nightstand", "witch_queen_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 5, item = "shards" },
		{ count = 1, item = "void_herb" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_nightstand_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_nightstand_v2"
	name = "Witch Queen Nightstand"
	description = "An opulent warm-toned nightstand fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_nightstand_v2"
	recipe_key = "witch_queen_nightstand"
	tags = ["furniture", "nightstand", "witch_queen_set"]
	crafting_level_requirement = 40
	recipe = [
		{ count = 5, item = "refined_stone" },
		{ count = 5, item = "shards" },
		{ count = 1, item = "void_herb" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_pillar_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_pillar_v1"
	name = "Witch Queen Pillar"
	description = "A dark pillar trimmed in gold."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_pillar_v1"
	recipe_key = "witch_queen_pillar"
	tags = ["furniture", "misc_furniture", "witch_queen_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 5, item = "shard_mass" },
		{ count = 1, item = "dragon_forged_fang" },
		{ count = 1, item = "gold_ingot" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_pillar_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_pillar_v2"
	name = "Witch Queen Pillar"
	description = "A light pillar trimmed in gold."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_pillar_v2"
	recipe_key = "witch_queen_pillar"
	tags = ["furniture", "misc_furniture", "witch_queen_set"]
	crafting_level_requirement = 46
	recipe = [
		{ count = 5, item = "shard_mass" },
		{ count = 1, item = "dragon_forged_powder" },
		{ count = 1, item = "gold_ingot" },
		{ hours = 0, minutes = 30 },
	]

[witch_queen_rug_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_rug_v1"
	name = "Witch Queen Rug"
	description = "An elaborate purple and gold rug that features the phases of the moon."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_rug_v1"
	recipe_key = "witch_queen_rug"
	tags = ["furniture", "large_rug", "witch_queen_set"]
	crafting_level_requirement = 50
	recipe = [
		{ count = 5, item = "alpaca_wool" },
		{ count = 5, item = "plum_blossom" },
		{ count = 3, item = "golden_feather" },
		{ count = 3, item = "monster_whisker" },
		{ count = 1, item = "dragon_forged_core" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_rug_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_rug_v2"
	name = "Witch Queen Rug"
	description = "An elaborate peach and gold rug that features the phases of the moon."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_rug_v2"
	recipe_key = "witch_queen_rug"
	tags = ["furniture", "large_rug", "witch_queen_set"]
	crafting_level_requirement = 50
	recipe = [
		{ count = 5, item = "alpaca_wool" },
		{ count = 5, item = "plum_blossom" },
		{ count = 3, item = "golden_feather" },
		{ count = 3, item = "monster_whisker" },
		{ count = 1, item = "dragon_forged_core" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_table_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_table_v1"
	name = "Witch Queen Table"
	description = "An opulent cool-toned table fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_table_v1"
	recipe_key = "witch_queen_table"
	tags = ["furniture", "dining_table", "witch_queen_set"]
	crafting_level_requirement = 48
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 6, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ count = 2, item = "monster_block" },
		{ hours = 0, minutes = 40 },
	]

[witch_queen_table_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_table_v2"
	name = "Witch Queen Table"
	description = "An opulent warm-toned table fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_table_v2"
	recipe_key = "witch_queen_table"
	tags = ["furniture", "dining_table", "witch_queen_set"]
	crafting_level_requirement = 48
	recipe = [
		{ count = 10, item = "refined_stone" },
		{ count = 6, item = "shards" },
		{ count = 2, item = "shard_mass" },
		{ count = 2, item = "monster_block" },
		{ hours = 0, minutes = 40 },
	]

[witch_queen_throne_v1]
	icon_sprite = "spr_ui_item_furniture_witch_queen_throne_v1"
	name = "Witch Queen Throne"
	description = "A regal cool-toned throne fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_throne_v1"
	recipe_key = "witch_queen_throne"
	tags = ["furniture", "misc_seating", "witch_queen_set"]
	crafting_level_requirement = 50
	recipe = [
		{ count = 5, item = "mistril_ingot" },
		{ count = 5, item = "shard_mass" },
		{ count = 2, item = "alpaca_wool" },
		{ count = 2, item = "monster_block" },
		{ count = 2, item = "dragon_forged_horn" },
		{ hours = 0, minutes = 50 },
	]

[witch_queen_throne_v2]
	icon_sprite = "spr_ui_item_furniture_witch_queen_throne_v2"
	name = "Witch Queen Throne"
	description = "A regal warm-toned throne fit for a Witch Queen."
	value = { bin = "self.recipe * 1.1" }
	object = "witch_queen_throne_v2"
	recipe_key = "witch_queen_throne"
	tags = ["furniture", "misc_seating", "witch_queen_set"]
	crafting_level_requirement = 50
	recipe = [
		{ count = 5, item = "mistril_ingot" },
		{ count = 5, item = "shard_mass" },
		{ count = 2, item = "alpaca_wool" },
		{ count = 2, item = "monster_block" },
		{ count = 2, item = "dragon_forged_horn" },
		{ hours = 0, minutes = 50 },
	]
