[engagement_ring_hayden]
kind = "gameplay_triggered"
actions = [
    { bark = { bark = "cute_face", npc = "hayden" } },
    { cutscene = "hayden_ten_hearts" }
]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "Hey, [Ari]! What's on your mind?"
next = "1"

[engagement_ring_hayden.1]
speaker = "hayden"
portrait = "think"
local = "You want to go somewhere to talk?"
next = "2"

[engagement_ring_hayden.2]
speaker = "hayden"
portrait = "shy_special"
local = "Hmm..."
next = "3"

[engagement_ring_hayden.3]
speaker = "hayden"
portrait = "confident_blush"
local = "Why don't we take a little walk up to the $Summit$? We should have it all to ourselves."

# ten heart scene
[hayden_ten_hearts]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "happy_arm_down"
local = "Ahhh... It's beautiful up here, ain't it?"
next = "1"

[hayden_ten_hearts.1]
speaker = "hayden"
portrait = "confident_blush"
local = "Just look at that view!"
next = "2"

[hayden_ten_hearts.2]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "There's no one else I'd rather share this with."
next = "3"

[hayden_ten_hearts.3]
speaker = "hayden"
portrait = "shy_special"
local = "Actually, you know [Ari]..."
next = "4"

[hayden_ten_hearts.4]
speaker = "hayden"
portrait = "confident_blush"
local = "Pretty much anything worth doing is better when I get to do it with you."
next = "5"

[hayden_ten_hearts.5]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "Enjoying a meal, a trip to the Beach, a walk in the woods-"
next = "6"

[hayden_ten_hearts.6]
speaker = "hayden"
portrait = "shy_special"
local = "Or even trying something new entirely..."
next = "7"

[hayden_ten_hearts.7]
speaker = "hayden"
portrait = "confident_blush"
local = "I never feel alone when I'm with you."
prompts = [
    { local = "How could you feel alone if I'm with you, silly?", next = "8" },
    { local = "You're not alone, Hayden. I'm always here for you.", next = "9" }
]

[hayden_ten_hearts.8]
speaker = "hayden"
portrait = "embarrassed"
local = "I guess it sounds kind of funny, don't it? Maybe I'm not explaining it well..."
next = "11"

[hayden_ten_hearts.9]
speaker = "hayden"
portrait = "shy_special"
local = "..."
next = "10"

[hayden_ten_hearts.10]
speaker = "hayden"
portrait = "embarrassed"
local = "I guess I sound kind of silly, don't I? It's a feeling that's kind of hard to explain..."
next = "11"

[hayden_ten_hearts.11]
speaker = "hayden"
portrait = "sweat"
local = "Do you ever get a bit sad in the middle of a dinner with friends? Or maybe right afterwards?"
next = "12"

[hayden_ten_hearts.12]
speaker = "hayden"
portrait = "gloomy"
local = "A lonely little ache... that somehow gets louder when you're with other people?"
next = "13"

[hayden_ten_hearts.13]
speaker = "hayden"
portrait = "embarrassed"
local = "It's not all the time, mind you!"
next = "14"

[hayden_ten_hearts.14]
speaker = "hayden"
portrait = "shy_special"
local = "But there was less of it back when Gran was around..."
next = "15"

[hayden_ten_hearts.15]
speaker = "hayden"
portrait = "confident_blush"
local = "And there's been less of it since you became part of my life."
next = "16"

[hayden_ten_hearts.16]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "Maybe it's a desire for a deeper connection. To really know someone, and to be known in return."
next = "17"

[hayden_ten_hearts.17]
speaker = "hayden"
portrait = "shy_special"
local = "Even when we were just friends, [Ari]... you managed to bridge the distance in a way no one else could."
next = "18"

[hayden_ten_hearts.18]
speaker = "hayden"
portrait = "think"
local = """People talk about the idea of "found family"."""
next = "19"

[hayden_ten_hearts.19]
speaker = "hayden"
portrait = "sweat"
local = "I'm not sure I understood what they meant, until-"
next = "20"

[hayden_ten_hearts.20]
speaker = "hayden"
portrait = "embarrassed"
local = "Well, until you became part of mine."
prompts = [
    { local = "I know what you mean, Hayden. I feel the same way.", next = "21" },
    { local = "No one knows me the way you do, Hayden...", next = "21" }
]

[hayden_ten_hearts.21]
speaker = "hayden"
portrait = "shy_special"
local = "[Ari]..."
next = "22"

[hayden_ten_hearts.22]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "I think the best part is that... I'll never have to stop getting to know you."
next = "23"

[hayden_ten_hearts.23]
speaker = "hayden"
portrait = "shy_special"
local = "I want to hear every funny story from when you were growing up..."
next = "24"

[hayden_ten_hearts.24]
speaker = "hayden"
portrait = "blush"
local = "I want to know what flavor tea I should make for you, if you ever catch a cold."
next = "25"

[hayden_ten_hearts.25]
speaker = "hayden"
portrait = "embarrassed"
local = "I want to find out what kind of things will make you laugh three years from now, ten years from now..."
next = "26"

[hayden_ten_hearts.26]
speaker = "hayden"
portrait = "confident_blush"
local = "Who will that version of [Ari] be? And what will I like best about <he>him</he><she>her</she><they>them</they><it>it</it><none>[Ari]</none>?"
next = "27"

[hayden_ten_hearts.27]
speaker = "hayden"
portrait = "blush"
local = "I..."
next = "28"

[hayden_ten_hearts.28]
speaker = "hayden"
portrait = "embarrassed"
local = "Sorry, I'm getting a little ahead of myself."
next = "29"

[hayden_ten_hearts.29]
speaker = "hayden"
portrait = "blush"
local = "I just want you to understand how much you mean to me."
next = [
    { target = "30_second", requires = [
        { cutscene_seen_hayden_ten_hearts = true }
    ] },
    { target = "30_first", requires = [] }
]

[hayden_ten_hearts.30_second]
speaker = "hayden"
portrait = "shy_special"
local = "That's why I made that $Carved Nest$ for you."
next = "31_second"

[hayden_ten_hearts.31_second]
speaker = "hayden"
portrait = "embarrassed"
local = "I wanted you to have it, so you'll never forget..."
next = "32"

[hayden_ten_hearts.30_first]
speaker = "hayden"
portrait = "shy_special"
local = "Actually, on that note... I made a little something for you. Holt gave me some tips on whittling so I could get it just right."
next = "31_first"

[hayden_ten_hearts.31_first]
speaker = "hayden"
portrait = "embarrassed"
local = "It's a $Carved Nest$. I wanted you to have it, so you'll never forget..."
next = "32"

[hayden_ten_hearts.32]
speaker = "hayden"
portrait = "blush"
local = "No matter what the future holds..."
next = "33"

[hayden_ten_hearts.33]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "You're family to me, [Ari]."
next = "34"

[hayden_ten_hearts.34]
speaker = "hayden"
portrait = "confident_blush"
local = "You always will be."
next = "35"

[hayden_ten_hearts.35]
speaker = "hayden"
portrait = "gloomy"
local = "And ah... there's something I want to ask you, [Ari]. Something important. But-"
next = "36"

[hayden_ten_hearts.36]
speaker = "hayden"
portrait = "embarrassed"
local = "But that's not why we came here today, is it."
next = "37"

[hayden_ten_hearts.37]
speaker = "hayden"
portrait = "blush"
local = "There was something else you wanted to talk about, right? Lay it on me!"
prompts = [
    { local = "I wanted to talk to you about our future together...", next = "38" },
    { local = "Let's talk about it another time...", next = "49" }
]

# first yes
[hayden_ten_hearts.38]
speaker = "hayden"
portrait = "shocked"
effect = "shock"
local = "Our-"
next = "39"

[hayden_ten_hearts.39]
speaker = "hayden"
portrait = "shy_special"
local = "Wait, you don't mean...?"
prompts = [
    { local = "I love you, Hayden. Are you going to ask me to marry you, or what?", next = "40" },
    { local = "Actually, let's talk about it more another day.", next = "50" }
]

[hayden_ten_hearts.40]
writes = [
    { breakup_bump = true, expires = "3d" },
    { engagement_bump = true, expires = "2d" },
    { engagement_delay = true, expires = "20h" },
    { engagement_cap = false, expires = "3d" },
]
actions = [{ can_talk = "hayden" }]
speaker = "hayden"
portrait = "laugh_blush"
local = "GYA HA HA HA!"
next = "41"

[hayden_ten_hearts.41]
speaker = "hayden"
portrait = "confident_blush"
local = "You already knew... Of course you did!"
next = "42"

[hayden_ten_hearts.42]
speaker = "hayden"
portrait = "blush"
local = "There's nothing I want more in this world, [Ari]."
next = "43"

[hayden_ten_hearts.43]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "You will marry me, won't you?"
next = "44"

[hayden_ten_hearts.44]
speaker = "hayden"
portrait = "blush"
local = "Yes? Oh [Ari]..."
next = "45"

[hayden_ten_hearts.45]
speaker = "hayden"
portrait = "embarrassed"
local = "You've made me the happiest man in all of Aldaria."
next = "46"

[hayden_ten_hearts.46]
speaker = "hayden"
portrait = "happy_arm_down_blush"
local = "I love you so much..."
next = "47"

[hayden_ten_hearts.47]
speaker = "hayden"
portrait = "confident_blush"
local = "Now c'mere and let me hold you... my fiancé!"
next = "48"

[hayden_ten_hearts.48]
speaker = "hayden"
portrait = "laugh_blush"
local = "GYA HA HA HA!"

# first no
[hayden_ten_hearts.49]
speaker = "hayden"
portrait = "embarrassed"
local = "Oh! Sure, that's no problem."
next = "51"

# second no
[hayden_ten_hearts.50]
speaker = "hayden"
portrait = "embarrassed"
local = "Oh! O-of course."
next = "51"

[hayden_ten_hearts.51]
speaker = "hayden"
portrait = "blush"
local = "You just let me know, okay? I can always make the time to come up here for a chat."
