# <---------MINES ITEMS: DEEP EARTH------------->

# <---------DEEP EARTH ARTIFACTS------------->

[really_round_rock]
	name = "Really Round Rock"
	description = "A common artifact. This naturally formed stone is unnaturally round."
	icon_sprite = "spr_ui_item_really_round_rock"
	value = { bin = 40, renown = 5 }
	tags = ["archaeology"]

[seriously_square_stone]
	name = "Seriously Square Stone"
	description = "A common artifact. This naturally formed stone is a perfect square, a true delight for a rock connoisseur."
	icon_sprite = "spr_ui_item_seriously_square_rock"
	value = { bin = 40, renown = 5 }
	tags = ["archaeology"]

[earth_infused_stone]
	name = "Earth-Infused Stone"
	description = "An uncommon artifact. This chunk of rock has taken on elemental qualities of earth."
	icon_sprite = "spr_ui_item_earth_infused_stone"
	value = { bin = 50, renown = 5 }
	tags = ["archaeology"]

[faceted_rock_gem]
	name = "Faceted Rock Gem"
	description = "An uncommon artifact. Despite its mesmerizing, gem-like appearance, it's just a piece of rock."
	icon_sprite = "spr_ui_item_faceted_rock_gem"
	value = { bin = 75, renown = 10 }
	tags = ["archaeology"]

[rock_statue]
	name = "Rock Statue"
	description = "A rare artifact. This naturally formed stone appears to be in the shape of a human, but... surely it's just a coincidence."
	icon_sprite = "spr_ui_item_rock_statue"
	value = { bin = 125, renown = 20 }
	tags = ["archaeology"]

	# <---------DEEP EARTH FORAGE------------->

[crystal]
	name = "Crystal"
	description = "A shard of crystal. Used in crafting recipes."
	icon_sprite = "spr_ui_item_crystal"
	value = { bin = 15 }
	recipe_is_default = true
	recipe = [
		{ count = 8, item = "ore_stone" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["refined_material", "material"]

[crystal_berries]
	name = "Crystal Berries"
	description = "These berries have a glasslike appearance and are very sweet."
	value = { bin = 30 }
	icon_sprite = "spr_ui_item_crystal_berries"
	restore = 6
	tags = ["forageable", "mines_forageable"]

[shale_grass]
	name = "Shale Grass"
	description = "This grass only looks like it's made of rock. Very tough to cut."
	value = { bin = 35 }
	icon_sprite = "spr_ui_item_shale_grass"
	restore = 6
	tags = ["forageable", "mines_forageable"]

[earthshroom]
	name = "Earthshroom"
	description = "These mushrooms grow in dense clusters, and smell strongly of earth."
	value = { bin = 30 }
	restore = 6
	icon_sprite = "spr_ui_item_earthshroom"
	tags = ["forageable", "mines_forageable", "mushroom"]

[rockroot]
	name = "Rockroot"
	description = "It's hard to tell if this is part of a living plant or if it just resembles one."
	value = { bin = 35 }
	icon_sprite = "spr_ui_item_rockroot"
	restore = 6
	tags = ["forageable", "mines_forageable"]

[crystal_rose]
	name = "Crystal Rose"
	description = "This delicate, shimmering rose appears to be made of crystal."
	value = { bin = 35 }
	icon_sprite = "spr_ui_item_crystal_rose"
	tags = ["forageable", "mines_forageable", "flower"]

	# <---------DEEP EARTH FISH------------->

[pebble_minnow]
	name = "Pebble Minnow"
	description = "A common small Deep Earth fish. The scales of these fish have taken on a pebbled texture to help it blend into its surroundings."
	icon_sprite = "spr_ui_item_fish_small_pebble_minnow"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[shardfin]
	name = "Shardfin"
	description = "An uncommon small Deep Earth fish. This fish's sleek fin has an iridescent shimmer."
	icon_sprite = "spr_ui_item_fish_small_shardfin"
	value = { bin = 55 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[earth_eel]
	name = "Earth Eel"
	description = "A common medium Deep Earth fish. Doesn't seem to have a mouth, so who knows what it eats."
	icon_sprite = "spr_ui_item_fish_medium_earth_eel"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[rockbiter]
	name = "Rockbiter"
	description = "An uncommon medium Deep Earth fish. This fish has an over-developed jaw to help it grind down stone."
	icon_sprite = "spr_ui_item_fish_medium_rockbiter"
	value = { bin = 55 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[emerald_horned_charger]
	name = "Emerald-Horned Charger"
	description = "A rare large Deep Earth fish. This large fish is nearly all horn, which seems to be made of pure emerald."
	icon_sprite = "spr_ui_item_fish_large_emerald_horned_charger"
	value = { bin = 120 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[rock_roach]
	description = "An uncommon Deep Earth insect. It's cuter than you'd expect."
	icon_sprite = "spr_ui_item_insect_rock_roach"
	name = "Rock Roach"
	value = { bin = 25 }
	tags = ["bugs"]

	# <---------DEEP EARTH BUGS------------>

[deep_earthworm]
	description = "An uncommon Deep Earth insect. It's completely unlike its surface-dwelling cousin... if you're a worm expert."
	icon_sprite = "spr_ui_item_insect_deep_earthworm"
	name = "Deep Earthworm"
	value = { bin = 25 }
	tags = ["bugs"]

[crystalline_cricket]
	description = "A common Deep Earth insect. The stones around it vibrate in tune with its song."
	icon_sprite = "spr_ui_item_insect_crystalline_cricket"
	name = "Crystalline Cricket"
	value = { bin = 25 }
	tags = ["bugs"]

[gem_shard_caterpillar]
	description = "An uncommon Deep Earth insect. It seems to feed on crystal berries."
	icon_sprite = "spr_ui_item_insect_gem_shard_caterpillar"
	name = "Gem Shard Caterpillar"
	value = { bin = 40 }
	tags = ["bugs"]

[crystal_wing_moth]
	description = "A rare Deep Earth insect. Their delicate wings reflect the light and make them sparkle."
	icon_sprite = "spr_ui_item_insect_crystal_wing_moth"
	name = "Crystal Wing Moth"
	value = { bin = 50 }
	tags = ["bugs"]
