# <---------MINES ITEMS: RUINS------------->

# <---------RUINS ARTIFACTS------------->

[dragon_claw]
	name = "Dragon Claw"
	description = "An uncommon Ruins artifact. Extremely sharp, despite its age. It would make a fine blade, if it wasn't so heavy."
	icon_sprite = "spr_ui_item_dragon_claw"
	value = { bin = 50, renown = 20 }
	tags = ["archaeology", "dragon_part"]

[dragon_forged_bracelet]
	name = "Dragon-Forged Bracelet"
	description = "A rare Ruins artifact. An ancient bracelet forged by dragon fire. Strangely, it looks like it would fit a human-sized wrist."
	icon_sprite = "spr_ui_item_dragon_forged_bracelet"
	value = { bin = 75, renown = 30 }
	tags = ["archaeology"]

[dragon_pact_tablet]
	name = "Dragon Pact Tablet"
	description = "A legendary Ruins artifact. Written in untranslatable Draconian."
	icon_sprite = "spr_ui_item_dragon_pact_tablet"
	value = { bin = 125, renown = 50 }
	tags = ["archaeology"]

[dragon_scale]
	name = "Dragon Scale"
	description = "An uncommon Ruins artifact. The passing of thousands of years has hardened this scale into something stronger than steel."
	icon_sprite = "spr_ui_item_dragon_scale"
	value = { bin = 50, renown = 20 }
	tags = ["archaeology", "dragon_part"]

[hardened_essence]
	name = "Hardened Essence"
	description = "A rare Ruins artifact. Magic essence hardened into a gem-like form. There must have been an enormous amount of magic in the world when this was formed."
	icon_sprite = "spr_ui_item_hardened_essence"
	value = { bin = 75, renown = 30 }
	tags = ["archaeology"]


	# <---------RUINS FISH------------>

[winged_shrimp]
	name = "Winged Shrimp"
	description = "A common small Ruins crustacean. These shrimp appear to have adapted to the extreme conditions found in the Ruins."
	icon_sprite = "spr_ui_item_fish_small_winged_shrimp"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[gazer]
	name = "Gazer"
	description = "An uncommon medium Ruins fish. This strange fish does not need eyes in order to see."
	icon_sprite = "spr_ui_item_fish_small_gazer"
	value = { bin = 110 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[luminescent_crab]
	name = "Luminescent Crab"
	description = "A common medium Ruins crustacean. This crab's unusual glow is likely due to the Mistril particles in the Ruins sediment."
	icon_sprite = "spr_ui_item_fish_medium_luminescent_crab"
	value = { bin = 90 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[giant_jellyfish]
	name = "Giant Jellyfish"
	description = "A common large Ruins invertebrate. This majestic jelly is beautiful to look at!"
	icon_sprite = "spr_ui_item_fish_large_giant_jellyfish"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[coelacanth]
	name = "Coelacanth"
	description = "A rare large Ruins fish. Seems to have been down here a very long time..."
	icon_sprite = "spr_ui_item_fish_large_coelacanth"
	value = { bin = 140 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

	# <---------RUINS BUGS------------>

[ancient_firefly]
	description = "A common Ruins insect. This ancient firefly is almost fairy-like in its appearance."
	icon_sprite = "spr_ui_item_insect_ancient_firefly"
	name = "Ancient Firefly"
	value = { bin = 40 }
	tags = ["bugs"]

[void_snail]
	description = "A common Ruins insect. This unusual snail prefers to live in total darkness."
	icon_sprite = "spr_ui_item_insect_void_snail"
	name = "Void Snail"
	value = { bin = 40 }
	tags = ["bugs"]

[giant_worm]
	description = "An uncommon Ruins insect. This prehistoric worm was previously thought to be extinct."
	icon_sprite = "spr_ui_item_insect_giant_worm"
	name = "Giant Worm"
	value = { bin = 50 }
	tags = ["bugs"]

[parchment_moth]
	description = "An uncommon Ruins insect. This moth is known to feed mainly on old parchment."
	icon_sprite = "spr_ui_item_insect_parchment_moth"
	name = "Parchment Moth"
	value = { bin = 80 }
	tags = ["bugs"]

[hidden_beetle]
	description = "A rare Ruins insect. This camouflaging beetle is hard to notice among the rubble."
	icon_sprite = "spr_ui_item_insect_hidden_beetle"
	name = "Hidden Beetle"
	value = { bin = 90 }
	tags = ["bugs"]


	# --RUINS FORAGE-- (Moved spell_fruit and essence_blossom back here for updates + re-review)

[spell_fruit]
	name = "Spell Fruit"
	description = "A fruit with a mouthwatering aroma that's simply magical."
	value = { bin = 45 }
	icon_sprite = "spr_ui_item_spell_fruit"
	restore = 8
	tags = ["forageable", "mines_forageable"]


[written_root]
	name = "Written Root"
	description = "A root that seems to form itself into letters. How strange."
	value = { bin = 50 }
	restore = 6
	icon_sprite = "spr_ui_item_written_root"
	tags = ["forageable", "mines_forageable"]

[essence_blossom]
	name = "Essence Blossom"
	description = "A flower infused with magic. Beautiful and surprisingly resilient."
	value = { bin = 55 }
	restore = 10
	icon_sprite = "spr_ui_item_essence_blossom"
	tags = ["forageable", "mines_forageable"]


[ethereal_grass]
	name = "Ethereal Grass"
	description = "Grass with an otherworldly origin. Used in certain crafting recipes."
	value = { bin = 60 }
	restore = 10
	icon_sprite = "spr_ui_item_ethereal_grass"
	tags = ["forageable", "mines_forageable"]

[chirping_fern]
	name = "Chirping Fern"
	description = "A fern that occasionally emits a pleasant chirp through unknown means and for unknown reasons."
	value = { bin = 60 }
	edible = false
	icon_sprite = "spr_ui_item_chirping_fern"
	tags = ["forageable", "mines_forageable"]


	# <---------RUINS MATERIALS------------->

[voidite]
	name = "Voidite"
	description = "A shard of voidite."
	value = { bin = 20 }
	icon_sprite = "spr_ui_item_voidite"
	recipe_is_default = true
	recipe = [
		{ count = 8, item = "ore_stone" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["refined_material", "material"]
