# <---------MINES ITEMS: TIDE CAVERNS------------->

# <---------TIDE CAVERN ARTIFACTS------------->

[stone_shell]
	name = "Stone Shell"
	description = "A common artifact. When you hold it to your ear, you can hear the sound of water flowing through deep caves."
	icon_sprite = "spr_ui_item_stone_shell"
	value = { bin = 40, renown = 5 }
	tags = ["archaeology"]


[starlight_coral]
	name = "Starlight Coral"
	description = "A common artifact. This piece of coral glimmers as if reflecting starlight."
	icon_sprite = "spr_ui_item_starlight_coral"
	value = { bin = 40, renown = 5 }
	tags = ["archaeology"]

[tidestone]
	name = "Tidestone"
	description = "An uncommon artifact. This chunk of stone appears to grow and shrink slightly along with the tides."
	icon_sprite = "spr_ui_item_tidestone"
	value = { bin = 50, renown = 5 }
	tags = ["archaeology"]

[dense_water]
	name = "Dense Water"
	description = "An uncommon artifact. This water is so dense that it holds its shape even in air."
	value = { bin = 50, renown = 5 }
	icon_sprite = "spr_ui_item_dense_water"
	tags = ["archaeology"]

[crab_statue]
	name = "Crab Statue"
	description = "A rare artifact. This delicately crafted statue almost seems alive."
	icon_sprite = "spr_ui_item_crab_statue"
	value = { bin = 75, renown = 10 }
	tags = ["archaeology"]

	# <---------TIDE CAVERN FORAGE------------->

[coral]
	description = "A pretty piece of coral. Found in the Tide Caverns & used for crafting."
	icon_sprite = "spr_ui_item_coral"
	name = "Coral"
	value = { bin = 15 }
	recipe_is_default = true
	recipe = [
		{ count = 8, item = "ore_stone" },
		{ hours = 0, minutes = 10 },
	]
	tags = ["refined_material", "material"]

[underseaweed]
	name = "Underseaweed"
	icon_sprite = "spr_ui_item_underseaweed"
	description = "This seaweed has a mild flavor and bouncy texture. Used in a variety of cooking recipes."
	tags = ["forageable", "mines_forageable"]
	restore = 5
	value = { bin = 30 }

[sea_grapes]
	name = "Sea Grapes"
	icon_sprite = "spr_ui_item_sea_grapes"
	description = "These grapes have a salty pop that adds a briny taste to any dish. Used in a variety of cooking recipes."
	tags = ["forageable", "mines_forageable"]
	restore = 5
	value = { bin = 35 }

[cave_kelp]
	name = "Jade Dulse"
	description = "This seaweed makes a great thickener for soups. Used in a variety of cooking recipes."
	icon_sprite = "spr_ui_item_cave_kelp"
	tags = ["forageable", "mines_forageable"]
	restore = 5
	value = { bin = 30 }

[mines_mussels]
	name = "Mines Mussels"
	description = "These mussels grow in bunches underground. Used in a variety of cooking recipes."
	icon_sprite = "spr_ui_item_mines_mussels"
	tags = ["forageable", "mines_forageable"]
	restore = 5
	value = { bin = 35 }

[tide_lettuce]
	name = "Tide Lettuce"
	icon_sprite = "spr_ui_item_tide_lettuce"
	description = "This wild lettuce has a rich flavor and a satisfying crunch. Used in a variety of cooking recipes."
	tags = ["forageable", "mines_forageable"]
	restore = 5
	value = { bin = 30 }

	# <---------TIDE CAVERN FISH------------->

[sapphire_betta]
	name = "Sapphire Betta"
	description = "A common small Tide Caverns fish. It has a lovely color."
	icon_sprite = "spr_ui_item_fish_small_sapphire_betta"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[archerfish]
	name = "Archerfish"
	description = "An uncommon small Tide Caverns fish. It squirts a stream of water to catch bugs."
	icon_sprite = "spr_ui_item_fish_small_archerfish"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[transparent_jellyfish]
	name = "Transparent Jellyfish"
	description = "A common medium Tide Caverns invertebrate. It evolved in darkness, resulting in an unusual transparent appearance."
	icon_sprite = "spr_ui_item_fish_medium_transparent_jellyfish"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[water_balloon_fish]
	name = "Water Balloon Fish"
	description = "An uncommon medium Tide Caverns fish. It takes in an impressive amount of water to discourage predators."
	icon_sprite = "spr_ui_item_fish_medium_water_balloon_fish"
	value = { bin = 50 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[mini_whale_shark]
	name = "Mini-Whale Shark"
	description = "A rare large Tide Caverns fish. Despite its name, it is still very large."
	icon_sprite = "spr_ui_item_fish_large_mini_whale_shark"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------TIDE CAVERN BUGS------------>

[sea_scarab]
	description = "An uncommon Tide Caverns insect. Its pretty carapace looks like the sea on a sunny day."
	icon_sprite = "spr_ui_item_insect_sea_scarab"
	name = "Sea Scarab"
	value = { bin = 20 }
	tags = ["bugs"]

[waterfly]
	description = "A common Tide Caverns insect. Like its firefly cousin, it uses its blue glow to signal."
	icon_sprite = "spr_ui_item_insect_waterfly"
	name = "Waterfly"
	value = { bin = 20 }
	tags = ["bugs"]

[hermit_snail]
	description = "An uncommon Tide Caverns insect. Decorates its shell with sand and brightly colored pebbles."
	icon_sprite = "spr_ui_item_insect_hermit_snail"
	name = "Hermit Snail"
	value = { bin = 35 }
	tags = ["bugs"]

[puddle_spider]
	description = "A rare Tide Caverns insect. Seems to use the vibrations on puddles to hunt."
	icon_sprite = "spr_ui_item_insect_puddle_spider"
	name = "Puddle Spider"
	value = { bin = 45 }
	tags = ["bugs"]

[coral_mantis]
	description = "An uncommon Tide Caverns insect. Its camouflage has turned this mantis into a work of art."
	icon_sprite = "spr_ui_item_insect_coral_mantis"
	name = "Coral Mantis"
	value = { bin = 35 }
	tags = ["bugs"]
