# <---------MINES ITEMS: UPPER MINES------------->

# <---------UPPER MINES ARTIFACTS------------->

[miners_pickaxe]
	name = "Miner's Pickaxe"
	description = "A common artifact. It's in pretty good condition despite its age."
	icon_sprite = "spr_ui_item_miners_pickaxe"
	value = { bin = 40, renown = 5 }
	tags = ["archaeology"]

[tin_lunchbox]
	name = "Tin Lunchbox"
	description = "A common artifact. Sadly, it's empty."
	icon_sprite = "spr_ui_item_tin_lunchbox"
	value = { bin = 40, renown = 5 }
	tags = ["archaeology"]

[miners_slab]
	name = "Miner's Slab"
	description = "An uncommon artifact. It appears to warn of pitfalls ahead."
	icon_sprite = "spr_ui_item_miners_slab"
	value = { bin = 50, renown = 5 }
	tags = ["archaeology"]

[miners_rucksack]
	name = "Miner's Rucksack"
	description = "An uncommon artifact. It seems to have been down in the Mines a long time."
	icon_sprite = "spr_ui_item_miners_rucksack"
	value = { bin = 50, renown = 5 }
	tags = ["archaeology"]

[miners_helmet]
	name = "Miner's Helmet"
	description = "A rare artifact. There is a worn away name on it that ends with the letter L..."
	icon_sprite = "spr_ui_item_miners_helmet"
	value = { bin = 75, renown = 10 }
	tags = ["archaeology"]

	# <---------UPPER MINES FORAGE------------->

[upper_mines_mushroom]
	description = "A wild mushroom with a great flavor and texture. Commonly used as a cooking ingredient."
	icon_sprite = "spr_ui_item_upper_mines_mushroom"
	name = "Upper Mines Mushroom"
	tags = ["forageable", "mines_forageable"]
	restore = 3
	value = { bin = 20 }

[sweetroot]
	description = "A root that grows in caves underground. Makes a great snack, even when eaten raw!"
	icon_sprite = "spr_ui_item_sweetroot"
	name = "Sweetroot"
	tags = ["forageable", "mines_forageable"]
	restore = 20
	value = { bin = 20 }

[shadow_flower]
	description = "A rare flower that only grows in darkness. It makes a unique gift."
	icon_sprite = "spr_ui_item_shadow_flower"
	name = "Shadow Flower"
	tags = ["forageable", "mines_forageable", "flower"]
	value = { bin = 50 }

[narrows_moss]
	description = "A unique species of moss. Very exciting to moss experts."
	icon_sprite = "spr_ui_item_narrows_moss"
	name = "Narrows Moss"
	tags = ["forageable", "mines_forageable"]
	value = { bin = 20 }

	# <---------UPPER MINES FISH------------->

[cave_shrimp]
	description = "A common small Upper Mines crustacean. Its translucent body gives it a distinct appearance."
	icon_sprite = "spr_ui_item_fish_small_cave_shrimp"
	name = "Cave Shrimp"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[rock_guppy]
	description = "An uncommon small Upper Mines fish. Very similar to a regular guppy."
	icon_sprite = "spr_ui_item_fish_small_rock_guppy"
	name = "Rock Guppy"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[stone_loach]
	description = "A common medium Upper Mines fish. They easily blend in with the surrounding rocks."
	icon_sprite = "spr_ui_item_fish_medium_stone_loach"
	name = "Stone Loach"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[cave_eel]
	description = "An uncommon medium Upper Mines fish. They build nests out of stone."
	icon_sprite = "spr_ui_item_fish_medium_cave_eel"
	name = "Cave Eel"
	value = { bin = 50 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[cave_shark]
	description = "A rare large Upper Mines fish. How did they end up in the Mines?!"
	icon_sprite = "spr_ui_item_fish_large_cave_shark"
	name = "Cave Shark"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------UPPER MINES BUGS------------>

[lantern_moth]
	description = "A common Upper Mines insect. They gather near light sources in dark places."
	icon_sprite = "spr_ui_item_insect_lantern_moth"
	name = "Lantern Moth"
	value = { bin = 15 }
	tags = ["bugs"]

[copper_beetle]
	description = "An uncommon Upper Mines insect. Their unique coloration is great camouflage."
	icon_sprite = "spr_ui_item_insect_copper_beetle"
	name = "Copper Nugget Beetle"
	value = { bin = 30 }
	tags = ["bugs"]

[worm]
	description = "An uncommon Upper Mines invertebrate. It's just a worm."
	icon_sprite = "spr_ui_item_insect_worm"
	name = "Worm"
	value = { bin = 15 }
	tags = ["bugs"]

[mine_cricket]
	description = "A rare Upper Mines insect. Their songs are kinda catchy..."
	icon_sprite = "spr_ui_item_insect_mine_cricket"
	name = "Mine Cricket"
	value = { bin = 35 }
	tags = ["bugs"]

[tunnel_millipede]
	description = "An uncommon Upper Mines insect. Their many legs make quick work of tunneling."
	icon_sprite = "spr_ui_item_insect_tunnel_millipede"
	name = "Tunnel Millipede"
	value = { bin = 15 }
	tags = ["bugs"]
