[ryis_two_hearts_turn_in]
kind = "gameplay_triggered"
speaker = "landen"
portrait = "neutral"
local = "Ah, the wood for my request! Come on back to the shop, and I can pay you right now."
actions = [
	{ cutscene = "ryis_two_hearts" },
]

[ryis_two_hearts]
kind = "gameplay_triggered"
speaker = "landen"
portrait = "neutral"
local = "And there you go! 150 tesserae. Thanks again, [Ari]."
next = "1"

[ryis_two_hearts.1]
portrait = "happy"
speaker = "landen"
local = "Ryis will be delighted!"
next = "2"

[ryis_two_hearts.2]
portrait = "think"
speaker = "landen"
local = "Ah, actually, could you go get him while I watch the shop? He's on his break, but I'm sure he'll want to know about this."
next = "3"

[ryis_two_hearts.3]
portrait = "neutral"
speaker = "landen"
local = "You can find him south of the shop by the old cottage ruins."
next = "4"

[ryis_two_hearts.4]
speaker = "ryis"
portrait = "neutral"
local = "[Ari]! This is a surprise."
prompts = [
	{ local = "Message delivery!", next = "5" },
	{ local = "Your uncle told me where you were!", next = "6" },
]

[ryis_two_hearts.5]
speaker = "ryis"
portrait = "happy"
local = "I'm impressed you found me!"
next = "7"

[ryis_two_hearts.6]
speaker = "ryis"
portrait = "neutral"
effect = "surprise"
local = "Haha, that explains it."
next = "7"

[ryis_two_hearts.7]
speaker = "ryis"
portrait = "neutral"
local = "Oh, you fulfilled Uncle Landen's request! You're a lifesaver [Ari]. Now we can finish up a commission that's been on hold."
next = "8"

[ryis_two_hearts.8]
speaker = "ryis"
portrait = "think"
local = "I suppose I should wrap up my break..."
prompts = [
	{ local = "What a pretty spot.", next = "9" },
	{ local = "What were these ruins of?", next = "10" },
]

[ryis_two_hearts.9]
speaker = "ryis"
portrait = "neutral"
local = "Isn't it? I come here to relax."
next = "11"

[ryis_two_hearts.10]
speaker = "ryis"
portrait = "neutral"
local = "Eiland thinks it was someone's house a long time ago, but I just think it's relaxing being out here."
next = "11"

[ryis_two_hearts.11]
speaker = "ryis"
portrait = "think"
local = "Before the earthquake there was a tree here, with an old birdhouse in it. The birds that lived there had the prettiest songs."
next = "12"

[ryis_two_hearts.12]
speaker = "ryis"
portrait = "sad"
local = "'Course, the earthquake took the tree down and smashed the birdhouse. Pretty sure the birds got away safely though."
next = "13"

[ryis_two_hearts.13]
speaker = "ryis"
portrait = "think"
local = "I should really get around to setting up a new birdhouse for them... though it feels a bit silly when I've got so much work to do around Mistria as it is!"
prompts = [
	{ local = "It's not silly, I think it's cool!", next = "14" },
	{ local = "It's a good idea! Those birds could use your help too.", next = "15" },
]

[ryis_two_hearts.14]
speaker = "ryis"
portrait = "embarrassed"
local = "Haha, you think so?"
next = "16"

[ryis_two_hearts.15]
speaker = "ryis"
portrait = "neutral"
local = "That's a good point!"
next = "16"

[ryis_two_hearts.16]
speaker = "ryis"
portrait = "happy"
local = "You know what, you're right [Ari]. It'd be a fun project! I hope I can count on your help?"
next = "17"

[ryis_two_hearts.17]
speaker = "ryis"
portrait = "neutral"
local = "Great! Unfortunately I think my break really is over now. I'll let you know when I've got some time to focus on this!"
