[ryis_four_hearts]
kind = "gameplay_triggered"
speaker = "ryis"
portrait = "happy"
local = "[Ari]!"
next = "1"

[ryis_four_hearts.1]
speaker = "ryis"
portrait = "neutral"
local = "Welcome to my room. Sorry it's a bit cramped, I tend to bring my work upstairs with me..."
prompts = [
	{ local = "It's cozy! Very you.", next = "2" },
	{ local = "If you think this is bad, you should see my farm.", next = "3" },
]

[ryis_four_hearts.2]
speaker = "ryis"
portrait = "embarrassed"
local = "Thank you!"
next = "4"

[ryis_four_hearts.3]
speaker = "ryis"
portrait = "happy"
local = "I can see we're birds of a feather."
next = "4"

[ryis_four_hearts.4]
speaker = "ryis"
portrait = "think"
local = "So according to my big book of Aldarian birds, we're dealing with a Mistrian bluebird!"
next = "5"

[ryis_four_hearts.5]
speaker = "ryis"
portrait = "neutral"
local = "They're similar to their continental cousins, but have a few key differences."
next = "6"

[ryis_four_hearts.6]
speaker = "ryis"
portrait = "happy"
local = "Most notably, they're quite the singers!"
next = "7"

[ryis_four_hearts.7]
speaker = "ryis"
portrait = "think"
local = "They're not picky nesters, but they seem to prefer hawthorn trees."
next = "8"

[ryis_four_hearts.8]
speaker = "ryis"
portrait = "neutral"
local = "So what if we grew a hawthorn to put their new birdhouse in?"
prompts = [
	{ local = "That'll bring them back for sure!", next = "9" },
	{ local = "Thorns to protect your house, huh. Maybe I should get some...", next = "10" },
]

[ryis_four_hearts.9]
speaker = "ryis"
portrait = "happy"
effect = "cheery"
local = "Right? It'll be the perfect spot!"
next = "11"

[ryis_four_hearts.10]
speaker = "ryis"
portrait = "wink"
local = "Haha, sounds like a fun woodworking project."
next = "11"

[ryis_four_hearts.11]
speaker = "balor"
portrait = "happy"
local = "There you are!"
next = "12"

[ryis_four_hearts.12]
speaker = "balor"
portrait = "neutral"
local = "Here's your Hawthorn tree sapling, the finest I could procure."
next = "13"

[ryis_four_hearts.13]
speaker = "ryis"
portrait = "neutral"
local = "Excellent, thank you Balor."
next = "14"

[ryis_four_hearts.14]
speaker = "balor"
portrait = "wink"
local = "You've brought [Ari] in on your project as well? I can see you want to do this right."
next = "15"

[ryis_four_hearts.15]
speaker = "ryis"
portrait = "neutral"
local = "Of course!"
next = "16"

[ryis_four_hearts.16]
speaker = "balor"
portrait = "neutral"
local = "Let's settle up the tab over cards some time. Now, I'm sure you two want to get this sapling into the ground, so I'll leave you to it."
next = "17"

[ryis_four_hearts.17]
speaker = "ryis"
portrait = "neutral"
local = "He's right. Shall we, [Ari]?"
next = "18"

[ryis_four_hearts.18]
speaker = "ryis"
portrait = "neutral"
local = "And that's that. We'll have plenty of time to work on the bird house while the tree grows."
next = "19"

[ryis_four_hearts.19]
speaker = "ryis"
portrait = "think"
local = "Anything I can do to help hurry it along, [Ari]?"
prompts = [
	{ local = "Check on it every day!", next = "20" },
	{ local = "Give the tree compliments every day!", next = "21" },
]

[ryis_four_hearts.20]
speaker = "ryis"
portrait = "happy"
local = "Works for me!"
next = "23"

[ryis_four_hearts.21]
speaker = "ryis"
portrait = "think"
local = "Hey uh, tree... those are some healthy looking... leaves?"
next = "22"

[ryis_four_hearts.22]
speaker = "ryis"
portrait = "embarrassed"
local = "I'll keep practicing..."
next = "23"

[ryis_four_hearts.23]
speaker = "ryis"
portrait = "neutral"
local = "Thanks for all your help today, [Ari]."
