[ryis_six_hearts]
kind = "gameplay_triggered"
writes = [{ ryis_heart_event = "six_heart", expires = "4d" }]
speaker = "landen"
portrait = "happy"
local = "-And that's why I always keep a full set of hammers on my toolbelt at all times."
next = "1"

[ryis_six_hearts.1]
speaker = "ryis"
portrait = "neutral"
local = "I don't know, a full set of screwdrivers on hand seems more useful."
next = "2"

[ryis_six_hearts.2]
speaker = "landen"
portrait = "think"
local = "What if we added a tool... bandolier? Then you could bring everything!"
next = "3"

[ryis_six_hearts.3]
speaker = "ryis"
portrait = "happy"
local = "There you are!"
next = "4"

[ryis_six_hearts.4]
speaker = "landen"
portrait = "neutral"
local = "Here to help with the birdhouse project? Sounds fun!"
next = "5"

[ryis_six_hearts.5]
speaker = "landen"
portrait = "wink"
local = "Tell you what Ryis, I'll take over your shift running the counter."
next = "6"

[ryis_six_hearts.6]
speaker = "ryis"
portrait = "neutral"
local = "Thanks, Uncle."
next = "7"

[ryis_six_hearts.7]
speaker = "ryis"
portrait = "happy"
local = "This is exciting, isn't it? I've been laying aside materials for the project while we've been waiting for the tree to grow big enough."
next = "8"

[ryis_six_hearts.8]
speaker = "ryis"
portrait = "neutral"
local = "I like working on the big town projects with you, but there's something nice about collaborating on something small, right?"
prompts = [{ local = "It'll be fun to get the details just so!", next = "9" }, { local = "Yeah, it's more intimate.", next = "10" }]

[ryis_six_hearts.9]
speaker = "ryis"
portrait = "wink"
local = "You get it!"
next = "11"

[ryis_six_hearts.10]
speaker = "ryis"
portrait = "embarrassed"
local = "Y-yeah..."
next = "11"

[ryis_six_hearts.11]
speaker = "ryis"
portrait = "neutral"
local = "Let me get out my blueprints and we can go over them together!"
next = "12"

[ryis_six_hearts.12]
speaker = "landen"
portrait = "happy"
local = "Well now! That house is much too fine for a bird!"
next = "13"

[ryis_six_hearts.13]
speaker = "ryis"
portrait = "wink"
local = "We might have gotten a little carried away."
prompts = [{ local = "It was really fun to build!", next = "14" }, { local = "It's better than a birdhouse. It's a bird... home.", next = "15"}]

[ryis_six_hearts.14]
speaker = "ryis"
portrait = "happy"
local = "It sure was!"
next = "16"

[ryis_six_hearts.15]
speaker = "ryis"
portrait = "happy"
local = "I'm sure the Mistrian Bluebirds will feel the same way!"
next = "16"

[ryis_six_hearts.16]
speaker = "landen"
portrait = "neutral"
local = "Paint looks like it's dried nicely. Why don't you two hang it, and I'll whip up a celebratory treat for when you get back?"
next = "17"

[ryis_six_hearts.17]
speaker = "landen"
portrait = "wink"
local = "Maybe Ryis didn't tell you this, [Ari], but I make a mean =Coconut Cream Pie=."
next = "18"

[ryis_six_hearts.18]
speaker = "ryis"
portrait = "neutral"
local = "Sounds great! We shouldn't be gone long."
next = "19"

[ryis_six_hearts.19]
speaker= "ryis"
portrait = "think"
local = "Feels good and secure to me."
next = "20"

[ryis_six_hearts.20]
speaker = "ryis"
portrait = "neutral"
local = "Those bluebirds are going to be SO surprised."
prompts = [{ local = "So what's next?", next = "21" }, { local = "So now we need to make a bluebird whistle, huh?", next = "22" }]

[ryis_six_hearts.21]
speaker = "ryis"
portrait = "think"
local = "We keep our eyes peeled for our prospective homeowners. I'll let you know the moment I spot a bit of blue."
next = "23"

[ryis_six_hearts.22]
speaker = "ryis"
portrait = "think"
local = "That would be fun, but I worry it might make the birds think this spot is already taken."
next = "23"

[ryis_six_hearts.23]
speaker = "ryis"
portrait = "happy"
local = "But for right now, I think it's time for pie!"
next = "24"

[ryis_six_hearts.24]
speaker = "ryis"
portrait = "wink"
local = "Come on, we'd better get back before Uncle Landen decides he's tired of waiting."
