[engagement_ring_march]
kind = "gameplay_triggered"
actions = [
	{ bark = { bark = "cute_face", npc = "march" } },
	{ cutscene = "march_ten_hearts" }
]
speaker = "march"
portrait = "eight_heart_happy"
local = "Oh, [Ari]! Hey."
next = "1"

[engagement_ring_march.1]
speaker = "march"
portrait = "eight_heart_think"
local = "Everything okay?"
next = "2"

[engagement_ring_march.2]
speaker = "march"
portrait = "eight_heart_happy"
local = "You want to go somewhere to talk? Sure, I have time."
next = "3"

[engagement_ring_march.3]
speaker = "march"
portrait = "drunk"
local = "Why don't we go up to the $Summit$?"

# ten heart scene
[march_ten_hearts]
kind = "gameplay_triggered"
speaker = "march"
portrait = "eight_heart_happy"
local = "Wow, it's so nice up here..."
next = "1"

[march_ten_hearts.1]
speaker = "march"
portrait = "tsundere"
local = "Maybe we should make an effort to hike up to the Summit more often."
next = "2"

[march_ten_hearts.2]
speaker = "march"
portrait = "eight_heart_happy"
local = "Looking out over the town with you, everything seems more..."
next = "3"

[march_ten_hearts.3]
speaker = "march"
portrait = "tsundere"
local = "Well, more beautiful than before."
next = "4"

[march_ten_hearts.4]
speaker = "march"
portrait = "eight_heart_think"
local = "Don't get me wrong, I know you've worked hard to restore Mistria. That's not exactly what I'm talking about, though..."
next = "5"

[march_ten_hearts.5]
speaker = "march"
portrait = "eight_heart_flustered"
local = "There's just something about you, [Ari]."
next = "6"

[march_ten_hearts.6]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "I don't know what it is, exactly..."
next = "7"

[march_ten_hearts.7]
speaker = "march"
portrait = "eight_heart_flustered"
local = "You make me see things differently than I used to. I wouldn't have guessed that was possible, back when we first met."
prompts = [
	{ local = "Back then, I hoped one day you might one day see me differently, too...", next = "8" },
	{ local = "When we first met, I wouldn't have thought it possible either...", next = "12" }
]

[march_ten_hearts.8]
speaker = "march"
portrait = "sad_special"
local = "[Ari]..."
next = "9"

[march_ten_hearts.9]
speaker = "march"
portrait = "tsundere"
local = "I uh... I always noticed certain things about you. Even if I didn't care to mention them at the time."
next = "10"

[march_ten_hearts.10]
speaker = "march"
portrait = "eight_heart_flustered"
local = "The way your eyes light up when you smile. The way your cheeks flush near the heat of the forge..."
next = "11"

[march_ten_hearts.11]
speaker = "march"
portrait = "tsundere"
local = "Your unwavering persistence in the face of, er... stubbornness."
next = "16"

[march_ten_hearts.12]
speaker = "march"
portrait = "embarrassed"
local = "Yeah, I get that."
next = "13"

[march_ten_hearts.13]
speaker = "march"
portrait = "tsundere"
local = "But you know, I... I always noticed certain things about you. Even if I didn't care to mention them at the time."
next = "14"

[march_ten_hearts.14]
speaker = "march"
portrait = "eight_heart_flustered"
local = "The way your eyes light up when you smile. The way your cheeks flush near the heat of the forge..."
next = "15"

[march_ten_hearts.15]
speaker = "march"
portrait = "tsundere"
local = "Your unwavering persistence in the face of, er... stubbornness."
next = "16"

[march_ten_hearts.16]
speaker = "march"
portrait = "sad_special"
local = "I don't know what compelled you to give me a second chance back then-"
next = "17"

[march_ten_hearts.17]
speaker = "march"
portrait = "tsundere"
local = "Or a third, or a fourth..."
next = "18"

[march_ten_hearts.18]
speaker = "march"
portrait = "mad_special"
local = "But [Ari]..."
next = "19"

[march_ten_hearts.19]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "I'm so glad that you did."
next = "20"

[march_ten_hearts.20]
speaker = "march"
portrait = "sad_special"
local = "My heart was closed off, when you first arrived."
next = "21"

[march_ten_hearts.21]
speaker = "march"
portrait = "eight_heart_think"
local = "It had been, for a long time already."
next = "22"

[march_ten_hearts.22]
speaker = "march"
portrait = "eight_heart_blush"
local = "I didn't like the thought of anything, anyone breaking through."
next = "23"

[march_ten_hearts.23]
speaker = "march"
portrait = "eight_heart_flustered"
local = "But you just kept chipping away. With each hello, with each smile."
next = "24"

[march_ten_hearts.24]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "Until before I knew it... You'd changed me."
prompts = [
	{ local = "You changed me, too. I gained a new kind of strength...", next = "25" },
	{ local = "Forged by the fire in my heart...", next = "26" }
]

[march_ten_hearts.25]
speaker = "march"
portrait = "drunk"
local = "Really, [Ari]?"
next = "27"

[march_ten_hearts.26]
speaker = "march"
portrait = "drunk"
local = "[Ari]! Haha... yeah, honestly. That is what it feels like."
next = "27"

[march_ten_hearts.27]
speaker = "march"
portrait = "eight_heart_flustered"
local = "I hope that means you can forgive me for being such a jerk back then."
next = "28"

[march_ten_hearts.28]
speaker = "march"
portrait = "tsundere"
local = "I was cold. I know that. And yet-"
next = "29"

[march_ten_hearts.29]
speaker = "march"
portrait = "sad_special"
local = "I sometimes wonder if that's just the kind of person I am."
next = "30"

[march_ten_hearts.30]
speaker = "march"
portrait = "eight_heart_think"
local = "It's still not easy for me to open up, you know."
next = "31"

[march_ten_hearts.31]
speaker = "march"
portrait = "tsundere"
local = "There are times I have to fight myself, to keep myself from pushing you away."
next = "32"

[march_ten_hearts.32]
speaker = "march"
portrait = "eight_heart_blush"
local = "Not because I don't want you-"
next = "33"

[march_ten_hearts.33]
speaker = "march"
portrait = "eight_heart_flustered"
local = "But because of how intensely I DO want you."
next = "34"

[march_ten_hearts.34]
speaker = "march"
portrait = "eight_heart_blush"
local = "I want you here by my side, always. I want to see your smile..."
next = "35"

[march_ten_hearts.35]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "And I want to protect you from anything that might threaten to make it disappear."
next = [
    { target = "36_second", requires = [
        { cutscene_seen_march_ten_hearts = true }
    ] },
    { target = "36_first", requires = [] }
]

[march_ten_hearts.36_second]
speaker = "march"
portrait = "eight_heart_flustered"
local = "I've been thinking about that a lot lately, [Ari]."
next = "37_second"

[march_ten_hearts.37_second]
speaker = "march"
portrait = "eight_heart_blush"
local = "That's why I crafted the $Mistrian Shield$ for you."
next = "38_second"

[march_ten_hearts.38_second]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "It represents my promise..."
next = "39_second"

[march_ten_hearts.39_second]
speaker = "march"
portrait = "eight_heart_flustered"
local = "To protect you, and your happiness, no matter what."
next = "40"

[march_ten_hearts.36_first]
speaker = "march"
portrait = "eight_heart_flustered"
local = "I've been thinking about that a lot lately, [Ari]. And there's something important I want to talk to you about."
next = "37_first"

[march_ten_hearts.37_first]
speaker = "march"
portrait = "eight_heart_blush"
local = "But first, there's something I want to give you. Something I put my heart into forging for you."
next = "38_first"

[march_ten_hearts.38_first]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "I call it the $Mistrian Shield$."
next = "39_first"

[march_ten_hearts.39_first]
speaker = "march"
portrait = "eight_heart_flustered"
local = "It's my promise to you. To protect you, and your happiness, no matter what."
next = "40"

[march_ten_hearts.40]
speaker = "march"
portrait = "eight_heart_closed_eyes"
local = "[Ari], I-"
next = "41"

[march_ten_hearts.41]
speaker = "march"
portrait = "mad_special"
local = "There's something I want to ask you..."
next = "42"

[march_ten_hearts.42]
speaker = "march"
portrait = "tsundere"
local = "..."
next = "43"

[march_ten_hearts.43]
speaker = "march"
portrait = "eight_heart_closed_eyes"
local = "What am I saying?"
next = "44"

[march_ten_hearts.44]
speaker = "march"
portrait = "sincere_special"
local = "You're the one who invited me out here to talk! You should go first."
next = "45"

[march_ten_hearts.45]
speaker = "march"
portrait = "eight_heart_happy"
local = "What was on your mind?"
prompts = [
	{ local = "No, no... after you, really.", next = "46" },
	{ local = "Let's talk about it another time...", next = "59" }
]

# first yes
[march_ten_hearts.46]
speaker = "march"
portrait = "eight_heart_flustered"
local = "You want me to go first? Well-"
next = "47"

[march_ten_hearts.47]
speaker = "march"
portrait = "super_flustered"
local = "[Ari], I wanted to ask you-"
next = "48"

[march_ten_hearts.48]
speaker = "march"
portrait = "eight_heart_blush"
local = "To ask if you would-"
next = "49"

[march_ten_hearts.49]
speaker = "march"
portrait = "tsundere"
local = "I mean, will... will you......?"
prompts = [
	{ local = "I love you, March. Of course I'll marry you!", next = "50" },
	{ local = "Actually, let's talk about it more another day.", next = "61" }
]

# second yes
[march_ten_hearts.50]
writes = [
	{ breakup_bump = true, expires = "3d" },
	{ engagement_bump = true, expires = "2d" },
	{ engagement_delay = true, expires = "20h" },
	{ engagement_cap = false, expires = "3d" }
]
actions = [{ can_talk = "march" }]
speaker = "march"
portrait = "super_flustered"
local = "You will?"
next = "51"

[march_ten_hearts.51]
speaker = "march"
portrait = "drunk"
local = "You'll marry me?"
next = "52"

[march_ten_hearts.52]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "You're serious? You're not just teasing me, right?"
next = "53"

[march_ten_hearts.53]
speaker = "march"
portrait = "drunk"
local = "I love you, [Ari]!"
next = "54"

[march_ten_hearts.54]
speaker = "march"
portrait = "eight_heart_flustered"
local = "I feel like I might be dreaming right now..."
next = "55"

[march_ten_hearts.55]
speaker = "march"
portrait = "super_flustered"
local = "I thought so much about how I was going to ask you, the whole time I was working on your $Mistrian Shield$..."
next = "56"

[march_ten_hearts.56]
speaker = "march"
portrait = "tsundere"
local = """And I thought about a hundred different ways you might say "no"."""
next = "57"

[march_ten_hearts.57]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "But now it seems ridiculous that I was ever afraid. E-even if it was hard to get the words out."
next = "58"

[march_ten_hearts.58]
speaker = "march"
portrait = "drunk"
local = "I'm going to marry you, [Ari]! You're mine! I'm so happy!"

# first no
[march_ten_hearts.59]
speaker = "march"
portrait = "eight_heart_flustered"
local = "Are you sure?"
next = "60"

[march_ten_hearts.60]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "Well in that case, just let me know when you want to talk, okay?"

# second no
[march_ten_hearts.61]
speaker = "march"
portrait = "eight_heart_closed_eyes"
local = "Yeah... Maybe that's for the best."
next = "62"

[march_ten_hearts.62]
speaker = "march"
portrait = "eight_heart_flustered"
local = "I can't seem to get my words out today, anyway."
next = "63"

[march_ten_hearts.63]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "Just let me know when you want to talk, okay?"
