[march_two_hearts]
kind = "gameplay_triggered"
speaker = "march"
portrait = "neutral"
local = "I didn't think you'd actually show."
next = "1"

[march_two_hearts.1]
portrait = "think"
local = "I hear you've been making yourself useful around town. Everybody only has good things to say about you."
prompts = [
	{ local = "It's been lots of fun helping out!", next = "2" },
	{ local = "So I guess this is where you apologize for your bad attitude.", next = "3" },
]

[march_two_hearts.2]
portrait = "ugh"
local = "Fun? Ugh."
next = "4"

[march_two_hearts.3]
portrait = "mad"
local = "Hah, not a chance!"
next = "4"

[march_two_hearts.4]
portrait = "neutral"
local = "We both know what's ACTUALLY going on here."
next = "5"

[march_two_hearts.5]
portrait = "unimpressed"
local = "Oh please. You're in way over your head. You come out here, no money, no experience, and think you can just fake your way through running a farm?"
next = "6"

[march_two_hearts.6]
portrait = "mad"
local = "And now everyone in town acts like it was YOU who won the first-place blacksmithing trophy three years running."
next = "7"

[march_two_hearts.7]
portrait = "neutral"
local = "It's all fun and games now, but the second things actually get tough, I'm sure you're going to ditch Mistria and its problems."
prompts = [
	{ local = "I'm not going anywhere!", next = "8" },
	{ local = "Jealousy is an ugly thing, March.", next = "9" },
]

[march_two_hearts.8]
portrait = "unimpressed"
local = "We'll see."
next = "10"

[march_two_hearts.9]
portrait = "mad"
effect = "angry"
local = "Hmph..."
next = "10"

[march_two_hearts.10]
portrait = "neutral"
local = "You think you can hack it for the long haul? Here."
next = "11"

[march_two_hearts.11]
portrait = "think"
local = "If you fail, you can't blame it on a lack of help from me."
next = "12"

[march_two_hearts.12]
portrait = "unimpressed"
local = "Who knows, maybe you'll surprise me. I'll be keeping an eye on you."
next = "13"

[march_two_hearts.13]
portrait = "neutral"
local = "See you around, [Ari]."
