# wedding ceremony
[wedding_balor_0]
kind = "gameplay_triggered"
speaker = "balor"
portrait = "happy_blush"
local = "[Ari], can you believe it? The whole town is here!"
next = "1"

[wedding_balor_0.1]
speaker = "balor"
portrait = "embarrassed"
local = "It's really nice that so many people want to celebrate our happiness with us."
next = "2"

[wedding_balor_0.2]
speaker = "balor"
portrait = "neutral"
local = "Although it wouldn't surprise me if they were mostly here for you."
next = "3"

[wedding_balor_0.3]
speaker = "balor"
portrait = "embarrassed"
local = "I certainly can't keep my eyes off you."
prompts = [
	{ local = "So you like my outfit?", next = "4" },
	{ local = "You clean up very well yourself, Balor.", next = "6" }
]

[wedding_balor_0.4]
speaker = "balor"
portrait = "happy_blush"
local = "Oh, I don't know if \"like\" fully covers it."
next = "5"

[wedding_balor_0.5]
speaker = "balor"
portrait = "embarrassed"
local = "It seems like every day that goes by, I fall more in love with you, [Ari]."
next = "9"

[wedding_balor_0.6]
speaker = "balor"
portrait = "happy_blush"
local = "Haha!"
next = "7"

[wedding_balor_0.7]
speaker = "balor"
portrait = "embarrassed"
local = "If there was ever an occasion for it, it's our wedding."
next = "8"

[wedding_balor_0.8]
speaker = "balor"
portrait = "neutral"
local = "I wanted everything to be... perfect."
next = "9"

[wedding_balor_0.9]
speaker = "elsie"
portrait = "happy"
local = "Not to interrupt you two, but if you're ready... shall we begin the ceremony?"
next = "10"

[wedding_balor_0.10]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "11"

[wedding_balor_0.11]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Balor and [Ari], as they join their light in matrimony."
next = "12"

[wedding_balor_0.12]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two radiant souls-"
next = "13"

[wedding_balor_0.13]
speaker = "elsie"
portrait = "neutral"
local = "Sharing in a bright vision of the future, where all can enjoy shared peace and prosperity..."
next = "14"

[wedding_balor_0.14]
speaker = "elsie"
portrait = "embarrassed"
local = "Destined to shine as one, to spend this lifetime together."
next = "15"

[wedding_balor_0.15]
speaker = "elsie"
portrait = "happy"
local = "Balor, [Ari], if you would..."
next = "16"

[wedding_balor_0.16]
speaker = "elsie"
portrait = "neutral"
local = "Please go ahead and light your candles."
next = "17"

[wedding_balor_0.17]
speaker = "balor"
portrait = "neutral"
local = "[Ari]..."
next = "18"

[wedding_balor_0.18]
speaker = "balor"
portrait = "happy_blush"
local = "Your light... It's amazing! It seems like all of Mistria has lit up!"
prompts = [
	{ local = "So is yours. It's filling the whole town with warmth...", next = "19" },
	{ local = "Yours too! It's burning so beautifully!", next = "19" }
]

[wedding_balor_0.19]
speaker = "balor"
portrait = "embarrassed"
local = "..."
next = "20"

[wedding_balor_0.20]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "21"

[wedding_balor_0.21]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are brilliant indeed!"
next = "22"

[wedding_balor_0.22]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "23"

[wedding_balor_0.23]
speaker = "balor"
portrait = "sincere_special"
local = "[Ari]... you are the light that brightens my world."
next = "24"

[wedding_balor_0.24]
speaker = "balor"
portrait = "neutral"
local = "Driving away the shadows that once lingered in my heart."
next = "25"

[wedding_balor_0.25]
speaker = "balor"
portrait = "embarrassed"
local = "Your love has inspired me to embrace my true self. To never stop striving to make things better."
next = "26"

[wedding_balor_0.26]
speaker = "balor"
portrait = "happy_blush"
local = "I want nothing more than to share this life with you. To be yours, forevermore."
prompts = [
	{ local = "I love you, Balor. I want the same thing.", next = "27" },
	{ local = "I love you, Balor. You make my days better, just being you.", next = "27" }
]

[wedding_balor_0.27]
speaker = "balor"
portrait = "embarrassed"
local = "[Ari]..."
next = "28"

[wedding_balor_0.28]
speaker = "balor"
portrait = "happy_blush"
local = "I love you too."
next = "29"

[wedding_balor_0.29]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "30"

[wedding_balor_0.30]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "31"

[wedding_balor_0.31]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "32"

[wedding_balor_0.32]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception
[wedding_balor_1]
kind = "gameplay_triggered"
speaker = "josephine"
portrait = "neutral"
local = "Ahem!"
next = "1"

[wedding_balor_1.1]
speaker = "josephine"
portrait = "happy"
local = "My fellow Mistrians... Thank you for joining us today, to celebrate the marriage of Balor and [Ari]."
next = "2"

[wedding_balor_1.2]
speaker = "josephine"
portrait = "think"
local = "They both came to this village as strangers, during its time of greatest need."
next = "3"

[wedding_balor_1.3]
speaker = "josephine"
portrait = "sad"
local = "A time when many had already left, and few would venture to come here..."
next = "4"

[wedding_balor_1.4]
speaker = "josephine"
portrait = "neutral"
local = "But they did. And despite the challenges that faced them, they stayed."
next = "5"

[wedding_balor_1.5]
speaker = "josephine"
portrait = "happy"
local = "Through their tireless hard work, they not only helped to improve the town, but became a treasured part of it."
next = "6"

[wedding_balor_1.6]
speaker = "josephine"
portrait = "neutral"
local = "Why, I don't think there's a soul in town who hasn't benefited from their care and dedication to making Mistria a better place for all."
next = "7"

[wedding_balor_1.7]
speaker = "josephine"
portrait = "embarrassed"
local = "You are truly part of the family. We are honored and delighted to celebrate this special day with you both."
next = "8"

[wedding_balor_1.8]
speaker = "balor"
portrait = "embarrassed"
local = "Jo... everyone, thank you. I think I speak for [Ari] and I both when I say that we're lucky to call Mistria our home."
next = "9"

[wedding_balor_1.9]
speaker = "hemlock"
portrait = "happy"
local = "To [Ari] and Balor! May the care you show us all return to you tenfold."
next = "10"

[wedding_balor_1.10]
speaker = "maple"
portrait = "happy"
local = "May mom let me take over Balor's old room! Expanding my territory twofold!"
next = "11"

[wedding_balor_1.11]
speaker = "luc"
portrait = "embarrassed"
local = "May your life together be like a legendary bug... one of a kind!"
next = "12"

[wedding_balor_1.12]
speaker = "josephine"
portrait = "happy"
local = "Cheers! To the newly married couple!"
next = "13"

[wedding_balor_1.13]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_balor_2]
kind = "gameplay_triggered"
speaker = "balor"
portrait = "happy_blush"
local = "What a wonderful night!"
next = "1"

[wedding_balor_2.1]
speaker = "balor"
portrait = "neutral"
local = "So many toasts..."
next = "2"

[wedding_balor_2.2]
speaker = "balor"
portrait = "think"
local = "We've done something worthwhile here, haven't we [Ari]?"
next = "3"

[wedding_balor_2.3]
speaker = "balor"
portrait = "neutral"
local = "Somewhere along the way, it became about more than just helping Mistria..."
next = "4"

[wedding_balor_2.4]
speaker = "balor"
portrait = "embarrassed"
local = "It became about making a home for the two of us."
prompts = [
	{ local = "You always did dream big.", next = "5" },
	{ local = "I'd say... this is only the beginning.", next = "6" }
]

[wedding_balor_2.5]
speaker = "balor"
portrait = "happy_blush"
local = "You're the only person I've met who dreams as big as I do, [Ari]."
next = "7"

[wedding_balor_2.6]
speaker = "balor"
portrait = "happy_blush"
local = "That's just one of the things I love about you, [Ari]. You always know how to get me fired up."
next = "7"

[wedding_balor_2.7]
speaker = "balor"
portrait = "neutral"
local = "Well... the night is still young."
next = "8"

[wedding_balor_2.8]
speaker = "balor"
portrait = "embarrassed"
local = "Shall we head inside and continue the celebration?"
