# wedding
[wedding_juniper_0]
kind = "gameplay_triggered"
speaker = "juniper"
portrait = "neutral"
local = "[Ari]... You..."
next = "1"

[wedding_juniper_0.1]
speaker = "juniper"
portrait = "sly"
local = "You've outdone yourself."
prompts = [
	{ local = "Speak for yourself. I'm breathless.", next = "2" },
	{ local = "I was hoping you'd like it.", next = "7" }
]

[wedding_juniper_0.2]
speaker = "juniper"
portrait = "happy"
local = "I'm happy you're pleased."
next = "3"

[wedding_juniper_0.3]
speaker = "juniper"
portrait = "sly"
local = "These bridal silks were woven long ago and far away, using a technique lost to time."
next = "4"

[wedding_juniper_0.4]
speaker = "juniper"
portrait = "sincere_special"
local = "I brought this dress among other heirlooms when I came to Mistria..."
next = "5"

[wedding_juniper_0.5]
speaker = "juniper"
portrait = "neutral"
local = "I never thought the day would come that I'd get to wear it."
next = "6"

[wedding_juniper_0.6]
speaker = "juniper"
portrait = "think_special"
local = "Look at me, prattling on. You got me carried away, [Ari]. I thought I wasn't nervous."
next = "11"

[wedding_juniper_0.7]
speaker = "juniper"
portrait = "happy"
local = "V-very much so."
next = "8"

[wedding_juniper_0.8]
speaker = "juniper"
portrait = "think_special"
local = "Seeing you dressed up like this, it's finally starting to feel real..."
next = "9"

[wedding_juniper_0.9]
speaker = "juniper"
portrait = "neutral"
local = "We're really doing this, [Ari]!"
next = "10"

[wedding_juniper_0.10]
speaker = "juniper"
portrait = "happy"
local = "I'm so happy!"
next = "11"

[wedding_juniper_0.11]
speaker = "elsie"
portrait = "embarrassed"
local = "Oh, you two... I do so hate to interrupt, but it's time to begin the ceremony."
next = "12"

[wedding_juniper_0.12]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "13"

[wedding_juniper_0.13]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Juniper and [Ari], as they join their light in matrimony."
next = "14"

[wedding_juniper_0.14]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two brilliant souls-"
next = "15"

[wedding_juniper_0.15]
speaker = "elsie"
portrait = "neutral"
local = "Swept to Mistria by the tides of fate."
next = "16"

[wedding_juniper_0.16]
speaker = "elsie"
portrait = "embarrassed"
local = "Destined to meet, to unite as one."
next = "17"

[wedding_juniper_0.17]
speaker = "elsie"
portrait = "happy"
local = "Juniper, [Ari], if you would..."
next = "18"

[wedding_juniper_0.18]
speaker = "elsie"
portrait = "neutral"
local = "Please go ahead and light your candles."
next = "19"

[wedding_juniper_0.19]
speaker = "juniper"
portrait = "neutral"
local = "[Ari]..."
next = "20"

[wedding_juniper_0.20]
speaker = "juniper"
portrait = "sly"
local = "This light of mine shines for you."
prompts = [
	{ local = "And mine for you.", next = "21" },
	{ local = "And I'll protect it with everything I have.", next = "22" }
]

[wedding_juniper_0.21]
speaker = "juniper"
portrait = "sincere_special"
local = "I'll never let it go out."
next = "23"

[wedding_juniper_0.22]
speaker = "juniper"
portrait = "neutral"
local = "[Ari]..."
next = "23"

[wedding_juniper_0.23]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "24"

[wedding_juniper_0.24]
speaker = "elsie"
portrait = "wink"
local = "I can see how you sustain each others' flames..."
next = "25"

[wedding_juniper_0.25]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "26"

[wedding_juniper_0.26]
speaker = "juniper"
portrait = "neutral"
local = "[Ari]... With your light, you have cast warmth and love into my life."
next = "27"

[wedding_juniper_0.27]
speaker = "juniper"
portrait = "sincere_special"
local = "Illuminating even the deepest recesses of my heart."
next = "28"

[wedding_juniper_0.28]
speaker = "juniper"
portrait = "sly"
local = "A magic only you are capable of conjuring."
next = "29"

[wedding_juniper_0.29]
speaker = "juniper"
portrait = "neutral"
local = "With these words, I bind my heart to yours for all that may come..."
prompts = [
	{ local = "I love you, Juniper. I am eternally under your spell.", next = "30" },
	{ local = "I love you, Juniper. My heart is yours.", next = "31" }
]

[wedding_juniper_0.30]
speaker = "juniper"
portrait = "happy"
local = "I love you too, [Ari]."
next = "32"

[wedding_juniper_0.31]
speaker = "juniper"
portrait = "sly"
local = "I love you too, [Ari]."
next = "32"

[wedding_juniper_0.32]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "33"

[wedding_juniper_0.33]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "34"

[wedding_juniper_0.34]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "35"

[wedding_juniper_0.35]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception
[wedding_juniper_1]
kind = "gameplay_triggered"
speaker = "celine"
portrait = "blush_special"
local = "Um... c-can I have your attention, everyone? I prepared a toast!"
next = "1"

[wedding_juniper_1.1]
speaker = "elsie"
portrait = "neutral"
local = "Oh? I as well."
next = "2"

[wedding_juniper_1.2]
speaker = "dell"
portrait = "happy"
local = "We want to make some toast, too!"
next = "3"

[wedding_juniper_1.3]
speaker = "maple"
portrait = "wink"
local = "Yeah, you should let us go! We've been friends with Juniper the longest!"
next = "4"

[wedding_juniper_1.4]
speaker = "luc"
portrait = "happy"
local = "And [Ari] too! <he>He's</he><she>She's</she><they>They've</they><it>It's</it><none>[Ari]'s</none> been my protege since <he>he</he><she>she</she><they>they</they><it>it</it><none>[Ari]</none> first came to Mistria!"
next = "5"

[wedding_juniper_1.5]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "Oh! In that case, by all means..."
next = "6"

[wedding_juniper_1.6]
speaker = "elsie"
portrait = "neutral"
local = "Please, go ahead children!"
next = "7"

[wedding_juniper_1.7]
speaker = "dell"
portrait = "happy"
local = "Yay!"
next = "8"

[wedding_juniper_1.8]
speaker = "dell"
portrait = "neutral"
local = "Congrats Juniper, congrats [Ari]!"
next = "9"

[wedding_juniper_1.9]
speaker = "dell"
portrait = "happy"
effect = "sparkles"
local = "May your lives be happy, and your cauldrons normal-smelling."
next = "10"

[wedding_juniper_1.10]
speaker = "luc"
portrait = "happy"
local = "Congratulations you two!"
next = "11"

[wedding_juniper_1.11]
speaker = "luc"
portrait = "embarrassed"
local = "I haven't cried this much since my mantises got married..."
next = "12"

[wedding_juniper_1.12]
speaker = "luc"
portrait = "happy"
effect = "cheery"
local = "But don't worry, these are happy tears!"
next = "13"

[wedding_juniper_1.13]
speaker = "maple"
portrait = "happy"
local = "Queen Maple hereby congratulates you on your nuptials!"
next = "14"

[wedding_juniper_1.14]
speaker = "maple"
portrait = "neutral"
local = "May your houses benefit from this auspicious union..."
next = "15"

[wedding_juniper_1.15]
speaker = "maple"
portrait = "happy"
local = "And may your enemies' positions be weakened as a result."
next = "16"

[wedding_juniper_1.16]
speaker = "celine"
portrait = "embarrassed"
local = "Um. Well said!"
next = "17"

[wedding_juniper_1.17]
speaker = "elsie"
portrait = "happy"
local = "Hear hear!"
next = "18"

[wedding_juniper_1.18]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_juniper_2]
kind = "gameplay_triggered"
speaker = "juniper"
portrait = "neutral"
local = "I can hardly believe today was real..."
next = "1"

[wedding_juniper_2.1]
speaker = "juniper"
portrait = "think_special"
local = "Marrying you... and being celebrated by so many people..."
next = "2"

[wedding_juniper_2.2]
speaker = "juniper"
portrait = "sly"
local = "It's like a dream."
next = "3"

[wedding_juniper_2.3]
speaker = "juniper"
portrait = "sincere_special"
local = "But it's not a dream, is it? Here you are, standing right in front of me."
next = "4"

[wedding_juniper_2.4]
speaker = "juniper"
portrait = "happy"
local = "I'm... so happy I can't stand it."
prompts = [
	{ local = "Me too, Juniper.", next = "5" },
	{ local = "Welcome home, Juniper.", next = "5" }
]

[wedding_juniper_2.5]
speaker = "juniper"
portrait = "sly"
local = "[Ari]..."
next = "6"

[wedding_juniper_2.6]
speaker = "juniper"
portrait = "think_special"
local = "The mysterious wanderer who came to Mistria..."
next = "7"

[wedding_juniper_2.7]
speaker = "juniper"
portrait = "sly"
local = "Now I have a lifetime to unravel you."
