# wedding ceremony

[wedding_march_0]
kind = "gameplay_triggered"
speaker = "march"
portrait = "embarrassed"
local = "[Ari]... You look..."
next = "1"

[wedding_march_0.1]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "You look incredible."
prompts = [
	{ local = "So do you!", next = "2" },
	{ local = "You like it?", next = "7" }
]

[wedding_march_0.2]
speaker = "march"
portrait = "tsundere"
local = "I do?"
next = "3"

[wedding_march_0.3]
speaker = "march"
portrait = "embarrassed"
local = "Um."
next = "4"

[wedding_march_0.4]
speaker = "march"
portrait = "think"
local = "I had a hard time remembering which way I comb my hair... Er."
next = "5"

[wedding_march_0.5]
speaker = "march"
portrait = "tsundere"
local = "Seeing you all dressed up like this... it's kind of unfair."
next = "6"

[wedding_march_0.6]
speaker = "march"
portrait = "eight_heart_blush"
local = "You're taking my breath away."
next = "11"

[wedding_march_0.7]
speaker = "march"
portrait = "embarrassed"
local = "U-um..."
next = "8"

[wedding_march_0.8]
speaker = "march"
portrait = "eight_heart_flustered"
local = "It's just..."
next = "9"

[wedding_march_0.9]
speaker = "march"
portrait = "drunk"
local = "Seeing you all dressed up like this..."
next = "10"

[wedding_march_0.10]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "You kind of... took my breath away."
next = "11"

[wedding_march_0.11]
speaker = "elsie"
portrait = "wink"
local = "I do so hate to interrupt March's flirting, but if you two are ready... shall we begin the ceremony?"
next = "12"

[wedding_march_0.12]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "13"

[wedding_march_0.13]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of March and [Ari], as they join their light in matrimony."
next = "14"

[wedding_march_0.14]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two radiant souls-"
next = "15"

[wedding_march_0.15]
speaker = "elsie"
portrait = "neutral"
local = "Brilliant sparks, cast into the world by the strike of eternity's hammer."
next = "16"

[wedding_march_0.16]
speaker = "elsie"
portrait = "embarrassed"
local = "Destined to meet, to share this lifetime together."
next = "17"

[wedding_march_0.17]
speaker = "elsie"
portrait = "happy"
local = "March, [Ari], if you would..."
next = "18"

[wedding_march_0.18]
speaker = "elsie"
portrait = "neutral"
local = "Please go ahead and light your candles."
next = "19"

[wedding_march_0.19]
speaker = "march"
portrait = "sincere_special"
local = "[Ari]..."
next = "20"

[wedding_march_0.20]
speaker = "march"
portrait = "eight_heart_blush"
local = "Your light. It's... beautiful."
prompts = [
	{ local = "So is yours. It's glowing so tenderly...", next = "21" },
	{ local = "Yours is amazing. It's blazing so intensely!", next = "22" }
]

[wedding_march_0.21]
speaker = "march"
portrait = "embarrassed"
local = "..."
next = "23"

[wedding_march_0.22]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "..."
next = "23"

[wedding_march_0.23]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "24"

[wedding_march_0.24]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are brilliant indeed!"
next = "25"

[wedding_march_0.25]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "26"

[wedding_march_0.26]
speaker = "march"
portrait = "sincere_special"
local = "[Ari]. The flame in my heart burns only for you."
next = "27"

[wedding_march_0.27]
speaker = "march"
portrait = "neutral"
local = "I promise to offer you my light when the day is dark."
next = "28"

[wedding_march_0.28]
speaker = "march"
portrait = "embarrassed"
local = "To share my warmth when the day is cold."
next = "29"

[wedding_march_0.29]
speaker = "march"
portrait = "eight_heart_flustered"
local = "To forge our future together, side by side."
next = "30"

[wedding_march_0.30]
speaker = "march"
portrait = "mad"
local = "And to love you fiercely, for all my days."
prompts = [
	{ local = "I love you, March. You are everything to me.", next = "31" },
	{ local = "I love you, March. I promise that I'll always stay by your side.", next = "32" }
]

[wedding_march_0.31]
speaker = "march"
portrait = "embarrassed"
local = "I love you too, [Ari]."
next = "34"

[wedding_march_0.32]
speaker = "march"
portrait = "embarrassed"
local = "[Ari]..."
next = "33"

[wedding_march_0.33]
speaker = "march"
portrait = "teary"
local = "I love you too."
next = "34"

[wedding_march_0.34]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "35"

[wedding_march_0.35]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "36"

[wedding_march_0.36]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "37"

[wedding_march_0.37]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# wedding speech
[wedding_march_1]
kind = "gameplay_triggered"
speaker = "olric"
portrait = "neutral"
local = "Ahem!"
next = "1"

[wedding_march_1.1]
speaker = "olric"
portrait = "happy"
local = "You just know we gotta make a toast! To [Ari] and March!"
next = "2"

[wedding_march_1.2]
speaker = "olric"
portrait = "neutral"
local = "March, you're the best brother a guy could ask for."
next = "3"

[wedding_march_1.3]
speaker = "olric"
portrait = "happy"
local = "It's been an honor to watch you grow up and stuff..."
next = "4"

[wedding_march_1.4]
speaker = "olric"
portrait = "embarrassed"
local = "And now, seeing you move on to this next stage of your life... I'm super proud of you."
next = "5"

[wedding_march_1.5]
speaker = "olric"
portrait = "sad"
local = "My one and only little bro..."
next = "6"

[wedding_march_1.6]
speaker = "olric"
portrait = "neutral"
local = "Though now that I think about it, if you and [Ari] are married..."
next = "7"

[wedding_march_1.7]
speaker = "olric"
portrait = "mad"
effect = "sparkles"
local = "Then <he>he's</he><she>she's</she><they>they're</they><it>it's</it><none>[Ari]'s</none> officially my bro, too!"
next = "8"

[wedding_march_1.8]
speaker = "olric"
portrait = "think"
local = "So actually, I'm not really losing a bro at all-"
next = "9"

[wedding_march_1.9]
speaker = "olric"
portrait = "happy"
local = "I'm totally gaining another one! Cool!"
next = "10"

[wedding_march_1.10]
speaker = "olric"
portrait = "embarrassed"
effect = "cheery"
local = "Congrats, you two!"
next = "11"

[wedding_march_1.11]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_march_2]
kind = "gameplay_triggered"
speaker = "march"
portrait = "drunk"
local = "What an amazing night!"
next = "1"

[wedding_march_2.1]
speaker = "march"
portrait = "embarrassed"
local = "I can hardly believe it. We really did it. We got married!"
next = "2"

[wedding_march_2.2]
speaker = "march"
portrait = "eight_heart_flustered"
local = "It's strange to think I'll be living here now, too..."
next = "3"

[wedding_march_2.3]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "A home of my own, a family of my own."
next = "4"

[wedding_march_2.4]
speaker = "march"
portrait = "teary"
local = "I'm... I'm really happy, [Ari]"
prompts = [
	{ local = "Me too, March.", next = "5" },
	{ local = "Welcome home, March.", next = "5" }
]

[wedding_march_2.5]
speaker = "march"
portrait = "eight_heart_happy_blush"
local = "..."
next = "6"

[wedding_march_2.6]
speaker = "march"
portrait = "neutral"
local = "Well, it's getting pretty late."
next = "7"

[wedding_march_2.7]
speaker = "march"
portrait = "embarrassed"
local = "What do you think? Should we call it a night?"
