[wedding_eiland_0]
kind = "gameplay_triggered"
speaker = "eiland"
portrait = "neutral"
local = "[Ari]! The way you look right now..."
next = "1"

[wedding_eiland_0.1]
speaker = "eiland"
portrait = "hope_special"
local = "My words alone couldn't capture it."
next = "2"

[wedding_eiland_0.2]
speaker = "eiland"
portrait = "embarrassed"
local = "If-if you don't mind me saying so..."
prompts = [
	{ local = "Eiland... I'm so glad you feel that way.", next = "3" },
	{ local = "You look wonderful too, Eiland.", next = "5" }
]

[wedding_eiland_0.3]
speaker = "eiland"
portrait = "neutral"
local = "I mean it."
next = "4"

[wedding_eiland_0.4]
speaker = "eiland"
portrait = "embarrassed"
local = "I'm falling in love with you all over again."
next = "8"

[wedding_eiland_0.5]
speaker = "eiland"
portrait = "embarrassed"
local = "Oh!"
next = "6"

[wedding_eiland_0.6]
speaker = "eiland"
portrait = "bashful"
local = "It's not too much, is it?"
next = "7"

[wedding_eiland_0.7]
speaker = "eiland"
portrait = "embarrassed"
local = "I... I guess I'm just a little nervous!"
next = "8"

[wedding_eiland_0.8]
speaker = "elsie"
portrait = "happy"
local = "Well, aren't you two just the cutest! If you're ready now... shall we begin the ceremony?"
next = "9"

[wedding_eiland_0.9]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "10"

[wedding_eiland_0.10]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Eiland and [Ari], as they join their light in matrimony."
next = "11"

[wedding_eiland_0.11]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two radiant souls-"
next = "12"

[wedding_eiland_0.12]
speaker = "elsie"
portrait = "neutral"
local = "Beacons of light, drawn to each other across time."
next = "13"

[wedding_eiland_0.13]
speaker = "elsie"
portrait = "embarrassed"
local = "Destined to find one another, to share this lifetime together."
next = "14"

[wedding_eiland_0.14]
speaker = "elsie"
portrait = "happy"
local = "Eiland, [Ari], if you would..."
next = "15"

[wedding_eiland_0.15]
speaker = "elsie"
portrait = "neutral"
local = "Please go ahead and light your candles."
next = "16"

[wedding_eiland_0.16]
speaker = "eiland"
portrait = "neutral"
local = "[Ari]..."
next = "17"

[wedding_eiland_0.17]
speaker = "eiland"
portrait = "happy"
local = "Your light... It's resplendent! Everything is so vivid in its glow!"
prompts = [
	{ local = "So is yours. It's glowing so enthusiastically...", next = "18" },
	{ local = "Yours too! It's burning so devotedly!", next = "18" }
]

[wedding_eiland_0.18]
speaker = "eiland"
portrait = "hope_special"
local = "..."
next = "19"

[wedding_eiland_0.19]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "20"

[wedding_eiland_0.20]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are brilliant indeed!"
next = "21"

[wedding_eiland_0.21]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "22"

[wedding_eiland_0.22]
speaker = "eiland"
portrait = "neutral"
local = "[Ari]... your light has shown me wonders untold."
next = "23"

[wedding_eiland_0.23]
speaker = "eiland"
portrait = "embarrassed"
local = "With you by my side, the world has greater depth, more meaning."
next = "24"

[wedding_eiland_0.24]
speaker = "eiland"
portrait = "hope_special"
local = "Your love has inspired me to press forward into a brilliant new future."
next = "25"

[wedding_eiland_0.25]
speaker = "eiland"
portrait = "neutral"
local = "I want nothing more than to find out what lies beyond that distant horizon with you."
next = "26"

[wedding_eiland_0.26]
speaker = "eiland"
portrait = "happy"
local = "Ours is a story that will surely echo across time. A love for the ages."
prompts = [
	{ local = "I love you, Eiland, now and forever.", next = "27" },
	{ local = "I love you, Eiland. Let's never stop chasing our dreams.", next = "28" }
]

[wedding_eiland_0.27]
speaker = "eiland"
portrait = "embarrassed"
local = "I love you too, [Ari]."
next = "30"

[wedding_eiland_0.28]
speaker = "eiland"
portrait = "embarrassed"
local = "[Ari]..."
next = "29"

[wedding_eiland_0.29]
speaker = "eiland"
portrait = "happy"
local = "I love you too."
next = "30"

[wedding_eiland_0.30]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "31"

[wedding_eiland_0.31]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "32"

[wedding_eiland_0.32]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "33"

[wedding_eiland_0.33]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception
[wedding_eiland_1]
kind = "gameplay_triggered"
speaker = "wiscar"
portrait = "neutral"
local = "Ahem!"
next = "1"

[wedding_eiland_1.1]
speaker = "wiscar"
portrait = "happy"
local = "My fellow Mistrians... We thank you for joining us today, to celebrate the marriage of our son, Eiland."
next = "2"

[wedding_eiland_1.2]
speaker = "wiscar"
portrait = "neutral"
local = "It is our great honor to officially welcome you to the family, [Ari]."
next = "3"

[wedding_eiland_1.3]
speaker = "wiscar"
portrait = "happy"
local = "The two of you have worked very hard for the sake of Mistria. Our Museum has become a wonder of Aldaria."
next = "4"

[wedding_eiland_1.4]
speaker = "wiscar"
portrait = "neutral"
local = "I am immensely proud of you both, and I wholeheartedly support and rejoice in your union."
next = "5"

[wedding_eiland_1.5]
speaker = "wiscar"
portrait = "embarrassed"
local = "I feel that I can rest assured, knowing that your sights are set on not just Mistria's future, but your own."
next = "6"

[wedding_eiland_1.6]
speaker = "eiland"
portrait = "embarrassed"
local = "Father..."
next = "7"

[wedding_eiland_1.7]
speaker = "linnet"
portrait = "happy"
local = "My dearest Eiland..."
next = "8"

[wedding_eiland_1.8]
speaker = "linnet"
portrait = "neutral"
local = "Your letters over these past seasons had long convinced me that what had begun to grow between you and [Ari] would one day blossom."
next = "9"

[wedding_eiland_1.9]
speaker = "linnet"
portrait = "happy"
local = "Just how brilliantly, I'm not sure that I could have guessed..."
next = "10"

[wedding_eiland_1.10]
speaker = "linnet"
portrait = "embarrassed"
local = "I hope that the happiness of this special day will continue to shine throughout the rest of your lives together..."
next = "11"

[wedding_eiland_1.11]
speaker = "linnet"
portrait = "think"
local = "And while I match your father's trust and faith in you two..."
next = "12"

[wedding_eiland_1.12]
speaker = "linnet"
portrait = "embarrassed"
local = "As a mother, just know that if you two need anything... We're only a few day's carriage ride away."
next = "13"

[wedding_eiland_1.13]
speaker = "linnet"
portrait = "happy"
local = "Cheers! To the newly married couple!"
next = "14"

[wedding_eiland_1.14]
speaker = "adeline"
portrait = "happy"
effect = "cheery"
local = "Congratulations, you two!"
next = "15"

[wedding_eiland_1.15]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_eiland_2]
kind = "gameplay_triggered"
speaker = "eiland"
portrait = "embarrassed"
local = "Well!"
next = "1"

[wedding_eiland_2.1]
speaker = "eiland"
portrait = "hope_special"
local = "Here we are!"
next = "2"

[wedding_eiland_2.2]
speaker = "eiland"
portrait = "bashful"
local = "Newly wed. About to start our new lives together..."
next = "3"

[wedding_eiland_2.3]
speaker = "eiland"
portrait = "embarrassed"
local = "I'm sorry, I don't know why I've suddenly gotten nervous again."
prompts = [
	{ local = "It's okay! There's nothing to be nervous about!", next = "4" },
	{ local = "I'm a bit nervous too...", next = "5" }
]

[wedding_eiland_2.4]
speaker = "eiland"
portrait = "hope_special"
local = "You're right, of course."
next = "6"

[wedding_eiland_2.5]
speaker = "eiland"
portrait = "hope_special"
local = "You are? I had no idea!"
next = "6"

[wedding_eiland_2.6]
speaker = "eiland"
portrait = "happy"
local = "It just feels surreal to be standing here, at the door of our new home together..."
next = "7"

[wedding_eiland_2.7]
speaker = "eiland"
portrait = "think"
local = "But there's no place I'd rather be than right here, with you."
next = "8"

[wedding_eiland_2.8]
speaker = "eiland"
portrait = "hope_special"
local = "So... shall we call it a night?"
