# wedding
[wedding_valen_0]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "happy_blush"
local = "[Ari], can you believe it? Our big day is finally here!"
next = "1"

[wedding_valen_0.1]
speaker = "valen"
portrait = "embarrassed"
local = "You look fantastic..."
prompts = [
    { local = "Do you like my outfit?", next = "2" },
    { local = "Love the suit, Valen.", next = "5" }
]

[wedding_valen_0.2]
speaker = "valen"
portrait = "happy_blush"
local = "Very much so."
next = "3"

[wedding_valen_0.3]
speaker = "valen"
portrait = "caring_special"
local = "Although I personally think you look good in anything..."
next = "4"

[wedding_valen_0.4]
speaker = "valen"
portrait = "embarrassed"
local = "This outfit especially suits you, [Ari]."
next = "8"

[wedding_valen_0.5]
speaker = "valen"
portrait = "happy_blush"
local = "You do? Me too."
next = "6"

[wedding_valen_0.6]
speaker = "valen"
portrait = "embarrassed"
local = "It's nice to get dressed up, sometimes."
next = "7"

[wedding_valen_0.7]
speaker = "valen"
portrait = "neutral"
local = "And if there was ever a day for it, it's today!"
next = "8"

[wedding_valen_0.8]
speaker = "elsie"
portrait = "happy"
local = "You both look picture perfect. Now, if you're ready... shall we begin the ceremony?"
next = "9"

[wedding_valen_0.9]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "10"

[wedding_valen_0.10]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Valen and [Ari], as they join their light in matrimony."
next = "11"

[wedding_valen_0.11]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two radiant souls-"
next = "12"

[wedding_valen_0.12]
speaker = "elsie"
portrait = "neutral"
local = "Beacons of hope and generosity, offering care and assistance to all who may need it."
next = "13"

[wedding_valen_0.13]
speaker = "elsie"
portrait = "embarrassed"
local = "Shining their light as one, destined to live this life together in the service of a greater good."
next = "14"

[wedding_valen_0.14]
speaker = "elsie"
portrait = "happy"
local = "Valen, [Ari], if you would..."
next = "15"

[wedding_valen_0.15]
speaker = "elsie"
portrait = "neutral"
local = "Please light your candles."
next = "16"

[wedding_valen_0.16]
speaker = "valen"
portrait = "neutral"
local = "[Ari]..."
next = "17"

[wedding_valen_0.17]
speaker = "valen"
portrait = "happy_blush"
local = "Your light... It's incredible! It feels so warm..."
prompts = [
    { local = "So is yours. It's so comforting...", next = "18" },
    { local = "Yours too! It's burning so brightly!", next = "18" }
]

[wedding_valen_0.18]
speaker = "valen"
portrait = "hope_special"
local = "..."
next = "19"

[wedding_valen_0.19]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "20"

[wedding_valen_0.20]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are brilliant indeed!"
next = "21"

[wedding_valen_0.21]
speaker = "elsie"
portrait = "neutral"
local = "Now, it's time for the joining."
next = "22"

[wedding_valen_0.22]
speaker = "valen"
portrait = "embarrassed"
local = "[Ari]... where do I even begin?"
next = "23"

[wedding_valen_0.23]
speaker = "valen"
portrait = "think"
local = "You've brought me light and hope on even the darkest of days..."
next = "24"

[wedding_valen_0.24]
speaker = "valen"
portrait = "embarrassed"
local = "Times at which it would have been easier for me to give up than to push forward."
next = "25"

[wedding_valen_0.25]
speaker = "valen"
portrait = "teary"
local = "I have never met anyone as selfless, caring, and brave as you. You are my everything."
prompts = [
    { local = "I love you, Valen. I feel the same way.", next = "26" },
    { local = "I love you, Valen. You are my inspiration.", next = "27" }
]

[wedding_valen_0.26]
speaker = "valen"
portrait = "embarrassed"
local = "[Ari]... I..."
next = "28"

[wedding_valen_0.27]
speaker = "valen"
portrait = "embarrassed"
local = "Oh [Ari]..."
next = "28"

[wedding_valen_0.28]
speaker = "valen"
portrait = "happy_blush"
local = "I love you too."
next = "29"

[wedding_valen_0.29]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "30"

[wedding_valen_0.30]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "31"

[wedding_valen_0.31]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "32"

[wedding_valen_0.32]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception
[wedding_valen_1]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "neutral"
local = "Ahem!"
next = "1"

[wedding_valen_1.1]
speaker = "hayden"
portrait = "happy_arm_down"
local = "As Valen's oldest friend, it is my honor and privilege to celebrate her marriage to [Ari] with a toast!"
next = "2"

[wedding_valen_1.2]
speaker = "hayden"
portrait = "neutral_fist"
local = "There isn't a soul in town who hasn't been helped by our doctor."
next = "3"

[wedding_valen_1.3]
speaker = "hayden"
portrait = "think"
local = "She's certainly saved my skin more times than I can count!"
next = "4"

[wedding_valen_1.4]
speaker = "hayden"
portrait = "laugh"
local = "Gya ha ha ha!"
next = "5"

[wedding_valen_1.5]
speaker = "hayden"
portrait = "happy"
local = "And [Ari]!"
next = "6"

[wedding_valen_1.6]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "You're the best neighbor a fellow could ask for."
next = "7"

[wedding_valen_1.7]
speaker = "hayden"
portrait = "happy_fist"
local = "You're generous, selfless, and a true Mistrian at heart..."
next = "8"

[wedding_valen_1.8]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "Why, I'd say you two are a perfect match."
next = "9"

[wedding_valen_1.9]
speaker = "hayden"
portrait = "happy"
local = "Cheers, everyone! To the newlyweds!"
next = "10"

[wedding_valen_1.10]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_valen_2]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "happy_blush"
local = "What a wonderful night!"
next = "1"

[wedding_valen_2.1]
speaker = "valen"
portrait = "think"
local = "So much good cheer, so many old stories..."
next = "2"

[wedding_valen_2.2]
speaker = "valen"
portrait = "neutral"
local = "I never thought I could be so happy."
next = "3"

[wedding_valen_2.3]
speaker = "valen"
portrait = "embarrassed"
local = "It seems that all my dreams have come true..."
prompts = [
    { local = "Funny, all my dreams have come true, too.", next = "4" },
    { local = "We'll just have to come up with some new dreams then!", next = "5" }
]

[wedding_valen_2.4]
speaker = "valen"
portrait = "happy_blush"
local = "Then we're agreed. All that's left is to live happily ever after."
next = "6"

[wedding_valen_2.5]
speaker = "valen"
portrait = "happy_blush"
local = "I'm excited just thinking about the possibilities!"
next = "6"

[wedding_valen_2.6]
speaker = "valen"
portrait = "embarrassed"
local = "We have so much to look forward to..."
next = "7"

[wedding_valen_2.7]
speaker = "valen"
portrait = "caring_special"
local = "Well, shall we head inside?"
