# wedding
[wedding_ryis_0]
kind = "gameplay_triggered"
speaker = "ryis"
portrait = "embarrassed"
local = "Wow, [Ari]..."
next = "1"

[wedding_ryis_0.1]
speaker = "ryis"
portrait = "starry_eyed"
local = "You look amazing."
prompts = [{ local = "You look so dashing...", next = "2" }, { local = "Thank you.", next = "7" }]

[wedding_ryis_0.2]
speaker = "ryis"
portrait = "think"
local = "Aw, you think so?"
next = "3"

[wedding_ryis_0.3]
speaker = "ryis"
portrait = "blush_special"
local = "I wanted to look good for you."
next = "4"

[wedding_ryis_0.4]
speaker = "ryis"
portrait = "happy_blush"
local = "Glad I pass muster."
next = "5"

[wedding_ryis_0.5]
speaker = "ryis"
portrait = "think"
local = "You, though... you look great."
next = "6"

[wedding_ryis_0.6]
speaker = "ryis"
portrait = "embarrassed"
local = "I saw you, and my heart got wings."
next = "11"

[wedding_ryis_0.7]
speaker = "ryis"
portrait = "blush_special"
local = "Just... look at me a second. I want to fix this in my memory forever."
next = "8"

[wedding_ryis_0.8]
speaker = "ryis"
portrait = "embarrassed"
local = "..."
next = "9"

[wedding_ryis_0.9]
speaker = "ryis"
portrait = "happy_blush"
local = "You seriously look great."
next = "10"

[wedding_ryis_0.10]
speaker = "ryis"
portrait = "blush_special"
local = "I saw you, and my heart got wings."
next = "11"

[wedding_ryis_0.11]
speaker = "elsie"
portrait = "happy"
local = "A couple that flirts at the altar... be still, my heart! Come now, let's start the ceremony."
next = "12"

[wedding_ryis_0.12]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "13"

[wedding_ryis_0.13]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Ryis and [Ari], as they join their light in matrimony."
next = "14"

[wedding_ryis_0.14]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two brilliant souls-"
next = "15"

[wedding_ryis_0.15]
speaker = "elsie"
portrait = "neutral"
local = "Caretakers of home and hearth, illuminating this land with their light."
next = "16"

[wedding_ryis_0.16]
speaker = "elsie"
portrait = "embarrassed"
local = "Standing shoulder to shoulder, destined to build a life together."
next = "17"

[wedding_ryis_0.17]
speaker = "elsie"
portrait = "happy"
local = "Ryis, [Ari], if you would..."
next = "18"

[wedding_ryis_0.18]
speaker = "elsie"
portrait = "neutral"
local = "Please go ahead and light your candles."
next = "19"

[wedding_ryis_0.19]
speaker = "ryis"
portrait = "embarrassed"
local = "[Ari]..."
next = "20"

[wedding_ryis_0.20]
speaker = "ryis"
portrait = "starry_eyed"
local = "Your light's more beautiful than a Mistrian morning."
prompts = [
	{ local = "Your light is so sweet and strong.", next = "21" },
	{ local = "You're my morning sun, Ryis.", next = "21" }
]

[wedding_ryis_0.21]
speaker = "ryis"
portrait = "embarrassed"
local = "[Ari]..."
next = "22"

[wedding_ryis_0.22]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "23"

[wedding_ryis_0.23]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are positively radiant!"
next = "24"

[wedding_ryis_0.24]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "25"

[wedding_ryis_0.25]
speaker = "ryis"
portrait = "neutral"
local = "[Ari]... you're the light in everything."
next = "26"

[wedding_ryis_0.26]
speaker = "ryis"
portrait = "closed_eyes_smile_blush"
local = "I see you in the sun and the moon. I see you in the river's glint, and the dappled trees."
next = "27"

[wedding_ryis_0.27]
speaker = "ryis"
portrait = "blush_special"
local = "I promise to shelter that light, one day at a time, with everything I am."
next = "28"

[wedding_ryis_0.28]
speaker = "ryis"
portrait = "neutral"
local = "I can't wait to build a shining future with you."
prompts = [
	{ local = "I love you, Ryis.", next = "29" },
	{ local = "You lit a flame for me, so I could fly home to you.", next = "30" }
]

[wedding_ryis_0.29]
speaker = "ryis"
portrait = "blush_special"
local = "I love you, [Ari]."
next = "31"

[wedding_ryis_0.30]
speaker = "ryis"
portrait = "starry_eyed"
local = "I love you, [Ari]."
next = "31"

[wedding_ryis_0.31]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "32"

[wedding_ryis_0.32]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "33"

[wedding_ryis_0.33]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "34"

[wedding_ryis_0.34]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception


[wedding_ryis_1]
kind = "gameplay_triggered"
speaker = "wynne"
portrait = "neutral"
local = "Family and friends new and old... I'm so happy to see you all!"
next = "1"

[wedding_ryis_1.1]
speaker = "wynne"
portrait = "wink"
local = "I'm Wynne, and I'd like to propose a toast for my baby brother on the day of his wedding."
next = "2"

[wedding_ryis_1.2]
speaker = "wynne"
portrait = "think"
local = "When I was little, my sister and I begged my parents for a brother every day..."
next = "3"

[wedding_ryis_1.3]
speaker = "darren"
portrait = "happy"
effect = "drop"
local = "And as their father, let me just say that it's a bit more difficult than baking a loaf of bread."
next = "4"

[wedding_ryis_1.4]
speaker = "wynne"
portrait = "wink"
effect = "sparkles"
local = "It worked, didn't it? You're welcome for being born, Ryis!"
next = "5"

[wedding_ryis_1.5]
speaker = "darren"
portrait = "neutral"
local = "Call me biased, but Ryis is basically the kindest, most helpful son you could ask for."
next = "6"

[wedding_ryis_1.6]
speaker = "darren"
portrait = "think"
local = "We were always trying to spoil him, especially his sisters, but we never could. He always wanted to help out."
next = "7"

[wedding_ryis_1.7]
speaker = "darren"
portrait = "closed_eyes"
local = "That's also part of why he came to Mistria. He heard my brother, Landen, needed a hand around the shop... and he wanted to make a difference."
next = "8"

[wedding_ryis_1.8]
speaker = "darren"
portrait = "sad"
local = "I was sad, but... man, I was so proud to see him step up like that."
next = "9"

[wedding_ryis_1.9]
speaker = "wynne"
portrait = "sad"
local = "When I heard, I bawled my eyes out. Baby Ryis was leaving? With no sisters to look out for him?"
next = "10"

[wedding_ryis_1.10]
speaker = "wynne"
portrait = "ugh"
local = "I was sooo depressed. Like seriously depressed, guys."
next = "11"

[wedding_ryis_1.11]
speaker = "wynne"
portrait = "happy"
local = "But then his letters started coming in, and I relaxed a little. He was getting by okay."
next = "12"

[wedding_ryis_1.12]
speaker = "wynne"
portrait = "think"
local = "And then he started writing us about someone new who came to town."
next = "13"

[wedding_ryis_1.13]
speaker = "wynne"
portrait = "wink"
local = "And... listen, I'm his big sister. I can read between the lines. I KNOW a crush when I see one."
next = "14"

[wedding_ryis_1.14]
speaker = "wynne"
portrait = "think"
local = "And after a few more letters, I couldn't even be sad anymore."
next = "15"

[wedding_ryis_1.15]
speaker = "wynne"
portrait = "neutral"
local = "I realized that Ryis was meant to make his way to Mistria..."
next = "16"

[wedding_ryis_1.16]
speaker = "wynne"
portrait = "happy"
local = "He was meant to meet you, [Ari]."
next = "17"

[wedding_ryis_1.17]
speaker = "darren"
portrait = "happy"
local = "Let's raise a glass to that. Welcome to the family, [Ari]!"
next = "18"

[wedding_ryis_1.18]
speaker = "wynne"
portrait = "happy"
effect = "cheery"
local = "Welcome to the family!"
next = "19"

[wedding_ryis_1.19]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."


# outside the house
[wedding_ryis_2]
kind = "gameplay_triggered"
speaker = "ryis"
portrait = "closed_eyes_smile_blush"
local = "What an unreal day..."
next = "1"

[wedding_ryis_2.1]
speaker = "ryis"
portrait = "neutral"
local = "I'm so happy you could meet my dad."
next = "2"

[wedding_ryis_2.2]
speaker = "ryis"
portrait = "happy_blush"
local = "And Wynne. They're crazy about you!"
next = "3"

[wedding_ryis_2.3]
speaker = "ryis"
portrait = "embarrassed"
local = "And now... you and I are family, too, [Ari]. We get to have a home together."
next = "4"

[wedding_ryis_2.4]
speaker = "ryis"
portrait = "blush_special"
local = "I'm so happy."
prompts = [{ local = "Me too, Ryis.", next = "5" }, { local = "Welcome home, Ryis.", next = "5" }]

[wedding_ryis_2.5]
speaker = "ryis"
portrait = "starry_eyed"
local = "[Ari]..."
next = "6"

[wedding_ryis_2.6]
speaker = "ryis"
portrait = "thoughtful_blush"
local = "It's getting late... should we call it?"
next = "7"

[wedding_ryis_2.7]
speaker = "ryis"
portrait = "blush_special"
local = "Tomorrow we'll wake up to birdsong, and to the rest of our lives together."
