# wedding
[wedding_hayden_0]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "embarrassed"
local = "[Ari]! H-hey. Happy... happy wedding... day."
next = "1"

[wedding_hayden_0.1]
speaker = "hayden"
portrait = "shy_special"
local = "Ahem! Sorry, got a bit nervous there!"
prompts = [
    { local = "Hayden, you look incredible!", next = "2" },
    { local = "Your hair's tied up! I like it.", next = "4" }
]

[wedding_hayden_0.2]
speaker = "hayden"
portrait = "embarrassed"
local = "Aww, shucks."
next = "3"

[wedding_hayden_0.3]
speaker = "hayden"
portrait = "neutral"
local = "Hemlock and Holt swung by this morning and helped me with the suit, even took care of the animals for me!"
next = "6"

[wedding_hayden_0.4]
speaker = "hayden"
portrait = "embarrassed"
local = "Aww, shucks."
next = "5"

[wedding_hayden_0.5]
speaker = "hayden"
portrait = "neutral"
local = "Hemlock and Holt swung by this morning and helped me with it, even took care of the animals for me!"
next = "6"

[wedding_hayden_0.6]
speaker = "hayden"
portrait = "confident_blush"
local = "I'm glad you like it..."
next = "7"

[wedding_hayden_0.7]
speaker = "hayden"
portrait = "embarrassed"
local = "And you look magnificent yourself."
next = "8"

[wedding_hayden_0.8]
speaker = "elsie"
portrait = "happy"
local = "You both look wonderful, dears. Now, if you're ready... shall we begin the ceremony?"
next = "9"

[wedding_hayden_0.9]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "10"

[wedding_hayden_0.10]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Hayden and [Ari], as they join their light in matrimony."
next = "11"

[wedding_hayden_0.11]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two radiant souls-"
next = "12"

[wedding_hayden_0.12]
speaker = "elsie"
portrait = "neutral"
local = "Stewards to the land of Mistria, ushering forth its bounty with the warmth of their light."
next = "13"

[wedding_hayden_0.13]
speaker = "elsie"
portrait = "embarrassed"
local = "Destined to shine as one, to share this lifetime together."
next = "14"

[wedding_hayden_0.14]
speaker = "elsie"
portrait = "happy"
local = "Hayden, [Ari], if you would..."
next = "15"

[wedding_hayden_0.15]
speaker = "elsie"
portrait = "neutral"
local = "Please go ahead and light your candles."
next = "16"

[wedding_hayden_0.16]
speaker = "hayden"
portrait = "neutral"
local = "[Ari]..."
next = "17"

[wedding_hayden_0.17]
speaker = "hayden"
portrait = "happy_arm_down"
local = "Your light... It's like the glow of dawn! I feel as if I'm wrapped up in it."
prompts = [
    { local = "So is yours. It's filling me with warmth...", next = "18" },
    { local = "Yours too! It's burning so steadily!", next = "18" }
]

[wedding_hayden_0.18]
speaker = "hayden"
portrait = "confident_blush"
local = "..."
next = "19"

[wedding_hayden_0.19]
speaker = "elsie"
portrait = "happy"
local = "My, my."
next = "20"

[wedding_hayden_0.20]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are brilliant indeed!"
next = "21"

[wedding_hayden_0.21]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "22"

[wedding_hayden_0.22]
speaker = "hayden"
portrait = "embarrassed"
local = "[Ari], your light fills a lonesome place in my heart that I never realized was made to hold it."
next = "23"

[wedding_hayden_0.23]
speaker = "hayden"
portrait = "think"
local = "I bask in the warmth of your glow... So does this land, its people and its animals..."
next = "24"

[wedding_hayden_0.24]
speaker = "hayden"
portrait = "gloomy"
local = "You are the sun in my sky. The love of my life. My family."
next = "25"

[wedding_hayden_0.25]
speaker = "hayden"
portrait = "confident_blush"
local = "I want nothing more than to spend the rest of my days with you."
prompts = [
    { local = "I love you, Hayden, and I want the same thing.", next = "26" },
    { local = "I love you, Hayden. You're my family, too.", next = "26" }
]

[wedding_hayden_0.26]
speaker = "hayden"
portrait = "embarrassed"
local = "[Ari]..."
next = "27"

[wedding_hayden_0.27]
speaker = "hayden"
portrait = "confident_blush"
local = "I love you too."
next = "28"

[wedding_hayden_0.28]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "29"

[wedding_hayden_0.29]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "30"

[wedding_hayden_0.30]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "31"

[wedding_hayden_0.31]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception
[wedding_hayden_1]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "happy"
local = "Hear hear, if I could request everyone's attention for a moment!"
next = "1"

[wedding_hayden_1.1]
speaker = "valen"
portrait = "neutral"
local = "I would like to make a toast to the happy couple."
next = "2"

[wedding_hayden_1.2]
speaker = "valen"
portrait = "happy"
local = "To Hayden, one of my oldest friends. Caring. Generous. Full of laughter..."
next = "3"

[wedding_hayden_1.3]
speaker = "hayden"
portrait = "happy_arm_down"
local = "Gya ha ha!"
next = "4"

[wedding_hayden_1.4]
speaker = "valen"
portrait = "think_smile"
local = "And to [Ari]..."
next = "5"

[wedding_hayden_1.5]
speaker = "valen"
portrait = "neutral"
local = "It's hard to imagine a Mistria without you. You've had such an impact on this town and its people."
next = "6"

[wedding_hayden_1.6]
speaker = "valen"
portrait = "think_smile"
local = "I've seen for myself just how much Hayden has opened up with you by his side."
next = "7"

[wedding_hayden_1.7]
speaker = "valen"
portrait = "embarrassed"
local = "I am so happy to call you both my friends."
next = "8"

[wedding_hayden_1.8]
speaker = "valen"
portrait = "neutral"
local = "Now let's all raise our glasses! To the newlyweds!"
next = "9"

[wedding_hayden_1.9]
speaker = "valen"
portrait = "happy"
effect = "cheery"
local = "Cheers!"
next = "10"

[wedding_hayden_1.10]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_hayden_2]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "neutral"
local = "What a day! I haven't laughed that much in ages."
next = "1"

[wedding_hayden_2.1]
speaker = "hayden"
portrait = "happy_arm_down"
local = "Why, we ought to get married more often!"
next = "2"

[wedding_hayden_2.2]
speaker = "hayden"
portrait = "think"
local = "..."
next = "3"

[wedding_hayden_2.3]
speaker = "hayden"
portrait = "neutral"
local = "Feels a bit odd, don't it? Everything's changed, and yet... I've never felt more content or more comfortable."
next = "4"

[wedding_hayden_2.4]
speaker = "hayden"
portrait = "embarrassed"
local = "I suppose that's what love is all about, huh?"
prompts = [
    { local = "We've got the rest of our lives together to find out.", next = "5" },
    { local = "I couldn't agree more!", next = "6" }
]

[wedding_hayden_2.5]
speaker = "hayden"
portrait = "neutral"
local = "Now ain't that a wonderful thought!"
next = "7"

[wedding_hayden_2.6]
speaker = "hayden"
portrait = "neutral"
local = "I'm glad you feel the same way."
next = "7"

[wedding_hayden_2.7]
speaker = "hayden"
portrait = "happy_arm_down"
local = "You know, as late as it is, I'm still full of vim and vigor!"
next = "8"

[wedding_hayden_2.8]
speaker = "hayden"
portrait = "embarrassed"
local = "Though I don't mind telling you that the sooner I'm out of this starchy suit, the happier I'll be."
next = "9"

[wedding_hayden_2.9]
speaker = "hayden"
portrait = "confident_blush"
local = "Let's call it a night, shall we?"
