# wedding
[wedding_reina_0]
kind = "gameplay_triggered"
speaker = "reina"
portrait = "neutral"
local = "[Ari], ooh, you look so good!"
next = "1"

[wedding_reina_0.1]
speaker = "reina"
portrait = "blush_think"
local = "Mom said Louis went all out for our wedding..."
next = "2"

[wedding_reina_0.2]
speaker = "reina"
portrait = "happy"
local = "What do you think of the dress he made for me?"
prompts = [
    { local = "It's a dream! And so is the woman wearing it.", next = "3" },
    { local = "You take my breath away.", next = "3" }
]

[wedding_reina_0.3]
speaker = "reina"
portrait = "embarrassed"
local = "You charmer!"
next = "4"

[wedding_reina_0.4]
speaker = "reina"
portrait = "neutral"
local = "I'm glad I picked it then. Hehe!"
next = "5"

[wedding_reina_0.5]
speaker = "elsie"
portrait = "happy"
local = "My, aren't you two sweet? Now, if you're ready... shall we begin the ceremony?"
next = "6"

[wedding_reina_0.6]
speaker = "elsie"
portrait = "happy"
local = "Ahem."
next = "7"

[wedding_reina_0.7]
speaker = "elsie"
portrait = "neutral"
local = "Welcome, one and all. We are gathered here today to celebrate the union of Reina and [Ari], as they join their light in matrimony."
next = "8"

[wedding_reina_0.8]
speaker = "elsie"
portrait = "closed_eyes"
local = "Two radiant souls-"
next = "9"

[wedding_reina_0.9]
speaker = "elsie"
portrait = "neutral"
local = "Sharing in a bright vision of Mistria's future, in which its best qualities are appreciated by all..."
next = "10"

[wedding_reina_0.10]
speaker = "elsie"
portrait = "embarrassed"
local = "Destined to shine as one, to spend this lifetime together."
next = "11"

[wedding_reina_0.11]
speaker = "elsie"
portrait = "happy"
local = "Reina, [Ari], if you would..."
next = "12"

[wedding_reina_0.12]
speaker = "elsie"
portrait = "neutral"
local = "Please light your candles."
next = "13"

[wedding_reina_0.13]
speaker = "reina"
portrait = "neutral"
local = "[Ari]..."
next = "14"

[wedding_reina_0.14]
speaker = "reina"
portrait = "happy"
local = "Your light... It feels like home! Like the soft glow of a hearth..."
prompts = [
    { local = "So does yours. It's filling me with warmth...", next = "15" },
    { local = "Yours too! It's burning so intently!", next = "15" }
]

[wedding_reina_0.15]
speaker = "reina"
portrait = "happy"
local = "..."
next = "16"

[wedding_reina_0.16]
speaker = "elsie"
portrait = "happy"
local = "How wonderful."
next = "17"

[wedding_reina_0.17]
speaker = "elsie"
portrait = "wink"
local = "Your feelings for each other are brilliant indeed!"
next = "18"

[wedding_reina_0.18]
speaker = "elsie"
portrait = "neutral"
local = "Now, it is time for the joining."
next = "19"

[wedding_reina_0.19]
speaker = "reina"
portrait = "closed_eyes_smile_blush"
local = "[Ari]..."
next = "20"

[wedding_reina_0.20]
speaker = "reina"
portrait = "neutral"
local = "Your light illuminates the path ahead of me when the way feels murky."
next = "21"

[wedding_reina_0.21]
speaker = "reina"
portrait = "blush_think"
local = "You have stayed with me, supporting me wholeheartedly on the road to achieving my dreams."
next = "22"

[wedding_reina_0.22]
speaker = "reina"
portrait = "embarrassed"
local = "You inspire me to keep going, to never stop striving for the future I envision."
next = "23"

[wedding_reina_0.23]
speaker = "reina"
portrait = "blush_open_eyes"
local = "And in that future... you are always by my side."
prompts = [
    { local = "I love you, Reina. I want the same thing.", next = "24" },
    { local = "I love you, Reina. You inspire me, every day.", next = "25" }
]

[wedding_reina_0.24]
speaker = "reina"
portrait = "embarrassed"
local = "Oh [Ari]..."
next = "26"

[wedding_reina_0.25]
speaker = "reina"
portrait = "embarrassed"
local = "[Ari]..."
next = "26"

[wedding_reina_0.26]
speaker = "reina"
portrait = "blush_open_eyes"
local = "I love you too."
next = "27"

[wedding_reina_0.27]
speaker = "elsie"
portrait = "happy"
local = "By the power vested in me by the Kingdom of Aldaria..."
next = "28"

[wedding_reina_0.28]
speaker = "elsie"
portrait = "neutral"
effect = "cheery"
local = "I now pronounce you married!"
next = "29"

[wedding_reina_0.29]
speaker = "elsie"
portrait = "embarrassed"
local = "May the love and joy of your union illuminate your lives forevermore."
next = "30"

[wedding_reina_0.30]
speaker = "elsie"
portrait = "happy"
local = "Congratulations!"

# reception
[wedding_reina_1]
kind = "gameplay_triggered"
speaker = "josephine"
portrait = "neutral"
local = "Ahem! I would like to make a toast."
next = "1"

[wedding_reina_1.1]
speaker = "josephine"
portrait = "happy"
local = "My fellow Mistrians... Thank you for joining us today, to celebrate the marriage of our daughter, Reina."
next = "2"

[wedding_reina_1.2]
speaker = "josephine"
portrait = "neutral"
local = "It is an honor to officially welcome you to the family, [Ari]!"
next = "3"

[wedding_reina_1.3]
speaker = "josephine"
portrait = "embarrassed"
local = "Though to be honest, I've considered you part of it for some time already-"
next = "4"

[wedding_reina_1.4]
speaker = "josephine"
portrait = "happy"
local = "I just knew the two of you would end up together."
next = "5"

[wedding_reina_1.5]
speaker = "josephine"
portrait = "neutral"
local = "Why I still remember what you said to me, Reina, that first spring [Ari] moved here-"
next = "6"

[wedding_reina_1.6]
speaker = "reina"
portrait = "embarrassed"
local = "Maaa!"
next = "7"

[wedding_reina_1.7]
speaker = "reina"
portrait = "blush_open_eyes"
local = "Can we maybe save that story for another time?"
next = "8"

[wedding_reina_1.8]
speaker = "josephine"
portrait = "wink"
local = "Alright, alright. I'll leave it there."
next = "9"

[wedding_reina_1.9]
speaker = "josephine"
portrait = "happy"
local = "Hemlock, dear, over to you!"
next = "10"

[wedding_reina_1.10]
speaker = "hemlock"
portrait = "happy"
local = "Seriously though, me and your mom couldn't be happier."
next = "11"

[wedding_reina_1.11]
speaker = "hemlock"
portrait = "neutral"
local = "[Ari], thank you for always being there for Reina..."
next = "12"

[wedding_reina_1.12]
speaker = "hemlock"
portrait = "happy"
local = "I hope you know you can count on us in the future."
next = "13"

[wedding_reina_1.13]
speaker = "hemlock"
portrait = "embarrassed"
local = "You are truly part of our family. We are delighted to celebrate this special day with you both."
next = "14"

[wedding_reina_1.14]
speaker = "reina"
portrait = "embarrassed"
local = "Pa..."
next = "15"

[wedding_reina_1.15]
speaker = "hemlock"
portrait = "happy"
local = "Cheers! To the newly married couple!"
next = "16"

[wedding_reina_1.16]
speaker = "maple"
portrait = "happy"
local = "Cheers to mom letting me take over Reina's old room, expanding my territory twofold!"
next = "17"

[wedding_reina_1.17]
speaker = "luc"
portrait = "embarrassed"
local = "Cheers to letting me hunt for bugs on [farm_name]!"
next = "18"

[wedding_reina_1.18]
speaker = "josephine"
portrait = "happy"
local = "To a lifetime of happiness for you both!"
next = "19"

[wedding_reina_1.19]
no_speaker = true
local = "You spent the rest of the evening enjoying the celebration together..."

# outside the house
[wedding_reina_2]
kind = "gameplay_triggered"
speaker = "reina"
portrait = "happy"
local = "That was sooo much fun! Everything was exactly how I imagined it would be!"
next = "1"

[wedding_reina_2.1]
speaker = "reina"
portrait = "neutral"
local = "The company, the music, the food..."
next = "2"

[wedding_reina_2.2]
speaker = "reina"
portrait = "embarrassed"
local = "I'll remember this day for the rest of my life."
next = "3"

[wedding_reina_2.3]
speaker = "reina"
portrait = "blush_open_eyes"
local = "The perfect day when I married my perfect person."
prompts = [
    { local = "I'm so happy, Reina.", next = "4" },
    { local = "I can't wait to spend every day with you.", next = "5" }
]

[wedding_reina_2.4]
speaker = "reina"
portrait = "embarrassed"
local = "I couldn't be happier, [Ari]!"
next = "6"

[wedding_reina_2.5]
speaker = "reina"
portrait = "embarrassed"
local = "Oh [Ari]... I feel the same way."
next = "6"

[wedding_reina_2.6]
speaker = "reina"
portrait = "neutral"
local = "To think, we have the rest of our lives to look forward to..."
next = "7"

[wedding_reina_2.7]
speaker = "reina"
portrait = "blush_think"
local = "But for now, should we head inside?"
next = "8"

[wedding_reina_2.8]
speaker = "reina"
portrait = "embarrassed"
local = "I... I think I might need a little help getting out this dress."
