game_stats_key = "items_forged"
skill = "blacksmithing"
stat_one = "defense"
stat_two = "damage"
preview_y_offset = -18
use_common_slice = true
context = "blacksmithing"
open_to_index = 0
corner_tier = false

[sprites]
	backplate = "spr_ui_blacksmithing_backplate"
	text_lut = "spr_ui_blacksmithing_text_lut"
	scroller_lut = "spr_ui_blacksmithing_scroller_lut"
	craft_icon = "spr_ui_blacksmithing_craft_icon"
	button_lut = "spr_ui_blacksmithing_button_lut"
	button_label_lut = "spr_ui_blacksmithing_button_text_lut"
	button_label_invalid_lut = "spr_ui_blacksmithing_button_invalid_text_lut"
	left_arrow = "spr_ui_blacksmithing_left_arrow"
	right_arrow = "spr_ui_blacksmithing_right_arrow"
	clock = "spr_ui_blacksmithing_clock_icon"
	window = "spr_ui_blacksmithing_carousel_window"
	lock = "spr_ui_blacksmithing_lock_icon"
	category_header = "spr_ui_blacksmithing_header_box"
	scroller_outline = "spr_ui_blacksmithing_outline_box"
	stat_one_icon = "spr_ui_tooltip_defense_icon"
	stat_two_icon = "spr_ui_tooltip_attack_icon"
	corner_plate = "spr_ui_blacksmithing_upper_corner_backplate"

### Ingots
[[categories]]
	name = "Ingots"
	icon = "spr_ui_blacksmithing_category_icon_ingots"

	[[categories.sub_categories]]
		name = "Ingots"
		icon = "spr_ui_blacksmithing_category_icon_ingots"
		manual_order = ["copper_ingot", "iron_ingot", "silver_ingot", "gold_ingot", "mistril_ingot"]

### Pickaxes
[[categories]]
	name = "Pickaxes"
	icon = "spr_ui_blacksmithing_category_icon_pickaxes"

	[[categories.sub_categories]]
		name = "Pickaxes"
		icon = "spr_ui_blacksmithing_category_icon_pickaxes"
		manual_order = ["pick_axe_copper", "pick_axe_iron", "pick_axe_silver", "pick_axe_gold", "pick_axe_mistril"]

### Axes
[[categories]]
	name = "Axes"
	icon = "spr_ui_blacksmithing_category_icon_axes"

	[[categories.sub_categories]]
		name = "Axes"
		icon = "spr_ui_blacksmithing_category_icon_axes"
		manual_order = ["axe_copper", "axe_iron", "axe_silver", "axe_gold", "axe_mistril"]


### Hoes
[[categories]]
	name = "Hoes"
	icon = "spr_ui_blacksmithing_category_icon_hoes"

	[[categories.sub_categories]]
		name = "Hoes"
		icon = "spr_ui_blacksmithing_category_icon_hoes"
		manual_order = ["hoe_copper", "hoe_iron", "hoe_silver", "hoe_gold", "hoe_mistril"]


### Watering Cans
[[categories]]
	name = "Watering Cans"
	icon = "spr_ui_blacksmithing_category_icon_watering_cans"

	[[categories.sub_categories]]
		name = "Watering Cans"
		icon = "spr_ui_blacksmithing_category_icon_watering_cans"
		manual_order = ["watering_can_copper", "watering_can_iron", "watering_can_silver", "watering_can_gold", "watering_can_mistril"]


### Fishing Rods
[[categories]]
	name = "Fishing Rods"
	icon = "spr_ui_blacksmithing_category_icon_rods"

	[[categories.sub_categories]]
		name = "Fishing Rods"
		icon = "spr_ui_blacksmithing_category_icon_rods"
		manual_order = ["fishing_rod_copper", "fishing_rod_iron", "fishing_rod_silver", "fishing_rod_gold", "fishing_rod_mistril"]

### Shovels
[[categories]]
	name = "Shovels"
	icon = "spr_ui_blacksmithing_category_icon_shovels"

	[[categories.sub_categories]]
		name = "Shovels"
		icon = "spr_ui_blacksmithing_category_icon_shovels"
		manual_order = ["shovel_copper", "shovel_iron", "shovel_silver", "shovel_gold", "shovel_mistril"]

### Bug Nets
[[categories]]
	name = "Bug Nets"
	icon = "spr_ui_blacksmithing_category_icon_nets"

	[[categories.sub_categories]]
		name = "Bug Nets"
		icon = "spr_ui_blacksmithing_category_icon_nets"
		manual_order = ["net_copper", "net_iron", "net_silver", "net_gold", "net_mistril"]

### Swords
[[categories]]
	name = "Swords"
	icon = "spr_ui_blacksmithing_category_icon_swords"

	[[categories.sub_categories]]
		name = "Swords"
		icon = "spr_ui_blacksmithing_category_icon_swords"
		manual_order = ["sword_copper", "sword_iron", "sword_silver", "sword_gold", "sword_mistril"]

## Armor
[[categories]]
	name = "Armor"
	icon = "spr_ui_blacksmithing_category_icon_armor"

	[[categories.sub_categories]]
		name = "Armor"
		icon = "spr_ui_blacksmithing_category_icon_armor"
		manual_order = [
			"copper_helmet",
			"copper_armor",
			"copper_ring",
			"copper_legplates",
			"copper_greaves",

			"iron_helmet",
			"iron_armor",
			"iron_ring",
			"iron_legplates",
			"iron_greaves",

			"silver_helmet",
			"silver_armor",
			"silver_ring",
			"silver_legplates",
			"silver_greaves",

			"gold_helmet",
			"gold_armor",
			"gold_ring",
			"gold_legplates",
			"gold_greaves",

			"mistril_helmet",
			"mistril_armor",
			"mistril_ring",
			"mistril_legplates",
			"mistril_boots",
		]

## Engagement Ring
[[categories]]
	name = "Special"
	icon = "spr_ui_blacksmithing_category_icon_special"

	[[categories.sub_categories]]
	name = "Special"
	icon = "spr_ui_blacksmithing_category_icon_special"
	manual_order = [
		"engagement_ring",
	]