game_stats_key = "items_cooked"
skill = "cooking"
stat_one = "health_modifier"
stat_two = "stamina_modifier"
preview_y_offset = -18
use_common_slice = true
context = "cooking"
open_to_index = 0
corner_tier = true

[sprites]
	backplate = "spr_ui_cooking_backplate"
	text_lut = "spr_ui_cooking_text_lut"
	# scroller_lut = "spr_ui_cooking_scroller_lut"
	craft_icon = "spr_ui_cooking_craft_icon"
	button_lut = "spr_ui_cooking_button_lut"
	button_label_lut = "spr_ui_cooking_button_text_lut"
	button_label_invalid_lut = "spr_ui_cooking_button_invalid_text_lut"
	left_arrow = "spr_ui_cooking_left_arrow"
	right_arrow = "spr_ui_cooking_right_arrow"
	clock = "spr_ui_cooking_clock_icon"
	window = "spr_ui_cooking_carousel_window"
	lock = "spr_ui_cooking_lock_icon"
	category_header = "spr_ui_cooking_header_box"
	scroller_outline = "spr_ui_cooking_outline_box"
	stat_one_icon = "spr_ui_hud_health_health_bar_icon_normal_health"
	stat_two_icon = "spr_ui_hud_health_stamina_bar_icon_good"
	corner_plate = "spr_ui_cooking_upper_corner_backplate"

### Pantry
[[categories]]
	name = "Pantry"
	icon = "spr_ui_cooking_category_icon_pantry"

	[[categories.sub_categories]]
		name = "Dairy"
		icon = "spr_ui_cooking_category_icon_dairy"
		tags = ["dairy"]

	[[categories.sub_categories]]
		name = "Jams"
		icon = "spr_ui_cooking_category_icon_jam"
		tags = ["jam"]

	[[categories.sub_categories]]
		name = "Sauces & Condiments"
		icon = "spr_ui_cooking_category_icon_sauce_and_condiment"
		tags = ["sauce_and_condiment"]

	[[categories.sub_categories]]
		name = "Pickles & Fermenting"
		icon = "spr_ui_cooking_category_icon_pickle_and_fermenting"
		tags = ["pickle_and_fermenting"]

	[[categories.sub_categories]]
		name = "Miscellaneous"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_pantry"]

### Snacks
[[categories]]
	name = "Snacks"
	icon = "spr_ui_cooking_category_icon_snacks"

	[[categories.sub_categories]]
		name = "Snacks"
		icon = "spr_ui_cooking_category_icon_snacks"
		tags = ["snack"]

### Salads
[[categories]]
	name = "Salads & Greens"
	icon = "spr_ui_cooking_category_icon_salad"

	[[categories.sub_categories]]
		name = "Salads"
		icon = "spr_ui_cooking_category_icon_salad"
		tags = ["salad"]

	[[categories.sub_categories]]
		name = "Greens"
		icon = "spr_ui_cooking_category_icon_greens"
		tags = ["greens"]

### Soups
[[categories]]
	name = "Soups & Stews"
	icon = "spr_ui_cooking_category_icon_soups"

	[[categories.sub_categories]]
		name = "Soups"
		icon = "spr_ui_cooking_category_icon_soups"
		tags = ["soup"]

	[[categories.sub_categories]]
		name = "Stews"
		icon = "spr_ui_cooking_category_icon_stews"
		tags = ["stew"]

### Main Dishes
[[categories]]
	name = "Main Courses"
	icon = "spr_ui_cooking_category_icon_main_dishes"

	[[categories.sub_categories]]
		name = "Hand Crafted"
		icon = "spr_ui_cooking_category_icon_handcrafted_dish"
		tags = ["hand_crafted_dish"]

	[[categories.sub_categories]]
		name = "Grilled"
		icon = "spr_ui_cooking_category_icon_grilled_dish"
		tags = ["grilled_dish"]

	[[categories.sub_categories]]
		name = "Sauteed"
		icon = "spr_ui_cooking_category_icon_sauteed_dish"
		tags = ["sauteed_dish"]

	[[categories.sub_categories]]
		name = "Fried"
		icon = "spr_ui_cooking_category_icon_fried_dish"
		tags = ["fried_dish"]

	[[categories.sub_categories]]
		name = "Baked"
		icon = "spr_ui_cooking_category_icon_baked_dish"
		tags = ["baked_dish"]

	[[categories.sub_categories]]
		name = "Roasted"
		icon = "spr_ui_cooking_category_icon_roasted_dish"
		tags = ["roasted_dish"]

	[[categories.sub_categories]]
		name = "Steamed"
		icon = "spr_ui_cooking_category_icon_steamed_dish"
		tags = ["steamed_dish"]

	[[categories.sub_categories]]
		name = "Simmered"
		icon = "spr_ui_cooking_category_icon_simmered_dish"
		tags = ["simmered_dish"]

	[[categories.sub_categories]]
		name = "Chilled"
		icon = "spr_ui_cooking_category_icon_chilled_dish"
		tags = ["chilled_dish"]

### Desserts
[[categories]]
	name = "Desserts"
	icon = "spr_ui_cooking_category_icon_desserts"

	[[categories.sub_categories]]
		name = "Hand Crafted"
		icon = "spr_ui_cooking_category_icon_handcrafted_dessert"
		tags = ["hand_crafted_dessert"]

	[[categories.sub_categories]]
		name = "Baked"
		icon = "spr_ui_cooking_category_icon_baked_dessert"
		tags = ["baked_dessert"]

	[[categories.sub_categories]]
		name = "Fried"
		icon = "spr_ui_cooking_category_icon_fried_dessert"
		tags = ["fried_dessert"]

	[[categories.sub_categories]]
		name = "Steamed"
		icon = "spr_ui_cooking_category_icon_steamed_dessert"
		tags = ["steamed_dessert"]

	[[categories.sub_categories]]
		name = "Frozen"
		icon = "spr_ui_cooking_category_icon_frozen_dessert"
		tags = ["frozen_dessert"]

	[[categories.sub_categories]]
		name = "Candy"
		icon = "spr_ui_cooking_category_icon_candy"
		tags = ["candy"]

### Drinks
[[categories]]
	name = "Drinks"
	icon = "spr_ui_cooking_category_icon_drinks"

	[[categories.sub_categories]]
		name = "Cold"
		icon = "spr_ui_cooking_category_icon_cold_drinks"
		tags = ["cold_drink"]

	[[categories.sub_categories]]
		name = "Hot"
		icon = "spr_ui_cooking_category_icon_hot_drinks"
		tags = ["hot_drink"]
