game_stats_key = "items_forged"
skill = "blacksmithing"
stat_one = "defense"
stat_two = "damage"
preview_y_offset = -18
use_common_slice = true
context = "blacksmithing"
open_to_index = 0
corner_tier = false

[sprites]
	backplate = "spr_ui_blacksmithing_backplate"
	text_lut = "spr_ui_blacksmithing_text_lut"
	scroller_lut = "spr_ui_blacksmithing_scroller_lut"
	craft_icon = "spr_ui_blacksmithing_craft_icon"
	button_lut = "spr_ui_blacksmithing_button_lut"
	button_label_lut = "spr_ui_blacksmithing_button_text_lut"
	button_label_invalid_lut = "spr_ui_blacksmithing_button_invalid_text_lut"
	left_arrow = "spr_ui_blacksmithing_left_arrow"
	right_arrow = "spr_ui_blacksmithing_right_arrow"
	clock = "spr_ui_blacksmithing_clock_icon"
	window = "spr_ui_blacksmithing_carousel_window"
	lock = "spr_ui_blacksmithing_lock_icon"
	category_header = "spr_ui_blacksmithing_header_box"
	scroller_outline = "spr_ui_blacksmithing_outline_box"
	stat_one_icon = "spr_ui_tooltip_defense_icon"
	stat_two_icon = "spr_ui_tooltip_attack_icon"
	corner_plate = "spr_ui_blacksmithing_upper_corner_backplate"

### Swords
[[categories]]
	name = "Swords"
	icon = "spr_ui_blacksmithing_category_icon_swords"

	[[categories.sub_categories]]
		name = "Swords"
		icon = "spr_ui_blacksmithing_category_icon_swords"
		manual_order = ["sword_dragon_forged"]

### Materials
[[categories]]
	name = "Materials"
	icon = "spr_ui_blacksmithing_category_icon_materials"

	[[categories.sub_categories]]
		name = "Materials"
		icon = "spr_ui_blacksmithing_category_icon_materials"
		manual_order = [
			"dragon_forged_fang",
			"dragon_forged_horn",
			"dragon_forged_core",
			"dragon_forged_powder",
		]