[lut_indexes]
	body = 1
	title = 1
	count = 4
	cannot_afford = 6
	scroller = 1
	quantity = 1
	craft_button_label = 3
	craft_button_label_invalid = 4
	duration = 5
	duration_invalid = 6
	quantity_neutral = 9
	quantity_valid = 10
	quantity_invalid = 11
	quantity_count_valid = 5
	quantity_count_invalid = 2
	stat_numbers = 7
	category_name = 12

[right_header]
	size = [169, 14]
	position = [-16, 9]

[left_header]
	size = [115, 19]
	position = [31, 5]

[options]
	square_size = 24
	per_row = 6

[category]
	top_padding = 20
	bottom_padding = 8
	icon_offset = [10, 4]
	header_height = 18

[recipe_box]
	position = [0, 0]
	size = [93, 71]
	rows = 2
	columns = 3

[recipe_square]
	size = [29, 29]
	start_pos = [2, 4]
	inc = [30, 33]

[preview_box]
	size = [68, 71]
	position = [101, 0]

[stat_box]
	size = [62, 38]
	position = [104, 30]

[tier_requirement]
	position = [35, 81]

[level_requirement_box]
	position = [0, 76]
	cooking_position = [55, 76] # pain
	size = [38, 15]

[stars]
	position = [115, 76]

[description_box]
	size = [175, 39]
	position = [-3, 98]

[recipe_item]
	box_size = [29, 29]
	position = [0, 1]        # center/top in
	count_position = [0, -2] # center/bottom in

[craft_button]
	size = [44, 38]
	position = [-4, 0] # right/bottom in

[quantity_box]
	size = [27, 14]
	position = [20, -21]

[quantity_text]
	position = [0, 0]

[minus_button]
	size = [20, 20]
	position = [-3, 0]

[minus_icon]
	position = [0, -1]

[plus_button]
	size = [20, 20]
	position = [3, 0]

[plus_icon]
	position = [0, 0]

[max_button]
	size = [30, 20]
	position = [0, 1]

[max_icon]
	position = [0, 0]

[duration_container]
	size = [48, 14]
	position = [-52, -21]

	# [kitchen_level_number]
	# 	position = [-13, 21]
