game_stats_key = "items_refined"
skill = "<n/a>"
stat_one = "<n/a>"
stat_two = "<n/a>"
preview_y_offset = 0
use_common_slice = true
context = "refining"
open_to_index = 0
corner_tier = false

[sprites]
	backplate = "spr_ui_stone_refinery_backplate"
	text_lut = "spr_ui_stone_refinery_text_lut"
	scroller_lut = "spr_ui_stone_refinery_scroller_lut"
	craft_icon = "spr_ui_stone_refinery_craft_icon"
	button_lut = "spr_ui_stone_refinery_button_lut"
	button_label_lut = "spr_ui_stone_refinery_button_text_lut"
	button_label_invalid_lut = "spr_ui_stone_refinery_button_invalid_text_lut"
	left_arrow = "spr_ui_stone_refinery_left_arrow"
	right_arrow = "spr_ui_stone_refinery_right_arrow"
	clock = "spr_ui_stone_refinery_clock_icon"
	window = "spr_ui_stone_refinery_carousel_window"
	lock = "spr_ui_cooking_lock_icon"
	category_header = "spr_ui_stone_refinery_header_box"
	scroller_outline = "spr_ui_stone_refinery_outline_box"

[[categories]]
	name = "Essence Stones"
	icon = "spr_ui_stone_refinery_category_icon_essence_crystals"

	[[categories.sub_categories]]
		name = "Essence Stones"
		icon = "spr_ui_stone_refinery_category_icon_essence_crystals"
		manual_order = ["essence_stone_tiny", "essence_stone_small", "essence_stone_medium", "essence_stone_large", "essence_stone_giant"]

[[categories]]
	name = "Materials"
	icon = "spr_ui_stone_refinery_craft_icon"

	[[categories.sub_categories]]
		name = "Materials"
		icon = "spr_ui_stone_refinery_craft_icon"
		manual_order = [
			"refined_stone",
			"basic_wood",
			"hard_wood",
			"clay",
			"sod",
			"peat",
			"shards",
			"shard_mass",
			"glass",
			"grass_seed",
			"hay",
			"coral",
			"crystal",
			"obsidian",
			"ore_ruby",
			"ore_sapphire",
			"ore_emerald",
			"ore_diamond",
		]
