game_stats_key = "items_woodcrafted"
skill = "woodcrafting"
stat_one = "<n/a>"
stat_two = "<n/a>"
preview_y_offset = 0
use_common_slice = true
context = "woodcrafting"
open_to_index = 2
corner_tier = false

[sprites]
	backplate = "spr_ui_woodcrafting_backplate"
	text_lut = "spr_ui_woodcrafting_text_lut"
	scroller_lut = "spr_ui_woodcrafting_scroller_lut"
	craft_icon = "spr_ui_woodcrafting_craft_icon"
	button_lut = "spr_ui_woodcrafting_button_lut"
	button_label_lut = "spr_ui_woodcrafting_button_text_lut"
	button_label_invalid_lut = "spr_ui_woodcrafting_button_invalid_text_lut"
	left_arrow = "spr_ui_woodcrafting_left_arrow"
	right_arrow = "spr_ui_woodcrafting_right_arrow"
	clock = "spr_ui_woodcrafting_clock_icon"
	window = "spr_ui_woodcrafting_carousel_window"
	lock = "spr_ui_cooking_lock_icon"
	category_header = "spr_ui_woodcrafting_header_box"
	scroller_outline = "spr_ui_woodcrafting_outline_box"
	corner_plate = "spr_ui_woodcrafting_upper_corner_backplate"

### Sets
[[categories]]
	name = "Sets"
	icon = "spr_ui_crafting_category_icon_sets"
	display_in_aggregate = false

	[[categories.sub_categories]]
		name = "Automation Set"
		icon = "spr_ui_woodcrafting_category_icon_automation"
		tags = ["automation"]

	[[categories.sub_categories]]
		name = "All Misc. Functional"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_functional"]

	[[categories.sub_categories]]
		name = "Bakery Decor Set"
		icon = "spr_ui_woodcrafting_category_icon_bakery_decor_set"
		tags = ["bakery_decor_set"]

	[[categories.sub_categories]]
		name = "Basic Chest Set"
		icon = "spr_ui_woodcrafting_category_icon_chest_and_storage"
		tags = ["basic_chest_set"]

	[[categories.sub_categories]]
		name = "Basic Set"
		icon = "spr_ui_woodcrafting_category_icon_basic_set"
		tags = ["basic_set"]

	[[categories.sub_categories]]
		name = "Bathroom Set"
		icon = "spr_ui_woodcrafting_category_icon_bathroom_set"
		tags = ["bathroom_set"]

	[[categories.sub_categories]]
		name = "Cavern Set"
		icon = "spr_ui_woodcrafting_category_icon_deep_earth_set"
		tags = ["cavern_set"]

	[[categories.sub_categories]]
		name = "Cherry Set"
		icon = "spr_ui_woodcrafting_category_icon_cherry_set"
		tags = ["cherry_set"]

	[[categories.sub_categories]]
		name = "Chess Piece Set"
		icon = "spr_ui_woodcrafting_category_icon_chess_set"
		tags = ["chess_decor_set"]

	[[categories.sub_categories]]
		name = "Cooking Set"
		icon = "spr_ui_woodcrafting_category_icon_cooking_set"
		tags = ["cooking_set"]

	[[categories.sub_categories]]
		name = "Cottage Garden Set"
		icon = "spr_ui_item_decor_cottage_garden_planter_v2"
		tags = ["cottage_garden"]

	[[categories.sub_categories]]
		name = "Counter Set"
		icon = "spr_ui_woodcrafting_category_icon_counter"
		tags = ["counter_set"]

	[[categories.sub_categories]]
		name = "Craft Set"
		icon = "spr_ui_woodcrafting_category_icon_craft_set"
		tags = ["craft_set"]

	[[categories.sub_categories]]
		name = "Crop Sign Set (Spring)"
		icon = "spr_ui_woodcrafting_category_icon_spring_sign_set"
		tags = ["spring_sign_set"]

	[[categories.sub_categories]]
		name = "Crop Sign Set (Summer)"
		icon = "spr_ui_woodcrafting_category_icon_summer_sign_set"
		tags = ["summer_sign_set"]

	[[categories.sub_categories]]
		name = "Crop Sign Set (Fall)"
		icon = "spr_ui_woodcrafting_category_icon_fall_sign_set"
		tags = ["fall_sign_set"]

	[[categories.sub_categories]]
		name = "Crop Sign Set (Winter)"
		icon = "spr_ui_woodcrafting_category_icon_winter_sign_set"
		tags = ["winter_sign_set"]

	[[categories.sub_categories]]
		name = "Dragon Claw Altar Set"
		icon = "spr_ui_woodcrafting_category_icon_dragon_altar_set"
		tags = ["dragon_altar_set"]

	[[categories.sub_categories]]
		name = "Emerald Set"
		icon = "spr_ui_woodcrafting_category_icon_emerald_set"
		tags = ["emerald_set"]

	[[categories.sub_categories]]
		name = "Explorer Set"
		icon = "spr_ui_woodcrafting_category_icon_explorer_set"
		tags = ["explorer_set"]

	[[categories.sub_categories]]
		name = "Fall Set"
		icon = "spr_ui_woodcrafting_category_icon_fall_set"
		tags = ["fall_set"]

	[[categories.sub_categories]]
		name = "Faux Spring Plant Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_spring"
		tags = ["faux_spring_plants_set"]

	[[categories.sub_categories]]
		name = "Faux Summer Plant Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_summer"
		tags = ["faux_summer_plants_set"]

	[[categories.sub_categories]]
		name = "Faux Fall Plant Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_fall"
		tags = ["faux_fall_plants_set"]

	[[categories.sub_categories]]
		name = "Faux Winter Plant Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_winter"
		tags = ["faux_winter_plants_set"]

	[[categories.sub_categories]]
		name = "Faux Deep Woods Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_deep_woods"
		tags = ["faux_deep_woods_plants_set"]

	[[categories.sub_categories]]
		name = "Faux Mines Plant Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_mines"
		tags = ["faux_mines_plants_set"]

	[[categories.sub_categories]]
		name = "Faux Shell Set"
		icon = "spr_ui_woodcrafting_category_icon_faux_shell"
		tags = ["faux_shells_set"]

	[[categories.sub_categories]]
		name = "Fishing Set"
		icon = "spr_ui_woodcrafting_category_icon_fishing_set"
		tags = ["fishing_set"]

	[[categories.sub_categories]]
		name = "Haunted Attic Set"
		icon = "spr_ui_woodcrafting_category_icon_haunted_attic_set"
		tags = ["haunted_attic_set"]

	[[categories.sub_categories]]
		name = "Insect Set"
		icon = "spr_ui_woodcrafting_category_icon_insect_set"
		tags = ["insect_set"]

	[[categories.sub_categories]]
		name = "Kitchen Set"
		icon = "spr_ui_woodcrafting_category_icon_kitchen_set"
		tags = ["kitchen_set"]

	[[categories.sub_categories]]
		name = "Lava Caves Set"
		icon = "spr_ui_woodcrafting_category_icon_lava_set"
		tags = ["lava_set"]

	[[categories.sub_categories]]
		name = "Lemon Set"
		icon = "spr_ui_woodcrafting_category_icon_lemon_set"
		tags = ["lemon_set"]

	[[categories.sub_categories]]
		name = "Lovely Cottage Set"
		icon = "spr_ui_woodcrafting_category_icon_lovely_cottage_set"
		tags = ["lovely_cottage_set"]

	[[categories.sub_categories]]
		name = "Mermaid Set"
		icon = "spr_ui_woodcrafting_category_icon_mermaid_set"
		tags = ["mermaid_set"]

	[[categories.sub_categories]]
		name = "Mineshaft Set"
		icon = "spr_ui_woodcrafting_category_icon_mineshaft_set"
		tags = ["mineshaft_set"]

	[[categories.sub_categories]]
		name = "Mistrian History Set"
		icon = "spr_ui_woodcrafting_category_icon_mistrian_history_set"
		tags = ["mistrian_history_set"]

	[[categories.sub_categories]]
		name = "Monster Set"
		icon = "spr_ui_woodcrafting_category_icon_monster_set"
		tags = ["monster_set"]

	[[categories.sub_categories]]
		name = "Ornate Rug Set"
		icon = "spr_ui_woodcrafting_category_icon_ornate_rug_set"
		tags = ["ornate_rug_set"]

	[[categories.sub_categories]]
		name = "Paving Stone Set"
		icon = "spr_ui_woodcrafting_category_icon_paving_stone"
		tags = ["paving_stone_set"]

	[[categories.sub_categories]]
		name = "Picnic Decor Set"
		icon = "spr_ui_woodcrafting_category_icon_picnic_decor_set"
		tags = ["picnic_decor_set"]

	[[categories.sub_categories]]
		name = "Ruins Set"
		icon = "spr_ui_woodcrafting_category_icon_ruins_set"
		tags = ["ruins_set"]

	[[categories.sub_categories]]
		name = "Rustic Cabin Set"
		icon = "spr_ui_woodcrafting_category_icon_rustic_cabin_set"
		tags = ["rustic_cabin_set"]

	[[categories.sub_categories]]
		name = "Shooting Star Set"
		icon = "spr_ui_woodcrafting_category_icon_star_festival"
		tags = ["star_festival_set"]

	[[categories.sub_categories]]
		name = "Spring Set"
		icon = "spr_ui_woodcrafting_category_icon_spring_set"
		tags = ["spring_set"]

	[[categories.sub_categories]]
		name = "Starter Farm Set"
		icon = "spr_ui_woodcrafting_category_icon_starter_farm_set"
		tags = ["starter_farm_set"]

	[[categories.sub_categories]]
		name = "Stone Garden Set"
		icon = "spr_ui_woodcrafting_category_icon_stone_garden_set"
		tags = ["stone_garden_set"]

	[[categories.sub_categories]]
		name = "Summer Set"
		icon = "spr_ui_woodcrafting_category_icon_summer_set"
		tags = ["summer_set"]

	[[categories.sub_categories]]
		name = "Tabletop Clutter Set"
		icon = "spr_ui_woodcrafting_category_icon_tabletop_clutter"
		tags = ["tabletop_clutter"]

	[[categories.sub_categories]]
		name = "Tide Set"
		icon = "spr_ui_woodcrafting_category_icon_tide_caverns_set"
		tags = ["tide_caverns_set"]

	[[categories.sub_categories]]
		name = "Training Dummy Set"
		icon = "spr_ui_woodcrafting_category_icon_training_dummy_decor"
		tags = ["training_dummy_set"]

	[[categories.sub_categories]]
		name = "Void Set"
		icon = "spr_ui_woodcrafting_category_icon_void_set"
		tags = ["void_set"]

	[[categories.sub_categories]]
		name = "Witch Queen Set"
		icon = "spr_ui_woodcrafting_category_icon_witch_queen_set"
		tags = ["witch_queen_set"]

	[[categories.sub_categories]]
		name = "Worn Set"
		icon = "spr_ui_woodcrafting_category_icon_default_set"
		tags = ["default_set"]

### Functional
[[categories]]
	name = "Functional"
	icon = "spr_ui_woodcrafting_category_icon_functional"

	[[categories.sub_categories]]
		name = "Automation"
		icon = "spr_ui_woodcrafting_category_icon_automation"
		tags = ["automation"]

	[[categories.sub_categories]]
		name = "All Misc. Functional"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_functional"]

	[[categories.sub_categories]]
		name = "Calendar"
		icon = "spr_ui_woodcrafting_category_icon_calendar"
		tags = ["calendar"]

	[[categories.sub_categories]]
		name = "Chests & Storage"
		icon = "spr_ui_woodcrafting_category_icon_chest_and_storage"
		tags = ["chest_and_storage"]

	[[categories.sub_categories]]
		name = "Diary"
		icon = "spr_ui_woodcrafting_category_icon_journal"
		tags = ["journal"]


### Farm & Outdoor
[[categories]]
	name = "Farm & Outdoor"
	icon = "spr_ui_woodcrafting_category_icon_farm_and_outdoor"

	[[categories.sub_categories]]
		name = "Crop Signs"
		icon = "spr_ui_woodcrafting_category_icon_crop_signs"
		tags = ["crop_signs"]

	[[categories.sub_categories]]
		name = "Farm"
		icon = "spr_ui_woodcrafting_category_icon_farm_decor"
		tags = ["farm_decor"]

	[[categories.sub_categories]]
		name = "Fencing"
		icon = "spr_ui_woodcrafting_category_icon_fencing"
		tags = ["fencing"]

	[[categories.sub_categories]]
		name = "Garden"
		icon = "spr_ui_woodcrafting_category_icon_garden_decor"
		tags = ["garden_decor"]

	[[categories.sub_categories]]
		name = "Ground"
		icon = "spr_ui_woodcrafting_category_icon_ground_decor"
		tags = ["ground_decor"]

	[[categories.sub_categories]]
		name = "Misc. Outdoor"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_outdoor_decor"]

### Flooring
[[categories]]
	name = "Flooring"
	icon = "spr_ui_woodcrafting_category_icon_flooring"

	[[categories.sub_categories]]
		name = "Carpet"
		icon = "spr_ui_woodcrafting_category_icon_carpet_flooring"
		tags = ["carpet_flooring"]

	[[categories.sub_categories]]
		name = "Misc. Flooring"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_flooring"]

	[[categories.sub_categories]]
		name = "Novelty"
		icon = "spr_ui_woodcrafting_category_icon_novelty_flooring"
		tags = ["novelty_flooring"]

	[[categories.sub_categories]]
		name = "Tile"
		icon = "spr_ui_woodcrafting_category_icon_tile_flooring"
		tags = ["tile_flooring"]

	[[categories.sub_categories]]
		name = "Wood"
		icon = "spr_ui_woodcrafting_category_icon_wood_flooring"
		tags = ["wood_flooring"]


### Wallpaper
[[categories]]
	name = "Wallpaper"
	icon = "spr_ui_woodcrafting_category_icon_wallpaper"

	[[categories.sub_categories]]
		name = "Wallpaper"
		icon = "spr_ui_woodcrafting_category_icon_wallpaper"
		tags = ["wallpaper"]

### Seating
[[categories]]
	name = "Seating"
	icon = "spr_ui_woodcrafting_category_icon_seating"

	[[categories.sub_categories]]
		name = "Accent Chairs"
		icon = "spr_ui_woodcrafting_category_icon_accent_chair"
		tags = ["accent_chair"]


	[[categories.sub_categories]]
		name = "Dining Chairs"
		icon = "spr_ui_woodcrafting_category_icon_dining_chair"
		tags = ["dining_chair"]

	[[categories.sub_categories]]
		name = "Misc. Seating"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_seating"]

	[[categories.sub_categories]]
		name = "Sofas"
		icon = "spr_ui_woodcrafting_category_icon_sofa"
		tags = ["sofa"]

	[[categories.sub_categories]]
		name = "Stools"
		icon = "spr_ui_woodcrafting_category_icon_stool"
		tags = ["stool"]


### Beds
[[categories]]
	name = "Beds"
	icon = "spr_ui_woodcrafting_category_icon_beds"

	[[categories.sub_categories]]
		name = "Double"
		icon = "spr_ui_woodcrafting_category_icon_double_bed"
		tags = ["double_bed"]

	[[categories.sub_categories]]
		name = "Single"
		icon = "spr_ui_woodcrafting_category_icon_single_bed"
		tags = ["single_bed"]


### Tables
[[categories]]
	name = "Tables"
	icon = "spr_ui_woodcrafting_category_icon_tables"

	[[categories.sub_categories]]
		name = "Coffee Tables"
		icon = "spr_ui_woodcrafting_category_icon_coffee_table"
		tags = ["coffee_table"]

	[[categories.sub_categories]]
		name = "Consoles"
		icon = "spr_ui_woodcrafting_category_icon_console_table"
		tags = ["console_table"]

	[[categories.sub_categories]]
		name = "Counters"
		icon = "spr_ui_woodcrafting_category_icon_counter"
		tags = ["counters"]

	[[categories.sub_categories]]
		name = "Dining Tables"
		icon = "spr_ui_woodcrafting_category_icon_dining_table"
		tags = ["dining_table"]

	[[categories.sub_categories]]
		name = "Dressing Tables"
		icon = "spr_ui_woodcrafting_category_icon_dressing_table"
		tags = ["dressing_table"]

	[[categories.sub_categories]]
		name = "Side Tables"
		icon = "spr_ui_woodcrafting_category_icon_side_table"
		tags = ["side_table"]


### Shelves & Drawers
[[categories]]
	name = "Shelves & Drawers"
	icon = "spr_ui_woodcrafting_category_icon_shelves_and_drawers"

	[[categories.sub_categories]]
		name = "Armoires"
		icon = "spr_ui_woodcrafting_category_icon_armoire"
		tags = ["armoire"]

	[[categories.sub_categories]]
		name = "Bookshelves"
		icon = "spr_ui_woodcrafting_category_icon_bookshelf"
		tags = ["bookshelf"]

	[[categories.sub_categories]]
		name = "Drawers"
		icon = "spr_ui_woodcrafting_category_icon_drawer"
		tags = ["drawer"]

	[[categories.sub_categories]]
		name = "Nightstands"
		icon = "spr_ui_woodcrafting_category_icon_nightstand"
		tags = ["nightstand"]

	[[categories.sub_categories]]
		name = "Wall Shelves"
		icon = "spr_ui_woodcrafting_category_icon_wall_shelf"
		tags = ["wall_shelf"]


### Lighting
[[categories]]
	name = "Lighting"
	icon = "spr_ui_woodcrafting_category_icon_lighting"

	[[categories.sub_categories]]
		name = "Floor"
		icon = "spr_ui_woodcrafting_category_icon_floor_lighting"
		tags = ["floor_lighting"]

	[[categories.sub_categories]]
		name = "Misc. Lighting"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_lighting"]

	[[categories.sub_categories]]
		name = "Table"
		icon = "spr_ui_woodcrafting_category_icon_table_lighting"
		tags = ["table_lighting"]

	[[categories.sub_categories]]
		name = "Wall"
		icon = "spr_ui_woodcrafting_category_icon_wall_lighting"
		tags = ["wall_lighting"]


### Rugs
[[categories]]
	name = "Rugs"
	icon = "spr_ui_woodcrafting_category_icon_rugs"

	[[categories.sub_categories]]
		name = "Large"
		icon = "spr_ui_woodcrafting_category_icon_large_rug"
		tags = ["large_rug"]

	[[categories.sub_categories]]
		name = "Medium"
		icon = "spr_ui_woodcrafting_category_icon_medium_rug"
		tags = ["medium_rug"]

	[[categories.sub_categories]]
		name = "Small"
		icon = "spr_ui_woodcrafting_category_icon_small_rug"
		tags = ["small_rug"]


### Windows
[[categories]]
	name = "Windows"
	icon = "spr_ui_woodcrafting_category_icon_window"

	[[categories.sub_categories]]
		name = "Window"
		icon = "spr_ui_woodcrafting_category_icon_window"
		tags = ["window"]

### Wall Decor
[[categories]]
	name = "Wall Decor"
	icon = "spr_ui_woodcrafting_category_icon_wall_decor"

	[[categories.sub_categories]]
		name = "Misc. Wall Decor"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_wall_decor"]

	[[categories.sub_categories]]
		name = "Wall Art"
		icon = "spr_ui_woodcrafting_category_icon_wall_art"
		tags = ["wall_art"]

	[[categories.sub_categories]]
		name = "Wall Hanging"
		icon = "spr_ui_woodcrafting_category_icon_wall_hanging"
		tags = ["wall_hanging"]


### Plants
[[categories]]
	name = "Plants"
	icon = "spr_ui_woodcrafting_category_icon_plants"

	[[categories.sub_categories]]
		name = "Freestanding"
		icon = "spr_ui_woodcrafting_category_icon_freestanding_plant"
		tags = ["freestanding_plant"]

	[[categories.sub_categories]]
		name = "Misc. Plants"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_plant"]

	[[categories.sub_categories]]
		name = "Potted"
		icon = "spr_ui_woodcrafting_category_icon_potted_tree"
		tags = ["potted_tree"]

	[[categories.sub_categories]]
		name = "Tabletop"
		icon = "spr_ui_woodcrafting_category_icon_tabletop_plant"
		tags = ["tabletop_plant"]


### Decorative Items
[[categories]]
	name = "Decorative Items"
	icon = "spr_ui_woodcrafting_category_icon_decorative_items"

	[[categories.sub_categories]]
		name = "Home Essentials"
		icon = "spr_ui_woodcrafting_category_icon_home_essential"
		tags = ["home_essential"]

	[[categories.sub_categories]]
		name = "Kitchen"
		icon = "spr_ui_woodcrafting_category_icon_kitchen_decor"
		tags = ["kitchen_decor"]

	[[categories.sub_categories]]
		name = "Misc. Decor"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_decor"]

	[[categories.sub_categories]]
		name = "Office"
		icon = "spr_ui_woodcrafting_category_icon_office_decor"
		tags = ["office_decor"]


### Miscellaneous
[[categories]]
	name = "Miscellaneous"
	icon = "spr_ui_crafting_category_icon_misc"

	[[categories.sub_categories]]
		name = "Miscellaneous"
		icon = "spr_ui_crafting_category_icon_misc"
		tags = ["misc_furniture"]
