[spouse_delivery_seridia]
writes = [
    { child_born_bump = true, expires = "2d" },
    { baby_born_timer = true, expires = "5d" }
]
kind = "gameplay_triggered"
speaker = "seridia"
portrait = "mad"
local = "[Ari], wake up!"
next = "1"

[spouse_delivery_seridia.1]
speaker = "seridia"
portrait = "closed_eyes_blush"
local = "The time has come. Our daughter will arrive soon."
next = "2"

[spouse_delivery_seridia.2]
speaker = "seridia"
portrait = "embarrassed"
local = "Let us proceed to the Clinic at once."
next = "3"

[spouse_delivery_seridia.3]
speaker = "valen"
portrait = "neutral"
local = "Congratulations, Seridia, [Ari]!"
next = "4"

[spouse_delivery_seridia.4]
speaker = "valen"
portrait = "happy"
local = "You are now the proud parents of a healthy $baby girl$!"
next = "5"

[spouse_delivery_seridia.5]
speaker = "valen"
portrait = "neutral"
local = "Have you two decided $what you will name her$?"
next = "6"

[spouse_delivery_seridia.6]
speaker = "seridia"
portrait = "blush"
local = "Yes... [child_0] is a powerful name."
next = "7"

[spouse_delivery_seridia.7]
speaker = "seridia"
portrait = "closed_eyes_smile"
local = "I might say it was pre-destined for her, if I believed in such restrictions."
next = "8"

[spouse_delivery_seridia.8]
speaker = "valen"
portrait = "neutral"
local = "Now, before I let you head home..."
next = "9"

[spouse_delivery_seridia.9]
speaker = "valen"
portrait = "happy"
local = "Would you like me to $tell you more about caring for a child$?"
prompts = [
    { local = "Yes, please!", next = "11" },
    { local = "No, I think we've got it covered.", next = "10" }
]

[spouse_delivery_seridia.10]
speaker = "valen"
portrait = "neutral"
local = "Understood."
next = "11"

[spouse_delivery_seridia.11]
speaker = "valen"
portrait = "neutral"
local = "Well, I believe that's everything for the time being."
next = "12"

[spouse_delivery_seridia.12]
speaker = "valen"
portrait = "think_special"
local = "Now Seridia, make sure you take it easy and get plenty of rest."
next = "13"

[spouse_delivery_seridia.13]
speaker = "valen"
portrait = "raised_eyebrow"
local = "Do I make myself clear, [Ari]? Don't let her overdo it!"
next = "14"

[spouse_delivery_seridia.14]
speaker = "valen"
portrait = "neutral"
local = "And remember, if you need anything at all, I'm just up the road."
next = "15"

[spouse_delivery_seridia.15]
speaker = "valen"
portrait = "happy"
effect = "cheery"
local = "Congratulations again!"
