[spouse_delivery_valen]
writes = [
    { child_born_bump = true, expires = "2d" },
    { baby_born_timer = true, expires = "5d" }
]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "mad"
effect = "surprise"
local = " [Ari]? Are you awake?"
next = "1"

[spouse_delivery_valen.1]
speaker = "valen"
portrait = "think"
local = "I think the baby is coming...!"
next = "2"

[spouse_delivery_valen.2]
speaker = "valen"
portrait = "embarrassed"
local = "We'd better call on Jo for some assistance and head to the Clinic!"
next = "3"

[spouse_delivery_valen.3]
speaker = "josephine"
portrait = "happy"
local = "You did it, Valen, well done!"
next = "4"

[spouse_delivery_valen.4]
speaker = "josephine"
portrait = "embarrassed"
effect = "cheery"
local = "You two are now the parents of a healthy and beautiful $baby boy$!"
next = "5"

[spouse_delivery_valen.5]
speaker = "josephine"
portrait = "neutral"
local = "Have you $decided on a name for him$?"
next = "6a"

[spouse_delivery_valen.6a]
speaker = "valen"
portrait = "happy_blush"
local = "Oh!"
next = [
    { target = "6b_torin", requires = [{ child_0_has_default_name = true }] },
    { target = "6b_standard", requires = [] }
]

[spouse_delivery_valen.6b_torin]
speaker = "valen"
portrait = "teary"
local = "$Torin$... My father's name."
next = "7"

[spouse_delivery_valen.6b_standard]
speaker = "valen"
portrait = "caring_special"
local = "Yes, [child_0]..."
next = "7"

[spouse_delivery_valen.7]
speaker = "valen"
portrait = "happy_blush"
local = "It suits him perfectly. It's as if it were already chosen for him long ago.."
next = "8"

[spouse_delivery_valen.8]
speaker = "josephine"
portrait = "neutral"
local = "Now, why don't we see about getting you two home?"
next = "9"

[spouse_delivery_valen.9]
speaker = "josephine"
portrait = "think"
local = "You need to get plenty of rest, Valen."
next = "10"

[spouse_delivery_valen.10]
speaker = "josephine"
portrait = "wink"
local = "You got that, [Ari]? Don't let her overdo it!"
next = "11"

[spouse_delivery_valen.11]
no_speaker = true
local = "Do you want to view the $Raising a Child$ Tutorial?"
prompts = [{ local = "Yes" }, { local = "No" }]
