[default]
	offset = [0, 0]
	collision_offset = [0, 0]
	size = [2, 2]
	collision_grid = "2"
	on_floor = false
	depth_offset = 0
	light_offset = [0, 0]
	sound_emitter_size = [4, 4]

#------------ Pillar
[biome1_pillar]
	sprites = ["spr_dungeon_mines_biome_1_unbreakable_spring"]
	depth_offset = -8

[biome2_pillar]
	sprites = ["spr_dungeon_mines_biome_2_pillar_spring"]
	depth_offset = -8

[biome3_pillar]
	sprites = ["spr_dungeon_mines_biome_3_unbreakable_spring"]
	depth_offset = -8

[biome4_pillar]
	sprites = ["spr_dungeon_mines_biome_4_unbreakable_spring"]
	depth_offset = -8

[biome5_pillar]
	sprites = ["spr_dungeon_mines_biome_5_unbreakable_spring"]
	depth_offset = -8

#------------ Light
[biome1_light]
	sprites = ["spr_dungeon_mines_biome_1_light_spring_on"]
	light = "circle_eighty"
	depth_offset = -11
	light_offset = [8, -3]
	sound = "SoundEffects/Environment/FirePlace"

[biome2_light]
	sprites = ["spr_dungeon_mines_biome_2_light_spring_on"]
	light = "circle_eighty"
	depth_offset = -11
	light_offset = [8, -3]
	sound = "SoundEffects/Environment/FirePlace"

[biome3_light]
	sprites = ["spr_dungeon_mines_biome_3_light_spring_on"]
	light = "circle_eighty"
	depth_offset = -11
	light_offset = [8, 0]
	sound = "SoundEffects/Environment/FirePlace"

[biome4_light]
	sprites = ["spr_dungeon_mines_biome_4_light_spring_on"]
	light = "circle_eighty"
	depth_offset = -11
	light_offset = [8, -3]
	sound = "SoundEffects/Environment/FirePlace"

[biome5_light]
	sprites = ["spr_dungeon_mines_biome_5_light_spring_on"]
	light = "circle_eighty"
	depth_offset = -11
	light_offset = [8, -3]
	sound = "SoundEffects/Environment/FirePlace"

#------------ M Beam
[biome1_m_beam_left]
	sprites = ["spr_dungeon_mines_biome_1_beam_left_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_1_beam_left_spring_top"]
	depth_offset = -15

[biome1_m_beam_middle]
	sprites = ["spr_dungeon_mines_biome_1_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = -15

[biome1_m_beam_right]
	sprites = ["spr_dungeon_mines_biome_1_beam_right_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_1_beam_right_spring_top"]
	depth_offset = -15

[biome2_m_beam_left]
	sprites = ["spr_dungeon_mines_biome_2_beam_left_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_2_beam_left_spring_top"]
	depth_offset = -15

[biome2_m_beam_middle]
	sprites = ["spr_dungeon_mines_biome_2_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = -15

[biome2_m_beam_right]
	sprites = ["spr_dungeon_mines_biome_2_beam_right_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_2_beam_right_spring_top"]
	depth_offset = -15

[biome3_m_beam_left]
	sprites = ["spr_dungeon_mines_biome_3_beam_left_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_3_beam_left_spring_top"]
	depth_offset = -15

[biome3_m_beam_middle]
	sprites = ["spr_dungeon_mines_biome_3_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = -15

[biome3_m_beam_right]
	sprites = ["spr_dungeon_mines_biome_3_beam_right_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_3_beam_right_spring_top"]
	depth_offset = -15

[biome4_m_beam_left]
	sprites = ["spr_dungeon_mines_biome_4_beam_left_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_4_beam_left_spring_top"]
	depth_offset = -15

[biome4_m_beam_middle]
	sprites = ["spr_dungeon_mines_biome_4_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = -15

[biome4_m_beam_right]
	sprites = ["spr_dungeon_mines_biome_4_beam_right_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_4_beam_right_spring_top"]
	depth_offset = -15

[biome5_m_beam_left]
	sprites = ["spr_dungeon_mines_biome_5_beam_left_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_5_beam_left_spring_top"]
	depth_offset = -15

[biome5_m_beam_middle]
	sprites = ["spr_dungeon_mines_biome_5_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = -15

[biome5_m_beam_right]
	sprites = ["spr_dungeon_mines_biome_5_beam_right_spring"]
	collision_grid = "0"
	top_sprites = ["spr_dungeon_mines_biome_5_beam_right_spring_top"]
	depth_offset = -15

#------------ Wall Beam
[biome1_wall_beam_left]
	sprites = ["spr_dungeon_mines_biome_1_wall_beam_left_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome1_wall_beam_right]
	sprites = ["spr_dungeon_mines_biome_1_wall_beam_right_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome1_wall_beam_middle]
	sprites = ["spr_dungeon_mines_biome_1_wall_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome2_wall_beam_left]
	sprites = ["spr_dungeon_mines_biome_2_wall_beam_left_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome2_wall_beam_right]
	sprites = ["spr_dungeon_mines_biome_2_wall_beam_right_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome2_wall_beam_middle]
	sprites = ["spr_dungeon_mines_biome_2_wall_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome3_wall_beam_left]
	sprites = ["spr_dungeon_mines_biome_3_wall_beam_left_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome3_wall_beam_right]
	sprites = ["spr_dungeon_mines_biome_3_wall_beam_right_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome3_wall_beam_middle]
	sprites = ["spr_dungeon_mines_biome_3_wall_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = 1

[biome4_wall_beam_left]
	sprites = ["spr_dungeon_mines_biome_4_wall_beam_left_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome4_wall_beam_right]
	sprites = ["spr_dungeon_mines_biome_4_wall_beam_right_spring"]
	collision_grid = "0"
	depth_offset = 2

[biome4_wall_beam_middle]
	sprites = ["spr_dungeon_mines_biome_4_wall_beam_middle_spring"]
	collision_grid = "0"
	depth_offset = 1

[biome5_wall_beam_left]
	sprites = ["spr_dungeon_mines_biome_5_wall_beam_left"]
	collision_grid = "0"
	depth_offset = 3

[biome5_wall_beam_right]
	sprites = ["spr_dungeon_mines_biome_5_wall_beam_right"]
	collision_grid = "0"
	depth_offset = 3

[biome5_wall_beam_middle]
	sprites = ["spr_dungeon_mines_biome_5_wall_beam_middle"]
	collision_grid = "0"
	depth_offset = 2

#------------ BIOME 1
[biome1_fallen_pillar]
	sprites = ["spr_dungeon_mines_biome_1_fallen_pillar_spring"]
	collision_offset = [0, -1]
	size = [6, 3]
	collision_grid = ["001111", "111111", "111100"]
	depth_offset = -3

[biome1_mine_cart]
	sprites = ["spr_dungeon_mines_biome_1_mine_cart_spring"]
	size = [4, 2]

[biome1_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_1_stalagmite_1_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome1_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_1_stalagmite_2_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome1_wall_light]
	sprites = ["spr_dungeon_mines_biome_1_wall_light_on"]
	collision_grid = "0"
	light = "circle_eighty"
	light_offset = [8, 0]

[biome1_track_lg1]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_1_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg2]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_2_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg3]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_3_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg4]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_4_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg5]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_5_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg6]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_6_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg7]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_7_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg8]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_8_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_lg9]
	sprites = ["spr_dungeon_mines_biome_1_track_lg_9_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_sm1]
	sprites = ["spr_dungeon_mines_biome_1_track_sm_1_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_sm2]
	sprites = ["spr_dungeon_mines_biome_1_track_sm_2_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_sm3]
	sprites = ["spr_dungeon_mines_biome_1_track_sm_3_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_sm4]
	sprites = ["spr_dungeon_mines_biome_1_track_sm_4_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_sm5]
	sprites = ["spr_dungeon_mines_biome_1_track_sm_5_spring"]
	collision_grid = "0"
	on_floor = true

[biome1_track_sm6]
	sprites = ["spr_dungeon_mines_biome_1_track_sm_6_spring"]
	collision_grid = "0"
	on_floor = true

#------------ BIOME 2
[biome2_fallen_pillar]
	sprites = ["spr_dungeon_mines_biome_2_broken_pillar_spring"]
	collision_offset = [0, -1]
	size = [6, 4]
	collision_grid = ["000111", "011111", "111100", "111000"]

[biome2_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_2_stalagmite_v1_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome2_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_2_stalagmite_v2_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome2_water_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_2_water_stalagmite_v1_spring"]
	size = [4, 2]
	collision_grid = "1"
	depth_offset = -8

[biome2_water_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_2_water_stalagmite_v2_spring"]
	size = [4, 2]
	collision_grid = "1"
	depth_offset = -8

[biome2_wall_light]
	sprites = ["spr_dungeon_mines_biome_2_wall_light_spring_on"]
	collision_grid = "0"
	light = "circle_eighty"
	light_offset = [8, 0]

[biome2_wall_coral]
	sprites = ["spr_dungeon_mines_biome_2_wall_coral_decoration_spring"]
	collision_grid = "0"

[biome2_floor_shell1]
	sprites = ["spr_dungeon_mines_biome_2_floor_shell_v1"]
	collision_grid = "0"
	on_floor = true

[biome2_floor_shell2]
	sprites = ["spr_dungeon_mines_biome_2_floor_shell_v2"]
	collision_grid = "0"
	on_floor = true

[biome2_floor_stones]
	sprites = ["spr_dungeon_mines_biome_2_floor_stones_spring"]
	collision_grid = "0"
	on_floor = true

#------------ BIOME 3
[biome3_fallen_pillar]
	sprites = ["spr_dungeon_mines_biome_3_broken_pillar_spring"]
	collision_offset = [0, -1]
	size = [6, 4]
	collision_grid = ["000111", "011111", "111100", "111000"]

[biome3_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_3_stalagmite_v1_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome3_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_3_stalagmite_v2_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome3_water_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_3_water_stalagmite_v1_spring"]
	size = [4, 2]
	collision_grid = "1"
	depth_offset = -8

[biome3_water_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_3_water_stalagmite_v2_spring"]
	size = [4, 2]
	collision_grid = "1"
	depth_offset = -8

[biome3_wall_light]
	sprites = ["spr_dungeon_mines_biome_3_wall_light_spring"]
	collision_grid = "0"
	light = "circle_eighty"
	light_offset = [8, 0]
	sound = "SoundEffects/Environment/FirePlace"

[biome3_floor_stones]
	sprites = ["spr_dungeon_mines_biome_3_floor_stones_spring"]
	collision_grid = "0"
	on_floor = true

#------------ BIOME 4
[biome4_floor_stones]
	sprites = ["spr_dungeon_mines_biome_4_floor_stones_spring"]
	collision_grid = "0"
	on_floor = true

[biome4_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_4_stalagmite_v1_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome4_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_4_stalagmite_v2_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome4_lava_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_4_lava_stalagmite_v1_spring"]
	collision_grid = "2"
	depth_offset = -8

[biome4_lava_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_4_lava_stalagmite_v2_spring"]
	collision_grid = "2"
	depth_offset = -8

[biome4_crumbled_wall1]
	sprites = ["spr_dungeon_mines_biome_4_crumbled_wall_v1_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome4_crumbled_wall2]
	sprites = ["spr_dungeon_mines_biome_4_crumbled_wall_v2_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome4_broken_statue]
	sprites = ["spr_dungeon_mines_biome_4_broken_statue_spring"]
	size = [4, 4]
	collision_grid = "3"
	depth_offset = -27

[biome4_wall_light]
	sprites = ["spr_dungeon_mines_biome_4_wall_light_spring"]
	collision_grid = "0"
	light = "circle_eighty"
	light_offset = [8, 0]
	sound = "SoundEffects/Environment/FirePlace"

#------------ BIOME 5
[biome5_floor_stones]
	sprites = ["spr_dungeon_mines_biome_5_floor_stones_spring"]
	collision_grid = "0"
	on_floor = true

[biome5_floor_stone_square]
	sprites = ["spr_priestess_quarters_floor_stone_1"]
	collision_grid = "0"
	on_floor = true

[biome5_floor_stone_diamond]
	sprites = ["spr_priestess_quarters_floor_stone_2"]
	collision_grid = "0"
	on_floor = true

[biome5_water_stalagmite1]
	sprites = ["spr_dungeon_mines_biome_5_water_stalagmite_v1_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome5_water_stalagmite2]
	sprites = ["spr_dungeon_mines_biome_5_water_stalagmite_v2_spring"]
	collision_grid = "1"
	depth_offset = -8

[biome5_broken_statue]
	sprites = ["spr_dungeon_mines_biome_5_broken_statue_main"]
	size = [4, 4]
	collision_grid = "3"
	depth_offset = -27

[biome5_crystal_light]
	sprites = ["spr_dungeon_mines_biome_5_crystal_light_main_off"]
	collision_grid = "1"
	depth_offset = -8
	light = "insect"
	light_offset = [8, 2]
	sound = "SoundEffects/Environment/FirePlace"

	[biome5_crystal_light.dark_light]
		sprite = "spr_dungeon_mines_biome_5_crystal_light_main_on"
		light = "circle_hundred_fifty_two"

[biome5_wall_light]
	sprites = ["spr_dungeon_mines_biome_5_wall_light_on"]
	collision_grid = "0"
	depth_offset = -15
	light = "circle_eighty"
	light_offset = [8, 0]
	sound = "SoundEffects/Environment/FirePlace"

[biome5_rubble1]
	sprites = ["spr_dungeon_mines_biome_5_rubble_v1_main"]
	collision_grid = "1"
	depth_offset = -8

[biome5_rubble2]
	sprites = ["spr_dungeon_mines_biome_5_rubble_v2_main"]
	collision_grid = "1"
	depth_offset = -8

[biome5_rubble3]
	size = [4, 2]
	sprites = ["spr_dungeon_mines_biome_5_rubble_v3_main"]
	collision_grid = "1"

[biome5_rubble4]
	size = [2, 4]
	sprites = ["spr_dungeon_mines_biome_5_rubble_v4_main"]
	collision_grid = ["00", "11", "11", "11"]
	depth_offset = -15

[biome5_rubble5]
	size = [4, 2]
	sprites = ["spr_dungeon_mines_biome_5_rubble_v5_main"]
	collision_grid = "1"

[biome5_water_rubble1]
	size = [5, 4]
	sprites = ["spr_dungeon_mines_biome_5_water_rubble_v1"]
	collision_grid = ["00000", "00000", "11111", "11111"]
	depth_offset = -15

[biome5_water_rubble2]
	size = [3, 2]
	sprites = ["spr_dungeon_mines_biome_5_water_rubble_v2"]
	collision_grid = "1"
	depth_offset = -1

[biome5_window]
	sprites = ["spr_dungeon_mines_biome_5_window"]
	collision_grid = "0"
	depth_offset = -15