[[biomes]]
	name = "Upper Mines"
	floor = 1
	asset_insert = "mines_biome_1"
	music = "Music/Playlists/MinesUpper"
	artifact_set = "upper_mines_artifacts"
	ore = "ore_copper"
	gem = "ore_ruby"
	combat_xp_gain = 3
	ladder_chance_range = [0.25, 0.75]
	monster_element_points = 1
	object_element_points = 1
	cosmetics = [
		"head_miners_helmet",
		"suit_miner",
		"shoes_boots_miner",
	]
	armor = [
		"scrap_metal_helmet",
		"scrap_metal_chestpiece",
		"scrap_metal_pants",
		"scrap_metal_boots",
		"scrap_metal_ring",
		"sword_scrap_metal",
	]
	furniture = [
		"miners_copper_node",
		"miners_ruby_rock",
		"miners_minecart_v1",
		"miners_minecart_v2",
		"miners_crate_chair_v1",
		"miners_crate_chair_v2",
		"miners_crate_chest_v1",
		"miners_crate_chest_v2",
		"miners_floor_lamp_v1",
		"miners_floor_lamp_v2",
		"miners_wall_lamp_v1",
		"miners_wall_lamp_v2",
		"miners_shelves_v1",
		"miners_shelves_v2",
		"miners_flooring",
		"miners_wallpaper",
		"mines_wooden_arch",
	]
	dungeon_delicacies = [
		"baked_sweetroot",
		"cherry_cobbler",
		"miners_mushroom_stew",
		"grape_juice",
		"turnip_and_cabbage_salad",
		"monster_cookie",
	]
	taste_maker = [
		"crunchy_chickpeas",
		"turnip_and_cabbage_salad",
		"monster_cookie",
	]
	[biomes.shrine]
		inputs = [
			{ item_id = "ore_stone", amount = 10 },
		]
		outputs.health = 25
		outputs.stamina = 20
		outputs.essence = 10

	[biomes.votes]
		junk = [{ object = "debris" }]
		breakable = [{ object = "barrel" }, { object = "crate" }, { object = "box" }]
		chest = [
			{ object = "treasure_chest_wood" },
			{ object = "treasure_chest_copper" },
			{ object = "treasure_chest_silver" },
			{ object = "treasure_chest_gold" },
		]
		enemy = [
			{ object = "sapling", votes = 8 },
			{ object = "mushroom", votes = 5 },
			{ object = "rockclod", votes = 4 },
			{ object = "enchantern", votes = 5 },
			{ object = "sapling_cool", votes = 3 },
			{ object = "copperclod", votes = 3 },
			{ object = "mimic", votes = 1 },
		]
		large_rock = [{ object = "large_rock_stone_upper" }]
		ore_rock = [
			{ object = "node_copper", votes = 45 },
			{ object = "rock_copper", votes = 9 },
			{ object = "node_ruby", votes = 3 },
			{ object = "rock_ruby", votes = 1 },
		]
		small_rock = [
			{ object = "small_rock_stone_upper" },
			{ object = "small_dirt_rock_one" },
		]
		seam_rock = [{ object = "seam_rock_copper" }]
		fish = [
			{ object = "cave_shrimp", votes = 30 },
			{ object = "stone_loach", votes = 30 },
			{ object = "rock_guppy", votes = 18 },
			{ object = "cave_eel", votes = 18 },
			{ object = "cave_shark", votes = 10 },
		]
		bug = [
			{ object = "lantern_moth", votes = 50 },
			{ object = "copper_beetle", votes = 30 },
			{ object = "mine_cricket", votes = 20 },
		]
		forageable = [
			{ object = "upper_mines_mushroom" },
			{ object = "sweetroot" },
			{ object = "shadow_flower" },
			{ object = "narrows_moss" },
		]
		void_rock = [
			{ object = "rock_void" },
		]
		void_herb = [
			{ object = "void_herb" },
		]
		void_pearl = [
			{ object = "void_pearl" },
		]

[[biomes]]
	name = "The Tide Caverns"
	floor = 20
	asset_insert = "mines_biome_2"
	music = "Music/Playlists/MinesTideCaverns"
	artifact_set = "tide_caverns"
	ore = "ore_iron"
	gem = "ore_sapphire"
	combat_xp_gain = 4
	ladder_chance_range = [0.15, 0.70]
	monster_element_points = 1
	object_element_points = 1
	cosmetics = [
		"head_crown_tide",
		"robe_tide",
		"shoes_sandals_tide",
	]
	armor = [
		"verdigris_helmet",
		"verdigris_chestpiece",
		"verdigris_tassets",
		"verdigris_boots",
		"verdigris_ring",
		"sword_verdigris",
	]
	furniture = [
		"coral_lamp_blue",
		"coral_chair_blue",
		"coral_table_blue",
		"coral_storage_chest_blue",
		"coral_lamp_purple",
		"coral_chair_purple",
		"coral_table_purple",
		"coral_storage_chest_purple",
		"sand_rug",
		"low_tide_flooring",
		"tide_touched_cavern_wall",
		"ornamental_iron_node",
		"ornamental_sapphire_rock",
		"coral_stone_archway",
	]
	dungeon_delicacies = [
		"deep_sea_soup",
		"sour_lemon_cake",
		"chickpea_curry",
		"monster_mash",
		"crispy_fried_earthshroom",
		"tide_salad",
	]
	taste_maker = [
		"sour_lemon_cake",
		"cherry_smoothie",
		"chickpea_curry",
		"monster_mash",
		"crispy_fried_earthshroom",
		"tide_salad",
	]
	[biomes.shrine]
		inputs = [
			{ item_id = "ore_stone", amount = 10 },
			{ item_id = "ore_iron", amount = 5 },
			{ item_id = "coral", amount = 3 },
		]
		outputs.health = 25
		outputs.stamina = 20
		outputs.essence = 10

	[biomes.votes]
		junk = [
			{ object = "coral_small" },
			{ object = "coral_large" },
		]
		breakable = [
			{ object = "barrel" },
			{ object = "crate" },
		]
		chest = [
			{ object = "treasure_chest_wood" },
			{ object = "treasure_chest_copper" },
			{ object = "treasure_chest_silver" },
			{ object = "treasure_chest_gold" },
		]
		enemy = [
			{ object = "sapling_blue", votes = 5 },
			{ object = "mushroom_green", votes = 5 },
			{ object = "rockclod_blue", votes = 5 },
			{ object = "enchantern_blue", votes = 5 },
			{ object = "ironclod", votes = 3 },
			{ object = "stalagmite", votes = 3 },
			{ object = "bat", votes = 3 },
			{ object = "mimic", votes = 1 },
		]
		large_rock = [{ object = "large_rock_stone_two" }]
		ore_rock = [
			{ object = "node_iron", votes = 45 },
			{ object = "rock_iron", votes = 9 },
			{ object = "node_sapphire", votes = 3 },
			{ object = "rock_sapphire", votes = 1 },
		]
		small_rock = [
			{ object = "small_rock_stone_two" },
			{ object = "small_dirt_rock_two" },
		]
		seam_rock = [{ object = "seam_rock_iron" }]
		fish = [
			{ object = "sapphire_betta", votes = 30 },
			{ object = "transparent_jellyfish", votes = 30 },
			{ object = "archerfish", votes = 30 },
			{ object = "water_balloon_fish", votes = 18 },
			{ object = "mini_whale_shark", votes = 10 },
		]
		bug = [
			{ object = "waterfly", votes = 50 },
			{ object = "hermit_snail", votes = 30 },
			{ object = "coral_mantis", votes = 60 },
			{ object = "puddle_spider", votes = 20 },
		]
		forageable = [
			{ object = "sea_grapes" },
			{ object = "cave_kelp" },
			{ object = "mines_mussels" },
			{ object = "tide_lettuce" },
		]
		water_forageable = [
			{ object = "underseaweed" },
		]
		void_rock = [
			{ object = "rock_void" },
		]
		void_herb = [
			{ object = "void_herb" },
		]
		void_pearl = [
			{ object = "void_pearl" },
		]

[[biomes]]
	name = "Deep Earth"
	floor = 40
	asset_insert = "mines_biome_3"
	music = "Music/Playlists/MinesDeepEarth"
	artifact_set = "deep_earth"
	ore = "ore_silver"
	gem = "ore_emerald"
	combat_xp_gain = 5
	ladder_chance_range = [0.15, 0.70]
	monster_element_points = 1
	object_element_points = 1
	cosmetics = [
		"head_circlet_earth",
		"robe_earth",
		"shoes_sandals_earth",
	]
	armor = [
		"crystal_helmet",
		"crystal_chestpiece",
		"crystal_tassets",
		"crystal_boots",
		"crystal_ring",
		"sword_crystal",
	]
	furniture = [
		"cavern_crystal_lamp_green",
		"cavern_mushroom_stool_green",
		"cavern_crystal_lamp_pink",
		"cavern_mushroom_stool_pink",
		"cavern_crystal_lamp_purple",
		"cavern_mushroom_stool_purple",
		"cavern_emerald_rock",
		"cavern_silver_node",
		"cavern_hewn_rock_bookshelf",
		"cavern_hewn_rock_table",
		"cavern_stone_arch",
		"cavern_wall_brazier_purple",
		"cavern_wall_brazier_orange",
		"cavern_wall_brazier_blue",
		"cavern_floor_brazier_purple",
		"cavern_floor_brazier_orange",
		"cavern_floor_brazier_blue",
		"cavern_mossy_rug_v1",
		"cavern_mossy_rug_v2",
		"cavern_rock_wallpaper",
		"cavern_rock_flooring",
	]
	dungeon_delicacies = [
		"fried_rice",
		"herb_salad",
		"turnip_and_potato_gratin",
		"vegetable_pot_pie",
		"spring_galette",
	]
	taste_maker = [
		"herb_salad",
		"turnip_and_potato_gratin",
		"vegetable_pot_pie",


	]
	[biomes.shrine]
		inputs = [
			{ item_id = "ore_stone", amount = 10 },
		]
		outputs.health = 25
		outputs.stamina = 20
		outputs.essence = 10

	[biomes.votes]
		junk = [{ object = "crystal_large" }, { object = "crystal_small" }]
		breakable = [{ object = "barrel" }, { object = "crate" }]
		chest = [
			{ object = "treasure_chest_wood" },
			{ object = "treasure_chest_copper" },
			{ object = "treasure_chest_silver" },
			{ object = "treasure_chest_gold" },
		]
		enemy = [
			{ object = "sapling_purple", votes = 5 },
			{ object = "mushroom_blue", votes = 5 },
			{ object = "rockclod_green", votes = 4 },
			{ object = "silverclod", votes = 3 },
			{ object = "stalagmite_green", votes = 3 },
			{ object = "bat_blue", votes = 3 },
			{ object = "mimic", votes = 1 },
		]
		large_rock = [{ object = "large_rock_stone_three" }]
		ore_rock = [
			{ object = "node_silver", votes = 45 },
			{ object = "rock_silver", votes = 9 },
			{ object = "node_emerald", votes = 3 },
			{ object = "rock_emerald" },
		]
		small_rock = [
			{ object = "small_rock_stone_three" },
			{ object = "small_dirt_rock_three" },
		]
		seam_rock = [{ object = "seam_rock_silver" }]
		fish = [
			{ object = "pebble_minnow", votes = 30 },
			{ object = "earth_eel", votes = 30 },
			{ object = "shardfin", votes = 30 },
			{ object = "rockbiter", votes = 18 },
			{ object = "emerald_horned_charger", votes = 10 },
		]
		bug = [
			{ object = "crystalline_cricket", votes = 50 },
			{ object = "gem_shard_caterpillar", votes = 30 },
			{ object = "crystal_wing_moth", votes = 20 },
		]
		forageable = [
			{ object = "crystal_berries" },
			{ object = "shale_grass" },
			{ object = "earthshroom" },
			{ object = "rockroot" },
			{ object = "crystal_rose" },
		]
		water_forageable = []
		void_rock = [
			{ object = "rock_void" },
		]
		void_herb = [
			{ object = "void_herb" },
		]
		void_pearl = [
			{ object = "void_pearl" },
		]

[[biomes]]
	name = "The Lava Caves"
	floor = 60
	asset_insert = "mines_biome_4"
	music = "Music/Playlists/MinesLavaCaves"
	artifact_set = "lava_caves"
	ore = "ore_gold"
	gem = "ore_diamond"
	ladder_chance_range = [0.20, 0.75]
	monster_element_points = 1
	object_element_points = 1
	combat_xp_gain = 6
	cosmetics = [
		"head_fire_hood",
		"shoes_boots_fire",
		"robe_fire",
		"back_gear_fire_cloak",
	]
	armor = [
		"tarnished_gold_helmet",
		"tarnished_gold_armor",
		"tarnished_gold_legplates",
		"tarnished_gold_boots",
		"tarnished_gold_ring",
		"sword_tarnished_gold",
	]
	furniture = [
		"lava_caves_diamond_rock",
		"lava_caves_gold_node",
		"lava_caves_stone_arch",
		"lava_caves_wallpaper",
		"lava_caves_flooring",
		"lava_caves_obsidian_fence_purple",
		"lava_caves_obsidian_fence_blue",
		"lava_caves_obsidian_bed_blue",
		"lava_caves_obsidian_bed_purple",
		"lava_caves_obsidian_double_bed_blue",
		"lava_caves_obsidian_double_bed_purple",
		"lava_caves_obsidian_chair_blue",
		"lava_caves_obsidian_chair_purple",
		"lava_caves_obsidian_table_blue",
		"lava_caves_obsidian_table_purple",
		"lava_caves_obsidian_storage_chest_blue",
		"lava_caves_obsidian_storage_chest_purple",
		"lava_caves_obsidian_floor_lamp_blue",
		"lava_caves_obsidian_floor_lamp_purple",
	]
	dungeon_delicacies = [
		"incredibly_hot_pot",
		"summer_salad",
		"spicy_crab_sushi",
		"chili_coconut_curry",
		"fried_rice",
	]
	taste_maker = [
		"incredibly_hot_pot",
		"summer_salad",
		"spicy_crab_sushi",
		"chili_coconut_curry",
		"fried_rice",
	]
	[biomes.shrine]
		inputs = [
			{ item_id = "ore_stone", amount = 10 },
		]
		outputs.health = 25
		outputs.stamina = 20
		outputs.essence = 10

	[biomes.votes]
		junk = [{ object = "obsidian_large" }, { object = "obsidian_small" }]
		breakable = [{ object = "barrel" }, { object = "crate" }]
		chest = [
			{ object = "treasure_chest_wood" },
			{ object = "treasure_chest_copper" },
			{ object = "treasure_chest_silver" },
			{ object = "treasure_chest_gold" },
		]
		enemy = [
			{ object = "spirit", votes = 5 },
			{ object = "cat", votes = 5 },
			{ object = "sapling_orange", votes = 4 },
			{ object = "mushroom_purple", votes = 4 },
			{ object = "rockclod_red", votes = 3 },
			{ object = "goldclod", votes = 2 },
			{ object = "stalagmite_purple", votes = 3 },
			{ object = "mimic", votes = 1 },
		]
		large_rock = [{ object = "large_rock_stone_four" }]
		ore_rock = [
			{ object = "node_gold", votes = 45 },
			{ object = "rock_gold", votes = 9 },
			{ object = "node_diamond", votes = 3 },
			{ object = "rock_diamond" },
		]
		small_rock = [
			{ object = "small_rock_stone_four" },
			{ object = "small_dirt_rock_four" },
		]
		seam_rock = [{ object = "seam_rock_gold" }]
		fish = [
			{ object = "lava_piranha", votes = 30 },
			{ object = "armored_bass", votes = 30 },
			{ object = "candelabra_seadragon", votes = 18 },
			{ object = "sulfur_crab", votes = 18 },
			{ object = "firesail_fish", votes = 10 },
		]
		bug = [
			{ object = "fire_wasp", votes = 60 },
			{ object = "lava_snail", votes = 50 },
			{ object = "cooktop_beetle", votes = 60 },
			{ object = "smoke_moth", votes = 50 },
			{ object = "diamond_beetle", votes = 30 },
		]
		forageable = [
			{ object = "flame_pepper" },
			{ object = "ash_mushroom" },
			{ object = "lava_chestnuts" },
			{ object = "hot_potato" },
			{ object = "breath_of_fire" },
		]
		water_forageable = []
		void_rock = [
			{ object = "rock_void" },
		]
		void_herb = [
			{ object = "void_herb" },
		]
		void_pearl = [
			{ object = "void_pearl" },
		]

[[biomes]]
	name = "Ancient Ruins"
	floor = 80
	asset_insert = "mines_biome_5"
	music = "Music/Playlists/MinesRuins"
	artifact_set = "dragon"
	ore = "ore_mistril"
	gem = "ore_pink_diamond"
	ladder_chance_range = [0.23, 0.75]
	monster_element_points = 1
	object_element_points = 1
	combat_xp_gain = 7
	cosmetics = [
		"head_dark_regent_crown",
		"shoes_boots_dark_regent",
		"back_gear_dark_regent_cape",
		"robe_dark_regent",
	]
	armor = [
		"corrupted_mistril_helmet",
		"corrupted_mistril_chestpiece",
		"corrupted_mistril_pants",
		"corrupted_mistril_boots",
		"corrupted_mistril_ring",
		"sword_corrupted_mistril",
	]
	furniture = [
		"ruins_pink_diamond_rock",
		"ruins_mistril_node",
		"ruins_wallpaper",
		"ruins_flooring",
		"ruins_stone_arch",
		"ruins_pot1",
		"ruins_pot2",
		"ruins_pot3",
		"ruins_pot4",
		"ruins_pot5",
		"ruins_pot6",
		"ruins_pot7",
		"ruins_pot8",
		"ruins_pot9",
		"ruins_crystal_light",
		"ruins_wall_crystal_light",
		"ruins_floor_brazier_purple",
		"ruins_floor_brazier_orange",
		"ruins_floor_brazier_blue",
		"ruins_window_v1",
		"ruins_window_v2",
		"ruins_window_v3",
		"witch_queen_flooring_v1",
		"witch_queen_flooring_v2",
		"witch_queen_wallpaper_v1",
		"witch_queen_wallpaper_v2",
		"witch_queen_bed_v1",
		"witch_queen_bed_v2",
		"witch_queen_double_bed_v1",
		"witch_queen_double_bed_v2",
		"witch_queen_cauldron_v1",
		"witch_queen_cauldron_v2",
		"witch_queen_chair_v1",
		"witch_queen_chair_v2",
		"witch_queen_dressing_table_v1",
		"witch_queen_dressing_table_v2",
		"witch_queen_moon_lamp_v1",
		"witch_queen_moon_lamp_v2",
		"witch_queen_nightstand_v1",
		"witch_queen_nightstand_v2",
		"witch_queen_pillar_v1",
		"witch_queen_pillar_v2",
		"witch_queen_rug_v1",
		"witch_queen_rug_v2",
		"witch_queen_table_v1",
		"witch_queen_table_v2",
		"witch_queen_throne_v1",
		"witch_queen_throne_v2",
	]
	dungeon_delicacies = [
		"spell_fruit_parfait",
		"pizza",
		"spicy_corn",
		"cucumber_sandwich",
	]
	taste_maker = [
		"spell_fruit_parfait",
		"pizza",
		"spicy_corn",
		"cucumber_sandwich",
	]
	[biomes.shrine]
		inputs = [
			{ item_id = "ore_stone", amount = 10 },
		]
		outputs.health = 25
		outputs.stamina = 20
		outputs.essence = 10

	[biomes.votes]
		junk = [{ object = "voidite_large" }, { object = "voidite_small" }]
		breakable = [
			{ object = "ruins_pot_white" },
			{ object = "ruins_pot_red" },
			{ object = "ruins_pot_purple" },
		]
		chest = [
			{ object = "treasure_chest_wood" },
			{ object = "treasure_chest_copper" },
			{ object = "treasure_chest_silver" },
			{ object = "treasure_chest_gold" },
		]
		enemy = [
			{ object = "rock_stack", votes = 5 },
			{ object = "sapling_pink", votes = 7 },
			{ object = "spirit_purple", votes = 5 },
			{ object = "tome", votes = 5 },
			{ object = "cat_void", votes = 4 },
			{ object = "mimic", votes = 1 },
		]
		mini_boss_enemy = [
			{ object = "griffin_statue", votes = 1 },
		]
		large_rock = [{ object = "large_rock_stone_five" }]
		ore_rock = [
			{ object = "node_mistril", votes = 45 },
			{ object = "rock_mistril", votes = 9 },
			{ object = "node_pink_diamond", votes = 3 },
			{ object = "rock_pink_diamond" },
		]
		small_rock = [
			{ object = "small_rock_stone_five" },
			{ object = "small_dirt_rock_five" },
		]
		seam_rock = [{ object = "seam_rock_mistril" }]
		fish = [
			{ object = "winged_shrimp", votes = 30 },
			{ object = "luminescent_crab", votes = 30 },
			{ object = "giant_jellyfish", votes = 30 },
			{ object = "gazer", votes = 18 },
			{ object = "coelacanth", votes = 18 },
		]
		bug = [
			{ object = "ancient_firefly", votes = 50 },
			{ object = "void_snail", votes = 50 },
			{ object = "parchment_moth", votes = 30 },
			{ object = "hidden_beetle", votes = 20 },
		]
		forageable = [
			{ object = "spell_fruit" },
			{ object = "written_root" },
			{ object = "essence_blossom" },
			{ object = "ethereal_grass" },
			{ object = "chirping_fern" },
			#{ object = "void_herb },
		]
		water_forageable = []
		void_rock = [
			{ object = "rock_void" },
		]
		void_herb = [
			{ object = "void_herb" },
		]
		void_pearl = [
			{ object = "void_pearl" },
		]
