# Biome 1 - Upper Mines
rm_mines_upper_amoeba = [2, 19]
rm_mines_upper_boomerang = [2, 19]
rm_mines_upper_canada = [2, 19]
rm_mines_upper_four = [2, 19]
rm_mines_upper_muscle = [2, 19]
rm_mines_upper_pond = [2, 19]
rm_mines_upper_snake = [2, 19]
rm_mines_upper_sock = [2, 19]
rm_mines_upper_staple = [2, 19]
rm_mines_upper_wishbone = [2, 19]
rm_mines_upper_worm = [2, 19]
rm_mines_upper_crossroad = [2, 19]
rm_mines_upper_floor1 = [1, 1]
rm_mines_upper_path = [2, 19]
rm_mines_upper_pillars = [2, 19]
rm_mines_upper_pits = [2, 19]
rm_mines_upper_ponds = [2, 19]
rm_mines_upper_stream = [2, 19]
rm_mines_upper_treasure = [2, 19]
rm_mines_upper_slimetime = [16, 19]
rm_mines_upper_formerelevator = [16, 19]

# Biome 2 - Tide Caverns
rm_mines_tide_whirly = [22, 39]
rm_mines_tide_fork = [22, 39]
rm_mines_tide_chamber = [22, 39]
rm_mines_tide_milestone = [22, 39]
rm_mines_tide_oasis = [22, 39]
rm_mines_tide_paths = [22, 39]
rm_mines_tide_ritual_chamber = [22, 39]
rm_mines_tide_islands = [22, 39]
rm_mines_tide_shrine1 = [22, 39]
rm_mines_tide_shrine2 = [22, 39]
rm_mines_tide_shrine3 = [22, 39]
rm_mines_tide_whirlpool1 = [22, 39]
rm_mines_tide_whirlpool2 = [22, 39]
rm_mines_tide_whirlpool3 = [22, 39]
rm_mines_tide_whirlpool4 = [22, 39]
rm_mines_tide_switch1 = [22, 39]
rm_mines_tide_switch2 = [22, 39]
rm_mines_tide_switch3 = [22, 39]
rm_mines_tide_switch4 = [22, 39]
rm_mines_tide_basic1 = [22, 39]
rm_mines_tide_basic2 = [22, 39]
rm_mines_tide_basic3 = [22, 39]
rm_mines_tide_basic4 = [22, 39]

# Biome 3 - Deep Earth
rm_mines_deep_butterfly = [41, 59]
rm_mines_deep_chambers = [41, 59]
rm_mines_deep_key = [41, 59]
rm_mines_deep_leap = [41, 59]
rm_mines_deep_ritual_chamber = [41, 59]
rm_mines_deep_runner = [41, 59]
rm_mines_deep_scorpio = [41, 59]
rm_mines_deep_spiral = [41, 59]
rm_mines_deep_switch1 = [41, 59]
rm_mines_deep_switch2 = [41, 59]
rm_mines_deep_switch3 = [41, 59]
rm_mines_deep_switch4 = [41, 59]
rm_mines_deep_winding = [41, 59]
rm_mines_deep_wishbone = [41, 59]
rm_mines_deep_shrine1 = [41, 59]
rm_mines_deep_shrine2 = [41, 59]
rm_mines_deep_shrine3 = [41, 59]
rm_mines_deep_shrine4 = [41, 59]
rm_mines_deep_treasure1 = [41, 59]
rm_mines_deep_whirlpool1 = [41, 59]
rm_mines_deep_whirlpool2 = [41, 59]

# Biome 4 - Lava Caves
rm_mines_lava_world = [61, 79]
rm_mines_lava_bullseye = [61, 79]
rm_mines_lava_arena = [61, 79]
rm_mines_lava_generic = [61, 79]
rm_mines_lava_elements = [61, 79]
rm_mines_lava_ritual_chamber = [61, 79]
rm_mines_lava_treasure = [61, 79]
rm_mines_lava_switch1 = [61, 79]
rm_mines_lava_switch2 = [61, 79]
rm_mines_lava_switch3 = [61, 79]
rm_mines_lava_switch4 = [61, 79]
rm_mines_lava_switch5 = [61, 79]
rm_mines_lava_basic1 = [61, 79]
rm_mines_lava_basic2 = [61, 79]
rm_mines_lava_basic3 = [61, 79]
rm_mines_lava_basic4 = [61, 79]
rm_mines_lava_basic5 = [61, 79]
rm_mines_lava_shrine1 = [61, 79]
rm_mines_lava_shrine2 = [61, 79]
rm_mines_lava_shrine3 = [61, 79]
rm_mines_lava_shrine4 = [61, 79]

# Biome 5 - Ruins
rm_mines_ruins_ritual_chamber = [81, 99]
rm_mines_ruins_basic1 = [81, 99]
rm_mines_ruins_large_switch = [81, 99]
rm_mines_ruins_basic5 = [81, 99]
rm_mines_ruins_basic2 = [81, 99]
rm_mines_ruins_basic3 = [81, 99]
rm_mines_ruins_basic4 = [81, 99]
rm_mines_ruins_switch2 = [81, 99]
rm_mines_ruins_switch3 = [81, 99]
rm_mines_ruins_switch4 = [81, 99]
rm_mines_ruins_switch5 = [81, 99]
rm_mines_ruins_whirlpool1 = [81, 99]
rm_mines_ruins_whirlpool2 = [81, 99]
rm_mines_ruins_whirlpool3 = [81, 99]
rm_mines_ruins_whirlpool4 = [81, 99]
rm_mines_ruins_whirlpool5 = [81, 99]
rm_mines_ruins_shrine1 = [81, 99]
rm_mines_ruins_shrine2 = [81, 99]
rm_mines_ruins_shrine3 = [81, 99]
rm_mines_ruins_shrine4 = [81, 99]
rm_mines_ruins_shrine5 = [81, 99]
rm_mines_ruins_treasure = [81, 99]
rm_mines_ruins_arena1 = [81, 99]
rm_mines_ruins_arena2 = [81, 99]
rm_mines_ruins_arena3 = [81, 99]

# for being replaced later
rm_mines_basement_no_elevator = [21, 99]
rm_mines_basement_elevator = [20, 99]
rm_mines_basement_treasure = [41, 99]
