# To force a floor to appear on a particular level, notate it below!

# Upper Mines Biome Floors
rm_mines_upper_floor1 = 1
rm_mines_upper_elevator5 = 5
rm_mines_upper_elevator10 = 10
rm_mines_upper_elevator15 = 15
# Tide Cavern Biome Floors
rm_mines_tide_floor21 = 21
rm_mines_tide_elevator25 = 25
rm_mines_tide_elevator30 = 30
rm_mines_tide_elevator35 = 35
# Deep Earth Biome Floors
rm_mines_deep_41 = 41
rm_mines_deep_45 = 45
rm_mines_deep_50 = 50
rm_mines_deep_55 = 55
# Lava Caves Biome Floors
rm_mines_lava_61 = 61
rm_mines_lava_65 = 65
rm_mines_lava_70 = 70
rm_mines_lava_75 = 75
# Ruins Biome Floors
rm_mines_ruins_81 = 81
rm_mines_ruins_85 = 85
rm_mines_ruins_95 = 95
