[standard]
	upper = 20
	tide_caverns = 20
	deep_earth = 22
	lava_caves = 20
	ruins = 20

[interact]
	upper = 0
	tide_caverns = 2
	deep_earth = 2
	lava_caves = 2
	ruins = 2

[offering] #Shrine
	upper = 0
	tide_caverns = 2
	deep_earth = 2
	lava_caves = 2
	ruins = 2

[ladder_choice]
	upper = 0
	tide_caverns = 0
	deep_earth = 0
	lava_caves = 0
	ruins = 0

[fountain]
	upper = 0
	tide_caverns = 0
	deep_earth = 2
	lava_caves = 2
	ruins = 2

[enemy]
	upper = 0
	tide_caverns = 0
	deep_earth = 0
	lava_caves = 0
	ruins = 3

[treasure]
	upper = 0
	tide_caverns = 0
	deep_earth = 0
	lava_caves = 0
	ruins = 0

[ritual]
	upper = 0
	tide_caverns = 0
	deep_earth = 0
	lava_caves = 0
	ruins = 0
