[balor_four_hearts]
kind = "gameplay_triggered"
speaker = "hemlock"
portrait = "happy"
local = "Hey there, [Ari]! Looking for Balor?"
next = "1"

[balor_four_hearts.1]
speaker = "hemlock"
portrait = "neutral"
local = "Thought so. He had to step out for a moment, but he said you're welcome to head up to his room and he'll meet you there."
next = "2"

[balor_four_hearts.2]
speaker = "hemlock"
portrait = "neutral"
local = "It's just up the steps, first door on the left!"
next = "3"

[balor_four_hearts.3]
no_speaker = true
local = "\"I've secured a reliable supply line from the Capital by adding to the bulk orders made by neighboring towns. From there, I can handle the final transport of goods to Mistria myself.\""
next = "4"

[balor_four_hearts.4]
no_speaker = true
local = """"This will keep my prices low until Mistria stabilizes..." """
next = "5"

[balor_four_hearts.5]
no_speaker = true
local = """"Despite Nora's grumbling, she knows that Mistria is in a precarious position and the town needs every advantage they can muster." """
next = "6"

[balor_four_hearts.6]
no_speaker = true
local = "You probably shouldn't be reading this..."
prompts = [{ local = "I should wait for Balor.", next = "7" }, { local = "Continue reading.", next = "8" }]

[balor_four_hearts.7]
no_speaker = true
local = "..."
next = "9"

[balor_four_hearts.8]
no_speaker = true
local = "The next several pages feature column after column of numbers monitoring item prices and tedious order details going back several months."
next = "9"

[balor_four_hearts.9]
speaker = "balor"
portrait = "neutral"
local = "There you are! Sorry about that, had a delivery come in unexpectedly."
next = "10"

[balor_four_hearts.10]
speaker = "balor"
portrait = "sigh"
local = "I suppose the blame is on me for leaving my journal out."
next = "11"

[balor_four_hearts.11]
speaker = "balor"
portrait = "ugh"
local = "I hope I can trust your discretion on this."
prompts = [{ local = "But there's nothing bad here...", next = "12" }, { local = "It looks like you're working hard to help!", next = "13" }]

[balor_four_hearts.12]
speaker = "balor"
portrait = "think"
local = "Mistria has been in a delicate position since the earthquake, there's no need to remind everyone."
next = "14"

[balor_four_hearts.13]
speaker = "balor"
portrait = "angry_blush"
local = "That's-!"
next = "14"

[balor_four_hearts.14]
speaker = "balor"
portrait = "sigh"
effect = "sigh"
local = "Listen."
next = "15"

[balor_four_hearts.15]
speaker = "balor"
portrait = "think"
local = "I don't want you getting the wrong idea. What benefits the town benefits me, understand?"
next = "16"

[balor_four_hearts.16]
speaker = "balor"
portrait = "neutral"
local = "Mistria has the potential to be a major influence in Aldaria, and I want to get in on the ground floor."
next = "17"

[balor_four_hearts.17]
speaker = "balor"
portrait = "wink"
local = "I assume you do as well, since you moved here. Mistria will recover, we'll both make our fortunes, and then we can all go our separate ways."
prompts = [{ local = "I guess I see your point...", next = "18" }, { local = "But you seem to really like it here...", next = "19" }]

[balor_four_hearts.18]
speaker = "balor"
portrait = "neutral"
local = "Excellent. I knew you were a kindred spirit the moment I met you."
next = "20"

[balor_four_hearts.19]
speaker = "balor"
portrait = "angry_blush"
local = "A merchant needs to make his client's concerns his own, that's all."
next = "20"

[balor_four_hearts.20]
speaker = "balor"
portrait = "neutral"
local = "On that note, let's get down to business."
next = "21"

[balor_four_hearts.21]
speaker = "balor"
portrait = "wink"
local = "You've been doing a great job with your shipments. In a short period of time you've become one of my key suppliers."
next = "22"

[balor_four_hearts.22]
speaker = "balor"
portrait = "neutral"
local = "My advice is to continue to diversify what you sell. Mistria needs all kinds of support to get back on its feet, so focusing on just one or two areas won't cut it."
next = "23"

[balor_four_hearts.23]
speaker = "balor"
portrait = "sly"
local = "Remember, business comes first, alright? There's a lot of profit to be made in Mistria for those with the eye for it."
next = "24"

[balor_four_hearts.24]
speaker = "balor"
portrait = "wink"
local = "And after that, who knows? The world awaits!"
