# engagement ring line
[engagement_ring_celine]
kind = "gameplay_triggered"
actions = [
    { bark = { bark = "cute_face", npc = "celine" } },
    { cutscene = "celine_ten_hearts" }
]
speaker = "celine"
portrait = "neutral"
local = "What is it, [Ari]? You look like you have something on your mind."
next = "1"

[engagement_ring_celine.1]
speaker = "celine"
portrait = "embarrassed"
local = "You do? I knew it!"
next = "2"

[engagement_ring_celine.2]
speaker = "celine"
portrait = "happy"
local = "Why don't we take a walk and talk about it?"
next = "3"

[engagement_ring_celine.3]
speaker = "celine"
portrait = "shy_blush"
local = "I know! How about we head up to the $Summit$?"

# 10 heart scene
[celine_ten_hearts]
kind = "gameplay_triggered"
speaker = "celine"
portrait = "blush_closed_eyes"
local = "Wow... It's beautiful, isn't it?"
next = "1"

[celine_ten_hearts.1]
speaker = "celine"
portrait = "neutral"
local = "I can't believe I used to get nervous about coming up here..."
next = "2"

[celine_ten_hearts.2]
speaker = "celine"
portrait = "blush"
local = "Now it's my favorite place in all of Mistria."
prompts = [
    { local = "Mine too.", next = "3" },
    { local = "My favorite place is wherever you are...", next = "4" }
]

[celine_ten_hearts.3]
speaker = "celine"
portrait = "happy"
local = "Really? That makes me so happy! There's really no place like it."
next = "5"

[celine_ten_hearts.4]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "[Ari]! You're so sweet, hehe."
next = "5"

[celine_ten_hearts.5]
speaker = "celine"
portrait = "shy_blush"
local = "Looking out over the world... at all of nature's endless glory..."
next = "6"

[celine_ten_hearts.6]
speaker = "celine"
portrait = "sweat"
local = "I can't help but think about how all of this started. You and I, searching for a lost flower."
next = "7"

[celine_ten_hearts.7]
speaker = "celine"
portrait = "happy"
local = "I remember how surprised I was back when you first agreed to go look for the seed with me!"
prompts = [
    { local = "It took some perseverance, but it was fun too!", next = "8" },
    { local = "Honestly, it was a good excuse to spend more time with you...", next = "10" }
]

[celine_ten_hearts.8]
speaker = "celine"
portrait = "laugh"
local = "Yeah... you're right. It was fun, wasn't it?"
next = "9"

[celine_ten_hearts.9]
speaker = "celine"
portrait = "embarrassed"
local = "And it was definitely worth the hard work, in the end."
next = "13"

[celine_ten_hearts.10]
speaker = "celine"
portrait = "blush_special"
local = "[Ari]!"
next = "11"

[celine_ten_hearts.11]
speaker = "celine"
portrait = "embarrassed"
local = "Well, since you admit it... I was pretty glad of the excuse myself."
next = "12"

[celine_ten_hearts.12]
speaker = "celine"
portrait = "laugh"
local = "We had fun, didn't we? And in the end, it was worth the hard work."
next = "13"

[celine_ten_hearts.13]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "..."
next = "14"

[celine_ten_hearts.14]
speaker = "celine"
portrait = "think"
local = "You know, when I first moved out of my parent's house and into my own place, it felt like I had all this energy but nowhere to use it."
next = "15"

[celine_ten_hearts.15]
speaker = "celine"
portrait = "think_special"
local = "I know my mom was disappointed at the time, because I'd told her I didn't want to take over the store. Since I didn't have much else lined up, I think she worried about me a lot."
next = "16"

[celine_ten_hearts.16]
speaker = "celine"
portrait = "embarrassed"
local = "Researching the Codex Mistria gave me direction, but everyone considered it an eccentric hobby at best..."
next = "17"

[celine_ten_hearts.17]
speaker = "celine"
portrait = "shy_blush"
local = "Well, until you arrived."
next = "18"

[celine_ten_hearts.18]
speaker = "celine"
portrait = "think_special"
local = "You were the first person to really take my interest in it seriously."
next = "19"

[celine_ten_hearts.19]
speaker = "celine"
portrait = "teary_special"
local = "I'll never forget that, [Ari]."
next = "20"

[celine_ten_hearts.20]
speaker = "celine"
portrait = "sweat"
local = "Bringing that seed back from the brink of extinction should have been impossible..."
next = "21"

[celine_ten_hearts.21]
speaker = "celine"
portrait = "embarrassed"
local = "But together... we made it happen!"
prompts = [
    { local = "It was our growing feelings for each other that did it!", next = "22" },
    { local = "Only a master botanist like you could have made it sprout.", next = "23" }
]

[celine_ten_hearts.22]
speaker = "celine"
portrait = "shy_blush"
local = "It's like the flower knew how we felt even before we did..."
next = "24"

[celine_ten_hearts.23]
speaker = "celine"
portrait = "shy_blush"
local = "But it was our feelings for each other that made it bloom."
next = "24"

[celine_ten_hearts.24]
speaker = "celine"
portrait = "neutral"
local = "Speaking of which... I've been doing some research on our flower."
next = "25"

[celine_ten_hearts.25]
speaker = "celine"
portrait = "shy_blush"
local = "I took a cutting of it, and to propagate it, well..."
next = "26"

[celine_ten_hearts.26]
speaker = "celine"
portrait = "blush_special"
local = "I sat with it and... um. Thought about you."
next = "27"

[celine_ten_hearts.27]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "And it worked, another flower bloomed!"
next = [
    { target = "28_second", requires = [
        { cutscene_seen_celine_ten_hearts = true }
    ] },
    { target = "28_first", requires = [] }
]

[celine_ten_hearts.28_second]
speaker = "celine"
portrait = "embarrassed"
local = "I wanted to grow that $Revived Flower$ for you..."
next = "29_second"

[celine_ten_hearts.29_second]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "So when you look at it, I hope it reminds you of my feelings for you."
next = "30"

[celine_ten_hearts.28_first]
speaker = "celine"
portrait = "embarrassed"
local = "Here. This $Revived Flower$ is for you. I wanted to grow one for you so that whenever you see it..."
next = "29_first"

[celine_ten_hearts.29_first]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "You'll be reminded of my feelings for you."
next = "30"

[celine_ten_hearts.30]
speaker = "celine"
portrait = "blush_special"
local = "Oh!"
next = "31"

[celine_ten_hearts.31]
speaker = "celine"
portrait = "shy_blush"
local = "I've been talking your ear off, haven't I?"
next = "32"

[celine_ten_hearts.32]
speaker = "celine"
portrait = "embarrassed"
local = "You had something you wanted to speak to me about today too, didn't you?"
prompts = [
    { local = "I wanted to talk to you about our future... together.", next = "33" },
    { local = " Let's talk about it another time...", next = "41" }
]

[celine_ten_hearts.33]
speaker = "celine"
portrait = "blush_special"
local = "Ah!"
next = "34"

[celine_ten_hearts.34]
speaker = "celine"
portrait = "shy_blush"
local = "[Ari], are... are you-"
prompts = [
    { local = "I love you, Celine. Will you marry me?", next = "35" },
    { local = "Actually, let's talk about it more another day.", next = "41" }
]

[celine_ten_hearts.35]
writes = [
    { breakup_bump = true, expires = "3d" },
    { engagement_bump = true, expires = "2d" },
    { engagement_delay = true, expires = "20h" },
    { engagement_cap = false, expires = "3d" },
]
actions = [{ can_talk = "celine" }]
speaker = "celine"
portrait = "teary_special"
local = "Oh [Ari]! Yes!"
next = "36"

[celine_ten_hearts.36]
speaker = "celine"
portrait = "very_happy"
local = "Yes! Of course!"
next = "37"

[celine_ten_hearts.37]
speaker = "celine"
portrait = "teary_special"
local = "There is nothing I want more."
next = "38"

[celine_ten_hearts.38]
speaker = "celine"
portrait = "blush"
local = "I love you, [Ari]!"
next = "39"

[celine_ten_hearts.39]
speaker = "celine"
portrait = "embarrassed"
local = "I never imagined I could feel so much happiness..."
next = "40"

[celine_ten_hearts.40]
speaker = "celine"
portrait = "blush_closed_eyes"
local = "I can't wait to start planning our wedding!"

[celine_ten_hearts.41]
speaker = "celine"
portrait = "sweat"
local = "Oh? Sure. No worries!"
next = "42"

[celine_ten_hearts.42]
speaker = "celine"
portrait = "embarrassed"
local = "Just let me know when you want to talk, I can always make time for you."
