[celine_four_hearts]
kind = "gameplay_triggered"
speaker = "celine"
portrait = "neutral"
local = "Hey, [Ari]! You got my letter?"
next = "1"

[celine_four_hearts.1]
portrait = "happy"
local = "I'm so glad! Let's solve the mystery of this seed!"
next = "2"

[celine_four_hearts.2]
portrait = "neutral"
local = "So here's what we know already."
next = "3"

[celine_four_hearts.3]
portrait = "neutral"
local = "While I still haven't fully translated the codex, I'm pretty sure this section describes our seed."
next = "4"

[celine_four_hearts.4]
portrait = "think"
local = "It seems like the type of soil and the amount of watering are most important."
next = "5"

[celine_four_hearts.5]
portrait = "gloomy"
local = "But there seem to be other extra special conditions as well. Oh, I'm just not sure!"
prompts = [
	{ local = "Well let's start with what we do know!", next = "6" },
	{ local = "Nobody knows more about this seed than you!", next = "7" },
]

[celine_four_hearts.6]
portrait = "sweat"
local = "Ah, you're right. I'm getting ahead of myself."
next = "8"

[celine_four_hearts.7]
portrait = "laugh"
local = "Haha, that's a nice way of looking at it!"
next = "8"

[celine_four_hearts.8]
portrait = "neutral"
local = "For the type of soil, I tried to mimic the growing conditions where we found it. Rocky, with a good mix of clay."
next = "9"

[celine_four_hearts.9]
portrait = "think"
local = "But I think the seed could use a good wake-up call of nutrients. [Ari], could you add however much plant food you think best?"
next = "10"

[celine_four_hearts.10]
portrait = "wink"
local = "It's my own special blend!"
prompts = [
	{ local = "Let's add just a pinch and go from there.", next = "11" },
	{ local = "The more fertilizer the better!", next = "12" },
]

[celine_four_hearts.11]
portrait = "neutral"
local = "Sensible! This seed has been so patient, we can be patient too!"
next = "13"

[celine_four_hearts.12]
portrait = "happy"
local = "You're right! Who doesn't like a big breakfast!"
next = "13"

[celine_four_hearts.13]
portrait = "think"
local = "Now to water it..."
next = "14"

[celine_four_hearts.14]
portrait = "neutral"
local = "The seed has been dormant so long that I think it'd be hard to overwater it, but the pot has excellent drainage, so we should be okay in either case."
next = "15"

[celine_four_hearts.15]
portrait = "think"
local = "The book is no help, I can't translate this word here. [Ari], could you tell me what you think it says?"
prompts = [
	{ local = "Looks like we just want to dampen the soil...", next = "16" },
	{ local = "Looks like it wants us to douse it!", next = "16" },
]

[celine_four_hearts.16]
portrait = "sweat"
local = "You'd better do it, [Ari]. I'm too nervous!"
next = "17"

[celine_four_hearts.17]
portrait = "annoyed"
local = "Come on little seed... you can do it!"
next = "18"

[celine_four_hearts.18]
portrait = "happy"
effect = "drop"
local = "I guess it's silly of me to think anything would actually happen right away-"
next = "19"

[celine_four_hearts.19]
portrait = "neutral"
effect = "surprise"
local = "Oh my!"
next = "20"

[celine_four_hearts.20]
portrait = "very_happy"
local = "[Ari]! It looks just like the sprout from the book! It IS the flower from my childhood!"
next = "21"

[celine_four_hearts.21]
portrait = "neutral"
local = "We should make precise notes of everything we did while we can still remember. You don't mind, do you [Ari]?"
next = "22"

[celine_four_hearts.22]
portrait = "happy"
local = "I'll put on a pot of tea!"
