# this is just reflective of the spacing in game, but is not used in game
# this is so that external tools can accurately judge widths and what not
"w" = 8
"x" = 6
"h" = 6
"y" = 6
"n" = 6
"s" = 6
"f" = 5
"g" = 6
"_" = 6
"l" = 4
"o" = 6
"0" = 6
"1" = 6
"2" = 6
"3" = 6
"a" = 6
"4" = 6
"5" = 6
"6" = 6
"7" = 6
"8" = 6
"9" = 6
"m" = 8
"i" = 4
"d" = 6
" " = 3
"!" = 2
"\"" = 4
"#" = 6
"$" = 6
"%" = 7
"&" = 7
"'" = 2
"(" = 3
")" = 3
"*" = 4
"+" = 6
"," = 3
"-" = 6
"." = 2
"/" = 7
":" = 2
";" = 3
"<" = 7
"=" = 6
">" = 7
"?" = 6
"@" = 7
"A" = 7
"C" = 7
"D" = 7
"E" = 7
"F" = 7
"G" = 8
"H" = 7
"I" = 6
"J" = 7
"K" = 7
"L" = 6
"M" = 8
"N" = 7
"O" = 7
"P" = 7
"Q" = 7
"R" = 7
"S" = 8
"T" = 8
"U" = 7
"V" = 8
"W" = 8
"X" = 8
"Y" = 8
"Z" = 8
"[" = 3
"\\" = 7
"]" = 3
"^" = 6
"`" = 3
"u" = 6
"{" = 4
"|" = 2
"}" = 4
"~" = 7
"∎" = 6
"À" = 7
"Á" = 7
"v" = 6
"Â" = 7
"Ã" = 7
"Ç" = 7
"È" = 7
"b" = 6
"É" = 7
"Ê" = 7
"Ì" = 6
"Í" = 6
"Ñ" = 7
"p" = 6
"Ò" = 7
"Ó" = 7
"Õ" = 7
"Ù" = 7
"Ú" = 7
"à" = 6
"q" = 7
"á" = 6
"â" = 6
"ã" = 6
"ç" = 6
"è" = 6
"¡" = 2
"é" = 6
"¿" = 6
"ê" = 6
"«" = 7
"ì" = 4
"»" = 7
"í" = 4
"Ä" = 7
"ñ" = 6
"Ă" = 7
"ò" = 6
"Ë" = 7
"ó" = 6
"Ğ" = 8
"õ" = 6
"Î" = 6
"ù" = 6
"Ï" = 6
"ú" = 6
"İ" = 6
"©" = 8
"Ö" = 7
"Ô" = 7
"Ő" = 7
"Ø" = 7
"Ș" = 8
"Ş" = 8
"Š" = 8
"Ț" = 8
"Û" = 7
"Ü" = 7
"Ű" = 7
"k" = 6
"Ÿ" = 8
"Ý" = 8
"Ž" = 8
"ä" = 6
"ă" = 6
"å" = 6
"ë" = 6
"ğ" = 6
"î" = 4
"ï" = 4
"ı" = 4
"ö" = 6
"ô" = 6
"ő" = 6
"ø" = 6
"ș" = 6
"ş" = 6
"š" = 6
"ț" = 5
"û" = 6
"ü" = 6
"ű" = 6
"ÿ" = 6
"ý" = 6
"B" = 7
"ž" = 6
"Å" = 7
"t" = 5
"r" = 6
"j" = 3
"c" = 6
"e" = 6
"z" = 6
" " = 3
"¨" = 4
"°" = 4
"º" = 5
"ª" = 6
"—" = 9
"·" = 3
"×" = 6
"ß" = 7
"Æ" = 10
"æ" = 10
"Œ" = 11
"œ" = 10
"А" = 7
"Б" = 7
"В" = 7
"Г" = 6
"Д" = 8
"Е" = 7
"Ё" = 7
"Ж" = 10
"З" = 7
"И" = 7
"Й" = 7
"К" = 7
"Л" = 7
"М" = 8
"Н" = 7
"О" = 7
"П" = 7
"Р" = 7
"С" = 7
"Т" = 8
"У" = 7
"Ф" = 8
"Х" = 8
"Ц" = 8
"Ч" = 7
"Ш" = 8
"Щ" = 9
"Ъ" = 9
"Ы" = 8
"Ь" = 6
"Э" = 8
"Ю" = 9
"Я" = 7
"а" = 6
"б" = 6
"в" = 6
"г" = 5
"д" = 6
"е" = 6
"ё" = 6
"ж" = 8
"з" = 6
"и" = 6
"й" = 6
"к" = 6
"л" = 6
"м" = 6
"н" = 6
"о" = 6
"п" = 6
"р" = 6
"с" = 6
"т" = 6
"у" = 6
"ф" = 8
"х" = 6
"ц" = 7
"ч" = 6
"ш" = 8
"щ" = 9
"ъ" = 8
"ы" = 7
"ь" = 6
"э" = 7
"ю" = 8
"я" = 6
"Ґ" = 6
"І" = 6
"Ї" = 6
"Є" = 8
"ґ" = 5
"і" = 4
"ї" = 4
"є" = 7