[player_delivery_adeline]
writes = [
    { child_born_bump = true, expires = "2d" },
    { baby_born_timer = true, expires = "5d" }
]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "sad"
local = "Is everything okay, [Ari]?"
next = "1"

[player_delivery_adeline.1]
speaker = "adeline"
portrait = "shocked"
effect = "surprise"
local = "The baby is coming!?"
next = "2"

[player_delivery_adeline.2]
speaker = "adeline"
portrait = "sad"
local = "We have to get you to the Clinic right away!"
next = "3"

[player_delivery_adeline.3]
speaker = "valen"
portrait = "neutral"
local = "Congratulations, [Ari], Adeline!"
next = "4"

[player_delivery_adeline.4]
speaker = "valen"
portrait = "happy"
local = "You are now the proud parents of a healthy $baby girl$!"
next = "5"

[player_delivery_adeline.5]
speaker = "valen"
portrait = "neutral"
local = "Have you two decided $what you will name her$?"
next = "6"

[player_delivery_adeline.6]
speaker = "adeline"
portrait = "blush"
local = "Our little [child_0]..."
next = "7"

[player_delivery_adeline.7]
speaker = "adeline"
portrait = "happy_blush"
local = "Yes, that name suits her perfectly! It's as if it were already chosen for her long ago."
next = "8"

[player_delivery_adeline.8]
speaker = "valen"
portrait = "neutral"
local = "Now, before I let you head home..."
next = "9"

[player_delivery_adeline.9]
speaker = "valen"
portrait = "happy"
local = "Would you like me to $tell you more about caring for a child$?"
prompts = [
    { local = "Yes, please!", next = "11" },
    { local = "No, I think we've got it covered.", next = "10" }
]

[player_delivery_adeline.10]
speaker = "valen"
portrait = "neutral"
local = "Understood."
next = "11"

[player_delivery_adeline.11]
speaker = "valen"
portrait = "neutral"
local = "Well, I believe that's everything for the time being."
next = "12"

[player_delivery_adeline.12]
speaker = "valen"
portrait = "think_special"
local = "Now [Ari], make sure you take it easy and get plenty of rest."
next = "13"

[player_delivery_adeline.13]
speaker = "valen"
portrait = "raised_eyebrow"
local = "Do I make myself clear, Adeline? Don't let <he>him</he><she>her</she><they>them</they><it>it</it><none>[Ari]</none> overdo it!"
next = "14"

[player_delivery_adeline.14]
speaker = "valen"
portrait = "neutral"
local = "And remember, if you need anything at all, I'm just up the road."
next = "15"

[player_delivery_adeline.15]
speaker = "valen"
portrait = "happy"
effect = "cheery"
local = "Congratulations again!"
