[default]
	hp = 1000
	damage = 0
	essence = 0
	drops = []
	coin_count = [1, 3]

	starting_dir = [181, 181]

	damage_number_offset = -15

	iframes = 1
	gm_object = "obj_monster_mimic"
	hurtbox = "spr_monster_mimic_main_idle_south"

	patience_acknowledgement_reset = -120

	spit_frame = 17
	idle_variant = [120, 240]

	sprites = { misc = {} }

	status_effect_offset = -12
	fire_effect_offset = -1

	[default.tango]
		attack = "SoundEffects/Enemies/MimicChest/MimicChestAttackOpen"
		hurt = "SoundEffects/Enemies/MimicChest/MimicChestFlicker"
		acknowledgment = "SoundEffects/Enemies/EnemyAlerted"
		misc.idle_shake = "SoundEffects/Enemies/MimicChest/MimicChestRumble"
		misc.weak_damage = "SoundEffects/Enemies/TakeDamageFleshWeak"
		misc.strong_damage = "SoundEffects/Enemies/TakeDamageFleshStrong"

[mimic]
	damage = 20
	essence = 0

	[mimic.sprites]
		idle.north = "spr_monster_mimic_main_idle_south"
		idle.south = "spr_monster_mimic_main_idle_south"

		attack.north = "spr_monster_mimic_main_attack_south"
		attack.south = "spr_monster_mimic_main_attack_south"

		hurt.north = "spr_monster_mimic_main_hurt_south"
		hurt.south = "spr_monster_mimic_main_hurt_south"

		gobble.north = "spr_monster_mimic_main_eat_south"
		gobble.south = "spr_monster_mimic_main_eat_south"

		dying.north = "spr_monster_mimic_main_idle_south"
		dying.south = "spr_monster_mimic_main_idle_south"

		fade.north = "spr_monster_mimic_main_disappear_south"
		fade.south = "spr_monster_mimic_main_disappear_south"

		misc.idle_two = "spr_monster_mimic_main_idle_2_south"
