bio = "Sweet, bookish gardener who works part-time at her parents' General Store. Daughter of Nora and Holt, sister to Dell. "
birthday = { season = "summer", day = 14 }
loved_gifts = [
	"breath_of_fire",
	"crystal_rose",
	"essence_blossom",
	"frost_lily",
	"hydrangea",
	"middlemist",
	"plum_blossom",
	"rose",
	"snowdrop_anemone",
	"temple_flower",
]

liked_gifts = [

	"catmint",
	"celosia",
	"chrysanthemum",
	"cosmos",
	"crocus",
	"daffodil",
	"daisy",
	"dandelion",
	"heather",
	"iris",
	"jasmine",
	"lilac",
	"marigold",
	"poinsettia",
	"rose_tea",
	"snapdragon",
	"spring_salad",
	"sunflower",
	"tulip",
	"viola",
]

disliked_gift_tags = ["junk", "bugs", "weird_gift"]
hated_gift = "caterpillar"
name = "Celine"
aldarian_name = "SLN"
music = "Music/Npc Tracks/Celine"
outfits = [
	"spring",
	"spring_garden",
	"summer",
	"summer_garden",
	"autumn",
	"autumn_garden",
	"winter",
	"beach",
	"wedding",
]
tags = ["townsfolk", "general_store_family", "dateable"]
journal_portrait_offset = [-113, -40]
journal_background_color = [215, 249, 246]
date_photo_offset = [-1, 0]
job = "Gardener, Part-Timer"
roommate_routine = "celine_roommate"
proposal_cutscene = "celine_ten_hearts"
children = ["rowan"]
can_carry_child = true

icon_sprite = "spr_ui_generic_icon_npc_celine"
small_icon_sprite = "spr_ui_generic_icon_npc_small_celine"
small_outlined_icon_sprite = "spr_ui_generic_icon_npc_small_outline_celine"
dateable = true

[gossip]
	line = "celine_gossip"
	portrait = "happy"
	effect = "hearts"

[drink_preferences]
	"6" = ["black_tea", "green_tea"]
	"12" = ["green_tea", "lemonade"]
	"16" = ["wine", "white_wine", "rose_wine"]
	"20" = ["wine", "cocktail"]

[offsets]
	portrait = [-127, -65]
	sweat = [0, 10]
	hearts = [-2, 9]
	angry = [-4, 11]
	sparkles = [0, 9]
	sparkles_dark = [0, 9]
	sick = [1, 14]
	music_notes = [0, 6]
	intensity = [0, 0]
	surprise = [0, 9]
	shock = [4, 6]
	sigh = [-2, 5]
	loud = [7, 9]
	cheery = [0, 10]
	drop = [0, 5]

[child_portrait_fallbacks]
    very_happy = "happy"
    blush = "blush_closed_eyes"
    mad = "annoyed"
    concerned = "gloomy"
    sad = "gloomy"
    ugh = "gloomy"

[portraits]
	neutral = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	think = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	happy = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	wink = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	very_happy = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	blush = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	embarrassed = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	blush_closed_eyes = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	blush_special = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	annoyed = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	mad = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	angry_blush = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	gloomy = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	concerned = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	sad = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	laugh = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	sweat = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	ugh = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	think_special = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]
	teary_special = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	shy_blush = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	bath_neutral = [
		"beach",
	]
	shocked = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
	]

[cycles.idle]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	type = "linear"
	on_pause_speaking_turn = true

[cycles.walk]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	type = "linear"
	on_pause_speaking_turn = true
	on_pause_speaking = "idle"
	on_pause_background = "idle"

[cycles.blink]
	default_direction = "south"
	directions = ["south", "east"]
	outfits = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	type = "linear"

[cycles.shocked]
	default_direction = "south"
	directions = ["south"]
	outfits = ["spring", "spring_garden"]
	type = "complex"

[cycles.sit]
	default_direction = "south"
	directions = ["north", "south", "east"]
	is_seated = true
	outfits = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"wedding",
	]
	type = "linear"

[cycles.drink]
	default_direction = "south"
	directions = ["north", "south", "east"]
	is_seated = true
	outfits = ["spring", "summer", "autumn", "winter"]
	type = "linear"
	last_frame_hold = [240, 360]

[cycles.eat]
	default_direction = "south"
	directions = ["south", "east", "north"]
	is_seated = true
	outfits = ["spring", "summer", "autumn", "winter"]
	type = "linear"
	last_frame_hold = [240, 360]

[cycles.kiss]
	default_direction = "east"
	directions = ["east"]
	outfits = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
		"beach",
		"wedding",
	]
	type = "linear"

[cycles.action]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring", "summer", "autumn", "winter", "beach", "wedding"]
	type = "linear"
	last_frame_hold = [240, 360]
	on_pause_speaking = "idle"

[cycles.sleep]
	default_direction = "east"
	directions = ["east"]
	outfits = ["spring", "summer", "autumn", "winter"]
	type = "linear"

[cycles.bath_swim]
	default_direction = "south"
	directions = ["south", "east"]
	outfits = ["beach"]
	type = "linear"

[cycles.herb]
	default_direction = "south"
	directions = ["south"]
	outfits = ["spring"]
	type = "linear"
	on_pause_speaking = "idle"

[cycles.book_stand]
	default_direction = "south"
	directions = ["south"]
	outfits = ["spring", "summer", "autumn", "winter"]
	type = "complex"
	on_pause_speaking = "idle"

[cycles.book_sit]
	default_direction = "south"
	directions = ["south"]
	is_seated = true
	outfits = ["spring", "summer", "autumn", "winter"]
	type = "complex"
	on_pause_speaking = "sit"

[cycles.sweep]
	default_direction = "south"
	directions = ["south"]
	outfits = ["spring", "summer", "autumn", "winter"]
	type = "complex"
	on_pause_speaking = "idle"

[cycles.harvest]
	default_direction = "east"
	directions = ["east"]
	outfits = ["spring_garden", "summer_garden", "autumn_garden", "winter"]
	type = "linear"

[cycles.water]
	default_direction = "east"
	directions = ["east"]
	outfits = [
		"spring",
		"spring_garden",
		"summer",
		"summer_garden",
		"autumn",
		"autumn_garden",
		"winter",
	]
	type = "linear"
	on_pause_speaking = "idle"
