[juniper_two_hearts]
kind = "gameplay_triggered"
speaker = "olric"
portrait = "think"
local = "Will this really help me get shredded, Juniper?"
next = "1"

[juniper_two_hearts.1]
speaker = "juniper"
portrait = "sly"
local = """More than "shredded", if you can believe it. Whatever "shredded" means."""
next = "2"

[juniper_two_hearts.2]
speaker = "olric"
portrait = "happy"
local = "Wow!"
next = "3"

[juniper_two_hearts.3]
speaker = "juniper"
portrait = "sly"
local = "So don't be shy... hop to it!"
next = "4"

[juniper_two_hearts.4]
speaker = "olric"
portrait = "neutral"
local = "It... It's working! The power... it's coursing through me! I think."
next = "5"

[juniper_two_hearts.5]
speaker = "olric"
portrait = "neutral"
local = "Do my muscles look bigger?"
next = "6"

[juniper_two_hearts.6]
speaker = "juniper"
portrait = "happy"
local = "Colossal. I've outdone myself."
next = "7"

[juniper_two_hearts.7]
speaker = "juniper"
portrait = "think"
local = "The effects of my potion will fade with time, though..."
next = "8"

[juniper_two_hearts.8]
speaker = "juniper"
portrait = "angry_brows"
local = "So do come back when you feel like your oh-so-ordinary self again."
next = "9"

[juniper_two_hearts.9]
speaker = "olric"
portrait = "neutral"
local = "You got it, Juni! I hope you can get it to taste better next time, blugh."
next = "10"

[juniper_two_hearts.10]
speaker = "juniper"
portrait = "wink"
local = "Hmm, how does carrot-flavored sound?"
next = "11"

[juniper_two_hearts.11]
speaker = "olric"
portrait = "neutral"
local = "Pretty good, for some reason..."
next = "12"

[juniper_two_hearts.12]
speaker = "olric"
portrait = "neutral"
local = "Wow, I feel amazing! I could do a hundred laps around the town square!"
next = "13"

[juniper_two_hearts.13]
speaker = "olric"
portrait = "neutral"
local = "Bye Juniper! Bye [Ari]!"
next = "14"

[juniper_two_hearts.14]
speaker = "juniper"
portrait = "angry_brows"
local = "Now you. Come here."
next = "15"

[juniper_two_hearts.15]
speaker = "juniper"
portrait = "neutral"
local = "[Ari]. The mysterious wanderer who came to Mistria."
next = "16"

[juniper_two_hearts.16]
speaker = "juniper"
portrait = "angry_brows"
local = "I was wondering when you'd catch me working on my little experiments."
next = "17"

[juniper_two_hearts.17]
speaker = "juniper"
portrait = "sly"
local = "So tell me... what brings you here, adventurer?"
prompts = [
	{ local = "A... bath? At the Bathhouse?", next = "18" },
	{ local = "The health tonic? From the message board?", next = "19" },
]

[juniper_two_hearts.18]
speaker = "juniper"
portrait = "annoyed"
local = "Oh, let's not play games. Unless... you're serious?"
next = "20"

[juniper_two_hearts.19]
speaker = "juniper"
portrait = "annoyed"
local = "You're joking. You're joking, right?"
next = "20"

[juniper_two_hearts.20]
speaker = "juniper"
portrait = "unimpressed"
local = "Arcane energies flow around you, [Ari], but I see I've misunderstood their meaning."
next = "21"

[juniper_two_hearts.21]
speaker = "juniper"
portrait = "unimpressed"
local = "I thought you were someone like me, here to stake out your territory. But it's clear to me now. You're hardly a threat."
next = "22"

[juniper_two_hearts.22]
speaker = "juniper"
portrait = "think"
local = "Allow me to explain in terms that even you can understand. I came to Mistria because the magic here is unique. It bears studying."
next = "23"

[juniper_two_hearts.23]
speaker = "juniper"
portrait = "sly"
local = "The villagers being so pliable... that's been a nice bonus. They drink any concoction I give them."
prompts = [
	{ local = "You're using the townsfolk to test your potions? You should leave them alone.", next = "24" },
	{ local = "Can't we all just get along?", next = "25" },
]

[juniper_two_hearts.24]
speaker = "juniper"
portrait = "angry_brows"
local = "Oh, say it again. I'm quaking in my boots."
next = "26"

[juniper_two_hearts.25]
speaker = "juniper"
portrait = "angry_brows"
local = "Oh, you sweet, naive dear."
next = "26"

[juniper_two_hearts.26]
speaker = "juniper"
portrait = "neutral"
local = "I have a lovely idea. I promise to leave the poor, defenseless townsfolk alone..."
next = "27"

[juniper_two_hearts.27]
speaker = "juniper"
portrait = "sly"
local = "If YOU take their place and become my guinea pig."
next = "28"

[juniper_two_hearts.28]
speaker = "juniper"
portrait = "wink"
local = "Yes, this could be the beginning of a beautiful... relationship."
prompts = [
	{ local = "Sounds fun.", next = "29" },
	{ local = "Do I have a choice?", next = "30" },
]

[juniper_two_hearts.29]
speaker = "juniper"
portrait = "think"
local = "Fun? My my... there are hidden depths to you, [Ari]."
next = "31"

[juniper_two_hearts.30]
speaker = "juniper"
portrait = "sly"
local = "It's you or the denizens of Mistria, so... not really."
next = "31"

[juniper_two_hearts.31]
speaker = "juniper"
portrait = "neutral"
local = "Well... I'm simply thrilled to reach an accord with you. Look at you... protecting your fellow villagers. How admirable. How brave!"
next = "32"

[juniper_two_hearts.32]
speaker = "juniper"
portrait = "angry_brows"
local = "How cute."
next = "33"

[juniper_two_hearts.33]
speaker = "juniper"
portrait = "laugh"
local = "OH HO HO HO!"
