[engagement_ring_juniper]
kind = "gameplay_triggered"
actions = [
	{ bark = { bark = "cute_face", npc = "juniper" } },
	{ cutscene = "juniper_ten_hearts" }
]
speaker = "juniper"
portrait = "neutral"
local = "What is it, [Ari]?"
next = "1"

[engagement_ring_juniper.1]
speaker = "juniper"
portrait = "happy_blush"
local = "You want to talk to me about something? Sure, I have some time."
next = "2"

[engagement_ring_juniper.2]
speaker = "juniper"
portrait = "think_special"
local = "Why don't we take a walk up to the $Summit$?"

# ten heart scene
[juniper_ten_hearts]
kind = "gameplay_triggered"
speaker = "juniper"
portrait = "neutral"
local = "It's so peaceful..."
next = "1"

[juniper_ten_hearts.1]
speaker = "juniper"
portrait = "happy_blush"
local = "What did I tell you? It's just the two of us up here today."
next = "2"

[juniper_ten_hearts.2]
speaker = "juniper"
portrait = "think"
local = "I don't get the chance to come to the Summit often."
next = "3"

[juniper_ten_hearts.3]
speaker = "juniper"
portrait = "neutral"
local = "The scenery is something else..."
next = "4"

[juniper_ten_hearts.4]
speaker = "juniper"
portrait = "happy"
local = "Mistria really is a special place, isn't it?"
next = "5"

[juniper_ten_hearts.5]
speaker = "juniper"
portrait = "unimpressed"
local = "I used to think it was just another backwater village."
next = "6"

[juniper_ten_hearts.6]
speaker = "juniper"
portrait = "think_special"
local = "Turns out I just couldn't see what was right in front of me."
prompts = [
	{ local = "You were too busy keeping your eyes on me...", next = "7" },
	{ local = "We've both grown a lot since coming to Mistria, haven't we?", next = "9" }
]

[juniper_ten_hearts.7]
speaker = "juniper"
portrait = "embarrassed"
local = "[Ari]!"
next = "8"

[juniper_ten_hearts.8]
speaker = "juniper"
portrait = "think_special"
local = "Well... you're not wrong."
next = "10"

[juniper_ten_hearts.9]
speaker = "juniper"
portrait = "neutral"
local = "I suppose you're right."
next = "10"

[juniper_ten_hearts.10]
speaker = "juniper"
portrait = "closed_eyes"
local = "It's funny, looking back on those days."
next = "11"

[juniper_ten_hearts.11]
speaker = "juniper"
portrait = "sad_special"
local = "I never wanted to admit it at the time, but I was actually pretty lonely when I first moved here."
next = "12"

[juniper_ten_hearts.12]
speaker = "juniper"
portrait = "unimpressed"
local = "I've always had a tendency to keep people at a distance."
next = "13"

[juniper_ten_hearts.13]
speaker = "juniper"
portrait = "neutral"
local = "I used to, anyway."
next = "14"

[juniper_ten_hearts.14]
speaker = "juniper"
portrait = "neutral_blush"
local = "That started to change after I met you, [Ari]."
next = "15"

[juniper_ten_hearts.15]
speaker = "juniper"
portrait = "think_special"
local = "Somewhere along the way, I began to let other people in."
next = "16"

[juniper_ten_hearts.16]
speaker = "juniper"
portrait = "sad_special"
local = "The truth is, if it wasn't for you..."
next = "17"

[juniper_ten_hearts.17]
speaker = "juniper"
portrait = "sincere_special"
local = "I'm not sure how things might have turned out. I was selfish, inconsiderate-"
prompts = [
	{ local = "It's thanks to you that I'm alive and well!", next = "18" },
	{ local = "Well if it weren't for you, I might be a lizard by now!", next = "19" }
]

[juniper_ten_hearts.18]
speaker = "juniper"
portrait = "embarrassed"
local = "O-oh. Well..."
next = "20"

[juniper_ten_hearts.19]
speaker = "juniper"
portrait = "embarrassed"
local = "A lizard!?"
next = "20"

[juniper_ten_hearts.20]
speaker = "juniper"
portrait = "think_special"
local = "You're talking about the $Sealing Scroll$, right?"
next = "21"

[juniper_ten_hearts.21]
speaker = "juniper"
portrait = "sad"
local = "Removing the curse from you was the least I could do."
next = "22"

[juniper_ten_hearts.22]
speaker = "juniper"
portrait = "think_special"
local = "But you know, [Ari]... it's funny you should bring that up."
next = "23"

[juniper_ten_hearts.23]
speaker = "juniper"
portrait = "angry_blush"
local = "I've spent a lot of time reflecting on everything that happened."
next = "24"

[juniper_ten_hearts.24]
speaker = "juniper"
portrait = "think_special"
local = "I realized that I should have done more to protect you in the first place."
next = "25"

[juniper_ten_hearts.25]
speaker = "juniper"
portrait = "sad"
local = "If anything were to ever happen to you, I-"
next = "26"

[juniper_ten_hearts.26]
speaker = "juniper"
portrait = "angry_blush"
local = "Well, I won't ever let anything like that happen to you again!"
next = [
	{ target = "27_second", requires = [
		{ cutscene_seen_juniper_ten_hearts = true }
	] },
	{ target = "27_first", requires = [] }
]

[juniper_ten_hearts.27_second]
speaker = "juniper"
portrait = "happy_blush"
local = "That's why I made that $Protection Scroll$ for you."
next = "28_second"

[juniper_ten_hearts.28_second]
speaker = "juniper"
portrait = "think_special"
local = "It's a kind of good-luck charm."
next = "29_second"

[juniper_ten_hearts.29_second]
speaker = "juniper"
portrait = "blush"
local = "I just wanted you to know... I'll always be here for you, [Ari]."
next = "30"

[juniper_ten_hearts.27_first]
speaker = "juniper"
portrait = "happy_blush"
local = "Here. It took longer than I planned, but I made this for you."
next = "28_first"

[juniper_ten_hearts.28_first]
speaker = "juniper"
portrait = "think_special"
local = "Consider it something of a good-luck charm."
next = "29_first"

[juniper_ten_hearts.29_first]
speaker = "juniper"
portrait = "blush"
local = "It's my way of saying... I'll always be here for you, [Ari]."
next = "30"

[juniper_ten_hearts.30]
speaker = "juniper"
portrait = "think_special"
local = "Whatever life throws your way, I'll help you get through it."
next = "31"

[juniper_ten_hearts.31]
speaker = "juniper"
portrait = "sincere_special"
local = "Even if your magic is stronger than mine. It doesn't matter."
next = "32"

[juniper_ten_hearts.32]
speaker = "juniper"
portrait = "happy_blush"
local = "If it came to it, I'd give it all up if it meant you'd stay safe by my side."
next = "33"

[juniper_ten_hearts.33]
speaker = "juniper"
portrait = "think_special"
local = "A-anyway. There was something else you wanted to talk about, right?"
prompts = [
	{ local = "I wanted to talk to you about our future together...", next = "34" },
	{ local = "Let's talk about it another time...", next = "44" }
]

[juniper_ten_hearts.34]
speaker = "juniper"
portrait = "embarrassed"
local = "Our-"
next = "35"

[juniper_ten_hearts.35]
speaker = "juniper"
portrait = "neutral_blush"
local = "Our future together?"
prompts = [
	{ local = "I love you, Juniper. Will you marry me?", next = "36" },
	{ local = "Actually, let's talk about it more another day.", next = "44" }
]

[juniper_ten_hearts.36]
writes = [
	{ breakup_bump = true, expires = "3d" },
	{ engagement_bump = true, expires = "2d" },
	{ engagement_delay = true, expires = "20h" },
	{ engagement_cap = false, expires = "3d" }
]
actions = [{ can_talk = "juniper" }]
speaker = "juniper"
portrait = "teary_blush"
local = "[Ari]..."
next = "37"

[juniper_ten_hearts.37]
speaker = "juniper"
portrait = "happy_blush"
local = "Yes!"
next = "38"

[juniper_ten_hearts.38]
speaker = "juniper"
portrait = "embarrassed"
local = "YES!"
next = "39"

[juniper_ten_hearts.39]
speaker = "juniper"
portrait = "wild_laugh_blush"
local = "OH HO HO HO HO!"
next = "40"

[juniper_ten_hearts.40]
speaker = "juniper"
portrait = "embarrassed"
local = "I can't believe this is really happening... I'm going to be your wife!"
next = "41"

[juniper_ten_hearts.41]
speaker = "juniper"
portrait = "teary_blush"
local = "I'm so happy, [Ari]!"
next = "42"

[juniper_ten_hearts.42]
speaker = "juniper"
portrait = "neutral_blush"
local = "I love you so much!"
next = "43"

[juniper_ten_hearts.43]
speaker = "juniper"
portrait = "happy_blush"
local = "I can't wait to start planning our wedding!"

[juniper_ten_hearts.44]
speaker = "juniper"
portrait = "unimpressed"
local = "Oh? Sure, that's no problem."
next = "45"

[juniper_ten_hearts.45]
speaker = "juniper"
portrait = "blush"
local = "Whenever you want to talk, you know where to find me."
