[default]
	day_to_stage = [
		"grass_small",
		"grass_small",
		"grass_small",
		"grass_medium",
		"grass_medium",
		"grass_medium",
		"grass_medium",
		"grass_medium",
		"grass_medium",
		"grass_large",
	]
	hp = 1
	offset = [2, 6]
	size = [1, 1]
	sound_on_collide = "SoundEffects/Objects/TallGrassRustle"
	stunt_chance = 0

	[default.on_destruction_particles]
		spring = [
			"spr_part_weed_small_spring_1",
			"spr_part_weed_small_spring_2",
		]
		summer = [
			"spr_part_weed_small_summer_1",
			"spr_part_weed_small_summer_2",
		]
		fall = [
			"spr_part_weed_small_autumn_1",
			"spr_part_weed_small_autumn_2",
		]
		winter = [
			"spr_part_weed_small_winter_1",
		]

[grass_small]
	stunt_chance = 20

	[grass_small.sprites]
		spring = [
			"spr_farm_grass_small_c1_spring_step",
			"spr_farm_grass_small_c2_spring_step",
		]
		summer = [
			"spr_farm_grass_small_c1_summer_step",
			"spr_farm_grass_small_c2_summer_step",
		]
		fall = [
			"spr_farm_grass_small_c1_autumn_step",
			"spr_farm_grass_small_c2_autumn_step",
			"spr_farm_grass_small_c3_autumn_step",
			"spr_farm_grass_small_c4_autumn_step",
			"spr_farm_grass_small_c5_autumn_step",
			"spr_farm_grass_small_c6_autumn_step",
		]
		winter = [
			"spr_farm_grass_small_c1_winter_step",
			"spr_farm_grass_small_c2_winter_step",
		]
	[grass_small.outline_sprites]
		spring = [
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
		]
		summer = [
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
		]
		fall = [
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
		]
		winter = [
			"spr_farm_grass_small_outline_step",
			"spr_farm_grass_small_outline_step",
		]

[grass_medium]
	stunt_chance = 20

	[[grass_medium.drops]]
		item = "hay"
		chance = 5.0

	[[grass_medium.drops]]
		item = "grass_seed"
		chance = 5.0

	[grass_medium.sprites]
		spring = [
			"spr_farm_grass_medium_c1_spring_step",
			"spr_farm_grass_medium_c2_spring_step",
		]
		summer = [
			"spr_farm_grass_medium_c1_summer_step",
			"spr_farm_grass_medium_c2_summer_step",
		]
		fall = [
			"spr_farm_grass_medium_c1_autumn_step",
			"spr_farm_grass_medium_c2_autumn_step",
			"spr_farm_grass_medium_c3_autumn_step",
			"spr_farm_grass_medium_c4_autumn_step",
			"spr_farm_grass_medium_c5_autumn_step",
			"spr_farm_grass_medium_c6_autumn_step",
		]
		winter = [
			"spr_farm_grass_medium_c1_winter_step",
			"spr_farm_grass_medium_c2_winter_step",
		]
	[grass_medium.outline_sprites]
		spring = [
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
		]
		summer = [
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
		]
		fall = [
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
		]
		winter = [
			"spr_farm_grass_medium_outline_step",
			"spr_farm_grass_medium_outline_step",
		]

[grass_large]
	[[grass_large.drops]]
		item = "hay"
		chance = 7.5

	[[grass_large.drops]]
		item = "grass_seed"
		chance = 7.5

	[grass_large.sprites]
		spring = [
			"spr_farm_grass_big_c1_spring_step",
			"spr_farm_grass_big_c2_spring_step",
			"spr_farm_grass_big_flower_c1_spring_step",
			"spr_farm_grass_big_flower2_c1_spring_step",
			"spr_farm_grass_big_flower3_c1_spring_step",
			"spr_farm_grass_big_flower4_c1_spring_step",
			"spr_farm_grass_big_flower5_c1_spring_step",
			"spr_farm_grass_big_flower6_c1_spring_step",
			"spr_farm_grass_big_flower_c2_spring_step",
			"spr_farm_grass_big_flower2_c2_spring_step",
			"spr_farm_grass_big_flower3_c2_spring_step",
			"spr_farm_grass_big_flower4_c2_spring_step",
			"spr_farm_grass_big_flower5_c2_spring_step",
			"spr_farm_grass_big_flower6_c2_spring_step",
		]
		summer = [
			"spr_farm_grass_big_c1_summer_step",
			"spr_farm_grass_big_c2_summer_step",
			"spr_farm_grass_big_flower_c1_summer_step",
			"spr_farm_grass_big_flower2_c1_summer_step",
			"spr_farm_grass_big_flower_c2_summer_step",
			"spr_farm_grass_big_flower2_c2_summer_step",
		]
		fall = [
			"spr_farm_grass_big_c1_autumn_step",
			"spr_farm_grass_big_c2_autumn_step",
			"spr_farm_grass_big_c3_autumn_step",
			"spr_farm_grass_big_c4_autumn_step",
			"spr_farm_grass_big_c5_autumn_step",
			"spr_farm_grass_big_c6_autumn_step",
		]
		winter = [
			"spr_farm_grass_big_c1_winter_step",
			"spr_farm_grass_big_c2_winter_step",
		]
	[grass_large.outline_sprites]
		spring = [
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_flower_outline_step",
			"spr_farm_grass_big_flower2_outline_step",
			"spr_farm_grass_big_flower3_outline_step",
			"spr_farm_grass_big_flower4_outline_step",
			"spr_farm_grass_big_flower5_outline_step",
			"spr_farm_grass_big_flower6_outline_step",
			"spr_farm_grass_big_flower_outline_step",
			"spr_farm_grass_big_flower2_outline_step",
			"spr_farm_grass_big_flower3_outline_step",
			"spr_farm_grass_big_flower4_outline_step",
			"spr_farm_grass_big_flower5_outline_step",
			"spr_farm_grass_big_flower6_outline_step",
		]
		summer = [
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_flower_outline_step",
			"spr_farm_grass_big_flower2_outline_step",
			"spr_farm_grass_big_flower_outline_step",
			"spr_farm_grass_big_flower2_outline_step",
		]
		fall = [
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
		]
		winter = [
			"spr_farm_grass_big_outline_step",
			"spr_farm_grass_big_outline_step",
		]

[marsh_grass_small]
	day_to_stage = [
		"marsh_grass_small",
		"marsh_grass_small",
		"marsh_grass_small",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_large",
	]

	[marsh_grass_small.sprites]
		spring = [
			"spr_easternroad_marsh_grass_small_c1_spring",
			"spr_easternroad_marsh_grass_small_c2_spring",
		]
		summer = [
			"spr_easternroad_marsh_grass_small_c1_summer",
			"spr_easternroad_marsh_grass_small_c2_summer",
		]
		fall = [
			"spr_easternroad_marsh_grass_small_c1_autumn",
			"spr_easternroad_marsh_grass_small_c2_autumn",
		]
		winter = [
			"spr_easternroad_marsh_grass_small_c1_winter",
			"spr_easternroad_marsh_grass_small_c2_winter",
		]
	[marsh_grass_small.outline_sprites]
		spring = [
			"spr_easternroad_marsh_grass_small_outline",
			"spr_easternroad_marsh_grass_small_outline",
		]
		summer = [
			"spr_easternroad_marsh_grass_small_outline",
			"spr_easternroad_marsh_grass_small_outline",
		]
		fall = [
			"spr_easternroad_marsh_grass_small_outline",
			"spr_easternroad_marsh_grass_small_outline",
		]
		winter = [
			"spr_easternroad_marsh_grass_small_outline",
			"spr_easternroad_marsh_grass_small_outline",
		]

	[marsh_grass_small.on_destruction_particles]
		spring = [
			"spr_part_easternroad_marsh_grass_c1_spring",
			"spr_part_easternroad_marsh_grass_c2_spring",
		]
		summer = [
			"spr_part_easternroad_marsh_grass_c1_summer",
			"spr_part_easternroad_marsh_grass_c2_summer",
		]
		fall = [
			"spr_part_easternroad_marsh_grass_c1_autumn",
			"spr_part_easternroad_marsh_grass_c2_autumn",
		]
		winter = [
			"spr_part_easternroad_marsh_grass_c1_winter",
			"spr_part_easternroad_marsh_grass_c2_winter",
		]

[marsh_grass_medium]
	day_to_stage = [
		"marsh_grass_small",
		"marsh_grass_small",
		"marsh_grass_small",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_large",
	]

	[[marsh_grass_medium.drops]]
		item = "grass_seed"
		chance = 5

	[[marsh_grass_medium.drops]]
		item = "hay"
		chance = 5

	[marsh_grass_medium.sprites]
		spring = [
			"spr_easternroad_marsh_grass_medium_c1_spring",
			"spr_easternroad_marsh_grass_medium_c2_spring",
		]
		summer = [
			"spr_easternroad_marsh_grass_medium_c1_summer",
			"spr_easternroad_marsh_grass_medium_c2_summer",
		]
		fall = [
			"spr_easternroad_marsh_grass_medium_c1_autumn",
			"spr_easternroad_marsh_grass_medium_c2_autumn",
		]
		winter = [
			"spr_easternroad_marsh_grass_medium_c1_winter",
			"spr_easternroad_marsh_grass_medium_c2_winter",
		]

	[marsh_grass_medium.outline_sprites]
		spring = [
			"spr_easternroad_marsh_grass_medium_outline",
			"spr_easternroad_marsh_grass_medium_outline",
		]
		summer = [
			"spr_easternroad_marsh_grass_medium_outline",
			"spr_easternroad_marsh_grass_medium_outline",
		]
		fall = [
			"spr_easternroad_marsh_grass_medium_outline",
			"spr_easternroad_marsh_grass_medium_outline",
		]
		winter = [
			"spr_easternroad_marsh_grass_medium_outline",
			"spr_easternroad_marsh_grass_medium_outline",
		]

	[marsh_grass_medium.on_destruction_particles]
		spring = [
			"spr_part_easternroad_marsh_grass_c1_spring",
			"spr_part_easternroad_marsh_grass_c2_spring",
		]
		summer = [
			"spr_part_easternroad_marsh_grass_c1_summer",
			"spr_part_easternroad_marsh_grass_c2_summer",
		]
		fall = [
			"spr_part_easternroad_marsh_grass_c1_autumn",
			"spr_part_easternroad_marsh_grass_c2_autumn",
		]
		winter = [
			"spr_part_easternroad_marsh_grass_c1_winter",
			"spr_part_easternroad_marsh_grass_c2_winter",
		]

[marsh_grass_large]
	day_to_stage = [
		"marsh_grass_small",
		"marsh_grass_small",
		"marsh_grass_small",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_medium",
		"marsh_grass_large",
	]

	[[marsh_grass_large.drops]]
		item = "grass_seed"
		chance = 7.5

	[[marsh_grass_large.drops]]
		item = "hay"
		chance = 7.5

	[marsh_grass_large.sprites]
		spring = [
			"spr_easternroad_marsh_grass_large_c1_spring",
			"spr_easternroad_marsh_grass_large_c2_spring",
		]
		summer = [
			"spr_easternroad_marsh_grass_large_c1_summer",
			"spr_easternroad_marsh_grass_large_c2_summer",
		]
		fall = [
			"spr_easternroad_marsh_grass_large_c1_autumn",
			"spr_easternroad_marsh_grass_large_c2_autumn",
		]
		winter = [
			"spr_easternroad_marsh_grass_large_c1_winter",
			"spr_easternroad_marsh_grass_large_c2_winter",
		]

	[marsh_grass_large.outline_sprites]
		spring = [
			"spr_easternroad_marsh_grass_large_outline",
			"spr_easternroad_marsh_grass_large_outline",
		]
		summer = [
			"spr_easternroad_marsh_grass_large_outline",
			"spr_easternroad_marsh_grass_large_outline",
		]
		fall = [
			"spr_easternroad_marsh_grass_large_outline",
			"spr_easternroad_marsh_grass_large_outline",
		]
		winter = [
			"spr_easternroad_marsh_grass_large_outline",
			"spr_easternroad_marsh_grass_large_outline",
		]

	[marsh_grass_large.on_destruction_particles]
		spring = [
			"spr_part_easternroad_marsh_grass_c1_spring",
			"spr_part_easternroad_marsh_grass_c2_spring",
		]
		summer = [
			"spr_part_easternroad_marsh_grass_c1_summer",
			"spr_part_easternroad_marsh_grass_c2_summer",
		]
		fall = [
			"spr_part_easternroad_marsh_grass_c1_autumn",
			"spr_part_easternroad_marsh_grass_c2_autumn",
		]
		winter = [
			"spr_part_easternroad_marsh_grass_c1_winter",
			"spr_part_easternroad_marsh_grass_c2_winter",
		]
