[default]
	hp = 3
	offset = [8, 9]
	size = [2, 2]
	# minimum tool quality to hit this
	minimum_quality = "tier1"
	# winter_sprites = defaults to `sprites` if not present
	sprites = ["spr_illegal_16"]
	drops = [
		{ item = "basic_wood", count_range = [3, 3], exclusive = false },
		{ item = "basic_wood", chance = 10, exclusive = false },
	]
	initial_burn_iframes = 100

[branch]
	hp = 3
	offset = [8, 0]
	drops = [{ item = "basic_wood" }]

	sprites = [
		"spr_farm_branch_t1_c1_spring",
		"spr_farm_branch_t1_c2_spring",
		"spr_farm_branch_t2_c1_spring",
		"spr_farm_branch_t2_c2_spring",
		"spr_farm_branch_t3_c1_spring",
		"spr_farm_branch_t3_c2_spring",
	]
	winter_sprites = [
		"spr_farm_branch_t1_c1_winter",
		"spr_farm_branch_t1_c2_winter",
		"spr_farm_branch_t2_c1_winter",
		"spr_farm_branch_t2_c2_winter",
		"spr_farm_branch_t3_c1_winter",
		"spr_farm_branch_t3_c2_winter",
	]

[stump_apple]
	hp = 6.0
	sprites = "spr_fruit_apple_stump"

[stump_cherry]
	hp = 6.0
	sprites = "spr_fruit_cherry_stump"

[stump_large]
	drops = [{ item = "hard_wood", count_range = [2, 2] }]
	hp = 12
	size = [4, 4]
	offset = [16, 8]

	sprites = "spr_farm_stump_big_spring"
	winter_sprites = "spr_farm_stump_big_winter"
	minimum_quality = "tier2"

[stump_lemon]
	hp = 6
	sprites = "spr_fruit_lemon_stump"

[stump_orange]
	hp = 6
	sprites = "spr_fruit_orange_stump"

[stump_peach]
	hp = 6
	sprites = "spr_fruit_peach_stump"

[stump_pear]
	hp = 6
	sprites = "spr_fruit_pear_stump"

[stump_pomegranate]
	hp = 6
	sprites = "spr_fruit_pomegranate_stump"

[stump_small_oak]
	hp = 6
	sprites = "spr_tree_oak_stump_spring"

[stump_small_pine]
	hp = 6
	sprites = "spr_tree_pine_stump_spring"

[stump_deep_woods]
	drops = [{ item = "hard_wood", count_range = [2, 2] }]
	hp = 12
	minimum_quality = "tier2"
	sprites = "spr_tree_deep_woods_stump_spring"

[stump_plum_blossom]
	hp = 6
	sprites = "spr_fruit_plum_blossom_stump"

[stump_coconut]
	hp = 6
	sprites = "spr_fruit_coconut_stump"

[stump_small_pine_special]
	drops = []
	hp = 2
	sprites = "spr_farm_tree3_stump"
