
# <---------SPRING BUG ITEMS------------->

[butterfly]
	description = "A common insect found during the daytime in spring."
	icon_sprite = "spr_ui_item_insect_butterfly"
	name = "Butterfly"
	value = { bin = 10 }
	tags = ["bugs"]

[caterpillar]
	description = "A common insect found in spring. Sometimes found when shaking trees."
	icon_sprite = "spr_ui_item_insect_caterpillar"
	name = "Caterpillar"
	value = { bin = 10 }
	tags = ["bugs"]

[flower_crown_beetle]
	description = "A legendary insect found during the daytime in spring. It's so cute!"
	icon_sprite = "spr_ui_item_insect_flowercrownbeetle"
	name = "Flower Crown Beetle"
	value = { bin = 30 }
	tags = ["bugs"]

[petalhopper]
	description = "A common insect found during the daytime in spring. Sometimes found when cutting grass."
	icon_sprite = "spr_ui_item_insect_petalhopper"
	name = "Petalhopper"
	value = { bin = 10 }
	tags = ["bugs"]

[ladybug]
	description = "A common insect found in spring."
	icon_sprite = "spr_ui_item_insect_ladybug"
	name = "Ladybug"
	value = { bin = 10 }
	tags = ["bugs"]

[luna_moth]
	description = "A rare insect found at night in spring."
	icon_sprite = "spr_ui_item_insect_lunamoth"
	name = "Luna Moth"
	value = { bin = 20 }
	tags = ["bugs"]

[orchid_mantis]
	description = "A rare insect found during the daytime in spring."
	icon_sprite = "spr_ui_item_insect_orchidmantis"
	name = "Orchid Mantis"
	value = { bin = 20 }
	tags = ["bugs"]

[roly_poly]
	description = "An uncommon insect found in spring. Found when breaking rocks."
	icon_sprite = "spr_ui_item_insect_pillbug"
	name = "Roly Poly"
	value = { bin = 15 }
	tags = ["bugs"]

[snail]
	description = "An uncommon gastropod found in spring."
	icon_sprite = "spr_ui_item_insect_snail"
	name = "Snail"
	value = { bin = 15 }
	tags = ["bugs"]

[waterbug]
	description = "A common insect found at the beach in all seasons."
	icon_sprite = "spr_ui_item_insect_waterbug"
	name = "Waterbug"
	value = { bin = 10 }
	tags = ["bugs"]

	# <---------SUMMER BUG ITEMS------------->

[cicada]
	description = "A common insect found in summer. Sometimes found when shaking trees."
	icon_sprite = "spr_ui_item_insect_cicada"
	name = "Cicada"
	value = { bin = 10 }
	tags = ["bugs"]

[cricket]
	description = "A common insect found at night in summer."
	icon_sprite = "spr_ui_item_insect_cricket"
	name = "Cricket"
	value = { bin = 10 }
	tags = ["bugs"]

[dragonfly]
	description = "An uncommon insect found during the daytime in summer."
	icon_sprite = "spr_ui_item_insect_dragonfly"
	name = "Dragonfly"
	value = { bin = 15 }
	tags = ["bugs"]

[firefly]
	description = "A common insect found at night in summer."
	icon_sprite = "spr_ui_item_insect_firefly"
	name = "Firefly"
	value = { bin = 10 }
	tags = ["bugs"]

[jewel_beetle]
	description = "An uncommon insect found in summer. Found when breaking rocks."
	icon_sprite = "spr_ui_item_insect_jewelbeetle"
	name = "Jewel Beetle"
	value = { bin = 15 }
	tags = ["bugs"]

[magma_beetle]
	description = "A rare insect found in summer."
	icon_sprite = "spr_ui_item_insect_magmabeetle"
	name = "Magma Beetle"
	value = { bin = 20 }
	tags = ["bugs"]

[strawhopper]
	description = "A common insect found in summer. Sometimes found when cutting grass."
	icon_sprite = "spr_ui_item_insect_strawhopper"
	name = "Strawhopper"
	value = { bin = 10 }
	tags = ["bugs"]

[strobe_firefly]
	description = "A legendary insect found in summer. It's mesmerizing!"
	icon_sprite = "spr_ui_item_insect_strobefirefly"
	name = "Strobe Firefly"
	value = { bin = 30 }
	tags = ["bugs"]

[sand_bug]
	description = "A common insect found at the beach in all seasons."
	icon_sprite = "spr_ui_item_insect_sand_bug"
	name = "Sand Bug"
	value = { bin = 10 }
	tags = ["bugs"]

[surf_beetle]
	description = "A common insect found at the beach in all seasons."
	icon_sprite = "spr_ui_item_insect_surf_beetle"
	name = "Surf Beetle"
	value = { bin = 10 }
	tags = ["bugs"]


	# <---------FALL BUG ITEMS------------->

[beach_hopper]
	description = "A common insect found at the beach in all seasons."
	icon_sprite = "spr_ui_item_insect_beach_hopper"
	name = "Beach Hopper"
	value = { bin = 10 }
	tags = ["bugs"]

[chillipede]
	description = "An uncommon insect found in fall. Found when breaking rocks."
	icon_sprite = "spr_ui_item_insect_chillipede"
	name = "Chillipede"
	value = { bin = 15 }
	tags = ["bugs"]

[cicada_nymph]
	description = "A common insect found at night in fall."
	icon_sprite = "spr_ui_item_insect_cicadanymph"
	name = "Cicada Nymph"
	value = { bin = 10 }
	tags = ["bugs"]

[fairy_bee]
	description = "A legendary insect found during fall. It's beautiful!"
	icon_sprite = "spr_ui_item_insect_fairybee"
	name = "Fairy Bee"
	value = { bin = 30 }
	tags = ["bugs", "bee"]

[inchworm]
	description = "A common insect found in fall."
	icon_sprite = "spr_ui_item_insect_inchworm"
	name = "Inchworm"
	value = { bin = 10 }
	tags = ["bugs"]

[leafhopper]
	description = "A common insect found in fall. Sometimes found when cutting grass."
	icon_sprite = "spr_ui_item_insect_leafhopper"
	name = "Leafhopper"
	value = { bin = 10 }
	tags = ["bugs"]

[mistmoth]
	description = "A rare insect found at night in fall."
	icon_sprite = "spr_ui_item_insect_mistmoth"
	name = "Mistmoth"
	value = { bin = 30 }
	tags = ["bugs"]

[monarch_butterfly]
	description = "A common insect found during the daytime in fall."
	icon_sprite = "spr_ui_item_insect_monarchbutterfly"
	name = "Monarch Butterfly"
	value = { bin = 10 }
	tags = ["bugs"]

[tiger_swallowtail_butterfly]
	description = "An uncommon insect found during the daytime in fall."
	icon_sprite = "spr_ui_item_insect_tigerswallowtailbutterfly"
	name = "Tiger Swallowtail Butterfly"
	value = { bin = 15 }
	tags = ["bugs"]

[walking_leaf]
	description = "An uncommon insect found during the daytime in fall. Sometimes found when shaking trees."
	icon_sprite = "spr_ui_item_insect_walkingleaf"
	name = "Walking Leaf"
	value = { bin = 15 }
	tags = ["bugs"]

	# <---------WINTER BUG ITEMS------------->

[crystal_caterpillar]
	description = "A rare insect found on snowy days in winter."
	icon_sprite = "spr_ui_item_insect_crystalcaterpillar"
	name = "Crystal Caterpillar"
	value = { bin = 20 }
	tags = ["bugs"]

[brightbulb_moth]
	description = "A common insect found at night in winter."
	icon_sprite = "spr_ui_item_insect_brightbulb_moth"
	name = "Brightbulb Moth"
	value = { bin = 10 }
	tags = ["bugs"]

[frost_flutter_butterfly]
	description = "A common insect found during the daytime in winter."
	icon_sprite = "spr_ui_item_insect_frost_flutter_butterfly"
	name = "Frost Flutter Butterfly"
	value = { bin = 10 }
	tags = ["bugs"]

[icehopper]
	description = "A common insect found in winter. Sometimes found when cutting grass."
	icon_sprite = "spr_ui_item_insect_icehopper"
	name = "Icehopper"
	value = { bin = 10 }
	tags = ["bugs"]

[polar_fly]
	description = "A common insect found in winter."
	icon_sprite = "spr_ui_item_insect_polar_fly"
	name = "Polar Fly"
	value = { bin = 10 }
	tags = ["bugs"]

[snug_bug]
	description = "An uncommon insect found in winter. Found when breaking rocks."
	icon_sprite = "spr_ui_item_insect_snug_bug"
	name = "Snug Bug"
	value = { bin = 15 }
	tags = ["bugs"]

[relic_crab]
	description = "An uncommon crustacean found at the beach in all seasons."
	icon_sprite = "spr_ui_item_insect_reliccrab"
	name = "Relic Crab"
	value = { bin = 20 }
	tags = ["bugs"]

[snowball_beetle]
	description = "A legendary insect found during heavy snow in winter. It's adorable!"
	icon_sprite = "spr_ui_item_insect_snowballbeetle"
	name = "Snowball Beetle"
	value = { bin = 30 }
	tags = ["bugs"]

[walking_stick]
	description = "An uncommon insect found in winter."
	icon_sprite = "spr_ui_item_insect_walkingstick"
	name = "Walking Stick"
	value = { bin = 15 }
	tags = ["bugs"]

[winterpillar]
	description = "A common insect found in winter. Sometimes found when shaking trees."
	icon_sprite = "spr_ui_item_insect_winterpillar"
	name = "Winterpillar"
	value = { bin = 10 }
	tags = ["bugs"]

	# <---------MULTI-SEASON BUG ITEMS------------->

[ant]
	description = "A common insect found in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_ant"
	name = "Ant"
	value = { bin = 10 }
	tags = ["bugs"]

[bumblebee]
	description = "A common insect found during the daytime in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_bumblebee"
	name = "Bumblebee"
	value = { bin = 10 }
	tags = ["bugs", "bee"]

[fuzzy_moth]
	description = "An uncommon insect found at night in all seasons."
	icon_sprite = "spr_ui_item_insect_fuzzymoth"
	name = "Fuzzy Moth"
	value = { bin = 15 }
	tags = ["bugs"]

[grasshopper]
	description = "A common insect found during the daytime in all seasons but winter. Sometimes found when cutting grass."
	icon_sprite = "spr_ui_item_insect_grasshopper"
	name = "Grasshopper"
	value = { bin = 10 }
	tags = ["bugs"]

[hermit_crab]
	description = "A common crustacean found at the beach in all seasons."
	icon_sprite = "spr_ui_item_insect_hermitcrab"
	name = "Hermit Crab"
	value = { bin = 15 }
	tags = ["bugs"]

[hummingbird_hawk_moth]
	description = "A rare insect found in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_hummingbirdhawkmoth"
	name = "Hummingbird Hawk Moth"
	value = { bin = 20 }
	tags = ["bugs"]

[lightning_dragonfly]
	description = "A rare insect found during thunderstorms in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_lightningdragonfly"
	name = "Lightning Dragonfly"
	value = { bin = 20 }
	tags = ["bugs"]

[pond_skater]
	description = "An uncommon insect found in all seasons."
	icon_sprite = "spr_ui_item_insect_pondskater"
	name = "Pond Skater"
	value = { bin = 15 }
	tags = ["bugs"]

[praying_mantis]
	description = "A common insect found during the daytime in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_prayingmantis"
	name = "Praying Mantis"
	value = { bin = 10 }
	tags = ["bugs"]

[question_mark_butterfly]
	description = "An uncommon insect found during the daytime in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_questionmarkbutterfly"
	name = "Question Mark Butterfly"
	value = { bin = 15 }
	tags = ["bugs"]

[redhead_worm]
	description = "An uncommon worm found in all seasons but winter. Found when breaking rocks."
	icon_sprite = "spr_ui_item_insect_redhead_worm"
	name = "Redhead Worm"
	value = { bin = 15 }
	tags = ["bugs"]

[speedy_snail]
	description = "A legendary gastropod found in all seasons but winter. It goes fast!"
	icon_sprite = "spr_ui_item_insect_speedysnail"
	name = "Speedy Snail"
	value = { bin = 30 }
	tags = ["bugs"]

[rhinoceros_beetle]
	description = "An uncommon bug found at night in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_rhinocerosbeetle"
	name = "Rhinoceros Beetle"
	value = { bin = 15 }
	tags = ["bugs"]


	#not actually bugs

[pond_snail]
	description = "A common pond gastropod found in all seasons."
	icon_sprite = "spr_ui_item_dive_pond_snail"
	name = "Pond Snail"
	value = { bin = 25 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "pond"]

[river_snail]
	description = "A common river gastropod found in all seasons."
	icon_sprite = "spr_ui_item_dive_snail"
	name = "River Snail"
	value = { bin = 20 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "river"]

	# Deep Woods Bugs

[windleaf_butterfly]
	description = "A common Deep Woods insect. Clever camouflage makes this insect look like leaves fluttering about."
	icon_sprite = "spr_ui_item_insect_windleaf_butterfly"
	name = "Windleaf Butterfly"
	value = { bin = 20 }
	tags = ["bugs"]

[mote_firefly]
	description = "A common Deep Woods insect. Legends say that they are known to guide lost travelers out of the woods."
	icon_sprite = "spr_ui_item_insect_mote_firefly"
	name = "Mote Firefly"
	value = { bin = 25 }
	tags = ["bugs"]

[loam_caterpillar]
	description = "An uncommon Deep Woods insect. These caterpillars can be found munching away in the thick loam of the Deep Woods."
	icon_sprite = "spr_ui_item_insect_loam_caterpillar"
	name = "Loam Caterpillar"
	value = { bin = 35 }
	tags = ["bugs"]

[dragon_horn_beetle]
	description = "A common Deep Woods insect. This beetle spends most of its time sharpening its horn."
	icon_sprite = "spr_ui_item_insect_dragon_horn_beetle"
	name = "Dragon Horn Beetle"
	value = { bin = 40 }
	tags = ["bugs"]

[singing_katydid]
	description = "A rare Deep Woods insect. These remarkable insects spend their whole lives crafting a unique and beautiful song."
	icon_sprite = "spr_ui_item_insect_singing_katydid"
	name = "Singing Katydid"
	value = { bin = 70 }
	tags = ["bugs"]

	#NEW BEES

[fur_bee]
	description = "A common insect found during the daytime in winter."
	icon_sprite = "spr_ui_item_insect_fur_bee"
	name = "Fur Bee"
	value = { bin = 10 }
	tags = ["bugs", "bee"]

[sweet_bee]
	description = "An uncommon insect found during the daytime in all seasons."
	icon_sprite = "spr_ui_item_insect_sweet_bee"
	name = "Sweet Bee"
	value = { bin = 15 }
	tags = ["bugs", "bee"]

[big_bee]
	description = "An uncommon insect found during the daytime in all seasons but winter."
	icon_sprite = "spr_ui_item_insect_big_bee"
	name = "Big Bee"
	value = { bin = 15 }
	tags = ["bugs", "bee"]

[flower_bee]
	description = "A rare insect found during the daytime in all seasons."
	icon_sprite = "spr_ui_item_insect_flower_bee"
	name = "Flower Bee"
	value = { bin = 20 }
	tags = ["bugs", "bee"]

[moonlight_bee]
	description = "A rare insect found during the nighttime in all seasons."
	icon_sprite = "spr_ui_item_insect_moonlight_bee"
	name = "Moonlight Bee"
	value = { bin = 20 }
	tags = ["bugs", "bee"]

	# NEW PHEARMONE BUGS

[ant_queen]
	description = "An insect that can only be lured with Common Pheromones. This Ant Queen has a can-do attitude and is ready to start her very own colony."
	icon_sprite = "spr_ui_item_insect_ant_queen"
	name = "Ant Queen"
	value = { bin = 30 }
	tags = ["bugs"]

[sunset_moth]
	description = "An insect that can only be lured with Common Pheromones. What an eye-catching moth!"
	icon_sprite = "spr_ui_item_insect_sunset_moth"
	name = "Sunset Moth"
	value = { bin = 35 }
	tags = ["bugs"]

[saint_mantis]
	description = "An insect that can only be lured with Uncommon Pheromones. This mantis is unusually peace-loving and gentle."
	icon_sprite = "spr_ui_item_insect_saint_mantis"
	name = "Saint Mantis"
	value = { bin = 60 }
	tags = ["bugs"]

[queens_birdwing]
	description = "An insect that can only be lured with Rare Pheromones. This very large butterfly has a regal bearing."
	icon_sprite = "spr_ui_item_insect_queens_birdwing"
	name = "Queen's Birdwing"
	value = { bin = 90 }
	tags = ["bugs"]

[biggest_beetle]
	description = "An insect that can only be lured with Legendary Pheromones. Now that's a big beetle!"
	icon_sprite = "spr_ui_item_insect_biggest_beetle"
	name = "Biggest Beetle"
	value = { bin = 120 }
	tags = ["bugs"]
