
# DATE INSPIRATION ITEMS

[inn_menu]
	name = "Inn Menu"
	description = "This menu fills you with inspiration. Use this item to unlock the Inn Meal Date."
	icon_sprite = "spr_ui_item_date_inn_menu"
	date_unlock = "inn_meal"
	soulbind = "forever"
	tags = ["date_inspiration"]

[picnic_set]
	name = "Picnic Set"
	description = "This picnic set fills you with inspiration. Use this item to unlock the Deep Woods Picnic Date."
	icon_sprite = "spr_ui_item_date_picnic_set"
	date_unlock = "deep_woods_picnic"
	soulbind = "forever"
	tags = ["date_inspiration"]

[lovely_seashell]
	name = "Lovely Seashell"
	description = "This cute pink shell fills you with inspiration. Use this item to unlock the Beach Date."
	icon_sprite = "spr_ui_item_date_lovely_seashell"
	date_unlock = "beach"
	soulbind = "forever"
	tags = ["date_inspiration"]

[dollhouse_bench]
	name = "Dollhouse Bench"
	description = "This miniature park bench fills you with inspiration. Use this item to unlock the Park Date."
	icon_sprite = "spr_ui_item_date_dollhouse_bench"
	date_unlock = "park"
	soulbind = "forever"
	tags = ["date_inspiration"]

[rough_gemstone]
	name = "Rough Gemstone"
	description = "This rough gemstone fills you with inspiration. Use this item to unlock the Gem Cutting Date."
	icon_sprite = "spr_ui_item_date_rough_gemstone"
	date_unlock = "gem_cutting"
	soulbind = "forever"
	tags = ["date_inspiration"]

[bath_soap]
	name = "Bath Soap"
	description = "This ultra fancy bath soap fills you with inspiration. Use this item to unlock the Bathhouse Date."
	icon_sprite = "spr_ui_item_date_bath_soap"
	date_unlock = "bathhouse"
	soulbind = "forever"
	tags = ["date_inspiration"]
	value = { bin = 90000, store = 100000 }

	# DATE PHOTOS

[date_photo_beach]
	name = "Beach Date Photo"
	description = "A memento from an Beach Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_beach"
	soulbind = "forever"
	object = "date_photo_beach"
	tags = ["blacklist_popup"]

[date_photo_bath]
	name = "Bath Date Photo"
	description = "A memento from a Bath Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_bath"
	soulbind = "forever"
	object = "date_photo_bath"
	tags = ["blacklist_popup"]

[date_photo_deep_woods]
	name = "Picnic Date Photo"
	description = "A memento from a Deep Woods Picnic Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_deep_woods"
	soulbind = "forever"
	object = "date_photo_deep_woods"
	tags = ["blacklist_popup"]

[date_photo_gem_cutting]
	name = "Gem Cutting Date Photo"
	description = "A memento from a Gem Cutting Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_gem_cutting"
	soulbind = "forever"
	object = "date_photo_gem_cutting"
	tags = ["blacklist_popup"]

[date_photo_inn]
	name = "Inn Date Photo"
	description = "A memento from an Inn Meal Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_inn"
	soulbind = "forever"
	object = "date_photo_inn"
	tags = ["blacklist_popup"]

[date_photo_park]
	name = "Park Date Photo"
	description = "A memento from a Park Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_park"
	soulbind = "forever"
	object = "date_photo_park"
	tags = ["blacklist_popup"]

[date_photo_shooting_star]
	name = "Shooting Star Date Photo"
	description = "A memento from a Shooting Star Festival Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_shooting_star"
	soulbind = "forever"
	object = "date_photo_shooting_star"
	tags = ["blacklist_popup"]

[date_photo_harvest]
	name = "Harvest Dance Date Photo"
	description = "A memento from a Harvest Festival Date you went on. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_harvest"
	soulbind = "forever"
	object = "date_photo_harvest"
	tags = ["blacklist_popup"]

[date_photo_wedding]
	name = "Wedding Day Photo"
	description = "A memento from your Wedding Day. Place it on your wall to view it!"
	icon_sprite = "spr_ui_item_date_photo_wedding"
	soulbind = "forever"
	object = "date_photo_wedding"
	tags = ["blacklist_popup"]
