
# <---------SAPLING DROPS------------->

[sap]
	description = "A drip of sticky sap, sometimes dropped by Saplings. Used in a variety of crafting recipes."
	icon_sprite = "spr_ui_item_sap"
	name = "Sap"
	value = { bin = 5 }
	tags = ["junk", "monster_part", "material"]

[monster_fang]
	description = "A pointed fang sometimes dropped by Saplings. Used in certain cooking and crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_monster_fang"
	name = "Monster Fang"
	tags = ["monster_part", "material"]
	value = { bin = 15 }
	edible = false

	# <---------MUSHROOM DROPS------------->

[red_toadstool]
	description = "A red mushroom sometimes dropped by Mushroom monsters. Likely poisonous."
	icon_sprite = "spr_ui_item_redtoadstool"
	name = "Red Toadstool"
	tags = ["material", "mushroom", "mushroomy"]
	value = { bin = 15 }

[wild_mushroom]
	restore = 5
	description = "A tasty green mushroom sometimes dropped by Mushroom monsters."
	icon_sprite = "spr_ui_item_wildmushroom"
	name = "Cave Mushroom"
	tags = ["material", "mushroom", "mushroomy"]
	value = { bin = 15 }

[glowing_mushroom]
	description = "A glowing blue mushroom sometimes dropped by Mushroom monsters."
	restore = 5
	icon_sprite = "spr_ui_item_glowingmushroom"
	name = "Glowing Mushroom"
	tags = ["material", "mushroom", "mushroomy"]
	value = { bin = 15 }

[monster_powder]
	description = "A magic powder sometimes dropped by Mushroom monsters. Used in cooking and crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_monster_powder"
	name = "Monster Powder"
	tags = ["monster_part", "material"]
	value = { bin = 15 }
	edible = false

[purple_mushroom]
	description = "A spotted purple mushroom sometimes dropped by Mushroom monsters. Used in certain crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_purple_mushroom"
	name = "Purple Mushroom"
	tags = ["material", "mushroom", "mushroomy"]
	value = { bin = 15 }

	# <---------ROCK CLOD DROPS------------->

[monster_shell]
	description = "A rocky shell sometimes dropped by Clods. Used in certain cooking and crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_monster_shell"
	name = "Monster Shell"
	tags = ["monster_part", "material"]
	value = { bin = 20 }
	edible = false

[bomb]
	name = "Clod Bomb"
	description = "A bomb originating from a Silver Clod. You can throw it!"
	value = { bin = 50 }
	icon_sprite = "spr_ui_item_bomb"
	bomb = { damage = 50 }
	tags = ["bomb", "weird_gift"]

	# <---------ENCHANTERN DROPS------------->

[monster_core]
	description = "A powered core sometimes dropped by Enchanterns. Used in certain cooking and crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_monster_core"
	name = "Monster Core"
	tags = ["monster_part", "material"]
	value = { bin = 20 }
	edible = false

	# <---------STALAGMITE DROPS------------->

[monster_horn]
	description = "A spiral horn sometimes dropped by Stalagmites. Used in certain cooking and crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_monster_horn"
	name = "Monster Horn"
	tags = ["monster_part", "material"]
	value = { bin = 25 }
	edible = false

	# <---------ESSENCE BAT DROPS------------->

[essence_drop]
	description = "A drip of magic, sometimes dropped by Essence Bats. Used in a variety of crafting recipes."
	icon_sprite = "spr_ui_item_essence_drop"
	name = "Essence Drop"
	value = { bin = 20 }
	tags = ["junk", "material"]

[monster_wing]
	description = "A magic wing sometimes dropped by Essence Bats. Used in certain crafting recipes."
	restore = 5
	icon_sprite = "spr_ui_item_monster_wing"
	name = "Monster Wing"
	tags = ["monster_part", "material"]
	value = { bin = 30 }
	edible = false

#NEW MONSTER DROPS
[monster_whisker] # Need to be dropped by Lava Cats and Void Cats
	name = "Monster Whisker"
	description = "A long whisker sometimes dropped by Lava Cat and Void Cat monsters."
	icon_sprite = "spr_ui_item_monster_whisker"
	tags = ["monster_part"]
	value = { bin = 35 }

[monster_block] # Replacing Monster Hoops, will be dropped by Rock Stack and Griffin Statue
	name = "Monster Block"
	description = "A stone-like block sometimes dropped by Rock Stack and Gryphon Statue monsters."
	icon_sprite = "spr_ui_item_monster_block"
	tags = ["monster_part"]
	value = { bin = 40 }

	#monster pet skins

[pet_skin_sapling]
	icon_sprite = "spr_ui_item_pet_unlock_sapling"
	name = "Pet Skin: Sapling"
	description = "Use this item to unlock the Sapling pet skin."
	soulbind = "forever"
	pet_skin_unlock = "sapling"
	tags = ["blacklist_popup"]

[pet_skin_mushroom]
	icon_sprite = "spr_ui_item_pet_unlock_mushroom"
	name = "Pet Skin: Mushroom"
	description = "Use this item to unlock the Mushroom pet skin."
	soulbind = "forever"
	pet_skin_unlock = "mushroom"
	tags = ["blacklist_popup"]

[pet_skin_rockclod]
	icon_sprite = "spr_ui_item_pet_unlock_rockclod"
	name = "Pet Skin: Rockclod"
	description = "Use this item to unlock the Rockclod pet skin."
	soulbind = "forever"
	pet_skin_unlock = "rockclod"
	tags = ["blacklist_popup"]

[pet_skin_oreclod]
	icon_sprite = "spr_ui_item_pet_unlock_oreclod"
	name = "Pet Skin: Oreclod"
	description = "Use this item to unlock the Oreclod pet skin."
	soulbind = "forever"
	pet_skin_unlock = "oreclod"
	tags = ["blacklist_popup"]

[pet_skin_stalagmite]
	icon_sprite = "spr_ui_item_pet_unlock_stalagmite"
	name = "Pet Skin: Stalagmite"
	description = "Use this item to unlock the Stalagmite pet skin."
	soulbind = "forever"
	pet_skin_unlock = "stalagmite"
	tags = ["blacklist_popup"]

[pet_skin_lava_cat]
	icon_sprite = "spr_ui_item_pet_unlock_lava_cat"
	name = "Pet Skin: Lava Cat"
	description = "Use this item to unlock the Lava Cat pet skin."
	soulbind = "forever"
	pet_skin_unlock = "lava_cat"
	tags = ["blacklist_popup"]

[pet_skin_void_cat]
	icon_sprite = "spr_ui_item_pet_unlock_void_cat"
	name = "Pet Skin: Void Cat"
	description = "Use this item to unlock the Void Cat pet skin."
	soulbind = "forever"
	pet_skin_unlock = "void_cat"
	tags = ["blacklist_popup"]

[pet_skin_flame_spirit]
	icon_sprite = "spr_ui_item_pet_unlock_flame_spirit"
	name = "Pet Skin: Flame Spirit"
	description = "Use this item to unlock the Flame Spirit pet skin."
	soulbind = "forever"
	pet_skin_unlock = "flame_spirit"
	tags = ["blacklist_popup"]

[pet_skin_rock_stack]
	icon_sprite = "spr_ui_item_pet_unlock_rock_stack"
	name = "Pet Skin: Rock Stack"
	description = "Use this item to unlock the Rock Stack pet skin."
	soulbind = "forever"
	pet_skin_unlock = "rock_stack"
	tags = ["blacklist_popup"]

[pet_skin_gryphon_statue]
	icon_sprite = "spr_ui_item_pet_unlock_griffin_statue"
	name = "Pet Skin: Gryphon Statue"
	description = "Use this item to unlock the Gryphon Statue pet skin."
	soulbind = "forever"
	pet_skin_unlock = "griffin_statue"
	tags = ["blacklist_popup"]

[pet_skin_flying_tome]
	icon_sprite = "spr_ui_item_pet_unlock_flying_tome"
	name = "Pet Skin: Flying Tome"
	description = "Use this item to unlock the Flying Tome pet skin."
	soulbind = "forever"
	pet_skin_unlock = "flying_tome"
	tags = ["blacklist_popup"]

[pet_skin_essence_bat]
	icon_sprite = "spr_ui_item_pet_unlock_essence_bat"
	name = "Pet Skin: Essence Bat"
	description = "Use this item to unlock the Essence Bat pet skin."
	soulbind = "forever"
	pet_skin_unlock = "essence_bat"
	tags = ["blacklist_popup"]

[pet_skin_enchantern]
	icon_sprite = "spr_ui_item_pet_unlock_enchantern"
	name = "Pet Skin: Enchantern"
	description = "Use this item to unlock the Enchantern pet skin."
	soulbind = "forever"
	pet_skin_unlock = "enchantern"
	tags = ["blacklist_popup"]

[pet_skin_mimic]
	icon_sprite = "spr_ui_item_pet_unlock_mimic"
	name = "Pet Skin: Mimic"
	description = "Use this item to unlock the Mimic pet skin."
	soulbind = "forever"
	pet_skin_unlock = "mimic"
	tags = ["blacklist_popup"]
