# <---------ANIMAL DROPS------------->

[animal_currency]
	description = "A shiny bead gifted to you by an animal as thanks for your kindness. Surely these treasured beads have some mysterious purpose."
	icon_sprite = "spr_ui_item_shiny_bead"
	name = "Shiny Bead"
	tags = ["ranching", "animal_product"]
	value = { bin = 1, store = 100 }

[egg]
	description = "An egg laid by a hen. Used as an ingredient for cooking many kinds of dishes."
	icon_sprite = "spr_ui_item_chicken_egg_regular"
	name = "Chicken Egg"
	restore = 3
	value = { bin = 20, store = 80 }
	tags = ["ranching", "egg", "animal_harvest", "animal_product"]

[feather]
	description = "A feather dropped by a rooster. Used in a variety of crafting recipes."
	icon_sprite = "spr_ui_item_chicken_feather_regular"
	name = "Rooster Feather"
	value = { bin = 60, store = 240 }
	tags = ["ranching", "animal_fibre", "animal_harvest", "animal_product", "feather"]

[cow_milk]
	description = "Fresh milk from a cow. Used in a variety of cooking recipes."
	icon_sprite = "spr_ui_item_cow_milk_regular"
	name = "Milk"
	restore = 4
	value = { bin = 40, store = 120 }
	tags = [
		"ranching",
		"milk",
		"dairy",
		"pantry",
		"animal_harvest",
		"fresh",
		"drink_sound",
		"drink",
		"animal_product",
	]

[bull_horn]
	description = "A horn dropped by a bull. Used in a variety of crafting recipes."
	icon_sprite = "spr_ui_item_cow_horn_regular"
	name = "Bull Horn"
	value = { bin = 120, store = 360 }
	tags = ["ranching", "animal_harvest", "animal_product"]

[duck_egg]
	description = "An egg laid by a duck. Used as an ingredient for cooking a variety of dishes."
	icon_sprite = "spr_ui_item_duck_egg_regular"
	name = "Duck Egg"
	restore = 3
	value = { bin = 30, store = 120 }
	tags = ["ranching", "egg", "animal_harvest", "animal_product"]

[golden_duck_egg]
	description = "A gold quality egg layed by a duck. Used in high level cooking and crafting recipes."
	icon_sprite = "spr_ui_item_duck_egg_gold"
	name = "Golden Duck Egg"
	restore = 5
	value = { bin = 90, store = 270 }
	tags = ["ranching", "egg", "animal_harvest", "animal_product"]

[duck_feather]
	description = "A soft feather dropped by a drake. Used in a variety of crafting recipes."
	icon_sprite = "spr_ui_item_duck_feather_regular"
	name = "Duck Feather"
	value = { bin = 90, store = 270 }
	tags = ["ranching", "feather", "animal_fibre", "animal_harvest", "animal_product"]

[golden_duck_feather]
	description = "A gold quality feather dropped by a drake. Used in high level crafting recipes."
	icon_sprite = "spr_ui_item_duck_feather_gold"
	name = "Golden Duck Feather"
	value = { bin = 270, store = 540 }
	tags = ["ranching", "animal_fibre", "animal_harvest", "animal_product"]

[horse_hair]
	description = "Hair fiber dropped by a horse. Used in a variety of crafting recipes."
	icon_sprite = "spr_ui_item_horse_hair_regular"
	name = "Horse Hair"
	value = { bin = 130, store = 390 }
	tags = ["ranching", "animal_fibre", "animal_harvest", "animal_product"]

[golden_horse_hair]
	description = "Gold quality hair fiber dropped by a horse. Used in high level crafting recipes."
	icon_sprite = "spr_ui_item_horse_hair_gold"
	name = "Golden Horse Hair"
	value = { bin = 390, store = 780 }
	tags = ["ranching", "animal_fibre", "animal_harvest", "animal_product"]

[alpaca_wool]
	description = "Soft, silky wool from an alpaca. Used in a variety of crafting recipes."
	name = "Alpaca Wool"
	icon_sprite = "spr_ui_item_alpaca_wool_regular"
	value = { bin = 130, store = 390 }
	tags = ["ranching", "wool", "animal_fibre", "animal_harvest", "animal_product"]

[golden_alpaca_wool]
	description = "Gold quality wool from an alpaca. Used in a variety of crafting recipes."
	name = "Golden Alpaca Wool"
	icon_sprite = "spr_ui_item_alpaca_wool_gold"
	value = { bin = 390, store = 780 }
	tags = ["ranching", "wool", "animal_fibre", "animal_harvest", "animal_product"]

[bristle]
	description = "Stiff hairs dropped from the coat of a capybara. Used in a variety of crafting recipes."
	name = "Bristle"
	icon_sprite = "spr_ui_item_capybara_bristle_regular"
	value = { bin = 120, store = 360 }
	tags = ["ranching", "animal_fibre", "animal_harvest", "animal_product"]

[golden_bristle]
	description = "Gold quality hairs dropped from the coat of a capybara. Used in a variety of crafting recipes."
	name = "Golden Bristle"
	icon_sprite = "spr_ui_item_capybara_bristle_gold"
	value = { bin = 360, store = 720 }
	tags = ["ranching", "animal_fibre", "animal_harvest", "animal_product"]

[golden_bull_horn]
	description = "A gold quality horn dropped by a bull. Used in high level crafting recipes."
	icon_sprite = "spr_ui_item_cow_horn_gold"
	name = "Golden Bull Horn"
	value = { bin = 360, store = 720 }
	tags = ["ranching", "animal_harvest", "animal_product"]

[golden_cow_milk]
	description = "Gold quality milk from a cow. Used in high level cooking recipes."
	icon_sprite = "spr_ui_item_cow_milk_gold"
	name = "Golden Milk"
	restore = 6
	value = { bin = 120, store = 360 }
	tags = ["ranching", "milk", "dairy", "animal_harvest", "drink_sound", "drink", "animal_product"]

[golden_egg]
	description = "A gold quality egg laid by a hen. Used in high level cooking and crafting recipes."
	icon_sprite = "spr_ui_item_chicken_egg_gold"
	name = "Golden Egg"
	restore = 5
	value = { bin = 60, store = 240 }
	tags = ["ranching", "egg", "animal_harvest", "animal_product"]

[golden_feather]
	description = "A gold quality feather dropped by a rooster. Used in high level cooking and crafting recipes."
	icon_sprite = "spr_ui_item_chicken_feather_gold"
	name = "Golden Rooster Feather"
	value = { bin = 180, store = 360 }
	tags = ["ranching", "feather", "animal_fibre", "animal_harvest", "animal_product"]

[rabbit_wool]
	description = "Fluffy, soft wool from a rabbit. Used in a variety of crafting recipes."
	name = "Rabbit Wool"
	icon_sprite = "spr_ui_item_rabbit_hair_regular"
	value = { bin = 90, store = 360 }
	tags = ["ranching", "wool", "animal_fibre", "animal_harvest", "animal_product"]

[golden_rabbit_wool]
	description = "Gold quality wool from a rabbit. Used in a variety of crafting recipes."
	name = "Golden Rabbit Wool"
	icon_sprite = "spr_ui_item_rabbit_hair_gold"
	value = { bin = 270, store = 540 }
	tags = ["ranching", "wool", "animal_fibre", "animal_harvest", "animal_product"]

[sheep_wool]
	description = "Thick and cozy wool from a sheep. Used in a variety of crafting recipes."
	name = "Sheep Wool"
	icon_sprite = "spr_ui_item_sheep_wool_regular"
	value = { bin = 120, store = 480 }
	tags = ["ranching", "wool", "animal_fibre", "animal_harvest", "animal_product"]

[golden_sheep_wool]
	description = "Gold quality wool from a sheep. Used in a variety of crafting recipes."
	name = "Golden Sheep Wool"
	icon_sprite = "spr_ui_item_sheep_wool_gold"
	value = { bin = 360, store = 720 }
	tags = ["ranching", "wool", "animal_fibre", "animal_harvest", "animal_product"]

	# <---------BREEDING ITEMS (HEART SHAPED TREATS)------------->

[heart_shaped_chicken_treat]
	name = "Heart Shaped Chicken Treat"
	description = "Feed these treats to a male and female chicken to breed them. They must have at least 2 hearts & share a coop that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_chicken"
	value = { store = 150 }
	tags = ["chicken_treat", "weird_gift"]

[heart_shaped_cow_treat]
	name = "Heart Shaped Cow Treat"
	description = "Feed these treats to a male and female cow to breed them. They must have at least 2 hearts & share a barn that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_cow"
	value = { store = 300 }
	tags = ["cow_treat", "weird_gift"]

[heart_shaped_duck_treat]
	name = "Heart Shaped Duck Treat"
	description = "Feed these treats to a male and female duck to breed them. They must have at least 2 hearts & share a coop that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_duck"
	value = { store = 225 }
	tags = ["duck_treat", "weird_gift"]

[heart_shaped_capybara_treat]
	name = "Heart Shaped Capybara Treat"
	description = "Feed these treats to a male and female capybara to breed them. They must have at least 2 hearts & share a coop that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_capybara"
	value = { store = 300 }
	tags = ["capybara_treat", "weird_gift"]

[heart_shaped_rabbit_treat]
	name = "Heart Shaped Rabbit Treat"
	description = "Feed these treats to a male and female rabbit to breed them. They must have at least 2 hearts & share a coop that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_rabbit"
	value = { store = 300 }
	tags = ["rabbit_treat", "weird_gift"]

[heart_shaped_horse_treat]
	name = "Heart Shaped Horse Treat"
	description = "Feed these treats to a male and female horse to breed them. They must have at least 2 hearts & share a barn that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_horse"
	value = { store = 390 }
	tags = ["horse_treat", "weird_gift"]

[heart_shaped_alpaca_treat]
	name = "Heart Shaped Alpaca Treat"
	description = "Feed these treats to a male and female alpaca to breed them. They must have at least 2 hearts & share a barn that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_alpaca"
	value = { store = 390 }
	tags = ["alpaca_treat", "weird_gift"]

[heart_shaped_sheep_treat]
	name = "Heart Shaped Sheep Treat"
	description = "Feed these treats to a male and female sheep to breed them. They must have at least 2 hearts & share a barn that has a free space for a baby."
	icon_sprite = "spr_ui_item_animal_treat_sheep"
	value = { store = 300 }
	tags = ["sheep_treat", "weird_gift"]

# <---------ANIMAL TOYS------------->
[small_animal_seesaw]
	name = "Small Animal Seesaw"
	description = "A decorative toy for small animals to play on when outside. It's very cute!"
	object = "small_animal_seesaw"
	icon_sprite = "spr_ui_item_small_animal_toy_seesaw"
	value = { store = 500 }

[large_animal_ball_court]
	name = "Large Animal Ball Court"
	description = "A decorative toy for large animals to play on when outside. It's very cute!"
	object = "large_animal_ball"
	icon_sprite = "spr_ui_item_large_animal_toy_ball_court"
	value = { store = 750 }

[small_animal_hot_spring]
	name = "Small Animal Hot Spring"
	description = "A decorative toy for small animals to play in when outside. It's very cute!"
	object = "small_animal_hot_spring"
	icon_sprite = "spr_ui_item_small_animal_toy_hot_spring"
	value = { store = 1000 }

[large_animal_gramophone]
	name = "Large Animal Gramophone"
	description = "A decorative toy for large animals to play with when outside. It's very cute!"
	object = "large_animal_gramophone"
	icon_sprite = "spr_ui_item_large_animal_toy_gramophone"
	value = { store = 1500 }

	# Pet Treats ----------------------------

[cat_treat]
	name = "Cat Treat"
	description = "An optional treat for cats. All cats love it!"
	icon_sprite = "spr_ui_item_animal_treat_cat"
	value = { bin = 50, store = 100 }
	tags = ["cat_treat", "weird_gift", "milling", "animal_feed", "milled_animal_feed"]
	recipe_is_default = true
	recipe = [
		{ item = "smallmouth_bass", count = 1 },
		{ hours = 0, minutes = 10 },
	]
	pet_treat = { tier = "deluxe", pet_kinds = ["cat", "sapling", "mushroom", "rockclod", "oreclod", "enchantern", "stalagmite", "essence_bat", "mimic", "flame_spirit", "lava_cat", "void_cat", "rock_stack", "flying_tome", "griffin_statue"] }

[dog_treat]
	name = "Dog Treat"
	description = "An optional treat for dogs. All dogs love it!"
	icon_sprite = "spr_ui_item_animal_treat_dog"
	value = { bin = 50, store = 100 }
	tags = ["cat_treat", "weird_gift", "milling", "animal_feed", "milled_animal_feed"]
	recipe_is_default = true
	recipe = [
		{ item = "trout", count = 1 },
		{ hours = 0, minutes = 10 },
	]
	pet_treat = { tier = "deluxe", pet_kinds = ["dog", "sapling", "mushroom", "rockclod", "oreclod", "enchantern", "stalagmite", "essence_bat", "mimic", "flame_spirit", "lava_cat", "void_cat", "rock_stack", "flying_tome", "griffin_statue"] }
