#Song Crystals

[song_crystal_farm_boy]
	name = "Song Crystal - Farm Boy"
	song = "farm_boy"
	description = "Use to unlock \"Farm Boy\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_farm_boy"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_pink_twintails]
	name = "Song Crystal - Pink Twintails"
	song = "pink_twintails"
	description = "Use to unlock \"Pink Twintails\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_pink_twintails"
	tags = ["blacklist_popup", "song_crystal", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_crystal_caves]
	name = "Song Crystal - Crystal Caves"
	song = "crystal_caves"
	description = "Use to unlock \"Crystal Caves\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_crystal_caves"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_misty_pasture]
	name = "Song Crystal - Misty Pasture"
	song = "misty_pasture"
	description = "Use to unlock \"Misty Pasture\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_misty_pasture"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_purple_potions]
	name = "Song Crystal - Purple Potions"
	song = "purple_potions"
	description = "Use to unlock \"Purple Potions\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_purple_potions"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"


[song_crystal_heros_journey]
	name = "Song Crystal - Hero's Journey"
	song = "heros_journey"
	description = "Use to unlock \"Hero's Journey\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_heros_journey"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_five_more_minutes]
	name = "Song Crystal - Five More Minutes"
	song = "five_more_minutes"
	description = "Use to unlock \"Five More Minutes\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_five_more_minutes"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_dream_lobby]
	name = "Song Crystal - Dream Lobby"
	song = "dream_lobby"
	description = "Use to unlock \"Dream Lobby\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_dream_lobby"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_rainy_window]
	name = "Song Crystal - Rainy Window"
	song = "rainy_window"
	description = "Use to unlock \"Rainy Window\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_rainy_window"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_another_tower]
	name = "Song Crystal - Another Tower"
	song = "another_tower"
	description = "Use to unlock \"Another Tower\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_another_tower"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

	# Character theme Song Crystals

[song_crystal_adelines_theme]
	name = "Song Crystal - Adeline's Theme"
	song = "adelines_theme"
	description = "Use to unlock \"Adeline's Theme: The Smell of Drying Ink\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_adelines_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_balors_theme]
	name = "Song Crystal - Balor's Theme"
	song = "balors_theme"
	description = "Use to unlock \"Balor's Theme: Fair Weather\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_balors_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_caldarus_theme]
	name = "Song Crystal - Caldarus' Theme"
	song = "caldarus_theme"
	description = "Use to unlock \"Caldarus' Theme: The Sleeping Dragon\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_caldarus_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_celines_theme]
	name = "Song Crystal - Celine's Theme"
	song = "celines_theme"
	description = "Use to unlock \"Celine's Theme: Flower in Bloom\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_celines_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_eilands_theme]
	name = "Song Crystal - Eiland's Theme"
	song = "eilands_theme"
	description = "Use to unlock \"Eiland's Theme: Roots, Intertwined\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_eilands_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_haydens_theme]
	name = "Song Crystal - Hayden's Theme"
	song = "haydens_theme"
	description = "Use to unlock \"Hayden's Theme: Roll Up Your Sleeves!\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_haydens_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_junipers_theme]
	name = "Song Crystal - Juniper's Theme"
	song = "junipers_theme"
	description = "Use to unlock \"Juniper's Theme: Something's Brewing\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_junipers_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_marchs_theme]
	name = "Song Crystal - March's Theme"
	song = "marchs_theme"
	description = "Use to unlock \"March's Theme: What Do You Want?\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_marchs_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_reinas_theme]
	name = "Song Crystal - Reina's Theme"
	song = "reinas_theme"
	description = "Use to unlock \"Reina's Theme: Wildberry Pie\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_reinas_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_ryis_theme]
	name = "Song Crystal - Ryis' Theme"
	song = "ryis_theme"
	description = "Use to unlock \"Ryis' Theme: Birdsong\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_ryis_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_seridias_theme]
	name = "Song Crystal - Seridia's Theme"
	song = "seridias_theme"
	description = "Use to unlock \"Seridia's Theme: Rebirth\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_seridias_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"

[song_crystal_valens_theme]
	name = "Song Crystal - Valen's Theme"
	song = "valens_theme"
	description = "Use to unlock \"Valen's Theme: Cactus Blossom\" for your Crystal Resonators."
	icon_sprite = "spr_ui_item_song_crystal_valens_theme"
	tags = ["blacklist_popup", "song_crystal"]
	value = { store = 5000 }
	soulbind = "forever"
