
# <---------UNREVIEWED ITEMS------------>

#items are not yet in game


[monster_hoop] # THIS ITEM SHOULD NOT BE IN GAME - THIS ITEM IS BEING REPLACED WITH MONSTER BLOCK
	description = "Unimplemented item."
	restore = 5
	icon_sprite = "spr_ui_item_monster_hoop"
	name = "Monster Hoop"
	tags = ["monster_part"]
	value = { bin = 1 }

[big_egg]
	icon_sprite = "spr_ui_item_giant_egg"
	name = "Big Egg"
	description = "Crack the egg open?"
	soulbind = "forever"

	# []
	# 	name = ""
	# 	#description =
	# 	icon_sprite = ""
	# 	value = { bin = "self.recipe*1.1" }
	# 	object = ""
	# 	recipe_key = ""
	# 	#crafting_level_requirement =
	# 	recipe = [
	# 		{ count = 1, item = "basic_wood" },
	# 		{ hours = 0, minutes = 30 },
	# 	]
	# 	tags = ["furniture", "", "bathroom_set"]
