[engagement_tutorial]
kind = "gameplay_triggered"
speaker = "elsie"
portrait = "neutral"
local = "Good morning, [Ari]!"
next = "1"

[engagement_tutorial.1]
speaker = "elsie"
portrait = "happy"
local = "I hope you don't mind my dropping by. There's something I've been meaning to talk to you about..."
next = "2"

[engagement_tutorial.2]
speaker = "elsie"
portrait = "wink"
local = "I couldn't help but notice that you and $[ten_heart_romantic]$ have become quite close as of late."
next = "3"

[engagement_tutorial.3]
speaker = "elsie"
portrait = "embarrassed"
local = "I don't mean to make any assumptions... but I thought perhaps I should share this $Engagement Ring Recipe$ with you, in case you're starting to think about $Marriage$."
next = "4"

[engagement_tutorial.4]
speaker = "elsie"
portrait = "happy"
local = "You can use an $Engagement Ring$ to $invite someone you are Dating to discuss your future together$."
next = "5"

[engagement_tutorial.5]
speaker = "elsie"
portrait = "neutral"
local = "Just keep in mind that $discussing your future$ doesn't mean you need to $go through with a proposal$, you know. It's important to talk these things through before making a final decision."
next = "6"

[engagement_tutorial.6]
speaker = "elsie"
portrait = "happy"
local = "In any case, an $Engagement Ring$ can be crafted at a $Blacksmithing Station$."
next = "7"

[engagement_tutorial.7]
speaker = "elsie"
portrait = "think"
local = "Some of the required materials are a bit difficult to come by, but I've heard they can all be found in the $Mines$."
next = "8"

[engagement_tutorial.8]
speaker = "elsie"
portrait = "neutral"
local = "That shouldn't be an issue for one of your talents!"
next = "9"

[engagement_tutorial.9]
speaker = "elsie"
portrait = "happy"
local = "My, look at the time! I'd better let you get on with your day."
next = "10"

[engagement_tutorial.10]
speaker = "elsie"
portrait = "wink"
local = "Good luck, [Ari]!"
