name = "Archaeology"
icon_sprite_key = "spr_ui_skills_domain_icon_archaeology"
default_lut_index = 16
hovered_lut_index = 17
disabled_lut_index = 18

[[tier_1]]
	perk = "museum_quality_one"
	essence = 20
	icon = "spr_ui_skills_archaeology_icon_museum_quality_i"

[[tier_1]]
	perk = "unpeatable"
	essence = 10
	icon = "spr_ui_skills_archaeology_icon_unpeatable"

[[tier_1]]
	perk = "sunken_secrets"
	essence = 15
	icon = "spr_ui_skills_archaeology_icon_sunken_secrets"

[[tier_1]]
	perk = "western_ruins_scholar"
	essence = 15
	icon = "spr_ui_skills_archaeology_icon_western_ruins_scholar"

[[tier_2]]
	perk = "sunken_treasure"
	essence = 35
	icon = "spr_ui_skills_archaeology_icon_sunken_treasure"

[[tier_2]]
	perk = "stoneturner"
	essence = 40
	icon = "spr_ui_skills_archaeology_icon_stoneturner"

[[tier_2]]
	perk = "eastern_road_scholar"
	essence = 50
	icon = "spr_ui_skills_archaeology_icon_eastern_road_scholar"

[[tier_2]]
	perk = "pursuit"
	essence = 45
	icon = "spr_ui_skills_archaeology_icon_pursuit"

[[tier_3]]
	perk = "back_in_vogue"
	essence = 80
	icon = "spr_ui_skills_archaeology_icon_back_in_vogue"

[[tier_3]]
	perk = "natural_beauty"
	essence = 85
	icon = "spr_ui_skills_archaeology_icon_natural_beauty"

[[tier_3]]
	perk = "well_placed"
	essence = 70
	icon = "spr_ui_skills_archaeology_icon_well_placed"

[[tier_3]]
	perk = "museum_quality_two"
	essence = 75
	icon = "spr_ui_skills_archaeology_icon_museum_quality_ii"

[[tier_4]]
	perk = "former_farmers"
	essence = 155
	icon = "spr_ui_skills_archaeology_icon_former_farmers"

[[tier_4]]
	perk = "museum_quality_three"
	essence = 140
	icon = "spr_ui_skills_archaeology_icon_museum_quality_iii"

[[tier_4]]
	perk = "back_in_vogue_two"
	essence = 145
	icon = "spr_ui_skills_archaeology_icon_back_in_vogue_ii"

[[tier_4]]
	perk = "natural_beauty_two"
	essence = 150
	icon = "spr_ui_skills_archaeology_icon_natural_beauty_ii"

[[tier_5]]
	perk = "mist_sight"
	essence = 200
	icon = "spr_ui_skills_archaeology_icon_mist_sight"