name = "Blacksmithing"
icon_sprite_key = "spr_ui_skills_domain_icon_blacksmithing"
default_lut_index = 22
hovered_lut_index = 23
disabled_lut_index = 24

[[tier_1]]
	perk = "copper_expert"
	essence = 15
	icon = "spr_ui_skills_blacksmithing_icon_copper_expert"

[[tier_1]]
	perk = "time_sensitive"
	essence = 10
	icon = "spr_ui_skills_blacksmithing_icon_time_sensitive_i"

[[tier_1]]
	perk = "sharp_blacksmithing"
	essence = 20
	icon = "spr_ui_skills_blacksmithing_icon_sharp_blacksmithing"

[[tier_1]]
	perk = "fortified_blacksmithing"
	essence = 20
	icon = "spr_ui_skills_blacksmithing_icon_fortified_blacksmithing"

[[tier_2]]
	perk = "iron_expert"
	essence = 50
	icon = "spr_ui_skills_blacksmithing_icon_iron_expert"

[[tier_2]]
	perk = "time_sensitive_two"
	essence = 50
	icon = "spr_ui_skills_blacksmithing_icon_time_sensitive_ii"

[[tier_2]]
	perk = "leech_blacksmithing"
	essence = 45
	icon = "spr_ui_skills_blacksmithing_icon_leech_blacksmithing"

[[tier_2]]
	perk = "lightweight_blacksmithing"
	essence = 45
	icon = "spr_ui_skills_blacksmithing_icon_lightweight_blacksmithing"

[[tier_3]]
	perk = "silver_expert"
	essence = 75
	icon = "spr_ui_skills_blacksmithing_icon_silver_expert"

[[tier_3]]
	perk = "hasty_blacksmithing"
	essence = 75
	icon = "spr_ui_skills_blacksmithing_icon_hasty_blacksmithing"

[[tier_3]]
	perk = "time_sensitive_three"
	essence = 50
	icon = "spr_ui_skills_blacksmithing_icon_time_sensitive_iii"

[[tier_3]]
	perk = "empowered"
	essence = 65
	icon = "spr_ui_skills_blacksmithing_icon_empowered_i"

[[tier_4]]
	perk = "empowered_two"
	essence = 155
	icon = "spr_ui_skills_blacksmithing_icon_empowered_ii"

[[tier_4]]
	perk = "gold_expert"
	essence = 150
	icon = "spr_ui_skills_blacksmithing_icon_gold_expert"

[[tier_4]]
	perk = "tireless_blacksmithing"
	essence = 155
	icon = "spr_ui_skills_blacksmithing_icon_tireless_blacksmithing"

[[tier_4]]
	perk = "time_sensitive_four"
	essence = 150
	icon = "spr_ui_skills_blacksmithing_icon_time_sensitive_iv"

[[tier_5]]
	perk = "mistril_expert"
	essence = 205
	icon = "spr_ui_skills_blacksmithing_icon_mistril_expert"