name = "Combat"
icon_sprite_key = "spr_ui_skills_domain_icon_combat"
default_lut_index = 25
hovered_lut_index = 26
disabled_lut_index = 27

[[tier_1]]
	perk = "guardians_shield"
	essence = 10
	icon = "spr_ui_skills_combat_icon_guardians_shield"

[[tier_1]]
	perk = "true_strike"
	essence = 20
	icon = "spr_ui_skills_combat_icon_true_strike"

[[tier_1]]
	perk = "jump_attack"
	essence = 15
	icon = "spr_ui_skills_combat_icon_jump_attack"

[[tier_1]]
	perk = "well_armed"
	essence = 15
	icon = "spr_ui_skills_combat_icon_well_armed"

[[tier_2]]
	perk = "quick_footed"
	essence = 50
	icon = "spr_ui_skills_combat_icon_quick_footed"

[[tier_2]]
	perk = "shrine_savant"
	essence = 45
	icon = "spr_ui_skills_combat_icon_shrine_savant"

[[tier_2]]
	perk = "generous_in_defeat"
	essence = 50
	icon = "spr_ui_skills_combat_icon_generous_in_defeat"

[[tier_2]]
	perk = "dungeon_delicacies"
	essence = 45
	icon = "spr_ui_skills_combat_icon_dungeon_delicacies"

[[tier_3]]
	perk = "perfect_prefix"
	essence = 80
	icon = "spr_ui_skills_combat_icon_perfect_prefix"

[[tier_3]]
	perk = "rocking"
	essence = 70
	icon = "spr_ui_skills_combat_icon_rocking"

[[tier_3]]
	perk = "in_motion"
	essence = 75
	icon = "spr_ui_skills_combat_icon_in_motion"

[[tier_3]]
	perk = "out_of_juice"
	essence = 70
	icon = "spr_ui_skills_combat_icon_out_of_juice"

[[tier_4]]
	perk = "sonic_boom"
	essence = 160
	icon = "spr_ui_skills_combat_icon_sonic_boom"

[[tier_4]]
	perk = "gift_exchange"
	essence = 155
	icon = "spr_ui_skills_combat_icon_gift_exchange"

[[tier_4]]
	perk = "guardians_shield_two"
	essence = 155
	icon = "spr_ui_skills_combat_icon_guardians_shield_ii"

[[tier_4]]
	perk = "true_strike_two"
	essence = 160
	icon = "spr_ui_skills_combat_icon_true_strike_ii"

[[tier_5]]
	perk = "sure_strike"
	essence = 205
	icon = "spr_ui_skills_combat_icon_sure_strike"

[[tier_5]]
	perk = "generous_in_defeat_two"
	essence = 200
	icon = "spr_ui_skills_combat_icon_generous_in_defeat_ii"

[[tier_5]]
	perk = "friend_shaped"
	essence = 200 #placeholder
	icon = "spr_ui_skills_combat_icon_friend_shaped"
