name = "Cooking"
icon_sprite_key = "spr_ui_skills_domain_icon_cooking"
default_lut_index = 13
hovered_lut_index = 14
disabled_lut_index = 15

[[tier_1]]
	perk = "waste_not_want_not"
	essence = 15
	icon = "spr_ui_skills_cooking_icon_waste_not"

[[tier_1]]
	perk = "time_to_eat"
	essence = 10
	icon = "spr_ui_skills_cooking_icon_time_to_eat_i"

[[tier_1]]
	perk = "restorative_cooking"
	essence = 20
	icon = "spr_ui_skills_cooking_icon_restorative_cooking"

[[tier_1]]
	perk = "taste_maker"
	essence = 15
	icon = "spr_ui_skills_cooking_icon_taste_maker"

[[tier_2]]
	perk = "seasoned"
	essence = 45
	icon = "spr_ui_skills_cooking_icon_seasoned"

[[tier_2]]
	perk = "time_to_eat_two"
	essence = 50
	icon = "spr_ui_skills_cooking_icon_time_to_eat_ii"

[[tier_2]]
	perk = "award_winning"
	essence = 45
	icon = "spr_ui_skills_cooking_icon_award_winning"

[[tier_2]]
	perk = "likable_cooking"
	essence = 50
	icon = "spr_ui_skills_cooking_icon_likable_cooking"

[[tier_3]]
	perk = "speedy_cooking"
	essence = 70
	icon = "spr_ui_skills_cooking_icon_speedy_cooking"

[[tier_3]]
	perk = "dinner_for_two"
	essence = 80
	icon = "spr_ui_skills_cooking_icon_dinner_for_two"

[[tier_3]]
	perk = "a_way_to_the_heart"
	essence = 75
	icon = "spr_ui_skills_cooking_icon_a_way_to_the_heart"

[[tier_3]]
	perk = "time_to_eat_three"
	essence = 70
	icon = "spr_ui_skills_cooking_icon_time_to_eat_iii"

[[tier_4]]
	perk = "loveable_cooking"
	essence = 155
	icon = "spr_ui_skills_cooking_icon_lovable_cooking"

[[tier_4]]
	perk = "snacktime"
	essence = 145
	icon = "spr_ui_skills_cooking_icon_snacktime"

[[tier_4]]
	perk = "caffeine_crimes"
	essence = 155
	icon = "spr_ui_skills_cooking_icon_caffeine_crimes"

[[tier_4]]
	perk = "magical_meals"
	essence = 155
	icon = "spr_ui_skills_cooking_icon_magical_meals"

[[tier_5]]
	perk = "fairy_cooking"
	essence = 205
	icon = "spr_ui_skills_cooking_icon_fairy_cooking"

[[tier_5]]
	perk = "espresso_yourself"
	essence = 205
	icon = "spr_ui_skills_cooking_icon_espresso_yourself"