# These are the default values for each category.
[category]
	# The sprite key for this categories icon
	icon_sprite_key = "<n/a>"
	# The minimum level to unlock entries on each tier
	level_requirements = [1, 15, 30, 45, 60]
	# The index on the lut the icon should use
	default_lut_index = 0
	# The index on the lut the icon should use when hovered
	hovered_lut_index = 0
	# The entries in each tier (all below)
	tier_1 = []
	tier_2 = []
	tier_3 = []
	tier_4 = []
	tier_5 = []

# These are the default values for each entry in the tiers.
[entry]
	# The name displayed in the UI for this entry. If a perk is set, will default to
	# the perk's name.
	name = "<n/a>"
	# The description displayed in the UI for this entry. If a perk is set, will default
	# to the perk's description.
	description = "<n/a>"
	# The icon that will be rendered on this entry's tile.
	icon = "spr_illegal_16"
	# The amount of essence required to purchase this entry.
	essence = 0
	# If provided, the game will fire hand-written code associated with this value.
	custom_id = "<n/a>"
	# If provided, this perk will be unlocked when this entry is purchased.
	perk = "<n/a>"
