name = "Farming"
icon_sprite_key = "spr_ui_skills_domain_icon_farming"
default_lut_index = 4
hovered_lut_index = 5
disabled_lut_index = 6

[[tier_1]]
	perk = "prepared_picker"
	essence = 10
	icon = "spr_ui_skills_farming_icon_prepared_picker"

[[tier_1]]
	perk = "a_day_well_spent"
	essence = 20
	icon = "spr_ui_skills_farming_icon_day_well_spent"

[[tier_1]]
	perk = "green_thumb"
	essence = 15
	icon = "spr_ui_skills_farming_icon_green_thumb"

[[tier_1]]
	perk = "refreshing"
	essence = 10
	icon = "spr_ui_skills_farming_icon_refreshing"

[[tier_2]]
	perk = "bountiful"
	essence = 60
	icon = "spr_ui_skills_farming_icon_bountiful"

[[tier_2]]
	perk = "heavy_duty"
	essence = 30
	icon = "spr_ui_skills_farming_icon_heavy_duty"

[[tier_2]]
	perk = "well_watered"
	essence = 50
	icon = "spr_ui_skills_farming_icon_well_watered"

[[tier_2]]
	perk = "nice_swing"
	essence = 50
	icon = "spr_ui_skills_farming_icon_nice_swing"

[[tier_3]]
	perk = "living_off_the_land"
	essence = 95
	icon = "spr_ui_skills_farming_icon_living_off_the_land"

[[tier_3]]
	perk = "superb_sower"
	essence = 100
	icon = "spr_ui_skills_farming_icon_superb_sower"

[[tier_3]]
	perk = "harvest_time"
	essence = 90
	icon = "spr_ui_skills_farming_icon_harvest_time"

[[tier_3]]
	perk = "prize_winning"
	essence = 90
	icon = "spr_ui_skills_farming_icon_prize_winning"

[[tier_4]]
	perk = "sickle_sword"
	essence = 150
	icon = "spr_ui_skills_farming_icon_sickle_sword"

[[tier_4]]
	perk = "ornamental"
	essence = 145
	icon = "spr_ui_skills_farming_icon_ornamental"

[[tier_4]]
	perk = "perfect_pollinators"
	essence = 155
	icon = "spr_ui_skills_farming_icon_perfect_pollinators"

[[tier_4]]
	perk = "magic_design"
	essence = 160
	icon = "spr_ui_skills_farming_icon_magic_design"

[[tier_5]]
	perk = "earthly_essence"
	essence = 210
	icon = "spr_ui_skills_farming_icon_earthly_essence"