name = "Fishing"
icon_sprite_key = "spr_ui_skills_domain_icon_fishing"
default_lut_index = 7
hovered_lut_index = 8
disabled_lut_index = 9

[[tier_1]]
	perk = "weedline_watcher"
	essence = 15
	icon = "spr_ui_skills_fishing_icon_weedline_watcher"

[[tier_1]]
	perk = "aquatic_antiquities"
	essence = 20
	icon = "spr_ui_skills_fishing_icon_aquatic_antiquities"

[[tier_1]]
	perk = "appealing_reeling"
	essence = 10
	icon = "spr_ui_skills_fishing_icon_appealing_reeling"

[[tier_1]]
	perk = "catch_of_the_day"
	essence = 15
	icon = "spr_ui_skills_fishing_icon_catch_of_the_day"

[[tier_2]]
	perk = "school_crasher"
	essence = 50
	icon = "spr_ui_skills_fishing_icon_school_crasher"

[[tier_2]]
	perk = "lucky_haul"
	essence = 40
	icon = "spr_ui_skills_fishing_icon_lucky_haul_i"

[[tier_2]]
	perk = "perfect_catch"
	essence = 50
	icon = "spr_ui_skills_fishing_icon_perfect_catch"

[[tier_2]]
	perk = "unexpected_haul"
	essence = 40
	icon = "spr_ui_skills_fishing_icon_unexpected_haul"

[[tier_3]]
	perk = "full_class"
	essence = 75
	icon = "spr_ui_skills_fishing_icon_full_class_i"

[[tier_3]]
	perk = "legendary"
	essence = 80
	icon = "spr_ui_skills_fishing_icon_legendary"

[[tier_3]]
	perk = "treasure_trove"
	essence = 70
	icon = "spr_ui_skills_fishing_icon_treasure_trove"

[[tier_3]]
	perk = "weedline_watcher_two"
	essence = 75
	icon = "spr_ui_skills_fishing_icon_weedline_watcher_ii"

[[tier_4]]
	perk = "appealing_reeling_two"
	essence = 155
	icon = "spr_ui_skills_fishing_icon_appealing_reeling_ii"

[[tier_4]]
	perk = "frenzy"
	essence = 150
	icon = "spr_ui_skills_fishing_icon_frenzy"

[[tier_4]]
	perk = "what_a_catch"
	essence = 145
	icon = "spr_ui_skills_fishing_icon_what_a_catch"

[[tier_4]]
	perk = "lucky_haul_two"
	essence = 155
	icon = "spr_ui_skills_fishing_icon_lucky_haul_ii"

[[tier_5]]
	perk = "abyssal_ascendence"
	icon = "spr_ui_skills_fishing_icon_abyssal_ascendence"
	essence = 205