name = "Mining"
icon_sprite_key = "spr_ui_skills_domain_icon_mining"
default_lut_index = 10
hovered_lut_index = 11
disabled_lut_index = 12

[[tier_1]]
	perk = "earth_breaker"
	essence = 20
	icon = "spr_ui_skills_mining_icon_earthbreaker"

[[tier_1]]
	perk = "ore_riginal"
	essence = 25
	icon = "spr_ui_skills_mining_icon_ore_ginal"

[[tier_1]]
	perk = "reclaimer"
	essence = 15
	icon = "spr_ui_skills_mining_icon_reclaimer"

[[tier_1]]
	perk = "treasure_hunter"
	essence = 20
	icon = "spr_ui_skills_mining_icon_treasure_hunter"

[[tier_2]]
	perk = "iron_hound"
	essence = 50
	icon = "spr_ui_skills_mining_icon_iron_hound"

[[tier_2]]
	perk = "true_blue"
	essence = 45
	icon = "spr_ui_skills_mining_icon_true_blue"

[[tier_2]]
	perk = "treasured"
	essence = 45
	icon = "spr_ui_skills_mining_icon_treasured"

[[tier_2]]
	perk = "mine_time"
	essence = 50
	icon = "spr_ui_skills_mining_icon_mine_time"

[[tier_3]]
	perk = "resonance"
	essence = 75
	icon = "spr_ui_skills_mining_icon_resonance"

[[tier_3]]
	perk = "earth_breaker_two"
	essence = 80
	icon = "spr_ui_skills_mining_icon_earthbreaker_ii"

[[tier_3]]
	perk = "silver_seeker"
	essence = 85
	icon = "spr_ui_skills_mining_icon_silver_seeker"

[[tier_3]]
	perk = "fantastic_finds"
	essence = 80
	icon = "spr_ui_skills_mining_icon_fantastic_finds"

[[tier_4]]
	perk = "lost_to_history"
	essence = 155
	icon = "spr_ui_skills_mining_icon_lost_to_history"

[[tier_4]]
	perk = "good_as_gold"
	essence = 150
	icon = "spr_ui_skills_mining_icon_good_as_gold"

[[tier_4]]
	perk = "refined_rockery"
	essence = 150
	icon = "spr_ui_skills_mining_icon_refined_rockery"

[[tier_4]]
	perk = "break_one_get_two"
	essence = 155
	icon = "spr_ui_skills_mining_icon_break_one_get_two"

[[tier_5]]
	perk = "mistril_mastery"
	essence = 200
	icon = "spr_ui_skills_mining_icon_mistril_mastery"

[[tier_5]]
	perk = "perfect_pick"
	essence = 210
	icon = "spr_ui_skills_mining_icon_perfect_pick"

[[tier_5]]
	perk = "void_value"
	essence = 205
	icon = "spr_ui_skills_mining_icon_void_value"

[[tier_5]]
	perk = "lost_to_history_two"
	essence = 200
	icon = "spr_ui_skills_mining_icon_lost_to_history_ii"