name = "Mistmare"
icon_sprite_key = "spr_ui_skills_domain_icon_mount"
default_lut_index = 31
hovered_lut_index = 32
disabled_lut_index = 33


[[tier_1]]
	perk = "horsepower"
	essence = 200
	icon = "spr_ui_skills_mount_icon_horsepower"

[[tier_1]]
	perk = "harvest_horse"
	essence = 190
	icon = "spr_ui_skills_mount_icon_harvest_horse"

[[tier_1]]
	perk = "nice_ride"
	essence = 205
	icon = "spr_ui_skills_mount_icon_nice_ride"
