name = "Ranching"
icon_sprite_key = "spr_ui_skills_domain_icon_ranching"
default_lut_index = 19
hovered_lut_index = 20
disabled_lut_index = 21

[[tier_1]]
	perk = "feeding_frenzy"
	essence = 15
	icon = "spr_ui_skills_ranching_icon_feeding_frenzy"

[[tier_1]]
	perk = "close_bond"
	essence = 25
	icon = "spr_ui_skills_ranching_icon_close_bond"

[[tier_1]]
	perk = "barnyard_bounty"
	essence = 30
	icon = "spr_ui_skills_ranching_icon_barnyard_bounty_i"

[[tier_1]]
	perk = "currency_of_care"
	essence = 25
	icon = "spr_ui_skills_ranching_icon_currency_of_care"

[[tier_2]]
	perk = "currency_of_care_two"
	essence = 50
	icon = "spr_ui_skills_ranching_icon_currency_of_care_ii"

[[tier_2]]
	perk = "feed_prepper"
	essence = 40
	icon = "spr_ui_skills_ranching_icon_feed_prepper"

[[tier_2]]
	perk = "welcome_home"
	essence = 45
	icon = "spr_ui_skills_ranching_icon_welcome_home_i"

[[tier_2]]
	perk = "discount_treats"
	essence = 40
	icon = "spr_ui_skills_ranching_icon_discount_treats"

[[tier_3]]
	perk = "currency_of_care_three"
	essence = 75
	icon = "spr_ui_skills_ranching_icon_currency_of_care_iii"

[[tier_3]]
	perk = "welcome_home_two"
	essence = 70
	icon = "spr_ui_skills_ranching_icon_welcome_home_ii"

[[tier_3]]
	perk = "barnyard_bounty_two"
	essence = 80
	icon = "spr_ui_skills_ranching_icon_barnyard_bounty_ii"

[[tier_3]]
	perk = "wind_down"
	essence = 145
	icon = "spr_ui_skills_ranching_icon_wind_down"

[[tier_4]]
	perk = "the_bell_tolls"
	essence = 155
	icon = "spr_ui_skills_ranching_icon_the_bell_tolls"

[[tier_4]]
	perk = "maximum_milling"
	essence = 150
	icon = "spr_ui_skills_ranching_icon_maximum_milling"

[[tier_4]]
	perk = "barnyard_bounty_three"
	essence = 145
	icon = "spr_ui_skills_ranching_icon_barnyard_bounty_iii"

[[tier_4]]
	perk = "playtime"
	essence = 150
	icon = "spr_ui_skills_ranching_icon_playtime_i"

[[tier_5]]
	perk = "eggstra"
	essence = 205
	icon = "spr_ui_skills_ranching_icon_eggstra"

[[tier_5]]
	perk = "close_bond_two"
	essence = 210
	icon = "spr_ui_skills_ranching_icon_close_bond_ii"

[[tier_5]]
	perk = "true_trust"
	essence = 215
	icon = "spr_ui_skills_ranching_icon_true_trust"