name = "Woodcrafting"
icon_sprite_key = "spr_ui_skills_domain_icon_crafting"
default_lut_index = 28
hovered_lut_index = 29
disabled_lut_index = 30

[[tier_1]]
	perk = "hammer_timing"
	essence = 10
	icon = "spr_ui_skills_crafting_icon_hammer_timing_i"

[[tier_1]]
	perk = "lumberjack"
	essence = 15
	icon = "spr_ui_skills_crafting_icon_lumberjack_i"

[[tier_1]]
	perk = "masonry"
	essence = 15
	icon = "spr_ui_skills_crafting_icon_masonry_i"

[[tier_1]]
	perk = "forager"
	essence = 20
	icon = "spr_ui_skills_crafting_icon_forager"

[[tier_2]]
	perk = "working_with_the_grain"
	essence = 60
	icon = "spr_ui_skills_crafting_icon_working_with_the_grain"

[[tier_2]]
	perk = "quality_crafting"
	essence = 95
	icon = "spr_ui_skills_crafting_icon_quality_crafting"

[[tier_2]]
	perk = "natural"
	essence = 20
	icon = "spr_ui_skills_crafting_icon_natural"

[[tier_2]]
	perk = "hammer_timing_two"
	essence = 50
	icon = "spr_ui_skills_crafting_icon_hammer_timing_ii"

[[tier_3]]
	perk = "material_world"
	essence = 75
	icon = "spr_ui_skills_crafting_icon_material_world"

[[tier_3]]
	perk = "steady_supplies"
	essence = 70
	icon = "spr_ui_skills_crafting_icon_steady_supplies"

[[tier_3]]
	perk = "set_pieces"
	essence = 80
	icon = "spr_ui_skills_crafting_icon_set_pieces"

[[tier_3]]
	perk = "hammer_timing_three"
	essence = 50
	icon = "spr_ui_skills_crafting_icon_hammer_timing_iii"

[[tier_4]]
	perk = "lumberjack_two"
	icon = "spr_ui_skills_crafting_icon_lumberjack_ii"
	essence = 155

[[tier_4]]
	perk = "underground_inspiration"
	icon = "spr_ui_skills_crafting_icon_underground_inspiration"
	essence = 145

[[tier_4]]
	perk = "deliberate_debris"
	icon = "spr_ui_skills_crafting_icon_deliberate_debris"
	essence = 150


[[tier_4]]
	perk = "working_with_the_grain_two"
	icon = "spr_ui_skills_crafting_icon_working_with_the_grain_ii"
	essence = 155

[[tier_5]]
	perk = "void_crafting"
 	icon = "spr_ui_skills_crafting_icon_void_crafting"
 	essence = 205

[[tier_5]]
 	perk = "big_water_sprites"
 	icon = "spr_ui_skills_crafting_icon_big_water_sprites"
	essence = 205

[[tier_5]]
	perk = "hammer_timing_four"
	icon = "spr_ui_skills_crafting_icon_hammer_timing_iv"
	essence = 210

[[tier_5]]
	perk = "deliberate_debris_two"
	icon = "spr_ui_skills_crafting_icon_deliberate_debris_ii"
	essence = 200