name = "Darren"
outfits = ["spring"]
voice = "SoundEffects/NPCs/Vocal/TextBlipDarren"

[offsets]
	portrait = [-126, -65]
	sweat = [10, 2]
	hearts = [10, 2]
	angry = [6, -6]
	sparkles = [10, -6]
	sparkles_dark = [10, -6]
	sick = [14, -4]
	music_notes = [6, -4]
	intensity = [7, -15]
	surprise = [8, -1]
	shock = [9, -12]
	sigh = [7, -3]
	loud = [12, -8]
	cheery = [8, 4]
	drop = [11, -10]

[portraits]
	neutral = ["spring"]
	think = ["spring"]
	happy = ["spring"]
	wink = ["spring"]
	mad = ["spring"]
	embarrassed = ["spring"]
	sad = ["spring"]
	ugh = ["spring"]

[cycles.idle]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring"]
	type = "linear"
	on_pause_speaking_turn = true

[cycles.walk]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring"]
	type = "linear"

[cycles.blink]
	default_direction = "south"
	directions = ["south", "east"]
	outfits = ["spring"]
	type = "linear"

[cycles.sit]
	default_direction = "south"
	directions = ["north", "south", "east"]
	is_seated = true
	outfits = ["spring"]
	type = "linear"