name = "Great Bird"
outfits = ["spring"]
voice = "SoundEffects/NPCs/Vocal/TextBlipGeneric"

[offsets]
	portrait = [-105, -65]
	sweat = [0, 0]
	hearts = [0, 0]
	angry = [0, 0]
	sparkles = [0, 0]
	sparkles_dark = [0, 0]
	sick = [0, 0]
	music_notes = [0, 0]
	intensity = [0, 0]
	surprise = [0, 0]
	shock = [0, 0]
	sigh = [0, 0]
	loud = [0, 0]
	cheery = [0, 0]
	drop = [0, 0]

[portraits]
	neutral = ["spring"]
	happy = ["spring"]
	mad = ["spring"]
	sad = ["spring"]
	ugh = ["spring"]
	neutral_closed = ["spring"]

[cycles]
