name = "Wiscar"
outfits = ["spring"]
voice = "SoundEffects/NPCs/Vocal/TextBlipWiscar"

[offsets]
	portrait = [-121, -65]
	sweat = [-5, 20]
	hearts = [-5, 20]
	angry = [-5, 2]
	sparkles = [0, -2]
	sparkles_dark = [0, -2]
	sick = [2, 4]
	music_notes = [-3, -1]
	intensity = [0, -7]
	surprise = [0, 6]
	shock = [1, -3]
	sigh = [-1, 5]
	loud = [7, 4]
	cheery = [0, 11]
	drop = [1, 3]

[portraits]
	neutral = ["spring"]
	think = ["spring"]
	happy = ["spring"]
	wink = ["spring"]
	mad = ["spring"]
	embarrassed = ["spring"]
	sad = ["spring"]
	ugh = ["spring"]

[cycles.idle]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring"]
	type = "linear"
	on_pause_speaking_turn = true

[cycles.walk]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring"]
	type = "linear"

[cycles.blink]
	default_direction = "south"
	directions = ["south", "east"]
	outfits = ["spring"]
	type = "linear"

[cycles.sit]
	default_direction = "south"
	directions = ["north", "south", "east"]
	is_seated = true
	outfits = ["spring"]
	type = "linear"