name = "Wynne"
outfits = ["spring"]
voice = "SoundEffects/NPCs/Vocal/TextBlipWynne"

[offsets]
	portrait = [-126, -65]
	sweat = [-4, 16]
	hearts = [-4, 16]
	angry = [-10, 5]
	sparkles = [-2, 1]
	sparkles_dark = [-2, 1]
	sick = [-1, 10]
	music_notes = [-1, 8]
	intensity = [3, -2]
	surprise = [-6, 7]
	shock = [-3, -3]
	sigh = [2, 3]
	loud = [3, 3]
	cheery = [-1, 13]
	drop = [0, 3]

[portraits]
	neutral = ["spring"]
	think = ["spring"]
	happy = ["spring"]
	wink = ["spring"]
	mad = ["spring"]
	embarrassed = ["spring"]
	sad = ["spring"]
	ugh = ["spring"]

[cycles.idle]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring"]
	type = "linear"
	on_pause_speaking_turn = true

[cycles.walk]
	default_direction = "south"
	directions = ["north", "south", "east"]
	outfits = ["spring"]
	type = "linear"

[cycles.blink]
	default_direction = "south"
	directions = ["south", "east"]
	outfits = ["spring"]
	type = "linear"

[cycles.sit]
	default_direction = "south"
	directions = ["north", "south", "east"]
	is_seated = true
	outfits = ["spring"]
	type = "linear"