[massive_minnow]
	description = "A common fish that can only be lured with Common Fish Bait. It's quite massive...for a minnow."
	icon_sprite = "spr_ui_item_fish_massive_minnow"
	name = "Massive Minnow"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[copper_rockfish]
	description = "A common fish that can only be lured with Common Fish Bait. The scales of his fish are a deep, burnished copper."
	icon_sprite = "spr_ui_item_fish_copper_rockfish"
	name = "Copper Rockfish"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[iron_fish]
	description = "An uncommon fish that can only be lured with Uncommon Fish Bait. It could almost be mistaken for a piece of iron."
	icon_sprite = "spr_ui_item_fish_iron_fish"
	name = "Iron Fish"
	value = { bin = 65 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[silver_squid]
	description = "An uncommon fish that can only be lured with Uncommon Fish Bait. Widely considered to be good luck if caught."
	icon_sprite = "spr_ui_item_fish_silver_squid"
	name = "Silver Squid"
	value = { bin = 75 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[golden_eel]
	description = "A rare fish that can only be lured with Rare Fish Bait. This mysterious eel is rarely seen in nature."
	icon_sprite = "spr_ui_item_fish_golden_eel"
	name = "Golden Eel"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]
