#DEEP WOODS FISH

[sunny]
	description = "A common small Deep Woods fish found on rainy or snowy days in all seasons."
	icon_sprite = "spr_ui_item_fish_small_sunny"
	name = "Sunny"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[forest_perch]
	description = "A common medium Deep Woods fish found on rainy or snowy days in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_forest_perch"
	name = "Forest Perch"
	value = { bin = 50 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[silver_redhorse]
	description = "An uncommon medium Deep Woods fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_silver_redhorse"
	name = "Silver Redhorse"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[lake_trout]
	description = "A common large Deep Woods fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_large_lake_trout"
	name = "Lake Trout"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[muskie]
	description = "An uncommon large Deep Woods fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_large_muskie"
	name = "Muskie"
	value = { bin = 90 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]
