# <---------MISC FISHING ITEMS------------->

# <---------TREASURE BOXES------------->

[treasure_box_wood]
	name = "Wooden Treasure Box"
	description = "A common wooden treasure box. Open it to find out what's inside!"
	icon_sprite = "spr_ui_item_wooden_chest"
	soulbind = "forever"

[treasure_box_copper]
	name = "Copper Treasure Box"
	description = "An uncommon copper treasure box. Open it to find out what's inside!"
	icon_sprite = "spr_ui_item_copper_chest"
	soulbind = "forever"

[treasure_box_silver]
	name = "Silver Treasure Box"
	description = "A rare silver treasure box. Open it to find out what's inside!"
	icon_sprite = "spr_ui_item_silver_chest"
	soulbind = "forever"

[treasure_box_gold]
	name = "Golden Treasure Box"
	description = "A very rare golden treasure box. Open it to find out what's inside!"
	icon_sprite = "spr_ui_item_gold_chest"
	soulbind = "forever"

	# <---------DIVE SPOT ITEMS------------->

[seaweed]
	description = "A common plant, grows in all seasons."
	icon_sprite = "spr_ui_item_dive_seaweed"
	name = "Seaweed"
	value = { bin = 15 }
	edible = false
	restore = 6
	tags = ["dive", "ocean", "fishable"]

[clam]
	description = "A common find found in all seasons."
	icon_sprite = "spr_ui_item_dive_clam"
	name = "Clam"
	value = { bin = 20 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "ocean", "fishy", "fishable"]

[newt]
	description = "A common amphibian found in all seasons."
	icon_sprite = "spr_ui_item_dive_newt"
	name = "Newt"
	value = { bin = 25 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "pond", "junk", "fishable"]

[pearl_clam]
	description = "A common ocean mollusk, found in all seasons."
	icon_sprite = "spr_ui_item_dive_pearl_clam"
	name = "Pearl Clam"
	value = { bin = 25 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "ocean", "fishy", "fishable"]

[paper_pondshell]
	description = "A common pond mussel, found in all seasons."
	icon_sprite = "spr_ui_item_dive_paper_pondshell"
	name = "Paper Pondshell"
	value = { bin = 20 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "pond", "fishy", "fishable"]

[freshwater_oyster]
	description = "A common river mussel, found in all seasons."
	icon_sprite = "spr_ui_item_dive_freshwater_oyster"
	name = "Freshwater Oyster"
	value = { bin = 25 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "river", "fishy", "fishable"]

	# <---------FORAGE BEACH SHELLS------------->

[spirula_shell]
	description = "A common shell found on the Beach."
	icon_sprite = "spr_ui_item_shell_common_spirula"
	name = "Spirula Shell"
	value = { bin = 30, store = 120 }
	tags = ["dive", "forageable", "material"]

[sand_dollar]
	description = "A common shell found on the Beach."
	icon_sprite = "spr_ui_item_shell_sand_dollar"
	name = "Sand Dollar"
	value = { bin = 25, store = 100 }
	tags = ["dive", "forageable", "material"]

[pink_scallop_shell]
	description = "A common shell found on the Beach."
	icon_sprite = "spr_ui_item_shell_pink_scallop"
	name = "Pink Scallop Shell"
	value = { bin = 20, store = 60 }
	tags = ["dive", "forageable", "material"]

[blue_conch_shell]
	description = "A common blue conch shell."
	icon_sprite = "spr_ui_item_shell_small_blue_conch"
	name = "Blue Conch Shell"
	value = { bin = 20, store = 80 }
	tags = ["fish_or_dive", "forageable", "material"]
