# <---------MULTI-SEASON OCEAN FISH------------->

[cod]
	description = "A common large ocean fish found in summer and winter."
	icon_sprite = "spr_ui_item_fish_large_cod"
	name = "Cod"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[jellyfish]
	description = "An uncommon medium ocean invertebrate found in spring and fall."
	icon_sprite = "spr_ui_item_fish_medium_jellyfish"
	name = "Jellyfish"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[octopus]
	description = "An uncommon large ocean cephalopod found in summer and winter."
	icon_sprite = "spr_ui_item_fish_large_octopus"
	name = "Octopus"
	value = { bin = 70 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[pollock]
	description = "A common large ocean fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_large_pollock"
	name = "Pollock"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[puffer_fish]
	description = "An uncommon medium ocean fish found in summer and winter."
	icon_sprite = "spr_ui_item_fish_medium_puffer_fish"
	name = "Puffer Fish"
	value = { bin = 90 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[red_snapper]
	description = "A common large ocean fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_large_red_snapper"
	name = "Red Snapper"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sardine]
	description = "A common small ocean fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_small_sardine"
	name = "Sardine"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sea_bream]
	description = "A common medium ocean fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_medium_sea_bream"
	name = "Sea Bream"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[squid]
	description = "A common medium ocean cephalopod found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_squid"
	name = "Squid"
	value = { bin = 30 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[swordfish]
	description = "An uncommon large ocean fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_large_swordfish"
	name = "Swordfish"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[tuna]
	description = "A common large ocean fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_large_tuna"
	name = "Tuna"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------SPRING OCEAN FISH------------->

[anchovy]
	description = "A common small ocean fish found in spring."
	icon_sprite = "spr_ui_item_fish_small_anchovy"
	name = "Anchovy"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[lobster]
	description = "A common medium ocean crustacean found in spring."
	icon_sprite = "spr_ui_item_fish_medium_lobster"
	name = "Lobster"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[mackerel]
	description = "A common large ocean fish found on rainy days in spring."
	icon_sprite = "spr_ui_item_fish_large_mackerel"
	name = "Mackerel"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[ocean_sunfish]
	description = "A rare giant ocean fish found in spring."
	icon_sprite = "spr_ui_item_fish_giant_ocean_sunfish"
	name = "Ocean Sunfish"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[shrimp]
	description = "A common small ocean crustacean found in spring."
	icon_sprite = "spr_ui_item_fish_small_shrimp"
	name = "Shrimp"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------SUMMER OCEAN FISH------------->

[bonito]
	description = "A common medium ocean fish found in summer and winter."
	icon_sprite = "spr_ui_item_fish_medium_bonito"
	name = "Bonito"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[char]
	description = "A common large ocean fish found in summer."
	icon_sprite = "spr_ui_item_fish_large_char"
	name = "Char"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[crab]
	description = "A common small ocean crustacean found in summer."
	icon_sprite = "spr_ui_item_fish_small_crab"
	name = "Crab"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[dart]
	description = "A common small ocean fish found in summer."
	icon_sprite = "spr_ui_item_fish_small_dart"
	name = "Dart"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[grouper]
	description = "A rare giant ocean fish found in summer."
	icon_sprite = "spr_ui_item_fish_giant_grouper"
	name = "Grouper"
	value = { bin = 90 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[stingray]
	description = "A common medium ocean fish found in summer."
	icon_sprite = "spr_ui_item_fish_medium_stingray"
	name = "Stingray"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------FALL OCEAN FISH------------->

[butterfish]
	description = "A common small ocean fish found in fall."
	icon_sprite = "spr_ui_item_fish_small_butterfish"
	name = "Butterfish"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[halibut]
	description = "A common large ocean fish found on rainy days in fall."
	icon_sprite = "spr_ui_item_fish_large_halibut"
	name = "Halibut"
	value = { bin = 50 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[mullet]
	description = "A common medium ocean fish found in fall."
	icon_sprite = "spr_ui_item_fish_medium_mullet"
	name = "Mullet"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[saury]
	description = "A common large ocean fish found in fall."
	icon_sprite = "spr_ui_item_fish_small_saury"
	name = "Saury"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[shark]
	description = "A rare giant ocean fish found in fall."
	icon_sprite = "spr_ui_item_fish_giant_shark"
	name = "Shark"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------WINTER OCEAN FISH------------->

[horse_mackerel]
	description = "A common small ocean fish found in winter."
	icon_sprite = "spr_ui_item_fish_small_horse_mackerel"
	name = "Horse Mackerel"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[king_crab]
	description = "A common large ocean crustacean found on snowy days in winter."
	icon_sprite = "spr_ui_item_fish_large_king_crab"
	name = "King Crab"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[oarfish]
	description = "A rare giant ocean fish found in winter."
	icon_sprite = "spr_ui_item_fish_giant_oarfish"
	name = "Oarfish"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sand_lance]
	description = "A common small ocean fish found in winter."
	icon_sprite = "spr_ui_item_fish_small_sand_lance"
	name = "Sand Lance"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sea_bass]
	description = "A common medium ocean fish found in winter."
	icon_sprite = "spr_ui_item_fish_medium_sea_bass"
	name = "Sea Bass"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[snow_fish]
	description = "A legendary medium ocean fish found on blizzard days in winter."
	icon_sprite = "spr_ui_item_fish_medium_snow_fish"
	name = "Snow Fish"
	value = { bin = 500 }
	soulbind.invert.donated_item = "snow_fish"
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy", "legendary_fish"]
