# <---------MULTI-SEASON POND FISH------------->

[bullfrog]
	description = "A common small pond catch found on rainy and snowy days in summer and winter."
	icon_sprite = "spr_ui_item_fish_small_bullfrog"
	name = "Bullfrog"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[catfish]
	description = "An uncommon medium pond fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_catfish"
	name = "Catfish"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[frog]
	description = "A common small pond amphibian found in spring and fall."
	icon_sprite = "spr_ui_item_fish_small_frog"
	name = "Frog"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[koi]
	description = "A common medium pond fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_koi"
	name = "Koi"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[roach]
	description = "A common medium pond fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_roach"
	name = "Roach"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[snakehead]
	description = "An uncommon large pond fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_large_snakehead"
	name = "Snakehead"
	value = { bin = 60 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[snapping_turtle]
	description = "A common large pond reptile found in summer and winter."
	icon_sprite = "spr_ui_item_fish_large_snapping_turtle"
	name = "Snapping Turtle"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[tetra]
	description = "A common small pond fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_small_tetra"
	name = "Tetra"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[turtle]
	description = "A common large pond reptile found in all seasons."
	icon_sprite = "spr_ui_item_fish_large_turtle"
	name = "Turtle"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------SPRING POND FISH------------->

[angel_fish]
	description = "A common small pond fish found in spring."
	icon_sprite = "spr_ui_item_fish_small_angel_fish"
	name = "Angel Fish"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[barb]
	description = "A common small pond fish found in spring."
	icon_sprite = "spr_ui_item_fish_small_barb"
	name = "Barb"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[cherry_fish]
	description = "A legendary small pond fish found on breezy cherry blossom days in spring."
	icon_sprite = "spr_ui_item_fish_small_cherry_fish"
	name = "Cherry Fish"
	value = { bin = 500 }
	soulbind.invert.donated_item = "cherry_fish"
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy", "legendary_fish"]

[crucian_carp]
	description = "A common medium pond fish found in spring."
	icon_sprite = "spr_ui_item_fish_medium_crucian_carp"
	name = "Crucian Carp"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[goldfish]
	description = "A rare small pond fish found in spring."
	icon_sprite = "spr_ui_item_fish_small_goldfish"
	name = "Goldfish"
	value = { bin = 120 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------SUMMER POND FISH------------->

[brown_bullhead]
	description = "A common medium pond fish found in summer."
	icon_sprite = "spr_ui_item_fish_medium_brown_bullhead"
	name = "Brown Bullhead"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[brown_trout]
	description = "A common large pond fish found in spring."
	icon_sprite = "spr_ui_item_fish_large_brown_trout"
	name = "Brown Trout"
	value = { bin = 50 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[giant_koi]
	description = "A rare giant pond fish found in summer."
	icon_sprite = "spr_ui_item_fish_giant_giant_koi"
	name = "Giant Koi"
	value = { bin = 90 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[golden_shiner]
	description = "A common small pond fish found in summer."
	icon_sprite = "spr_ui_item_fish_small_golden_shiner"
	name = "Golden Shiner"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[lake_chub]
	description = "A common small pond fish found in summer."
	icon_sprite = "spr_ui_item_fish_small_lake_chub"
	name = "Lake Chub"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sauger]
	description = "A common large pond fish found in summer."
	icon_sprite = "spr_ui_item_fish_large_sauger"
	name = "Sauger"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]


	# <---------FALL POND FISH------------->

[bluefish]
	description = "A common large pond fish found on rainy days in fall."
	icon_sprite = "spr_ui_item_fish_large_bluefish"
	name = "Bluefish"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[killifish]
	description = "A common small pond fish found in fall."
	icon_sprite = "spr_ui_item_fish_small_killifish"
	name = "Killifish"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[white_perch]
	description = "A rare medium pond fish found in fall."
	icon_sprite = "spr_ui_item_fish_medium_white_perch"
	name = "White Perch"
	value = { bin = 120 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[rainbow_trout]
	description = "A common medium pond fish found in fall."
	icon_sprite = "spr_ui_item_fish_medium_rainbow_trout"
	name = "Rainbow Trout"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[striped_bass]
	description = "A common large pond fish found in fall."
	icon_sprite = "spr_ui_item_fish_large_striped_bass"
	name = "Striped Bass"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------WINTER POND FISH------------->

[alligator_gar]
	description = "A rare giant pond fish found in winter."
	icon_sprite = "spr_ui_item_fish_giant_alligator_gar"
	name = "Alligator Gar"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[burbot]
	description = "A common large pond fish found on snowy days in winter."
	icon_sprite = "spr_ui_item_fish_large_burbot"
	name = "Burbot"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[flathead_catfish]
	description = "A common medium pond fish found in winter."
	icon_sprite = "spr_ui_item_fish_medium_flathead_catfish"
	name = "Flathead Catfish"
	value = { bin = 30 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[freshwater_eel]
	description = "A common medium river fish found in winter."
	icon_sprite = "spr_ui_item_fish_medium_freshwater_eel"
	name = "Freshwater Eel"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[giant_tilapia]
	description = "An uncommon giant pond fish found in winter."
	icon_sprite = "spr_ui_item_fish_large_giant_tilapia"
	name = "Giant Tilapia"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[tilapia]
	description = "A common small pond fish found in winter."
	icon_sprite = "spr_ui_item_fish_small_tilapia"
	name = "Tilapia"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]
