# <---------MULTI-SEASON RIVER FISH------------->

[chum]
	description = "An uncommon large river fish found in summer and winter."
	icon_sprite = "spr_ui_item_fish_large_chum"
	name = "Chum"
	value = { bin = 75 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[crayfish]
	description = "A common river crustacean found in all seasons."
	icon_sprite = "spr_ui_item_dive_crayfish"
	name = "Crayfish"
	value = { bin = 25 }
	edible = false
	restore = "dive_item_restore"
	tags = ["dive", "river", "fishy"]

[gar]
	description = "A common large river fish found in summer and winter."
	icon_sprite = "spr_ui_item_fish_large_gar"
	name = "Gar"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[goby]
	description = "An uncommon medium river fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_goby"
	name = "Goby"
	value = { bin = 70 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[pike]
	description = "A common large river fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_large_pike"
	name = "Pike"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[rock_bass]
	description = "A common medium river fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_medium_rock_bass"
	name = "Rock Bass"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[salmon]
	description = "A common large river fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_large_salmon"
	name = "Salmon"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[smallmouth_bass]
	description = "A common small river fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_small_smallmouth_bass"
	name = "Smallmouth Bass"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sturgeon]
	description = "An uncommon large river fish found in spring and fall."
	icon_sprite = "spr_ui_item_fish_large_sturgeon"
	name = "Sturgeon"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[trout]
	description = "A common medium river fish found in all seasons."
	icon_sprite = "spr_ui_item_fish_medium_trout"
	name = "Trout"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------SPRING RIVER FISH------------->

[bluegill]
	description = "A common small river fish found in spring."
	icon_sprite = "spr_ui_item_fish_small_blue_gill"
	name = "Blue Gill"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[walleye]
	description = "A common large river fish found on rainy days in spring."
	icon_sprite = "spr_ui_item_fish_large_walleye"
	name = "Walleye"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[carp]
	description = "A common medium river fish found in spring."
	icon_sprite = "spr_ui_item_fish_medium_carp"
	name = "Carp"
	value = { bin = 35 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[chub]
	description = "A common small river fish found in spring."
	icon_sprite = "spr_ui_item_fish_small_chub"
	name = "Chub"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[paddlefish]
	description = "A rare giant river fish found in spring."
	icon_sprite = "spr_ui_item_fish_giant_paddlefish"
	name = "Paddlefish"
	value = { bin = 90 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------SUMMER RIVER FISH------------->

[bream]
	description = "A common large river fish found in summer."
	icon_sprite = "spr_ui_item_fish_large_bream"
	name = "Bream"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[lightning_fish]
	description = "A legendary medium river fish found on stormy days in summer."
	icon_sprite = "spr_ui_item_fish_medium_lightning_fish"
	name = "Lightning Fish"
	value = { bin = 500 }
	soulbind.invert .donated_item = "lightning_fish"
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy", "legendary_fish"]

[loach]
	description = "A common small river fish found in summer."
	icon_sprite = "spr_ui_item_fish_small_loach"
	name = "Loach"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[minnow]
	description = "A common small river fish found in summer."
	icon_sprite = "spr_ui_item_fish_small_minnow"
	name = "Minnow"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[sweetfish]
	description = "A common medium river fish found in summer."
	icon_sprite = "spr_ui_item_fish_medium_sweetfish"
	name = "Sweetfish"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[tarpon]
	description = "A rare giant river fish found in summer."
	icon_sprite = "spr_ui_item_fish_giant_tarpon"
	name = "Tarpon"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------FALL RIVER FISH------------->

[grayling]
	description = "A common small river fish found on rainy days in fall."
	icon_sprite = "spr_ui_item_fish_small_grayling"
	name = "Grayling"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[lamprey]
	description = "A common small river fish found in fall."
	icon_sprite = "spr_ui_item_fish_small_lamprey"
	name = "Lamprey"
	value = { bin = 70 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[leaf_fish]
	description = "A legendary small river fish found on breezy falling leaf days in fall."
	icon_sprite = "spr_ui_item_fish_small_leaf_fish"
	name = "Leaf Fish"
	value = { bin = 500 }
	soulbind.invert.donated_item = "leaf_fish"
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy", "legendary_fish"]

[perch]
	description = "A common large river fish found on rainy days in fall."
	icon_sprite = "spr_ui_item_fish_large_perch"
	name = "Perch"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[razorback]
	description = "A rare medium river fish found in fall."
	icon_sprite = "spr_ui_item_fish_medium_razorback"
	name = "Razorback"
	value = { bin = 160 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[shad]
	description = "A common medium river fish found in fall."
	icon_sprite = "spr_ui_item_fish_medium_shad"
	name = "Shad"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

	# <---------WINTER RIVER FISH------------->

[bowfish]
	description = "A common large river fish found in winter."
	icon_sprite = "spr_ui_item_fish_large_bowfish"
	name = "Bowfish"
	value = { bin = 40 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[dace]
	description = "A common small river fish found on snowy days in winter."
	icon_sprite = "spr_ui_item_fish_small_dace"
	name = "Dace"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[herring]
	description = "A common small river fish found in winter."
	icon_sprite = "spr_ui_item_fish_small_herring"
	name = "Herring"
	value = { bin = 45 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]

[shadow_bass]
	description = "A rare medium river fish found in winter."
	icon_sprite = "spr_ui_item_fish_medium_shadow_bass"
	name = "Shadow Bass"
	value = { bin = 140 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable", "fishy"]
