[blue_crab]
	name = "Blue Crab"
	description = "A common small Fish Trap crustacean. Has a striking blue color."
	icon_sprite = "spr_ui_item_fish_small_blue_crab"
	value = { bin = 60 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[sea_urchin]
	name = "Sea Urchin"
	description = "An uncommon small Fish Trap echinoderm. It's spiky, so handle with caution!"
	icon_sprite = "spr_ui_item_fish_small_sea_urchin"
	value = { bin = 80 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[bait_thief]
	name = "Bait Thief"
	description = "A common medium Fish Trap fish. These rarely caught fish are famous for expertly stealing bait."
	icon_sprite = "spr_ui_item_fish_medium_bait_thief"
	value = { bin = 100 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[hake]
	name = "Hake"
	description = "An uncommon medium Fish Trap fish. They tend to wander into shallow waters at night."
	icon_sprite = "spr_ui_item_fish_medium_hake"
	value = { bin = 120 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]

[amberjack]
	name = "Amberjack"
	description = "A rare large Fish Trap find. What a catch!"
	icon_sprite = "spr_ui_item_fish_large_amberjack"
	value = { bin = 200 }
	edible = false
	restore = "small_common_fish_restore"
	tags = ["fishable"]
