[wedding_0]
kind = "gameplay_triggered"
writes = [{ family_planning_gate = true, expires = "14d" }, { post_wedding_bump = true, expires = "2d" }]
speaker = "elsie"
portrait = "happy"
local = "Good morning, [Ari]!"
next = "1"

[wedding_0.1]
speaker = "elsie"
portrait = "embarrassed"
local = "The big day is finally here... You must be so excited!"
next = "2"

[wedding_0.2]
speaker = "josephine"
portrait = "happy"
local = "Now don't you worry about any chores today. We've got it handled."
next = "3"

[wedding_0.3]
speaker = "josephine"
portrait = "neutral"
local = "Everyone's pitching in to make sure your $animals are fed$ and your $crops are watered$!"
next = "4"

[wedding_0.4]
speaker = "elsie"
portrait = "wink"
local = "Your only worry for today is to enjoy yourself to the fullest!"
next = "5"

[wedding_0.5]
speaker = "josephine"
portrait = "happy"
local = "We've set up a room at the Inn with everything you'll need to get ready for your ceremony."
next = "6"

[wedding_0.6]
speaker = "josephine"
portrait = "wink"
local = "[fiance] will be using my room to prepare, so no peeking!"
next = [
    { target = "7_female", requires = [
        { any = [
            { adeline_is_fiance = true },
            { celine_is_fiance = true },
            { juniper_is_fiance = true },
            { reina_is_fiance = true },
            { seridia_is_fiance = true },
            { valen_is_fiance = true }
        ] }
    ] },
    { target = "7_male", requres = [] },
]

[wedding_0.7_female]
speaker = "josephine"
portrait = "happy"
local = "You'll have to wait til the ceremony to see her... hehe!"
next = "8"

[wedding_0.7_male]
speaker = "josephine"
portrait = "happy"
local = "You'll have to wait til the ceremony to see him... hehe!"
next = "8"

[wedding_0.8]
speaker = "elsie"
portrait = "happy"
local = "Well, shall we be on our way? Your big day awaits!"
next = "9"

[wedding_0.9]
speaker = "elsie"
portrait = "neutral"
local = "What do you think? Didn't Josephine do a nice job making up the east guestroom?"
next = "10"

[wedding_0.10]
speaker = "josephine"
portrait = "embarrassed"
local = "It was nothing, really. I'm just happy it could be of some use!"
next = "11"

[wedding_0.11]
speaker = "josephine"
portrait = "happy"
local = "And besides, it was Elsie who coordinated today's wardrobe options! With Louis, of course."
next = "12"

[wedding_0.12]
speaker = "elsie"
portrait = "wink"
local = "I just thought you might like having your pick of the latest wedding fashions from the Capital."
next = "13"

[wedding_0.13]
speaker = "elsie"
portrait = "neutral"
local = "Of course, you're welcome to style yourself however pleases you. Today's your big day, after all!"
next = "14"

[wedding_0.14]
speaker = "josephine"
portrait = "neutral"
local = "Well, we'll let you get to it."
next = "15"

[wedding_0.15]
speaker = "josephine"
portrait = "happy"
local = "If you need any help, we'll be right outside. Just give us a shout!"
next = "16"

[wedding_0.16]
speaker = "elsie"
portrait = "happy"
local = "Are you all ready, [Ari]?"
next = "17"

[wedding_0.17]
speaker = "josephine"
portrait = "embarrassed"
local = "Oh! Look, Elsie. <he>Doesn't he</he><she>Doesn't she</she><they>Don't they</they><it>Doesn't it</it><none>Doesn't [Ari]</none> look brilliant?"
next = "18"

[wedding_0.18]
speaker = "elsie"
portrait = "embarrassed"
local = "<he>He certainly does</he><she>She certainly does</she><they>They certainly do</they><it>It certainly does</it><none>[Ari] certainly does</none>! <he>He's</he><she>She's</she><they>They're</they><it>It's</it><none>[Ari]'s</none> positively sparkling!"
next = "19"

[wedding_0.19]
speaker = "elsie"
portrait = "neutral"
local = "It's just about time to start the ceremony, [Ari]."
next = [
    { target = "20_female", requires = [
        { any = [
            { adeline_is_fiance = true },
            { celine_is_fiance = true },
            { juniper_is_fiance = true },
            { reina_is_fiance = true },
            { seridia_is_fiance = true },
            { valen_is_fiance = true }
        ] }
    ] },
    { target = "20_male", requres = [] },
]

[wedding_0.20_female]
speaker = "elsie"
portrait = "happy"
local = "[fiance] says she's ready, too."
next = "21"

[wedding_0.20_male]
speaker = "elsie"
portrait = "happy"
local = "[fiance] says he's ready, too."
next = "21"

[wedding_0.21]
speaker = "josephine"
portrait = "happy"
local = "What is it? Do you need another moment?"
prompts = [
    { local = "I'm just a little nervous!", next = "22" },
    { local = "I'm just so excited!", next = "25" }
]

[wedding_0.22]
speaker = "josephine"
portrait = "happy"
local = "That's completely normal!"
next = "23"

[wedding_0.23]
speaker = "josephine"
portrait = "neutral"
local = "I had a terrible case of nerves on my wedding day, you know."
next = "24"

[wedding_0.24]
speaker = "josephine"
portrait = "embarrassed"
local = "But the moment I saw Hemlock at the altar... all that just melted away."
next = "28"

[wedding_0.25]
speaker = "josephine"
portrait = "happy"
local = "As you should be!"
next = "26"

[wedding_0.26]
speaker = "josephine"
portrait = "neutral"
local = "I was full of butterflies on my wedding day too, you know."
next = "27"

[wedding_0.27]
speaker = "josephine"
portrait = "embarrassed"
local = "The minute I saw Hemlock at the altar... my heart just about overflowed."
next = "28"

[wedding_0.28]
speaker = "josephine"
portrait = "happy"
local = "I'm sure that you'll feel the same as soon as you see [fiance]."
next = "29"

[wedding_0.29]
speaker = "josephine"
portrait = "neutral"
local = "And... as someone who's watched you change and grow over these many seasons... I just know you'll be so happy."
next = [
    { target = "30_female", requires = [
        { any = [
            { adeline_is_fiance = true },
            { celine_is_fiance = true },
            { juniper_is_fiance = true },
            { reina_is_fiance = true },
            { seridia_is_fiance = true },
            { valen_is_fiance = true }
        ] }
    ] },
    { target = "30_male", requres = [] },
]

[wedding_0.30_female]
speaker = "josephine"
portrait = "happy"
local = "Come, we'd better not keep her waiting."

[wedding_0.30_male]
speaker = "josephine"
portrait = "happy"
local = "Come, we'd better not keep him waiting."
