[cutscene_basement]
kind = "gameplay_triggered"
speaker = "caldarus"
portrait = "embarrassed"
local = "Hey man, this is like...super awkward. But that cutscene doesn't exist."
next = "1"

[cutscene_basement.1]
speaker = "caldarus"
portrait = "happy"
local = "Hope your day is groovy though! By the way, I'd just escape out of this cutscene right now, who knows what'll happen."
