multiply_by_light_count = 0
min_multiply_level = 0

# what we start at
init.shading.vivid = [80, 70, 255, 25]
init.shading.multiply = [21, 0, 87, 87]
init.shading.levels = { black = 0, grey = 232, white = 240 }

init.light = [1.0, 0.9, 0.6, 0.14]
init.shadow = [21, 0, 87, 87]
