multiply_by_light_count = 3
min_multiply_level = 0

# what we start at
init.shading.vivid = [20, 0, 88, 25]
init.shading.multiply = [0, 0, 0, 255]
init.shading.levels = { black = 0, grey = 232, white = 240 }

init.light = [0.45, 0.405, 0.36, 0.315]
init.shadow = [21, 0, 87, 87]
