multiply_by_light_count = 0
min_multiply_level = 0

# NOTE: this is mostly as a copy-paste reservoir!
init.shading.vivid = [0, 0, 0, 0]
init.shading.multiply = [0, 0, 0, 30]
init.shading.levels = { black = 0, grey = 255, white = 255 }

init.light = [1.0, 1.0, 1.0, 1.0]
init.shadow = [180, 170, 190, 230]
