multiply_by_light_count = 0
min_multiply_level = 0

# what we start at
init.shading.vivid = [116, 56, 194, 91]
init.shading.multiply = [206, 61, 255, 92]
init.shading.levels = { black = 20, grey = 265, white = 245 }

init.light = [1.0, 1.0, 1.0, 1.0]
init.shadow = [190, 180, 240, 230]
