order = [
	"crown_request_crops",
	"crown_request_tables_and_chairs",
	"crown_request_mine_forageables",
	"crown_request_fish",
	"crown_request_berries",
	"crown_request_ingots",
	"crown_request_animal_materials",
	"crown_request_soup",
	"crown_request_stone",
	"crown_request_archaeology_shards",
	"crown_request_copper_tools",
	"crown_request_golden_ingredients",
	"crown_request_baked_dishes",
	"crown_request_stone_paths",
	"crown_request_flowers",
	"crown_request_monster_materials",
	"crown_request_grass_starter",
	"crown_request_refined_stone",
	"crown_request_bell_berries",
	"crown_request_gold_ingots",
]

days_between = 7

[tag_registrations]
	dining_table = { text = "Dining Tables", item_for_icon = "basic_table_oak"}
	dining_chair = { text = "Dining Chairs", item_for_icon = "basic_chair_oak"}
	crop = { text = "Crops", item_for_icon = "turnip" }
	mines_forageable = { text = "Mines Forageables", item_for_icon = "shadow_flower" }
	fishy = { text = "Fish", item_for_icon = "trout" }
	berry = { text = "Berries", item_for_icon = "wild_berries" }
	feather = { text = "Feathers", item_for_icon = "feather" }
	wool = { text = "Wool", item_for_icon = "sheep_wool" }
	soup = { text = "Soup", item_for_icon = "vegetable_soup" }
	copper_tool = { text = "Copper Tools", item_for_icon = "pick_axe_copper"}
	golden_mayonnaise = { text = "Golden Mayonnaise", item_for_icon = "golden_mayonnaise" }
	stone_path = { text = "Stone Paths", item_for_icon = "starter_stone_path_double" }
	flower = { text = "Flowers", item_for_icon = "celosia" }
	monster_part = { text = "Monster Parts", item_for_icon = "monster_fang" }
	baked_dish = { text = "Baked Main Dishes", item_for_icon = "baked_potato" }
	bugs = { text = "Bugs", item_for_icon = "ladybug" }

