[green_sapling_surprise]
	name = "Green Sapling Surprise"
	description = """A terrible fate awaits the people of this town...

Unless someone can defeat 20 Sapling Monsters!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "sapling_beanbag_chair_green" }]

	[[green_sapling_surprise.stages]]
		objective_description = "Defeat 20 Green Sapling Monsters."
		requirements.defeated_monster.sap = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "green_sapling_surprise_turn_in" },
		]

[rock_clod_catastrophe]
	name = "Rock Clod Catastrophe"
	description = """An unimaginably grim future can only be averted with the destruction of 20 Rock Clods."""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "rock_clod_garden_brown" }]

	[[rock_clod_catastrophe.stages]]
		objective_description = "Defeat 20 Rock Clod Monsters."
		requirements.defeated_monster.clod = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "rock_clod_catastrophe_turn_in" },
		]

[mushroom_madness]
	name = "Mushroom Madness"
	description = """Foul Mushrooms threaten to reduce the Kingdom to ruins.

Travel to the Tide Caverns and defeat 20 Green Mushrooms!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "mushroom_sofa_green" }]

	[[mushroom_madness.stages]]
		objective_description = "Defeat 20 Green Mushroom Monsters."
		requirements.defeated_monster.shroom = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "mushroom_madness_turn_in" },
		]

[enchantern_explosion]
	name = "Enchantern Explosion"
	description = """Venture into the Tide Caverns and slay 20 Blue Enchanterns before they bring Havoc to Aldaria!"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "enchantern_lamp_blue" }]

	[[enchantern_explosion.stages]]
		objective_description = "Defeat 20 Blue Enchantern Monsters."
		requirements.defeated_monster.enchantern = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "enchantern_explosion_turn_in" },
		]

[staggering_stalagmites]
	name = "Staggering Stalagmites"
	description = """In the Deep Earth biome, Green Stalagmites threaten to undermine all we hold dear.

Turn 10 Green Stalagmite monsters to gravel!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "stalagmite_tile_green" }]

	[[staggering_stalagmites.stages]]
		objective_description = "Defeat 10 Green Stalagmite Monsters."
		requirements.defeated_monster.mite = 10
		queries = [
			{ npc = "stillwell", npc_conversation = "staggering_stalagmites_turn_in" },
		]

[essence_gone_batty]
	name = "Essence Gone Batty"
	description = """Head to the Deep Earth biome and set your sights on Blue Essence Bats.

Only when 20 have been slain will Mistria be safe!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "essence_bat_garland_blue" }]

	[[essence_gone_batty.stages]]
		objective_description = "Defeat 20 Blue Essence Bats Monsters."
		requirements.defeated_monster.bat = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "essence_gone_batty_turn_in" },
		]

[malicious_mimics]
	name = "Malicious Mimics"
	description = """Aldaria's good fortunes will change for the worse, unless 5 Mimics are defeated in the Mines."""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "mimic_storage_chest" }]

	[[malicious_mimics.stages]]
		objective_description = "Defeat 5 Mimic Monsters."
		requirements.defeated_monster.mimic = 5
		queries = [
			{ npc = "stillwell", npc_conversation = "malicious_mimics_turn_in" },
		]

[flame_spirit_shocker]
	name = "Flame Spirit Shocker"
	description = """Take care not to be burned while you hunt down 20 Flame Spirits in the Lava Caves."""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "flame_spirit_lamp_orange" }]

	[[flame_spirit_shocker.stages]]
		objective_description = "Defeat 20 Flame Spirit Monsters."
		requirements.defeated_monster.spirit = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "flame_spirit_shocker_turn_in" },
		]

[lava_cat_conundrum]
	name = "Lava Cat Conundrum"
	description = """Lava Cats. Cute, but deadly. Fall not for their feline charms, but instead head to the Lava Caves and defeat 20 of them!"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "lava_cat_bed_orange" }]

	[[lava_cat_conundrum.stages]]
		objective_description = "Defeat 20 Lava Cat Monsters."
		requirements.defeated_monster.cat = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "lava_cat_conundrum_turn_in" },
		]

[flying_tome_trouble]
	name = "Flying Tome Trouble"
	description = """In the Ruins, the Flying Tomes tempt adventurers with their forbidden knowledge.

Turn 20 of them into confetti!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "floating_tome_lamp" }]

	[[flying_tome_trouble.stages]]
		objective_description = "Defeat 20 Flying Tome Monsters."
		requirements.defeated_monster.tome = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "flying_tome_trouble_turn_in" },
		]

[rock_stack_smackdown]
	name = "Rock Stack Smackdown"
	description = """Rock Stacks. An uncanny alliance between monsters, that can only lead to the mortal world being crushed beneath them.

Journey down to the Ruins and break apart 20 Rock Stacks!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "rock_stack_shelf" }]

	[[rock_stack_smackdown.stages]]
		objective_description = "Defeat 20 Rock Stack Monsters."
		requirements.defeated_monster.rock_stack = 20
		queries = [
			{ npc = "stillwell", npc_conversation = "rock_stack_smackdown_turn_in" },
		]

[gryphon_grapple]
	name = "Gryphon Grapple"
	description = """A conspiracy of Gryphon Statues threatens all we hold dear, unless they are annihilated.

Defeat 10 Gryphon Statues in the Ruins!
"""
	npc_for_icon = "stillwell"
	rewards = [{ renown = 100 }, { crafting_scroll = "void_gryphon_statue_purple" }]

	[[gryphon_grapple.stages]]
		objective_description = "Defeat 10 Gryphon Statue Monsters."
		requirements.defeated_monster.statue = 10
		queries = [
			{ npc = "stillwell", npc_conversation = "gryphon_grapple_turn_in" },
		]
