order = [
	"green_sapling_surprise",
	"rock_clod_catastrophe",
	"mushroom_madness",
	"enchantern_explosion",
	"staggering_stalagmites",
	"essence_gone_batty",
	"malicious_mimics",
	"flame_spirit_shocker",
	"lava_cat_conundrum",
	"flying_tome_trouble",
	"rock_stack_smackdown",
	"gryphon_grapple",
]
