order = [
	"rice_ball_challenge",
	"crystal_berry_pie_challenge",
	"crispy_fried_earthshroom_challenge",
	"chocolate_cake_challenge",
	"tide_salad_challenge",
	"omelet_challenge",
	"bell_berry_bakewell_tart_challenge",
	"herb_salad_challenge",
	"incredibly_hot_pot_challenge",
	"golden_cookies_challenge",
	"veggie_sub_sandwich_challenge",
	"beet_soup_challenge",
]
