[rice_ball_challenge]
	name = "Rice Ball Challenge"
	description = """Our first cooking challenge is...

The simple yet satisfying "Rice Ball"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "cooking_stockpot_v1" }, { crafting_scroll = "cooking_stockpot_v1" }]

	[[rice_ball_challenge.stages]]
		objective_description = "Turn in a Rice Ball to Taliferro."
		requirements = { has_item = "riceball" }
		queries = [
			{ npc = "taliferro", npc_conversation = "rice_ball_challenge_turn_in" },
		]

[crispy_fried_earthshroom_challenge]
	name = "Fried Earthshroom Challenge"
	description = """This week's cooking challenge dish is...

The umami "Crispy Fried Earthshroom"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "cooking_frying_pan_v1" }, { crafting_scroll = "cooking_frying_pan_v1" }]

	[[crispy_fried_earthshroom_challenge.stages]]
		objective_description = "Turn in a Crispy Fried Earthshroom to Taliferro."
		requirements = { has_item = "crispy_fried_earthshroom" }
		queries = [
			{ npc = "taliferro", npc_conversation = "crispy_fried_earthshroom_challenge_turn_in" },
		]

[crystal_berry_pie_challenge]
	name = "Crystal Berry Pie Challenge"
	description = """This week's cooking challenge dish is...

The beautiful "Crystal Berry Pie"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "cooking_hanging_pans_v1" }, { crafting_scroll = "cooking_hanging_pans_v1" }]

	[[crystal_berry_pie_challenge.stages]]
		objective_description = "Turn in a Crystal Berry Pie to Taliferro."
		requirements = { has_item = "crystal_berry_pie" }
		queries = [
			{ npc = "taliferro", npc_conversation = "crystal_berry_pie_challenge_turn_in" },
		]

[chocolate_cake_challenge]
	name = "Chocolate Cake Challenge"
	description = """Today's cooking challenge dish is...

The rich and decadent "Chocolate Cake"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_garlic_braid" }, { crafting_scroll = "kitchen_garlic_braid" }]

	[[chocolate_cake_challenge.stages]]
		objective_description = "Turn in a Chocolate Cake to Taliferro."
		requirements = { has_item = "caldosian_chocolate_cake" }
		queries = [
			{ npc = "taliferro", npc_conversation = "chocolate_cake_challenge_turn_in" },
		]

[tide_salad_challenge]
	name = "Tide Salad Challenge"
	description = """Today's cooking challenge dish is...

The crisp and healthy "Tide Salad"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_hanging_onion_basket" }, { crafting_scroll = "kitchen_hanging_onion_basket" }]

	[[tide_salad_challenge.stages]]
		objective_description = "Turn in a Tide Salad to Taliferro."
		requirements = { has_item = "tide_salad" }
		queries = [
			{ npc = "taliferro", npc_conversation = "tide_salad_challenge_turn_in" },
		]

[omelet_challenge]
	name = "Omelet Challenge"
	description = """Today's cooking challenge dish is...

The fluffy and cheese-filled "Omelet"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "cooking_tea_kettle_v1" }, { crafting_scroll = "cooking_tea_kettle_v1" }]

	[[omelet_challenge.stages]]
		objective_description = "Turn in an Omelet to Taliferro."
		requirements = { has_item = "omelet" }
		queries = [
			{ npc = "taliferro", npc_conversation = "omelet_challenge_turn_in" },
		]

[bell_berry_bakewell_tart_challenge]
	name = "Bell Berry Bakewell Tart Challenge"
	description = """This week's cooking challenge dish is...

The new and trending "Bell Berry Bakewell Tart"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_herb_planter_v1" }, { crafting_scroll = "kitchen_herb_planter_v1" }]

	[[bell_berry_bakewell_tart_challenge.stages]]
		objective_description = "Turn in a Bell Berry Bakewell Tart to Taliferro."
		requirements = { has_item = "bell_berry_bakewell_tart" }
		queries = [
			{ npc = "taliferro", npc_conversation = "bell_berry_bakewell_tart_challenge_turn_in" },
		]

[herb_salad_challenge]
	name = "Herb Salad Challenge"
	description = """Today's cooking challenge dish is...

The delicate and refreshing "Herb Salad"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_oil_and_vinegar_basket_v1" }, { crafting_scroll = "kitchen_oil_and_vinegar_basket_v1" }]

	[[herb_salad_challenge.stages]]
		objective_description = "Turn in an Herb Salad to Taliferro."
		requirements = { has_item = "herb_salad" }
		queries = [
			{ npc = "taliferro", npc_conversation = "herb_salad_challenge_turn_in" },
		]

[incredibly_hot_pot_challenge]
	name = "Incredibly Hot Pot Challenge"
	description = """Today's cooking challenge dish is...

The unbelievably spicy "Incredibly Hot Pot"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_scale_blue" }, { crafting_scroll = "kitchen_scale_blue" }]

	[[incredibly_hot_pot_challenge.stages]]
		objective_description = "Turn in an Incredibly Hot Pot to Taliferro."
		requirements = { has_item = "incredibly_hot_pot" }
		queries = [
			{ npc = "taliferro", npc_conversation = "incredibly_hot_pot_challenge_turn_in" },
		]

[golden_cookies_challenge]
	name = "Golden Cookies Challenge"
	description = """This week's cooking challenge dish is...

The incredibly delicious "Golden Cookies"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_mixing_bowls_v1" }, { crafting_scroll = "kitchen_mixing_bowls_v1" }]

	[[golden_cookies_challenge.stages]]
		objective_description = "Turn in Golden Cookies to Taliferro."
		requirements = { has_item = "golden_cookies" }
		queries = [
			{ npc = "taliferro", npc_conversation = "golden_cookies_challenge_turn_in" },
		]

[veggie_sub_sandwich_challenge]
	name = "Veggie Sub Sandwich Challenge"
	description = """This week's cooking challenge dish is...

The beloved "Veggie Sub Sandwich"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "kitchen_utensil_holder_blue" }, { crafting_scroll = "kitchen_utensil_holder_blue" }]

	[[veggie_sub_sandwich_challenge.stages]]
		objective_description = "Turn in a Veggie Sub Sandwich to Taliferro."
		requirements = { has_item = "veggie_sub_sandwich" }
		queries = [
			{ npc = "taliferro", npc_conversation = "veggie_sub_sandwich_challenge_turn_in" },
		]

[beet_soup_challenge]
	name = "Beet Soup Challenge"
	description = """Our final cooking challenge dish is...

The legendary "Beet Soup"!"""
	npc_for_icon = "taliferro"
	rewards = [{ renown = 100 }, { item = "champions_kitchen_blue" }, { crafting_scroll = "champions_kitchen_blue" }, { item = "counter_kitchen_blue" }, { crafting_scroll = "counter_kitchen_blue" }]

	[[beet_soup_challenge.stages]]
		objective_description = "Turn in a Beet Soup to Taliferro."
		requirements = { has_item = "beet_soup" }
		queries = [
			{ npc = "taliferro", npc_conversation = "beet_soup_challenge_turn_in" },
		]
