[ari_birth]
	kind = "gameplay_triggered"
	speaker = "juniper"
	local = "[Ari], what is it? The baby is coming!? Let's get you to the Clinic!"

[spouse_birth]
	kind = "gameplay_triggered"
	speaker = "juniper"
	local = "[Ari], wake up, the baby is coming! Can you help me to the Clinic?"

[stork_birth]
	kind = "gameplay_triggered"
	speaker = "juniper"
	local = "[Ari], do you hear that?"
