[crafting_tutorial_turn_in]
kind = "gameplay_triggered"
actions = [{ cutscene = "crafting_tutorial" }]
speaker = "ryis"
portrait = "neutral"
local = "Looks like you're ready for your crafting lesson. Come on, I just need to get a few things together first."

[crafting_tutorial]
kind = "gameplay_triggered"
speaker = "ryis"
portrait = "neutral"
local = "So this is where you'll be crafting today. Feel free to use it any time. There's also a crafting station in town, and you can even buy one from us to place on your farm!"
next = "1"

[crafting_tutorial.1]
speaker = "landen"
portrait = "happy"
local = "Any time you want tips you only have to ask!"
next = "2"

[crafting_tutorial.2]
speaker = "ryis"
portrait = "neutral"
local = "I think you'll find being able to make your own fences handy. You can use them to section off your land to keep your farm organized."
next = "3"

[crafting_tutorial.3]
speaker = "landen"
portrait = "neutral"
local = "They'll keep your chickens out of your corn and the weeds from overtaking your fields!"
next = "4"

[crafting_tutorial.4]
speaker = "ryis"
portrait = "happy"
local = "They're great practice too. You'll be on to bigger projects in no time."
next = "5"

[crafting_tutorial.5]
speaker = "ryis"
portrait = "neutral"
local = "Ready to get technical about how to craft them?"
prompts = [{ local = "Let's start my fencing lesson!", next = "8" }, { local = "I think I'm good!", next = "7" }]

# NOTE -- a fake line was snipped here. not adjusting the numbers as to not mess with localization

[crafting_tutorial.7]
speaker = "landen"
portrait = "wink"
local = "I like that confidence! You remind me of, well, me!"
next = "8"

[crafting_tutorial.8]
speaker = "ryis"
portrait = "happy"
local = "Nicely done!"
next = "9"

[crafting_tutorial.9]
speaker = "landen"
portrait = "happy"
local = "I'll say!"
next = "10"

[crafting_tutorial.10]
speaker = "ryis"
portrait = "neutral"
local = "Let's have you make a few more sections of fence while you're here to make sure you've got the hang of it."
