[day_zero]
kind = "gameplay_triggered"
speaker = "balor"
portrait = "neutral"
local = "Oh? Hello there."
next = "1"

[day_zero.1]
speaker = "balor"
portrait = "think"
local = "Didn't expect to see anyone else out this way. The roads have been a real mess since the $earthquake$."
next = "2"

[day_zero.2]
speaker = "balor"
portrait = "neutral"
local = "I'm Balor, a traveling merchant. Pleased to meet you."
next = "3"

[day_zero.3]
speaker = "balor"
portrait = "sincere_special"
local = "Let me guess, you're here at Lady Adeline's request? She mentioned someone had taken her up on her offer."
prompts = [
	{ local = """She said she was looking for a "capable adventurer"!""", next = "4" },
	{ local = "There was something about free land and a house...", next = "5" },
]

[day_zero.4]
speaker = "balor"
portrait = "neutral"
local = "Well, Mistria could certainly use the help to get back on its feet."
next = "6"

[day_zero.5]
speaker = "balor"
portrait = "neutral"
local = "I've seen the area! It's a nice spot, quite close to town."
next = "6"

[day_zero.6]
speaker = "balor"
portrait = "think"
local = "I'll walk with you the rest of the way, if you don't mind the company. No wagons can get through since the bridge collapsed, so I've had to carry what I can on foot."
next = "7"

[day_zero.7]
speaker = "balor"
portrait = "happy"
local = "Great, let's go!"
next = "8"

[day_zero.8]
speaker = "balor"
portrait = "sincere_special"
local = "Whew!"
next = "9"

[day_zero.9]
speaker = "balor"
portrait = "neutral"
local = "We should be able to make it before it gets dark. Come on, we'll head straight to your new farmstead!"
next = "10"

[day_zero.10]
speaker = "balor"
portrait = "neutral"
local = "Lord Eiland! Look who I found out at the edge of the forest!"
next = "11"

[day_zero.11]
speaker = "eiland"
portrait = "happy"
local = "[Ari], I presume! Welcome, welcome! I'm Eiland, it's wonderful to meet you!"
next = "12"

[day_zero.12]
speaker = "balor"
portrait = "neutral"
local = "You're in good hands, [Ari]. I'm off to the Inn, it's been a long day and I need a hot meal. See you around!"
next = "13"

[day_zero.13]
speaker = "eiland"
portrait = "neutral"
local = "So what do you think? Nice isn't it? You're right outside of town, great soil for farming..."
next = "14"

[day_zero.14]
speaker = "eiland"
portrait = "happy"
local = "And look at this house! Four stout walls with a rich history! Let's go inside, shall we?"
next = "15"

[day_zero.15]
speaker = "eiland"
portrait = "neutral"
effect = "shock"
local = "Ah-"
next = "16"

[day_zero.16]
speaker = "adeline"
portrait = "embarrassed"
effect = "sweat"
local = "J-just a minute!"
next = "17"

[day_zero.17]
speaker = "eiland"
portrait = "embarrassed"
effect = "drop"
local = "It, er, appears we're not quite ready for you."
next = "18"

[day_zero.18]
speaker = "eiland"
portrait = "think"
local = "But not to worry! I'm sure she'll only need a moment."
prompts = [
	{ local = "Should we go in and help...?", next = "19" },
	{ local = "I'm used to roughing it, honestly.", next = "19" },
]

[day_zero.19]
speaker = "adeline"
portrait = "angry_blush"
local = "No need!"
effect = "sweat"
next = "20"

[day_zero.20]
speaker = "eiland"
portrait = "ugh"
effect = "drop"
local = "Ahaha..."
next = "21"

[day_zero.21]
speaker = "adeline"
portrait = "neutral"
local = "You must be [Ari]! I'm Adeline, thank you so much for answering my request!"
next = "22"

[day_zero.22]
speaker = "adeline"
portrait = "happy"
effect = "cheery"
local = "My brother and I are so excited to have a real adventurer here to help the town."
next = "23"

[day_zero.23]
speaker = "adeline"
portrait = "wink"
local = "I hope you like your new farm! It has a lot of potential, don't you think?"
next = "24"

[day_zero.24]
speaker = "adeline"
portrait = "happy"
local = "Why don't you come inside?"
next = "25"

[day_zero.25]
speaker = "adeline"
portrait = "neutral"
local = "Welcome to your new home!"
prompts = [{ local = "How cozy!", next = "26" }, { local = "Wow, that was fast!", next = "27" }]

[day_zero.26]
speaker = "adeline"
portrait = "happy"
local = "I'm glad you think so!"
next = "28"

[day_zero.27]
speaker = "adeline"
portrait = "happy"
effect = "drop"
local = "Haha..."
next = "28"

[day_zero.28]
speaker = "eiland"
portrait = "happy"
local = "Would you like a quick tour of the room?"
prompts = [{ local = "Yes, please!", next = "29" }, { local = "I'm good!", next = "30" }]

[day_zero.29]
speaker = "eiland"
portrait = "wink"
local = "Wonderful!"
next = "31"

[day_zero.30]
speaker = "eiland"
portrait = "neutral"
local = "Of course!"
next = "38"

[day_zero.31]
speaker = "eiland"
portrait = "neutral"
local = "This here is your $Diary$! You can write in it when you want to $record your story$."
next = "32"

[day_zero.32]
speaker = "eiland"
portrait = "neutral"
local = "And this of course is your new $Bed$!"
next = "33"

[day_zero.33]
speaker = "eiland"
portrait = "happy"
effect = "drop"
local = "Make sure you get to sleep by $2 am$ each day to keep your $Stamina$ up."
next = "34"

[day_zero.34]
speaker = "eiland"
portrait = "neutral"
local = "We've also put this $Calendar$ up for you. You can use it to check when Mistria holds its $Festivals$ and to check when everyone in town's $Birthdays$ are!"
next = "35"

[day_zero.35]
speaker = "eiland"
portrait = "neutral"
local = "And this $Storage Chest$ here was made by Mistria's very own carpenter, Ryis!"
next = "36"

[day_zero.36]
speaker = "eiland"
portrait = "think"
local = "You can $store items$ here if your bag starts to get too full."
next = "37"

[day_zero.37] # when deleting this line, make sure line 31 hooks up to the right line
speaker = "eiland"
portrait = "happy"
local = "And that's about it for your tour!"
next = "38"

[day_zero.38]
speaker = "adeline"
portrait = "neutral"
local = "I thought you might be hungry when you got here, so I stopped by the Inn and picked up a bowl of their famous $Vegetable Soup$!"
next = "39"

[day_zero.39]
speaker = "eiland"
portrait = "think"
local = "Well I'm sure you're worn out from your long day. We won't keep you up."
next = "40"

[day_zero.40]
speaker = "adeline"
portrait = "happy"
local = "Welcome to Mistria, [Ari]. We're so glad to have you!"
next = "41"

[day_zero.41]
speaker = "adeline"
portrait = "sly"
local = "Let's meet up tomorrow so we can start discussing our plans for the town restoration."
