[dying]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "sad"
local = "Ah, you're awake!"
next = "1"

[dying.1]
speaker = "valen"
portrait = "think"
local = "You gave us quite a scare."
next = "2"

[dying.2]
speaker = "valen"
portrait = "mad"
local = "Please take your health more seriously, [Ari]."
next = "3"

[dying.3]
speaker = "valen"
portrait = "think"
local = "You're lucky we found you by that dragon statue in the Mines."
next = "4"

[dying.4]
speaker = "valen"
portrait = "neutral"
local = "Well, I'm glad you seem to be doing better. Let's get you home to rest."

# ALTERNATE IF DATING VALEN
[dying_dating_valen]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "sad"
local = "[Ari], you're awake!"
next = "1"

[dying_dating_valen.1]
speaker = "valen"
portrait = "mad"
local = "Don't scare me like that!"
next = "2"

[dying_dating_valen.2]
speaker = "valen"
portrait = "sad"
local = "Please take your health more seriously..."
next = "3"

[dying_dating_valen.3]
speaker = "valen"
portrait = "think_blush"
local = "If not for your own sake, then for mine."
next = "4"

[dying_dating_valen.4]
speaker = "valen"
portrait = "caring_special"
local = "Well, I'm glad you seem to be feeling better. Let's get you home to rest."

# ALTERNATE IF MARRIED TO VALEN
[dying_married_valen]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "sad"
local = "[Ari], you're awake!"
next = "1"

[dying_married_valen.1]
speaker = "valen"
portrait = "mad"
local = "Don't scare your wife like that!"
next = "2"

[dying_married_valen.2]
speaker = "valen"
portrait = "sad"
local = "Please take your health more seriously..."
next = "3"

[dying_married_valen.3]
speaker = "valen"
portrait = "think_blush"
local = "If not for your own sake, then for mine."
next = "4"

[dying_married_valen.4]
speaker = "valen"
portrait = "caring_special"
local = "Well, I'm glad you seem to be feeling better. Let's get you back home to rest."
