[elsie_dating_tutorial]
kind = "gameplay_triggered"
speaker = "elsie"
portrait = "neutral"
local = "[Ari]! Good morning!"
next = "1"

[elsie_dating_tutorial.1]
speaker = "elsie"
portrait = "happy"
effect = "cheery"
local = "A little bird told me that you and [ELSIE_ROMANTIC_NPC] have confessed your feelings for each other... and have started $Dating$!"
next = "2"

[elsie_dating_tutorial.2]
speaker = "elsie"
portrait = "embarrassed"
local = "How wonderful. I'm so happy for you both!"
next = "3"

[elsie_dating_tutorial.3]
speaker = "elsie"
portrait = "neutral"
local = "I hope you don't mind my stopping by, but I thought that perhaps you could use some tips on $Dating$, to get you started."
next = "4"

[elsie_dating_tutorial.4]
speaker = "elsie"
portrait = "think"
local = "The first thing you need to keep in mind is that $timing is important$!"
next = "5"

[elsie_dating_tutorial.5]
speaker = "elsie"
portrait = "neutral"
local = "Everyone is busy with work during the week, so $weekends are the best time to invite someone out on a Date$."
next = "6"

[elsie_dating_tutorial.6]
speaker = "elsie"
portrait = "neutral"
local = "Both $Saturday$ and $Sunday$ are perfect days to do so."
next = "7"

[elsie_dating_tutorial.7]
speaker = "elsie"
portrait = "happy"
local = "Just keep in mind that you can only go on $one Date per week, per partner$."
next = "8"

[elsie_dating_tutorial.8]
speaker = "elsie"
portrait = "think"
local = "So theoretically... $if you were dating two people$, you could go on a $Date$ with one person on $Saturday$ and one on $Sunday$ in the same week."
next = "9"

[elsie_dating_tutorial.9]
speaker = "elsie"
portrait = "wink"
local = "I'm not here to judge, [Ari]. The only way to know if someone is right for you is to spend more time with them."
next = "10"

[elsie_dating_tutorial.10]
speaker = "elsie"
portrait = "embarrassed"
local = "But do keep in mind that when the time comes... $you can only marry one person$."
next = "11"

[elsie_dating_tutorial.11]
speaker = "elsie"
portrait = "wink"
local = "So make sure you choose well."
next = "12"

[elsie_dating_tutorial.12]
speaker = "elsie"
portrait = "think"
local = "Let's see now, what else..."
next = "13"

[elsie_dating_tutorial.13]
speaker = "elsie"
portrait = "neutral"
effect = "surprise"
local = "Oh, yes! There's the matter of $where to go on your Dates$!"
next = "14"

[elsie_dating_tutorial.14]
speaker = "elsie"
portrait = "happy"
local = "Sometimes you will encounter $Date Inspiration Items$ that will inspire new $Date Types$ when used!"
next = [
	{ target = "15", requires = [{ caldarus_home = true }] },
	{ target = "15_no_deep_woods" }
]

[elsie_dating_tutorial.15]
speaker = "elsie"
portrait = "neutral"
local = "Here, [Ari]. I have two $Date Inspiration$ items here. This should be enough to get you started."
next = "16"

[elsie_dating_tutorial.15_no_deep_woods]
speaker = "elsie"
portrait = "neutral"
local = "Here, [Ari]. I have a $Date Inspiration$ item here. This should be enough to get you started."
next = "16"

[elsie_dating_tutorial.16]
speaker = "elsie"
portrait = "happy"
local = "$The first time you go on a new Date with someone$, you will receive a $Photo Card$ commemorating the occasion."
next = "17"

[elsie_dating_tutorial.17]
speaker = "elsie"
portrait = "wink"
local = "You can collect these $Photo Cards$ and even $place them in your house to view them any time$. Isn't that fun?"
next = "18"

[elsie_dating_tutorial.18]
speaker = "elsie"
portrait = "neutral"
local = "With a little luck, I'm sure you will find all kinds of $Date Inspiration Items$, enjoy all sorts of $Dates$, and collect lots of cute $Photo Cards$!"
next = "19"

[elsie_dating_tutorial.19]
speaker = "elsie"
portrait = "wink"
local = "Good luck, [Ari]! I'll be cheering you on!"
next = "20"

[elsie_dating_tutorial.20]
no_speaker = true
local = "Would you like to view the $Dating Tutorial$?"
prompts = [{ local = "Yes" }, { local = "No" }]
