[farm_introduction]
kind = "gameplay_triggered"
speaker = "celine"
portrait = "neutral"
local = "Ah... hello! You must be [ARI]. I'm Celine, it's nice to meet you!"
next = "1"

[farm_introduction.1]
speaker = "celine"
portrait = "shy_blush"
local = "It looks like we're going to be neighbors! So I thought I'd bring you a little housewarming- um, fieldwarming present..."
next = "2"

[farm_introduction.2]
speaker = "celine"
portrait = "happy"
local = "Here is a $Hoe$, you'll need it to $till your fields$! I love gardening myself, so I had this extra one laying around."
next = "3"

[farm_introduction.3]
speaker = "celine"
portrait = "neutral"
local = "If you want to $expand your field's size$ though, you'll need a $Shovel$. They are available at my family's $General Store$."
next = "4"

[farm_introduction.4]
speaker = "celine"
portrait = "happy"
local = "And here are 3 bags of $Tulip Seeds$ to get you started! Our store also carries a selection of other $Seeds$ so be sure to stop by."
next = "5"

[farm_introduction.5]
speaker = "celine"
portrait = "shy_blush"
local = "I hope you'll consider growing lots of flowers!"
prompts = [
	{ local = "Thank you, I love flowers!", next = "6" },
	{ local = "I'm more into potatoes...", next = "7" },
]

[farm_introduction.6]
portrait = "blush_special"
local = "Oh, I'm so glad! You know, Mistria has a rich horticultural history-"
next = "8"

[farm_introduction.7]
speaker = "celine"
portrait = "blush_special"
local = "Oh, did you know that potato plants flower too? You'll actually be able to tell that they're ready to harvest when their flowers bloom-"
next = "8"

[farm_introduction.8]
speaker = "hayden"
portrait = "happy"
local = "Morning neighbor! The name's Hayden, I run $Sweetwater Farm$ to the west. You don't gotta tell me your name, [Ari], you're already the talk of the town!"
next = "9"

[farm_introduction.9]
speaker = "celine"
portrait = "ugh"
local = "Hayden! You almost galloped straight into poor [Ari]!"
next = "10"

[farm_introduction.10]
speaker = "hayden"
portrait = "wink_fist"
local = "Ah, don't mind my horse. He just likes meeting new folks as much as I do!"
next = "11"

[farm_introduction.11]
speaker = "hayden"
portrait = "laugh"
local = "GYA HA HA!"
prompts = [
	{ local = "It's fine. Pleasure's all mine!", next = "12" },
	{ local = "I think I need to lie down...", next = "13" },
]

[farm_introduction.12]
speaker = "hayden"
portrait = "neutral"
local = "A farmer after my own heart! Here, I brought you a little something!"
next = "14"

[farm_introduction.13]
speaker = "hayden"
portrait = "embarrassed"
effect = "sweat"
local = "Well now, my apologies. Here, let me make it up to you."
next = "14"

[farm_introduction.14]
speaker = "hayden"
portrait = "happy"
local = "Take this $Watering Can$! You'll need to $water your crops every day$ if you want them to grow big and strong."
next = "15"

[farm_introduction.15]
speaker = "hayden"
portrait = "neutral"
local = "And here are 3 bags of $Turnip Seeds$! Turnips are good raw, and they're even better cooked!"
next = "16"

[farm_introduction.16]
speaker = "celine"
portrait = "happy"
local = "The whole town will surely appreciate more shipments of fresh produce."
next = "17"

[farm_introduction.17]
speaker = "hayden"
portrait = "neutral"
local = "It's been a good while since I've been out here, things sure have gotten overgrown... You need any pointers on getting started with your field, [Ari]?"
prompts = [
	{ local = "I'd love some tips from you two!", next = "20" },
	{ local = "Thanks, but I already know my way around a farm...", next = "19" },
]

[farm_introduction.19]
speaker = "celine"
portrait = "shy_blush"
local = "Wow so you've done this before! That's great!"
next = "20"

[farm_introduction.20]
speaker = "hayden"
portrait = "neutral"
local = "Now don't be shy [Ari], come by anytime if you want to chat. I'd love to introduce you to all my animals!"
next = "21"

[farm_introduction.21]
speaker = "celine"
portrait = "neutral"
local = "I'm sure you must be eager to meet up with Adeline. Just head $north of here$ and the road will take you right into $town$!"
