[find_the_weathervane]
kind = "gameplay_triggered"
speaker = "hayden"
local = "Morning [Ari]! That was some windstorm that rolled through last night..."
next = "1"

[find_the_weathervane.1]
portrait = "happy"
local = "I just wanted to check in and see if everything was alright over here. Seems like there was no damage!"
next = "2"

[find_the_weathervane.2]
portrait = "sweat"
local = "Although... the $Weathervane$ blew clear off my new barn..."
next = "3"

[find_the_weathervane.3]
portrait = "ugh"
local = "Would you mind helping me find it? I'd like to get it back on before Ryis and Landen find out..."
next = "4"

[find_the_weathervane.4]
portrait = "think"
local = "The wind was blowing northwest... so I'm betting it ended up $somewhere in the Narrows$."
next = "5"

[find_the_weathervane.5]
portrait = "happy"
local = "Let me know if you manage to find it!"

[find_the_weathervane_turn_in]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "happy"
local = "Oh, you found my $Weathervane$! Thank you, [Ari]."
next = "1"

[find_the_weathervane_turn_in.1]
portrait = "think"
local = "Now I'll get this back on before anyone finds out..."
