[pet_arrival]
kind = "gameplay_triggered"
no_speaker = true
local = "How strange! It seems this [pet_type] has decided to live with you!"
next = "1"

[pet_arrival.1]
no_speaker = true
local = "Somehow, you already know their name is [pet_name]."