[pet_dream]
kind = "gameplay_triggered"
no_speaker = true
local = "You dream of a $familiar presence$..."
next = "1"

[pet_dream.1]
local = "You concentrate, and an image begins to form..."
next = "2"

[pet_dream.2]
local = "What a nice dream..."
