[prologue]
kind = "gameplay_triggered"
speaker = "eiland"
portrait = "neutral"
local = "Still working, sis?"
next = "1"

[prologue.1]
speaker = "adeline"
portrait = "neutral"
local = "Oh, Eiland!"
next = "2"

[prologue.2]
speaker = "adeline"
portrait = "happy"
effect = "drop"
local = "I didn't realize how late it had gotten."
next = "3"

[prologue.3]
speaker = "eiland"
portrait = "neutral"
local = "I thought you could use a nice hot cup of coffee."
next = "4"

[prologue.4]
speaker = "adeline"
portrait = "happy"
local = "Thank you!"
next = "5"

[prologue.5]
speaker = "eiland"
portrait = "think"
local = "So how is the town revitalization plan coming along?"
next = "6"

[prologue.6]
speaker = "adeline"
portrait = "neutral"
local = "It's nearly there, I think."
next = "7"

[prologue.7]
speaker = "adeline"
portrait = "think"
local = "I've cataloged the earthquake's damage, listed out the various repairs necessary..."
next = "8"

[prologue.8]
speaker = "adeline"
portrait = "neutral"
local = "And even made plans to replenish our emergency stockpile by the end of summer!"
next = "9"

[prologue.9]
speaker = "adeline"
portrait = "concerned"
local = "The only thing we're missing now is the help to see it through."
next = "10"

[prologue.10]
speaker = "eiland"
portrait = "think"
local = "With Mother and Father called away to the Capital, and people leaving after the earthquake, there certainly are fewer helping hands around."
next = "11"

[prologue.11]
speaker = "eiland"
portrait = "sad"
local = "If only we could attract new villagers to move here..."
next = "12"

[prologue.12]
speaker = "eiland"
portrait = "neutral"
local = "Mistria is such a beautiful place! The small town charm, the rich history of the area, the rolling farmland-"
next = "13"

[prologue.13]
speaker = "adeline"
portrait = "neutral"
effect = "surprise"
local = "That's it! The old farm south of town!"
next = "14"

[prologue.14]
speaker = "adeline"
portrait = "happy"
local = "Why don't we send a notice to the Adventurer's Guild in the Capital?"
next = "15"

[prologue.15]
speaker = "adeline"
portrait = "neutral"
local = "Surely someone out there will agree to aid the town in exchange for land with such potential."
next = "16"

[prologue.16]
speaker = "eiland"
portrait = "happy"
local = "That's a great idea!"
next = "17"

[prologue.17]
speaker = "adeline"
portrait = "happy"
local = "I'll get started on it. Thank you, Eiland."
next = "18"

[prologue.18]
speaker = "adeline"
portrait = "think"
local = "I wonder who will answer the call..."
