# stinky_stamina_potion_lilac
[stinky_stamina_potion_lilac_adeline]
refresh = "never"
requires = [
    { npc = "adeline" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_adeline.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_balor]
refresh = "never"
requires = [
    { npc = "balor" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_balor.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_celine]
refresh = "never"
requires = [
    { npc = "celine" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_celine.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_dell]
refresh = "never"
requires = [
    { npc = "dell" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_dell.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_eiland]
refresh = "never"
requires = [
    { npc = "eiland" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_eiland.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_elsie]
refresh = "never"
requires = [
    { npc = "elsie" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_elsie.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_errol]
refresh = "never"
requires = [
    { npc = "errol" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_errol.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_hemlock]
refresh = "never"
requires = [
    { npc = "hemlock" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_hemlock.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_holt]
refresh = "never"
requires = [
    { npc = "holt" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_holt.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_josephine]
refresh = "never"
requires = [
    { npc = "josephine" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_josephine.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_landen]
refresh = "never"
requires = [
    { npc = "landen" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_landen.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_luc]
refresh = "never"
requires = [
    { npc = "luc" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_luc.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_maple]
refresh = "never"
requires = [
    { npc = "maple" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_maple.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_nora]
refresh = "never"
requires = [
    { npc = "nora" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_nora.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_olric]
refresh = "never"
requires = [
    { npc = "olric" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_olric.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_reina]
refresh = "never"
requires = [
    { npc = "reina" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_reina.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_ryis]
refresh = "never"
requires = [
    { npc = "ryis" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_ryis.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_terithia]
refresh = "never"
requires = [
    { npc = "terithia" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_terithia.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

[stinky_stamina_potion_lilac_valen]
refresh = "never"
requires = [
    { npc = "valen" },
    { quest_stinky_stamina_potion_in_progress = true },
    { quest_stinky_stamina_potion_complete = false },
    { stinky_stamina_potion_lilac_ms_line = false },
    { location = "haydens_farm", comparator = "!=" },
    { location = "haydens_house", comparator = "!=" }
]
writes = [{ stinky_stamina_potion_lilac_ms_line = true }]
local = "You're looking for $Lilacs$? I've seen them growing near Hayden's farm, I think!"
next = "1"

[stinky_stamina_potion_lilac_valen.1]
local = "Hayden's farm is $to the west of your farm$, if you haven't been there yet."

# follow up

[stinky_stamina_potion_follow_up_1]
refresh = "never"
requires = [
	{ npc = "juniper" },
	{ quest_stinky_stamina_potion_complete = true },
	{ ssp = true },
]
portrait = "think"
local = "You're feeling fine after you drank my potion? No long-term effects?"
next = "1"

[stinky_stamina_potion_follow_up_1.1]
portrait = "think"
local = "Rhetorical questions, of course. Quite rhetorical. Mmhmm. Well, be on your way, you healthy adventurer you."

[stinky_stamina_potion_follow_up_2]
refresh = "never"
requires = [
	{ npc = "dell" },
	{ quest_stinky_stamina_potion_complete = true },
	{ ssp = true },
]
portrait = "think"
local = "I told Miss Juniper that her potion smelled so bad that she should call it reverse-perfume."
next = "1"

[stinky_stamina_potion_follow_up_2.1]
portrait = "happy"
local = "She kicked me out of the Bathhouse!"

[stinky_stamina_potion_follow_up_3]
refresh = "never"
requires = [
	{ npc = "maple" },
	{ quest_stinky_stamina_potion_complete = true },
	{ ssp = true },
]
local = "Miss Juniper's potion smelled pretty bad, huh?"
next = "1"

[stinky_stamina_potion_follow_up_3.1]
portrait = "happy"
local = "When I'm queen, I'm making her my royal poisoner."

[stinky_stamina_potion_follow_up_4]
refresh = "never"
requires = [
	{ npc = "luc" },
	{ quest_stinky_stamina_potion_complete = true },
	{ ssp = true },
]
portrait = "ugh"
local = "I don't think there's a smell in nature as bad as that potion of Miss Juniper's. And YOU drank it. Wow!"
next = "1"

[stinky_stamina_potion_follow_up_4.1]
portrait = "happy"
local = "Humanity is truly capable of anything."

[stinky_stamina_potion_turn_in]
kind = "gameplay_triggered"
speaker = "juniper"
portrait = "neutral"
local = "Well well! Adeline's little Request Board scheme actually works! I'm impressed. Now, follow me."
actions = [{ cutscene = "stinky_stamina_potion" }]

[stinky_stamina_potion]
kind = "gameplay_triggered"
writes = [{ ssp = true, expires = "4d" }]
speaker = "juniper"
portrait = "annoyed"
local = "What are you little gremlins doing here?"
next = "1"

[stinky_stamina_potion.1]
speaker = "luc"
portrait = "ugh"
local = "We're following that smell!"
next = "2"

[stinky_stamina_potion.2]
speaker = "maple"
portrait = "ugh"
local = "That super gross smell!"
next = "3"

[stinky_stamina_potion.3]
speaker = "dell"
portrait = "happy"
local = "If I knew baths could make you smell like this, I wouldn't try to avoid them! It's like... stink armor!"
next = "4"

[stinky_stamina_potion.4]
speaker = "juniper"
portrait = "neutral"
local = "What's in the cauldron isn't for the bath. It's for a... health tonic. With one sip, you'll be instantly refreshed!"
next = "5"

[stinky_stamina_potion.5]
speaker = "maple"
portrait = "ugh"
local = "No one is going to drink that if it tastes as bad as it smells."
next = "6"

[stinky_stamina_potion.6]
speaker = "juniper"
portrait = "wink"
local = "Ah, but I have yet to add the final ingredient. [Ari], if you would?"
next = "7"

[stinky_stamina_potion.7]
speaker = "juniper"
portrait = "neutral"
local = "There we are, that unfortunate smell has cleared right up. Don't you agree, [Ari]?"
prompts = [
	{ local = "Smells like old wet socks...", next = "8" },
	{ local = "Smells like fresh fertilizer...", next = "8" },
]

[stinky_stamina_potion.8]
speaker = "juniper"
portrait = "happy"
local = "An obvious improvement! Now who to test it on..."
next = "9"

[stinky_stamina_potion.9]
speaker = "dell"
portrait = "happy"
local = "Ooo, ooo! Me, me!"
next = "10"

[stinky_stamina_potion.10]
speaker = "juniper"
portrait = "wink"
local = "While I admire your enthusiasm Dell, I think we should reward the intrepid adventurer who retrieved the final ingredient."
next = "11"

[stinky_stamina_potion.11]
speaker = "dell"
portrait = "sad"
local = "Aww..."
next = "12"

[stinky_stamina_potion.12]
speaker = "luc"
portrait = "happy"
local = "Cool!"
next = "13"

[stinky_stamina_potion.13]
speaker = "juniper"
portrait = "think"
local = "Hmm! Very interesting. The lilac appears to have inverted the potion's intended effect."
next = "14"

[stinky_stamina_potion.14]
speaker = "maple"
portrait = "think"
local = "[Ari] doesn't look too good. We should go get Doctor Valen!"
next = "15"

[stinky_stamina_potion.15]
speaker = "juniper"
portrait = "annoyed"
local = "Ah, there's no need to get that woman involved. Here now [Ari]! Why don't you toddle off to the bath, it's on me."
next = "16"

[stinky_stamina_potion.16]
speaker = "juniper"
portrait = "happy"
local = "See kids? Right as rain. And to make sure there's no... lingering effects. $Your next five bathhouse visits are free$, [Ari]!"
next = "17"

[stinky_stamina_potion.17]
speaker = "dell"
portrait = "ugh"
local = "Who would ever want to take that many baths? Yuck."
next = "18"

[stinky_stamina_potion.18]
speaker = "juniper"
portrait = "neutral"
local = "Thank you again for your assistance, [Ari]. I'll be sure to call on you again in the future. Now why don't you all scoot out of here, I need to do a post experiment write-up."
next = "19"

[stinky_stamina_potion.19]
speaker = "luc"
portrait = "happy"
local = "Are you sure? We could help you come up with LOTS of ways to describe how bad it smells."
next = "20"

[stinky_stamina_potion.20]
speaker = "maple"
portrait = "think"
local = "Hot garbage!"
next = "21"

[stinky_stamina_potion.21]
speaker = "dell"
portrait = "happy"
local = "Dog burps!"
