[tea_with_hayden]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "happy"
local = "Thanks for stopping by! Come on in, put up your feet!"
next = "1"

[tea_with_hayden.1]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "So you're looking to raise some $animals$? I've got quite the selection to choose from, [Ari]!"
next = "2"

[tea_with_hayden.2]
speaker = "hayden"
portrait = "happy_arm_down"
local = "If you $feed$ them, $pet$ them, and $call them outside on nice days$, they'll reward you with all sorts of wonderful produce!"
next = "3"

[tea_with_hayden.3]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "Fresh $eggs$ and $milk$ are real useful if you like $cooking$. You can also sell them for a nice profit!"
next = "4"

[tea_with_hayden.4]
speaker = "hayden"
portrait = "think"
local = "Some animals even provide useful crafting materials, such as $feathers$ and $wool$."
next = "5"

[tea_with_hayden.5]
speaker = "hayden"
portrait = "neutral"
local = "Mistria also holds an annual $Animal Festival$ with great prizes..."
next = "6"

[tea_with_hayden.6]
speaker = "hayden"
portrait = "wink"
local = "Although you might find the competition a little stiff against my Henrietta!"
next = "7"

[tea_with_hayden.7]
speaker = "hayden"
portrait = "neutral"
local = "If you go on to $breed$ your animals with $Heart Shaped Treats$, you can even pair them to produce $rare colors$!"
next = "8"

[tea_with_hayden.8]
speaker = "hayden"
portrait = "wink"
local = "Here's some $milled feed$ to get you started, but don't forget you can also let them $graze$ or even $hand feed$ them as a treat."
next = "tutorial_prompt"

[tea_with_hayden.tutorial_prompt]
no_speaker = true
local = "Would you like to view the $Ranching Tutorial$?"
prompts = [{ local = "Yes", next = "9" }, { local = "No", next = "9" }]

[tea_with_hayden.9]
speaker = "hayden"
portrait = "happy"
local = "Well, I think that's about everything for now."
next = "10"

[tea_with_hayden.10]
speaker = "hayden"
portrait = "wink"
local = "Don't be a stranger, [Ari]! I can tell Henrietta appreciates your company, and so do I!"
