requires = [
	{ weather = "rainy" },
	{ caldarus_home = true },
	{ any = [{ rain_counter = 0 }, { rain_counter = 2 }] }
]

# Caldarus
[caldarus."6:00am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]

[caldarus."6:25am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ routine = "caldarus_house_reading" }]

[caldarus."9:45am"]
destination = "caldarus_house/dragon_cleaning_1"
on_arrival_actions = [{ routine = "statue_cleaning" }]

[caldarus."12:44pm"]
destination = "caldarus_house/south_east_routine"
on_arrival_actions = [{ routine = "tree_pruning" }]

[caldarus."5:12pm"]
destination = "caldarus_house/Caldarus Pouf Left"

[caldarus."7:23pm"]
destination = "caldarus_house/Caldarus Pouf Left"
on_arrival_actions = [{ routine = "tea_making" }]

[caldarus."9:53pm"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]
