requires = [
	{ weather = "snowy" },
	{ caldarus_home = true },
	{ season = "winter" }
]

# Caldarus
[caldarus."6:00am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]

[caldarus."6:33am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ routine = "scroll_rearranging" }]

[caldarus."10:43am"]
destination = "caldarus_house/Caldarus Desk Chair"
on_arrival_actions = [{ activity = "desk_reading" }]

[caldarus."1:17pm"]
destination = "caldarus_house/lute_1"
on_arrival_actions = [{ animation = "lute_play" }]

[caldarus."4:32pm"]
destination = "deep_woods/Caldarus Bench Left"

[caldarus."7:48pm"]
destination = "caldarus_house/routine_entrance"
on_arrival_actions = [{ routine = "tea_making" }]

[caldarus."10:43pm"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]
