priority = "max"
requires = [
	{ animal_festival_date = "1d", time = "after" },
	{ caldarus_home = true },
	{ caldarus_seridia_town = true },
]

# balor
[balor."6:00am"]
destination = "town/af_large_booth_2"

[balor."1:53pm"]
destination = "town/af_cow_cutout"

[balor."4:08pm"]
destination = "town/af_zoo_2"

[balor."8:53pm"]
destination = "inn/Top Bar Seat"
on_arrival_actions = [{ activity = "order_drink" }]

[balor."1:38am"]
destination = "balors_room/Balor Wake Point"

# caldarus
[caldarus."6:00am"]
destination = "town/af_north_chat_3"

[caldarus."11:24am"]
destination = "town/af_zoo_6"

[caldarus."3:52pm"]
destination = "town/af_souvenir_booth_dismissal"

[caldarus."6:32pm"]
destination = "town/af_cow_cutout"

[caldarus."8:41pm"]
destination = "inn/Bottom-Middle Bar Seat"
on_arrival_actions = [{ activity = "order_drink" }]

[caldarus."12:08am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]

# celine
[celine."6:00am"]
destination = "town/af_zoo_2"

[celine."6:52am"]
destination = "town/af_horse_cutout"

[celine."9:08am"]
destination = "town/af_zoo_2"

[celine."3:59pm"]
destination = "town/af_small_booth_2"

[celine."8:31pm"]
destination = "celines_room/ArmChair Seat"
on_arrival_actions = [{ activity = "drink" }]

# errol
[errol."6:00am"]
destination = "town/af_souvenir_booth_4"

[errol."9:34am"]
destination = "town/af_south_chat_1"

[errol."4:58pm"]
destination = "town/af_large_booth_1"

[errol."8:48pm"]
destination = "manor_house_dining_room/Table Right Seat 2"
on_arrival_actions = [{ activity = "drink" }]

[errol."1:22am"]
destination = "errols_bedroom/Desk Chair"

# josephine
[josephine."6:00am"]
destination = "town/af_podium"

[josephine."8:45pm"]
destination = "town/af_small_booth_dismissal"

[josephine."9:02pm"]
destination = "town/af_large_booth_dismissal"

[josephine."9:13pm"]
destination = "town/af_souvenir_booth_dismissal"

[josephine."9:53pm"]
destination = "inn/Bottom Bar Seat"
on_arrival_actions = [{ activity = "order_drink" }]

[josephine."12:15am"]
destination = "inn/Top-Middle Bar Seat"
on_arrival_actions = [{ activity = "drink" }]

[josephine."1:42am"]
destination = "jo_and_hemlocks_room/Jo Wake Point"

# seridia
[seridia."6:00am"]
destination = "town/af_chicken_cutout"

[seridia."8:15am"]
destination = "town/af_souvenir_booth_shelf"

[seridia."10:55am"]
destination = "town/af_large_booth_3"

[seridia."2:17pm"]
destination = "town/af_western_observation"

[seridia."6:58pm"]
destination = "western_ruins/seridia_sea_watch"

[seridia."1:18am"]
destination = "seridias_house_back/Seridia Throne"
on_arrival_actions = [{ activity = "drink" }]

# valen
[valen."6:00am"]
destination = "town/af_large_booth_3"

[valen."10:03am"]
destination = "town/af_south_chat_3"

[valen."4:17pm"]
destination = "town/af_horse_cutout"

[valen."6:35pm"]
destination = "clinic_f1/Research"

[valen."12:55am"]
destination = "clinic_f2/Valen Wake Point"
