priority = "max"
requires = [
	{ harvest_festival_date = "1d", time = "after" },
	{ caldarus_home = true },
	{ caldarus_seridia_town = true },
]

[caldarus."6:00am"]
destination = "town/hf_shopping_3"

[caldarus."12:28pm"]
destination = "town/hf_bar_0"

[caldarus."4:29pm"]
destination = "town/hf_table_south_3"

[caldarus."8:21pm"]
destination = "haydens_house/Haybale Seat 1"
on_arrival_actions = [{ activity = "drink" }]

[caldarus."1:21am"]
destination = "caldarus_house/Caldarus Wake Point"
on_arrival_actions = [{ animation = "eyes_closed" }]

# elsie
[elsie."6:00am"]
destination = "town/hf_kitchen_hang_1"

[elsie."3:28pm"]
destination = "town/hf_table_north_1"

[elsie."5:48pm"]
destination = "town/hf_side_chat_2"

[elsie."7:57pm"]
destination = "manor_house_dining_room/Table Right Seat 1"
on_arrival_actions = [{ activity = "drink" }]

# juniper
[juniper."6:00am"]
destination = "town/hf_table_north_5"

[juniper."12:11pm"]
destination = "town/hf_bar_1"

[juniper."2:44pm"]
destination = "town/hf_side_chat_0"

[juniper."7:58pm"]
destination = "manor_house_dining_room/Table Left Seat 1"
on_arrival_actions = [{ activity = "drink" }]

[juniper."1:18am"]
destination = "bathhouse_bedroom/Crystal Ball Seat"

# seridia
[seridia."6:00am"]
destination = "town/hf_table_north_1"

[seridia."9:48am"]
destination = "town/hf_patch_3"

[seridia."2:23pm"]
destination = "town/hf_side_chat_1"

[seridia."7:59pm"]
destination = "manor_house_dining_room/Table Right Seat 2"
on_arrival_actions = [{ activity = "drink" }]

[seridia."12:34am"]
destination = "seridias_house/Seridia Wake Point"
