priority = "max"
requires = [
	{ day_of_the_week = "friday" },
	{ weather = "pleasant" },
	{ fnati = 4 },
    { caldarus_seridia_town = true },
]
start_writes = [{ march_forge_work_day = true }]
end_writes = [
	{ inn_counter = 0 },
	{ bathhouse_counter = 0 },
	{ march_forge_work_day = false },
	{ clinic_counter = 0 },
]

# adeline
[adeline."6:00am"]
destination = "deep_woods/gor_routine_entrance"
on_arrival_actions = [{ routine = "grove_of_rest_wander" }]

[adeline."8:27am"]
destination = "deep_woods/foraging_chat_1"

[adeline."10:28am"]
destination = "bathhouse_change_room/Left Stool Seat"
on_arrival_writes = [{ bathhouse_counter = 1, operator = "+=" }]
on_departure_writes = [{ bathhouse_counter = 1, operator = "-=" }]

[adeline."3:38pm"]
destination = "inn/North Table Top 1"
on_arrival_actions = [{ activity = "order_drink" }]

# balor
[balor."6:00am"]
destination = "town/Wagon Meet Up 1"

[balor."11:35am"]
destination = "inn/North Table Left End"
on_arrival_actions = [{ activity = "eat" }]

[balor."2:12pm"]
destination = "balors_room/Desk Chair"

[balor."4:59pm"]
destination = "inn/South Table Top 3"
on_arrival_actions = [{ activity = "order_drink" }]

# caldarus
[caldarus."6:00am"]
destination = "landens_house_f1/Extra Hang"

[caldarus."9:28am"]
destination = "town/Big Tree Playdate 3"

[caldarus."1:11pm"]
destination = "town/Big Tree Right"
on_arrival_actions = [{ animation = "lute_play"}]

[caldarus."4:33pm"]
destination = "inn/South Table Top 2"
on_arrival_actions = [{ activity = "order_drink" }]

# celine
[celine."6:00am"]
destination = "deep_woods/west_forage_routine_entrance"
on_arrival_actions = [{ routine = "deep_woods_west_forage"}]

[celine."8:41am"]
destination = "deep_woods/foraging_chat_2"

[celine."10:29am"]
destination = "landens_house_f1/Register Chatting"

[celine."3:16pm"]
destination = "inn/Top Bar Hang"

# dell
[dell."6:00am"]
destination = "dells_bedroom/Dell Bed"

[dell."6:04am"]
destination = "town/Town South Meetup 3"

[dell."8:11am"]
destination = "general_store_store/shopping_entrance"
on_arrival_actions = [{ routine = "general_store_shopping" }]

[dell."11:46am"]
destination = "inn/cooking_tutorial_4"

[dell."1:18pm"]
destination = "inn/cooking_tutorial_4"
on_arrival_actions = [{ routine = "fnati_five_kids_inn"}]

[dell."5:33pm"]
destination = "inn/Bartender 2"

# dozy
[dozy."6:00am"]
destination = "bathhouse/Dozy"
on_arrival_actions = [{ routine = "dozy_snooze" }]

# eiland
[eiland."6:00am"]
destination = "museum_entry/Museum Desk"

[eiland."11:02am"]
destination = "town/adeline_business_general_store"

[eiland."4:14pm"]
destination = "inn/South Table Top 1"
on_arrival_actions = [{ activity = "order_drink" }]

# elsie
[elsie."6:00am"]
destination = "elsies_bedroom/Bed"

[elsie."6:15am"]
destination = "town/Wagon Meet Up 3"

[elsie."11:33am"]
destination = "town/Fountain Meetcute 2"

[elsie."3:57pm"]
destination = "inn/capital_club_2"

# errol
[errol."6:00am"]
destination = "landens_house_f1/Carpentry Point Right"

[errol."9:39am"]
destination = "town/garden_wander_entrance"
on_arrival_actions = [{ routine = "manor_garden_wander" }]

[errol."1:12pm"]
destination = "town/Gazebo Hang Left"

[errol."3:28pm"]
destination = "inn/North Table Top 3"
on_arrival_actions = [{ activity = "order_drink" }]

# hayden
[hayden."6:00am"]
destination = "haydens_farm/farm_chat_3"

[hayden."9:37am"]
destination = "haydens_farm/farm_chat_3"
on_arrival_actions = [{ routine = "hayden_farm_work" }]

[hayden."2:25pm"]
destination = "inn/North Table Top 2"
on_arrival_actions = [{ activity = "order_drink" }]

# hemlock
[hemlock."6:00am"]
destination = "inn/Bartender 2"
on_arrival_actions = [{ routine = "inn_table_service" }]

[hemlock."8:13am"]
destination = "inn/Story Listener 1"

[hemlock."11:14am"]
destination = "town/Big Tree Playdate 1"

[hemlock."1:10pm"]
destination = "town/Big Tree Left"
on_arrival_actions = [{ animation = "lute_play"}]

[hemlock."4:34pm"]
destination = "inn/Top Bar Seat"


# henrietta
[henrietta]
"6:00am" = "haydens_house/Hayden Kitchen"

# holt
[holt."6:00am"]
destination = "general_store_store/General Store Register"
on_arrival_actions = [{ routine = "general_store" }]

[holt."11:15am"]
destination = "town/general_store_entrance_routine"
on_arrival_actions = [{ routine = "general_store_outside_chores" }]

[holt."12:49pm"]
destination = "town/business_general_store"

[holt."4:15pm"]
destination = "inn/Top-Middle Bar Seat"


# josephine
[josephine."6:00am"]
destination = "maples_room/routine_entrance"
on_arrival_actions = [{ routine = "room_clean" }]

[josephine."8:08am"]
destination = "lucs_room/routine_entrance"
on_arrival_actions = [{ routine = "room_clean" }]

[josephine."10:13am"]
destination = "bathhouse_change_room/Left Bench Right Seat"
on_arrival_writes = [{ bathhouse_counter = 1, operator = "+=" }]
on_departure_writes = [{ bathhouse_counter = 1, operator = "-=" }]

[josephine."2:11pm"]
destination = "inn/chores_entrance"
on_arrival_actions = [{ routine = "inn_josephine_fnati_five" }]

[josephine."5:43pm"]
destination = "inn/Bottom Bar Seat"

# juniper
[juniper."6:00am"]
destination = "bathhouse_bedroom/Crystal Ball Seat"

[juniper."6:12am"]
destination = "museum_entry/south_routine_entrance"
occupy_point = false
on_arrival_actions = [{ routine = "museum_visit" }]

[juniper."11:32am"]
destination = "mines_entry/Dragon Statue"

[juniper."2:35pm"]
destination = "inn/North Table Bottom 2"
on_arrival_actions = [{ activity = "order_drink" }]


# landen
[landen."6:00am"]
destination = "landens_house_f1/Carpentry Point Left"

[landen."9:41am"]
destination = "town/garden_wander_entrance"
on_arrival_actions = [{ routine = "manor_garden_wander" }]

[landen."1:14pm"]
destination = "town/Gazebo Hang Right"

[landen."3:30pm"]
destination = "inn/North Table Bottom 3"
on_arrival_actions = [{ activity = "order_drink" }]

# luc
[luc."6:00am"]
destination = "inn/South Table Bottom 1"

[luc."6:04am"]
destination = "town/Town South Meetup 4"

[luc."8:13am"]
destination = "general_store_store/shopping_entrance"
on_arrival_actions = [{ routine = "general_store_shopping" }]

[luc."11:45am"]
destination = "inn/cooking_tutorial_3"

[luc."1:17pm"]
destination = "inn/cooking_tutorial_3"
on_arrival_actions = [{ routine = "fnati_five_kids_inn"}]

[luc."5:33pm"]
destination = "inn/Bartender 3"

# maple
[maple."6:00am"]
destination = "inn/South Table Top 1"

[maple."6:04am"]
destination = "town/Town South Meetup 1"

[maple."8:15am"]
destination = "general_store_store/shopping_entrance"
on_arrival_actions = [{ routine = "general_store_shopping" }]

[maple."11:43am"]
destination = "inn/cooking_tutorial_2"

[maple."1:16pm"]
destination = "inn/cooking_tutorial_2"
on_arrival_actions = [{ routine = "fnati_five_kids_inn"}]

[maple."5:33pm"]
destination = "inn/Bartender 4"

# march
[march."6:00am"]
destination = "haydens_farm/farm_chat_1"

[march."9:36am"]
destination = "town/north_west_routine_entrance"
on_arrival_actions = [{ routine = "forge_work_principal" }]

[march."3:49pm"]
destination = "inn/North Table Bottom 1"
on_arrival_actions = [{ activity = "order_drink" }]

# nora
[nora."6:00am"]
destination = "holt_and_noras_bedroom/Nora Wake Point"

[nora."6:39am"]
destination = "town/general_store_entrance_routine"
on_arrival_actions = [{ routine = "inspect" }]

[nora."11:32am"]
destination = "bathhouse_change_room/Left Bench Left Seat"
on_arrival_writes = [{ bathhouse_counter = 1, operator = "+=" }]
on_departure_writes = [{ bathhouse_counter = 1, operator = "-=" }]

[nora."3:37pm"]
destination = "inn/Bottom-Middle Bar Seat"

# olric
[olric."6:00am"]
destination = "narrows/Gathering Bait Near River"

[olric."10:34am"]
destination = "town/Fountain Meetcute 1"

[olric."3:56pm"]
destination = "inn/South Table Bottom 1"
on_arrival_actions = [{ activity = "order_drink" }]

# reina
[reina."6:00am"]
destination = "inn/South Table Top 1"

[reina."6:04am"]
destination = "town/Town South Meetup 2"

[reina."8:09am"]
destination = "general_store_store/shopping_entrance"
on_arrival_actions = [{ routine = "general_store_shopping" }]

[reina."11:40am"]
destination = "inn/cooking_tutorial_1"

[reina."1:16pm"]
destination = "inn/cooking_tutorial_1"
on_arrival_actions = [{ routine = "inn_josephine_fnati"}]

[reina."5:52pm"]
destination = "inn/Bartender 1"

# ryis
[ryis."6:00am"]
destination = "landens_house_f2/Ryis Wake Point"

[ryis."6:01am"]
destination = "eastern_road/bird_watching"

[ryis."10:49am"]
destination = "landens_house_f1/Register"

[ryis."3:15pm"]
destination = "inn/capital_club_3"

# seridia
[seridia."6:00am"]
destination = "inn/South Table Left End"
on_arrival_actions = [{ activity = "eat" }]

[seridia."8:09am"]
destination = "inn/Story Listener 3"

[seridia."11:15am"]
destination = "clinic_f1/Bothering Valen"

[seridia."3:35pm"]
destination = "inn/South Table Left End"
on_arrival_actions = [{ activity = "order_drink" }]

# terithia
[terithia."6:00am"]
destination = "narrows/fishing_1"
on_arrival_actions = [{ animation = "fish" }]

[terithia."10:36am"]
destination = "town/garden_wander_entrance"
on_arrival_actions = [{ routine = "manor_garden_wander" }]

[terithia."1:28pm"]
destination = "town/Manor Gazebo"

[terithia."3:25pm"]
destination = "inn/South Table Bottom 2"
on_arrival_actions = [{ activity = "order_drink" }]

# valen
[valen."6:00am"]
destination = "museum_entry/south_routine_entrance"
occupy_point = false
on_arrival_actions = [{ routine = "museum_visit" }]

[valen."9:15am"]
destination = "clinic_f1/Doctor's Desk"
on_arrival_actions = [{ animation = "write" }]

[valen."12:12pm"]
destination = "clinic_f1/Valen Chatting"

[valen."3:46pm"]
destination = "clinic_f1/Doctor's Desk"
on_arrival_actions = [{ animation = "write" }]

[valen."4:22pm"]
destination = "inn/capital_club_1"
