name = "Flora"

[sets.spring_crops]
	name = "Spring Crop Set"
	description = "A collection of crops grown during Spring."
	items = ["cabbage", "potato", "strawberry", "turnip", "cherry"]

[sets.spring_flowers]
	name = "Spring Flower Set"
	description = "A collection of flowers grown during Spring."
	items = ["daffodil", "tulip", "dandelion", "lilac", "snowdrop_anemone"]

[sets.spring_forage]
	name = "Spring Forage Set"
	description = "A collection of foraged items found during Spring."
	items = ["fennel", "fiddlehead", "morel_mushroom", "nettle", "wild_leek"]

[sets.summer_crops]
	name = "Summer Crop Set"
	description = "A collection of crops grown during Summer."
	items = ["cucumber", "chili_pepper", "watermelon", "tomato", "corn"]

[sets.summer_flowers]
	name = "Summer Flower Set"
	description = "A collection of flowers grown during Summer."
	items = ["daisy", "iris", "marigold", "catmint", "cosmos"]

[sets.summer_forage]
	name = "Summer Forage Set"
	description = "A collection of foraged items found during Summer."
	items = ["sage", "basil", "thyme", "oregano", "dill"]

[sets.fall_crops]
	name = "Fall Crop Set"
	description = "A collection of crops grown during Fall."
	items = ["broccoli", "cranberry", "pumpkin", "sweet_potato", "apple"]

[sets.fall_flowers]
	name = "Fall Flower Set"
	description = "A collection of flowers grown during Fall."
	items = ["celosia", "chrysanthemum", "fog_orchid", "heather", "viola"]

[sets.fall_forage]
	name = "Fall Forage Set"
	description = "A collection of foraged items found during Fall."
	items = ["rosemary", "garlic", "horseradish", "moon_fruit", "chestnut"]

[sets.winter_crops]
	name = "Winter Crop Set"
	description = "A collection of crops grown during Winter."
	items = ["beet", "cauliflower", "snow_peas", "daikon_radish", "pomegranate"]

[sets.winter_flowers]
	name = "Winter Flower Set"
	description = "A collection of flowers grown during Winter."
	items = ["frost_lily", "poinsettia", "jasmine", "crocus", "snapdragon"]

[sets.winter_forage]
	name = "Winter Forage Set"
	description = "A collection of foraged items found during Winter."
	items = ["burdock_root", "holly", "pineshroom", "oyster_mushroom", "rose_hip"]

[sets.deep_woods]
	name = "Deep Woods Forage Set"
	description = "A collection of foraged items found in the Deep Woods."
	items = ["thorn_vine", "spirit_mushroom", "temple_flower", "walnut", "bell_berry"]

[sets.upper_mines]
	name = "Upper Mines Forage Set"
	description = "A collection of foraged items found in the Upper Mines."
	items = [
		"upper_mines_mushroom",
		"red_toadstool",
		"sweetroot",
		"shadow_flower",
		"narrows_moss",
	]

[sets.tide_caverns]
	name = "Tide Caverns Forage Set"
	description = "A collection of foraged items found in the Tide Caverns."
	items = [
		"underseaweed",
		"sea_grapes",
		"cave_kelp",
		"mines_mussels",
		"tide_lettuce",
	]

[sets.deep_earth]
	name = "Deep Earth Forage Set"
	description = "A collection of foraged items found in the Deep Earth."
	items = [
		"crystal_berries",
		"shale_grass",
		"earthshroom",
		"rockroot",
		"crystal_rose",
	]

[sets.lava_caves]
	name = "Lava Caves Forage Set"
	description = "A collection of foraged items found in the Lava Caves."
	items = [
		"flame_pepper",
		"ash_mushroom",
		"lava_chestnuts",
		"hot_potato",
		"breath_of_fire",
	]

[sets.ruins]
	name = "Ruins Forage Set"
	description = "A collection of foraged items found in the Ruins."
	items = [
		"spell_fruit",
		"written_root",
		"essence_blossom",
		"ethereal_grass",
		"chirping_fern",
	]

[sets.void]
	name = "Void Forage Set"
	description = "A collection of void items found in the Mines."
	items = [
		"void_herb",
		"void_stone",
		"void_powder",
		"void_pearl",
		"voidite",
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_1"
	entries = [
		{ item = "treasure_box_wood" },
		{ cosmetic = "head_farmer_cap" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_2"
	entries = [
		{ item = "treasure_box_copper" },
		{ cosmetic = "overalls_farmer" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_3"
	entries = [
		{ item = "treasure_box_copper" },
		{ cosmetic = "shoes_boots_farmer" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_4"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_bed_orange" },
		{ item = "spring_double_bed_orange" },
		{ crafting_scroll = "spring_bed_orange" },
		{ crafting_scroll = "spring_double_bed_orange" },

	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_5"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_lamp_orange" },
		{ crafting_scroll = "spring_lamp_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_6"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_rug_orange" },
		{ crafting_scroll = "spring_rug_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_7"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_sofa_orange" },
		{ crafting_scroll = "spring_sofa_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_8"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_potted_tree_orange" },
		{ crafting_scroll = "spring_potted_tree_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_9"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_flooring_orange" },
		{ crafting_scroll = "spring_flooring_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_10"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "spring_wallpaper_orange" },
		{ crafting_scroll = "spring_wallpaper_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_11"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "summer_bed_red" },
		{ item = "summer_double_bed_red" },
		{ crafting_scroll = "summer_bed_red" },
		{ crafting_scroll = "summer_double_bed_red" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_12"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "summer_table_red" },
		{ crafting_scroll = "summer_table_red" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_13"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "summer_rug_red" },
		{ crafting_scroll = "summer_rug_red" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_14"
	entries = [
		{ item = "summer_chair_red" },
		{ item = "summer_jar_lamp_red" },
		{ crafting_scroll = "summer_chair_red" },
		{ crafting_scroll = "summer_jar_lamp_red" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_15"
	entries = [
		{ item = "summer_flooring_red" },
		{ item = "summer_wallpaper_red" },
		{ crafting_scroll = "summer_flooring_red" },
		{ crafting_scroll = "summer_wallpaper_red" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_16"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "fall_bed_orange" },
		{ item = "fall_double_bed_orange" },
		{ crafting_scroll = "fall_bed_orange" },
		{ crafting_scroll = "fall_double_bed_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_17"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "fall_table_orange" },
		{ crafting_scroll = "fall_table_orange" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_18"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "tesserae_tree" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_flora_19"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "void_bonsai_v1" },
		{ crafting_scroll = "void_bonsai_v1" },
	]
