name = "Insects"

[sets.multi_season]
	name = "Multi-Season Insect Set"
	description = "A collection of insects found across multiple seasons."
	items = [
		"ant",
		"bumblebee",
		"fuzzy_moth",
		"praying_mantis",
		"hummingbird_hawk_moth",
	]

[sets.spring]
	name = "Spring Insect Set"
	description = "A collection of insects found in Spring."
	items = ["luna_moth", "butterfly", "ladybug", "caterpillar", "roly_poly"]

[sets.summer]
	name = "Summer Insect Set"
	description = "A collection of insects found in Summer."
	items = [
		"cicada",
		"cricket",
		"dragonfly",
		"firefly",
		"sand_bug",
	]

[sets.fall]
	name = "Fall Insect Set"
	description = "A collection of insects found in Fall."
	items = [
		"walking_leaf",
		"cicada_nymph",
		"monarch_butterfly",
		"inchworm",
		"tiger_swallowtail_butterfly",
	]

[sets.winter]
	name = "Winter Insect Set"
	description = "A collection of insects found in Winter."
	items = [
		"crystal_caterpillar",
		"walking_stick",
		"brightbulb_moth",
		"frost_flutter_butterfly",
		"winterpillar",
	]

[sets.rare]
	name = "Rare Insect Set"
	description = "A collection of insects that are particularly hard to find."
	items = [
		"jewel_beetle",
		"lightning_dragonfly",
		"magma_beetle",
		"mistmoth",
		"orchid_mantis",
	]

[sets.upper_mines]
	name = "Upper Mines Insect Set"
	description = "A collection of insects found in the Upper Mines."
	items = [
		"lantern_moth",
		"copper_beetle",
		"worm",
		"mine_cricket",
		"tunnel_millipede",
	]

[sets.tide_caverns]
	name = "Tide Caverns Insect Set"
	description = "A collection of insects found in the Tide Caverns."
	items = [
		"sea_scarab",
		"waterfly",
		"hermit_snail",
		"puddle_spider",
		"coral_mantis",
	]

[sets.deep_earth]
	name = "Deep Earth Insect Set"
	description = "A collection of insects found in the Deep Earth."
	items = [
		"rock_roach",
		"deep_earthworm",
		"crystalline_cricket",
		"gem_shard_caterpillar",
		"crystal_wing_moth",
	]

[sets.lava_caves]
	name = "Lava Caves Insect Set"
	description = "A collection of insects found in the Lava Caves."
	items = [
		"fire_wasp",
		"cooktop_beetle",
		"lava_snail",
		"smoke_moth",
		"diamond_beetle",
	]

[sets.ruins]
	name = "Ruins Insect Set"
	description = "A collection of insects found in the Ruins."
	items = [
		"ancient_firefly",
		"void_snail",
		"giant_worm",
		"parchment_moth",
		"hidden_beetle",
	]

[sets.deep_woods]
	name = "Deep Woods Insect Set"
	description = "A collection of insects found in the Deep Woods."
	items = [
		"windleaf_butterfly",
		"mote_firefly",
		"loam_caterpillar",
		"dragon_horn_beetle",
		"singing_katydid",
	]

[sets.bee]
	name = "Bee Insect Set"
	description = "A collection of bees."
	items = [
		"fur_bee",
		"sweet_bee",
		"big_bee",
		"flower_bee",
		"moonlight_bee",
	]

[sets.honey]
	name = "Honey Set"
	description = "A collection of honey produced by apiaries."
	items = [
		"honey",
		"honey_premium",
		"honey_deluxe",
		"honey_legendary",
		"honeycomb",
	]

[sets.bug_pheromone]
	name = "Bug Pheromone Set"
	description = "A collection of insects aquired by using bug pheromones."
	items = [
		"ant_queen",
		"sunset_moth",
		"saint_mantis",
		"queens_birdwing",
		"biggest_beetle",
	]

[sets.terrarium]
	name = "Terrarium Treasures"
	description = "A collection of items produced by terrariums."
	items = [
		"bug_pheromone_uncommon",
		"bug_pheromone_rare",
		"bug_pheromone_legendary",
		"fish_bait_uncommon",
		"fish_bait_rare",
	]

[sets.grass]
	name = "Grass Insect Set"
	description = "A collection of insects found in grass."
	items = [
		"grasshopper",
		"petalhopper",
		"strawhopper",
		"leafhopper",
		"icehopper",
	]

[sets.beach]
	name = "Beach Insect Set"
	description = "A collection of insects and other crawlies found at the Beach."
	items = [
		"hermit_crab",
		"relic_crab",
		"waterbug",
		"surf_beetle",
		"beach_hopper",
	]

[sets.legendary]
	name = "Legendary Insect Set"
	description = "A collection of insects that are exceptionally hard to find."
	items = [
		"fairy_bee",
		"flower_crown_beetle",
		"snowball_beetle",
		"speedy_snail",
		"strobe_firefly",
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_1"
	entries = [
		{ item = "treasure_box_wood" },
		{ cosmetic = "head_beekeeper_hat" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_2"
	entries = [
		{ item = "treasure_box_copper" },
		{ cosmetic = "top_long_sleeve_beekeeper" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_3"
	entries = [
		{ item = "treasure_box_copper" },
		{ cosmetic = "pants_beekeeper" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_4"
	entries = [
		{ item = "treasure_box_copper" },
		{ cosmetic = "shoes_boots_beekeeper" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_5"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "butterfly_bed_v1" },
		{ item = "butterfly_double_bed_v1" },
		{ crafting_scroll = "butterfly_bed_v1" },
		{ crafting_scroll = "butterfly_double_bed_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_6"
	entries = [
		{ item = "treasure_box_silver" },
		{ item = "ladybug_table_v1" },
		{ crafting_scroll = "ladybug_table_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_7"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "insect_rug_v1" },
		{ crafting_scroll = "insect_rug_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_8"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "caterpillar_chair_v1" },
		{ crafting_scroll = "caterpillar_chair_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_9"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "moth_lamp_v1" },
		{ crafting_scroll = "moth_lamp_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_10"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "insect_wallpaper_v1" },
		{ crafting_scroll = "insect_wallpaper_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_11"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "insect_flooring_v1" },
		{ crafting_scroll = "insect_flooring_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_12"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "firefly_wall_string_lights_yellow" },
		{ crafting_scroll = "firefly_wall_string_lights_yellow" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_13"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "butterfly_wall_lamp_gold" },
		{ crafting_scroll = "butterfly_wall_lamp_gold" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_14"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "bumblebee_plushie" },
		{ crafting_scroll = "bumblebee_plushie" },
	]

# Ruins Set placeholder
[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_15"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "butterfly_painting_v1" },
		{ crafting_scroll = "butterfly_painting_v1" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_16"
	entries = [
		{ item = "treasure_box_gold" },
		{ item = "honeycomb_shelf" },
		{ crafting_scroll = "honeycomb_shelf" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_17"
	entries = [
		{ item = "treasure_box_gold" },
		{ cosmetic = "back_gear_butterfly_wings" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_18"
	entries = [
		{ item = "treasure_box_gold" },
		{ cosmetic = "back_gear_dragonfly_wings" },
	]

[[rewards]]
	preview_sprite = "spr_ui_museum_reward_insect_19"
	entries = [
		{ item = "treasure_box_gold" },
		{ cosmetic = "head_beetle_mandible_horns" },
	]
