### Head Gear
[[head_gear]]
	key = "hat"
	name = "Hats"
	icon = "spr_ui_customization_icon_hats"

[[head_gear]]
	key = "hair_accessory"
	name = "Hair Accessories"
	icon = "spr_ui_customization_icon_hair_accessories"

[[head_gear]]
	key = "helmet"
	name = "Helmets"
	icon = "spr_ui_customization_icon_helmets"

[[head_gear]]
	key = "crown"
	name = "Crowns"
	icon = "spr_ui_customization_icon_crowns"

[[head_gear]]
	key = "head_gear_wedding"
	name = "Wedding Accessories"
	icon = "spr_ui_customization_icon_wedding_head_gear"

[[head_gear]]
	key = "head_gear_misc"
	name = "Miscellaneous"
	icon = "spr_ui_customization_icon_misc"

### Face Gear
[[face_gear]]
	key = "glasses"
	name = "Glasses"
	icon = "spr_ui_customization_icon_glasses"

[[face_gear]]
	key = "ear_accessory"
	name = "Ear Accessories"
	icon = "spr_ui_customization_icon_ear_accessories"

[[face_gear]]
	key = "face_accessory"
	name = "Face Accessory"
	icon = "spr_ui_customization_icon_face_accessories"

### Hair
[[hair]]
	key = "short_hair"
	name = "Short Hair"
	icon = "spr_ui_customization_icon_short_hair"

[[hair]]
	key = "medium_hair"
	name = "Medium Hair"
	icon = "spr_ui_customization_icon_medium_hair"

[[hair]]
	key = "long_hair"
	name = "Long Hair"
	icon = "spr_ui_customization_icon_long_hair"

### Eyes
[[eyes]]
	key = "eyes"
	name = "Eyes"
	icon = "spr_ui_customization_icon_eyes"

### Facial Hair
[[facial_hair]]
	key = "facial_hair"
	name = "Facial Hair"
	icon = "spr_ui_customization_icon_facial_hair"

### Tops
[[top]]
	key = "sleeveless"
	name = "Sleeveless Tops"
	icon = "spr_ui_customization_icon_sleeveless_tops"

[[top]]
	key = "short_sleeve"
	name = "Short Sleeved Tops"
	icon = "spr_ui_customization_icon_short_sleeved_tops"

[[top]]
	key = "long_sleeve"
	name = "Long Sleeved Tops"
	icon = "spr_ui_customization_icon_long_sleeved_tops"

[[top]]
	key = "jacket"
	name = "Jackets"
	icon = "spr_ui_customization_icon_jackets"

[[top]]
	key = "dress"
	name = "Dresses"
	icon = "spr_ui_customization_icon_dresses"

[[top]]
	key = "robe"
	name = "Robes and Coats"
	icon = "spr_ui_customization_icon_robes"

[[top]]
	key = "suit"
	name = "Suits"
	icon = "spr_ui_customization_icon_suits"

[[top]]
	key = "wedding_dress"
	name = "Wedding Dresses"
	icon = "spr_ui_customization_icon_wedding_dress"

[[top]]
	key = "wedding_suit"
	name = "Wedding Suits"
	icon = "spr_ui_customization_icon_wedding_suit"

[[top]]
	key = "top_misc"
	name = "Miscellaneous"
	icon = "spr_ui_customization_icon_misc"

### Bottoms
[[bottom]]
	key = "pants"
	name = "Pants"
	icon = "spr_ui_customization_icon_pants"

[[bottom]]
	key = "shorts"
	name = "Shorts"
	icon = "spr_ui_customization_icon_shorts"

[[bottom]]
	key = "skirt"
	name = "Skirts"
	icon = "spr_ui_customization_icon_skirts"

[[bottom]]
	key = "bottom_misc"
	name = "Miscellaneous"
	icon = "spr_ui_customization_icon_misc"

### Shoes
[[feet]]
	key = "boots"
	name = "Boots"
	icon = "spr_ui_customization_icon_boots"

[[feet]]
	key = "shoes"
	name = "Shoes"
	icon = "spr_ui_customization_icon_shoes"

[[feet]]
	key = "sandals"
	name = "Sandals"
	icon = "spr_ui_customization_icon_sandals"

[[feet]]
	key = "shoes_wedding"
	name = "Wedding Shoes"
	icon = "spr_ui_customization_icon_wedding_shoes"

[[feet]]
	key = "feet_misc"
	name = "Miscellaneous"
	icon = "spr_ui_customization_icon_misc"

### Skin
[[skin]]
	key = "skin"
	name = "Skin Tone"
	icon = "spr_ui_customization_icon_skin_tone"

### Back
[[back]]
	key = "backpacks"
	name = "Backpacks"
	icon = "spr_ui_customization_icon_back_accessories"

[[back]]
	key = "capes"
	name = "Capes"
	icon = "spr_ui_customization_icon_capes"

[[back]]
	key = "back_gear_misc"
	name = "Miscellaneous"
	icon = "spr_ui_customization_icon_misc"