special_thanks = [
	"Ngozi Ukazu",
	"Callum Underwood",
	"Chris Zukowski",
	"Vadym \"YellowAfterLife\" Diachenko",
	"Seth Coster",
	"Adam Coster",
	"Shi Chen",
	"David Capello",
	"Torin Freimiller",
	"Victoria Tran",
	"YoYo Games",
	"The GameMaker Discord",
	"Russell Kay",
	"katsaii",
	"Gavin Smart",
	"Marco Frisina",
	"Ross Manthorp",
	"Toby Fox",
	"Miguel Sternberg",
	"Benjamin \"Ralith\" Saunders",
	"Omar Cornut",
	"Wholesome Games",
	"Katie",
	"Sarah McCully",
	"Lilith Todd",
	"Ashwin Balaji",
	"Tim & Sandy",
	"Ben Esposito",
	"Cate",
	"Matt C (Merg)",
	"Niki Foley",
	"Cassie Freire",
	"Dave Murray",
	"mystiblack",
	"Awkynaut",
	"nicholaito",
	"CheeseWeens",
	"Eric Kubli",
	"Sarah E. Wang",
	"Sprinklefest",
	"Jordan Liv",
	"Kris Mukai",
	"Crook",
	"Iasmin Omar Ata",
	"Kim Hoang",
	"Miranda Doveton",
	"Spenpai",
	"damppantsu",
	"Tess Stone",
	"Miri Weidner",
	"Jerome DiMartino",
	"Neowmix",
	"Alexandra Christie",
	"Julia \"Infinite Tesserae\" Hontos",
	"Frank Gibson",
	"Cypress",
	"Bomi",
	"Our Family & Friends",
]

[final]
	top = "Thank you to Yasuhiro Wada & Eric Barone"
	middle = """For founding the farm-sim genre we love so dearly,
and inspiring us to make our own contribution."""
	bottom = "And most of all, thank you for playing!"

[[npc_studio]]
	name = "Andrew Duff"
	credit = "Co-Director"
	secondary_credit = "Co-Writer, Game Designer"


[[npc_studio]]
	name = "Claire Belton"
	credit = "Co-Director"
	secondary_credit = "Co-Writer, Creative Director, Game Designer"

[[npc_studio]]
	name = "Gabe Weiner"
	credit = "Lead Producer"
	secondary_credit = "Programmer, Game Designer"

[[npc_studio]]
	name = "Jonathan Spira"
	credit = "Lead Programmer"
	secondary_credit = "Game Designer"

[[npc_studio]]
	name = "Alina Sechkin"
	credit = "Lead Pixel Artist & Animator"
	secondary_credit = "Game Designer"

[[npc_studio]]
	name = "Hidehito Ikumo"
	credit = "Lead Composer"
	secondary_credit = ""

[[npc_studio]]
	name = "Ananth Hirsh"
	credit = "Senior Writer"
	secondary_credit = ""

[[npc_studio]]
	name = "Yuko Ota"
	credit = "Character Design & Environment Concept Artist"
	secondary_credit = ""

[[npc_studio]]
	name = "Catton Arthur"
	credit = "Additional Composer, Sound Designer"
	secondary_credit = ""

[[npc_studio]]
	name = "Edward Archibald"
	credit = "Narrative Designer: Dialogue & Cutscene Implementation"
	secondary_credit = "NPC Schedule Implementation"

[[npc_studio]]
	name = "Emma Suen-Lewis"
	credit = "Pixel Artist"
	secondary_credit = "Data Analyst"

[[npc_studio]]
	name = "Dina Zatzman"
	credit = "Producer"
	secondary_credit = "Internal QA, Localization Coordination"

[[npc_studio]]
	name = "Joel Nobles"
	credit = "Programmer"
	secondary_credit = ""

[[npc_studio]]
	name = "Sarah Podzorski"
	credit = "Social Media & Marketing Manager"
	secondary_credit = ""

[[npc_studio]]
	name = "Catherine West"
	credit = "Systems Programmer"
	secondary_credit = ""

[[npc_studio]]
	name = "Kerrie Lake"
	credit = "Pixel Artist"
	secondary_credit = ""

[[npc_studio]]
	name = "Dan Tazelaar"
	credit = "QA Analyst"
	secondary_credit = ""

[[additional_contributions]]
	credit = "Programming"
	names = ["Friendly Cosmonaut", "Scary Hag", "Dina Zatzman", "Kane \"Kane\" Rogers-Wong"]

[[additional_contributions]]
	credit = "Pixel Art"
	names = ["Claire Belton", "Victor Leão", "JoelLikesPigs"]

[[additional_contributions]]
	credit = "UI Design"
	names = ["Gabe Weiner", "Claire Belton", "Alina Sechkin", "Victor Leão"]

[[additional_contributions]]
	credit = "Mines Level Design"
	names = ["Andrew Duff", "Alina Sechkin", "Friendly Cosmonaut", "Scary Hag", "Yuko Ota", "Victor F. Leão"]

[[additional_contributions]]
	credit = "Tool Development"
	names = ["Jonathan Spira", "Gabe Weiner"]

[[additional_contributions]]
	credit = "Announcement Trailer Music"
	names = ["Toby Fox"]

[[additional_contributions]]
	credit = "\"Voice Acting\" (sampled for sfx)"
	names = [
		"Catton Arthur",
		"Gabe Weiner",
		"Yuko Ota",
		"Jonathan Spira",
		"Edward Archibald",
		"Friendly Cosmonaut",
		"Scary Hag",
		"Victor Leão",
		"Joel Nobles",
		"Emma Suen-Lewis",
		"Catherine West",
		"Lyra",
		"Obsidian (Little Kitty) Battleaxe",
	]

[[additional_contributions]]
	credit = "Game World Language Design"
	names = ["Edward Archibald"]

[[additional_contributions]]
	credit = "Huwiz QA/UX"
	names = [
		"Carolljo Maher",
		"David Rioux",
		"Guillaume Lanéel",
		"Jason Smith Murk",
		"Jast Aubin",
		"Jean-Sébastien Blanchette",
		"Louis St-Denis",
		"Maxime Calvé",
		"Sandra Malenfant",
		"Willyam Labelle",
		"Zachary Barba",
		"Pierre-Marc Gauthier",
		"Jordany Normandin",
	]

[[additional_contributions]]
	credit = "Marketing"
	names = ["Gabe Weiner"]

[[additional_contributions]]
	credit = "Character Concept Art"
	names = ["David Liu", "Minoru Omura"]

[[additional_contributions]]
	credit = "Environment Concept Art"
	names = ["Matt Cummings"]

[[additional_contributions]]
	credit = "Promotional & Key Art"
	names = ["Yue", "Yuko Ota", "BisouHime", "David Liu", "Matt Cummings"]

[[additional_contributions]]
	credit = "Pixel Fonts"
	names = ["Chevy Ray", "PixelMplus", "Cubic 11", "Zpix", "Silver", "QuanPixel"]

[[additional_contributions]]
	credit = "Pixel Art Tool Scripting"
	names = ["Miguel Sternberg"]

[[additional_contributions]]
	credit = "Logo Design"
	names = ["Eiji Saeki"]

[[eight_four]]
	credit = "Producer"
	names = ["Tina Carter", "Sami Ragone"]

[[eight_four]]
	credit = "Translator"
	names = ["Yuka Rice"]

[[eight_four]]
	credit = "Proofreader"
	names = ["Alissa Staples"]

[[eight_four]]
	credit = "Localization Support"
	names = [
		"Rio Hasegawa",
		"Graeme Howard",
		"Hiroyuki Matsushita",
		"Hiroko Minamoto",
		"John Ricciardi",
		"JP Wentz",
	]

[[shloc]]
	credit = "Project Management"
	names = ["Geraint Dafis", "Pat Walczak"]

[[shloc]]
	credit = "French Localisation"
	names = ["Adeline Guichard-Lepetit", "Monia Kim", "Thibaut Salembier", "Cédric Tannay"]

[[shloc]]
	credit = "Spanish Localisation"
	names = ["Diana Díaz Montón", "Pablo Gismero Calvo", "Aurora Martínez-Esparza Ramírez"]

[[shloc]]
	credit = "Russian Localisation"
	names = ["Innokentii Shcherbinin", "Evgeny Sheyanov", "Anton Sidorov"]

[[shloc]]
	credit = "Chinese and Korean Project Management"
	names = ["Hailey He", "Sylvia Song", "Simone Xie"]

[[shloc]]
	credit = "Simplified Chinese Localisation"
	names = ["Jim Huang", "Spark Yu"]

[[shloc]]
	credit = "Traditional Chinese Localisation"
	names = ["Minsyuan Lin", "Walter Wu"]

[[shloc]]
	credit = "Korean Localisation"
	names = ["Wooyoung Jang", "Yeokyung Kim"]

[[shloc]]
	credit = "Chinese and Korean QA Support"
	names = ["IJu Kwon (KOR)", "Jude Luo (TW)", "Spark Yu (CHS)"]
