[none]

[sweat]
	sprite = "spr_portrait_effects_sweat"
	sound = "SoundEffects/NPCs/DialogSweat"

[hearts]
	sprite = "spr_portrait_effects_hearts"
	sound = "SoundEffects/NPCs/DialogHearts"

[angry]
	sprite = "spr_portrait_effects_angry"
	sound = "SoundEffects/NPCs/DialogAngry"

[sick]
	sprite = "spr_portrait_effects_sick"
	sound = "SoundEffects/NPCs/DialogSick"

[sparkles]
	sprite = "spr_portrait_effects_sparkles"
	sound = "SoundEffects/NPCs/DialogSparkle"

[sparkles_dark]
	sprite = "spr_portrait_effects_sparkles_dark"
	sound = "SoundEffects/NPCs/DialogDarkSparkle"

[music_notes]
	sprite = "spr_portrait_effects_music_notes"
	sound = "SoundEffects/NPCs/DialogSing"

[intensity]
	sprite = "spr_portrait_effects_intensity"
	sound = "SoundEffects/NPCs/DialogIntensity"

[surprise]
	sprite = "spr_portrait_effects_surprise"
	sound = "SoundEffects/NPCs/DialogSurprised"
	play_once = true

[shock]
	sprite = "spr_portrait_effects_shock"
	sound = "SoundEffects/NPCs/DialogShock"
	play_once = true

[sigh]
	sprite = "spr_portrait_effects_sigh"
	sound = "SoundEffects/NPCs/DialogSigh"
	play_once = true

[loud]
	sprite = "spr_portrait_effects_loud"
	sound = "SoundEffects/NPCs/DialogLoud"

[cheery]
	sprite = "spr_portrait_effects_cheery"
	sound = "SoundEffects/NPCs/DialogCheery"

[drop]
	sprite = "spr_portrait_effects_drop"
	sound = "SoundEffects/NPCs/DialogDrop"
	play_once = true
