[[pages]]
	menu = "player"
	tab_sprite_key = "spr_ui_journal_tab_inventory"

[[pages]]
	menu = "customization"
	tab_sprite_key = "spr_ui_journal_tab_customization"

[[pages]]
	menu = "quest_log"
	tab_sprite_key = "spr_ui_journal_tab_quests"

[[pages]]
	menu = "relationships"
	tab_sprite_key = "spr_ui_journal_tab_relationships"

[[pages]]
	menu = "animal"
	tab_sprite_key = "spr_ui_journal_tab_animals"

[[pages]]
	menu = "spellcasting"
	tab_sprite_key = "spr_ui_journal_tab_magic"

[[pages]]
	menu = "map"
	tab_sprite_key = "spr_ui_journal_tab_map"

[[pages]]
	menu = "almanac"
	tab_sprite_key = "spr_ui_journal_tab_almanac"

[[pages]]
	menu = "settings"
	tab_sprite_key = "spr_ui_journal_tab_settings"
