special_characters = ["#", "@", "$", "^", "="]
markers = [
	"ari",
	"bathhouse_cost",
	"inn_soup_of_the_day",
	"farm_name",
	"animal_name",
	"animal_pair",
	"breeding_partner",
	"treat_item",
	"statue_cost_high",
	"statue_cost_low",
	"offering_item_count",
	"offering_item_name",
	"essence_charge",
	"festival_small_animal_type",
	"festival_small_animal_name",
	"festival_large_animal_type",
	"festival_large_animal_name",
	"pet_name",
	"pet_type",
	"elsie_romantic_npc",
	"factory_days_remaining",
	"factory_item_request",
	"currently_held_item",
	"child_0",
    # "child_1",
    "infant",
    "toddler",
    "child",
    "child_held_by_ari",
    "child_held_by_spouse",
	"ten_heart_romantic",
    "fiance",
    "spouse",
    "most_eaten_dish",
]
estimated_player_name_length = 6
