# If a language does not list a font for itself in a pack, it uses what is in standard below.
[standard]
	eng = "fnt_mistria_birdseed"
	spa = "fnt_mistria_birdseed"
	fra = "fnt_mistria_birdseed"
	rus = "fnt_mistria_birdseed"
	jpn = "fnt_pixel_m_plus"
	zh-Hant = "fnt_cubic_11"
	zh-Hans = "fnt_zpix"
	kor = "fnt_silver"

[popup_description]
	jpn = "fnt_pixel_m_plus"
	zh-Hant = "fnt_cubic_11"
	zh-Hans = "fnt_zpix"
	kor = "fnt_silver"

[textbox]
	jpn = "fnt_pixel_m_plus"
	zh-Hant = "fnt_cubic_11"
	zh-Hans = "fnt_zpix"
	kor = "fnt_silver"
