# The "heart" sprite used for non-dateable NPCs in the textbox
non_dateable_heart_sprites = [
	"spr_ui_dialogue_circle_purple",
	"spr_ui_dialogue_circle_purple",
	"spr_ui_dialogue_circle_blue",
	"spr_ui_dialogue_circle_blue",
	"spr_ui_dialogue_circle_green",
	"spr_ui_dialogue_circle_green",
	"spr_ui_dialogue_circle_yellow",
	"spr_ui_dialogue_circle_yellow",
	"spr_ui_dialogue_circle_orange",
	"spr_ui_dialogue_circle_orange",
	"spr_ui_dialogue_circle_red",
]

# The heart sprites used for dateables in the textbox based on their relationship with Ari. This
# array is aligned to the number of heart levels we have in the game (10).
dateable_heart_sprites = [
	"spr_ui_dialogue_heart_purple",
	"spr_ui_dialogue_heart_purple",
	"spr_ui_dialogue_heart_blue",
	"spr_ui_dialogue_heart_blue",
	"spr_ui_dialogue_heart_green",
	"spr_ui_dialogue_heart_green",
	"spr_ui_dialogue_heart_yellow",
	"spr_ui_dialogue_heart_yellow",
	"spr_ui_dialogue_heart_orange",
	"spr_ui_dialogue_heart_orange",
	"spr_ui_dialogue_heart_red",
]
