requires = [
	{ weather = "pleasant" },
	{ caldarus_seridia_town = true },
	{ seridia_is_human = true },
	{ seridia_counter = 0 }
]

# Seridia
[seridia."6:00am"]
destination = "seridias_house/Seridia Wake Point"

[seridia."6:15am"]
destination = "seridias_house/Seridia Wake Point"
on_arrival_actions = [{ routine = "seridia_coffee_making" }]

[seridia."9:48am"]
destination = "seridias_house/Seridia Desk Chair"
on_arrival_actions = [{ animation = "write_sit" }]

[seridia."11:25am"]
destination = "seridias_house/Seridia Desk Chair"
on_arrival_actions = [{ routine = "seridia_bookshelf"}]

[seridia."3:34pm"]
destination = "seridias_house_back/Seridia Throne"
on_arrival_actions = [{ activity = "drink" }]

[seridia."8:17pm"]
destination = "western_ruins/seridia_sea_watch"

[seridia."1:12am"]
destination = "seridias_house_back/Seridia Throne"
on_arrival_actions = [{ activity = "drink" }]
on_departure_writes = [{ seridia_counter = 1 }]
