name_max_width = 81

treat_sparkle_frequency = [300, 600]

min_heart_level_for_breeding = 2

default_male_names = [
	"Oliver",
	"Rook",
	"Tango",
	"Tails",
	"Pickles",
	"Dr. Soma",
	"Pip",
	"Finn",
	"Toast",
	"Chaz",
	"Jupiter",
	"Tacky",
	"Otto",
	"Taz",
	"Hudson",
	"Frank",
	"Sammy",
	"Charlie",
	"Bobby",
	"Mango",
	"Coconut",
	"Taro",
	"Baguette",
	"Kuro",
	"Gonta",
	"Pan",
	"Puck",
	"Walter",
	"Monty",
	"Rav Tuna",
	"BJ",
	"Argus",
	"Monty",
	"Python",
	"Felix",
	"Calvin",
	"Hobbes",
	"Tobias",
	"Poggers",
	"Peanut Butter",
	"Gustavo",
	"Bo",
	"Boo",
	"Shrimp",
	"Loaf",
	"Cake",
	"Pancake",
	"Pudding",
	"Bean",
	"Koro",
	"Chappy",
	"Turbo",
	"Kuma",
	"Socks",
	"Nall",
	"Peep",
	"Harold",
	"Oisin",
	"Hawke",
	"Ashton",
	"Chip",
	"Dale",
	"Hank",
	"Milo",
	"Sunny",
	"Pants",
]
default_female_names = [
	"Kiki",
	"Zozo",
	"Pepper",
	"Poppy",
	"Juno",
	"Luna",
	"Aurora",
	"Maggie",
	"Cricket",
	"Tux",
	"Ethel",
	"Cinnamon",
	"Grendel",
	"Daisy",
	"Pepita",
	"Misha",
	"Mika",
	"Apple",
	"Leaf",
	"Alsie",
	"Elly",
	"Fanny",
	"Miki",
	"Dixie",
	"Tiny",
	"Breezy",
	"Sweetheart",
	"Millie",
	"Stormy",
	"Toro",
	"Dolly",
	"Sammy",
	"Bo",
	"Boo",
	"Shrimp",
	"Loaf",
	"Cake",
	"Pancake",
	"Pudding",
	"Bean",
	"Koro",
	"Chappy",
	"Kuma",
	"Peep",
	"Suzy",
	"Beebee",
	"Jade",
	"Charlotte",
	"Piper",
	"Carmen",
	"Erin",
	"Leslie",
	"Lemon",
]

heart_point_table = [
	100,
	220,
	360,
	520,
	700,
	900,
	1100,
	1330,
	1560,
	1800,
]

# Table of the chances and rolls an animal gets each time it produces at a given heart level
[[production_tiers]]
	hearts_required = 0
	normal = { count = 1, additional_chance = 0.0 }
	golden = { count = 0, additional_chance = 0.0 }

[[production_tiers]]
	hearts_required = 2
	normal = { count = 1, additional_chance = 0.20 }
	golden = { count = 0, additional_chance = 0.0 }

[[production_tiers]]
	hearts_required = 4
	normal = { count = 2, additional_chance = 0.0 }
	golden = { count = 0, additional_chance = 0.0 }

[[production_tiers]]
	hearts_required = 6
	normal = { count = 2, additional_chance = 0.20 }
	golden = { count = 0, additional_chance = 0.0 }

[[production_tiers]]
	hearts_required = 8
	normal = { count = 2, additional_chance = 0.0 }
	golden = { count = 0, additional_chance = 0.10 }

[[production_tiers]]
	hearts_required = 10
	normal = { count = 0, additional_chance = 0.0 }
	golden = { count = 1, additional_chance = 0.10 }

[heart_points]
	pet = 5
	feed = 5
	go_outside = 5
	left_outside_penalty = -5
	normal_feed_bonus = 0
	quality_feed_bonus = 1
	deluxe_feed_bonus = 3
	ultimate_feed_bonus = 5
	crop_bonus = 5
	cooked_star_bonuses = [5, 6, 7, 8, 9]
	child_born = 10
	toy = 2

[xp]
	pet = 2
	feed = 2
	go_outside = 2
	gain_heart = 2
	breed = 6

[festival_scoring]
	tier = [20, 25, 30, 35, 40, 45]
	heart = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
