[[haydens_farm]]
kind = "horse"
variant = "chestnut"
sex = "male"
days_old = 10

[[haydens_farm]]
kind = "cow"
variant = "white"
sex = "male"
days_old = 10

[[haydens_farm]]
kind = "cow"
variant = "brown"
sex = "female"
days_old = 0

[[haydens_farm]]
kind = "rabbit"
variant = "black_and_white"
sex = "female"
days_old = 10
require_player_unlocked = true

[[haydens_farm]]
kind = "duck"
variant = "mallard"
sex = "male"
days_old = 10
require_player_unlocked = true

[[haydens_farm]]
kind = "sheep"
variant = "white"
sex = "female"
days_old = 10
require_player_unlocked = true

[[haydens_farm]]
kind = "capybara"
variant = "light_brown"
sex = "female"
days_old = 10
require_player_unlocked = true

[[haydens_farm]]
kind = "alpaca"
variant = "black"
sex = "female"
days_old = 10
require_player_unlocked = true
