[mistril_rank]
kind = "gameplay_triggered"
writes = [{ mistril_rank = true, expires = "3d" }]
speaker = "adeline"
portrait = "shocked"
effect = "surprise"
local = "[Ari]! I was just on my way to get you!"
next = "1"

[mistril_rank.1]
speaker = "adeline"
portrait = "blush"
local = "You're not going to believe who arrived in town this morning..."
next = "2"

[mistril_rank.2]
speaker = "adeline"
portrait = "happy_blush"
effect = "cheery"
local = "The Baron and Baroness! My parents are here!"
next = "3"

[mistril_rank.3]
speaker = "adeline"
portrait = "neutral"
local = "They said they've come with news from the Capital. Isn't this exciting?"
next = "4"

[mistril_rank.4]
speaker = "adeline"
portrait = "happy"
local = "Come on, they're waiting for us just up the road!"
next = [
	{ target = "5m", requires = [
		{ any = [{ adeline_is_spouse = true }, { eiland_is_spouse = true }] }
	] },
	{ target = "5u", requres = [] }
]

# married to adeline or eiland
[mistril_rank.5m]
speaker = "linnet"
portrait = "neutral"
local = "Greetings, [Ari]!"
next = "6m"

[mistril_rank.6m]
speaker = "linnet"
portrait = "happy"
local = "It's so good to see you again!"
next = "7m"

[mistril_rank.7m]
speaker = "linnet"
portrait = "neutral"
local = "We've been meaning to pay another visit since the wedding, but things have been quite busy at court as of late."
next = "8m"

[mistril_rank.8m]
speaker = "wiscar"
portrait = "neutral"
local = "Indeed they have!"
next = "9m"

[mistril_rank.9m]
speaker = "wiscar"
portrait = "happy"
local = "Though from what I hear, the same is true of Mistria."
next = "10m"

[mistril_rank.10m]
speaker = "wiscar"
portrait = "neutral"
local = "I hope you'll excuse the suddenness of our visit."
next = "11"

# not married to adeline or eiland
[mistril_rank.5u]
speaker = "linnet"
portrait = "neutral"
local = "Ah! You must be [Ari]."
next = "6u"

[mistril_rank.6u]
speaker = "linnet"
portrait = "happy"
local = "We've heard so much about you!"
next = "7u"

[mistril_rank.7u]
speaker = "linnet"
portrait = "neutral"
local = "I am Baroness Linnet, Eiland and Adeline's mother."
next = "8u"

[mistril_rank.8u]
speaker = "wiscar"
portrait = "neutral"
local = "It's a pleasure to finally meet you, [Ari]."
next = "9u"

[mistril_rank.9u]
speaker = "wiscar"
portrait = "happy"
local = "As you may have guessed, I am their father, Baron Wiscar."
next = "10u"

[mistril_rank.10u]
speaker = "wiscar"
portrait = "wink"
local = "There is no need for formalities... you may simply call me Wiscar."
next = "11"

[mistril_rank.11]
speaker = "eiland"
portrait = "happy_blush"
local = "Mother, Father, welcome home!"
next = "12"

[mistril_rank.12]
speaker = "eiland"
portrait = "neutral"
local = "But, er... to what do we owe the pleasure?"
next = "13"

[mistril_rank.13]
speaker = "eiland"
portrait = "embarrassed"
local = "We're delighted to see you, of course, it's just that we weren't expecting-"
next = "14"

[mistril_rank.14]
speaker = "wiscar"
portrait = "happy"
local = "Patience, my son! There is plenty of time yet for all that."
next = "15"

[mistril_rank.15]
speaker = "wiscar"
portrait = "neutral"
local = "We were hoping we could take a little time to enjoy the day."
next = "16"

[mistril_rank.16]
speaker = "linnet"
portrait = "think"
local = "Mistria has changed so much since we first left for the Capital..."
next = "17"

[mistril_rank.17]
speaker = "linnet"
portrait = "happy"
local = "If you have the time, why don't you take us on a tour?"
next = "18"

[mistril_rank.18]
speaker = "linnet"
portrait = "embarrassed"
local = "You've all worked so hard on Mistria's restoration, after all."
next = "19"

[mistril_rank.19]
speaker = "linnet"
portrait = "happy"
local = "It's one thing to hear about the changes in your letters, and another to appreciate them in person!"
next = "20"

[mistril_rank.20]
speaker = "adeline"
portrait = "happy"
local = "Of course, Mother, we would be happy to!"
next = "21"

[mistril_rank.21]
speaker = "linnet"
portrait = "embarrassed"
local = "I must admit, I am nearly lost for words!"
next = "22"

[mistril_rank.22]
speaker = "linnet"
portrait = "happy"
local = "I can hardly believe how wonderful the town is looking!"
next = "23"

[mistril_rank.23]
speaker = "wiscar"
portrait = "happy"
local = "I was about to say the same!"
next = "24"

[mistril_rank.24]
speaker = "wiscar"
portrait = "neutral"
local = "It's clear how hard you've worked for Mistria's sake."
next = "25"

[mistril_rank.25]
speaker = "wiscar"
portrait = "happy"
local = "I'm so proud of you all!"
next = "26"

[mistril_rank.26]
speaker = "eiland"
portrait = "embarrassed"
local = "Oh well, it was really all [Ari] and Adeline-"
next = "27"

[mistril_rank.27]
speaker = "adeline"
portrait = "embarrassed"
local = "That's not true, Eiland..."
next = "28"

[mistril_rank.28]
speaker = "adeline"
portrait = "happy_blush"
local = "Your work with [Ari] at the Museum played a huge role in raising our $Town Rank$!"
next = "29"

[mistril_rank.29]
speaker = "wiscar"
portrait = "sad"
effect = "shock"
local = "Ah!"
next = "30"

[mistril_rank.30]
speaker = "wiscar"
portrait = "embarrassed"
local = "The $Town$-"
next = "31"

[mistril_rank.31]
speaker = "linnet"
portrait = "embarrassed"
local = "$Rank$..."
next = "32"

[mistril_rank.32]
speaker = "linnet"
portrait = "embarrassed"
local = "We were enjoying ourselves so much, we nearly forgot why we came out here in the first place!"
next = "33"

[mistril_rank.33]
speaker = "wiscar"
portrait = "happy"
local = "Not to worry!"
next = "34"

[mistril_rank.34]
speaker = "wiscar"
portrait = "neutral"
local = "Why don't we just get started now?"
next = "35"

[mistril_rank.35]
speaker = "linnet"
portrait = "think"
local = "We have a big announcement to make, you see."
next = "36"

[mistril_rank.36]
speaker = "linnet"
portrait = "neutral"
local = "One we'd like the whole town to hear."
next = "37"

[mistril_rank.37]
speaker = "linnet"
portrait = "happy"
local = "Would you three help us gather everyone?"
next = "38"

[mistril_rank.38]
speaker = "wiscar"
portrait = "happy"
local = "Thank you all for coming on such short notice!"
next = "39"

[mistril_rank.39]
speaker = "linnet"
portrait = "neutral"
local = "It does my heart wonders to see you all again."
next = "40"

[mistril_rank.40]
speaker = "errol"
portrait = "happy"
local = "Salutations, My Lord, My lady!"
next = "41"

[mistril_rank.41]
speaker = "elsie"
portrait = "happy"
local = "Welcome home, dears!"
next = "42"

[mistril_rank.42]
speaker = "landen"
portrait = "happy"
local = "It's about time you came back for a visit! We've missed you!"
next = "43"

[mistril_rank.43]
speaker = "linnet"
portrait = "think"
local = "Now, I'm sure you must be wondering about the news we've come to share."
next = "44"

[mistril_rank.44]
speaker = "linnet"
portrait = "neutral"
local = "As you know, Mistria has quickly exceeded all expectations with its achievement of $Diamond Star Town Rank$..."
next = "45"

[mistril_rank.45]
speaker = "wiscar"
portrait = "happy"
local = "The highest honor awarded by the Kingdom's $Renown$ system!"
next = "46"

[mistril_rank.46]
speaker = "wiscar"
portrait = "think"
local = "That is, until now."
next = "47"

[mistril_rank.47]
speaker = "linnet"
portrait = "neutral"
local = "The moment we have all been waiting for has finally arrived."
next = "48"

[mistril_rank.48]
speaker = "linnet"
portrait = "happy"
local = "We are incredibly honored and delighted to announce..."
next = "49"

[mistril_rank.49]
speaker = "wiscar"
portrait = "happy"
local = "By the King's royal decree..."
next = "50"

[mistril_rank.50]
speaker = "wiscar"
portrait = "neutral"
local = "A new $Town Rank$ has been created especially for Mistria, which now sits at the top position in the Kingdom!"
next = "51"

[mistril_rank.51]
speaker = "linnet"                                                         # @ gabe this needs to be linnet and wiscar
portrait = "happy"
local = "Congratulations on your achievement of $Mistril Star Town Rank$!"
next = "52"

[mistril_rank.52]
speaker = "linnet"
portrait = "neutral"
local = "And in recognition of [Ari]'s role in Mistria's rapid ascension-"
next = "53"

[mistril_rank.53]
speaker = "linnet"
portrait = "happy"
local = "King Kelinien has prepared a special award just for <he>him</he><she>her</she><they>them</they><it>it</it><none>[Ari]</none>."
next = "54"

[mistril_rank.54]
speaker = "linnet"
portrait = "embarrassed"
local = "Presenting the $Mistril Star Trophy$!"
next = "55"

[mistril_rank.55]
speaker = "linnet"
portrait = "happy"
local = "Congratulations, [Ari]!"
next = "56"

[mistril_rank.56]
speaker = "wiscar"
portrait = "happy"
local = "Congratulations!"
next = "57"

[mistril_rank.57]
speaker = "wiscar"
portrait = "embarrassed"
local = "We thank you for all that you have done for this town and its people."
next = "58"

[mistril_rank.58]
speaker = "wiscar"
portrait = "happy"
local = "You're a true Mistrian, through and through!"
next = [
	{ target = "59e", requires = [{ eiland_is_spouse = true }] },
	{ target = "59a", requires = [] }
]

[mistril_rank.59e]
speaker = "eiland"
portrait = "happy"
local = "Hear hear!"

[mistril_rank.59a]
speaker = "adeline"
portrait = "happy"
local = "Hear hear!"
