[repair_haydens_barn_pt_1_follow_up_adeline]
refresh = "never"
requires = [{ npc = "adeline" }, { rhb = "part_1" }]
portrait = "neutral"
local = "I've been dreaming of growing Mistria's economy with new exports ever since I was a little girl."
next = "1"

[repair_haydens_barn_pt_1_follow_up_adeline.1]
portrait = "happy"
local = "I can't wait for the new animals to arrive!"

[repair_haydens_barn_pt_1_follow_up_balor]
refresh = "never"
requires = [{ npc = "balor" }, { rhb = "part_1" }]
portrait = "think"
local = "Hayden let slip Adeline's little plan. Do you know how much a thoroughbred Aldarian race horse sells for?"
next = "1"

[repair_haydens_barn_pt_1_follow_up_balor.1]
portrait = "mad"
local = "We could set the entire market on its head!"

[repair_haydens_barn_pt_1_follow_up_hayden]
refresh = "never"
requires = [{ npc = "hayden" }, { rhb = "part_1" }]
portrait = "neutral"
local = "I've been familiarizing myself with all the new animals I'll have in stock after the upgrade is done."
next = "1"

[repair_haydens_barn_pt_1_follow_up_hayden.1]
portrait = "happy_fist"
local = "Henrietta's been quizzing me!"

[repair_haydens_barn_pt_1_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { rhb = "part_1" }]
portrait = "neutral"
local = """Ryis came asking me for advice about constructing the most "state of the art barn" in the whole country..."""
next = "1"

[repair_haydens_barn_pt_1_follow_up_landen.1]
portrait = "think"
local = "Then told me he could handle the actual building part."
next = "2"

[repair_haydens_barn_pt_1_follow_up_landen.2]
portrait = "mad"
local = "Who does he think built Hayden's barn in the first place?!"

[repair_haydens_barn_pt_1]
kind = "gameplay_triggered"
writes = [{ rhb = "part_1" }]
speaker = "adeline"
portrait = "think"
local = "Grain rates are determined by the king's high council, but you make a compelling argument about a sliding scale for imports, Henrietta."
next = "1"

[repair_haydens_barn_pt_1.1]
speaker = "hayden"
portrait = "neutral"
local = "Now don't belabor the point Henrietta! You know these things can't move quickly."
next = "2"

[repair_haydens_barn_pt_1.2]
speaker = "adeline"
portrait = "happy"
local = "Thanks for coming, [Ari]! I'm very excited to share my latest proposal with you two."
next = "3"

[repair_haydens_barn_pt_1.3]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "I've been excited since I got your letter! The new General Store has been the talk of the town."
next = "4"

[repair_haydens_barn_pt_1.4]
speaker = "hayden"
portrait = "gloomy"
local = "But I can't think of what we could do around this old farm that'd match..."
prompts = [
	{ local = "What if you started selling new kinds of animals?", next = "5" },
	{ local = "Advanced chicken training. Better eggs, faster laying times!", next = "6" },
]

[repair_haydens_barn_pt_1.5]
speaker = "adeline"
portrait = "neutral"
effect = "surprise"
local = "How did you guess, [Ari]? Maybe I should start running my plans by you first!"
next = "7"

[repair_haydens_barn_pt_1.6]
speaker = "henrietta"
portrait = "neutral"
local = "(Henrietta makes a loud cluck. She seems to be saying bring it on)"
next = "7"

[repair_haydens_barn_pt_1.7]
speaker = "adeline"
portrait = "think"
local = "No one in Mistria knows more about animals than you, Hayden. Well, [Ari] might be a close second."
next = "8"

[repair_haydens_barn_pt_1.8]
speaker = "hayden"
portrait = "neutral"
local = "Aw shucks. I don't like to brag, but I do try to do my best by them. Not sure I could fit additional livestock here though..."
next = "9"

[repair_haydens_barn_pt_1.9]
speaker = "adeline"
portrait = "neutral"
local = "What if we built you a larger barn and coop, ones big enough to accommodate all kinds of new animals?"
next = "10"

[repair_haydens_barn_pt_1.10]
speaker = "hayden"
portrait = "happy_arm_down"
local = "Why, that'd be a dream come true! Just think of the possibilities!"
next = "11"

[repair_haydens_barn_pt_1.11]
speaker = "hayden"
portrait = "neutral"
local = "Sheep and horses... heck, maybe even rabbits!"
next = "12"

[repair_haydens_barn_pt_1.12]
speaker = "adeline"
portrait = "happy"
local = "All with their own valuable produce! We could turn the products Mistria currently has to import into valuable exports."
next = "13"

[repair_haydens_barn_pt_1.13]
speaker = "hayden"
portrait = "happy_fist"
local = "And just imagine how cute they'd all be!"
next = "14"

[repair_haydens_barn_pt_1.14]
speaker = "hayden"
portrait = "neutral"
local = "Don't think for a minute I'd leave you out of this, [Ari]. Any new animals I start raising I'll make available to you as well."
prompts = [
	{ local = "I'm just happy to help!", next = "15" },
	{ local = "Add ducks to the list and you can count me in.", next = "16" },
]

[repair_haydens_barn_pt_1.15]
speaker = "adeline"
portrait = "blush"
local = "You're an inspiration, [Ari]!"
next = "19"

[repair_haydens_barn_pt_1.16]
speaker = "hayden"
portrait = "think"
local = "What do you think, Henrietta? You'd need to share the coop."
next = "17"

[repair_haydens_barn_pt_1.17]
speaker = "henrietta"
portrait = "neutral"
local = "(Henrietta seems to think about it for a moment before nodding her head)"
next = "18"

[repair_haydens_barn_pt_1.18]
speaker = "hayden"
portrait = "happy"
local = "It's a deal!"
next = "19"

[repair_haydens_barn_pt_1.19]
speaker = "adeline"
portrait = "concerned"
local = "This is no small upgrade, though."
next = "20"

[repair_haydens_barn_pt_1.20]
speaker = "adeline"
portrait = "neutral"
local = "[Ari], you'll need to gather $400 Wood$, $500 Stone$, $8 Iron Ingots$, and $4000t$. I'll put the $Donation Box$ next to Hayden's barn."
next = "21"

[repair_haydens_barn_pt_1.21]
speaker = "adeline"
portrait = "happy"
local = "I know this is asking a lot of both of you, but if we all work together, Mistria's future will be even brighter!"

[repair_haydens_barn_pt_2_follow_up_adeline]
refresh = "never"
requires = [{ npc = "adeline" }, { rhb = "part_2" }]
portrait = "neutral"
local = "Isn't it wonderful how much Mistria has grown? But we can't rest on our laurels yet!"
next = "1"

[repair_haydens_barn_pt_2_follow_up_adeline.1]
portrait = "wink"
local = "I've got even bigger plans, just you wait and see!"

[repair_haydens_barn_pt_2_follow_up_hayden]
refresh = "never"
requires = [{ npc = "hayden" }, { rhb = "part_2" }]
portrait = "neutral"
local = "I really can't thank you enough, [Ari]. Repairing the bridge, then the Mill, and now the new barn and coop..."
next = "1"

[repair_haydens_barn_pt_2_follow_up_hayden.1]
portrait = "happy"
local = "Have you just been repaying me back for those turnip seeds I gave you when you moved in?"
next = "2"

[repair_haydens_barn_pt_2_follow_up_hayden.2]
portrait = "laugh"
local = "Gya ha ha!"

[repair_haydens_barn_pt_2_follow_up_henrietta]
refresh = "never"
requires = [{ npc = "henrietta" }, { rhb = "part_2" }]
portrait = "neutral"
local = "(Henrietta seems to be thanking you for the new coop)"

[repair_haydens_barn_pt_2_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { rhb = "part_2" }]
portrait = "think"
local = "Don't get me wrong. I'm happy to let Ryis take over the family business, but he's still got to learn one important lesson..."
next = "1"

[repair_haydens_barn_pt_2_follow_up_landen.1]
portrait = "happy"
local = "To take help from me when I offer it! Hahaha!"

[repair_haydens_barn_pt_2_turn_in]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "neutral"
local = "Hayden is going to be so excited! Let's gather everyone up."
actions = [{ cutscene = "repair_haydens_barn_pt_2" }]

[repair_haydens_barn_pt_2]
kind = "gameplay_triggered"
writes = [{ rhb = "part_2", expires = "4d" }]
speaker = "landen"
portrait = "neutral"
local = "This barn sure takes me back. You've kept my work in great condition, Hayden!"
next = "1"

[repair_haydens_barn_pt_2.1]
speaker = "hayden"
portrait = "embarrassed"
local = "I appreciate hearing that from you, Landen."
next = "2"

[repair_haydens_barn_pt_2.2]
speaker = "ryis"
portrait = "think"
local = "Uncle, really. [Ari] and I have got this. Aren't you supposed to be retired?"
next = "3"

[repair_haydens_barn_pt_2.3]
speaker = "landen"
portrait = "mad"
local = "What a thing to say! Me? Retired?"
prompts = [
	{ local = "Many hands make light work!", next = "4" },
	{ local = "I'm sure Landen can pitch in while we do the heavy lifting.", next = "5" },
]

[repair_haydens_barn_pt_2.4]
speaker = "landen"
portrait = "neutral"
local = "See? [Ari] gets it."
next = "6"

[repair_haydens_barn_pt_2.5]
speaker = "landen"
portrait = "mad"
effect = "angry"
local = "Now you listen here-"
next = "6"

[repair_haydens_barn_pt_2.6]
speaker = "adeline"
portrait = "happy"
local = "Landen, we are honored to have someone with your decades of experience so generously lending us your aid. Right, Hayden?"
next = "7"

[repair_haydens_barn_pt_2.7]
speaker = "hayden"
portrait = "neutral_fist"
local = "Oh, absolutely!"
next = "8"

[repair_haydens_barn_pt_2.8]
speaker = "landen"
portrait = "happy"
local = "That's more like it! Come on you two, let's get to work."
next = "9"

[repair_haydens_barn_pt_2.9]
speaker = "ryis"
portrait = "sigh"
local = "Yes, Uncle."
next = "10"

[repair_haydens_barn_pt_2.10]
speaker = "hayden"
portrait = "happy"
local = "Would you look at that, Henrietta!"
next = "11"

[repair_haydens_barn_pt_2.11]
speaker = "ryis"
portrait = "happy"
local = "Haha, I think we've got her seal of approval."
next = "12"

[repair_haydens_barn_pt_2.12]
speaker = "landen"
portrait = "neutral"
local = "That was fun! You and [Ari] are shaping up into fine carpenters."
next = "13"

[repair_haydens_barn_pt_2.13]
speaker = "ryis"
portrait = "embarrassed"
local = "Thanks. Maybe next time Adeline has a big project for us, you could join in from the start."
next = "14"

[repair_haydens_barn_pt_2.14]
speaker = "landen"
portrait = "happy"
local = "I'd like that."
next = "15"

[repair_haydens_barn_pt_2.15]
speaker = "adeline"
portrait = "neutral"
local = "Thank you all! And now the real work begins for you, Hayden."
next = "16"

[repair_haydens_barn_pt_2.16]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "And I can't wait! Time to get the new animals settled."
next = "17"

[repair_haydens_barn_pt_2.17]
speaker = "hayden"
portrait = "happy_fist"
local = "You come on by any time you like for your own, [Ari]!"
