[repair_the_general_store_pt_1_dell_follow_up]
refresh = "never"
requires = [{ npc = "dell" }, { rtgs = "part_1" }]
portrait = "think"
local = "Since we're going to remodel the store anyway, I want to add a secret tunnel to my room... but mom said no."
next = "1"

[repair_the_general_store_pt_1_dell_follow_up.1]
portrait = "happy"
effect = "sparkles"
local = "Guess I'll just have to dig it myself!"

[repair_the_general_store_pt_1_celine_follow_up]
refresh = "never"
requires = [{ npc = "celine" }, { rtgs = "part_1" }]
portrait = "happy"
local = "Oh [Ari]! My parents said you're helping with the General Store remodeling!"
next = "1"

[repair_the_general_store_pt_1_celine_follow_up.1]
portrait = "very_happy"
local = "It's been my mom's dream for a long time to have a bigger store."
next = "2"

[repair_the_general_store_pt_1_celine_follow_up.2]
portrait = "think"
local = "And it's been my dad's dream to eat an entire cake in one sitting."
next = "3"

[repair_the_general_store_pt_1_celine_follow_up.3]
portrait = "sweat"
local = "I... I don't know why I told you that."

[repair_the_general_store_pt_1_ryis_follow_up]
refresh = "never"
requires = [{ npc = "ryis" }, { rtgs = "part_1" }]
portrait = "happy"
local = "Thanks for helping out again with the General Store."
next = "1"

[repair_the_general_store_pt_1_ryis_follow_up.1]
portrait = "neutral"
local = "Can't believe I get to design a whole store! It's going to be fun."

[repair_the_general_store_pt_1]
kind = "gameplay_triggered"
writes = [{ rtgs = "part_1", expires = "4d" }]
speaker = "holt"
portrait = "neutral"
local = "Hey, [Ari]!"
next = "1"

[repair_the_general_store_pt_1.1]
speaker = "nora"
portrait = "neutral"
local = "So what's this all about, Adeline? Your letter was pretty vague."
next = "2"

[repair_the_general_store_pt_1.2]
speaker = "adeline"
portrait = "happy"
local = "Mistria's bounced back from the earthquake quite nicely, don't you all think?"
next = "3"

[repair_the_general_store_pt_1.3]
speaker = "holt"
portrait = "happy"
local = "I'll say! You've unearthed a real talent for managing things, Adeline."
next = "4"

[repair_the_general_store_pt_1.4]
speaker = "adeline"
portrait = "neutral"
local = "But I don't want us to rest on our laurels. There's no reason why we can't become the best town in Aldaria!"
next = "5"

[repair_the_general_store_pt_1.5]
speaker = "nora"
portrait = "happy"
local = "We're with you of course, but where do we start?"
prompts = [
	{ local = "How about upgrading the General Store?", next = "6" },
	{ local = "How about upgrading my farm?", next = "7" },
]

[repair_the_general_store_pt_1.6]
speaker = "adeline"
portrait = "wink"
local = "Just what I was thinking!"
next = "8"

[repair_the_general_store_pt_1.7]
speaker = "adeline"
portrait = "wink"
local = "Close, but you'll need access to more supplies for that! Let's upgrade the General Store!"
next = "8"

[repair_the_general_store_pt_1.8]
speaker = "nora"
portrait = "neutral"
local = "It'd be a dream come true!"
next = "9"

[repair_the_general_store_pt_1.9]
speaker = "holt"
portrait = "neutral"
local = "More stock, a better selection... just think of all the new puns I could come up with with that kind of material!"
next = "10"

[repair_the_general_store_pt_1.10]
speaker = "adeline"
portrait = "neutral"
local = "Exactly! Everyone who lives in Mistria would see some benefit."
next = "11"

[repair_the_general_store_pt_1.11]
speaker = "adeline"
portrait = "think"
local = "That is, if you two are up to the challenges of running a larger store..."
next = "12"

[repair_the_general_store_pt_1.12]
speaker = "nora"
portrait = "mad"
effect = "sparkles"
local = "Absolutely!"
next = "13"

[repair_the_general_store_pt_1.13]
speaker = "adeline"
portrait = "happy"
local = "I thought that might be the case."
next = "14"

[repair_the_general_store_pt_1.14]
speaker = "adeline"
portrait = "concerned"
local = "Unfortunately, since this isn't a recovery project, I'm afraid the Capital won't be able to assist."
prompts = [
	{ local = "If we all pitch in, it'll be no problem!", next = "15" },
	{ local = "Stock more seeds and another bag upgrade, and you can count me in!", next = "16" },
]

[repair_the_general_store_pt_1.15]
speaker = "adeline"
portrait = "blush"
local = "Thank you!"
next = "17"

[repair_the_general_store_pt_1.16]
speaker = "holt"
portrait = "happy"
local = "Ooh, a hard bargainer!  You got a deal."
next = "17"

[repair_the_general_store_pt_1.17]
speaker = "adeline"
portrait = "neutral"
local = "Now, I've already secured Ryis and March's involvement, and I've come up with a list for each of us."
next = "18"

[repair_the_general_store_pt_1.18]
speaker = "adeline"
portrait = "think"
local = """[Ari], from you we'll need $500 Stone$, $300 Wood$, $5 Copper Ingots$, $5 Iron Ingots$ and $3000 tesserae$. I'll set up the $Donation Box$ outside the General Store."""
next = "19"

[repair_the_general_store_pt_1.19]
speaker = "nora"
portrait = "neutral"
local = "We've got a lot of work ahead of us, but I'm sure we can do it!"
next = "20"

[repair_the_general_store_pt_1.20]
speaker = "holt"
portrait = "happy"
local = "I can't wait for the Grand Opening!"

[repair_the_general_store_pt_2_nora_follow_up]
refresh = "never"
requires = [{ npc = "nora" }, { rtgs = "part_2" }]
portrait = "happy"
local = "I've had to redo all my store spreadsheets to account for the new space."
prompts = [{ local = "Lucky!", next = "1" }, { local = "And you're happy about that...?", next = "2" }]

[repair_the_general_store_pt_2_nora_follow_up.1]
portrait = "neutral"
local = "You're telling me! Maybe I'll treat myself to a new binder... I bet Adeline can recommend one."

[repair_the_general_store_pt_2_nora_follow_up.2]
portrait = "mad"
local = "Of course!"

[repair_the_general_store_pt_2_holt_follow_up]
refresh = "never"
requires = [{ npc = "holt" }, { rtgs = "part_2" }]
portrait = "neutral"
local = "Never thought it'd feel so fancy in my own store! Do you think I should start wearing a tie?"

[repair_the_general_store_pt_2_dell_follow_up]
refresh = "never"
requires = [{ npc = "dell" }, { rtgs = "part_2" }]
portrait = "neutral"
local = "There's so much more room to run around in the store now!"
next = "1"

[repair_the_general_store_pt_2_dell_follow_up.1]
portrait = "think"
local = "Mom still says I shouldn't though..."

[repair_the_general_store_pt_2_celine_follow_up]
refresh = "never"
requires = [{ npc = "celine" }, { rtgs = "part_2" }]
portrait = "neutral"
local = "Isn't the new seed selection at the General Store nice?"
next = "1"

[repair_the_general_store_pt_2_celine_follow_up.1]
portrait = "mad"
local = "It's getting me fired up for gardening!"

[repair_the_general_store_pt_2_ryis_follow_up]
refresh = "never"
requires = [{ npc = "ryis" }, { rtgs = "part_2" }]
portrait = "neutral"
local = "Repair work is needed, and I like doing it..."
next = "1"

[repair_the_general_store_pt_2_ryis_follow_up.1]
portrait = "happy"
local = "But the General Store project was very satisfying. We made a good team, huh?"

[repair_the_general_store_pt_2_turn_in]
kind = "gameplay_triggered"
actions = [{ cutscene = "repair_the_general_store_pt_2" }]
speaker = "adeline"
portrait = "neutral"
local = "Hey [Ari]! You look like you've got something to tell me."
prompts = [
	{ local = "I donated everything we need for the General Store!", next = "1" },
	{ local = "Who's ready to shop?", next = "2" },
]

[repair_the_general_store_pt_2_turn_in.1]
speaker = "adeline"
portrait = "happy"
local = "Wonderful!"
next = "3"

[repair_the_general_store_pt_2_turn_in.2]
speaker = "adeline"
portrait = "happy"
effect = "shock"
local = "Does that mean we're ready to upgrade the General Store?"
next = "3"

[repair_the_general_store_pt_2_turn_in.3]
speaker = "adeline"
portrait = "neutral"
local = "I'll gather everyone together and meet you there!"

[repair_the_general_store_pt_2]
kind = "gameplay_triggered"
writes = [{ rtgs = "part_2", expires = "4d" }]
speaker = "ryis"
portrait = "happy"
local = "Looks like we're ready to start!"
next = "1"

[repair_the_general_store_pt_2.1]
speaker = "ryis"
portrait = "neutral"
local = "Alright folks, give me a season and you'll have your brand new and improved General Store."
next = "2"

[repair_the_general_store_pt_2.2]
speaker = "nora"
portrait = "ugh"
effect = "shock"
local = "A season?!"
next = "3"

[repair_the_general_store_pt_2.3]
speaker = "celine"
portrait = "sweat"
local = "Don't worry, Mom! All of you can stay at my place!"
next = "4"

[repair_the_general_store_pt_2.4]
speaker = "ryis"
portrait = "happy"
local = "Well, I think I could speed things up if I had a little assistance..."
next = "5"

[repair_the_general_store_pt_2.5]
speaker = "ryis"
portrait = "neutral"
local = "How about it, [Ari]?"
prompts = [
	{ local = "You bet!", next = "6" },
	{ local = "We'll get this done in an impossibly short time!", next = "7" },
]

[repair_the_general_store_pt_2.6]
speaker = "ryis"
portrait = "wink"
local = "Let's get to it!"
next = "8"

[repair_the_general_store_pt_2.7]
speaker = "ryis"
portrait = "wink"
local = "Let's get to it!"
next = "8"

[repair_the_general_store_pt_2.8]
speaker = "dell"
portrait = "neutral"
local = "I'm gonna help too!"
next = "9"

[repair_the_general_store_pt_2.9]
speaker = "nora"
portrait = "mad"
local = "No, Dell."
next = "10"

[repair_the_general_store_pt_2.10]
speaker = "holt"
portrait = "mad"
local = "Look at that mess! Time to show off the family's famous sweeping technique!"
next = "11"

[repair_the_general_store_pt_2.11]
speaker = "adeline"
portrait = "happy"
local = "Wow!"
next = "12"

[repair_the_general_store_pt_2.12]
speaker = "holt"
portrait = "happy"
local = "It's so beautiful..."
next = "13"

[repair_the_general_store_pt_2.13]
speaker = "nora"
portrait = "happy"
local = "Everyone, thank you. This is a turning point for all of Mistria!"
next = "14"

[repair_the_general_store_pt_2.14]
speaker = "adeline"
portrait = "neutral"
local = "You took the words out of my mouth!"
next = "15"

[repair_the_general_store_pt_2.15]
speaker = "ryis"
portrait = "neutral"
local = "I'm glad we all got to be a part of it!"
prompts = [{ local = "It was fun!", next = "16" }, { local = "Is it too late for me to be a carpenter?", next = "17" }]

[repair_the_general_store_pt_2.16]
speaker = "ryis"
portrait = "happy"
local = "It really was!"
next = "18"

[repair_the_general_store_pt_2.17]
speaker = "adeline"
portrait = "wink"
local = "Seems like you can turn your hand to pretty much anything, [Ari]."
next = "18"

[repair_the_general_store_pt_2.18]
speaker = "nora"
portrait = "neutral"
local = "All right family, let's get those shelves stocked!"
