[repair_the_summit_stairs]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "happy"
local = "[Ari], you're here! Now we can get the party started!"
next = "1"

[repair_the_summit_stairs.1]
speaker = "eiland"
portrait = "neutral"
local = "I wouldn't call it a party, but it is needful work."
next = "2"

[repair_the_summit_stairs.2]
speaker = "adeline"
portrait = "wink"
local = "Well, maybe it's both!"
next = "3"

[repair_the_summit_stairs.3]
speaker = "adeline"
portrait = "neutral"
local = "With Mistria back on its feet, I thought it was high time to take care of some of the debris and other damage the earthquake left behind."
next = "4"

[repair_the_summit_stairs.4]
speaker = "adeline"
portrait = "concerned"
local = "I'm sure the whole town would appreciate it being dealt with."
prompts = [{ local = "Let's get beautifying!", next = "5" }, { local = "Seems like a lot of work for three people...", next = "6" }]

[repair_the_summit_stairs.5]
speaker = "adeline"
portrait = "happy"
local = "Thanks, [Ari]!"
next = "7"

[repair_the_summit_stairs.6]
speaker = "adeline"
portrait = "think"
effect = "drop"
local = "W-well I'm sure we can make a start of things at least!"
next = "7"

[repair_the_summit_stairs.7]
speaker = "eiland"
portrait = "sad"
local = "It would go faster with more help, but..."
next = "8"

[repair_the_summit_stairs.8]
speaker = "adeline"
portrait = "mad"
local = "Eiland, we talked about this. Everyone is so busy already, we need to shoulder the extra burden!"
next = "9"

[repair_the_summit_stairs.9]
speaker = "adeline"
portrait = "neutral"
local = "The sooner we start the sooner we're done! Let's go!"
next = "10"

[repair_the_summit_stairs.10]
speaker = "eiland"
portrait = "ugh"
local = "I've needed to watch my step around here, especially at night."
next = "11"

[repair_the_summit_stairs.11]
speaker = "adeline"
portrait = "sigh"
local = "With the foot traffic the square gets, we're lucky no one twisted an ankle or worse."
next = "12"

[repair_the_summit_stairs.12]
speaker = "celine"
portrait = "neutral"
effect = "cheery"
local = "Hey, you three!"
next = "13"

[repair_the_summit_stairs.13]
speaker = "reina"
portrait = "neutral"
local = "Doing some repairs? Looks fun!"
prompts = [{ local = "Why don't you two join us?", next = "14" }, { local = "I'm having a blast!", next = "16" }]

[repair_the_summit_stairs.14]
speaker = "reina"
portrait = "happy"
local = "Why not?"
next = "17"

[repair_the_summit_stairs.16]
speaker = "reina"
portrait = "happy"
local = "Oooh, count me in!"
next = "17"

[repair_the_summit_stairs.17]
speaker = "celine"
portrait = "happy"
local = "Definitely better to take care of these cracks now!"
next = "18"

[repair_the_summit_stairs.18]
speaker = "celine"
portrait = "think"
local = "Knowing my sister, Dell would probably try to dig these even deeper..."
next = "19"

[repair_the_summit_stairs.19]
speaker = "adeline"
portrait = "happy"
local = "We're making such good progress. Thanks for helping out you two!"
next = "20"

[repair_the_summit_stairs.20]
speaker = "reina"
portrait = "neutral"
local = "It hardly feels like work when we all get to chat!"
next = "21"

[repair_the_summit_stairs.21]
speaker = "adeline"
portrait = "think"
local = "This is going to leave us with a lot of leftover stone..."
next = "22"

[repair_the_summit_stairs.22]
speaker = "eiland"
portrait = "neutral"
local = "I think we have a use for it. Why don't we fix the steps up to the Summit?"
next = "23"

[repair_the_summit_stairs.23]
speaker = "adeline"
portrait = "happy"
local = "Ooh, these would make perfect repair materials! And there's less hauling for us to do as well."
next = "24"

[repair_the_summit_stairs.24]
speaker = "errol"
portrait = "neutral"
effect = "surprise"
local = "My word, was tidying the Museum campus on the docket for today?"
next = "25"

[repair_the_summit_stairs.25]
speaker = "terithia"
portrait = "neutral"
local = "I think these youngsters are trying to get one up on us, Errol! Let's show them what we can do!"
next = "26"

[repair_the_summit_stairs.26]
speaker = "errol"
portrait = "wink"
local = "Apologies, I can see my exuberance has gotten the better of me."
next = "27"

[repair_the_summit_stairs.27]
speaker = "terithia"
portrait = "happy"
local = "You old show off!"
next = "28"

[repair_the_summit_stairs.28]
speaker = "eiland"
portrait = "neutral"
local = "Isn't it wonderful to restore old stonework? Untold generations of Mistrians have made use of these steps!"
next = "29"

[repair_the_summit_stairs.29]
speaker = "celine"
portrait = "neutral"
local = "More importantly, we'll finally have access to that lemon tree up on the hill again!"
next = "30"

[repair_the_summit_stairs.30]
speaker = "reina"
portrait = "happy"
local = "And the summit! The view up there can't be beat."
next = "31"

[repair_the_summit_stairs.31]
speaker = "ryis"
portrait = "neutral"
local = "So that's what all the noise was."
next = "32"

[repair_the_summit_stairs.32]
speaker = "march"
portrait = "think"
local = "..."
next = "33"

[repair_the_summit_stairs.33]
speaker = "march"
portrait = "mad"
local = "Ryis!"
next = "34"

[repair_the_summit_stairs.34]
speaker = "ryis"
portrait = "mad"
local = "March?"
next = "35"

[repair_the_summit_stairs.35]
speaker = "march"
portrait = "unimpressed"
local = "Let's go!"
next = "36"

[repair_the_summit_stairs.36]
speaker = "adeline"
portrait = "happy"
local = "Whew! I'd say that's a job well done."
next = "37"

[repair_the_summit_stairs.37]
speaker = "errol"
portrait = "neutral"
local = "Shall we head up to the summit? I confess I've missed the view."
next = "38"

[repair_the_summit_stairs.38]
speaker = "celine"
portrait = "neutral"
local = "Yeah!"
next = "39"

[repair_the_summit_stairs.39]
speaker = "adeline"
portrait = "happy"
local = "I can't believe it! My whole list checked off so quickly!"
next = "40"

[repair_the_summit_stairs.40]
speaker = "celine"
portrait = "neutral"
local = "Next time just put out a request, Adeline."
next = "41"

[repair_the_summit_stairs.41]
speaker = "errol"
portrait = "neutral"
local = "Miss Celine is correct. Where Mistria is concerned, I believe there is no one in town who wouldn't pitch in."
next = "42"

[repair_the_summit_stairs.42]
speaker = "adeline"
portrait = "embarrassed"
local = "Everyone... thank you."
