[repair_the_mill_pt_1]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "happy"
local = "[Ari]! Great timing, we were just about to get started."
next = "1"

[repair_the_mill_pt_1.1]
speaker = "adeline"
portrait = "think"
local = "So, if we combine what we have in the town's coffers with the grant I've secured from the Capital, we've made huge progress toward repairing the $Mill$!"
next = "2"

[repair_the_mill_pt_1.2]
speaker = "hayden"
portrait = "happy"
local = "Fantastic!"
next = "3"

[repair_the_mill_pt_1.3]
speaker = "adeline"
portrait = "ugh"
local = "But we're still $1000t$ short..."
next = "4"

[repair_the_mill_pt_1.4]
speaker = "hayden"
portrait = "gloomy"
local = "Ah..."
next = "5"

[repair_the_mill_pt_1.5]
speaker = "ryis"
portrait = "think"
local = """We need more building materials too. At least another $150 Wood$,
$200 Stone$, and $2 Copper Ingots$ to complete the repairs."""
prompts = [
	{ local = "Don't worry, I can help!", next = "6" },
	{ local = "Feels like everyone is waiting for me to volunteer...", next = "6" },
]

[repair_the_mill_pt_1.6]
speaker = "adeline"
portrait = "happy"
effect = "sparkles"
local = "What a splendid idea!"
next = "7"


[repair_the_mill_pt_1.7]
speaker = "hayden"
portrait = "happy"
local = "[Ari], you're the best!"
next = "8"

[repair_the_mill_pt_1.8]
speaker = "ryis"
portrait = "neutral"
local = "You can count on me to get the job done fast when you've gathered the materials!"
next = "9"

[repair_the_mill_pt_1.9]
speaker = "hayden"
portrait = "neutral"
local = "And I'll teach you all there is to know about raising animals and milling their feed when it's ready!"
next = "10"

[repair_the_mill_pt_1.10]
speaker = "adeline"
portrait = "happy"
local = "I'll set up a $Donation Box$ at the door of the Mill. You can deposit the materials there and then bring the funds to me when you're ready."
next = "11"

[repair_the_mill_pt_1.11]
speaker = "adeline"
portrait = "neutral"
local = "It's a big job so take your time!"
next = "12"

[repair_the_mill_pt_1.12]
speaker = "ryis"
portrait = "happy"
local = "Good to have your help on this."
next = "13"

[repair_the_mill_pt_1.13]
speaker = "hayden"
portrait = "happy"
local = "Yahoo! You can do it, [Ari]!"


[repair_the_mill_pt_2_turn_in]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "happy"
local = "You're indispensable, [Ari]! Let's get this mill running again!"
actions = [{ cutscene = "repair_the_mill_pt_2" }]


[repair_the_mill_pt_2]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "happy_arm_down"
local = "Incredible!"
next = "1"

[repair_the_mill_pt_2.1]
speaker = "ryis"
portrait = "happy"
local = "Whew!"
next = "2"

[repair_the_mill_pt_2.2]
speaker = "adeline"
portrait = "happy"
local = "Wonderful work everyone! Mistria finally has its mill back! You'll be able to make all kinds of $new products$ now, [Ari]."
next = "3"

[repair_the_mill_pt_2.3]
speaker = "adeline"
portrait = "think"
local = "Would you like to hear more about how to $process items$?"
prompts = [{ local = "Yes, please!", next = "6" }, { local = "I think I'm good.", next = "5" }]

# line cut here, tutorial implemented

[repair_the_mill_pt_2.5]
speaker = "adeline"
portrait = "happy"
local = "Ohh, I suppose you've done this before, huh?"
next = "6"

[repair_the_mill_pt_2.6]
speaker = "hayden"
portrait = "neutral"
local = "I won't have to import overpriced grain anymore! Henrietta and the rest of my animals are going to be thrilled."
next = "7"

[repair_the_mill_pt_2.7]
speaker = "ryis"
portrait = "neutral"
local = "If you want to try your own hand at $raising animals$, [Ari], you'll need somewhere for them to live."
next = "8"

[repair_the_mill_pt_2.8]
speaker = "ryis"
portrait = "happy"
local = "Just come by the workshop! With the right materials, we can set you up with $Coops$ and $Barns$."
next = "9"

[repair_the_mill_pt_2.9]
speaker = "adeline"
portrait = "happy"
effect = "sparkles"
local = "Thank you again everyone!"
