[repair_the_bell_tower_pt_1_follow_up_adeline]
refresh = "never"
requires = [{ npc = "adeline" }, { rtbt = "part_1" }]
portrait = "sad"
local = "I had no idea how bad of shape the Bell Tower had gotten since the earthquake..."
next = "1"

[repair_the_bell_tower_pt_1_follow_up_adeline.1]
portrait = "mad"
local = "I should do a town audit! I don't want another surprise like that."

[repair_the_bell_tower_pt_1_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { rtbt = "part_1" }]
portrait = "neutral"
local = "I'm excited to get back to work on the Bell Tower!"
next = "1"

[repair_the_bell_tower_pt_1_follow_up_landen.1]
portrait = "happy"
local = "My mentor Jacque used to go on and on about it. He said it was a marvel of engineering."
next = "2"

[repair_the_bell_tower_pt_1_follow_up_landen.2]
portrait = "neutral"
local = "He didn't build it, and he didn't know who did. It's been in this town a long, long time."
next = "3"

[repair_the_bell_tower_pt_1_follow_up_landen.3]
portrait = "sad"
local = "Also he'd get real antsy if our repair work didn't wrap up before sunset."
next = "4"

[repair_the_bell_tower_pt_1_follow_up_landen.4]
portrait = "think"
local = "I wonder why..."

[repair_the_bell_tower_pt_1_follow_up_ryis]
refresh = "never"
requires = [{ npc = "ryis" }, { rtbt = "part_1" }]
portrait = "neutral"
local = "Landen filled me in on the Bell Tower project."
next = "1"

[repair_the_bell_tower_pt_1_follow_up_ryis.1]
portrait = "think"
local = "I'm glad we're finally going to fix it properly, but it's weird how insistent he is that we drop everything to do it as soon as you gather the supplies."

[repair_the_bell_tower_pt_1_follow_up_zorel]
priority = "max"
refresh = "never"
requires = [{ npc = "zorel" }, { rtbt = "part_1" }]
portrait = "neutral"
local = "Thanks again for helping out with the Bell Tower, [Ari]."
next = "1"

[repair_the_bell_tower_pt_1_follow_up_zorel.1]
portrait = "sad"
local = "It makes my heart hurt to hear the bell the way it is now."

[repair_the_bell_tower_pt_1]
kind = "gameplay_triggered"
writes = [{ rtbt = "part_1", expires = "7d" }, { broken_bell = true }]
speaker = "zorel"
portrait = "happy"
local = "[Ari], you came!"
next = "1"

[repair_the_bell_tower_pt_1.1]
speaker = "zorel"
portrait = "neutral"
local = "I know this seems out of the blue, but I've got such good memories of this $Bell Tower$ from when my family would visit Mistria."
next = "2"

[repair_the_bell_tower_pt_1.2]
speaker = "zorel"
portrait = "happy"
local = "Hearing the bell ring out over the town every time evening fell... it was magical."
next = "3"

[repair_the_bell_tower_pt_1.3]
speaker = "zorel"
portrait = "sad"
local = "I know the bell still works, but I'd really like to help out and get the rest of the tower fixed up!"
next = "4"

[repair_the_bell_tower_pt_1.4]
speaker = "adeline"
portrait = "happy"
local = "That's so inspiring to hear, Zorel! I'm glad you have such fond memories of Mistria."
next = "5"

[repair_the_bell_tower_pt_1.5]
speaker = "adeline"
portrait = "think"
local = "The Bell Tower was damaged in the earthquake, but since it remained mostly functional, we made the decision to seal it while we dealt with more urgent repairs."
next = "6"

[repair_the_bell_tower_pt_1.6]
speaker = "adeline"
portrait = "neutral"
local = "Landen, can you give us an update on the Bell Tower's condition?"
next = "7"

[repair_the_bell_tower_pt_1.7]
speaker = "landen"
portrait = "ugh"
local = "Well, I won't lie. It's seen better days!"
next = "8"

[repair_the_bell_tower_pt_1.8]
speaker = "landen"
portrait = "think"
local = "What with the earthquake and me retiring, maintenance hasn't been what it should be."
next = "9"

[repair_the_bell_tower_pt_1.9]
speaker = "landen"
portrait = "sad"
local = "A Bell Tower has a lot of specialized parts, see? My mentor, Old Jacque passed a lot of it down to me, but I haven't had a chance yet to pass it down to Ryis."
next = "10"

[repair_the_bell_tower_pt_1.10]
speaker = "landen"
portrait = "embarrassed"
local = "I should have, but it's been one thing after another since the earthquake."
next = "11"

[repair_the_bell_tower_pt_1.11]
speaker = "landen"
portrait = "sad"
local = "Still, let's see what we're working with."
next = "12"

[repair_the_bell_tower_pt_1.12]
speaker = "landen"
portrait = "think"
local = "Woodwork could use a refresh... foundation needs to be shored up..."
next = "13"

[repair_the_bell_tower_pt_1.13]
speaker = "landen"
portrait = "mad"
local = "The biggest issue is that the Tower's Crystal Resonator is damaged, and I don't have much expertise with them."
next = "14"

[repair_the_bell_tower_pt_1.14]
speaker = "adeline"
portrait = "sad"
local = "And here I was hoping for a quick fix..."
next = "15"

[repair_the_bell_tower_pt_1.15]
speaker = "landen"
portrait = "neutral"
local = "Well, there isn't a particular rush! The bell still rings, don't it?"
next = "16"

[repair_the_bell_tower_pt_1.16]
speaker = "landen"
portrait = "happy"
local = "It's not like it's going to fall over anytime soon."
next = "17"

[repair_the_bell_tower_pt_1.17]
speaker = "zorel"
portrait = "mad"
local = "Landen-"
next = "18"

[repair_the_bell_tower_pt_1.18]
speaker = "landen"
portrait = "happy"
effect = "drop"
local = "But hey! It sounds like a fun project. I'm happy to donate my labor free of charge! I'll even clear my schedule!"
next = "19"

[repair_the_bell_tower_pt_1.19]
speaker = "zorel"
portrait = "happy"
local = "Now we're talking!"
next = "20"

[repair_the_bell_tower_pt_1.20]
speaker = "landen"
portrait = "embarrassed"
local = "However, the recent plaza project used up a lot of the Carpenter's Shops extra stock. I could use some help with the materials..."
next = "21"

[repair_the_bell_tower_pt_1.21]
speaker = "adeline"
portrait = "embarrassed"
local = "What do you say, [Ari]?"
prompts = [
    { local = "You can all rely on me!", next = "22" },
    { local = "Will the bell still ring at nightfall like this?", next = "23" }
]

[repair_the_bell_tower_pt_1.22]
speaker = "zorel"
portrait = "happy"
local = "You're the best, [Ari]."
next = "25"

[repair_the_bell_tower_pt_1.23]
speaker = "landen"
portrait = "ugh"
effect = "drop"
local = "Well, maybe...but who knows what it's going to sound like."
next = "24"

[repair_the_bell_tower_pt_1.24]
speaker = "landen"
portrait = "embarrassed"
local = "We could really use your help, [Ari]."
next = "25"

[repair_the_bell_tower_pt_1.25]
speaker = "adeline"
portrait = "think"
local = "Based on what we talked about... would $20 Refined Stone$ and $30 Hardwood$ be adequate for the building repairs?"
next = "26"

[repair_the_bell_tower_pt_1.26]
speaker = "zorel"
portrait = "think"
local = "We'll need a $Dragon-Forged Fang$ and a $Dragon-Forged Core$ to fix the Crystal Restonator, too."
next = "27"

[repair_the_bell_tower_pt_1.27]
speaker = "zorel"
portrait = "neutral"
local = "But when it's working again, I can make some upgrades so you can $change the sound of the Bell's toll$!"
next = "28"

[repair_the_bell_tower_pt_1.28]
speaker = "zorel"
portrait = "happy"
local = "You'll even be able to $play Sound Crystals in town$, if you'd like. I've already got some really fun melodies in mind."
next = "29"

[repair_the_bell_tower_pt_1.29]
speaker = "adeline"
portrait = "neutral"
local = "I'll place the $Donation Box$ outside the Bell Tower for you, [Ari]. Come and let me know when you've gathered the materials!"

[repair_the_bell_tower_pt_2_follow_up_adeline]
refresh = "never"
requires = [{ npc = "adeline" }, { rtbt = "part_2" }]
portrait = "neutral"
local = "It does my heart good to know the Bell Tower will grace Mistria for future generations to enjoy!"

[repair_the_bell_tower_pt_2_follow_up_dell]
refresh = "never"
requires = [{ npc = "dell" }, { rtbt = "part_2" }]
portrait = "neutral"
local = "Landen sure is lucky. When I break something, my parents don't get a buncha people in town to help ME fix it."
next = "1"

[repair_the_bell_tower_pt_2_follow_up_dell.1]
portrait = "think"
local = "Maybe I'm not breaking big enough stuff..."

[repair_the_bell_tower_pt_2_follow_up_eiland]
refresh = "never"
requires = [{ npc = "eiland" }, { rtbt = "part_2" }]
portrait = "neutral"
local = "Ryis mentioned that Landen had quite a few tall tales to tell him about the Bell Tower."
next = "1"

[repair_the_bell_tower_pt_2_follow_up_eiland.1]
portrait = "think"
local = "I should make time to talk to him. As an archaeologist, an area's oral traditions can tell us quite a lot that would otherwise be missed."

[repair_the_bell_tower_pt_2_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { rtbt = "part_2" }]
portrait = "happy"
local = "Can't tell you how glad I am that the Bell Tower is back to the way it should be."
next = "1"

[repair_the_bell_tower_pt_2_follow_up_landen.1]
portrait = "neutral"
local = "Thanks again for the supplies, [Ari]. You really did me a solid!"

[repair_the_bell_tower_pt_2_follow_up_ryis]
refresh = "never"
requires = [{ npc = "ryis" }, { rtbt = "part_2" }]
portrait = "neutral"
local = "I can see why my Uncle held off on teaching me about the Bell Tower's repair."
next = "1"

[repair_the_bell_tower_pt_2_follow_up_ryis.1]
portrait = "think"
local = "Frankly, I've never seen another building like it."

[repair_the_bell_tower_pt_2_follow_up_zorel]
priority = "max"
refresh = "never"
requires = [{ npc = "zorel" }, { rtbt = "part_2" }]
portrait = "neutral"
local = "The bell's sounding great now, huh?"
next = "1"

[repair_the_bell_tower_pt_2_follow_up_zorel.1]
portrait = "happy"
local = "It's nice to think my melodies will sound out over Mistria from now on."

[repair_the_bell_tower_pt_2_turn_in]
kind = "gameplay_triggered"
actions = [{ cutscene = "repair_the_bell_tower_pt_2" }]
speaker = "adeline"
portrait = "neutral"
local = "All the materials are ready for the Bell Tower?"
next = "1"

[repair_the_bell_tower_pt_2_turn_in.1]
speaker = "adeline"
portrait = "happy"
local = "You're the best, [Ari]! Let's go get everyone!"

[repair_the_bell_tower_pt_2]
kind = "gameplay_triggered"
writes = [{ rtbt = "part_2", expires = "7d" }, { broken_bell = false }]
speaker = "landen"
portrait = "neutral"
local = "You ready, Ryis?"
next = "1"

[repair_the_bell_tower_pt_2.1]
speaker = "ryis"
portrait = "happy"
local = "Yeah! Should be an interesting challenge."
next = "2"

[repair_the_bell_tower_pt_2.2]
speaker = "landen"
portrait = "happy"
local = "That's the spirit, just follow my lead!"
next = "3"

[repair_the_bell_tower_pt_2.3]
speaker = "landen"
portrait = "neutral"
local = "You just sit back and relax, [Ari]! You've done more than enough."
next = "4"

[repair_the_bell_tower_pt_2.4]
speaker = "ryis"
portrait = "neutral"
local = "Zorel, it's safe to come in and fix the $Crystal Resonator$!"
next = "5"

[repair_the_bell_tower_pt_2.5]
speaker = "landen"
portrait = "happy"
local = "And there we are! Good as new. Better even!"
next = "6"

[repair_the_bell_tower_pt_2.6]
speaker = "ryis"
portrait = "neutral"
local = "Shall we go inside?"
next = "7"

[repair_the_bell_tower_pt_2.7]
speaker = "adeline"
portrait = "neutral"
local = "It's so beautiful in here! I'd forgotten, it's been ages since I've been inside."
next = "8"

[repair_the_bell_tower_pt_2.8]
speaker = "ryis"
portrait = "happy"
local = "Uncle Landen passed down all of his maintenance notes. I'll be able to keep the tower in great condition from now on."
next = "9"

[repair_the_bell_tower_pt_2.9]
speaker = "zorel"
portrait = "happy"
local = "The resonator is fully repaired! I've already put in some $new bell tunes$ if anyone wants to play around with it later."
next = "10"

[repair_the_bell_tower_pt_2.10]
speaker = "adeline"
portrait = "happy"
local = "Wonderful work, everyone!"
next = "11"

[repair_the_bell_tower_pt_2.11]
speaker = "zorel"
portrait = "neutral"
local = "And before we go..."
