[repair_the_beach_bridge_pt_1]
kind = "gameplay_triggered"
writes = [{ rtbb = "part_1" }]
speaker = "adeline"
portrait = "happy"
local = "Hey, [Ari]!"
next = "1"

[repair_the_beach_bridge_pt_1.1]
speaker = "terithia"
portrait = "happy"
local = "Beautiful out here, isn't it?"
next = "2"

[repair_the_beach_bridge_pt_1.2]
speaker = "terithia"
portrait = "neutral"
local = "There's a lot to love here in Mistria, but I personally think nothing beats our beach!"
next = "3"

[repair_the_beach_bridge_pt_1.3]
speaker = "adeline"
portrait = "happy"
local = "You picked the perfect spot to build a house, Terithia."
next = "4"

[repair_the_beach_bridge_pt_1.4]
speaker = "terithia"
portrait = "think"
local = "Funny thing though... it's even nicer on that little island to the west of here."
next = "5"

[repair_the_beach_bridge_pt_1.5]
speaker = "adeline"
portrait = "neutral"
local = "I remember! Before the earthquake destroyed the bridge, it was a great spot for $Fishing$ and $Foraging$. Also, it's really pretty!"
next = "6"

[repair_the_beach_bridge_pt_1.6]
speaker = "terithia"
portrait = "neutral"
local = "I sometimes take my boat past there, and it still has all those things!"
next = "7"

[repair_the_beach_bridge_pt_1.7]
speaker = "terithia"
portrait = "happy"
local = "So I thought, why not share it again with the rest of the town?"
next = "8"

[repair_the_beach_bridge_pt_1.8]
speaker = "adeline"
portrait = "think"
local = "What do you think, [Ari]?"
prompts = [
	{ local = "More beach sounds like a win to me!", next = "9" },
	{ local = "Well, I have some experience with bridges...", next = "10" }
]

[repair_the_beach_bridge_pt_1.9]
speaker = "terithia"
portrait = "happy"
local = "Me too!"
next = "11"

[repair_the_beach_bridge_pt_1.10]
speaker = "adeline"
portrait = "wink"
local = "That's true!"
next = "11"

[repair_the_beach_bridge_pt_1.11]
speaker = "adeline"
portrait = "neutral"
local = "I'll set out a $Donation Box$. I think $300 Wood$, $150 Stone$, $50 Fiber$ and then $1000t$ delivered to Terithia should cover it."
next = "12"

[repair_the_beach_bridge_pt_1.12]
speaker = "terithia"
portrait = "neutral"
local = "I'll work with Ryis on some blueprints."

[repair_the_beach_bridge_pt_2_turn_in]
kind = "gameplay_triggered"
actions = [{ cutscene = "repair_the_beach_bridge_pt_2" }]
speaker = "terithia"
portrait = "neutral"
local = "We're ready to start on the Beach Bridge?"
next = "1"

[repair_the_beach_bridge_pt_2_turn_in.1]
speaker = "terithia"
portrait = "happy"
local = "Great! Let's grab Adeline and head to the build site!"

[repair_the_beach_bridge_pt_2]
kind = "gameplay_triggered"
writes = [{ rtbb = "part_2", expires = "4d" }]
speaker = "adeline"
portrait = "happy"
local = "Wow, you two!"
next = "1"

[repair_the_beach_bridge_pt_2.1]
speaker = "terithia"
portrait = "neutral"
local = "Stone pillars, wooden slats, and rope to tie it all together! Easy to replace if anything starts to wear out."
next = "2"

[repair_the_beach_bridge_pt_2.2]
speaker = "adeline"
portrait = "neutral"
local = "And flexible enough to ride through an earthquake!"
prompts = [
	{ local = "We've done a good day's work.", next = "3" },
	{ local = "Time for island exploration!", next = "4" }
]

[repair_the_beach_bridge_pt_2.3]
speaker = "terithia"
portrait = "happy"
local = "I'll say!"
next = "5"

[repair_the_beach_bridge_pt_2.4]
speaker = "terithia"
portrait = "happy"
local = "Kya ha ha!"
next = "5"

[repair_the_beach_bridge_pt_2.5]
speaker = "adeline"
portrait = "happy"
local = "I'll pass on the good word to the rest of the town."
