[replenishing_mistrias_food_reserves_2_pt_1_follow_up_nora]
refresh = "never"
requires = [{ npc = "nora" }, { rmfr2 = "pre" }]
portrait = "think"
local = "Food supplies with a long shelf life have been in high demand since the earthquake, and I don't think that demand is going anywhere."
next = "1"

[replenishing_mistrias_food_reserves_2_pt_1_follow_up_nora.1]
portrait = "happy"
local = "We're lucky to have so many talented do-it-yourselfers in Mistria to make up for it!"

[replenishing_mistrias_food_reserves_2_pt_1_follow_up_olric]
refresh = "never"
requires = [{ npc = "olric" }, { rmfr2 = "pre" }]
portrait = "neutral"
local = "I hear you're donating to the town food reserves, [Ari]!"
next = "1"

[replenishing_mistrias_food_reserves_2_pt_1_follow_up_olric.1]
portrait = "think"
local = "I offered to make some of my famous rock cakes for the cause, but Adeline turned me down. I wonder why..."

[replenishing_mistrias_food_reserves_2_pt_1_follow_up_reina]
refresh = "never"
requires = [{ npc = "reina" }, { rmfr2 = "pre" }]
portrait = "think"
local = "It's not easy making food last a long time and taste good."
next = "1"

[replenishing_mistrias_food_reserves_2_pt_1_follow_up_reina.1]
portrait = "ugh"
local = "But if you had tried the old emergency rations...bleh."
next = "2"

[replenishing_mistrias_food_reserves_2_pt_1_follow_up_reina.2]
portrait = "mad"
local = "I'm up for the challenge!"

[replenishing_mistrias_food_reserves_2_pt_1]
kind = "gameplay_triggered"
writes = [{ rmfr2 = "pre" }]
speaker = "hayden"
portrait = "happy"
local = "[Ari], welcome!"
next = "1"

[replenishing_mistrias_food_reserves_2_pt_1.1]
speaker = "adeline"
portrait = "neutral"
local = "We've been discussing preparing long-lasting rations to fill up the remainder of the town's food reserves."
next = "3"

[replenishing_mistrias_food_reserves_2_pt_1.3]
speaker = "adeline"
portrait = "sigh"
local = "It's a tall order!"
next = "4"

[replenishing_mistrias_food_reserves_2_pt_1.4]
speaker = "reina"
portrait = "think"
local = "I'm happy to help with the cooking, but I need the ingredients."
next = "5"

[replenishing_mistrias_food_reserves_2_pt_1.5]
speaker = "reina"
portrait = "happy"
local = "The Inn has been positively bustling now that the earthquake damage is repaired. I can't have our regulars go hungry!"
next = "6"

[replenishing_mistrias_food_reserves_2_pt_1.6]
speaker = "hayden"
portrait = "neutral_fist"
local = "You know I'll give as much as I can spare for the town, Adeline."
next = "7"

[replenishing_mistrias_food_reserves_2_pt_1.7]
speaker = "hayden"
portrait = "embarrassed"
local = "But I'm afraid my flock and herd are already at capacity. I don't think we can cover your whole request."
next = "8"

[replenishing_mistrias_food_reserves_2_pt_1.8]
speaker = "hayden"
portrait = "neutral_arm_down"
local = "I've been meaning to expand the barn and get more animals but, well..."
prompts = [{ local = "Just tell me how I can help!", next = "9" }, { local = "Moo-ve over, Hayden!", next = "10" }]

[replenishing_mistrias_food_reserves_2_pt_1.9]
speaker = "adeline"
portrait = "happy"
local = "That's what I like to hear!"
next = "11"

[replenishing_mistrias_food_reserves_2_pt_1.10]
speaker = "hayden"
portrait = "happy"
local = "Oh ho, I welcome a little friendly competition!"
next = "11"

[replenishing_mistrias_food_reserves_2_pt_1.11]
speaker = "adeline"
portrait = "think"
local = "Reina, you said you need another $10 Cheeses$ for your recipe, right?"
next = "12"

[replenishing_mistrias_food_reserves_2_pt_1.12]
speaker = "hayden"
portrait = "neutral"
local = "If you haven't already made $Cheese$, the $Mill$ should come in handy."
next = "13"

[replenishing_mistrias_food_reserves_2_pt_1.13]
speaker = "hayden"
portrait = "happy_arm_down"
local = "Just get some fresh $Milk$ from your cows, bring it to the $Mill$, and before you know it you'll have as much cheese as you can carry!"
next = "14"

[replenishing_mistrias_food_reserves_2_pt_1.14]
speaker = "adeline"
portrait = "neutral"
local = "And how many eggs does the recipe call for again?"
next = "15"

[replenishing_mistrias_food_reserves_2_pt_1.15]
speaker = "reina"
portrait = "neutral"
local = "$12 Eggs$ would let me mix up enough to keep the whole town fed!"
next = "16"

[replenishing_mistrias_food_reserves_2_pt_1.16]
speaker = "reina"
portrait = "happy"
local = "And I've been experimenting with the recipe. These'll be the best tasting rations in Aldaria!"
next = "17"

[replenishing_mistrias_food_reserves_2_pt_1.17]
speaker = "hayden"
portrait = "neutral"
local = "Well now! Maybe make a few extra for us hard-working volunteers?"
next = "18"

[replenishing_mistrias_food_reserves_2_pt_1.18]
speaker = "reina"
portrait = "happy"
local = "Of course!"
next = "19"

[replenishing_mistrias_food_reserves_2_pt_1.19]
speaker = "adeline"
portrait = "think"
local = "I'll set up the $Donation Box$... hmm. Would outside the Inn work, Reina?"
next = "20"

[replenishing_mistrias_food_reserves_2_pt_1.20]
speaker = "reina"
portrait = "neutral"
local = "Sure would!"
next = "21"

[replenishing_mistrias_food_reserves_2_pt_1.21]
speaker = "hayden"
portrait = "think"
local = "And to sweeten the pot..."
next = "22"

[replenishing_mistrias_food_reserves_2_pt_1.22]
speaker = "hayden"
portrait = "happy"
local = "How about I throw in some cosmetics for your hard working chickens and cows as a reward, [Ari]?"
next = "23"

[replenishing_mistrias_food_reserves_2_pt_1.23]
speaker = "hayden"
portrait = "laugh"
local = "Gya ha ha!"

[replenishing_mistrias_food_reserves_2_pt_2_follow_up_eiland]
refresh = "never"
requires = [{ npc = "eiland" }, { rmfr2 = "post" }]
portrait = "neutral"
local = "I need to thank you, [Ari]. You wouldn't believe the meetings Adeline and I had to try and figure out what to do if another disaster hit Mistria."
next = "1"

[replenishing_mistrias_food_reserves_2_pt_2_follow_up_eiland.1]
portrait = "happy"
local = "With the reserves filling up, Adeline has dropped those meetings!"

[replenishing_mistrias_food_reserves_2_pt_2_follow_up_josephine]
refresh = "never"
requires = [{ npc = "josephine" }, { rmfr2 = "post" }]
portrait = "happy"
local = "Did you hear, [Ari]? Everyone liked those rations so much that we added them to the menu at the Inn!"
next = "1"

[replenishing_mistrias_food_reserves_2_pt_2_follow_up_josephine.1]
portrait = "think"
local = "Too bad we didn't come up with a better name for them though..."

[replenishing_mistrias_food_reserves_2_pt_2_turn_in]
actions = [{ cutscene = "replenishing_mistrias_food_reserves_2_pt_2" }]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "neutral"
local = "Hey, [Ari]! If you've turned in everything for the food reserves, it's time for the next step!"
next = "1"

[replenishing_mistrias_food_reserves_2_pt_2_turn_in.1]
speaker = "adeline"
portrait = "happy"
local = "Taste testing!"

[replenishing_mistrias_food_reserves_2_pt_2]
kind = "gameplay_triggered"
writes = [{ rmfr2 = "post", expires = "4d" }]
speaker = "reina"
portrait = "mad"
local = "Keep an eye on that stove, Dad!"
next = "1"

[replenishing_mistrias_food_reserves_2_pt_2.1]
speaker = "hemlock"
portrait = "mad"
local = "Almost there..."
next = "2"

[replenishing_mistrias_food_reserves_2_pt_2.2]
speaker = "reina"
portrait = "neutral"
effect = "drop"
local = "Whew!"
next = "3"

[replenishing_mistrias_food_reserves_2_pt_2.3]
speaker = "reina"
portrait = "neutral"
local = "Twice-baked rations, with my own secret blend of herbs and spices. Dig in!"
prompts = [{ local = "You've done it again, Reina! Superb!", next = "4" }, { local = "Seconds, please.", next = "5" }]

[replenishing_mistrias_food_reserves_2_pt_2.4]
speaker = "reina"
portrait = "happy"
local = "Yaaaaay!"
next = "6"

[replenishing_mistrias_food_reserves_2_pt_2.5]
speaker = "adeline"
portrait = "wink"
local = "I agree with [Ari] that they're very good, but if we eat too much now I'll have to put out another donation request!"
next = "6"

[replenishing_mistrias_food_reserves_2_pt_2.6]
speaker = "hayden"
portrait = "happy"
local = "Surviving on these would be a real pleasure! Hemlock, make sure you put on a beer reserve that would pair as well."
next = "7"

[replenishing_mistrias_food_reserves_2_pt_2.7]
speaker = "hemlock"
portrait = "wink"
local = "Way ahead of you, Hayden!"
next = "8"

[replenishing_mistrias_food_reserves_2_pt_2.8]
speaker = "adeline"
portrait = "happy"
local = "I think the whole town will be delighted to know that the next time there's trouble, Mistria will be ready!"
