[upgrade_the_carpenters_shop_pt_1_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { utcs = "pre" }]
portrait = "think"
local = "I know, I know, I'm retired."
next = "1"

[upgrade_the_carpenters_shop_pt_1_follow_up_landen.1]
portrait = "neutral"
local = "But just thinking about expanding the workshop... all that extra space and new tools..."
next = "2"

[upgrade_the_carpenters_shop_pt_1_follow_up_landen.2]
portrait = "happy"
local = "My hands get itchy just thinking about all the projects I could take on!"

[upgrade_the_carpenters_shop_pt_1_follow_up_march]
refresh = "never"
requires = [{ npc = "march" }, { utcs = "pre" }]
actions = [{ item = { item = "glass", count = 5 } }]
portrait = "neutral"
local = "Ryis won't stop talking about all the exciting new projects he could do if his shop gets that expansion."
next = "1"

[upgrade_the_carpenters_shop_pt_1_follow_up_march.1]
portrait = "think"
local = "..."
next = "2"

[upgrade_the_carpenters_shop_pt_1_follow_up_march.2]
portrait = "sincere_special"
local = "Here, for the $Donation Box$. Don't tell Ryis, okay?"

[upgrade_the_carpenters_shop_pt_1_follow_up_ryis]
refresh = "never"
requires = [{ npc = "ryis" }, { utcs = "pre" }]
portrait = "neutral"
local = "I'm excited about the shop expansion, but take your time okay, [Ari]?"


[upgrade_the_carpenters_shop_pt_1]
kind = "gameplay_triggered"
writes = [{ utcs = "pre" }]
speaker = "ryis"
portrait = "happy"
local = "Hey, [Ari]! We're in the back, come on in!"
next = "1"

[upgrade_the_carpenters_shop_pt_1.1]
speaker = "landen"
portrait = "happy"
local = "Hoho, I can see you've brought [Ari]! Your proposal must have really caught Adeline's attention, Ryis!"
next = "2"

[upgrade_the_carpenters_shop_pt_1.2]
speaker = "ryis"
portrait = "wink"
local = "Well, really it's [Ari]'s fault."
next = "3"

[upgrade_the_carpenters_shop_pt_1.3]
speaker = "ryis"
portrait = "neutral"
local = "Mistria's town rank has been shooting up and the projects have been quickly getting more complex."
next = "4"

[upgrade_the_carpenters_shop_pt_1.4]
speaker = "landen"
portrait = "neutral"
local = "Those fancy schmancy vendor booths really caught us off guard!"
next = "5"

[upgrade_the_carpenters_shop_pt_1.5]
speaker = "landen"
portrait = "wink"
local = "Nothing we couldn't handle of course, but we had to do some improvising."
next = "6"

[upgrade_the_carpenters_shop_pt_1.6]
speaker = "ryis"
portrait = "think"
local = "So I talked it over with my uncle, and we submitted a blueprint for a new addition to the shop to Adeline."
next = "7"

[upgrade_the_carpenters_shop_pt_1.7]
speaker = "adeline"
portrait = "happy"
local = "It was very comprehensive! You two certainly made a powerful case."
next = "8"

[upgrade_the_carpenters_shop_pt_1.8]
speaker = "landen"
portrait = "neutral"
local = "I'll spare you busy folks all the technical details, but it'll let us take on big new custom orders!"
next = "9"

[upgrade_the_carpenters_shop_pt_1.9]
speaker = "ryis"
portrait = "neutral"
local = "A larger workshop would mean that a $second story upgrade on your house$ would be possible, and we'd be able to start selling $Greenhouse$ blueprints."
prompts = [
	{ local = "So I could start growing crops out of season?", next = "10" },
	{ local = "A Greenhouse would look great on my farm...", next = "10" },
]

[upgrade_the_carpenters_shop_pt_1.10]
speaker = "ryis"
portrait = "happy"
local = "I thought that'd catch your interest! Tell you what, when we're done, I'll throw in a $Small Greenhouse Blueprint$ for free."
next = "11"

[upgrade_the_carpenters_shop_pt_1.11]
speaker = "ryis"
portrait = "neutral"
local = "And we can cover all of the ordinary materials, since we have some in stock."
next = "12"

[upgrade_the_carpenters_shop_pt_1.12]
speaker = "adeline"
portrait = "happy"
local = "Thank you, Ryis!"
next = "13"

[upgrade_the_carpenters_shop_pt_1.13]
speaker = "adeline"
portrait = "neutral"
local = "Now, I'm delighted to report that Mistria's recent turnaround has meant the town's coffers are finally in the black!"
next = "14"

[upgrade_the_carpenters_shop_pt_1.14]
speaker = "adeline"
portrait = "happy"
local = "A larger, more advanced Carpenter's Shop benefits the whole town, so we're happy to cover the tesserae costs."
next = "15"

[upgrade_the_carpenters_shop_pt_1.15]
speaker = "adeline"
portrait = "neutral"
local = "[Ari], if you could handle gathering $100 Refined Stone$, $100 Glass$, $30 Crystal$, and $30 Obsidian$, we'd have all we need."
prompts = [
	{ local = "You can count on me!", next = "16" },
	{ local = "Of course! Lucky we built that Stone Refinery, huh?", next = "17" },
]

[upgrade_the_carpenters_shop_pt_1.16]
speaker = "landen"
portrait = "happy"
local = "Yahoo!"
next = "18"

[upgrade_the_carpenters_shop_pt_1.17]
speaker = "landen"
portrait = "happy"
local = "Who needs luck when we've got you in town, [Ari]?"
next = "18"

[upgrade_the_carpenters_shop_pt_1.18]
speaker = "adeline"
portrait = "happy"
local = "Wonderful! I'll put the $Donation Box$ right outside the Carpenter's Shop. Then when you're done come talk to me!"
next = "19"

[upgrade_the_carpenters_shop_pt_1.19]
speaker = "ryis"
portrait = "happy"
local = "Thank you, [Ari]."

[upgrade_the_carpenters_shop_pt_2_follow_up_celine]
refresh = "never"
requires = [{ npc = "celine" }, { utcs = "post" }]
portrait = "neutral"
local = "Did you hear that the Carpenter's Shop is selling Greenhouses now?"
next = "1"

[upgrade_the_carpenters_shop_pt_2_follow_up_celine.1]
portrait = "think"
local = "I love gardening outdoors, but it's awfully tempting..."
next = "2"

[upgrade_the_carpenters_shop_pt_2_follow_up_celine.2]
portrait = "happy"
local = "I could grow all my favorite flowers out of season!"

[upgrade_the_carpenters_shop_pt_2_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { utcs = "post" }]
actions = [{ item = "vegetable_pot_pie" }]
portrait = "neutral"
local = "I know I've already thanked you, [Ari] but well, you've really gone above and beyond for Ryis and myself..."
next = "1"

[upgrade_the_carpenters_shop_pt_2_follow_up_landen.1]
portrait = "happy"
local = "So I made you a =Vegetable Pot Pie=! Go on, take it!"

[upgrade_the_carpenters_shop_pt_2_follow_up_ryis]
refresh = "never"
requires = [{ npc = "ryis" }, { utcs = "post" }]
portrait = "neutral"
local = "With the extra room at the shop now, Uncle Landen has been talking about coming out of retirement again."
next = "1"

[upgrade_the_carpenters_shop_pt_2_follow_up_ryis.1]
portrait = "wink"
local = "After all the projects he's been helping us out on, I thought he already had!"

[upgrade_the_carpenters_shop_pt_2_turn_in]
kind = "gameplay_triggered"
actions = [{ cutscene = "upgrade_the_carpenters_shop_pt_2" }]
speaker = "adeline"
portrait = "neutral"
local = "Ooh, Ryis and Landen will be so excited! Come on, let's get started!"

[upgrade_the_carpenters_shop_pt_2]
kind = "gameplay_triggered"
writes = [{ utcs = "post", expires = "4d" }]
speaker = "ryis"
portrait = "happy"
effect = "drop"
local = "Whew!"
next = "1"

[upgrade_the_carpenters_shop_pt_2.1]
speaker = "landen"
portrait = "neutral"
local = "Nicely done everyone!"
next = "2"

[upgrade_the_carpenters_shop_pt_2.2]
speaker = "adeline"
portrait = "happy"
local = "Wonderful work, all of you! I haven't seen a finer workshop anywhere in Aldaria."
next = "3"

[upgrade_the_carpenters_shop_pt_2.3]
speaker = "ryis"
portrait = "neutral"
local = "Here's that $Small Greenhouse Blueprint$, [Ari]. And thank you again, for everything."
next = "4"

[upgrade_the_carpenters_shop_pt_2.4]
speaker = "landen"
portrait = "happy"
local = "And feel free to swing on by if you want to see the rest of the new projects we can offer now!"
