[upgrade_the_saturday_market_plaza_follow_up_adeline]
refresh = "never"
requires = [{ npc = "adeline" }, { utsmp = "part_1" }]
portrait = "neutral"
local = "Thanks again for offering to help with gathering the materials for the new booths, [Ari]!"
next = "1"

[upgrade_the_saturday_market_plaza_follow_up_adeline.1]
portrait = "happy"
local = "I'm so excited to see the new vendors, aren't you?"

[upgrade_the_saturday_market_plaza_follow_up_landen]
refresh = "never"
requires = [
	{ npc = "landen" },
	{ any = [{ utsmp = "part_1" }, { utsmp = "part_2" }] }
]
portrait = "neutral"
local = "See the $Plaza$ yet, [Ari]?"
next = "1"

[upgrade_the_saturday_market_plaza_follow_up_landen.1]
portrait = "happy"
local = "Some of my finest woodcrafting! Those benches are practically works of art!"

[upgrade_the_saturday_market_plaza_follow_up_march]
refresh = "never"
requires = [{ npc = "march" }, { utsmp = "part_1" }]
actions = [{ item = "refined_stone", count = 5 }]
portrait = "eight_heart_happy"
local = "I had a good time building the new $Plaza$. It's nice to see that empty land get some use!"
next = "1"

[upgrade_the_saturday_market_plaza_follow_up_march.1]
portrait = "think"
local = "You need $Refined Stone$ for the new vendor booths, right?"
next = "2"

[upgrade_the_saturday_market_plaza_follow_up_march.2]
portrait = "sincere_special"
local = "Here, take these."
next = "3"

[upgrade_the_saturday_market_plaza_follow_up_march.3]
portrait = "happy"
local = "Good luck with the rest."

[upgrade_the_saturday_market_plaza_follow_up_nora]
refresh = "never"
requires = [
	{ npc = "nora" },
	{ any = [{ utsmp = "part_1" }, { utsmp = "part_2" }] }
]
portrait = "neutral"
local = "Thanks again for supporting me with the market expansion, [Ari]."
next = "1"

[upgrade_the_saturday_market_plaza_follow_up_nora.1]
portrait = "happy"
local = "We're going to have the best market for miles around!"

[upgrade_the_saturday_market_plaza_follow_up_olric]
refresh = "never"
requires = [
	{ npc = "olric" },
	{ any = [{ utsmp = "part_1" }, { utsmp = "part_2" }] }
]
portrait = "neutral"
local = "Sorry that you couldn't help with building the $Plaza$, [Ari]."
next = "1"

[upgrade_the_saturday_market_plaza_follow_up_olric.1]
portrait = "mad"
local = "I want you to know that I made sure not to have too much fun laying down the flagstone."

[upgrade_the_saturday_market_plaza_follow_up_ryis]
refresh = "never"
requires = [
	{ npc = "ryis" },
	{ any = [{ utsmp = "part_1" }, { utsmp = "part_2" }] }
]
portrait = "happy"
local = "Building the $Plaza$ was really fun!"
next = "1"

[upgrade_the_saturday_market_plaza_follow_up_ryis.1]
portrait = "neutral"
local = "I've been doing so much restoration work around Mistria that it felt nice to build something totally new."

[upgrade_the_saturday_market_plaza_turn_in]
kind = "gameplay_triggered"
writes = [{ utsmp = "part_2", expires = "3d" }]
actions = [{ bark = { bark = "cute_face", npc = "adeline" } }]
speaker = "adeline"
portrait = "happy"
local = "You got all the materials for the new vendor's booths? That's so exciting!"
next = "1"

[upgrade_the_saturday_market_plaza_turn_in.1]
speaker = "adeline"
portrait = "neutral"
local = "Nora and I will take it from here."
next = "2"

[upgrade_the_saturday_market_plaza_turn_in.2]
speaker = "adeline"
portrait = "happy"
local = "You just look forward to seeing the new vendors at the next Saturday Market!"

[upgrade_the_saturday_market_plaza]
kind = "gameplay_triggered"
writes = [{ utsmp = "part_1", expires = "3d" }]
speaker = "nora"
portrait = "neutral"
local = "[Ari], I'm so glad you could make it! I've just finished filling Adeline in."
next = "1"

[upgrade_the_saturday_market_plaza.1]
speaker = "adeline"
portrait = "happy"
local = "Such a long list of potential vendors! It's certainly flattering."
next = "2"

[upgrade_the_saturday_market_plaza.2]
speaker = "adeline"
portrait = "think"
effect = "drop"
local = "But Nora's right. There just isn't any space left in the town square to accommodate more booths..."
next = "3"

[upgrade_the_saturday_market_plaza.3]
speaker = "nora"
portrait = "think"
local = "Adeline... what would you say to calling an impromptu meeting with the Carpenters and Blacksmiths?"
next = "4"

[upgrade_the_saturday_market_plaza.4]
speaker = "nora"
portrait = "neutral"
local = "They might have some good ideas about how we could make more space."
next = "5"

[upgrade_the_saturday_market_plaza.5]
speaker = "adeline"
portrait = "happy"
local = "That's a great plan! I'll go see if Ryis and Landen are available."
next = "6"

[upgrade_the_saturday_market_plaza.6]
speaker = "adeline"
portrait = "neutral"
local = "[Ari], can you go get March and Olric? And Nora, can you get set up in the Dining Room?"
next = "7"

[upgrade_the_saturday_market_plaza.7]
speaker = "landen"
portrait = "happy"
local = "Well now, there's suddenly so much interest in our little market!"
next = "8"

[upgrade_the_saturday_market_plaza.8]
speaker = "landen"
portrait = "wink"
local = "Before we talk about space, how about you tell us who the stand out applicants are, Nora?"
next = "9"

[upgrade_the_saturday_market_plaza.9]
speaker = "nora"
portrait = "think"
local = "Well..."
next = "10"

[upgrade_the_saturday_market_plaza.10]
speaker = "nora"
portrait = "neutral"
local = "First off is Zorel, she's a popular musician from the Capital."
next = "11"

[upgrade_the_saturday_market_plaza.11]
speaker = "ryis"
portrait = "neutral"
local = "I'll say she is! My sisters wrote to me about attending one of her shows last year. And she wants to open up a vendor booth?"
next = "12"

[upgrade_the_saturday_market_plaza.12]
speaker = "nora"
portrait = "think"
local = "That's right. She's selling $Song Crystals$ that play music when placed inside a special device called a $Crystal Resonator$."
next = "13"

[upgrade_the_saturday_market_plaza.13]
speaker = "nora"
portrait = "neutral"
local = "I don't pretend to understand it, but she's passionate about them and wants to spread them across Aldaria."
next = "14"

[upgrade_the_saturday_market_plaza.14]
speaker = "adeline"
portrait = "think"
local = "In close second is Stillwell. He's a fortune teller-"
next = "15"

[upgrade_the_saturday_market_plaza.15]
speaker = "march"
portrait = "unimpressed"
local = "Oh please."
next = "16"

[upgrade_the_saturday_market_plaza.16]
speaker = "adeline"
portrait = "neutral"
local = "Well, whatever your personal opinions are about fortune telling, he's VERY popular. Even my parents have been to see him."
next = "17"

[upgrade_the_saturday_market_plaza.17]
speaker = "nora"
portrait = "think"
local = """In his application he writes that it's "vitally important" he be given a booth here."""
next = "18"

[upgrade_the_saturday_market_plaza.18]
speaker = "nora"
portrait = "neutral"
local = "If nothing else, I believe he could be a big draw. People travel from all over Aldaria to see him in the Capital."
next = "19"

[upgrade_the_saturday_market_plaza.19]
speaker = "olric"
portrait = "think"
local = "So we just gotta find a place for their booths, huh..."
next = "20"

[upgrade_the_saturday_market_plaza.20]
speaker = "olric"
portrait = "happy"
local = "I volunteer my room!"
next = "21"

[upgrade_the_saturday_market_plaza.21]
speaker = "nora"
portrait = "happy"
effect = "drop"
local = "Noted."
next = "22"

[upgrade_the_saturday_market_plaza.22]
speaker = "adeline"
portrait = "think"
local = "Does anyone else have any other ideas?"
next = "23"

[upgrade_the_saturday_market_plaza.23]
speaker = "ryis"
portrait = "think"
local = "What about that rise of land west of the Blacksmith's Shop?"
next = "24"

[upgrade_the_saturday_market_plaza.24]
speaker = "ryis"
portrait = "happy"
local = "March and I have already talked about how nice a little plaza would be up there if it was cleaned up."
next = "25"

[upgrade_the_saturday_market_plaza.25]
speaker = "march"
portrait = "happy"
local = "That's a great idea! We never had the time before, but I think we could manage it now."
next = "26"

[upgrade_the_saturday_market_plaza.26]
speaker = "adeline"
portrait = "neutral"
local = "It seems we're all in agreement!"
next = "27"

[upgrade_the_saturday_market_plaza.27]
speaker = "adeline"
portrait = "think"
local = "I'll start running the numbers, it won't be cheap to build a whole new plaza..."
prompts = [
	{ local = "You know you can count on me!", next = "28" },
	{ local = "A new plaza and new vendors? I'm in!", next = "29" }
]

[upgrade_the_saturday_market_plaza.28]
speaker = "adeline"
portrait = "happy"
local = "I'm so glad we can always count on you, [Ari]."
next = "30"

[upgrade_the_saturday_market_plaza.29]
speaker = "adeline"
portrait = "happy"
local = "The whole town will certainly benefit!"
next = "30"

[upgrade_the_saturday_market_plaza.30]
speaker = "landen"
portrait = "mad"
local = "Whoa whoa whoa!"
next = "31"

[upgrade_the_saturday_market_plaza.31]
speaker = "landen"
portrait = "think"
local = "Now [Ari], you've done your share and then some. Let us take our share of the load!"
next = "32"

[upgrade_the_saturday_market_plaza.32]
speaker = "olric"
portrait = "happy"
local = "Yeah! Your laurels need resting or they're going to get worn out."
next = "33"

[upgrade_the_saturday_market_plaza.33]
speaker = "march"
portrait = "think"
local = "I don't know if I agree with Olric's phrasing, but I agree to his sentiment."
next = "34"

[upgrade_the_saturday_market_plaza.34]
speaker = "ryis"
portrait = "neutral"
local = "Yeah, [Ari]. You leave the plaza to us!"
next = "35"

[upgrade_the_saturday_market_plaza.35]
speaker = "landen"
portrait = "mad"
local = "Quick everyone! Let's get started right now, or else [Ari] will sneak in somehow!"
next = "36"

[upgrade_the_saturday_market_plaza.36]
speaker = "march"
portrait = "sigh"
local = "That does sound like <he>him</he><she>her</she><they>them</they><it>it</it><none>[Ari]</none>..."
next = "37"

[upgrade_the_saturday_market_plaza.37]
speaker = "olric"
portrait = "happy"
local = "I call dibs on breaking all the rocks!"
next = "38"

[upgrade_the_saturday_market_plaza.38]
speaker = "nora"
portrait = "happy"
local = "Weren't they enthusiastic!"
prompts = [
	{ local = "But I still want to help...", next = "39" },
	{ local = "Guess my time to shine is over...", next = "40" }
]

[upgrade_the_saturday_market_plaza.39]
speaker = "nora"
portrait = "embarrassed"
effect = "drop"
local = "Are you sure you don't want to relax? Well, if you insist..."
next = "41"

[upgrade_the_saturday_market_plaza.40]
speaker = "nora"
portrait = "embarrassed"
effect = "drop"
local = "Well, if you insist on contributing..."
next = "41"

[upgrade_the_saturday_market_plaza.41]
speaker = "nora"
portrait = "think"
local = "Adeline, didn't the vendors have some unusual materials requests for building their booths?"
next = "42"

[upgrade_the_saturday_market_plaza.42]
speaker = "adeline"
portrait = "think"
local = "They certainly did! They're looking for $50 Voidite$, $20 Refined Stone$, $5 Mistril Ingots$, $10 Monster Cores$ and $5 Monster Blocks$."
next = "43"

[upgrade_the_saturday_market_plaza.43]
speaker = "adeline"
portrait = "neutral"
local = "It'd be a huge help if you could handle gathering those for us, [Ari]."
next = "44"

[upgrade_the_saturday_market_plaza.44]
speaker = "adeline"
portrait = "happy"
local = "Thank you!"
next = "45"

[upgrade_the_saturday_market_plaza.45]
speaker = "adeline"
portrait = "neutral"
local = "I'll set up the $Donation Box$ at the new plaza to the $west of the Blacksmith's$ for you."
next = "46"

[upgrade_the_saturday_market_plaza.46]
speaker = "adeline"
portrait = "wink"
local = "Just let me know when it's done!"
next = "47"

[upgrade_the_saturday_market_plaza.47]
speaker = "nora"
portrait = "happy"
local = "Thank you [Ari], and Adeline. I can't believe the Saturday Market is going to be growing again!"
