[upgrade_the_saturday_market_follow_up_landen]
refresh = "never"
requires = [{ npc = "landen" }, { utsm = "part_1" }]
portrait = "neutral"
local = "There you are! Thank you so much for helping out with those goofy requirements for those snooty Capital vendors."
next = "1"

[upgrade_the_saturday_market_follow_up_landen.1]
portrait = "mad"
local = "Ryis and I are going to make the best booths they've ever seen!"

[upgrade_the_saturday_market_follow_up_march]
refresh = "never"
requires = [{ npc = "march" }, { utsm = "part_1" }]
portrait = "neutral"
local = "Never thought I'd see the day where a town project required me to do gold ornamentation work..."
next = "1"

[upgrade_the_saturday_market_follow_up_march.1]
portrait = "happy"
local = "I'm looking forward to working on the new vendor booths."

[upgrade_the_saturday_market_follow_up_nora]
refresh = "never"
requires = [{ npc = "nora" }, { utsm = "part_1" }]
portrait = "neutral"
local = "I can't thank you enough for helping out with these market booths, [Ari]."
next = "1"

[upgrade_the_saturday_market_follow_up_nora.1]
portrait = "happy"
local = "It's such a big milestone for the town!"

[upgrade_the_saturday_market_follow_up_ryis]
refresh = "never"
requires = [{ npc = "ryis" }, { utsm = "part_1" }]
portrait = "neutral"
local = "Landen and I have been working on the new vendor booth's blueprints."
next = "1"

[upgrade_the_saturday_market_follow_up_ryis.1]
portrait = "happy"
local = "It's a really exciting project! I've roped in March to help with the gold ornamentation, he loves working on that kind of thing."

[upgrade_the_saturday_market_pre_turn_in]
kind = "gameplay_triggered"
speaker = "adeline"
portrait = "happy"
local = "[Ari]! I can't wait to tell you all about the news. Come on!"
actions = [{ cutscene = "upgrade_the_saturday_market" }]

[upgrade_the_saturday_market_post_turn_in]
kind = "gameplay_triggered"
writes = [{ utsm = "part_2" }]
actions = [{ bark = { bark = "cute_face", npc = "adeline" } }]
speaker = "adeline"
portrait = "happy"
local = "You've gathered all the materials for the new Saturday Market vendors? Incredible work, [Ari]!"
next = "1"

[upgrade_the_saturday_market_post_turn_in.1]
speaker = "adeline"
portrait = "neutral"
local = "I'll let Ryis know, I'm sure he and Landen are raring to go."
next = "2"

[upgrade_the_saturday_market_post_turn_in.2]
speaker = "adeline"
portrait = "happy"
effect = "cheery"
local = "We should be able to get everything ready for the new vendors to join us on $Saturday$!"

[upgrade_the_saturday_market]
kind = "gameplay_triggered"
writes = [{ utsm = "part_1" }]
speaker = "nora"
portrait = "think"
local = "What's this all about, Adeline? I haven't seen you this excited since we got in that special order of colored pens."
next = "1"

[upgrade_the_saturday_market.1]
speaker = "adeline"
portrait = "happy"
local = "A letter arrived from the $Aldarian Merchant's Guild$, Nora."
next = "2"

[upgrade_the_saturday_market.2]
speaker = "nora"
portrait = "happy"
effect = "surprise"
local = "That is big news!"
next = "3"

[upgrade_the_saturday_market.3]
speaker = "nora"
portrait = "neutral"
local = "The $Aldarian Merchant's Guild$ handles all the business in the Capital, as well as any incoming and outgoing shipments in the country."
next = "4"

[upgrade_the_saturday_market.4]
speaker = "nora"
portrait = "think"
local = "A little place like Mistria would normally be beneath their notice."
next = "5"

[upgrade_the_saturday_market.5]
speaker = "adeline"
portrait = "neutral"
local = "They're impressed with how successful our $Saturday Market$ has become, and with how high our town rank has risen."
next = "6"

[upgrade_the_saturday_market.6]
speaker = "adeline"
portrait = "happy"
local = "In fact, they're so impressed, they're considering adding Mistria to the weekly travel routes of $two of their top vendors$!"
next = "7"

[upgrade_the_saturday_market.7]
speaker = "nora"
portrait = "happy"
local = "That's- That's incredible! Anyone I'd know?"
next = "8"

[upgrade_the_saturday_market.8]
speaker = "adeline"
portrait = "wink"
local = "I think you'll recognize both their names."
next = "9"

[upgrade_the_saturday_market.9]
speaker = "adeline"
portrait = "neutral"
local = "First up is $Taliferro$, he's the Royal Chef whose $Cooking Challenge$ booth has been a huge hit across Aldaria."
next = "10"

[upgrade_the_saturday_market.10]
speaker = "adeline"
portrait = "concerned"
local = "And uh... $Wheedle$. He's apparently very high up in the Merchant's Guild, specializing in $extremely high-end goods$."
next = "11"

[upgrade_the_saturday_market.11]
speaker = "nora"
portrait = "think"
local = "You're right, I have heard about them. Supposedly, they're both real characters."
next = "12"

[upgrade_the_saturday_market.12]
speaker = "nora"
portrait = "sad"
local = "But I shouldn't let rumors stand in the way of letting everyone in Mistria enjoy their booths."
next = "13"

[upgrade_the_saturday_market.13]
speaker = "adeline"
portrait = "happy"
local = "I feel the same way."
next = "14"

[upgrade_the_saturday_market.14]
speaker = "adeline"
portrait = "neutral"
local = "Now, the Capital will be covering their traveling expenses..."
next = "15"

[upgrade_the_saturday_market.15]
speaker = "adeline"
portrait = "think"
local = "And before you worry about it Nora, I volunteer the front lawn of the Manor House for them to set up their booths."
next = "16"

[upgrade_the_saturday_market.16]
speaker = "adeline"
portrait = "sigh"
local = "But the Merchant's Guild has sent along... er, exacting requirements for the construction of their booths, which Mistria needs to cover."
next = "17"

[upgrade_the_saturday_market.17]
speaker = "nora"
portrait = "neutral"
local = "Let me see..."
next = "18"

[upgrade_the_saturday_market.18]
speaker = "nora"
portrait = "mad"
local = "$Gold Ingots$? For a market booth?!"
next = "19"

[upgrade_the_saturday_market.19]
speaker = "adeline"
portrait = "ugh"
local = "These numbers are unfortunately after I negotiated them down... they were even worse initially..."
next = "20"

[upgrade_the_saturday_market.20]
speaker = "nora"
portrait = "sad"
local = "There's enough in the Market coffers to take this down by another 20%, but even then it's outrageous."
next = "21"

[upgrade_the_saturday_market.21]
speaker = "adeline"
portrait = "sad"
local = "I suppose the Saturday Market doesn't need to have an upgrade this year... or this decade..."
prompts = [
	{ local = "If the Saturday Market needs a helping hand, it's got mine!", next = "22" },
	{ local = "If it'll get my old pal Wheedle back in town, count me in!", next = "23" },
]

[upgrade_the_saturday_market.22]
speaker = "adeline"
portrait = "happy"
local = "Oh, [Ari]! Thank you!"
next = "24"

[upgrade_the_saturday_market.23]
speaker = "adeline"
portrait = "think"
local = "I... I didn't know you and Wheedle were such good friends! In any case..."
next = "24"

[upgrade_the_saturday_market.24]
speaker = "adeline"
portrait = "neutral"
local = "We'll need $8 Gold Ingots$, $20 Obsidian$, $20 Crystal$, $100 Hard Wood$, and $50 Refined Stone$."
next = "25"

[upgrade_the_saturday_market.25]
speaker = "nora"
portrait = "happy"
local = "You're a lifesaver, [Ari]."
next = "26"

[upgrade_the_saturday_market.26]
speaker = "adeline"
portrait = "happy"
local = "I'll set up the $Donation Box$ outside the Manor House."
