# STEAM ACHIEVEMENTS

# 1 - Welcome to Mistria
[welcome_to_mistria]
	requirements.seen_cutscene = "day_zero"

# 2 - Don't You Love That Sense of Achievement?
[sense_of_achievement]
	requirements.repaired_dragon_shrine = true

# 3 - Becoming a Familiar Face
[familiar_face]
	requirements.completed_quest = "repair_the_bridge"

# 4 - Bridge Builder
[bridge_builder]
	requirements.completed_quest = "repair_the_bridge"

# 5 - Market Regular
[market_regular]
	requirements.completed_quest = "greet_the_vendors"

# 6 - Novice Farmer
[novice_farmer]
	requirements.completed_quest = "replenishing_mistrias_food_reserves_1"

# 7 - On That Grind
[on_that_grind]
	requirements.completed_quest = "repair_the_mill"

# 8 - Summit Scaler
[summit_scaler]
	requirements.completed_quest = "repair_the_summit_stairs"

# 9 - For the General Good
[for_the_general_good]
	requirements.completed_quest = "repair_the_general_store"

# 10 - A Bridge for Terithia
[a_bridge_for_terithia]
	requirements.completed_quest = "repair_the_beach_bridge"

# 11 - Novice Rancher
[novice_rancher]
	requirements.completed_quest = "replenishing_mistrias_food_reserves_2"

# 12 - Barnyard Bounty
[barnyard_bounty]
	requirements.completed_quest = "repair_haydens_barn"


# 13 - Horse-Hearted
[horse_hearted]
	requirements.seen_cutscene = "reveal_mistmare"


# 14 - Inn Good Company
[inn_good_company]
	requirements.completed_quest = "repair_the_inn"

# 15 - Refined
[refined]
	requirements.completed_quest = "stone_refinery"

# 16 - Good Marketing
[good_marketing]
	requirements.completed_quest = "upgrade_the_saturday_market"

# 17 - Fine Grained
[fine_grained]
	requirements.completed_quest = "upgrade_the_carpenters_shop"

# 18 - Hold Your A Plaza
[hold_your_a_plaza]
	requirements.completed_quest = "upgrade_the_saturday_market_plaza"

# 19 - Ringing Ovation
[ringing_ovation]
	requirements.completed_quest = "repair_the_bell_tower"

# 20 - Opened the Water Seal
[the_water_seal]
	requirements.completed_quest = "the_water_tablet"

# 21 - Opened the Earth Seal
[the_earth_seal]
	requirements.completed_quest = "the_earth_tablet"

# 22 - Opened the Fire Seal
[the_fire_seal]
	requirements.completed_quest = "breaking_the_fire_seal"

# 23 - Opened the Ruins Seal
[the_ruins_seal]
	requirements.completed_quest = "breaking_the_ruins_seal"

# 24 - Used the Magic Key
[used_the_magic_key]
	requirements.seen_cutscene = "priestess_quarters_pt_2"

# 25 - Opened the Final Seal
[the_final_seal]
	requirements.seen_cutscene = "dragon_tablet_pt_4"

# 26 - Love is in the Air
[love_is_in_the_air]
	requirements.or = [
		{ seen_cutscene = "shooting_star_adeline" },
		{ seen_cutscene = "shooting_star_balor" },
		{ seen_cutscene = "shooting_star_caldarus" },
		{ seen_cutscene = "shooting_star_celine" },
		{ seen_cutscene = "shooting_star_eiland" },
		{ seen_cutscene = "shooting_star_hayden" },
		{ seen_cutscene = "shooting_star_juniper" },
		{ seen_cutscene = "shooting_star_march" },
		{ seen_cutscene = "shooting_star_reina" },
		{ seen_cutscene = "shooting_star_ryis" },
		{ seen_cutscene = "shooting_star_seridia" },
		{ seen_cutscene = "shooting_star_valen" },
	]

# 27 - New Pet Owner
[new_pet_owner]
	requirements.seen_cutscene = "pet_arrival"

# 28 - Patron of the Arts
[patron_of_the_arts]
	requirements.or = [
		{ completed_museum_set_within = "flora" },
		{ completed_museum_set_within = "archaeology" },
		{ completed_museum_set_within = "insect" },
		{ completed_museum_set_within = "fish" },
	]

# 29 - Acquaintance
[acquaintance]
	requirements.or = [
		{ reached_heart_level = { celine = 2 } },
		{ reached_heart_level = { juniper = 2 } },
		{ reached_heart_level = { reina = 2 } },
		{ reached_heart_level = { valen = 2 } },
		{ reached_heart_level = { adeline = 2 } },
		{ reached_heart_level = { seridia = 2 } },
		{ reached_heart_level = { balor = 2 } },
		{ reached_heart_level = { march = 2 } },
		{ reached_heart_level = { hayden = 2 } },
		{ reached_heart_level = { ryis = 2 } },
		{ reached_heart_level = { eiland = 2 } },
		{ reached_heart_level = { caldarus = 2 } },
		{ reached_heart_level = { dell = 2 } },
		{ reached_heart_level = { elsie = 2 } },
		{ reached_heart_level = { errol = 2 } },
		{ reached_heart_level = { hemlock = 2 } },
		{ reached_heart_level = { holt = 2 } },
		{ reached_heart_level = { josephine = 2 } },
		{ reached_heart_level = { landen = 2 } },
		{ reached_heart_level = { luc = 2 } },
		{ reached_heart_level = { maple = 2 } },
		{ reached_heart_level = { nora = 2 } },
		{ reached_heart_level = { olric = 2 } },
		{ reached_heart_level = { terithia = 2 } },
	]

# 30 - Friend
[friend]
	requirements.or = [
		{ reached_heart_level = { celine = 4 } },
		{ reached_heart_level = { juniper = 4 } },
		{ reached_heart_level = { reina = 4 } },
		{ reached_heart_level = { valen = 4 } },
		{ reached_heart_level = { adeline = 4 } },
		{ reached_heart_level = { seridia = 4 } },
		{ reached_heart_level = { balor = 4 } },
		{ reached_heart_level = { march = 4 } },
		{ reached_heart_level = { hayden = 4 } },
		{ reached_heart_level = { ryis = 4 } },
		{ reached_heart_level = { eiland = 4 } },
		{ reached_heart_level = { caldarus = 4 } },
		{ reached_heart_level = { dell = 4 } },
		{ reached_heart_level = { elsie = 4 } },
		{ reached_heart_level = { errol = 4 } },
		{ reached_heart_level = { hemlock = 4 } },
		{ reached_heart_level = { holt = 4 } },
		{ reached_heart_level = { josephine = 4 } },
		{ reached_heart_level = { landen = 4 } },
		{ reached_heart_level = { luc = 4 } },
		{ reached_heart_level = { maple = 4 } },
		{ reached_heart_level = { nora = 4 } },
		{ reached_heart_level = { olric = 4 } },
		{ reached_heart_level = { terithia = 4 } },
	]

# 31 - Good Friend
[good_friend]
	requirements.or = [
		{ reached_heart_level = { celine = 6 } },
		{ reached_heart_level = { juniper = 6 } },
		{ reached_heart_level = { reina = 6 } },
		{ reached_heart_level = { valen = 6 } },
		{ reached_heart_level = { adeline = 6 } },
		{ reached_heart_level = { seridia = 6 } },
		{ reached_heart_level = { balor = 6 } },
		{ reached_heart_level = { march = 6 } },
		{ reached_heart_level = { hayden = 6 } },
		{ reached_heart_level = { ryis = 6 } },
		{ reached_heart_level = { eiland = 6 } },
		{ reached_heart_level = { caldarus = 6 } },
		{ reached_heart_level = { dell = 6 } },
		{ reached_heart_level = { elsie = 6 } },
		{ reached_heart_level = { errol = 6 } },
		{ reached_heart_level = { hemlock = 6 } },
		{ reached_heart_level = { holt = 6 } },
		{ reached_heart_level = { josephine = 6 } },
		{ reached_heart_level = { landen = 6 } },
		{ reached_heart_level = { luc = 6 } },
		{ reached_heart_level = { maple = 6 } },
		{ reached_heart_level = { nora = 6 } },
		{ reached_heart_level = { olric = 6 } },
		{ reached_heart_level = { terithia = 6 } },
	]

# 32 - Best Friend
[best_friend]
	requirements.has_best_friend = true

# 33 - Romantic
[romantic]
	requirements.has_partner = true

# 34 - True Love
[true_love]
	requirements.or = [
		{ reached_heart_level.adeline = 10, is_dating = "adeline" },
		{ reached_heart_level.balor = 10, is_dating = "balor" },
		{ reached_heart_level.caldarus = 10, is_dating = "caldarus" },
		{ reached_heart_level.celine = 10, is_dating = "celine" },
		{ reached_heart_level.eiland = 10, is_dating = "eiland" },
		{ reached_heart_level.hayden = 10, is_dating = "hayden" },
		{ reached_heart_level.juniper = 10, is_dating = "juniper" },
		{ reached_heart_level.march = 10, is_dating = "march" },
		{ reached_heart_level.reina = 10, is_dating = "reina" },
		{ reached_heart_level.ryis = 10, is_dating = "ryis" },
		{ reached_heart_level.seridia = 10, is_dating = "seridia" },
		{ reached_heart_level.valen = 10, is_dating = "valen" },
	]

# 35 - I Do
[i_do]
	requirements.has_spouse = true


# 36 - Parent
[parent]
	requirements.world_fact_is = { child_0_status = "infant" }

# 37 - Time Flies
[time_flies]
	requirements.has_child_at_age = 1

# 38 - New Friend
[new_friend]
	requirements.has_any_animal = true

# 39 - Perk Procurer
[perk_procurer]
	requirements.has_at_least_one_tier_five_perk_per_category = true

# 40 - Master Rancher
[master_rancher]
	requirements.has_animal_of_rank = 5

# 41 - The Found Woods
[the_found_woods]
	requirements.unlocked_deep_woods = true

# 42 - Stone Star Rank
[stone_star_rank]
	requirements.reached_renown_level = 10

# 43 - Copper Star Rank
[copper_star_rank]
	requirements.reached_renown_level = 20

# 44 - Ruby Star Rank
[ruby_star_rank]
	requirements.reached_renown_level = 30

# 45 - Iron Star Rank
[iron_star_rank]
	requirements.reached_renown_level = 40

# 46- Sapphire Star Rank
[sapphire_star_rank]
	requirements.reached_renown_level = 50

# 47 - Silver Star Rank
[silver_star_rank]
	requirements.reached_renown_level = 60

# 48 - Emerald Star Rank
[emerald_star_rank]
	requirements.reached_renown_level = 70

# 49 - Gold Star Rank
[gold_star_rank]
	requirements.reached_renown_level = 80

# 50 - Diamond Star Rank
[diamond_star_rank]
	requirements.reached_renown_level = 90

# 51 - Mistril Star Rank
[mistril_star_rank]
	requirements.reached_mistril_rank = true

# 52 - First Place
[first_place]
	requirements.or = [
		{ seen_cutscene = "spring_festival_first_place" },
		{ seen_cutscene = "harvest_festival_first_place" },
	]

# 53 - Gifted
[gifted]
	requirements.good_gifts_given = 100

# 54 - Happy Birthday
[happy_birthday]
	requirements.world_fact_is = [
		{ gave_adeline_good_birthday_gift = true },
		{ gave_balor_good_birthday_gift = true },
		{ gave_caldarus_good_birthday_gift = true },
		{ gave_celine_good_birthday_gift = true },
		{ gave_dell_good_birthday_gift = true },
		{ gave_dozy_good_birthday_gift = true },
		{ gave_eiland_good_birthday_gift = true },
		{ gave_elsie_good_birthday_gift = true },
		{ gave_errol_good_birthday_gift = true },
		{ gave_hayden_good_birthday_gift = true },
		{ gave_hemlock_good_birthday_gift = true },
		{ gave_henrietta_good_birthday_gift = true },
		{ gave_holt_good_birthday_gift = true },
		{ gave_josephine_good_birthday_gift = true },
		{ gave_juniper_good_birthday_gift = true },
		{ gave_landen_good_birthday_gift = true },
		{ gave_luc_good_birthday_gift = true },
		{ gave_maple_good_birthday_gift = true },
		{ gave_march_good_birthday_gift = true },
		{ gave_nora_good_birthday_gift = true },
		{ gave_olric_good_birthday_gift = true },
		{ gave_reina_good_birthday_gift = true },
		{ gave_ryis_good_birthday_gift = true },
		{ gave_seridia_good_birthday_gift = true },
		{ gave_terithia_good_birthday_gift = true },
		{ gave_valen_good_birthday_gift = true },
	]

# 55 - Master Chef
[master_chef]
	requirements.reached_skill_level.cooking = 60

# 56 - Master Woodcrafter
[master_woodcrafter]
	requirements.reached_skill_level.woodcrafting = 60

# 57 - Master Blacksmith
[master_blacksmith]
	requirements.reached_skill_level.blacksmithing = 60

# 58 - Entomologist
[entomologist]
	requirements.completed_museum_set = { wing = "insect", set = "legendary" }

# 59 - Fish Fanatic
[fish_fanatic]
	requirements.completed_museum_set = { wing = "fish", set = "legendary" }

# 60 - Hero
[hero]
	requirements.completed_quests_in_category = "stillwell_challenge"

# 61 - Master Farmer
[master_farmer]
	requirements.reached_skill_level.farming = 60

# 62 - Bread Winner
[bread_winner]
	requirements.earned_gold = 1000000

# 63 - Essential Essence
[essential_essence]
	requirements.reached_essence = 10000

# 64 - Jack of All Trades
[jack_of_all_trades]
	requirements.reached_skill_level = [
		{ "archaeology" = 60 },
		{ "blacksmithing" = 60 },
		{ "cooking" = 60 },
		{ "farming" = 60 },
		{ "fishing" = 60 },
		{ "ranching" = 60 },
		{ "woodcrafting" = 60 },
		{ "combat" = 60 },
		{ "mining" = 60 },
	]

# 65 - Go to Sleep Already
[go_to_sleep_already]
	requirements.world_fact_is.has_ever_fainted = true

# 66 - From a House to a Home
[house_to_home]
	requirements.has_upper_floor = true
	requirements.has_home_upgrade = "large_west_east"

# 67 - Thoughtful Gifter
[thoughtful_gifter]
	requirements.or = [
		{ all_npc_gifts_discovered = "adeline" },
		{ all_npc_gifts_discovered = "balor" },
		{ all_npc_gifts_discovered = "caldarus" },
		{ all_npc_gifts_discovered = "celine" },
		{ all_npc_gifts_discovered = "darcy" },
		{ all_npc_gifts_discovered = "dell" },
		{ all_npc_gifts_discovered = "dozy" },
		{ all_npc_gifts_discovered = "eiland" },
		{ all_npc_gifts_discovered = "elsie" },
		{ all_npc_gifts_discovered = "errol" },
		{ all_npc_gifts_discovered = "hayden" },
		{ all_npc_gifts_discovered = "hemlock" },
		{ all_npc_gifts_discovered = "henrietta" },
		{ all_npc_gifts_discovered = "holt" },
		{ all_npc_gifts_discovered = "josephine" },
		{ all_npc_gifts_discovered = "juniper" },
		{ all_npc_gifts_discovered = "landen" },
		{ all_npc_gifts_discovered = "louis" },
		{ all_npc_gifts_discovered = "luc" },
		{ all_npc_gifts_discovered = "maple" },
		{ all_npc_gifts_discovered = "march" },
		{ all_npc_gifts_discovered = "merri" },
		{ all_npc_gifts_discovered = "nora" },
		{ all_npc_gifts_discovered = "olric" },
		{ all_npc_gifts_discovered = "reina" },
		{ all_npc_gifts_discovered = "ryis" },
		{ all_npc_gifts_discovered = "seridia" },
		{ all_npc_gifts_discovered = "taliferro" },
		{ all_npc_gifts_discovered = "terithia" },
		{ all_npc_gifts_discovered = "valen" },
		{ all_npc_gifts_discovered = "vera" },
		{ all_npc_gifts_discovered = "wheedle" },
	]

# 68 - Close Call
[close_call]
	requirements.world_fact_is.slept_last_minute = true

# 69 - Celebrated Curator
[celebrated_curator]
	requirements.completed_museum = true
