adeline_status = "best_friend"
balor_status = "best_friend"
caldarus_status = "best_friend"
celine_status = "best_friend"
eiland_status = "best_friend"
hayden_status = "best_friend"
juniper_status = "spouse"
march_status = "best_friend"
reina_status = "best_friend"
ryis_status = "best_friend"
seridia_status = "best_friend"
valen_status = "best_friend"

spouse_can_carry_child = true

caldarus_home = true
caldarus_is_human = true
seridia_is_human = true
caldarus_seridia_town = true
dragon_market = "caldarus"

fnati = 4

read_pq_scroll = true
read_pq_tablet = true

# knocks out our wife's first couple lines
'Conversations/Bank/Juniper/Banked Lines/greeting_ari/greeting_ari' = true
'Conversations/Bank/Juniper/Banked Lines/week_one_pt_1/week_one_pt_1' = true
'Conversations/Bank/Juniper/Banked Lines/week_one_pt_2/week_one_pt_2' = true
'Conversations/Bank/Juniper/Relationship Lines/Relationship/post_8h_lines_romantic/juniper_post_8h_romantic_0' = true
