[votes]
	legendary = 3
	rare = 6
	uncommon = 9
	common = 12

[locations]
	narrows = "aldarian"
	eastern_road = "caldosian"
	haydens_farm = "alda"
	western_ruins = "ancient"
	beach = "prehistoric"
	deep_woods = "deep_woods"
	dungeon = "mine"
	farm = "vintage_farm_tools"

[loot]
	peat = "common"
	sod = "common"
	shards = "common"
	shard_mass = "common"
	clay = "common"

	# note: these are "sunken" so they only show up 5% of the time anyway
	rusted_shield = "common"
	rock_with_a_hole = "common"

	aldarian_sword = "uncommon"
	family_crest_pendant = "uncommon"
	caldosian_sword = "uncommon"
	caldosian_emperor_bust = "uncommon"
	alda_clay_pot = "uncommon"
	alda_feather_pendant = "uncommon"
	ancient_stone_lantern = "uncommon"
	ancient_gold_coin = "uncommon"
	dragon_scale = "uncommon"
	dragon_claw = "uncommon"
	trilobite_fossil = "uncommon"
	amber_trapped_insect = "uncommon"
	coin_lump = "uncommon"
	water_sphere = "uncommon"
	rainbow_seaweed = "uncommon"
	criminal_confession = "uncommon"
	petrified_wood = "uncommon"
	gathering_basket = "uncommon"
	rubber_fish = "uncommon"
	giant_fish_scale = "uncommon"

	aldarian_war_banner = "rare"
	aldarian_gauntlet = "rare"
	caldosian_breastplate = "rare"
	caldosian_drinking_horn = "rare"
	alda_mural_tablet = "rare"
	alda_bronze_sword = "rare"
	ancient_crystal_goblet = "rare"
	ancient_horn_circlet = "rare"
	hardened_essence = "rare"
	dragon_forged_bracelet = "rare"
	tiny_dinosaur_skeleton = "rare"
	fossilized_egg = "rare"
	rusted_treasure_chest = "rare"
	mermaids_comb = "rare"

	lost_crown_of_aldaria = "legendary"
	statuette_of_caldarus = "legendary"
	alda_gem_bracelet = "legendary"
	ancient_royal_scepter = "legendary"
	dragon_pact_tablet = "legendary"
	meteorite = "legendary"
	fossilized_mandrake_root = "legendary"
	crystal_apple = "legendary"
	metal_leaf = "legendary"

	# OOPARTs
	weightless_stone = "legendary"
	muttering_cube = "legendary"
	completely_wrong_map = "legendary"
	black_tablet = "legendary"
	unknown_dragon_statuette = "legendary"

	# Upper Mines
	miners_pickaxe = "common"
	tin_lunchbox = "common"
	miners_slab = "uncommon"
	miners_rucksack = "uncommon"
	miners_helmet = "rare"

	# Tide Caverns
	stone_shell = "common"
	starlight_coral = "common"
	tidestone = "uncommon"
	dense_water = "uncommon"
	crab_statue = "rare"

	# Deep Earth
	really_round_rock = "common"
	seriously_square_stone = "common"
	earth_infused_stone = "uncommon"
	faceted_rock_gem = "uncommon"
	rock_statue = "rare"

	# Lava Caves
	fire_crystal = "common"
	warm_rock = "common"
	red_obsidian = "uncommon"
	rainbow_geode = "uncommon"
	tiny_volcano = "rare"

	# Underground
	stone_horse = "uncommon"
	flint_arrowhead = "uncommon"
	obsidian_blade = "rare"
	diamond_backed_mirror = "rare"
	shortcut_scroll = "legendary"

	# Vintage Farm Tools
	vintage_watering_can = "uncommon"
	vintage_hammer = "uncommon"
	vintage_sickle = "uncommon"
	vintage_brush = "rare"
	vintage_cow_bell = "legendary"

	# Ritual
	ritual_incense_burner = "uncommon"
	ritual_beads = "uncommon"
	ritual_chalice = "uncommon"
	ritual_scepter = "rare"
	ritual_tablet = "rare"

	# Mist
	misty_black_mirror = "uncommon"
	misty_feather_quill = "uncommon"
	mist_crystal = "uncommon"
	mist_scroll = "rare"
	mist_flute = "rare"

	# Fish Trap
	clay_amphora = "common"
	sea_glass = "common"
	porcelain_figurine = "uncommon"
	worn_pendant = "rare"
	message_in_a_bottle = "legendary"
