[default]
	# The icon for this bark. If not provided, we will automatically try to find a sprite with the name
	# 'spr_ui_bark_icon_<NAME>'. If it fails, it'll panic.
	icon = "<n/a>"

	# The sound this bark plays. These ONLY play during cutscenes.
	sound = "<n/a>"

	# the opacity we lower down to. some barks look better at lower opacity because of their vibrancy
	opacity = 0.8

[angry]
	sound = "SoundEffects/Barks/BubbleAngry"

[annoyed]
	sound = "SoundEffects/Barks/BubbleAnnoyed"

[cute_face]
	sound = "SoundEffects/Barks/BubbleKittyFace"

[ellipses]

[exclamation_mark]
	sound = "SoundEffects/Barks/BubbleSurprised"

[heart]
	sound = "SoundEffects/Barks/BubbleHeart"

[plant_tonic]

[yum]

[hay]

[seed]

[breath_of_flame]

[smoke_moth]

[firesail]

[obsidian]

[breed_male]
	sound = "SoundEffects/Inventory/AnimalHeartTreat"

[breed_female]
	sound = "SoundEffects/Inventory/AnimalHeartTreat"

[empty_heart]

[hungry]

[question_mark]
	sound = "SoundEffects/Barks/BubbleQuestion"

[sweat_drop]
	sound = "SoundEffects/Barks/BubbleDrop"

[blush]
	sound = "SoundEffects/Barks/Bubble_o_o"

[farming]

[fishing]

[mining]

[archaeology]

[chicken]

[crafting]

[woodcrafting]

[cooking]

[spring]

[summer]

[fall]
	icon = "spr_ui_bark_icon_autumn"

[winter]

[celebration]

[cow]

[horse]

[beach]

[mountain]

[forest]

[lake]

[sunny]

[rainy]

[thunderstorm]

[snow]

[mist]

[heatwave]

[cherry_blossoms]

[coin]

[no_coin]

[book]

[gem]

[sleepy]

[fire]

[music]

[thread]

[moon]

[stars]

[bathhouse]

[hot_drink]

[cold_drink]

[crown]

[one]

[two]

[three]

[four]

[five]

[six]

[seven]

[eight]

[nine]

[adeline]
	icon = "spr_ui_generic_icon_npc_small_adeline"

[balor]
	icon = "spr_ui_generic_icon_npc_small_balor"

[caldarus]
	icon = "spr_ui_generic_icon_npc_small_caldarus"

[celine]
	icon = "spr_ui_generic_icon_npc_small_celine"

[darcy]
	icon = "spr_ui_generic_icon_npc_small_darcy"

[dell]
	icon = "spr_ui_generic_icon_npc_small_dell"

[dozy]
	icon = "spr_ui_generic_icon_npc_small_dozy"

[eiland]
	icon = "spr_ui_generic_icon_npc_small_eiland"

[elsie]
	icon = "spr_ui_generic_icon_npc_small_elsie"

[errol]
	icon = "spr_ui_generic_icon_npc_small_errol"

[hayden]
	icon = "spr_ui_generic_icon_npc_small_hayden"

[hemlock]
	icon = "spr_ui_generic_icon_npc_small_hemlock"

[henrietta]
	icon = "spr_ui_generic_icon_npc_small_henrietta"

[holt]
	icon = "spr_ui_generic_icon_npc_small_holt"

[josephine]
	icon = "spr_ui_generic_icon_npc_small_josephine"

[juniper]
	icon = "spr_ui_generic_icon_npc_small_juniper"

[landen]
	icon = "spr_ui_generic_icon_npc_small_landen"

[louis]
	icon = "spr_ui_generic_icon_npc_small_louis"

[luc]
	icon = "spr_ui_generic_icon_npc_small_luc"

[maple]
	icon = "spr_ui_generic_icon_npc_small_maple"

[march]
	icon = "spr_ui_generic_icon_npc_small_march"

[merri]
	icon = "spr_ui_generic_icon_npc_small_merri"

[nora]
	icon = "spr_ui_generic_icon_npc_small_nora"

[olric]
	icon = "spr_ui_generic_icon_npc_small_olric"

[priestess]
	icon = "spr_ui_generic_icon_npc_small_priestess"

[reina]
	icon = "spr_ui_generic_icon_npc_small_reina"

[ryis]
	icon = "spr_ui_generic_icon_npc_small_ryis"

[seridia]
    icon = "spr_ui_generic_icon_npc_small_seridia"

[stillwell]
	icon = "spr_ui_generic_icon_npc_small_stillwell"

[taliferro]
	icon = "spr_ui_generic_icon_npc_small_taliferro"

[terithia]
	icon = "spr_ui_generic_icon_npc_small_terithia"

[valen]
	icon = "spr_ui_generic_icon_npc_small_valen"

[vera]
	icon = "spr_ui_generic_icon_npc_small_vera"

[wheedle]
	icon = "spr_ui_generic_icon_npc_small_wheedle"

[zorel]
	icon = "spr_ui_generic_icon_npc_small_zorel"

[relationship_status]
	icon = "spr_ui_bark_icon_cute_face" # will change if its they're romantic

[fish_bait]