[default]
	name = "Default"
	icon = "spr_ui_icon_bell_resonator_default"
    sound = "SoundEffects/SpecialEvents/8pmBell"

[gothic]
	name = "Gothic"
	icon = "spr_ui_icon_bell_resonator_gothic"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellGoth"

[meow]
	name = "Meow"
	icon = "spr_ui_icon_bell_resonator_meow"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellMeow"

[moonlight]
	name = "Moonlight Through My Window"
	icon = "spr_ui_icon_bell_resonator_moonlight_through_my_window"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellMoonlight"

[nostalgic]
	name = "Nostalgic"
	icon = "spr_ui_icon_bell_resonator_nostalgic"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellWeddingBells"

[school_bell]
	name = "School Bell"
	icon = "spr_ui_icon_bell_resonator_school_bell"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellWestminsterQuarters"

[shaking_off_a_storm]
	name = "Shaking Off a Storm"
	icon = "spr_ui_icon_bell_resonator_shaking_off_a_storm"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellSummer"

[title_theme]
	name = "Title Theme"
	icon = "spr_ui_icon_bell_resonator_title_theme"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellTheme"

[tsukihotaru]
	name = "Tsukihotaru"
	icon = "spr_ui_icon_bell_resonator_tsukihotaru"
    sound = "SoundEffects/SpecialEvents/Alt8pmBells/8pmBellTsukihotaru"