[default]
	# the ignore counter is, in a weird way, how far they'll travel.
	# make this number bigger and they'll be more like to fly farther away.
	ignore_counter = 10

	# how fast they fly
	fly_speed = 1.3

	# every time they choose to fly, this is the change
	# that they exit the map instead (out of 100)
	go_to_heaven = 25

	# this is in seconds
	idle_time = [6, 8]

	# this is how many times to do the animation in a row
	look_number = [1, 1]
	sleep_number = [2, 4]

	# the votes per action
	votes.fly = 3
	votes.look = 1
	votes.sleep = 2

[black]

	[black.sprites]
		idle = "spr_wildanimal_bird_black_idle_east"
		look = "spr_wildanimal_bird_black_look_east"
		sleep = "spr_wildanimal_bird_black_sleep_east"
		fly.east = "spr_wildanimal_bird_black_fly_east"
		fly.north = "spr_wildanimal_bird_black_fly_east"
		fly.south = "spr_wildanimal_bird_black_fly_east"

[white]
	[white.sprites]
		idle = "spr_wildanimal_bird_white_idle_east"
		look = "spr_wildanimal_bird_white_look_east"
		sleep = "spr_wildanimal_bird_white_sleep_east"
		fly.east = "spr_wildanimal_bird_white_fly_east"
		fly.north = "spr_wildanimal_bird_white_fly_east"
		fly.south = "spr_wildanimal_bird_white_fly_east"

[brown]
	[brown.sprites]
		idle = "spr_wildanimal_bird_brown_idle_east"
		look = "spr_wildanimal_bird_brown_look_east"
		sleep = "spr_wildanimal_bird_brown_sleep_east"
		fly.east = "spr_wildanimal_bird_brown_fly_east"
		fly.north = "spr_wildanimal_bird_brown_fly_east"
		fly.south = "spr_wildanimal_bird_brown_fly_east"

[red_cardinal]
	[red_cardinal.sprites]
		idle = "spr_wildanimal_bird_red_cardinal_idle_east"
		look = "spr_wildanimal_bird_red_cardinal_look_east"
		sleep = "spr_wildanimal_bird_red_cardinal_sleep_east"
		fly.east = "spr_wildanimal_bird_red_cardinal_fly_east"
		fly.north = "spr_wildanimal_bird_red_cardinal_fly_east"
		fly.south = "spr_wildanimal_bird_red_cardinal_fly_east"

[grey_cardinal]
	[grey_cardinal.sprites]
		idle = "spr_wildanimal_bird_grey_cardinal_idle_east"
		look = "spr_wildanimal_bird_grey_cardinal_look_east"
		sleep = "spr_wildanimal_bird_grey_cardinal_sleep_east"
		fly.east = "spr_wildanimal_bird_grey_cardinal_fly_east"
		fly.north = "spr_wildanimal_bird_grey_cardinal_fly_east"
		fly.south = "spr_wildanimal_bird_grey_cardinal_fly_east"

[yellow]
	[yellow.sprites]
		idle = "spr_wildanimal_bird_yellow_idle_east"
		look = "spr_wildanimal_bird_yellow_look_east"
		sleep = "spr_wildanimal_bird_yellow_sleep_east"
		fly.east = "spr_wildanimal_bird_yellow_fly_east"
		fly.north = "spr_wildanimal_bird_yellow_fly_east"
		fly.south = "spr_wildanimal_bird_yellow_fly_east"

[blue]
	[blue.sprites]
		idle = "spr_wildanimal_bird_blue_idle_east"
		look = "spr_wildanimal_bird_blue_look_east"
		sleep = "spr_wildanimal_bird_blue_sleep_east"
		fly.east = "spr_wildanimal_bird_blue_fly_east"
		fly.north = "spr_wildanimal_bird_blue_fly_east"
		fly.south = "spr_wildanimal_bird_blue_fly_east"
