[legendary]
	chance = 0.05
	small_roll = [
		# { crafting_scroll = "chicken_statue" },
		# { crafting_scroll = "cow_statue" },
		# { crafting_scroll = "duck_statue" },
		# { crafting_scroll = "rabbit_statue" },
		# { crafting_scroll = "sheep_statue" },
	]
	large_roll = [
		# { crafting_scroll = "alpaca_statue" },
		# { crafting_scroll = "capybara_statue" },
		# { item = "golden_large_coop_blueprint" },
		# { item = "golden_large_coop_blueprint" },
	]

[rare]
	chance = 0.2
	small_roll = [
		# { cosmetic = "chicken_hat" },
		# { cosmetic = "chicken_wing_shirt" },
		# { cosmetic = "chicken_leg_pants" },
		# { cosmetic = "chicken_feet_shoes" },
		# { cosmetic = "cow_hat" },
		# { cosmetic = "cow_shirt" },
		# { cosmetic = "cow_pants" },
		# { cosmetic = "cow_shoes" },
	]
	large_roll = [
		# { crafting_scroll = "golden_fence" },
		# { cosmetic = "alpaca_hat" },
		# { cosmetic = "alpaca_shirt" },
		# { cosmetic = "alpaca_pants" },
		# { cosmetic = "alpaca_shoes" },
		# { cosmetic = "capybara_hat" },
		# { cosmetic = "capybara_shirt" },
		# { cosmetic = "capybara_pants" },
		# { cosmetic = "capybara_shoes" },
	]

[common]
	chance = 1
	small_roll = [
		{ purse = 200 },
		{ item = "egg", count = 3 },
		{ item = "cow_milk", count = 3 },
		{ item = "cheese", count = 2 },
		{ item = "butter", count = 2 },
		{ item = "mayonnaise", count = 2 },
		{ item = "golden_egg" },
		{ item = "golden_cow_milk" },
		{ item = "pudding" },
		{ item = "omelet" },
		{ item = "quiche" },
		{ item = "vegetable_quiche" },
		{ item = "quality_small_animal_feed", count = 10 },
		{ item = "quality_hay", count = 10 },
		{ item = "deluxe_small_animal_feed", count = 5 },
		{ item = "deluxe_hay", count = 5 },
		{ recipe_scroll = "pudding" },
		{ recipe_scroll = "omelet" },
		{ recipe_scroll = "deviled_eggs" },
		{ recipe_scroll = "quiche" },
		{ recipe_scroll = "vegetable_quiche" },
		{ animal = "chicken", animal_cosmetic = "business_tie" },
		{ animal = "chicken", animal_cosmetic = "pearl_necklace" },
		{ animal = "cow", animal_cosmetic = "halo" },
		{ animal = "cow", animal_cosmetic = "beret" },
		{ requires = { has_unlocked_animal = "horse" }, animal = "horse", animal_cosmetic = "crown" },
		{ requires = { has_unlocked_animal = "horse" }, animal = "horse", animal_cosmetic = "derby_hat" },
		{ requires = { has_unlocked_animal = "duck" }, animal = "duck", animal_cosmetic = "ruffled_collar" },
		{ requires = { has_unlocked_animal = "duck" }, animal = "duck", animal_cosmetic = "sun_hat" },
		{ requires = { has_unlocked_animal = "sheep" }, animal = "sheep", animal_cosmetic = "tartan_beret" },
		{ requires = { has_unlocked_animal = "sheep" }, animal = "sheep", animal_cosmetic = "unicorn_horn" },
		{ requires = { has_unlocked_animal = "rabbit" }, animal = "rabbit", animal_cosmetic = "halo" },
		{ requires = { has_unlocked_animal = "rabbit" }, animal = "rabbit", animal_cosmetic = "heart_clips" },
		{ requires = { has_unlocked_animal = "alpaca" }, animal = "alpaca", animal_cosmetic = "spiked_collar" },
		{ requires = { has_unlocked_animal = "alpaca" }, animal = "alpaca", animal_cosmetic = "gold_pendant" },
		{ requires = { has_unlocked_animal = "capybara" }, animal = "capybara", animal_cosmetic = "leaf" },
		{ requires = { has_unlocked_animal = "capybara" }, animal = "capybara", animal_cosmetic = "bowler_hat" },
		{ pet_cosmetic = "pink_bow" },
		{ pet_cosmetic = "black_bow" },
		{ pet_cosmetic = "blue_bow" },
		{ pet_cosmetic = "red_bow" },
		{ pet_cosmetic = "yellow_bow" },
		{ pet_cosmetic = "green_bow" },
		{ pet_cosmetic = "purple_bow" },
		{ pet_cosmetic = "flower_crown" },
		{ pet_cosmetic = "halo" },
		{ pet_cosmetic = "unicorn_horn" },
		{ pet_cosmetic = "sun_hat" },
	]
	large_roll = [
		{ purse = 2000 },
		{ item = "golden_cheese", count = 6 },
		{ item = "golden_butter", count = 6 },
		{ item = "golden_mayonnaise", count = 2 },
		{ item = "golden_egg", count = 12 },
		{ item = "golden_cow_milk", count = 12 },
		{ item = "golden_cookies", count = 2 },
		{ item = "golden_cheesecake", count = 2 },
		{ item = "ultimate_small_animal_feed", count = 10 },
		{ item = "ultimate_hay", count = 10 },
		# { item = "golden_fence", count = 10 },
	]
