[ellie]
	name = "Ellie"
    sex = "female"
	tone_threshold = 18

[sterling]
	name = "Sterling"
    sex = "male"
	tone_threshold = 12

[tephra]
	name = "Tephra"
    sex = "female"
	tone_threshold = 15

[rowan]
	name = "Rowan"
    sex = "male"
	tone_threshold = 12

[astrid]
	name = "Astrid"
    sex = "female"
	tone_threshold = 18

[wilder]
	name = "Wilder"
    sex = "male"
	tone_threshold = 12

[rune]
	name = "Rune"
    sex = "female"
	tone_threshold = 12

[fray]
	name = "Fray"
    sex = "female"
	tone_threshold = 12

[cedar]
	name = "Cedar"
    sex = "male"
	tone_threshold = 24

[kam]
	name = "Kam"
    sex = "male"
	tone_threshold = 24

[brid]
	name = "Brid"
    sex = "female"
	tone_threshold = 15

[torin]
	name = "Torin"
    sex = "male"
	tone_threshold = 12

# stork_offset = [0, 3]
# cradle_offset = [0, 8]