[default]
	icon = "spr_illegal_16"
	photo_title = "MISSING"
	photo_item = "<n/a>"
	name = "MISSING"
	description = "MISSING"
	cutscene = "<n/a>"
	unlock_sprite = "<n/a>"
	random_item_reward = []
	npc_visuals = {}
	unlisted = false

[inn_meal]
	name = "Inn Meal Date"
	photo_title = "Inn Meal with {}"
	description = "You can now invite your partner to the Inn for a Meal on the weekend!"
	icon = "spr_ui_item_date_inn_menu"
	photo_item = "date_photo_inn"
	unlock_sprite = "spr_ui_inn_date_unlock"
	cutscene = "inn_meal_date"
	random_item_reward = [
		"fried_rice",
		"seafood_snow_pea_noodles",
		"mushroom_steak_dinner",
		"perch_risotto",
		"sea_bream_rice",
		"vegetable_pot_pie",
		"braised_burdock",
		"crayfish_etouffee",
		"chickpea_curry",
		"cauliflower_curry",
		"deluxe_curry",
		"mushroom_rice",
		"rosemary_garlic_noodles",
		"apple_honey_curry",
		"chili_coconut_curry",
		"crab_cakes",
		"incredibly_hot_pot",
		"herb_butter_pasta",
		"monster_mash",
		"loaded_baked_potato",
		"quiche",
		"vegetable_quiche",
		"harvest_plate",
		"spring_galette",
		"cod_with_thyme",
		"pizza",
		"turnip_and_potato_gratin",
		"breaded_catfish",
		"spicy_corn",
		"horseradish_salmon",
		"omelet",
	]

	[inn_meal.npc_visuals]
		adeline = { expression = "blush", frame = 1 }
		balor = { expression = "happy_blush", frame = 0 }
		caldarus = { expression = "think_special", frame = 0 }
		celine = { expression = "blush", frame = 1 }
		eiland = { expression = "happy_blush", frame = 0 }
		hayden = { expression = "laugh_blush", frame = 0 }
		juniper = { expression = "blush", frame = 0 }
		march = { expression = "eight_heart_happy_blush", frame = 0 }
		reina = { expression = "blush_open_eyes", frame = 1 }
		ryis = { expression = "blush_special", frame = 0 }
		seridia = { expression = "happy_blush", frame = 0 }
		valen = { expression = "neutral_blush", frame = 1 }

[deep_woods_picnic]
	name = "Deep Woods Picnic"
	description = "You can now invite your partner to the Deep Woods for a picnic on the weekend!"
	photo_title = "Deep Woods Picnic with {}"
	icon = "spr_ui_item_date_picnic_set"
	photo_item = "date_photo_deep_woods"
	unlock_sprite = "spr_ui_deep_woods_picnic_date_unlock"
	cutscene = "deep_woods_picnic_date"
	random_item_reward = [
		"cherry_tart",
		"peaches_and_cream",
		"caldosian_chocolate_cake",
		"crystal_berry_pie",
		"sour_lemon_cake",
		"lemon_pie",
		"pomegranate_sorbet",
		"pumpkin_pie",
		"strawberry_shortcake",
		"wildberry_pie",
		"wildberry_scone",
		"wintergreen_ice_cream",
		"golden_cookies",
		"golden_cheesecake",
		"mont_blanc",
		"coconut_cream_pie",
		"glowberry_cookies",
		"ice_cream_sundae",
		"spell_fruit_parfait",
		"apple_pie",
		"sweet_potato_pie",
		"moon_fruit_cake",
		"cranberry_orange_scone",
		"monster_cookie",
		"poached_pear",
		"bell_berry_bakewell_tart",
	]
	[deep_woods_picnic.npc_visuals]
		adeline = { expression = "happy_blush", frame = 1 }
		balor = { expression = "blush", frame = 1 }
		caldarus = { expression = "laugh_special", frame = 1 }
		celine = { expression = "blush_closed_eyes", frame = 1 }
		eiland = { expression = "hope_special", frame = 0 }
		hayden = { expression = "confident_blush", frame = 0 }
		juniper = { expression = "happy_blush", frame = 1 }
		march = { expression = "drunk", frame = 0 }
		reina = { expression = "blush", frame = 1 }
		ryis = { expression = "happy_blush", frame = 1 }
		seridia = { expression = "blush_think", frame = 0 }
		valen = { expression = "happy_blush", frame = 0 }

[beach]
	name = "Beach Date"
	description = "You can now invite your partner to the Beach for a walk on the weekend!"
	photo_title = "Beach Date with {}"
	icon = "spr_ui_item_date_lovely_seashell"
	photo_item = "date_photo_beach"
	unlock_sprite = "spr_ui_beach_date_unlock"
	cutscene = "beach_date"
	random_item_reward = [
		"blue_conch_shell",
		"pink_scallop_shell",
		"sand_dollar",
		"spirula_shell",
	]
	[beach.npc_visuals]
		adeline = { expression = "blush", frame = 0 }
		balor = { expression = "wink", frame = 1 }
		caldarus = { expression = "embarrassed", frame = 1 }
		celine = { expression = "blush_closed_eyes", frame = 1 }
		eiland = { expression = "embarrassed", frame = 0 }
		hayden = { expression = "sweat", frame = 1 }
		juniper = { expression = "wink", frame = 1 }
		march = { expression = "eight_heart_happy", frame = 1 }
		reina = { expression = "wink", frame = 1 }
		ryis = { expression = "thoughtful_blush", frame = 1 }
		seridia = { expression = "wink", frame = 0 }
		valen = { expression = "think_blush", frame = 0 }

[park]
	name = "Park Date"
	description = "You can now invite your partner to the Eastern Road Park on the weekend!"
	photo_title = "Park Date with {}"
	icon = "spr_ui_item_date_dollhouse_bench"
	unlock_sprite = "spr_ui_park_date_unlock"
	photo_item = "date_photo_park"
	cutscene = "park_date"

	[park.npc_visuals]
		adeline = { expression = "blush", frame = 1 }
		balor = { expression = "happy_blush", frame = 0 }
		caldarus = { expression = "think_special", frame = 0 }
		celine = { expression = "blush", frame = 1 }
		eiland = { expression = "happy_blush", frame = 0 }
		hayden = { expression = "laugh_blush", frame = 0 }
		juniper = { expression = "blush", frame = 0 }
		march = { expression = "eight_heart_happy_blush", frame = 0 }
		reina = { expression = "blush_open_eyes", frame = 1 }
		ryis = { expression = "blush_special", frame = 0 }
		seridia = { expression = "embarrassed", frame = 0 }
		valen = { expression = "neutral_blush", frame = 1 }


[gem_cutting]
	name = "Gem Cutting Date"
	description = "You can now invite your partner to the forge to cut gems on the weekend!"
	photo_title = "Gem Cutting with {}"
	icon = "spr_ui_item_date_rough_gemstone"
	unlock_sprite = "spr_ui_gem_cutting_date_unlock"
	photo_item = "date_photo_gem_cutting"
	cutscene = "gem_cutting_date"
	random_item_reward = [
		"ore_ruby",
		"ore_sapphire",
		"ore_emerald",
		"ore_diamond",
		"ore_pink_diamond",
	]

	[gem_cutting.npc_visuals]
		adeline = { expression = "happy_blush", frame = 0 }
		balor = { expression = "blush", frame = 0 }
		caldarus = { expression = "laugh_special", frame = 0 }
		celine = { expression = "blush_closed_eyes", frame = 0 }
		eiland = { expression = "hope_special", frame = 1 }
		hayden = { expression = "confident_blush", frame = 1 }
		juniper = { expression = "happy_blush", frame = 0 }
		march = { expression = "drunk", frame = 0 }
		reina = { expression = "blush", frame = 0 }
		ryis = { expression = "happy_blush", frame = 0 }
		seridia = { expression = "sinister_blush", frame = 0 }
		valen = { expression = "happy_blush", frame = 0 }

[bathhouse]
	name = "Bathhouse Date"
	description = "You can now invite your partner to the Bathhouse on the weekend!"
	photo_title = "Bathhouse Date with {}"
	icon = "spr_ui_item_date_bath_soap"
	unlock_sprite = "spr_ui_bathhouse_date_unlock"
	photo_item = "date_photo_bath"
	cutscene = "bathhouse_date"

	[bathhouse.npc_visuals]
		adeline = { outfit = "beach", expression = "bath_neutral", frame = 1 }
		balor = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		caldarus = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		celine = { outfit = "beach", expression = "bath_neutral", frame = 1 }
		eiland = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		hayden = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		juniper = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		march = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		reina = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		ryis = { outfit = "beach", expression = "bath_neutral", frame = 0 }
		valen = { outfit = "beach", expression = "bath_neutral", frame = 1 }
		seridia = { outfit = "beach", expression = "bath_neutral", frame = 0 }

[shooting_star]
	name = "Shooting Star"
	photo_title = "Shooting Star Festival with {}"
	photo_item = "date_photo_shooting_star"
	cutscene = "shooting_star_romantic"
	unlisted = true

	[shooting_star.npc_visuals]
		adeline = { expression = "blush", frame = 1 }
		balor = { expression = "hope_special", frame = 0 }
		caldarus = { expression = "caring_special", frame = 0 }
		celine = { expression = "blush", frame = 1 }
		eiland = { expression = "hope_special", frame = 1 }
		hayden = { expression = "confident_blush", frame = 1 }
		juniper = { expression = "think_special", frame = 1 }
		march = { expression = "eight_heart_happy_blush", frame = 1 }
		reina = { expression = "blush_open_eyes", frame = 1 }
		ryis = { expression = "blush_special", frame = 0 }
		seridia = { expression = "blush", frame = 0 }
		valen = { expression = "caring_special", frame = 1 }


[wedding]
	name = "Wedding"
	photo_title = "Your Wedding With {}"
	photo_item = "date_photo_wedding"
	cutscene = "wedding"
	unlisted = true

	[wedding.npc_visuals]
		adeline = { outfit = "wedding", expression = "neutral", frame = 1 }
		balor = { outfit = "wedding", expression = "neutral", frame = 0 }
		caldarus = { outfit = "wedding", expression = "smile", frame = 0 }
		celine = { outfit = "wedding", expression = "neutral", frame = 1 }
		eiland = { outfit = "wedding", expression = "hope_special", frame = 0 }
		hayden = { outfit = "wedding", expression = "neutral", frame = 1 }
		juniper = { outfit = "wedding", expression = "neutral", frame = 1 }
		march = { outfit = "wedding", expression = "eight_heart_happy_blush", frame = 0 }
		reina = { outfit = "wedding", expression = "neutral", frame = 0 }
		ryis = { outfit = "wedding", expression = "blush_special", frame = 0 }
		seridia = { outfit = "wedding", expression = "neutral", frame = 0 }
		valen = { outfit = "wedding", expression = "happy_blush", frame = 1 }

[harvest_dance]
	name = "Harvest Dance"
	photo_title = "Harvest Date with {}"
	photo_item = "date_photo_harvest"
	cutscene = "harvest_festival_dance"
	unlisted = true

	[harvest_dance.npc_visuals]
		adeline = { expression = "blush", frame = 1 }
		balor = { expression = "hope_special", frame = 0 }
		caldarus = { expression = "caring_special", frame = 0 }
		celine = { expression = "blush", frame = 1 }
		eiland = { expression = "hope_special", frame = 1 }
		hayden = { expression = "confident_blush", frame = 1 }
		juniper = { expression = "think_special", frame = 1 }
		march = { expression = "eight_heart_happy_blush", frame = 1 }
		reina = { expression = "blush_open_eyes", frame = 1 }
		ryis = { expression = "blush_special", frame = 0 }
		seridia = { expression = "blush", frame = 0 }
		valen = { expression = "caring_special", frame = 1 }
