"town/exit to eastern road top" = "eastern_road/exit to town top"
"town/exit to eastern road bottom" = "eastern_road/exit to town bottom"
"town/exit to narrows top" = "narrows/exit to town top"
"town/exit to narrows bottom" = "narrows/exit to town bottom"
"town/bathhouse front door" = "bathhouse/exit to town"
"town/blacksmith front door" = "blacksmith_store/exit to town"
"town/celine's front door" = "celines_room/exit to town"
"town/clinic front door" = "clinic_f1/exit to town"
"town/general store front door" = "general_store_store/exit to town"
"town/inn front door" = "inn/exit to town"
"town/manor house front door" = "manor_house_entry/exit to town"
"bathhouse/bathhouse bedroom door" = "bathhouse_bedroom/bathhouse main room door"
"bathhouse/bathhouse changing room door" = "bathhouse_change_room/bathhouse main room door"
"town/bell tower" = "bell_tower_f1/exit to town"
"bell_tower_f1/bell tower f2" = "bell_tower_f2/bell tower f1"
"blacksmith_store/march's room door" = "blacksmith_room_left/blacksmith store door"
"blacksmith_store/olric's room door" = "blacksmith_room_right/blacksmith store door"
"clinic_f1/clinic b1 trap door" = "clinic_b1/clinic f1 stairs"
"clinic_f1/clinic f2 stairs" = "clinic_f2/clinic f1 stairs"
"general_store_store/general store home door" = "general_store_home/general store store door"
"general_store_home/dell's bedroom door" = "dells_bedroom/general store home door"
"general_store_home/holt and nora's bedroom door" = "holt_and_noras_bedroom/general store home door"
"town/mill front door" = "mill/exit to town"
"inn/balor's room door" = "balors_room/inn main room door"
"inn/jo and hemlock's room door" = "jo_and_hemlocks_room/inn main room door"
"inn/luc's room door" = "lucs_room/inn main room door"
"inn/maple's room door" = "maples_room/inn main room door"
"inn/reina's room door" = "reinas_room/inn main room door"
"manor_house_entry/adeline's office door" = "adelines_office/manor house main room door"
"manor_house_entry/eiland's office door" = "eilands_office/manor house main room door"
"manor_house_entry/dining hall door" = "manor_house_dining_room/manor house main room door"
"manor_house_entry/adeline's bedroom door" = "adelines_bedroom/manor house main room door"
"manor_house_entry/eiland's bedroom door" = "eilands_bedroom/manor house main room door"
"manor_house_entry/elsie's bedroom door" = "elsies_bedroom/manor house main room door"
"eastern_road/carpenter's shop front door" = "landens_house_f1/exit to eastern road"
"eastern_road/exit to deep woods" = "deep_woods/exit to eastern road"
"eastern_road/exit to aldaria" = "aldaria/exit to eastern road"
"landens_house_f1/carpenter's shop f2 stairs" = "landens_house_f2/carpenter's shop f1 stairs"
"narrows/exit to summit" = "summit/exit to narrows"
"narrows/exit to western ruins" = "western_ruins/exit to narrows"
"narrows/exit to hayden's farm" = "haydens_farm/exit to narrows"
"narrows/errol's door" = "errols_bedroom/exit to narrows"
"narrows/exit to mines entry" = "mines_entry/exit to narrows"
"narrows/museum front door" = "museum_entry/exit to museum front door"
"museum_entry/archaeology wing" = "museum_wing_archaeology/exit to museum entry"
"museum_entry/fish wing" = "museum_wing_fish/exit to museum entry"
"museum_entry/flora wing" = "museum_wing_flora/exit to museum entry"
"museum_entry/insect wing" = "museum_wing_insect/exit to museum entry"
"haydens_farm/hayden's front door" = "haydens_house/exit to hayden's farm"
"haydens_house/hayden's bedroom door" = "haydens_bedroom/hayden's main room door"
"haydens_farm/exit to beach" = "beach/exit to hayden's farm"
"beach/terithia's front door" = "terithias_house/exit to the beach"
"deep_woods/caldarus' front door" = "caldarus_house/exit to deep woods"
"deep_woods/exit to dragonsworn glade" = "dragonsworn_glade/exit to deep woods"
"dragonsworn_glade/exit to deep woods" = "deep_woods/exit to dragonsworn glade"
"mines_entry/exit to abandoned mines" = "abandoned_mines/exit to mines entry"
"abandoned_mines/exit to abandoned pit" = "abandoned_pit/exit to abandoned mines"
"seridias_house/exit to seridia's house back" = "seridias_house_back/exit to seridia's house"
"seridias_house_back/exit to seridia's house" = "seridias_house/exit to seridia's house back"
"seridias_house/exit to western ruins" = "western_ruins/exit to seridia's house"
