spr_exterior_lighting_three_panel_insert = "spr_exterior_lighting_three_panel_light"
spr_exterior_lighting_two_panel_insert = "spr_exterior_lighting_two_panel_light"
spr_town_building_generalstore_side_exterior_lights_inserts = "spr_town_building_generalstore_side_exterior_lights_light"
spr_exterior_lighting_general_store_insert = "spr_exterior_lighting_general_store_light"
spr_town_building_manor_exterior_lighting_insert_spring = "spr_town_building_manor_exterior_lighting_light_spring"
spr_town_building_manor_exterior_lighting_insert_winter = "spr_town_building_manor_exterior_lighting_light_winter"
spr_exterior_lighting_narrow_insert = "spr_exterior_lighting_narrow_light"
spr_town_building_mill_insert_on = "spr_town_building_mill_insert_on"
spr_narrows_building_errolcabin_insert = "spr_narrows_building_errolcabin_light"
spr_narrows_museum_exterior_lighting_insert_spring = "spr_narrows_museum_exterior_lighting_light_spring"
spr_narrows_museum_exterior_lighting_insert_winter = "spr_narrows_museum_exterior_lighting_light_winter"
spr_exterior_lighting_carpenter_insert = "spr_exterior_lighting_carpenter_light"
spr_exterior_lighting_player_home_insert = "spr_exterior_lighting_player_home_insert"
spr_exterior_lighting_adobe_home_bottom_insert = "spr_exterior_lighting_adobe_home_bottom_insert"
spr_exterior_lighting_adobe_home_top_insert = "spr_exterior_lighting_adobe_home_top_insert"
spr_exterior_lighting_leafy_cottage_insert = "spr_exterior_lighting_leafy_cottage_insert"
spr_exterior_lighting_timbered_home_bottom_insert = "spr_exterior_lighting_timbered_home_bottom_insert"
spr_exterior_lighting_timbered_home_middle_insert = "spr_exterior_lighting_timbered_home_middle_insert"
spr_exterior_lighting_timbered_home_top_insert = "spr_exterior_lighting_timbered_home_top_insert"
spr_exterior_lighting_victorian_home_bottom_insert = "spr_exterior_lighting_victorian_home_bottom_insert"
spr_exterior_lighting_victorian_home_middle_insert = "spr_exterior_lighting_victorian_home_middle_insert"
spr_exterior_lighting_victorian_home_top_insert = "spr_exterior_lighting_victorian_home_top_insert"
spr_town_building_bathhouse_exterior_lighting_insert_spring = "spr_town_building_bathhouse_exterior_lighting_light_spring"
spr_town_building_bathhouse_exterior_lighting_insert_winter = "spr_town_building_bathhouse_exterior_lighting_light_winter"
spr_exterior_lighting_bell_tower_insert = "spr_exterior_lighting_bell_tower_insert"
spr_deep_woods_caldarus_doorway_insert = "spr_deep_woods_caldarus_doorway_light"
