bite_times = [
	{ small = 35, medium = 35, large = 25, giant = 25, legendary = 18 },
	{ small = 38, medium = 38, large = 30, giant = 30, legendary = 20 },
	{ small = 40, medium = 40, large = 35, giant = 35, legendary = 22 },
	{ small = 42, medium = 42, large = 38, giant = 38, legendary = 25 },
	{ small = 45, medium = 45, large = 40, giant = 40, legendary = 30 },
	{ small = 48, medium = 48, large = 45, giant = 45, legendary = 35 },
]
[stamina_costs] #what we take from Ari
	giant_fish = 12
	large_fish = 12
	medium_fish = 12
	small_fish = 12
	dive_spots = 0

[votes]
	ultra_common = 300
	very_very_common = 225
	very_common = 150
	common = 75
	uncommon = 55
	rare = 40
	junk = 30
	wood_chest = 7
	copper_chest = 6
	silver_chest = 5
	gold_chest = 4
	artifact_fishing = 3
	artifact_divespots = 15

[essence_gains]
	giant_fish = 12
	large_fish = 9
	medium_fish = 6
	small_fish = 3
	dive_spot = 3
	legendary_multiplier = 2
	special_multiplier = 2

[chest_tables.wood]
	gold = [25, 100]
	items = [
		{ value = "canned_sardines", kind = "item" },
		{ value = "canned_sardines", kind = "recipe" },
		{ value = "pan_fried_snapper", kind = "item" },
		{ value = "pan_fried_snapper", kind = "recipe" },
		{ value = "seaweed", kind = "item" },
		{ value = "pan_fried_salmon", kind = "item" },
		{ value = "pan_fried_salmon", kind = "recipe" },
		{ value = "fish_skewer", kind = "item" },
		{ value = "fish_skewer", kind = "recipe" },
		{ value = "freshwater_oyster", kind = "item" },
		{ value = "smoked_trout_soup", kind = "item" },
		{ value = "crayfish_etouffee", kind = "item" },
		{ value = "crayfish_etouffee", kind = "recipe" },
		{ value = "ore_ruby", kind = "item" },
		{ value = "copper_ingot", kind = "item" },
		{ value = "iron_ingot", kind = "item" },
		{ value = "shard_mass", kind = "item" },
		{ value = "middlemist", kind = "item" },
		{ value = "seed_potato", kind = "item", count = 2 },
		{ value = "seed_strawberry", kind = "item", count = 2 },
		{ value = "seed_tomato", kind = "item", count = 2 },
		{ value = "seed_corn", kind = "item", count = 2 },
		{ value = "seed_broccoli", kind = "item", count = 2 },
		{ value = "seed_cranberry", kind = "item", count = 2 },
		{ value = "seed_cauliflower", kind = "item", count = 2 },
		{ value = "seed_snow_peas", kind = "item", count = 2 },
		{ value = "baked_potato", kind = "item" },
		{ value = "hard_boiled_egg", kind = "item" },
		{ value = "berries_and_cream", kind = "item" },
		{ value = "jam_sandwich", kind = "item" },
		{ value = "sliced_turnip", kind = "item" },
		{ value = "trail_mix", kind = "item" },
		{ value = "cow_milk", kind = "item" },
		{ value = "flour", kind = "item" },
		{ value = "sugar", kind = "item" },
		{ value = "rice", kind = "item" },
		{ value = "oil", kind = "item", count = 2 },
		{ value = "soy_sauce", kind = "item", count = 2 },
	]
	sprite = "spr_dungeon_mines_chest_wood_spring_closed"

[chest_tables.copper]
	gold = [100, 200]
	items = [
		{ value = "ore_sapphire", kind = "item" },
		{ value = "ore_emerald", kind = "item" },
		{ value = "copper_ingot", kind = "item", count = 2 },
		{ value = "iron_ingot", kind = "item" },
		{ value = "silver_ingot", kind = "item" },
		{ value = "shard_mass", kind = "item" },
		{ value = "hard_wood", kind = "item", count = 5 },
		{ value = "seed_cabbage", kind = "item", count = 4 },
		{ value = "seed_strawberry", kind = "item", count = 4 },
		{ value = "seed_watermelon", kind = "item", count = 4 },
		{ value = "seed_pumpkin", kind = "item", count = 4 },
		{ value = "seed_snow_peas", kind = "item", count = 4 },
		{ value = "fish_stew", kind = "item" },
		{ value = "fish_stew", kind = "recipe" },
		{ value = "mushroom_rice", kind = "item" },
		{ value = "latte", kind = "item" },
		{ value = "coffee", kind = "item" },
		{ value = "flour", kind = "item", count = 2 },
		{ value = "sugar", kind = "item", count = 2 },
		{ value = "rice", kind = "item", count = 2 },
		{ value = "oil", kind = "item", count = 4 },
		{ value = "soy_sauce", kind = "item", count = 4 },
	]
	sprite = "spr_dungeon_mines_chest_copper_spring_closed"

[chest_tables.silver]
	gold = [200, 300]
	items = [
		{ value = "ore_sapphire", kind = "item", count = 2 },
		{ value = "ore_emerald", kind = "item", count = 2 },
		{ value = "hard_wood", kind = "item", count = 10 },
		{ value = "copper_ingot", kind = "item", count = 5 },
		{ value = "iron_ingot", kind = "item", count = 2 },
		{ value = "silver_ingot", kind = "item" },
		{ value = "summer_salad", kind = "item" },
		{ value = "summer_salad", kind = "recipe" },
		{ value = "gazpacho", kind = "item" },
		{ value = "mocha", kind = "item" },
		{ value = "riceball", kind = "item" },
		{ value = "caldosian_chocolate_cake", kind = "item" },
		{ value = "flour", kind = "item", count = 4 },
		{ value = "sugar", kind = "item", count = 4 },
		{ value = "rice", kind = "item", count = 4 },
		{ value = "oil", kind = "item", count = 6 },
		{ value = "soy_sauce", kind = "item", count = 6 },
	]
	sprite = "spr_dungeon_mines_chest_silver_spring_closed"

[chest_tables.gold]
	gold = [300, 500]
	items = [
		{ value = "silver_ingot", kind = "item", count = 2 },
		{ value = "sushi_platter", kind = "item" },
		{ value = "sushi_platter", kind = "recipe" },
		{ value = "spicy_crab_sushi", kind = "item" },
		{ value = "spicy_crab_sushi", kind = "recipe" },
		{ value = "lobster_roll", kind = "item" },
		{ value = "lobster_roll", kind = "recipe" },
		{ value = "sesame_tuna_bowl", kind = "item" },
		{ value = "sesame_tuna_bowl", kind = "recipe" },
		{ value = "deluxe_curry", kind = "item" },
		{ value = "strawberry_shortcake", kind = "item" },
		{ value = "lemon_pie", kind = "item" },
		{ value = "flour", kind = "item", count = 8 },
		{ value = "sugar", kind = "item", count = 8 },
		{ value = "rice", kind = "item", count = 8 },
		{ value = "lobster_roll", kind = "item" },
		{ value = "lobster_roll", kind = "recipe" },
	]
	sprite = "spr_dungeon_mines_chest_gold_spring_closed"

[chest_tables.abyss]
	gold = [0, 0]
	items = [
		{ value = "cosmetic", cosmetic = "back_gear_ancient_witch_broom", kind = "cosmetic" },
		{ value = "cosmetic", cosmetic = "head_ancient_witch_tiara", kind = "cosmetic" },
		{ value = "cosmetic", cosmetic = "shoes_boots_ancient_witch", kind = "cosmetic" },
		{ value = "cosmetic", cosmetic = "top_ancient_witch", kind = "cosmetic" },
		{ value = "cosmetic", cosmetic = "skirt_ancient_witch", kind = "cosmetic" },
		{ value = "essence_stone_large", kind = "item" },
		{ value = "essence_stone_medium", kind = "item" },
		{ value = "essence_stone_small", kind = "item" },
		{ value = "essence_stone_tiny", kind = "item" },
	]
