# CELINE'S COTTAGE

[spr_celinecottage_desk_spring]
	flavor_text = "celine_desk"

[spr_celinecottage_fireplace_spring_off]
	flavor_text = "celine_fireplace"

[spr_celinecottage_table_1_spring]
	flavor_text = "celine_end_table"

[spr_celinecottage_shortwall_spring]
	flavor_text = "celine_plant_shelf"

	# GENERAL STORE HOME

[spr_generalstore_home_bookshelf_spring]
	flavor_text = "general_home_bookshelf"

[spr_generalstore_home_toys_spring]
	flavor_text = "general_home_dollhouse"

[spr_generalstore_home_workdesk_spring]
	flavor_text = "general_home_workbench"

	# GENERAL STORE STORE

[spr_generalstore_store_groceries2_broken_spring]
	flavor_text = "general_store_produce_a"

[spr_generalstore_store_groceries2_spring]
	flavor_text = "general_store_produce_fixed_a"

[spr_generalstore_store_groceries_broken_spring]
	flavor_text = "general_store_produce_b"

[spr_generalstore_store_groceries_spring]
	flavor_text = "general_store_produce_fixed_b"

[spr_generalstore_store_productshelves_broken_spring]
	flavor_text = "general_store_shelf_a_broken"

[spr_generalstore_store_productshelves_spring]
	flavor_text = "general_store_shelf_a_fixed"

[spr_generalstore_store_productshelves2_broken_spring]
	flavor_text = "general_store_shelf_b_broken"

[spr_generalstore_store_productshelves2_spring]
	flavor_text = "general_store_shelf_b_fixed"

	# GENERAL STORE DELL'S ROOM

[spr_generalstore_dell_blanketfort_spring]
	flavor_text = "general_store_dell_fort"

[spr_generalstore_dell_toytrunk_spring]
	flavor_text = "general_store_dell_toybox"

[spr_generalstore_dell_trunk_spring]
	flavor_text = "general_store_dell_shelves"

	# GENERAL STORE HOLT AND NORA'S ROOM

[spr_generalstore_holtnora_sideboard_spring]
	flavor_text = "general_store_holt_carvings"

[spr_generalstore_holtnora_bookshelf_spring]
	flavor_text = "general_store_nora_shelf"

[spr_generalstore_holtnora_nightstand_spring]
	flavor_text = "general_store_holt_journal"

	# INN MAIN

[spr_inn_barcounter_horizontal_spring]
	flavor_text = "inn_flower_pot"

[spr_inn_barcounter_horizontal_spring_broken]
	flavor_text = "inn_flower_pot"

[spr_inn_banner_spring]
	flavor_text = "inn_banner"

[spr_inn_liquorcabinet_horizontal_spring]
	flavor_text = "inn_cabinet"

[spr_inn_liquorcabinet_horizontal_spring_broken]
	flavor_text = "inn_cabinet"

[spr_inn_locked_door_flavor_text]
	flavor_text = "inn_locked_door"

	# BALOR'S ROOM

[spr_inn_balor_vanity_spring]
	flavor_text = "inn_balor_vanity"

[spr_inn_balor_crate2_spring]
	flavor_text = "inn_balor_crate"

[spr_inn_balor_deskandchair_spring]
	flavor_text = "inn_balor_lockbox"

	# HEMLOCK AND JO'S ROOM

[spr_inn_johemlock_lute_spring]
	flavor_text = "inn_hemlock_lute"

[spr_inn_johemlock_vanity_spring]
	flavor_text = "inn_hemlock_vanity"

[spr_inn_johemlock_vanity2_spring]
	flavor_text = "inn_jo_vanity"

	# LUC'S ROOM

[spr_inn_luc_bug_net_spring]
	flavor_text = "inn_luc_net"

[spr_inn_luc_dresser_spring]
	flavor_text = "inn_luc_terrarium"

[spr_inn_luc_desk_spring]
	flavor_text = "inn_luc_artwork"

	# MAPLE'S ROOM

[spr_inn_maple_desk_spring]
	flavor_text = "inn_maple_artwork"

[spr_inn_maple_dresser_spring]
	flavor_text = "inn_maple_plushies"

[spr_inn_maple_plush_bear_spring]
	flavor_text = "inn_maple_bear"

	# REINA'S ROOM

[spr_inn_reina_woodstove_spring]
	flavor_text = "inn_reina_stove"

[spr_inn_reina_bookshelf_spring]
	flavor_text = "inn_reina_shelf"

[spr_inn_reina_desk_spring]
	flavor_text = "inn_reina_book"

	# VALEN'S CLINIC FLOOR 1

[spr_valenclinic_f1_skeletonmodel_spring]
	flavor_text = "clinic_f1_skeleton"

[spr_valenclinic_f1_basement_hatch_spring_closed]
	flavor_text = "clinic_f1_trapdoor"

[spr_valenclinic_f1_stairsdesk_spring_top]
	flavor_text = "clinic_f1_desk"

	# VALEN'S CLINIC FLOOR 2

[spr_valenclinic_f2_bookshelf_spring]
	flavor_text = "clinic_f2_bookshelf"

[spr_valenclinic_f2_bigstool_spring]
	flavor_text = "clinic_f2_cactus"

[spr_valenclinic_f2_nightstand2_spring]
	flavor_text = "clinic_f2_diary"

	# BATHHOUSE MAIN

[spr_bathhouse_shelf_spring]
	flavor_text = "bathhouse_shelf_a"

[spr_bathhouse_shelf2_spring]
	flavor_text = "bathhouse_shelf_b"

[spr_bathhouse_shelf3_spring]
	flavor_text = "bathhouse_shelf_c"

[spr_bathhouse_locker_spring]
	flavor_text = "bathhouse_locker"

[spr_bathhouse_cauldron1_spring]
	flavor_text = "bathhouse_cauldron"

	# BATHHOUSE JUNIPER'S BEDROOM

[spr_bathhouse_juniper_potionshelf_spring]
	flavor_text = "bathhouse_bedroom_potion_shelf"

[spr_bathhouse_juniper_cauldron2_spring]
	flavor_text = "bathhouse_bedroom_cauldron"

[spr_bathhouse_juniper_desk_spring]
	flavor_text = "bathhouse_bedroom_desk"

[spr_bathhouse_juniper_table_spring]
	flavor_text = "bathhouse_bedroom_crystal_ball"

	# BATHHOUSE CHANGING ROOM

[spr_bathhouse_changeroom_fountain_spring]
	flavor_text = "bathhouse_changing_fountain"

[spr_bathhouse_changeroom_cubbycabinet_spring]
	flavor_text = "bathhouse_changing_cubbies"

[spr_bathhouse_changeroom_door_flavor_text]
	flavor_text = "bathhouse_changing_door"

	# BLACKSMITHS MAIN

[spr_blacksmith_desk_spring]
	flavor_text = "blacksmiths_display"

[spr_blacksmith_table_spring]
	flavor_text = "blacksmiths_workbench"

	# BLACKSMITHS MARCH'S ROOM

[spr_blacksmith_bookshelf_spring]
	flavor_text = "blacksmiths_march_trophy_shelf"

[spr_blacksmith_sidetable_spring]
	flavor_text = "blacksmiths_march_plant"

[spr_blacksmith_chest_spring]
	flavor_text = "blacksmiths_march_trunk"

	# BLACKSMITHS OLRIC'S ROOM

[spr_blacksmith_table2_spring]
	flavor_text = "blacksmiths_olric_desk"

[spr_blacksmith_shelf_spring]
	flavor_text = "blacksmiths_olric_shelf_left"

[spr_blacksmith_shelf2_spring]
	flavor_text = "blacksmiths_olric_shelf_right"

	# MANOR HOUSE MAIN

[spr_manor_bookshelf_spring]
	flavor_text = "manor_adline_bookshelf"

[spr_manor_vase_spring]
	flavor_text = "manor_pottery"

[spr_manor_bookstand_spring]
	flavor_text = "manor_lectern"

[spr_manor_bookshelf2_spring]
	flavor_text = "manor_eiland_bookshelf"

	# MANOR HOUSE DINING ROOM

[spr_manor_dining_fireplace_spring_on]
	flavor_text = "manor_dining_portrait"

[spr_manor_dining_room_door_flavor_text]
	flavor_text = "manor_dining_door"

	# MANOR HOUSE ADELINE'S OFFICE

[spr_manor_adeline_office_bookshelf_spring]
	flavor_text = "manor_adeline_office_left_bookshelf"

[spr_manor_adeline_office_wallstonks_spring]
	flavor_text = "manor_adeline_office_chart"

[spr_manor_adeline_office_bookshelf2_spring]
	flavor_text = "manor_adeline_office_right_bookshelf"

	# MANOR HOUSE EILAND'S OFFICE

[spr_manor_eiland_office_shelf_spring]
	flavor_text = "manor_eiland_office_left_bookshelf"

[spr_manor_eiland_office_shelf2_spring]
	flavor_text = "manor_eiland_office_right_bookshelf"

[spr_manor_eiland_office_horse_statue_spring]
	flavor_text = "manor_eiland_office_pony"

	# MANOR ADELINE'S BEDROOM

[spr_manor_adeline_room_shelf_spring]
	flavor_text = "manor_adeline_bedroom_bookshelf"

[spr_manor_adeline_room_plantstand_spring]
	flavor_text = "manor_adeline_bedroom_plants"

[spr_manor_adeline_room_vanity_spring]
	flavor_text = "manor_adeline_bedroom_vanity"

[spr_manor_adeline_room_dresser_spring]
	flavor_text = "manor_adeline_bedroom_wardrobe"

	# MANOR EILAND'S BEDROOM

[spr_manor_eiland_room_wideshelf_spring]
	flavor_text = "manor_eiland_bedroom_bookshelf"

[spr_manor_eiland_room_book_stack2_spring]
	flavor_text = "manor_eiland_bedroom_books"

[spr_manor_eiland_room_tallshelf_spring]
	flavor_text = "manor_eiland_bedroom_candy"

	# MANOR ELSIE'S BEDROOM

[spr_manor_elsie_room_bookshelf2_spring]
	flavor_text = "manor_elsie_bedroom_bookshelf_left"

[spr_manor_elsie_room_bookshelf_spring]
	flavor_text = "manor_elsie_bedroom_bookshelf_right"

[spr_manor_elsie_room_wardrobe_spring]
	flavor_text = "manor_elsie_bedroom_wardrobe"

	# CARPENTERS SHOP FIRST FLOOR

[spr_carpenter_house_f1_wall_spring]
	flavor_text = "carpenters_birdhouses"

[spr_carpenter_house_f1_walltools_spring]
	flavor_text = "carpenters_tools"

[spr_carpenter_house_f1_worktable_spring]
	flavor_text = "carpenters_worktable"

	# CARPENTERS SHOP SECOND FLOOR

[spr_carpenter_house_f2_bookshelf_spring]
	flavor_text = "carpenters_f2_bookshelf"

[spr_carpenter_house_f2_desk1_spring]
	flavor_text = "carpenters_f2_ryis_desk"

[spr_carpenter_house_f2_desk2_spring]
	flavor_text = "carpenters_f2_landen_desk"

[spr_carpenter_house_f2_chest_spring]
	flavor_text = "carpenters_f2_ryis_trunk"

	# ERROL'S COTTAGE

[spr_errol_room_bookcase_spring]
	flavor_text = "errol_bookshelf"

[spr_errol_room_desk_spring]
	flavor_text = "errol_desk"

[spr_errol_room_toolbox_spring]
	flavor_text = "errol_toolbox"

	# MUSEUM ENTRY

[spr_museum_entryhall_velvet_rope_vertical_spring]
	flavor_text = "museum_rope_side"

[spr_museum_entryhall_velvet_rope_horizontal_spring]
	flavor_text = "museum_rope_front"

	# TERITHIA'S HOUSE

[spr_terithia_house_fish_rack_spring]
	flavor_text = "terithias_dried_fish"

[spr_terithia_house_wall_fish_net_spring]
	flavor_text = "terithias_wall_fish"

[spr_terithia_house_shelf_spring]
	flavor_text = "terithias_shelf"

	# HAYDEN'S HOUSE MAIN

[spr_hayden_doorway_spring]
	flavor_text = "haydens_wall_art"

[spr_hayden_shelf_spring]
	flavor_text = "haydens_shelf"

	# HAYDEN'S ROOM

[spr_hayden_bedroom_chickenbasket_spring]
	flavor_text = "haydens_statue"

[spr_hayden_bedroom_nightstand_spring_on]
	flavor_text = "haydens_nightstand"

[spr_hayden_bedroom_trunk_spring]
	flavor_text = "haydens_trunk"

	# TOWN EXTERIOR

[spr_town_building_clinic_door2_spring_locked]
	flavor_text = "clinic_door_locked"

[spr_town_mockup_door_boarded_up_spring]
	flavor_text = "clinic_shed_door_boarded"

[spr_town_building_mill_door_spring_locked]
	flavor_text = "mill_door_boarded"

[spr_town_stele_spring_default]
	flavor_text = "manor_stele"

[spr_town_stele_winter_default]
	flavor_text = "manor_stele_winter"

[spr_town_planter_rustic_medium_spring]
	flavor_text = "spring_flower_planter"

[spr_town_fountain_spring]
	flavor_text = "town_fountain"

	# NARROWS EXTERIOR

[spr_narrows_mines_entrance_door_spring]
	flavor_text = "mines_door_boarded"

[spr_narrows_gryphon_statue_v1_spring]
	flavor_text = "narrows_gryphon_statue_a"
	override_mask = "spr_narrows_gryphon_statue_mask"

[spr_narrows_gryphon_statue_v2_spring]
	flavor_text = "narrows_gryphon_statue_b"
	override_mask = "spr_narrows_gryphon_statue_mask"

[spr_narrows_gryphon_statue_v3_spring]
	flavor_text = "narrows_gryphon_statue_c"
	override_mask = "spr_narrows_gryphon_statue_mask"

[spr_narrows_stairs_broken_spring]
	flavor_text = "narrows_broken_stairs"

[spr_narrows_cave_entrance_spring_top]
	flavor_text = "narrows_cave"

	# WESTERN RUINS EXTERIOR

[spr_westernruins_stairs_upper_broken_spring]
	flavor_text = "western_ruins_stairs_broken"

[spr_westernruins_tools_spring]
	flavor_text = "western_ruins_tools_ground"

[spr_westernruins_bucket_v3_spring]
	flavor_text = "western_ruins_tools_pit"

	# EASTERN ROAD

[spr_easternroad_stairs_broken_spring]
	flavor_text = "eastern_road_stairs_broken_spring"

[spr_easternroad_stairs_broken_summer]
	flavor_text = "eastern_road_stairs_broken_summer"

[spr_easternroad_stairs_broken_fall]
	flavor_text = "eastern_road_stairs_broken_fall"

[spr_easternroad_stairs_winter]
	flavor_text = "eastern_road_stairs_broken_winter"

	# BEACH

[spr_beach_lighthouse_door_spring_locked]
	flavor_text = "lighthouse_door"

[spr_beach_sandcastle_spring]
	flavor_text = "sand_castle"

	# MINES ENTRY

[spr_narrows_mines_entry_cave_main_sealed]
	flavor_text = "mines_blocked_door"

[spr_narrows_mines_entry_cave_main_re_sealed]
	flavor_text = "mines_re_sealed_door"

	# HAYDEN'S FARM EXTERIOR

[spr_haydens_farm_seesaw_spring]
	flavor_text = "haydens_farm_seesaw"

[spr_haydens_farm_barn_spring]
	flavor_text = "haydens_small_barn"

[spr_haydens_farm_coop_spring]
	flavor_text = "haydens_small_coop"

	# CALDARUS' HOUSE

[spr_caldarus_house_chest_flavor_text]
	flavor_text = "caldarus_clothing_chest"

[spr_caldarus_house_wall_spring]
	flavor_text = "caldarus_scroll_closet"

[spr_caldarus_house_desk_spring]
	flavor_text = "caldarus_desk"
	alternative.flavor_text = "caldarus_desk_alt"
	alternative.requirements.has_void_sight = true

[spr_caldarus_house_fire_spring]
	flavor_text = "caldarus_hearth"

	#DEEP WOODS GRAVEYARD

[spr_deep_woods_stones]
	flavor_text = "cairn"

[spr_deep_woods_grave_b]
	flavor_text = "grave_b"

[spr_deep_woods_grave_c]
	flavor_text = "grave_c"

[spr_deep_woods_grave_e]
	flavor_text = "grave_e"

[spr_deep_woods_grave_f]
	flavor_text = "grave_f"

[spr_deep_woods_grave_g]
	flavor_text = "grave_g"

[spr_deep_woods_priestess_statue]
	flavor_text = "priestess_statue"

	# Dragonsworn's Glade

[spr_deep_woods_fir_tree_giant_spring]
	flavor_text = "glade_tree"

[spr_deep_woods_fir_tree_giant_summer]
	flavor_text = "glade_tree_fall"

[spr_deep_woods_fir_tree_giant_autumn]
	flavor_text = "glade_tree_fall"

[spr_deep_woods_fir_tree_giant_winter]
	flavor_text = "glade_tree_winter"

[spr_dragonsworn_glade_storage_chest_spring_opened]
	flavor_text = "glade_treasure"

[spr_dragonsworn_glade_storage_chest_spring_closed]
	flavor_text = "glade_treasure_b"

[spr_dragonsworn_glade_storage_chest_winter_opened]
	flavor_text = "glade_treasure_winter"

[spr_dragonsworn_glade_storage_chest_winter_closed]
	flavor_text = "glade_treasure_winter_b"

[spr_glade_flowers]
	flavor_text = "glade_flowers"

	# PRIESTESS' QUARTERS

[spr_priestess_quarters_bed_1_main]
	flavor_text = "priestess_quarters_bed"
	highlight = true

[spr_priestess_quarters_bed_2_main]
	flavor_text = "priestess_quarters_bed"
	highlight = true

[spr_priestess_quarters_bed_3_main]
	flavor_text = "priestess_quarters_bed"
	highlight = true

[spr_priestess_quarters_bedroom_shelf_left_main]
	flavor_text = "priestess_quarters_bedroom_shelf_left"
	highlight = true

[spr_priestess_quarters_workbench_1_main]
	flavor_text = "pq_northwest_workbench"
	highlight = true

[spr_priestess_quarters_workbench_4_main]
	flavor_text = "pq_southeast_workbench"
	highlight = true

	#FLOOR 100

[spr_seridias_chamber_door_barrier]
	flavor_text = "floor_100_barrier"
	highlight = true

[spr_seridias_house_crafting_station_main]
	flavor_text = "seridias_fire"
	highlight = true

	# Seridias House

[spr_seridias_house_wall_main]
	flavor_text = "serdias_shelves"

[spr_seridias_house_coin_stacks_left]
	flavor_text = "treasure_hoard_left"

[spr_seridias_house_coin_stacks_right]
	flavor_text = "treasure_hoard_right"


	#[spr_name]
	#	flavor_text = "name"
