[grass]
	walk_sound = "SoundEffects/Ari/Footsteps/GrassyFeet"
	run_sound = "SoundEffects/Ari/Footsteps/GrassyFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkGrass"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontGrass"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackGrass"

[dark_grass]
	walk_sound = "SoundEffects/Ari/Footsteps/GrassyLongFeet"
	run_sound = "SoundEffects/Ari/Footsteps/GrassyLongFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkGrass"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontGrass"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackGrass"

[dirt]
	walk_sound = "SoundEffects/Ari/Footsteps/DirtFeet"
	run_sound = "SoundEffects/Ari/Footsteps/DirtFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkDirt"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontDirt"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackDirt"

[soil]
	walk_sound = "SoundEffects/Ari/Footsteps/DirtFeet"
	run_sound = "SoundEffects/Ari/Footsteps/DirtFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkDirt"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontDirt"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackDirt"

[mud]
	walk_sound = "SoundEffects/Ari/Footsteps/MudFeet"
	run_sound = "SoundEffects/Ari/Footsteps/MudFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkMud"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontMud"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackMud"

	particle_sprites.horizontal = "spr_part_soil_footstep_horizontal_spring"
	particle_sprites.vertical = "spr_part_soil_footstep_vertical_spring"
	winter_particle_sprites.horizontal = "spr_part_soil_footstep_horizontal_winter"
	winter_particle_sprites.vertical = "spr_part_soil_footstep_vertical_winter"

[carpet]
	walk_sound = "SoundEffects/Ari/Footsteps/CarpetFeet"
	run_sound = "SoundEffects/Ari/Footsteps/CarpetFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkCarpet"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontCarpet"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackCarpet"

[stone]
	walk_sound = "SoundEffects/Ari/Footsteps/StoneFeet"
	run_sound = "SoundEffects/Ari/Footsteps/StoneFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkStone"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontStone"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackStone"

[wood]
	walk_sound = "SoundEffects/Ari/Footsteps/WoodFeet"
	run_sound = "SoundEffects/Ari/Footsteps/WoodFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkWood"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontWood"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackWood"

[sand]
	walk_sound = "SoundEffects/Ari/Footsteps/SnowFeet"
	run_sound = "SoundEffects/Ari/Footsteps/SnowFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkSand"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontSand"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackSand"

	particle_sprites.horizontal = "spr_part_sand_footstep_horizontal_spring"
	particle_sprites.vertical = "spr_part_sand_footstep_vertical_spring"
	winter_particle_sprites.horizontal = "spr_part_sand_footstep_horizontal_winter"
	winter_particle_sprites.vertical = "spr_part_sand_footstep_vertical_winter"

[water]
	walk_sound = "SoundEffects/Ari/Footsteps/ShallowWaterFeet"
	run_sound = "SoundEffects/Ari/Footsteps/ShallowWaterFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkShallowWater"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontShallowWater"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackShallowWater"

[snow]
	walk_sound = "SoundEffects/Ari/Footsteps/SnowFeet"
	run_sound = "SoundEffects/Ari/Footsteps/SnowFeetRun"

	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkSnow"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontSnow"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackSnow"

	winter_particle_sprites.horizontal = "spr_part_snow_footstep_horizontal"
	winter_particle_sprites.vertical = "spr_part_snow_footstep_vertical"

[void]
	walk_sound = "SoundEffects/Ari/Footsteps/VoidFeet"
	run_sound = "SoundEffects/Ari/Footsteps/VoidFeetRun"

	# don't matter
	mount_walk_sound = "SoundEffects/Animals/HorseFootsteps/HorseFootstepWalkWood"
	mount_run_sound_front = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopFrontWood"
	mount_run_sound_back = "SoundEffects/Animals/HorseFootsteps/HorseFootstepGallopBackWood"
