# all these sand_forageables are placed in the *common* category
# with a sand condition placed on them.
sand_forageables = [
	"blue_conch_shell",
	"sand_dollar",
	"spirula_shell",
	"pink_scallop_shell",
]

[votes]
	legendary = 3
	rare = 6
	uncommon = 9
	common = 12

[spring]
	common = ["daffodil", "dandelion", "fennel", "tulip", "chickpea", "lilac", "wild_leek"]
	uncommon = []
	rare = ["snowdrop_anemone", "fiddlehead", "morel_mushroom", "nettle"]
	legendary = ["middlemist"]

[winter]
	common = ["frost_lily", "poinsettia", "burdock_root", "jasmine", "crocus", "holly", "ice_block"]
	uncommon = []
	rare = ["snapdragon", "pineshroom", "oyster_mushroom"]
	legendary = []

[summer]
	common = ["daisy", "iris", "catmint", "cosmos"]
	uncommon = []
	rare = ["marigold", "sage", "basil", "thyme", "oregano", "dill", "sesame", "night_queen"]
	legendary = []

[fall]
	common = ["heather", "horseradish", "chestnut"]
	uncommon = []
	rare = ["moon_fruit", "rosemary", "garlic", "viola", "fog_orchid"]
	legendary = []
