# these are the crops, and the order they'll go in (each stage will be reflected)
# these names reflect crops in `crop.toml`
crops.spring = [
	"daffodil",
	"tulip",
	"snowdrop_anemone",
	"lilac",
	"potato",
	"turnip",
	"cabbage",
	"strawberry",
	"carrot",
	"peas",
	"chickpea",
	"temple_flower",
	"mystery_bag",
]

crops.summer = [
	'basil',
	'catmint',
	'chili_pepper',
	'corn',
	'cosmos',
	'cucumber',
	'daisy',
	'dill',
	'iris',
	'marigold',
	"mystery_bag",
	'night_queen',
	'oregano',
	'sage',
	'sugar_cane',
	'sunflower',
	'tea',
	"temple_flower",
	'thyme',
	'tomato',
	'watermelon',
]

crops.fall = [
	'broccoli',
	'celosia',
	'chrysanthemum',
	'cranberry',
	'garlic',
	'heather',
	'moon_fruit',
	"mystery_bag",
	'onion',
	'pumpkin',
	'rice',
	'rosemary',
	'sweet_potato',
	"temple_flower",
	'viola',
	'wheat',
]

crops.winter = [
	'beet',
	'burdock_root',
	'cauliflower',
	'daikon_radish',
	'frost_lily',
	'jasmine',
	"mystery_bag",
	'poinsettia',
	'snapdragon',
	'snow_peas',
	"temple_flower",
]

# the coordinates where we write out all this stuff
area_top_left = [70, 42]
area_bottom_right = [124, 108]

# this is the y coordinate upon which we start drawing trees. we obey the x coordinate
# right-hand side limit from `area_bottom_right`
tree_start = 70

# tree ids to correspond with trees in `tree.toml`
trees = [
	"tree_apple",
	"tree_cherry",
	"tree_lemon",
	"tree_peach",
	"tree_pear",
	"tree_pomegranate",
	"tree_orange",
]

# the barn and coops aren't represented here, but might be one day if they cause problems.
