# this exists for the room sniffer and is a very ridiculous file
# basically designed for speed.

# we check this in the test suite to make sure it's accurate to the game
tile_rule_to_tile_flag = [
	["none"],
	["placeable", "wilderness"],
	["placeable"],
	["chicken_feed"],
	["hay"],
	["forageable", "placeable"],
	["placeable_wall"],
	["river"],
	["lake"],
	["pond"],
	["ocean"],
	["river_no_dive_spot"],
	["npc_farm", "resists_reset"],
	["dig_site"],
	["dig_site_special"],
	["resists_reset"],
	["unbreakable", "placeable"],
	["grass_seed", "placeable"],
]

tile_flag_order = [
	"none",
	"placeable",
	"wilderness",
	"soil",
	"grass",
	"chicken_feed",
	"hay",
	"free_of_collisions",
	"free_of_any_object",
	"forageable",
	"placeable_wall",
	"free_of_non_surface_object",
	"river",
	"lake",
	"pond",
	"ocean",
	"river_no_dive_spot",
	"npc_farm",
	"dig_site",
	"dig_site_special",
	"resists_reset",
	"unbreakable",
	"grass_seed",
]
