bark_alpha = 0.75
max_radius = 12
detection_radius = 128
nudge_distance = 6
bounce_period = 32
standard_interaction_distance = 32
standard_bark_fade_speed = 0.10
forge_offset = [0, -16]
woodcrafting_offset = [12, -10]
milling_offset = [0, -1]
refining_offset = [10, -27]
stable_crafting_offset = [0, -14]
inn_kitchen_offset = [12, -20]
beginner_kitchen_offset = [0, -28]
mailbox_offset = [6, -22]
sprinkler_offset_v1 = [0, -22]
sprinkler_offset_v2 = [0, -22]
sprinkler_offset_v3 = [0, -23]
sprinkler_offset_v4 = [0, -24]
sprinkler_offset_v5 = [0, -25]
ocarina_offset = [0, -32]
seed_maker_offset = [-4, -32]
noticeboard_offset = [-4, -45]
challenge_board_offset = [0, -23]
dragon_shrine_offset = [0, -47]
dungeon_shrine_offset = [0, -35]
dungeon_ritual_altar_offset = [9, -21]
hay_manger_offset = [0, -24]
seed_bed_offset = [0, -32]
farm_bell_offset = [0, -32]
bathhouse_offset = [4, -33]
general_store_offset = [4, -20]
valens_clinic_offset = [0, -31]
blacksmith_store_offset = [0, -31]
terithias_store_offset = [4, -32]
darcys_stall_offset = [1, -32]
zorels_stall_offset = [1, -38]
merris_stall_offset = [0, -23]
veras_stall_offset = [0, -26]
louis_stall_offset = [0, -30]
balors_wagon_offset = [0, -23]
maples_stall_offset = [0, -23]
noras_stall_offset = [0, -23]
elsies_stall_offset = [0, -23]
wheedles_stall_offset = [1, -25]
museum_offset = [4, -32]
renown_chest_offset = [1, -17]
lost_and_found_offset = [1, -20]
museum_donate_offset = [4, -20]
hayden_store_offset = [4, -30]
inn_offset = [4, -33]
ryis_store_offset = [4, -27]
espresso_offset = [0, -25]
water_tablet_offset = [0, -29]
final_tablet_offset = [0, -52]
turn_in_box = [0, -19]
small_animal_booth_offset = [0, -25]
large_animal_booth_offset = [0, -25]
animal_souvenir_booth_offset = [0, -25]
harvest_souvenir_booth_offset = [0, -25]
storage_offset = [0, -19]
resonator_offset = [0, -32]
harvest_pie_offset = [0, -8]
harvest_pumpkin_patch = [0, -28]
caldarus_house_statue_offset = [0, -36]
seridias_house_statue_offset = [4, -37]
apiary_offset = [0, -33]
artifact_replicator_offset = [0, -38]
tower_resonator_offset = [0, -41]
terrarium_offset = [0, -33]
dragon_forge_offset = [0, -9]
fish_trap_offset = [1, -22]
large_sprinkler_offset_v1 = [0, -30]
large_sprinkler_offset_v2 = [0, -29]
large_sprinkler_offset_v3 = [0, -31]
tesserae_tree = [0, -31]
restoration_offset = [0, -18]
dragonsworn_statue_offset = [0, -40]
celines_flower_offset = [0, -32]
eilands_stelle_offset = [0, -50]
ryis_tree_offset = [0, -39]
mini_mill_offset = [0, -36]
mini_forge_offset = [12, -10]
auto_feeder_offset = [0, -26]
perpetual_soup_offset = [0, -18]

[highlight]
	default_color = [255, 227, 221]
	hold_period = 50
	hold_amplitude = 0.075
	hold_transform = 0.43
	tab_period = 32
	tab_amplitude = 0.28
	play_sound_time = 8
	tree_strength = 0.5
	door_strength = 0.5

[npcs]
	distance = 48
	period = 32
	circle_size = 8
	nudge_distance = 4
