[spr_inn_candle_north_main_on]
	light = "circle_twenty_four"
	offset = [0, -4]

[spr_inn_candle_north_broken_on]
	light = "circle_twenty_four"
	offset = [0, -4]

[spr_inn_candle_south_main_on]
	light = "circle_twenty_four"
	offset = [0, -4]

[spr_inn_candle_south_broken_on]
	light = "circle_twenty_four"
	offset = [0, -4]

[spr_manor_dining_candelabra_spring_on]
	light = "circle_eighty"
	offset = [0, -11]

[spr_manor_dining_candelabra_spring_top_on]
	light = "circle_eighty"
	offset = [0, -11]

[spr_void_seal_spotlight_large]
	light = "void_seal_spotlight_large"
	offset = [0, 0]

[spr_void_seal_spotlight_medium]
	light = "void_seal_spotlight_medium"
	offset = [0, 0]

[spr_void_seal_dragon_statue_left_main]
	light = "void_seal_spotlight_small_left"
	offset = [17, -24]

[spr_void_seal_dragon_statue_right_main]
	light = "void_seal_spotlight_small_right"
	offset = [-18, -24]

[spr_ruins_seal_tablet_cutscene_spring_start]
	light = "ruins_tablet_cutscene_start"
	offset = [0, 0]

[spr_ruins_seal_tablet_cutscene_spring_loop]
	light = "ruins_tablet_cutscene_loop"
	offset = [0, 0]

[spr_ruins_seal_tablet_cutscene_spring_end]
	light = "ruins_tablet_cutscene_end"
	offset = [0, 0]

[spr_ruins_seal_altar_cutscene_spring_start]
	light = "ruins_tablet_cutscene_start"
	offset = [5, -7]

[spr_ruins_seal_altar_cutscene_spring_loop]
	light = "ruins_tablet_cutscene_loop"
	offset = [5, -7]

[spr_ruins_seal_altar_cutscene_spring_end]
	light = "ruins_tablet_cutscene_end"
	offset = [5, -7]

[spr_seridias_chamber_crystal_spring]
	light = "circle_ninety_six"
	offset = [0, -12]

[spr_seridias_chamber_door_cracked_spring]
	light = "circle_eighty"
	offset = [0, -25]

[spr_seridias_chamber_door_barrier]
	light = "circle_ninety_six"
	offset = [0, -25]

[spr_priestess_quarters_dragon_forge_main_on]
	light = "circle_ninety_six"
	offset = [0, -4]

[spr_town_wedding_candle_left_on]
	light = "circle_twenty_four"
	offset = [2, -8]

[spr_town_wedding_candle_middle_on]
	light = "circle_twenty_four"
	offset = [0, -9]

[spr_town_wedding_candle_right_on]
	light = "circle_twenty_four"
	offset = [-2, -8]

[spr_town_stall_stillwell_large_table_spring]
	light = "circle_twenty_four"
	offset = [16, -16]