[small]
	sprites = [
		"spr_light_small_inner",
		"spr_light_small_middle",
		"spr_light_small_outer",
	]
	size = 64

[circle_forty_eight_weak]
	sprites = [
		"spr_fx_light_circle_width_48_weak_middle",
		"spr_fx_light_circle_width_48_weak_outer",
		"spr_nothing",
	]
	size = 48

[circle_sixty_four]
	sprites = [
		"spr_fx_light_circle_width_64_inner",
		"spr_fx_light_circle_width_64_middle",
		"spr_fx_light_circle_width_64_outer",
	]
	size = 64

[circle_eighty]
	sprites = [
		"spr_fx_light_circle_width_80_inner",
		"spr_fx_light_circle_width_80_middle",
		"spr_fx_light_circle_width_80_outer",
	]
	size = 80

[circle_eighty_eight]
	sprites = [
		"spr_fx_light_circle_width_88_inner",
		"spr_fx_light_circle_width_88_middle",
		"spr_fx_light_circle_width_88_outer",
	]
	size = 88

[circle_ninety_six]
	sprites = [
		"spr_fx_light_circle_width_96_inner",
		"spr_fx_light_circle_width_96_middle",
		"spr_fx_light_circle_width_96_outer",
	]
	size = 96

[circle_hundred]
	sprites = [
		"spr_fx_light_circle_width_100_inner",
		"spr_fx_light_circle_width_100_middle",
		"spr_fx_light_circle_width_100_outer",
	]
	size = 100

[circle_hundred_twelve]
	sprites = [
		"spr_fx_light_circle_width_112_inner",
		"spr_fx_light_circle_width_112_middle",
		"spr_fx_light_circle_width_112_outer",
	]
	size = 112

[circle_hundred_twenty_four]
	sprites = [
		"spr_fx_light_circle_width_124_inner",
		"spr_fx_light_circle_width_124_middle",
		"spr_fx_light_circle_width_124_outer",
	]
	size = 124

[circle_hundred_twenty_eight]
	sprites = [
		"spr_fx_light_circle_width_128_inner",
		"spr_fx_light_circle_width_128_middle",
		"spr_fx_light_circle_width_128_outer",
	]
	size = 128

[circle_hundred_thirty_six]
	sprites = [
		"spr_fx_light_circle_width_136_inner",
		"spr_fx_light_circle_width_136_middle",
		"spr_fx_light_circle_width_136_outer",
	]
	size = 136

[circle_hundred_forty_eight]
	sprites = [
		"spr_fx_light_circle_width_148_inner",
		"spr_fx_light_circle_width_148_middle",
		"spr_fx_light_circle_width_148_outer",
	]
	size = 148

[circle_hundred_fifty_two]
	sprites = [
		"spr_fx_light_circle_width_152_inner",
		"spr_fx_light_circle_width_152_middle",
		"spr_fx_light_circle_width_152_outer",
	]
	size = 152

[insect]
	sprites = [
		"spr_fx_light_insect_width_22_inner_idle",
		"spr_fx_light_insect_width_22_middle_idle",
		"spr_fx_light_insect_width_22_outer_idle",
	]
	size = 22

[circle_twenty_four]
	sprites = [
		"spr_fx_light_circle_width_24_inner",
		"spr_fx_light_circle_width_24_middle",
		"spr_fx_light_circle_width_24_outer",
	]
	size = 24

[xs]
	sprites = [
		"spr_fx_light_circle_width_48_inner",
		"spr_fx_light_circle_width_48_middle",
		"spr_fx_light_circle_width_48_outer",
	]
	size = 48

[enchantern]
	sprites = [
		"spr_fx_monster_enchantern_light_inner_loop",
		"spr_fx_monster_enchantern_light_middle_loop",
		"spr_fx_monster_enchantern_light_outer_loop",
	]
	size = 48

[enchantern_projectile_start]
	sprites = [
		"spr_monster_enchantern_floor_ball_light_inner_start",
		"spr_monster_enchantern_floor_ball_light_middle_start",
		"spr_monster_enchantern_floor_ball_light_outer_start",
	]
	size = 4

[enchantern_projectile_loop]
	sprites = [
		"spr_monster_enchantern_floor_ball_light_inner_loop",
		"spr_monster_enchantern_floor_ball_light_middle_loop",
		"spr_monster_enchantern_floor_ball_light_outer_loop",
	]
	size = 22

[enchantern_projectile_fizzle]
	sprites = [
		"spr_monster_enchantern_floor_ball_light_inner_fizzle",
		"spr_monster_enchantern_floor_ball_light_middle_fizzle",
		"spr_monster_enchantern_floor_ball_light_outer_fizzle",
	]
	size = 0

[flame_spirit]
	sprites = [
		"spr_fx_monster_flame_spirit_light_inner_main",
		"spr_fx_monster_flame_spirit_light_middle_main",
		"spr_fx_monster_flame_spirit_light_outer_main",
	]
	size = 96

[flame_spirit_appear]
	sprites = [
		"spr_fx_monster_flame_spirit_light_inner_appear",
		"spr_fx_monster_flame_spirit_light_middle_appear",
		"spr_fx_monster_flame_spirit_light_outer_appear",
	]
	size = 96

[flame_spirit_disappear]
	sprites = [
		"spr_fx_monster_flame_spirit_light_inner_disappear",
		"spr_fx_monster_flame_spirit_light_middle_disappear",
		"spr_fx_monster_flame_spirit_light_outer_disappear",
	]
	size = 0

[shooting_star_start]
	sprites = [
		"spr_summit_shooting_star_light_inner_start",
		"spr_summit_shooting_star_light_middle_start",
		"spr_summit_shooting_star_light_outer_start",
	]
	size = 0

[shooting_star_loop]
	sprites = [
		"spr_summit_shooting_star_light_inner_loop",
		"spr_summit_shooting_star_light_middle_loop",
		"spr_summit_shooting_star_light_outer_loop",
	]
	size = 0

[shooting_star_end]
	sprites = [
		"spr_summit_shooting_star_light_inner_end",
		"spr_summit_shooting_star_light_middle_end",
		"spr_summit_shooting_star_light_outer_end",
	]
	size = 0

[star_festival_arch]
	sprites = [
		"spr_town_shooting_star_festival_arch_light_inner",
		"spr_town_shooting_star_festival_arch_light_middle",
		"spr_town_shooting_star_festival_arch_light_outer",
	]
	size = 0

[star_festival_garland]
	sprites = [
		"spr_town_shooting_star_festival_garland_light_inner",
		"spr_town_shooting_star_festival_garland_light_middle",
		"spr_town_shooting_star_festival_garland_light_outer",
	]
	size = 0

[star_festival_lantern]
	sprites = [
		"spr_town_shooting_star_lantern_light_inner",
		"spr_town_shooting_star_lantern_light_middle",
		"spr_town_shooting_star_lantern_light_outer",
	]
	size = 0

[star_festival_tree_decoration]
	sprites = [
		"spr_town_shooting_star_tree_decoration_light_inner",
		"spr_town_shooting_star_tree_decoration_light_middle",
		"spr_town_shooting_star_tree_decoration_light_outer",
	]
	size = 0

[firefly_wall_string_lights]
	sprites = [
		"spr_decor_firefly_string_lights_light_inner_on",
		"spr_decor_firefly_string_lights_light_middle_on",
		"spr_nothing",
	]
	size = 0

[caldarus_house_garland]
	sprites = [
		"spr_caldarus_house_garland_light_inner",
		"spr_caldarus_house_garland_light_middle",
		"spr_caldarus_house_garland_light_outer",
	]
	size = 0

[abandoned_pit_spotlight]
	sprites = [
		"spr_nothing",
		"spr_fx_light_abandoned_mines_pit_middle",
		"spr_fx_light_abandoned_mines_pit_outer",
	]
	size = 0

[void_seal_spotlight_large]
	sprites = [
		"spr_fx_light_void_seal_spotlight_large_inner",
		"spr_fx_light_void_seal_spotlight_large_middle",
		"spr_nothing",
	]
	size = 0

[void_seal_spotlight_medium]
	sprites = [
		"spr_fx_light_void_seal_spotlight_medium_inner",
		"spr_fx_light_void_seal_spotlight_medium_middle",
		"spr_nothing",
	]
	size = 16

[void_seal_spotlight_small_left]
	sprites = [
		"spr_fx_light_void_seal_spotlight_small_left_inner",
		"spr_fx_light_void_seal_spotlight_small_left_middle",
		"spr_nothing",
	]
	size = 16

[void_seal_spotlight_small_right]
	sprites = [
		"spr_fx_light_void_seal_spotlight_small_right_inner",
		"spr_fx_light_void_seal_spotlight_small_right_middle",
		"spr_nothing",
	]
	size = 16

[ruins_tablet_cutscene_start]
	sprites = [
		"spr_ruins_seal_tablet_cutscene_light_inner_start",
		"spr_ruins_seal_tablet_cutscene_light_middle_start",
		"spr_ruins_seal_tablet_cutscene_light_outer_start",
	]
	size = 0

[ruins_tablet_cutscene_loop]
	sprites = [
		"spr_ruins_seal_tablet_cutscene_light_inner_loop",
		"spr_ruins_seal_tablet_cutscene_light_middle_loop",
		"spr_ruins_seal_tablet_cutscene_light_outer_loop",
	]
	size = 0

[ruins_tablet_cutscene_end]
	sprites = [
		"spr_ruins_seal_tablet_cutscene_light_inner_end",
		"spr_ruins_seal_tablet_cutscene_light_middle_end",
		"spr_ruins_seal_tablet_cutscene_light_outer_end",
	]
	size = 0

[dingy_string_lights]
	sprites = [
		"spr_furniture_dingy_mostly_broken_string_lights_light_inner_on",
		"spr_furniture_dingy_mostly_broken_string_lights_light_middle_on",
		"spr_nothing",
	]
	size = 0
