standard_minutes_per_day = 15
longer_minutes_per_day = 16.5
longest_minutes_per_day = 18

eat_time = 30

fetch_quests_per_day = 1
first_week_of_weather = [
	"calm",
	"calm",
	"calm",
	"inclement",
	"calm",
	"special",
	"heavy_inclement",
]
npc_heart_point_table = [
	80,
	180,
	280,
	390,
	530,
	705,
	900,
	1125,
	1450,
	1850,
]
controller_drift_amount = 16
tool_range_cycle_rate = 30
weather_cutscene_strength = 0.3

wallpaper_spawn_point = [152, 162]
flooring_spawn_point = [152, 162]
daily_hearts_for_speaking = 7

balor_price_markup = 1

shake_item_in_tree_chance = 25

cooking_recipe_star_prices = [150, 300, 400, 600, 800]

home_variant_cost = 5000

gossip_lines = [
	"gossip_one",
	"gossip_two",
	"gossip_three",
	"gossip_four",
	"gossip_five",
	"gossip_six",
	"gossip_seven",
	"gossip_eight",
]

illegal_winter_sprites = [
	"spr_beach_umbrella_red_spring",
	"spr_beach_umbrella_yellow_spring",
	"spr_beach_sandcastle_spring",
	"spr_furniture_beach_towel_blue_spring_east",
	"spr_furniture_beach_towel_blue_spring_south",
	"spr_furniture_beach_towel_red_spring_east",
	"spr_furniture_beach_towel_red_spring_south",
	"spr_furniture_beach_towel_yellow_spring_east",
	"spr_furniture_beach_towel_yellow_spring_south",
]

ancient_inspiration_table = ["cavern_mushroom_stool_green", "chess_pawn_white", "chess_rook_white"]

dungeon_monster_element_points = 1
dungeon_object_element_points = 1

# inner data for cosmetics and recipe scrolls are the same as above, inner data for unidentified_artifacts are artifact item ids
mist_sight_table = [
	#{ item_id = "recipe_scroll", inner_data = "chess_rook_white" },
	{ item_id = "unidentified_artifact", inner_data = "misty_black_mirror" },
	{ item_id = "unidentified_artifact", inner_data = "misty_feather_quill" },
	{ item_id = "unidentified_artifact", inner_data = "mist_crystal" },
	{ item_id = "unidentified_artifact", inner_data = "mist_scroll" },
	{ item_id = "unidentified_artifact", inner_data = "mist_flute" },
	{ item_id = "cosmetic", inner_data = "head_floating_cloud_headpiece" },
	{ item_id = "cosmetic", inner_data = "back_gear_cloud_backpack" },
	{ item_id = "mist_bed_v1" },
	{ item_id = "mist_bed_v2" },
	{ item_id = "mist_bed_v3" },
	{ item_id = "mist_bed_v4" },
	{ item_id = "mist_double_bed_v1" },
	{ item_id = "mist_double_bed_v2" },
	{ item_id = "mist_double_bed_v3" },
	{ item_id = "mist_double_bed_v4" },
	{ item_id = "mist_pet_bed_v1" },
	{ item_id = "mist_pet_bed_v2" },
	{ item_id = "mist_pet_bed_v3" },
	{ item_id = "mist_pet_bed_v4" },
	{ item_id = "mist_rug_v1" },
	{ item_id = "mist_rug_v2" },
	{ item_id = "mist_rug_v3" },
	{ item_id = "mist_rug_v4" },
	{ item_id = "mist_cushion_v1" },
	{ item_id = "mist_cushion_v2" },
	{ item_id = "mist_cushion_v3" },
	{ item_id = "mist_cushion_v4" },
	{ item_id = "mist_lamp_v1" },
	{ item_id = "mist_lamp_v2" },
	{ item_id = "mist_lamp_v3" },
	{ item_id = "mist_lamp_v4" },
	{ item_id = "mist_storage_chest_v1" },
	{ item_id = "mist_storage_chest_v2" },
	{ item_id = "mist_storage_chest_v3" },
	{ item_id = "mist_storage_chest_v4" },
]

small_animal_festival_rewards = [
	{},
	{ placeable = "white_{AnimalKind}_wall_ribbon", cosmetic = "ribbon_white" },
	{ placeable = "red_{AnimalKind}_wall_ribbon", cosmetic = "ribbon_red" },
	{ placeable = "blue_{AnimalKind}_wall_ribbon", cosmetic = "ribbon_blue" },
]

large_animal_festival_rewards = [
	{},
	{ placeable = "bronze_{AnimalKind}_trophy", cosmetic = "ribbon_white" },
	{ placeable = "silver_{AnimalKind}_trophy", cosmetic = "ribbon_red" },
	{ placeable = "gold_{AnimalKind}_trophy", cosmetic = "ribbon_blue" },
]

# this is the chance that any chest will drop a crystal. the quality of the chest
# in breakables.toml determines what kind of crystal it will drop.
global_essence_crystal_chance = 15

# the cost of pumpkin patch pumpkins from hayden on harvest festival day
pumpkin_patch_price = 200
pumpkin_patch_options = [
	{ item = "small_decorative_pumpkin_white", count = 1 },
	{ item = "small_decorative_pumpkin_yellow", count = 1 },
	{ item = "small_decorative_pumpkin_orange", count = 1 },
	{ item = "small_decorative_pumpkin_green", count = 1 },
	{ item = "small_decorative_pumpkin_purple", count = 1 },
	{ item = "small_decorative_pumpkin_black", count = 1 },
	{ item = "medium_decorative_pumpkin_white", count = 1 },
	{ item = "medium_decorative_pumpkin_yellow", count = 1 },
	{ item = "medium_decorative_pumpkin_orange", count = 1 },
	{ item = "medium_decorative_pumpkin_green", count = 1 },
	{ item = "medium_decorative_pumpkin_purple", count = 1 },
	{ item = "medium_decorative_pumpkin_black", count = 1 },
	{ item = "large_decorative_pumpkin_white", count = 1 },
	{ item = "large_decorative_pumpkin_yellow", count = 1 },
	{ item = "large_decorative_pumpkin_orange", count = 1 },
	{ item = "large_decorative_pumpkin_green", count = 1 },
	{ item = "large_decorative_pumpkin_purple", count = 1 },
	{ item = "large_decorative_pumpkin_black", count = 1 },
	{ item = "extra_large_decorative_pumpkin_white", count = 1 },
	{ item = "extra_large_decorative_pumpkin_yellow", count = 1 },
	{ item = "extra_large_decorative_pumpkin_orange", count = 1 },
	{ item = "extra_large_decorative_pumpkin_green", count = 1 },
	{ item = "extra_large_decorative_pumpkin_purple", count = 1 },
	{ item = "extra_large_decorative_pumpkin_black", count = 1 },
	{ item = "pumpkin_pile_white", count = 1 },
	{ item = "pumpkin_pile_yellow", count = 1 },
	{ item = "pumpkin_pile_orange", count = 1 },
	{ item = "pumpkin_pile_green", count = 1 },
	{ item = "pumpkin_pile_purple", count = 1 },
	{ item = "pumpkin_pile_black", count = 1 }
]

farm_expansion_collision_points = [
	[184, 118],
	[185, 118],
	[186, 118],
	[184, 131],
	[185, 131],
	[186, 131],
]

earthly_essence_alternative = [
	{item_id = "mana_potion"},
	{item_id = "heal_syrup"},
	{item_id = "stamina_syrup"},
	{item_id = "purse", gold = 500}
]

# what days the player can invite NPCs out on dates
date_days = ["saturday", "sunday"]

# how many points a date gives
date_heart_points = 60

# details on date photos
date_photo_size = [226, 166]

# statuses that allow an NPC to be taken on a date
statuses_eligible_for_dates = ["dating", "fiance", "spouse"]

# some chances for date items
lovely_seashell_chance = 1
rough_gemstone_chance = 0.15
dollhouse_bench_chance = 0.05

# drop chance for void powder once you get void sight
void_powder_chance = 10

# how long (in seconds) sacred light lasts
sacred_light_duration = 300

# default names for male children
default_male_child_names = [
    "Aden",
    "Allan",
    "Alon",
    "Ander",
    "Andre",
    "Archer",
    "Aslan",
    "Aslen",
    "Bailey",
    "Blaise",
    "Bowen",
    "Caden",
    "Cedric",
    "Chase",
    "Cian",
    "Connor",
    "Cryus",
    "Dane",
    "Daren",
    "Darian",
    "Dorian",
    "Drake",
    "Edric",
    "Eiden",
    "Eoin",
    "Eran",
    "Evan",
    "Ewan",
    "Ferran",
    "Finch",
    "Fisher",
    "Flin",
    "Flint",
    "Forest",
    "Gage",
    "Galen",
    "Gian",
    "Gray",
    "Gryffin",
    "Hayes",
    "Heston",
    "Hiro",
    "Ingram",
    "Isaia",
    "Ivan",
    "Jace",
    "Jean",
    "Julian",
    "Kai",
    "Kane",
    "Killian",
    "Lamar",
    "Locke",
    "Luca",
    "Marc",
    "Marcus",
    "Micah",
    "Miles",
    "Nolen",
    "Oberon",
    "Oisín",
    "Oliver",
    "Omari",
    "Pace",
    "Parker",
    "Pax",
    "Quinn",
    "Raven",
    "Reid",
    "Ren",
    "Riley",
    "Ronin",
    "Rory",
    "Rynn",
    "Sage",
    "Silas",
    "Silver",
    "Sky",
    "Sora",
    "Soren",
    "Tanner",
    "Tristen",
    "Ulric",
    "Vale",
    "Van",
    "Wesley",
    "Will",
    "Xan",
    "Yuri",
    "Zain",
    "Zaire",
]

# default names for female children
default_female_child_names = [
    "Adra",
    "Amber",
    "Anna",
    "Arin",
    "Ava",
    "Belle",
    "Briar",
    "Brynn",
    "Callie",
    "Cecilia",
    "Celeste",
    "Ciara",
    "Corinne",
    "Corra",
    "Delia",
    "Devin",
    "Diana",
    "Eda",
    "Eden",
    "Elise",
    "Ella",
    "Emmy",
    "Fay",
    "Fern",
    "Flora",
    "Freya",
    "Frieda",
    "Gemma",
    "Geneva",
    "Gigi",
    "Grace",
    "Halia",
    "Harper",
    "Hattie",
    "Hazel",
    "Helena",
    "Imani",
    "Indira",
    "Iris",
    "Isabel",
    "Isolde",
    "Jada",
    "Jasmine",
    "June",
    "Juno",
    "Kaia",
    "Kali",
    "Kara",
    "Kiara",
    "Kira",
    "Layla",
    "Lily",
    "Lola",
    "Luna",
    "Lyra",
    "Maddie",
    "Maisie",
    "Maya",
    "Mia",
    "Mimi",
    "Mona",
    "Morgan",
    "Myra",
    "Nadia",
    "Nina",
    "Noelle",
    "Nova",
    "Olive",
    "Ophelia",
    "Paige",
    "Pearl",
    "Phoebe",
    "Pia",
    "Quinn",
    "Raven",
    "Remi",
    "Riley",
    "Rory",
    "Ruby",
    "Rynn",
    "Sage",
    "Sara",
    "Sky",
    "Sora",
    "Stella",
    "Sylvie",
    "Talia",
    "Tessa",
    "Tori",
    "Tove",
    "Uma",
    "Ursa",
    "Vada",
    "Violet",
    "Vivian",
    "Willow",
    "Winnie",
    "Wren",
    "Wrynn",
    "Xena",
    "Yara",
    "Yasmin",
    "Yumi",
    "Yuna",
    "Zara",
    "Zoe",
    "Zuri",
]

wedding_assets = [
    "head_wedding_veil",
    "head_clips_wedding_flower",
    "head_wedding_top_hat",
    "dress_romantic_wedding_gown",
    "dress_mermaid_wedding_gown",
    "dress_caped_wedding_gown",
    "suit_tailcoat_wedding_tuxedo",
    "suit_tailcoat_wedding",
    "suit_classy_bowtie_wedding",
    "shoes_floral_wedding_dress",
    "shoes_wedding_dress",
]

seridia_armor = [
    "back_gear_dragonsworn_cloak_seridia",
    "head_dragonsworn_helmet_seridia",
    "pants_dragonsworn_armor_seridia",
    "shoes_boots_dragonsworn_armor_seridia",
    "top_dragonsworn_armor_seridia",
]

# coordinates for object prototypes to be removed that will "open up" the farm expansion
[farm_expansion_fence_region]
	top_left = { x = 178, y = 24 }
	bottom_right = { x = 255, y = 118 }

# inner data for cosmetics and recipe scrolls are the same as above
[earthly_essence]
	spring = [
		{ item_id = "cosmetic", inner_data = "back_gear_turnip_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_snowdrop_anemone_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_cabbage_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_strawberry_backpack" },
	]

	summer = [
		{ item_id = "cosmetic", inner_data = "back_gear_watermelon_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_tomato_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_sunflower_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_daisy_backpack" },
	]

	fall = [
		{ item_id = "cosmetic", inner_data = "back_gear_pumpkin_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_sweet_potato_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_onion_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_wheat_backpack" },
	]

	winter = [
		{ item_id = "cosmetic", inner_data = "back_gear_daikon_radish_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_cauliflower_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_frost_lily_backpack" },
		{ item_id = "cosmetic", inner_data = "back_gear_jasmine_backpack" },
	]

[chicken_statue]
	high_price = 100
	low_price = 10

[wishing_well]
	high_price = 500
	low_price = 100

[bugs]
	low_spawn = 5
	in_tree_chance = 5
	in_grass_chance = 1

[farm_data]
	# this is how many tile variants (the little decals on the farm)
	# we try to have on any given day.
	tile_variant_cap = 350
	# this is the chance of one of them spawning at all (out of 100). Note: they never spawn
	# next to each other
	tile_variant_spawn_rate = 10

	[farm_data.grass_variant_rates]
		grass_votes = 20
		flower_votes = 10

	[farm_data.expansion_cost]
		gold = 40000
		items = [
			{ item_id = "refined_stone", count = 50 },
			{ item_id = "hard_wood", count = 50 },
		]
		preview = "spr_ui_store_farm_expansion_preview"

[price_multipliers]
	bronze = 1.25
	gold = 1.75
	silver = 1.5
	special = 2

[ari_stats]
	base_gold = 50
	base_health = 100
	base_stamina = 100
	base_mana = 0
	starting_essence = 0
	starting_inventory = ["sword_worn"]
	# if this has members, the first spell will also be pinned
	starting_spells = [
		# "full_restore",
		# "growth"
	]
	starting_inventory_test_mode = [
		"sword_mistril",
		"axe_mistril",
		"hoe_mistril",
		"pick_axe_mistril",
		"shovel_mistril",
		"watering_can_mistril",
		"fishing_rod_mistril",
		"net_mistril",
	]

	[ari_stats.starting_armor]
		head = "cloth_helmet"
		chest = "cloth_chestpiece"
		legs = "cloth_pants"
		boots = "cloth_shoes"
		accessory = "cloth_wristband"

[ari_animation]
	# this is a range in number of second, so [8, 14] means "somewhere between every 8 and 14 seconds"
	blink_rate = [8, 14]
	# this is a range in number of second, so [30, 35] means "somewhere between every 30 and 35 seconds"
	idle_variance_rate = [30, 35]

[perk_vfx]
	essence_flash = [173, 105, 246]
	stamina_flash = [92, 201, 123]

[bathhouse]
	cost = 100
	usage_multiplier = 2

[enemy_hp]
	mushroom = 3
	slime = 3

[dungeon_fountain]
	essence_gain = 170
	health_gain = 33
	mana_gain = 33
	stamina_gain = 33

[inn]
	soup_kinds = [
		"corn chowder",
		"vegetable soup",
		"minestrone soup",
		"potato soup",
		"broccoli cheddar soup",
		"clam chowder soup",
		"egg drop soup",
	]
	# How many NPCs need to be present in the room in order to trigger the busy version of the music
	busy_threshold = 8

[npc_behavior]
	# The amount of frames (60 per second) that the Npcs pause inbetween barks while they
	# are chatting. The array represents a random range of two numbers.
	chat_interval = [1440, 2880]
	barks_random_invalid = [
		"one",
		"two",
		"three",
		"four",
		"five",
		"six",
		"seven",
		"eight",
		"nine",
		"lake",
		"breed_male",
		"breed_female",
		"caldarus",
        "seridia",
		"priestess",
	]
	# This is the chat interval for NPCs chatting in a cutscene, which we want to be a
	# bit faster.
	cutscene_chat_interval = [60, 120]
	# Similarly, how often the npcs can emit thought bubbles.
	thought_interval = [1440, 2880]
	# The maximum distance (in pixels) two npcs can be to begin / sustain a conversation.
	max_chat_distance = 48
	# The frequency at which an NPC checks for other NPCs to chat with.
	chat_scan_frequency = 120
	# The number of frames an npc waits before displaying the "..." bark when Ari is blocking their path
	path_block_bark_delay = 180
	# The number of frames an npc waits *after* barking before they just walk around Ari
	path_block_reroute_delay = 300
	# The number of tiles (8x8) that pathfinding characters look ahead while walking to detect "errors". The most
	# common example of this would be the npcs stopping when Ari stands in their way. If the number was set to 2,
	# Ari would need to be within 2 tiles of the Npc for them to stop.
	pathfinding_lookahead = 2

# Various movement speed values. The numbers are expressed in pixels-per-frame.
[movement_speeds]
    # the amount the player scans to "slip" past collisions. setting to a huge value is fun
    # but very wonky for most players as they'll always "slide" against a wall.
    slip_size = 4

	# The basic walking speed. This is what everyone uses when pathfinding, and what Ari uses when she toggles
	# into walk mode.
	walk = 0.6
	# A faster walking speed used occasionally in the cutscenes.
	fast_walk = 0.8

	# Ari's running speed.
	run = 2
	# Ari's swimming speed.
	swim = 1
	# Ari's swimming speed if she's in walk mode. lol we support that?
	swim_slow = 0.4

	mount_walk = 0.8
	mount_run = 3.0
	mount_horsepower_run = 3.2

[eating.east]
	offset = [19, -12]
	plate = "spr_npc_food_empty_plate_eat_east"

# we do not support north yet
[eating.north]
	offset = [0, -25]
	plate = "spr_npc_food_empty_plate_eat_south"

[eating.west]
	offset = [-18, -12]
	plate = "spr_npc_food_empty_plate_eat_east"

[eating.south]
	# according to Alina's mockup this offset should actually be [-9, -6]
	# alinadk why food was spawning too low! :(((
	offset = [0, 1]
	plate = "spr_npc_food_empty_plate_eat_south"

[npc_drinks]
	# note that we "magically" know that WEST is the same as east.
	# and by "magically", I mean through my hard work!!!
	beer = { east = "spr_npc_drink_beer_drink_east", south = "spr_npc_drink_beer_drink_south" }
	coffee = { east = "spr_npc_drink_coffee_drink_east", south = "spr_npc_drink_coffee_drink_south" }
	wine = { east = "spr_npc_drink_wine_drink_east", south = "spr_npc_drink_wine_drink_south" }
	juice = { east = "spr_npc_drink_juice_drink_east", south = "spr_npc_drink_juice_drink_south" }
	water = { east = "spr_npc_drink_water_drink_east", south = "spr_npc_drink_water_drink_south" }
	black_tea = { east = "spr_npc_drink_black_tea_drink_east", south = "spr_npc_drink_black_tea_drink_south" }
	green_tea = { east = "spr_npc_drink_green_tea_drink_east", south = "spr_npc_drink_green_tea_drink_south" }
	milk = { east = "spr_npc_drink_milk_drink_east", south = "spr_npc_drink_milk_drink_south" }
	white_wine = { east = "spr_npc_drink_white_wine_drink_east", south = "spr_npc_drink_white_wine_drink_south" }
	lemonade = { east = "spr_npc_drink_lemonade_drink_east", south = "spr_npc_drink_lemonade_drink_south" }
	espresso = { east = "spr_npc_drink_espresso_drink_east", south = "spr_npc_drink_espresso_drink_south" }
	whiskey = { east = "spr_npc_drink_whiskey_drink_east", south = "spr_npc_drink_whiskey_drink_south" }
	hot_chocolate = { east = "spr_npc_drink_hot_chocolate_drink_east", south = "spr_npc_drink_hot_chocolate_drink_south" }
	rose_wine = { east = "spr_npc_drink_rose_wine_drink_east", south = "spr_npc_drink_rose_wine_drink_south" }
	green_bottle = { east = "spr_npc_drink_green_bottle_drink_east", south = "spr_npc_drink_green_bottle_drink_south" }
	cocktail = { east = "spr_npc_drink_cocktail_drink_east", south = "spr_npc_drink_cocktail_drink_south" }
	latte = { east = "spr_npc_drink_latte_drink_east", south = "spr_npc_drink_latte_drink_south" }
	absinthe = { east = "spr_npc_drink_absinthe_drink_east", south = "spr_npc_drink_absinthe_drink_south" }

[diving]
	sfx = "SoundEffects/Ari/DiveDown"
	whirlpool_counter = 30
	dungeon_counter = 15

[kitchen_level_requirements]
	two = 15
	three = 30

[gift_giving.hearts]
	loved = 20
	liked = 10
	neutral = 3
	disliked = 0
	hated = 0
	birthday_boost = 20

[gift_giving.barks]
	loved = "heart"
	liked = "music"
	neutral = "cute_face"
	disliked = "question_mark"
	hated = "angry"

# This dictates the various chances of the item for gathering challenge dropping while its active
[gather_challenge_drop_chances]
	# harvesting a crop or forageable (including bushes)
	harvest = 0.12
	# digging/picking a dig site
	dig_site = 0.25
	# breaking a rock
	rock_break = 0.11
	# breaking an object with the axe
	axe_break = 0.15
	# when a fish is caught
	fish_caught = 0.33
	# when a dive spot is cleared
	dive_spot = 0.40
	# when a bug is caught
	bug_caught = 0.15
	# each time an animal drops an item overnight
	animal_production = 0.50
	# breaking stuff like bushes and boxes
	slash_breakable = 0.005
	# slashing grass
	slash_grass = 0.004
	# when killing an enemy.
	kill_enemy = 0.33

[xp_values] # exp earned for action
	break_dig_spot = 3
	identify_artifact = 6
	catch_small_fish = 20
	catch_medium_fish = 20
	catch_large_fish = 20
	catch_giant_fish = 20
	harvest_dive_spot = 10
	plant_seed = 4
	harvest_crop = 6
	till_dirt = 4
	water_dirt = 1

[window_backing]
	"6:00am" = 1
	"7:00am" = 1
	"9:00am" = 6
	"11:00am" = 11
	"6:30pm" = 11
	"7:30pm" = 16
	"8:30pm" = 21
	"10:00pm" = 26

[mines_overlay_values]
	venomous_overlay_color = [174, 189, 123]
	venomous_opacity = 0.39
	frozen_overlay_color = [148, 224, 235]
	frozen_opacity = 0.29
