fire_breath_orbs = 5
fire_breath_orb_growth = 12
fire_breath_time_cap = 600
fire_breath_damage = 100

fire_effect_speed = 4
fire_effect_count = 12
fire_effect_lifetime = 50
fire_effect_distance = 110
fire_effect_offset = 12 	# spawn distance from the player
fire_effect_fire_rate = 3 # bigger number = more frames between spawns
fire_effect_body = [255, 215, 18] # ari body color
fire_effect_body_time = 45 # how many frames it takes to complete a full oscillation
fire_effect_body_alpha_anchor = 0.5 # the value to oscilate from
fire_effect_body_alpha_range = 0.07 # with an anchor of 0.5 and a range of 0.1, fade from 0.4 to 0.6
fire_effect_ui_color = [255, 68, 68]
fire_effect_vfx_ratio = 3

item_detection_radius = 50
hurt_colors = [
	[255, 69, 69],
	[243, 0, 0],
	[162, 0, 0],
	[81, 0, 0],
]
hurt_timer = 33
vfx_sprites = [
	"spr_fx_player_hit_hurt_e",
	"spr_fx_player_hit_hurt_n",
	"spr_fx_player_hit_hurt_e",
	"spr_fx_player_hit_hurt_s",
]

damage_number_offset = -28
progress_bar_normal_offset = [-6, -32]

[electrocute]
	yellow_outline = [
		[255, 255, 255],
		[255, 255, 0],
	]
	blue_outline = [
		[206, 228, 255],
		[0, 0, 255],
	]

	yellow_blend = [
		[255, 230, 69],
		[243, 170, 0],
		[162, 85, 0],
		[81, 40, 0],
	]
	blue_blend = [
		[206, 228, 255],
		[112, 160, 255],
		[69, 129, 255],
		[17, 68, 255],
	]

[par]
	offset = [-40, -43]
	anim_speed = 0.016666667

[hurtbox]
	iframes = 60
	iframe_blinker = 8
	ibounds = [0.0, 0.75]

[jump_data]
	speed = -2.7
	gravity = 0.18
	frames = 29

[[large.sword_swing]]
	east.offset = [5, -27]
	east.dims = [20, 39]

	north.offset = [-24, -30]
	north.dims = [47, 24]

	west.offset = [-26, -27]
	west.dims = [20, 39]

	south.offset = [-24, -3]
	south.dims = [47, 24]

[[large.sword_swing]]
	east.offset = [5, -30]
	east.dims = [20, 37]

	north.offset = [-20, -26]
	north.dims = [37, 16]

	west.offset = [-26, -30]
	west.dims = [20, 37]

	south.offset = [-22, 1]
	south.dims = [38, 16]

[[large.sword_swing]]
	east.offset = [4, -11]
	east.dims = [28, 14]

	north.offset = [-7, -36]
	north.dims = [16, 24]

	west.offset = [-32, -11]
	west.dims = [28, 14]

	south.offset = [-7, 2]
	south.dims = [16, 24]
