neutral = "neutral"
think = "neutral"
concerned = "think"
blush_closed_eyes = "blush"
happy = { portrait = "neutral", effect = "sparkles" }
wink = "happy"
blush = "happy"
mad = "think"
angry_blush = "mad"
embarrassed = { portrait = "happy", effect = "sweat" }
sad = "think"
ugh = "think"
sigh = "think"
sly = "happy"
sly_think = "think"
laugh = "happy"
neutral_closed = "neutral"
unimpressed = "think"
very_happy = "happy"
cartoon_embarrassed = "embarrassed"
blush_special = "blush"
annoyed = "mad"
gloomy = "sad"
sweat = { portrait = "happy", effect = "sweat" }
neutral_arm_down = "neutral"
neutral_fist = "neutral"
happy_arm_down = "happy"
happy_fist = "happy"
wink_arm_down = "wink"
wink_fist = "wink"
angry_brows = "mad"
wild_laugh = "laugh"
wild_laugh_blush = "wild_laugh"
drunk = "blush"
raised_eyebrow = "think"
tsundere = "angry_blush"
eyes_shine = "neutral"
smile = "happy"
pained = "mad"
shocked = { portrait = "neutral", effect = "shock" }
shocked_special = "shocked"
gloomy_special = "sad"
hope_special = "embarrassed"
sincere_special = "neutral"
teary_special = "sad"
teary_blush = "sad"
think_special = "think"
shy_special = "embarrassed"
sad_special = "sad"
mad_special = "mad"
shock_special = "neutral"
caring_special = "embarrassed"
avoidant_special = "think"
avoidant = "think"
laugh_special = "happy"
hurt = "sad"
neutral_tired = "tired"
embarrassed_tired = "tired"
evasive_tired = "tired"
sick_eyes_open = "neutral"
sick_eyes_closed = "neutral"
sick_smile = "smile"
sick_think = "think"
shy_blush = "blush"
closed_eyes = "neutral"
closed_eyes_smile = "smile"
closed_eyes_smile_blush = "smile"
closed_eyes_brow = "angry_brows"
closed_eyes_blush = "blush"
happy_arm_down_blush = "blush"
confident_blush = "happy"
blush_open_eyes = "blush"
blush_think = "blush"
happy_blush = "happy"
hurt_shock = { portrait = "neutral", effect = "intensity" }
hurt_sad = "sad"
hurt_sad_special = "sad"
hurt_mad = "mad"
hurt_tsundere = "tsundere"
hurt_blush = "blush"
hurt_blush_closed_eyes = "blush_closed_eyes"
hurt_closed_eyes = "closed_eyes"
hurt_think = "think"
hurt_happy = "happy"
hurt_happy_blush = "blush"
eight_heart_happy = "happy"
eight_heart_think = "think"
eight_heart_closed_eyes = "closed_eyes"
eight_heart_blush = "blush"
eight_heart_happy_blush = "blush"
eight_heart_flustered = { portrait = "embarrassed", effect = "sweat" }
super_flustered = { portrait = "eight_heart_flustered", effect = "sweat" }
bath_neutral = "neutral"
neutral_blush = "embarrassed"
unsure_special = "think_special"
panic = "sad"
teary = "sad"
watery_eyes = "sad"
think_blush = "think"
think_smile = "think"
serious = "neutral"
serious_blush = "neutral"
bashful = "embarrassed"
laugh_blush = "laugh"
starry_eyed = "blush_special"
thoughtful = "neutral"
thoughtful_blush = "blush_special"
surprised = { portrait = "neutral", effect = "intensity" }
sinister = "mad"
serious_think = "closed_eyes"
smirk = "happy"
smirk_think = "closed_eyes"
unmasking = { portrait = "happy", effect = "sparkles_dark" }
unsure = "think"
unsure_blush = "think"
surprise = { portrait = "neutral", effect = "surprise" }
surprise_blush = { portrait = "neutral", effect = "surprise" }
sinister_blush = "mad"

# Cal statue
real = "neutral"
real_closed_eyes = "neutral"
