# Darcy 2h
[darcy_coffee]
	item = "coffee"
	z = -50

[darcy_espresso]
	item = "espresso"
	z = -50

[darcy_latte]
	item = "latte"
	z = -50

# Reina 2h
[reina_pie]
	item = "wildberry_pie"
	z = -50

# celine
[digsite_prop]
	artifact = "rubber_fish"

# March 4h
[march_ingot_pile]
	sprite = "spr_town_ingot_pile_spring"

[march_blacksmith_barrel]
	sprite = "spr_blacksmith_barrel_spring"

[march_carpenter_barrel]
	sprite = "spr_carpenter_house_f1_barrel1_spring"

[march_inn_barrel]
	sprite = "spr_inn_barrel_spring"

# reina 4h
[reina_dragonhorn_mushroom_shop]
	item = "dragon_horn_mushroom"
	z = -500

[reina_dragonhorn_mushroom_room]
	item = "dragon_horn_mushroom"
	z = -500

[reina_dragonhorn_dish]
	item = "dragon_horn_mushroom_with_thyme"
	z = -500

# Valen 4h
[valen_lurid_colored_drink]
	item = "lurid_colored_drink"
	z = -20

# hemlock 2h
[hemlock_place_setting_empty]
	sprite = "spr_inn_place_settings_v1_spring"
	z = 5

[hemlock_place_setting_crumb]
	sprite = "spr_inn_place_settings_v2_spring"
	z = 5

# olric 2h
[olric_shirt]
	sprite = "spr_bathhouse_changeroom_olrics_shirt"

# day zero
[eastern_road_rock]
	sprite = "spr_farm_rock_big_t1_c2_spring"

[eastern_road_rock_2]
	sprite = "spr_farm_rock_big_t1_c2_spring"
	seasonal = true

[house_bedding]
	sprite = "spr_furniture_pile_of_bedding_spring"
	z = -10

[house_bedding_ground]
	sprite = "spr_furniture_pile_of_bedding_ground"
	z = 0

[player_home_dusty_bed]
	sprite = "spr_furniture_messy_house_bed_spring"

[player_home_dusty_table]
	sprite = "spr_furniture_messy_house_table_spring_south"
	z = 0

[player_home_rubble]
	sprite = "spr_furniture_messy_house_rubble_spring"

[player_home_mat]
	sprite = "spr_furniture_pile_of_bedding_ground"
	z = 0

# Stillwell 2h
[stillwell_plate]
	item = "vegetable_soup"
	z = -20

[ari_plate]
	item = "vegetable_soup"
	z = -20

# Cop some ore
[copper_ingot]
	item = "copper_ingot"
	z = -50

# jos cooking class
[jcc_vegetable_soup]
	item = "vegetable_soup"
	z = -20

	# translating the water tablet

[water_tablet]
	item = "water_tablet_rubbing"
	z = -20

[b2h_wagon]
	sprite = "spr_town_balor_wagon_spring"
	z = -20

[b2h_box]
	sprite = "spr_town_crate_spring"
	z = -10

[j4h_horse_south]
	sprite = "spr_animal_horse_cutscene_base_idle_south"
	z = -50

[j4h_horse_east_1]
	sprite = "spr_animal_horse_cutscene_base_idle_east"
	z = -50

[j4h_horse_east_2]
	sprite = "spr_animal_horse_cutscene_base_idle_2_east"
	z = -50

[j4h_horse_east_3]
	sprite = "spr_animal_horse_cutscene_base_idle_3_east"
	z = -50

[j4h_horse_east_4]
	sprite = "spr_animal_horse_cutscene_base_happy_east"
	z = -50

[tet_earth_tablet]
	item = "earth_tablet_rubbing"
	z = -20

[tet_fish]
	item = "archerfish"
	z = -2000

[tet_jewel]
	item = "ore_sapphire"
	z = -2000

[tet_kelp]
	item = "cave_kelp"
	z = -2000

[tet_bug]
	item = "coral_mantis"
	z = -2000

[b4h_journal]
	sprite = "spr_balor_journal_spring"
	z = 0

[rtgs2_rubble]
	sprite = "spr_furniture_messy_house_rubble_spring"
	z = 0

[ct_fence]
	item = "starter_wood_fence"
	z = -50

[rtss_rubble]
	sprite = "spr_furniture_messy_house_rubble_spring"
	z = 0

[h2h_veggie_platter]
	sprite = "spr_ui_item_braised_carrots"
	z = -500

[prologue_coffee]
	item = "confiscated_coffee"
	z = -500

[blacksmithing_cutscene_fireball]
	sprite = "spr_npc_blacksmith_hammer_prop"
	z = 0

[rmfr2_1_cow_1]
	sprite = "spr_cutscene_female_cow_east_base"
	z = 0

[rmfr2_1_cow_2]
	sprite = "spr_cutscene_male_cow_south_base"
	z = 0

[rmfr2_2_pan_full]
	sprite = "spr_inn_stove_pan_spring_food"
	z = 0

[rmfr2_2_pan_empty]
	sprite = "spr_inn_stove_pan_spring_empty"
	z = 0

[rmfr2_2_ari_rations]
	item = "twice_baked_rations"
	z = -20

[rti1_drink_fruity]
	sprite = "spr_prop_cocktail"
	z = -50

[rti1_drink_bitter]
	sprite = "spr_prop_green_bottle"
	z = -50

[rti1_drink_water]
	sprite = "spr_prop_water"
	z = -50

[rti1_proposal]
	sprite = "spr_prop_papers"
	z = -50

[h4h_feed_stack]
	sprite = "spr_prop_quality_seed_bags_spring"
	z = 0

[pws_spell]
	sprite = "spr_ui_journal_magic_rain_spell_icon_main"
	z = -50

[pes_spell]
	sprite = "spr_ui_journal_magic_growth_spell_icon_main"
	z = -50

[db_spell]
	sprite = "spr_ui_journal_magic_fire_spell_icon_main"
	z = -50

[c2h_dirt]
	sprite = "spr_dig_site_empty_spring"
	z = 0

[c2h_sod]
	item = "sod"
	z = -20

[c2h_peat]
	item = "peat"
	z = -20

[c2h_unusual_seed]
	item = "unusual_seed"
	z = -20

[v6h_notes]
	sprite = "spr_prop_papers"
	z = -20

[h6h_corn]
	sprite = "spr_ui_item_corn"
	z = -20

[h6h_strawberry]
	sprite = "spr_ui_item_strawberry"
	z = -30

[h6h_picnic_basket]
	sprite = "spr_decor_picnic_basket_red_spring_north"
	z = -20

[h6h_picnic_blanket]
	sprite = "spr_decor_picnic_rug_red_spring_south"
	z = 0

[h6h_picnic_flowers]
	item = "picnic_sunflower_vase_pink"
	z = -20

[e6h_cloak]
	sprite = "spr_prop_dragonsworn_cloak"
	z = -5

[b6h_wine]
	sprite = "spr_prop_wine_bottle"
	z = -20

[b6h_wine_glass]
	sprite = "spr_prop_wine"
	z = -20

[b6h_lemonade]
	sprite = "spr_ui_item_lemonade"
	z = -20

[b6h_contract]
	sprite = "spr_prop_papers"
	z = -10

[c6h_cobbler]
	item = "cherry_cobbler"
	z = -10

[c6h_sprout]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_open"
	z = -20

[c6h_sprouting]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_opening2"
	z = -20

[c6h_sprouted]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_open_2"
	z = -20

[c6h_sprouting_2]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_opening3"
	z = -20

[c6h_sprouted_2]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_open3"
	z = -20

[r6h_table_runner]
	sprite = "spr_inn_table_runner_spring"
	z = -10

[r6h_spicy_cake]
	sprite = "spr_prop_spicy_cake"
	z = -20

[r6h_honey_curry]
	sprite = "spr_ui_item_honey_curry"
	z = -20

[r6h_modernist_plate]
	sprite = "spr_prop_modernist_plate"
	z = -20

[r6h_modernist_specks]
	sprite = "spr_prop_modernist_specks"
	z = -20

[r6h_thick_drink]
	sprite = "spr_prop_thick_drink"
	z = -20

[r6h_pan]
	sprite = "spr_inn_stove_pan_spring_food"
	z = 0

[j6h_package]
	sprite = "spr_prop_gift"
	z = -10

[j6h_tonic]
	sprite = "spr_ui_item_plant_growth_tonic"
	z = -10

[a6h_food_box]
	sprite = "spr_town_crate_spring"
	z = -10

[a6h_project]
	sprite = "spr_celinecottage_stool_spring"
	z = 0

[a6h_horse]
	sprite = "spr_animal_horse_cutscene_base_idle_east"
	z = -10

[a6h_vegetable_soup]
	item = "vegetable_soup"
	z = -20

[shst_blanket]
	sprite = "spr_town_shooting_star_picnic_blanket"
	z = 15

[shst_pouf]
	sprite = "spr_town_shooting_star_pouf_spring"
	z = 5

[m6h_shield_unfinished]
	sprite = "spr_prop_shield_of_the_realm_unfinished"
	z = -5

[m6h_shield_unfinished_shake]
	sprite = "spr_prop_shield_of_the_realm_unfinished_shake"
	z = -5

[m6h_shield_finished_bounce]
	sprite = "spr_prop_shield_of_the_realm_finished_bounce"
	z = -5

[m6h_shield_finished]
	sprite = "spr_prop_shield_of_the_realm_finished"
	z = -5

[r6h_lumber]
	sprite = "spr_prop_lumber_stack_horizontal_spring"
	z = -20

[r6h_ruler]
	sprite = "spr_prop_ruler_spring"
	z = -20

[r6h_blueprints]
	sprite = "spr_prop_blueprint_big"
	z = -20

[r6h_lumber_floor]
	sprite = "spr_prop_lumber_stack_horizontal_partial_spring"
	z = -20

[r6h_plank]
	sprite = "spr_prop_lumber_plank_vertical_medium_spring"
	z = 0

[r6h_split_plank]
	sprite = "spr_prop_lumber_plank_vertical_small_spring"
	z = 0

[r6h_wood_piece]
	sprite = "spr_prop_lumber_plank_horizontal_medium_spring"
	z = -20

[r6h_birdhouse_no_roof]
	sprite = "spr_prop_birdhouse_no_roof_spring"
	z = -20

[r6h_birdhouse_roof]
	sprite = "spr_prop_birdhouse_roof"
	z = -20

[r6h_sawdust_big]
	sprite = "spr_prop_sawdust_medium"
	z = -20

[r6h_sawdust_small]
	sprite = "spr_prop_sawdust_small"
	z = -20

[r6h_paint_can]
	sprite = "spr_prop_paint_bucket_and_brush_spring"
	z = -20

[r6h_birdhouse_paintless]
	sprite = "spr_prop_birdhouse_unpainted_spring"
	z = -20

[r6h_birdhouse_finished]
	sprite = "spr_prop_birdhouse_finished_spring"
	z = -20

[tft_bathhouse_fire_tablet]
	item = "fire_tablet_rubbing"
	z = -20

[b8h_contract]
	sprite = "spr_ui_item_torn_contract"
	z = -50                              # placeholder value

[b8h_table]
	sprite = "spr_prop_dining_table_spring"
	z = -20                                 # placeholder value

[b8h_stool]
	sprite = "spr_inn_barstool_spring_broken"
	z = 0

[b8h_dish]
	sprite = "spr_prop_dining_table_dish"
	z = -30                               # placeholder value

[b8h_wine_wheedle]
	sprite = "spr_prop_wine"
	z = -20

[a8h_plate_stack]
	sprite = "spr_prop_stacked_plates_main"
	z = -50                                 # placeholder value

[a8h_tray]
	sprite = "spr_prop_tea_tray_main"
	z = -50                           # placeholder value

[a8h_tea]
	sprite = "spr_prop_green_tea"
	z = -20

[a8h_tea_adeline_ab]
	sprite = "spr_prop_green_tea"
	z = -50

[a8h_lemon_pie]
	item = "lemon_pie"
	z = -10

[a8h_chair]
	sprite = "spr_manor_adeline_room_armchair_spring"
	z = 14

[a8h_chair_top]
	sprite = "spr_manor_adeline_room_armchair_spring_top"
	z = 37

[a8h_chair_shadow]
	sprite = "spr_manor_adeline_room_armchair_shadow"
	z = 10

[c8h_blanket]
	sprite = "spr_prop_picnic_rug_green"
	z = 25

[c8h_cushion]
	sprite = "spr_prop_cushion_yellow_main"
	z = 5

[c8h_basket_horizontal_closed]
	sprite = "spr_prop_picnic_basket_green_main_horizontal_closed"
	z = -20

[c8h_basket_horizontal_open]
	sprite = "spr_prop_picnic_basket_green_main_horizontal_open"
	z = -20

[c8h_basket_vertical_closed]
	sprite = "spr_prop_picnic_basket_green_main_vertical_closed"
	z = -20

[c8h_basket_vertical_open]
	sprite = "spr_prop_picnic_basket_green_main_vertical_open"
	z = -20

[c8h_sandwiches]
	sprite = "spr_prop_cucumber_sandwiches_main"
	z = -10

[c8h_flower_pot]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_open3"
	z = -10

[c8h_flower_pot_yellow_sprouting]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_opening4_friendship"
	z = -10

[c8h_flower_pot_yellow_sprouted]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_open4_friendship"
	z = -10

[c8h_flower_pot_pink_sprouting]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_opening4_romance"
	z = -10

[c8h_flower_pot_pink_sprouted]
	sprite = "spr_celinecottage_seed_pot_sprout_spring_open4_romance"
	z = -10

[c8h_tea]
	sprite = "spr_prop_black_tea"
	z = -10

[c8h_sandwiches_summit]
	sprite = "spr_prop_cucumber_sandwiches_main"
	z = -20

[h8h_quiche]
	item = "vegetable_quiche"
	z = -10

[h8h_empty_plate]
	sprite = "spr_prop_empty_plate_green"
	z = -10

[r8h_table_runner]
	sprite = "spr_prop_table_runner_cooking_contest"
	z = -10

[r8h_napkin_south]
	sprite = "spr_prop_napkin_south"
	z = -10

[r8h_napkin_east]
	sprite = "spr_prop_napkin_east"
	z = -10

[r8h_napkin_north]
	sprite = "spr_prop_napkin_north"
	z = -10

[r8h_napkin_west]
	sprite = "spr_prop_napkin_west"
	z = -10

[j8h_footprints]
	sprite = "spr_prop_bath_footsteps"
	z = -40

[r8h_table_setting]
	sprite = "spr_inn_table_runner_spring"
	z = -10

[r8h_pan]
	sprite = "spr_inn_stove_pan_spring_food"
	z = 0

[r8h_napkin]
	sprite = "spr_prop_napkin_north"
	z = -10

[r8h_tea]
	sprite = "spr_prop_green_tea"
	z = -10

[r8h_dragonhorn]
	item = "dragon_horn_mushroom_with_thyme"
	z = -10

[r8h_dragonhorn_empty]
	sprite = "spr_prop_empty_plate_dragonshornthyme"
	z = -10

[r8h_curry]
	sprite = "spr_prop_mistrian_vegetable_curry"
	z = -10

[r8h_curry_empty]
	sprite = "spr_prop_empty_bowl_mistrian_vegetable_curry"
	z = -10

[r8h_pie]
	item = "wildberry_pie"
	z = -10

[r8h_pie_empty]
	sprite = "spr_prop_empty_plate_wildberry_pie"
	z = -10

[e8h_chest_and_pants]
	sprite = "spr_ui_item_dragonsworn_chest_and_pants"
	z = -5

[e8h_open_chest]
	sprite = "spr_dragonsworn_glade_storage_chest_spring_opened"
	z = -5

[e8h_open_chest_opening]
	sprite = "spr_dragonsworn_glade_storage_chest_spring_opening"
	z = -5

[e8h_open_chest_winter]
	sprite = "spr_dragonsworn_glade_storage_chest_winter_opened"
	z = -5

[e8h_open_chest_winter_opening]
	sprite = "spr_dragonsworn_glade_storage_chest_winter_opening"
	z = -5

[m8h_mushroom]
	sprite = "spr_forage_upper_mines_mushroom_stage1"

[c8h_onion_soup]
	item = "onion_soup"
	z = -10

[c8h_mushroom_rice]
	item = "mushroom_rice"
	z = -10

[c8h_onion_soup_empty]
	sprite = "spr_prop_empty_bowl_onion_soup"
	z = -10

[c8h_mushroom_rice_empty]
	sprite = "spr_prop_empty_bowl_mushroomrice"
	z = -10

[c8h_outside_pouf]
	sprite = "spr_caldarus_house_pouf_spring"
	z = 5

[utcs1_blueprints]
	sprite = "spr_prop_blueprint_big"
	z = -20

[r8h_stool]
	sprite = "spr_carpenter_house_f2_stool2_spring"
	z = 5

[r8h_berry_bush_spring]
	sprite = "spr_bush_wildberry_spring_stage2"
	z = -20

[r8h_berry_bush_spring_empty]
	sprite = "spr_bush_wildberry_spring_stage1"
	z = -20

[r8h_berry_bush_summer]
	sprite = "spr_bush_wildberry_summer_stage2"
	z = -20

[r8h_berry_bush_summer_empty]
	sprite = "spr_bush_wildberry_spring_stage1"
	z = -20

[r8h_berry_bush_fall]
	sprite = "spr_bush_wildberry_autumn_stage2"
	z = -20

[r8h_berry_bush_fall_empty]
	sprite = "spr_bush_wildberry_spring_stage1"
	z = -20

[r8h_berry_bush_winter]
	sprite = "spr_bush_wintergreen_winter_stage2"
	z = -20

[r8h_berry_bush_winter_empty]
	sprite = "spr_bush_wintergreen_winter_stage1"
	z = -20

[inn_date_plate]
	sprite = "spr_prop_mistrian_vegetable_curry"
	z = -10

[inn_date_empty_plate]
	sprite = "spr_prop_empty_bowl_mistrian_vegetable_curry"
	z = -10

[dwpd_blanket]
	sprite = "spr_decor_picnic_rug_yellow_spring_south"
	z = 15

[dwpd_pouf]
	sprite = "spr_caldarus_house_pouf_spring"
	z = 5

[dwpd_picnic_basket]
	sprite = "spr_decor_picnic_basket_red_spring_south"
	z = -20

[pd_flower]
	sprite = "spr_flower_tulip_stage4"
	z = -10

[bd_seashell]
	sprite = "spr_shell_small_blue_conch_main"
	z = -10

[gcd_gem_unpolished]
	item = "rough_gemstone"
	z = -50

[gcd_gem_polished]
	item = "ore_ruby"
	z = -50

[v8h_cliffblossom]
	sprite = "spr_prop_cliffblossom"
	z = -1000

[v8h_stone]
	sprite = "spr_prop_cracked_rock_spring"
	z = -10

[v8h_stone_winter]
	sprite = "spr_prop_cracked_rock_winter"
	z = -10

[v8h_ladder_vertical]
	sprite = "spr_prop_ladder_main"
	z = -10

[v8h_ladder_horizontal]
	sprite = "spr_prop_ladder_horizontal_main"
	z = -10

[v8h_stone_gap]
	sprite = "spr_prop_hole_in_wall_spring"
	z = -1000

[v8h_stone_gap_winter]
	sprite = "spr_prop_hole_in_wall_winter"
	z = -1000

[v8h_chair]
	sprite = "spr_valenclinic_f1_chair_spring"
	z = 0

[v8h_potion]
	item = "lurid_colored_drink"
	z = -20

[v8h_stone_falling]
	sprite = "spr_prop_stone_falling_spring"
	z = -1000

[v8h_stone_falling_winter]
	sprite = "spr_prop_stone_falling_winter"
	z = -1000

[rs1_spell]
	sprite = "spr_prop_inverted_void_sight_icon"
	z = -50

[rs2_void_mass]
	sprite = "spr_ui_item_void_mass"
	z = -50

[pq2_spell]
	sprite = "spr_ui_journal_magic_sacred_light_spell_icon_main"
	z = -50

[dt3_void_sight]
	sprite = "spr_prop_void_sight_icon"
	z = -50

[s8h_cake]
	item = "strawberry_shortcake"
	z = -50

[s8h_portal_1_opening]
	sprite = "spr_cutscene_misty_portal_castle_opening"
	z = -50

[s8h_portal_1]
	sprite = "spr_cutscene_misty_portal_castle_idle"
	z = -50

[s8h_portal_1_closing]
	sprite = "spr_cutscene_misty_portal_castle_closing"
	z = -50

[s8h_portal_2_opening]
	sprite = "spr_cutscene_misty_portal_treasure_opening"
	z = -50

[s8h_portal_2]
	sprite = "spr_cutscene_misty_portal_treasure_idle"
	z = -50

[s8h_portal_2_closing]
	sprite = "spr_cutscene_misty_portal_treasure_closing"
	z = -50

[s8h_portal_3_opening]
	sprite = "spr_cutscene_misty_portal_hands_opening"
	z = -50

[s8h_portal_3]
	sprite = "spr_cutscene_misty_portal_hands_idle"
	z = -50

[s8h_portal_3_closing]
	sprite = "spr_cutscene_misty_portal_hands_closing"
	z = -50

[wed_side_candle_left_unlit]
	sprite = "spr_town_wedding_candle_left_off"
	z = -20

[wed_side_candle_right_unlit]
	sprite = "spr_town_wedding_candle_right_off"
	z = -20

[wed_side_candle_left_lit]
	sprite = "spr_town_wedding_candle_left_on"
	z = -20

[wed_side_candle_right_lit]
	sprite = "spr_town_wedding_candle_right_on"
	z = -20

[wed_central_candle_unlit]
	sprite = "spr_town_wedding_candle_middle_off"
	z = -20

[wed_central_candle_lit]
	sprite = "spr_town_wedding_candle_middle_on"
	z = -20

[gb0_feather]
	item = "mystical_feather"
	z = -9999

[gb_bird]
	sprite = "spr_npc_great_bird_spring"
	z = -9999

[gb1_star_appear]
	sprite = "spr_cutscene_great_bird_star_appear"
	z = -9999

[gb1_star_idle]
	sprite = "spr_cutscene_great_bird_star_idle"
	z = -9999

[gb0_star_bkg]
    sprite = "spr_cutscene_great_bird_background"
    z = -9000

[gb1_star_bkg]
    sprite = "spr_cutscene_great_bird_background"
    z = -9000

[sd_star_bkg]
    sprite = "spr_cutscene_great_bird_background"
    z = -9000

[sd_bird]
	sprite = "spr_npc_great_bird_spring" # replace with great bird with baby, do we want to do a crossfade have the baby essentially fade in on the bird?
	z = -9999