# How many levels are within each rank
levels_per_rank = 10
# The rewards Ari gets for completing a given level.
rewards = [
	# Wood
	{ purse = 100 },
	{ cosmetic = "head_adventurer_hood" },
	{ purse = 150 },
	{ cosmetic = "top_adventurer" },
	{ purse = 150 },
	{ cosmetic = "pants_adventurer" },
	{ purse = 200 },
	{ cosmetic = "shoes_boots_adventurer" },
	{ purse = 250 },
	{ item = "stamina_up" },
	# Stone
	{ purse = 100 },
	{ item = "stone_bench_v2" },
	{ purse = 150 },
	{ item = "stone_storage_chest_v2" },
	{ purse = 150 },
	{ item = "large_paving_stone_v2" },
	{ purse = 200 },
	{ item = "stone_lamp_v2" },
	{ item = "stone_table_v2" },
	{ item = "stamina_up" },
	# Copper
	{ purse = 100 },
	{ cosmetic = "top_ranger_jacket" },
	{ purse = 150 },
	{ cosmetic = "top_ranger" },
	{ purse = 150 },
	{ cosmetic = "shoes_boots_ranger" },
	{ purse = 200 },
	{ cosmetic = "head_ranger_leaves" },
	{ item = "training_dummy_sapling" },
	{ item = "stamina_up" },
	# Ruby
	{ purse = 100 },
	{ item = "mistria_wall_map_v1" },
	{ purse = 150 },
	{ item = "mistria_history_book_v1" },
	{ purse = 150 },
	{ item = "ornate_flagstone_v2" },
	{ purse = 200 },
	{ item = "dragon_priestess_fountain_v2" },
	{ item = "stone_dragon_figure_v2" },
	{ item = "stamina_up" },
	# Iron
	{ purse = 100 },
	{ cosmetic = "top_caldosian_overcoat" },
	{ purse = 150 },
	{ cosmetic = "face_gear_caldosian_moon_earrings" },
	{ purse = 150 },
	{ cosmetic = "shoes_boots_caldosian" },
	{ purse = 200 },
	{ cosmetic = "head_caldosian_hat" },
	{ item = "mistria_history_scroll_v1" },
	{ item = "stamina_up" },

	# Sapphire
	{ purse = 100 },
	{ item = "cottage_garden_planter_v1" },
	{ purse = 150 },
	{ item = "cottage_garden_trellis_v3" },
	{ purse = 150 },
	{ item = "cottage_garden_workbench_v2" },
	{ purse = 200 },
	{ item = "cottage_garden_arch_v2" },
	{ item = "cottage_garden_shed_v2" },
	{ item = "stamina_up" },
	# Silver
	{ purse = 100 },
	{ cosmetic = "back_gear_noble_cape" },
	{ purse = 150 },
	{ cosmetic = "top_noble_jacket" },
	{ purse = 150 },
	{ cosmetic = "shoes_boots_noble" },
	{ purse = 200 },
	{ cosmetic = "top_noble_tunic" },
	{ cosmetic = "head_noble_hat" },
	{ item = "stamina_up" },
	# Emerald
	{ purse = 200 },
	{ item = "emerald_chair_v1" },
	{ purse = 250 },
	{ item = "emerald_nightstand_v1" },
	{ purse = 300 },
	{ item = "emerald_bed_v1" },
	{ purse = 350 },
	{ item = "emerald_wallpaper_v1" },
	{ item = "emerald_rug_v1" },
	{ item = "essence_stone_large" },
	# Gold
	{ purse = 300 },
	{ cosmetic = "back_gear_exalted_cloak" },
	{ purse = 350 },
	{ cosmetic = "top_exalted" },
	{ purse = 400 },
	{ cosmetic = "pants_exalted" },
	{ purse = 450 },
	{ cosmetic = "shoes_boots_exalted" },
	{ cosmetic = "head_exalted_crown" },
	{ item = "essence_stone_large" },
	# Diamond
	{ purse = 300 },
	{ item = "hero_shield_bronze" },
	{ purse = 350 },
	{ item = "royal_chest_red" },
	{ purse = 400 },
	{ item = "treasure_box_gold" },
	{ purse = 450 },
	{ item = "treasure_box_gold" },
	{ purse = 500 },
	{ item = "essence_stone_large" },

]

[[ranks]]
	name = "Wood"
	sprite = "spr_ui_renown_status_star_icon_wood"
	small_sprite = "spr_ui_journal_inventory_renown_wood_icon"

[[ranks]]
	name = "Stone"
	sprite = "spr_ui_renown_status_star_icon_stone"
	small_sprite = "spr_ui_journal_inventory_renown_stone_icon"

[[ranks]]
	name = "Copper"
	sprite = "spr_ui_renown_status_star_icon_copper"
	small_sprite = "spr_ui_journal_inventory_renown_copper_icon"

[[ranks]]
	name = "Ruby"
	sprite = "spr_ui_renown_status_star_icon_ruby"
	small_sprite = "spr_ui_journal_inventory_renown_ruby_icon"

[[ranks]]
	name = "Iron"
	sprite = "spr_ui_renown_status_star_icon_iron"
	small_sprite = "spr_ui_journal_inventory_renown_iron_icon"

[[ranks]]
	name = "Sapphire"
	sprite = "spr_ui_renown_status_star_icon_sapphire"
	small_sprite = "spr_ui_journal_inventory_renown_sapphire_icon"

[[ranks]]
	name = "Silver"
	sprite = "spr_ui_renown_status_star_icon_silver"
	small_sprite = "spr_ui_journal_inventory_renown_silver_icon"

[[ranks]]
	name = "Emerald"
	sprite = "spr_ui_renown_status_star_icon_emerald"
	small_sprite = "spr_ui_journal_inventory_renown_emerald_icon"

[[ranks]]
	name = "Gold"
	sprite = "spr_ui_renown_status_star_icon_gold"
	small_sprite = "spr_ui_journal_inventory_renown_gold_icon"

[[ranks]]
	name = "Diamond"
	sprite = "spr_ui_renown_status_star_icon_diamond"
	small_sprite = "spr_ui_journal_inventory_renown_diamond_icon"

[[ranks]]
	name = "Mistril"
	sprite = "spr_ui_renown_status_star_icon_mistril"
	small_sprite = "spr_ui_journal_inventory_renown_mistril_icon"
