[or]

[invert]

[has_perk]

# lol look, what would you name it
#
# i refuse to write this explicitly using has_perk and or, i want to be fast
[has_at_least_one_tier_five_perk_per_category]

[seen_cutscene]

[scene_is_playing]

[completed_quest]

[completed_quests_in_category]

[quest_is_active]

[quest_is_at_stage]

[reached_skill_level]

[reached_heart_level]

[is_day_type]

[is_season]

[in_time_range]

[in_date_range]

[is_festival_day]

[met_npc]

[shipped_tag]

[shipped_item]

[defeated_monster]

[has_item]

[has_gold]

[donated_item]

[unlocked_animal]

[received_letter]

[world_fact_is]

[acquired_item]

[supplied_items]

[reached_date]

[is_player_birthday]

[is_dating_someone]

[is_dating]

[is_spouse]

[is_partner]

[is_best_friend]

[has_spouse]

[has_fiance]

[has_best_friend]

[has_partner]

[reached_mines_level]

[reached_renown_level]

[earned_gold]

[eligible_for_crown_request]

[has_animal_of_rank]

[acquired_animals]

[end_of_day_status]

[has_any_animal]

[has_upper_floor]

[has_left_house_today]

[has_coop]

[has_barn]

[has_home_upgrade]

[completed_museum_set_within]

[completed_museum_set]

[completed_museum]

[good_gifts_given]

[reached_items_cooked]

[reached_items_woodcrafted]

[reached_items_smithed]

[reached_enemies_defeated]

[reached_crops_harvested]

[reached_bugs_caught]

[reached_fish_caught]

[baby_is_due]

[has_child]

[reached_essence]

[completed_almanac]

[all_npc_gifts_discovered]

[has_child_at_age]

[custom]

[sleep]
	seen_cutscene = "farm_introduction"

[use_dragon_shrine]
	met_npc = "caldarus"

[collect_essence]
	seen_cutscene = "the_unusual_tree_pt_2"

[repaired_dragon_shrine]
	seen_cutscene = "the_unusual_tree_pt_1"

[saturday_market_unlocked]
	seen_cutscene = "repair_the_bridge_pt_2"

[opened_mines]
	seen_cutscene = "unlocking_the_mines_pt_2"

[use_water_tablet]
	seen_cutscene = "translating_the_water_tablet"

[broke_water_seal]
	seen_cutscene = "break_water_seal"

[broke_earth_seal]
	seen_cutscene = "break_earth_seal"

[broke_fire_seal]
	seen_cutscene = "break_fire_seal"

[speak_to_statue]
	seen_cutscene = "the_unusual_tree_pt_2"

[use_earth_tablet]
	seen_cutscene = "translating_the_earth_tablet"

[use_fire_tablet]
	seen_cutscene = "translating_the_fire_tablet"

[celine_plant_stage_zero]
	seen_cutscene = "celine_two_hearts"

[celine_plant_stage_one]
	seen_cutscene = "celine_four_hearts"

[celine_plant_stage_two]
	seen_cutscene = "celine_six_hearts"

[celine_plant_stage_three_romantic]
	is_partner = "celine"

[celine_plant_stage_three_best_friend]
	is_best_friend = "celine"

[ryis_stump_removed]
	seen_cutscene = "ryis_four_hearts"

[ryis_tree_intermediate]
	reached_heart_level = { ryis = 5 }
    ryis_tree_planted = true

[ryis_tree_planted]
	seen_cutscene = "ryis_four_hearts"

[ryis_tree_grown]
	seen_cutscene = "ryis_six_hearts"

[eiland_armor_one]
	seen_cutscene = "eiland_two_hearts"

[eiland_armor_two]
	seen_cutscene = "eiland_four_hearts"

[eiland_armor_three]
	seen_cutscene = "eiland_six_hearts"

[eiland_armor_four]
	seen_cutscene = "eiland_eight_hearts"

[repaired_eastern_road_bridge]
	seen_cutscene = "repair_the_bridge_pt_2"

[unlocked_refining]
	seen_cutscene = "stone_refinery_pt_2"

[unlocked_deep_woods]
	seen_cutscene = "destroy_vines_eastern_road"

[repaired_general_store]
	seen_cutscene = "repair_the_general_store_pt_2"

[repaired_carpenters_shop]
	seen_cutscene = "upgrade_the_carpenters_shop_pt_2"

[broke_bell]
	seen_cutscene = "repair_the_bell_tower_pt_1"
	invert.or = [{ repaired_bell_tower = true }, { repaired_bell_tower_door = true }]

[repaired_bell_tower_door]
	seen_cutscene = "repair_the_bell_tower_pt_2"

[repaired_bell_tower]
	seen_cutscene = "repair_the_bell_tower_pt_2"

[repaired_inn]
	seen_cutscene = "repair_the_inn_pt_2"

[repaired_mill]
	seen_cutscene = "repair_the_mill_pt_2"

[unlocked_summit]
	seen_cutscene = "repair_the_summit_stairs"

[repaired_beach_bridge]
	seen_cutscene = "repair_the_beach_bridge_pt_2"

[unlocked_narrows_secret]
	seen_cutscene = "narrows_secret"

[unlocked_beach_secret]
	seen_cutscene = "beach_secret"

[repaired_horse_statue]
	seen_cutscene = "find_the_weathervane_setup"

[unlocked_dragonsworn_glade]
	seen_cutscene = "eiland_eight_hearts"

[repaired_haydens_farm]
	seen_cutscene = "repair_haydens_barn_pt_2"

[unlocked_lost_and_found]
	seen_cutscene = "lost_and_found"

[unlocked_pq_ne]
	seen_cutscene = "unlock_pq_ne"

[unlocked_pq_door]
	seen_cutscene = "priestess_quarters_pt_2"

[has_void_sight]
	seen_cutscene = "break_ruins_seal_pt_1"

[opened_void_portal]
	seen_cutscene = "break_ruins_seal_pt_1"

[broke_ruins_seal]
	seen_cutscene = "break_ruins_seal_pt_3"

[seridia_transformed]
	seen_cutscene = "dragon_tablet_pt_4"

[has_dragonsworn_armor]
	seen_cutscene = "dragon_tablet_pt_3"

[in_glade_flashback]
	scene_is_playing = "dragon_tablet_pt_4"

[priestess_crystal_removed]
	or = [{ scene_is_playing = "dragon_tablet_pt_4" }, { seen_cutscene = "dragon_tablet_pt_4" }]

[closed_final_seal]
	seen_cutscene = "dragon_tablet_pt_4"

[seridia_house_open]
	seen_cutscene = "dragon_tablet_pt_4"

[repaired_town_plaza]
    seen_cutscene = "upgrade_the_saturday_market_plaza"

[reached_mistril_rank]
    seen_cutscene = "mistril_rank"