[vars]
	common_forage_restore = 3
	rare_forage_restore = 5
	fast_crop_restore = 6
	regrow_crop_restore = 8
	medium_crop_restore = 10
	fruit_crop_restore = 10
	unlockable_regrow_crop_restore = 10
	slow_crop_restore = 12
	unlockable_medium_crop_restore = 12
	small_common_fish_restore = 5
	medium_common_fish_restore = 6
	large_common_fish_restore = 8
	small_less_common_fish_restore = 4
	medium_less_common_fish_restore = 5
	large_less_common_fish_restore = 6
	small_rare_fish_restore = 5
	medium_rare_fish_restore = 6
	large_rare_fish_restore = 7
	dive_item_restore = 3

[[stars]]
	restoration_multiplier = 3
	value_expr = "self.recipe * 1.1"

[[stars]]
	restoration_multiplier = 3.5
	value_expr = "self.recipe * 1.15"

[[stars]]
	restoration_multiplier = 3.75
	value_expr = "self.recipe * 1.2"

[[stars]]
	restoration_multiplier = 4
	value_expr = "self.recipe * 1.25"

[[stars]]
	restoration_multiplier = 4.25
	value_expr = "self.recipe * 1.3"
