[tool_strong]
	length = 10
	strength = 1

[tool_weak]
	length = 10
	strength = 0.25

[tool_invalid]
	length = 5
	strength = 0.25

[furniture_place]
	length = 10
	strength = 0.25

[furniture_remove]
	length = 20
	strength = 0.5

[fishing_strong]
	length = 20
	strength = 1

[fishing_weak]
	length = 10
	strength = 0.4

[fishing_success]
	length = 20
	strength = 1

[bobber_in_water]
	length = 10
	strength = 1

[downsmash_fail]
	length = 15
	strength = 0.75

[sword_strong]
	length = 20
	strength = 1

[sword_weak]
	length = 20
	strength = 0.75

[hurt]
	length = 20
	strength = 1

[breakable_break]
	length = 10
	strength = 0.4

[building_complete]
	length = 20
	strength = 1

[pet]
	length = 20
	strength = 0.5

[hold_to_use]
	# this is a lie, and we hack it to be as long as we want
	length = 40
	strength = 0.25

[spell_execute]
	length = 20
	strength = 1

[item_collect]
	length = 5
	strength = 0.25
