[water]
	tablet_sprite = "spr_water_seal_tablet_spring"
	quest = "the_water_tablet"
	stage = 1
	cutscene = "break_water_seal"

[earth]
	tablet_sprite = "spr_earth_seal_tablet_spring"
	quest = "the_earth_tablet"
	stage = 1
	cutscene = "break_earth_seal"

[fire]
	tablet_sprite = "spr_fire_seal_tablet_spring"
	quest = "breaking_the_fire_seal"
	stage = 0
	cutscene = "break_fire_seal"

[priestess]
	tablet_sprite = "spr_priestess_quarters_tablet_main"
	quest = "find_the_magic_key"
	stage = 3

[ruins]
	tablet_sprite = "spr_ruins_seal_tablet_spring"
	quest = "breaking_the_ruins_seal"
	stage = 0
	cutscene = "break_ruins_seal_pt_3"

[void]
	tablet_sprite = "spr_void_seal_cauldron_main"
	quest = "creating_the_void_mass"
	stage = 0
	cutscene = "break_ruins_seal_pt_2"

[final]
	tablet_sprite = "spr_seridias_chamber_tablet_locked"
	location = "seridias_chamber"
	quest = "breaking_the_final_seal"
	stage = 0
	cutscene = "dragon_tablet_pt_4"