[archaeology]
	sprite = "spr_ui_skill_icon_archaeology"

[blacksmithing]
	sprite = "spr_ui_skill_icon_blacksmithing"

[cooking]
	sprite = "spr_ui_skill_icon_cooking"

[farming]
	sprite = "spr_ui_skill_icon_farming"

[fishing]
	sprite = "spr_ui_skill_icon_fishing"

[ranching]
	sprite = "spr_ui_skill_icon_ranching"

[woodcrafting]
	sprite = "spr_ui_skill_icon_woodcrafting"

[combat]
	sprite = "spr_ui_skill_icon_combat"

[mining]
	sprite = "spr_ui_skill_icon_mining"