[farm_boy]
	name = "Farm Boy"
	icon = "spr_ui_item_song_crystal_farm_boy"
	track = "Music/Crystal Tracks/FarmBoy"

[pink_twintails]
	name = "Pink Twintails"
	icon = "spr_ui_item_song_crystal_pink_twintails"
	track = "Music/Crystal Tracks/PinkTwintails"

[crystal_caves]
	name = "Crystal Caves"
	icon = "spr_ui_item_song_crystal_crystal_caves"
	track = "Music/Crystal Tracks/CrystalCaves"

[misty_pasture]
	name = "Misty Pasture"
	icon = "spr_ui_item_song_crystal_misty_pasture"
	track = "Music/Crystal Tracks/MistyPasture"

[purple_potions]
	name = "Purple Potions"
	icon = "spr_ui_item_song_crystal_purple_potions"
	track = "Music/Crystal Tracks/PurplePotions"

[heros_journey]
	name = "Hero's Journey"
	icon = "spr_ui_item_song_crystal_heros_journey"
	track = "Music/Crystal Tracks/Hero'sJourney"

[five_more_minutes]
	name = "Five More Minutes"
	icon = "spr_ui_item_song_crystal_five_more_minutes"
	track = "Music/Crystal Tracks/FiveMoreMinutes"

[dream_lobby]
	name = "Dream Lobby"
	icon = "spr_ui_item_song_crystal_dream_lobby"
	track = "Music/Crystal Tracks/DreamLobby"

[rainy_window]
	name = "Rainy Window"
	icon = "spr_ui_item_song_crystal_rainy_window"
	track = "Music/Crystal Tracks/RainyWindow"

[another_tower]
	name = "Another Tower"
	icon = "spr_ui_item_song_crystal_another_tower"
	track = "Music/Location Tracks/TowerRoom"

[adelines_theme]
	name = "Adeline's Theme: The Smell of Drying Ink"
	icon = "spr_ui_item_song_crystal_adelines_theme"
	track = "Music/Npc Tracks/Adeline"

[balors_theme]
	name = "Balor's Theme: Fair Weather"
	icon = "spr_ui_item_song_crystal_balors_theme"
	track = "Music/Npc Tracks/Balor"

[caldarus_theme]
	name = "Caldarus' Theme: The Sleeping Dragon"
	icon = "spr_ui_item_song_crystal_caldarus_theme"
	track = "Music/Npc Tracks/Caldarus"

[celines_theme]
	name = "Celine's Theme: Flower in Bloom"
	icon = "spr_ui_item_song_crystal_celines_theme"
	track = "Music/Npc Tracks/Celine"

[eilands_theme]
	name = "Eiland's Theme: Roots, Intertwined"
	icon = "spr_ui_item_song_crystal_eilands_theme"
	track = "Music/Npc Tracks/Eiland"

[haydens_theme]
	name = "Hayden's Theme: Roll Up Your Sleeves!"
	icon = "spr_ui_item_song_crystal_haydens_theme"
	track = "Music/Npc Tracks/Hayden"

[junipers_theme]
	name = "Juniper's Theme: Something's Brewing"
	icon = "spr_ui_item_song_crystal_junipers_theme"
	track = "Music/Npc Tracks/Juniper"

[marchs_theme]
	name = "March's Theme: What Do You Want?"
	icon = "spr_ui_item_song_crystal_marchs_theme"
	track = "Music/Npc Tracks/March"

[reinas_theme]
	name = "Reina's Theme: Wildberry Pie"
	icon = "spr_ui_item_song_crystal_reinas_theme"
	track = "Music/Npc Tracks/Reina"

[ryis_theme]
	name = "Ryis' Theme: Birdsong"
	icon = "spr_ui_item_song_crystal_ryis_theme"
	track = "Music/Npc Tracks/Ryis"

[seridias_theme]
	name = "Seridia's Theme: Rebirth"
	icon = "spr_ui_item_song_crystal_seridias_theme"
	track = "Music/Npc Tracks/Seridia"

[valens_theme]
	name = "Valen's Theme: Cactus Blossom"
	icon = "spr_ui_item_song_crystal_valens_theme"
	track = "Music/Npc Tracks/Valen"
