[default]
	name = "<n/a>"
	description = "<n/a>"
	cost = 4
	mana_modifier = 4
	icon_key = "spr_illegal_16"
	upper_icon = "spr_illegal_16"
	ribbon = "spr_illegal_16"

[full_restore]
	name = "Full Restore"
	description = "Restores all of your Stamina and HP when cast."
	type = "Healing"
	cost = 4
	icon_key = "spr_ui_journal_magic_restore_spell_icon"
	upper_icon = "spr_ui_journal_magic_restore_card_icon"
	ribbon = "spr_ui_journal_magic_card_ribbon_restore"

[summon_rain]
	name = "Summon Rain"
	description = "Summons a brief rain storm that waters all of your crops when cast."
	type = "Farming"
	cost = 4
	icon_key = "spr_ui_journal_magic_rain_spell_icon"
	upper_icon = "spr_ui_journal_magic_rain_card_icon"
	ribbon = "spr_ui_journal_magic_card_ribbon_rain"
	indoor_duration = 300
    indoor_fade_length = 120

[growth]
	name = "Growth"
	description = "Fully grows crops in a 3x3 area when cast. It can also progress tree growth by 1 stage."
	type = "Farming"
	cost = 8
	icon_key = "spr_ui_journal_magic_growth_spell_icon"
	upper_icon = "spr_ui_journal_magic_growth_card_icon"
	ribbon = "spr_ui_journal_magic_card_ribbon_growth"

[fire_breath]
	name = "Dragon's Breath"
	description = "Projects a stream of fire that can be used to destroy objects and monsters for a short time."
	type = "Offense"
	cost = 8
	icon_key = "spr_ui_journal_magic_fire_spell_icon"
	upper_icon = "spr_ui_journal_magic_fire_card_icon"
	ribbon = "spr_ui_journal_magic_card_ribbon_fire"

[sacred_light]
	name = "Sacred Light"
	description = "Illuminates dark floors in the Ruins deep underground."
	type = "Utility"
	cost = 4
	icon_key = "spr_ui_journal_magic_sacred_light_spell_icon"
	upper_icon = "spr_ui_journal_magic_sacred_light_card_icon"
	ribbon = "spr_ui_journal_magic_card_ribbon_sacred_light"
