[times]
	wake_up = { hour = 6, minute = 10 }
	go_out = { hour = 11, minute = 0 }
	come_home = { hour = 19, minute = 0 }
	sleep = { hour = 24, minute = 0 }

[wedding_parties]

    [wedding_parties.adeline]
        spouse_party_0 = "celine"
        spouse_party_1 = "reina"
        spouse_guest_0 = "wiscar"
        spouse_guest_1 = "linnet"
        standing_speaker_0 = "wiscar"
        standing_speaker_1 = "linnet"

    [wedding_parties.balor]
        spouse_party_0 = "hayden"
        spouse_party_1 = "hemlock"
        standing_speaker_0 = "josephine"

    [wedding_parties.caldarus]
        spouse_party_0 = "celine"
        spouse_party_1 = "balor"
        standing_speaker_0 = "celine"

    [wedding_parties.celine]
        spouse_party_0 = "reina"
        spouse_party_1 = "adeline"
        standing_speaker_0 = "nora"
        standing_speaker_1 = "holt"

    [wedding_parties.eiland]
        spouse_party_0 = "errol"
        spouse_party_1 = "adeline"
        spouse_guest_0 = "wiscar"
        spouse_guest_1 = "linnet"
        standing_speaker_0 = "wiscar"
        standing_speaker_1 = "linnet"

    [wedding_parties.hayden]
        spouse_party_0 = "valen"
        spouse_party_1 = "henrietta"
        standing_speaker_0 = "valen"

    [wedding_parties.juniper]
        spouse_party_0 = "celine"
        spouse_party_1 = "dozy"
        standing_speaker_0 = "celine"
        standing_speaker_1 = "elsie"
        standing_speaker_2 = "dell"
        standing_speaker_3 = "luc"
        standing_speaker_4 = "maple"

    [wedding_parties.march]
        spouse_party_0 = "olric"
        spouse_party_1 = "ryis"
        standing_speaker_0 = "olric"

    [wedding_parties.reina]
        spouse_party_0 = "celine"
        spouse_party_1 = "adeline"
        standing_speaker_0 = "josephine"
        standing_speaker_1 = "hemlock"

    [wedding_parties.ryis]
        spouse_party_0 = "landen"
        spouse_party_1 = "march"
        spouse_guest_0 = "wynne"
        spouse_guest_1 = "darren"
        standing_speaker_0 = "wynne"
        standing_speaker_1 = "darren"

    [wedding_parties.seridia]
        spouse_party_0 = "olric"
        spouse_party_1 = "juniper"
        standing_speaker_0 = "juniper"

    [wedding_parties.valen]
        spouse_party_0 = "hayden"
        spouse_party_1 = "nora"
        standing_speaker_0 = "hayden"