bg_0_sky_parallax = 0.0
bg_1_stars_parallax = 2.5
bg_2_moon_parallax = 2.5
bg_3_horizonclouds_back_parallax = 2.2
bg_4_horizonclouds_front_parallax = 2.2
bg_5_mountains_parallax = 1.80
bg_6_woods_parallax = 1.55
bg_7_woodsdecals_parallax = 1.55

bg_0_sky_vertical_parallax = 0.20
bg_1_stars_vertical_parallax = 0.20
bg_2_moon_vertical_parallax = 0.20
bg_3_horizonclouds_back_vertical_parallax = 0.25
bg_4_horizonclouds_front_vertical_parallax = 0.25
bg_5_mountains_vertical_parallax = 0.30
bg_6_woods_vertical_parallax = 0.35
bg_7_woodsdecals_vertical_parallax = 0.35

day_start = 6
dusk_start = 17
night_start = 20

# This is the speed at which the visuals will transition from one day time to the next, or from one daytime to the layers weather sprites!
transition_speed_day = 0.0006
transition_speed_night = 0.0006
transition_speed_dusk = 0.0006
transition_speed_weather = 0.0006

# This is order dependant, whatever is earlier in the array gets drawn *before* whatever is drawn afterwards.
# If it's hard to understand, remember that everything after the background draws on top of the background
# And everything after the sky, draws on top of the sky!
layers = [
	"BG_0_Sky",
	"BG_1_Stars",
	"BG_2_Moon",
	"BG_3_HorizonClouds_Back",
	"BG_4_HorizonClouds_Front",
	"BG_5_Mountains",
	"BG_6_Woods",
	"BG_7_WoodsDecals",
]
