fade_speed = 0.0625

[normal]
	[normal.tool]
		valid = "spr_cursor_placement_tile_indicator_tool_valid"
		invalid = "spr_cursor_placement_tile_indicator_tool_invalid"
	[normal.furniture]
		valid = "spr_cursor_placement_tile_indicator_furniture_valid"
		invalid = "spr_cursor_placement_tile_indicator_furniture_invalid"

[winter]
	[winter.tool]
		valid = "spr_cursor_placement_tile_indicator_winter_tool_valid"
		invalid = "spr_cursor_placement_tile_indicator_winter_tool_invalid"
	[winter.furniture]
		valid = "spr_cursor_placement_tile_indicator_winter_furniture_valid"
		invalid = "spr_cursor_placement_tile_indicator_winter_furniture_invalid"
