[[spr_easternroad_pillar_spring]]
	offset = [-8, -40]
	size = [16, 40]

[[spr_easternroad_pillar_chipped_spring]]
	offset = [-8, -40]
	size = [16, 40]

[[spr_deep_woods_fir_tree_giant_spring]]
	offset = [-38, -50]
	size = [76, 48]

[[spr_deep_woods_fir_tree_giant_spring]]
	offset = [-28, -81]
	size = [56, 31]

[[spr_deep_woods_fir_tree_giant_spring]]
	offset = [-16, -106]
	size = [32, 25]

[[spr_deep_woods_fir_tree_large_spring]]
	offset = [-32, -43]
	size = [64, 41]

[[spr_deep_woods_fir_tree_large_spring]]
	offset = [-21, -73]
	size = [44, 30]

[[spr_deep_woods_fir_tree_large_spring]]
	offset = [-19, -88]
	size = [39, 15]

[[spr_deep_woods_fir_tree_medium_spring]]
	offset = [-29, -42]
	size = [58, 40]

[[spr_deep_woods_fir_tree_medium_spring]]
	offset = [-21, -59]
	size = [43, 17]

[[spr_deep_woods_fir_tree_medium_spring]]
	offset = [-10, -76]
	size = [20, 17]

[[spr_deep_woods_fir_tree_small_1_spring]]
	offset = [-25, -35]
	size = [49, 33]

[[spr_deep_woods_fir_tree_small_1_spring]]
	offset = [-19, -49]
	size = [35, 14]

[[spr_deep_woods_fir_tree_small_1_spring]]
	offset = [-8, -62]
	size = [14, 13]

[[spr_deep_woods_fir_tree_small_2_spring]]
	offset = [-25, -35]
	size = [49, 33]

[[spr_deep_woods_fir_tree_small_2_spring]]
	offset = [-19, -49]
	size = [35, 14]

[[spr_deep_woods_fir_tree_small_2_spring]]
	offset = [-8, -62]
	size = [14, 13]

[[spr_easternroad_big_fir_tree_spring]]
	offset = [-27, -51]
	size = [56, 51]

[[spr_easternroad_big_fir_tree_spring]]
	offset = [-19, -82]
	size = [37, 31]

[[spr_easternroad_big_fir_tree_spring]]
	offset = [-11, -93]
	size = [23, 11]

[[spr_town_tree_large_spring_idle]]
	offset = [-16, -31]
	size = [35, 32]

[[spr_town_tree_large_spring_idle]]
	offset = [-57, -64]
	size = [127, 33]

[[spr_town_tree_large_spring_idle]]
	offset = [-48, -91]
	size = [101, 27]

[[spr_town_tree_large_spring_idle]]
	offset = [-41, -106]
	size = [80, 15]

[[spr_town_tree_large_spring_idle]]
	offset = [-23, -120]
	size = [43, 14]
