[legendary]
	chance = 0.05
	small_roll = [
	]
	large_roll = [
	]

[rare]
	chance = 0.2
	small_roll = [
	]
	large_roll = [
	]

[common]
	chance = 1
	small_roll = [
		{ item = "copper_ingot", count = 2 },
		{ item = "iron_ingot" },
		{ item = "ore_ruby", count = 2 },
		{ item = "ore_emerald", count = 2 },
		{ item = "ore_sapphire", count = 2 },
		{ item = "wild_berry_jam" },
		{ item = "blueberry_jam" },
		{ item = "cabbage_slaw" },
		{ item = "spring_salad" },
		{ item = "latte" },
		{ cosmetic = "head_teapot" },
		{ cosmetic = "head_soup_pot" },
	]
	large_roll = [
		{ item = "silver_ingot", count = 2 },
		{ item = "berry_bowl" },
		{ recipe_scroll = "berry_bowl" },
		{ item = "fried_rice" },
		{ recipe_scroll = "fried_rice" },
		{ item = "spicy_cheddar_biscuit" },
		{ recipe_scroll = "spicy_cheddar_biscuit" },
		{ item = "dragon_ruins_pillar_v1" },
		{ item = "dragon_ruins_pillar_v2" },
		{ item = "dragon_road_wall", count = 5 },
		{ item = "dragon_wall_head_piece" },
		{ item = "dragon_wall_tail_piece" },
		{ item = "dragon_talon_chair" },
		{ item = "dragon_water_altar_v1" },
		{ item = "dragon_water_altar_v2" },
		{ item = "dragon_chest" },
		{ item = "dragon_lamp" },
		{ item = "dragon_stained_glass_window_v1" },
		{ item = "dragon_stained_glass_window_v2" },
		{ item = "dragon_fireplace" },
		{ item = "large_dragon_rug" },
		{ item = "medium_dragon_rug" },
		# { item = "dragon_relief_wallpaper" },
		# { item = "dragon_mosaic_flooring" },
	]
