[valen_four_hearts_turn_in]
kind = "gameplay_triggered"
actions = [
	{ cutscene = "valen_four_hearts" },
]
speaker = "valen"
portrait = "neutral"
local = "Oh, for my request? Thank you! Come with me and I'll get your payment."

[valen_four_hearts]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "think"
local = "I think two hundred tesserae is fitting for such high quality peat. Thank you again, [Ari]."
prompts = [
	{ local = "What are you going to use it for?", next = "1" },
	{ local = "Hey, can I see your creepy basement again?", next = "2" },
]

[valen_four_hearts.1]
portrait = "raised_eyebrow"
local = "An experiment on the nature of the bacteria in this soil."
next = "3"

[valen_four_hearts.2]
portrait = "ugh"
local = "I-it's not creepy!"
next = "3"

[valen_four_hearts.3]
portrait = "think"
local = "..."
next = "4"

[valen_four_hearts.4]
portrait = "neutral"
local = "Would you like to come down and see my work?"
next = "5"

[valen_four_hearts.5]
portrait = "happy"
local = "My family have been doctors for generations, this is our laboratory. Over the years, my ancestors made many contributions to the science of medicine."
next = "6"

[valen_four_hearts.6]
portrait = "neutral"
local = "One of whom invented the panacea I used to instantly cure Hayden's ankle."
next = "7"

[valen_four_hearts.7]
portrait = "raised_eyebrow"
local = "She made a stockpile of it that my family has been using over the years only when there's been a real need for it."
next = "8"

[valen_four_hearts.8]
portrait = "neutral"
local = "I've made it my life's work to recreate the recipe, which has been lost to time. I think I'm getting close..."
next = "9"

[valen_four_hearts.9]
portrait = "mad"
local = "I'm telling you this because I think I can trust you with this secret, [Ari]. I can trust you, yes?"
prompts = [
	{ local = "Your secret is safe with me.", next = "10" },
	{ local = "You wouldn't believe the secrets I'm already keeping!", next = "11" },
]

[valen_four_hearts.10]
portrait = "neutral"
local = "Thank you [Ari], it means a lot to me that I can trust you."
next = "12"

[valen_four_hearts.11]
portrait = "think"
local = "Interesting, I didn't think this sleepy little town had any juicy secrets!"
next = "12"

[valen_four_hearts.12]
portrait = "think"
local = "This is batch three hundred and twelve."
next = "13"

[valen_four_hearts.13]
portrait = "mad"
local = "It's a bit more... volatile than my previous batches."
next = "14"

[valen_four_hearts.14]
portrait = "neutral"
local = "[Ari], can I rely on you to make notes when I take it? I may become incapacitated."
prompts = [
	{ local = "Then let me drink it, for science!", next = "15" },
	{ local = "Can I drink it? It looks really tasty...", next = "16" },
]

[valen_four_hearts.15]
portrait = "think"
effect = "surprise"
local = "I've never had a volunteer before, that's very generous of you."
next = "17"

[valen_four_hearts.16]
portrait = "embarrassed"
local = "Do you think so? I uh, didn't concern myself with the elixir's taste or appearance."
next = "17"

[valen_four_hearts.17]
portrait = "neutral"
local = "Thank you [Ari]. I really appreciate this."
next = "18"

[valen_four_hearts.18]
portrait = "mad"
local = "Ready!"
next = "19"

[valen_four_hearts.19]
portrait = "ugh"
local = "Oh dear."
next = "20"

[valen_four_hearts.20]
portrait = "sad"
local = "Coming to? How do you feel?"
prompts = [
	{ local = "I saw my life flash before my eyes...", next = "21" },
	{ local = "I feel great!", next = "22" },
]

[valen_four_hearts.21]
portrait = "sad"
local = "I'm sorry, [Ari]."
next = "23"

[valen_four_hearts.22]
portrait = "neutral"
local = "I should hope so, I used the last of the panacea on you after the test batch didn't work out."
next = "23"

[valen_four_hearts.23]
portrait = "think"
local = "I've wanted to keep my work secret until I was successful, but with the last of the panacea gone, this has become more urgent..."
next = "24"

[valen_four_hearts.24]
portrait = "neutral"
local = "Can I count on you to help me, [Ari]?"
next = "25"

[valen_four_hearts.25]
portrait = "happy"
local = "Thank you."
next = "26"

[valen_four_hearts.26]
portrait = "sad"
local = "I promise not to risk harming your health again."
next = "27"

[valen_four_hearts.27]
portrait = "neutral"
local = "I'm going to collect all my notes together and try to narrow down what's gone wrong. I'll let you know when it's time to start mixing up the next test batch."
