[engagement_ring_valen]
kind = "gameplay_triggered"
actions = [
	{ bark = { bark = "cute_face", npc = "valen" } },
	{ cutscene = "valen_ten_hearts" }
]
speaker = "valen"
portrait = "neutral"
local = "You have a pensive look, [Ari]."
next = "1"

[engagement_ring_valen.1]
speaker = "valen"
portrait = "happy"
local = "Would you like to talk?"
next = "2"

[engagement_ring_valen.2]
speaker = "valen"
portrait = "think_smile"
local = "I have time, and I wouldn't mind a walk in the $Western Ruins$."

# scene
[valen_ten_hearts]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "think_smile"
local = "Thanks for coming out here with me, [Ari]."
next = "1"

[valen_ten_hearts.1]
speaker = "valen"
portrait = "neutral_blush"
local = "Walking around these ruins always reminds me of you, and the time we went searching for the Cliffblossom together."
next = "2"

[valen_ten_hearts.2]
speaker = "valen"
portrait = "think"
local = "I suppose I've never articulated this, but... there aren't many people I can turn to for help."
next = "3"

[valen_ten_hearts.3]
speaker = "valen"
portrait = "neutral"
local = "Mistria is a place where neighbors support each other, but..."
next = "4"

[valen_ten_hearts.4]
speaker = "valen"
portrait = "sincere_special"
local = "I'm a doctor, and the townsfolk are my patients."
next = "5"

[valen_ten_hearts.5]
speaker = "valen"
portrait = "sad"
local = "As a professional, it stands to reason that I try not to speak much about my own troubles."
next = "6"

[valen_ten_hearts.6]
speaker = "valen"
portrait = "neutral"
local = "That line of thinking began at my practice, but eventually it appeared in most facets of my life."
next = "7"

[valen_ten_hearts.7]
speaker = "valen"
portrait = "think"
local = "And over time I simply... got used to thinking that way. Perhaps I even began to prefer it."
next = "8"

[valen_ten_hearts.8]
speaker = "valen"
portrait = "embarrassed"
local = "I took it as a fact of life, that I had to do things alone... until you walked into my Clinic."
prompts = [
	{ local = "What did you even think of me, walking in straight from my work in the fields?", next = "9" },
	{ local = "I'm glad I came in for a checkup that day.", next = "10" }
]

[valen_ten_hearts.9]
speaker = "valen"
portrait = "happy_blush"
local = "That you were awfully cute, with that smudge of dirt on your cheek and the sweat on your brow."
next = "11"

[valen_ten_hearts.10]
speaker = "valen"
portrait = "happy_blush"
local = "Me too."
next = "11"

[valen_ten_hearts.11]
speaker = "valen"
portrait = "sad"
local = "When we first met, rediscovering the formula for the $Panacea$ was weighing on me every day."
next = "12"

[valen_ten_hearts.12]
speaker = "valen"
portrait = "think"
local = "My research was a secret. My own burden to bear."
next = "13"

[valen_ten_hearts.13]
speaker = "valen"
portrait = "raised_eyebrow"
local = "But you surprised me. You assisted me with Hayden, helped me handle Juniper, and joined me in the search for the elusive Cliffblossom."
next = "14"

[valen_ten_hearts.14]
speaker = "valen"
portrait = "neutral"
local = "You made it so easy to ask for help. Sometimes, I didn't even need to ask."
next = "15"

[valen_ten_hearts.15]
speaker = "valen"
portrait = "think"
local = "Don't misunderstand, I like that I can depend on myself."
next = "16"

[valen_ten_hearts.16]
speaker = "valen"
portrait = "neutral"
local = "But being self-sufficient doesn't need to mean... being alone."
next = "17"

[valen_ten_hearts.17]
speaker = "valen"
portrait = "happy"
local = "Thank you for reminding me of that."
next = "18"

[valen_ten_hearts.18]
speaker = "valen"
portrait = "neutral_blush"
local = "It's an understatement, but... you've truly enriched my life, [Ari]."
prompts = [
	{ local = "I'm always here for you... no matter what you need!", next = "19" },
	{ local = "I feel the same. You taught me to take better care of myself.", next = "20" }
]

[valen_ten_hearts.19]
speaker = "valen"
portrait = "happy_blush"
local = "Oh? I'll make a note of that. Haha!"
next = "21"

[valen_ten_hearts.20]
speaker = "valen"
portrait = "happy_blush"
local = "Oh? I'll take that to heart."
next = "21"

[valen_ten_hearts.21]
speaker = "valen"
portrait = "think"
local = "I..."
next = "22"

[valen_ten_hearts.22]
speaker = "valen"
portrait = "think_blush"
local = "How do I say this? I'm thankful to know you..."
next = "23"

[valen_ten_hearts.23]
speaker = "valen"
portrait = "caring_special"
local = "And to be close to you."
next = "24"

[valen_ten_hearts.24]
speaker = "valen"
portrait = "embarrassed"
local = "You're precious to me, [Ari]."
next = [
    { target = "25_second", requires = [
        { cutscene_seen_valen_ten_hearts = true }
    ] },
    { target = "25_first", requires = [] }
]

[valen_ten_hearts.25_second]
speaker = "valen"
portrait = "think_smile"
local = "That's why I gave you the $Panacea Jar$."
next = "26"

[valen_ten_hearts.25_first]
speaker = "valen"
portrait = "think_smile"
local = "Which reminds me... I have something for you. It's a $Panacea Jar$."
next = "26"

[valen_ten_hearts.26]
speaker = "valen"
portrait = "neutral"
local = "The $Panacea$ is still quite rare, but I want you to always have some on hand."
next = "27"

[valen_ten_hearts.27]
speaker = "valen"
portrait = "think_blush"
local = "So you'll always be safe. That's important to me."
next = "28"

[valen_ten_hearts.28]
speaker = "valen"
portrait = "think"
local = "I care for all the townsfolk, but..."
next = "29"

[valen_ten_hearts.29]
speaker = "valen"
portrait = "embarrassed"
local = "It's different, with you."
next = "30"

[valen_ten_hearts.30]
speaker = "valen"
portrait = "think_blush"
local = "I suppose I am, ah... more personally invested in your well-being."
next = "31"

[valen_ten_hearts.31]
speaker = "valen"
portrait = "embarrassed"
local = "But you know that already, don't you? O-of course you do..."
next = "32"

[valen_ten_hearts.32]
speaker = "valen"
portrait = "happy"
effect = "drop"
local = "Sorry... I don't know what's gotten into me today."
next = "33"

[valen_ten_hearts.33]
speaker = "valen"
portrait = "embarrassed"
local = "I'm not usually one to be so talkative, nor to have so much trouble with my words..."
next = "34"

[valen_ten_hearts.34]
speaker = "valen"
portrait = "neutral"
local = "In any case, you had mentioned there was something you wanted to discuss?"
prompts = [
	{ local = "I wanted to talk to you about our future together...", next = "35" },
	{ local = "Let's talk about it another time...", next = "44" }
]

[valen_ten_hearts.35]
speaker = "valen"
portrait = "think"
local = "Our future?"
next = "36"

[valen_ten_hearts.36]
speaker = "valen"
portrait = "happy_blush"
local = "In what sense?"
prompts = [
	{ local = "I love you, Valen. Will you marry me?", next = "37" },
	{ local = "Actually, let's talk about it more another day.", next = "44" }
]

[valen_ten_hearts.37]
writes = [
	{ breakup_bump = true, expires = "3d" },
	{ engagement_bump = true, expires = "2d" },
	{ engagement_delay = true, expires = "20h" },
	{ engagement_cap = false, expires = "3d" }
]
actions = [{ can_talk = "valen" }]
speaker = "valen"
portrait = "embarrassed"
effect = "surprise"
local = "..."
next = "38"

[valen_ten_hearts.38]
speaker = "valen"
portrait = "teary"
local = "You want to... marry me?"
next = "39"

[valen_ten_hearts.39]
speaker = "valen"
portrait = "happy_blush"
local = "Yes! Of course I will!"
next = "40"

[valen_ten_hearts.40]
speaker = "valen"
portrait = "caring_special"
local = "There's nothing I want more."
next = "41"

[valen_ten_hearts.41]
speaker = "valen"
portrait = "happy_blush"
local = "I'm so happy I can hardly think straight!"
next = "42"

[valen_ten_hearts.42]
speaker = "valen"
portrait = "embarrassed"
local = "I love you, [Ari]!"
next = "43"

[valen_ten_hearts.43]
speaker = "valen"
portrait = "happy_blush"
local = "I love you so much!"

[valen_ten_hearts.44]
speaker = "valen"
portrait = "raised_eyebrow"
local = "Another day? Of course."
next = "45"

[valen_ten_hearts.45]
speaker = "valen"
portrait = "happy"
local = "Come find me whenever you'd like to talk. I'm always here for you."
