[valen_two_hearts]
kind = "gameplay_triggered"
speaker = "hayden"
portrait = "ugh"
local = "Don't sugarcoat it, Valen! You're gonna have to take off the foot, I just know it!"
next = "1"

[valen_two_hearts.1]
speaker = "valen"
portrait = "raised_eyebrow"
local = "You twisted your ankle tripping over a sack of grain, Hayden."
next = "2"

[valen_two_hearts.2]
portrait = "neutral"
local = "Keep off that foot for two weeks... I'll come check up on you, and we can go from there."
next = "3"

[valen_two_hearts.3]
speaker = "hayden"
portrait = "gloomy"
local = "[Ari], I'm doomed... I can't work my field for two weeks. My harvest is going to be ruined..."
next = "4"

[valen_two_hearts.4]
portrait = "sad"
effect = "sick"
local = "And then I'll starve to death... and my poor, dear chicken Henrietta... she'll have to arrange the funeral herself, and..."
next = "5"

[valen_two_hearts.5]
speaker = "valen"
portrait = "mad"
local = "Oh, hush, Hayden. You should have said as much earlier."
next = "6"

[valen_two_hearts.6]
portrait = "think"
local = "[Ari], could you go into the basement? There's a barrel in the corner... bring me one scoop of what's inside."
prompts = [
	{ local = "Barrel?", next = "7" },
	{ local = "Basement?", next = "8" },
]

[valen_two_hearts.7]
portrait = "neutral"
local = "You'll see. Now, quickly please, Hayden is in no danger of expiring, but his belly-aching isn't doing any of us any good."
next = "9"

[valen_two_hearts.8]
portrait = "neutral"
local = "Yes, the cellar door in the corner. Quickly, please."
next = "9"

[valen_two_hearts.9]
portrait = "neutral"
local = "Thank you, [Ari]."
prompts = [
	{ local = "What are you doing?", next = "10" },
	{ local = "What is that?", next = "11" },
]

[valen_two_hearts.10]
portrait = "think"
local = "Just a moment, [Ari], speed is essential to an effective application."
next = "12"

[valen_two_hearts.11]
portrait = "think"
local = "Ah, in a moment [Ari], I need to focus."
next = "12"

[valen_two_hearts.12]
speaker = "hayden"
portrait = "think"
local = "Oh... ohhh! Amazing!"
next = "13"

[valen_two_hearts.13]
portrait = "happy"
local = "I'm CURED! You're a miracle worker, Doctor!"
next = "14"

[valen_two_hearts.14]
speaker = "valen"
portrait = "raised_eyebrow"
local = "Don't run, Hayden! Stay hydrated! Make sure you get plenty of rest!"
next = "15"

[valen_two_hearts.15]
portrait = "neutral"
local = "Thanks for helping out, [Ari]. You're here for your check-up?"
next = "16"

[valen_two_hearts.16]
portrait = "neutral"
local = "Good, go lie down on the bed, I'll be right with you."
next = "17"

[valen_two_hearts.17]
portrait = "neutral"
local = "You've got a clean bill of health, [Ari]. All that fresh air and outdoor work have you in tiptop shape."
next = "18"

[valen_two_hearts.18]
portrait = "raised_eyebrow"
local = "Anything else you'd like to ask me? Don't hesitate, patient confidentiality is part of a doctor's code."
prompts = [
	{ local = "What's with the creepy basement?", next = "19" },
	{ local = "What was that powder in the barrel? Can I have some?", next = "19" },
]

[valen_two_hearts.19]
portrait = "mad"
local = "Is there anything about your personal health you'd like to ask me about?"
next = "20"

[valen_two_hearts.20]
portrait = "neutral"
local = "Now, I've got to get ready for my next patient... have a nice day, [Ari]."
