[engagement_ring_caldarus]
kind = "gameplay_triggered"
actions = [
	{ bark = { bark = "cute_face", npc = "caldarus" } },
	{ cutscene = "caldarus_ten_hearts" }
]
speaker = "caldarus"
portrait = "neutral"
local = "Is something troubling you, [Ari]?"
next = "1"

[engagement_ring_caldarus.1]
speaker = "caldarus"
portrait = "smile"
local = "There is something you wish to speak of? Of course."
next = "2"

[engagement_ring_caldarus.2]
speaker = "caldarus"
portrait = "happy"
local = "Shall we go for a $walk in the woods$? I always enjoy my time spent with you."

# scene
[caldarus_ten_hearts]
kind = "gameplay_triggered"
speaker = "caldarus"
portrait = "smile"
local = "These woods are beautiful this time of year."
next = "1"

[caldarus_ten_hearts.1]
speaker = "caldarus"
portrait = "caring_special"
local = "Moreso with your company."
next = "2"

[caldarus_ten_hearts.2]
speaker = "caldarus"
portrait = "unsure_special"
local = "This place... something about it always brings you to mind."
next = "3"

[caldarus_ten_hearts.3]
speaker = "caldarus"
portrait = "embarrassed"
local = "It is an old, melancholy feeling..."
next = "4"

[caldarus_ten_hearts.4]
speaker = "caldarus"
portrait = "laugh_special"
local = "And a new, joyous one."
next = "5"

[caldarus_ten_hearts.5]
speaker = "caldarus"
portrait = "caring_special"
local = "These emotions... they should be at odds, should they not? But instead, they fit together like a puzzle."
next = "6"

[caldarus_ten_hearts.6]
speaker = "caldarus"
portrait = "laugh_special"
local = "Forgive me. I always come to you when I cannot understand my own feelings."
prompts = [
	{ local = "You're cute when you're like this.", next = "7" },
	{ local = "You've always been a guide. It's my turn.", next = "8" }
]

[caldarus_ten_hearts.7]
speaker = "caldarus"
portrait = "embarrassed"
local = "Is that so? Perhaps I need not be so shy about sharing, then."
next = "9"

[caldarus_ten_hearts.8]
speaker = "caldarus"
portrait = "embarrassed"
local = "[Ari]..."
next = "9"

[caldarus_ten_hearts.9]
speaker = "caldarus"
portrait = "unsure_special"
local = "When you repaired my statue and woke me, my first thought was of Mistria."
next = "10"

[caldarus_ten_hearts.10]
speaker = "caldarus"
portrait = "smile"
local = "And what kismet it was, to form a pact with a soul who instinctively understood my life's purpose."
next = "11"

[caldarus_ten_hearts.11]
speaker = "caldarus"
portrait = "think"
local = "I thought you would come to me only when you were in need, as it has always been between myself and mortals."
next = "12"

[caldarus_ten_hearts.12]
speaker = "caldarus"
portrait = "caring_special"
local = "But sometimes you would come to me simply to... talk. And it was in those times that I felt my heart begin to change."
next = "13"

[caldarus_ten_hearts.13]
speaker = "caldarus"
portrait = "sigh"
local = "Before you, I had always thought of my role as that of a caretaker... tending to the garden of Mistria while being held slightly apart."
next = "14"

[caldarus_ten_hearts.14]
speaker = "caldarus"
portrait = "think"
local = "Who I am has always brought with it a certain measure of deference, even worship..."
next = "15"

[caldarus_ten_hearts.15]
speaker = "caldarus"
portrait = "neutral"
local = "And I thought I was happy being only what others needed me to be."
next = "16"

[caldarus_ten_hearts.16]
speaker = "caldarus"
portrait = "smile"
local = "But it is not so. You have shown me that I wish to stand in the garden, too."
prompts = [
	{ local = "It was your guidance that helped me find my place as well.", next = "17" },
	{ local = "Our pact is important, but what really helped me were the times you listened.", next = "17" }
]

[caldarus_ten_hearts.17]
speaker = "caldarus"
portrait = "embarrassed"
local = "Truly? Then it seems it is mutual."
next = "18"

[caldarus_ten_hearts.18]
speaker = "caldarus"
portrait = "unsure_special"
local = "It is undeniable, the ways I have begun to change under your influence."
next = "19"

[caldarus_ten_hearts.19]
speaker = "caldarus"
portrait = "neutral"
local = "Mingling with the townsfolk, learning to cook..."
next = "20"

[caldarus_ten_hearts.20]
speaker = "caldarus"
portrait = "smile"
local = "These are things I would not have allowed myself, once."
next = "21"

[caldarus_ten_hearts.21]
speaker = "caldarus"
portrait = "laugh_special"
local = "But you have shown me the way..."
next = "22"

[caldarus_ten_hearts.22]
speaker = "caldarus"
portrait = "caring_special"
local = "You have opened my eyes, and my heart."
next = "23"

[caldarus_ten_hearts.23]
speaker = "caldarus"
portrait = "serious_blush"
local = "I wish for us to always be together, [Ari]. Regardless of lifetime, regardless of form."
next = [
    { target = "24_second", requires = [
        { cutscene_seen_caldarus_ten_hearts = true }
    ] },
    { target = "24_first", requires = [] }
]

[caldarus_ten_hearts.24_second]
speaker = "caldarus"
portrait = "unsure_special"
local = "That is why I put chisel to stone for the first time in a millenia..."
next = "25_second"

[caldarus_ten_hearts.25_second]
speaker = "caldarus"
portrait = "embarrassed"
local = "To sculpt the $Dragonsworn Statue$."
next = "26_second"

[caldarus_ten_hearts.26_second]
speaker = "caldarus"
portrait = "laugh_special"
local = "I thought of you as I worked."
next = "27_second"

[caldarus_ten_hearts.27_second]
speaker = "caldarus"
portrait = "caring_special"
local = "As I... frequently do."
next = "28"

[caldarus_ten_hearts.24_first]
speaker = "caldarus"
portrait = "unsure_special"
local = "Ah, that reminds me... There is something I wish to show you."
next = "25_first"

[caldarus_ten_hearts.25_first]
speaker = "caldarus"
portrait = "embarrassed"
local = "I... made something for you. I call it the $Dragonsworn Statue$."
next = "26_first"

[caldarus_ten_hearts.26_first]
speaker = "caldarus"
portrait = "unsure_special"
local = "It has been a millenia since I put chisel to stone... I hope I did justice to your countenance."
next = "27_first"

[caldarus_ten_hearts.27_first]
speaker = "caldarus"
portrait = "caring_special"
local = "I thought of you as I worked. As I... frequently do."
next = "28"

[caldarus_ten_hearts.28]
speaker = "caldarus"
portrait = "unsure_special"
local = "And I thought that perhaps you could place the statue on your farm, near my own."
next = "29"

[caldarus_ten_hearts.29]
speaker = "caldarus"
portrait = "embarrassed"
local = "So that no matter how much time passes... a part of us will remain there together, always."
next = "30"

[caldarus_ten_hearts.30]
speaker = "caldarus"
portrait = "happy"
local = "Forgive me for speaking at length."
next = "31"

[caldarus_ten_hearts.31]
speaker = "caldarus"
portrait = "caring_special"
local = "There was something you wished to discuss today, was there not?"
prompts = [
	{ local = "I wanted to talk to you about our future together...", next = "32" },
	{ local = "Let's talk about it another time...", next = "34" }
]

[caldarus_ten_hearts.32]
speaker = "caldarus"
portrait = "embarrassed"
local = "Our future together."
next = "33"

[caldarus_ten_hearts.33]
speaker = "caldarus"
portrait = "caring_special"
local = "[Ari]...?"
prompts = [
	{ local = "I love you, Caldarus. Will you marry me?", next = "36" },
	{ local = "Actually, let's talk about it more another day.", next = "44" }
]

[caldarus_ten_hearts.34]
speaker = "caldarus"
portrait = "embarrassed"
local = "Another time? As you wish."
next = "35"

[caldarus_ten_hearts.35]
speaker = "caldarus"
portrait = "smile"
local = "Just know, I am always near if you have need of me."

[caldarus_ten_hearts.36]
writes = [
	{ breakup_bump = true, expires = "3d" },
	{ engagement_bump = true, expires = "2d" },
	{ engagement_delay = true, expires = "20h" },
	{ engagement_cap = false, expires = "3d" }
]
actions = [{ can_talk = "caldarus" }]
speaker = "caldarus"
portrait = "embarrassed"
local = "[Ari]... you..."
next = "37"

[caldarus_ten_hearts.37]
speaker = "caldarus"
portrait = "laugh_special"
local = "..."
next = "38"

[caldarus_ten_hearts.38]
speaker = "caldarus"
portrait = "caring_special"
local = "Yes. It would be my honor..."
next = "39"

[caldarus_ten_hearts.39]
speaker = "caldarus"
portrait = "embarrassed"
local = "And my most heartfelt wish come true!"
next = "40"

[caldarus_ten_hearts.40]
speaker = "caldarus"
portrait = "laugh_special"
local = "You have made me so happy this day, [Ari]..."
next = "41"

[caldarus_ten_hearts.41]
speaker = "caldarus"
portrait = "caring_special"
local = "I love you. With all my heart!"
next = "42"

[caldarus_ten_hearts.42]
speaker = "caldarus"
portrait = "laugh_special"
local = "Oh my... This calls for a ceremony, does it not?"
next = "43"

[caldarus_ten_hearts.43]
speaker = "caldarus"
portrait = "caring_special"
local = "Let us make it a celebration to remember."

[caldarus_ten_hearts.44]
speaker = "caldarus"
portrait = "sigh"
local = "Another day? As you wish."
next = "45"

[caldarus_ten_hearts.45]
speaker = "caldarus"
portrait = "smile"
local = "Just know, I am always near if you have need of me."
