[core]
	name = "Alpaca"
	plural_name = "Alpaca"
	female_other = "a female alpaca"
	male_other = "a male alpaca"
	new_baby_born = "A new Alpaca was born! Enter new name"
	size = "large"
	default_icon_variant = "white"
	cosmetic_sub_icon = "spr_ui_item_sub_animal_alpaca"
	requirements = { repaired_haydens_farm = true, reached_date = { season = "winter", day = 1, year = 1 } }

[behavior]
	can_wander_in_home = false

[celebration_data]
	baby_animation = "happy"
	adult_animation = "happy"

[production.male]
	days_to_produce = 3
	normal_product = "alpaca_wool"
	golden_product = "golden_alpaca_wool"

[production.female]
	days_to_produce = 3
	normal_product = "alpaca_wool"
	golden_product = "golden_alpaca_wool"

[breeding]
	uses_egg = false
	treat = "heart_shaped_alpaca_treat"

[eating]
	kind = "hay"
	offset = [21, 0]
	baby_offset = [12, -2]
	shake_frames = [1, 9]

[petting]
	kind = "pet"

[pricing]
	buy_price = 2300
	baby_sell_price = 650
	adult_sell_prices = [
		900,
		975,
		1170,
		1300,
		1450,
		1600,
		1850,
		2100,
		2300,
		2500,
		2600,
	]

[mounting]
	is_mount = true

[bark_offsets]
	adult = { north = [1, -42], south = [1, -38], east = [8, -42], west = [-6, -42] }
	baby = { north = [2, -36], south = [2, -34], east = [5, -35], west = [0, -35] }

[[sounds.baby]]
	ambient = "SoundEffects/Animals/BabyAlpacaAmbient"
	positive_react = "SoundEffects/Animals/BabyAlpacaPositiveReact"
	negative_react = "SoundEffects/Animals/BabyAlpacaNegativeReact"

[[sounds.adult]]
	ambient = "SoundEffects/Animals/AlpacaAmbient"
	positive_react = "SoundEffects/Animals/AlpacaPositiveReact"
	negative_react = "SoundEffects/Animals/AlpacaNegativeReact"

[animations.idle]
	player_offsets.south = [
		[0, -10],
	]
	player_offsets.east = [
		[-2, -10],
	]
	player_offsets.north = [
		[0, -10],
	]
	randomly_selected = false
	duration = [3, 7]
	play_ambient_sounds = true

[animations.idle_2]
	player_offsets.south = [
		[0, -10],
	]
	player_offsets.east = [
		[-2, -10],
	]
	player_offsets.north = [
		[0, -10],
	]
	end_with_animation = true
	valid_for = ["male", "female"]

[animations.blink]
	player_offsets.south = [
		[0, -10],
	]
	player_offsets.east = [
		[-2, -10],
	]
	player_offsets.north = [
		[0, -10],
	]
	end_with_animation = true

[animations.walk]
	player_offsets.south = [
		[0, -9],
		[0, -10],
		[0, -9],
		[0, -10],
	]
	player_offsets.east = [
		[-2, -9],
		[-2, -10],
		[-2, -9],
		[-2, -10],
	]
	player_offsets.north = [
		[0, -9],
		[0, -10],
		[0, -9],
		[0, -10],
	]
	randomly_selected = false
	duration = [1, 2]

[animations.run]
	player_offsets.south = [
		[0, -10],
		[0, -11],
		[0, -12],
		[0, -11],
	]
	player_offsets.east = [
		[-2, -10],
		[-2, -10],
		[-2, -11],
		[-2, -11],
	]
	player_offsets.north = [
		[0, -9],
		[0, -10],
		[0, -11],
		[0, -10],
	]
	randomly_selected = false
	valid_for = ["male", "female"]

[animations.jump]
	player_offsets.south = [
		[0, -11],
		[0, -13],
		[0, -10],
		[0, -9],
	]
	player_offsets.east = [
		[-2, -11],
		[-2, -12],
		[-2, -12],
		[-2, -10],
	]
	player_offsets.north = [
		[0, -12],
		[0, -14],
		[0, -13],
		[0, -9],
	]
	randomly_selected = false
	valid_for = ["male", "female"]

[animations.happy]
	randomly_selected = false

[animations.playball]
	randomly_selected = false
	valid_for = ["male", "female"]

# Variants
[variants.default]
	lut = "spr_animal_alpaca_lut"

	[variants.default.male]
		key = "basic_base"
		ui_key = "basic"
		top_key = "basic_top"

	[variants.default.female]
		key = "basic_base"
		ui_key = "basic"
		top_key = "basic_top"

	[variants.default.baby]
		key = "basic_baby_cria"
		top_key = "<n/a>"

# White
[variants.white]
	name = "White"
	lut_index = 1
	default_unlocked = true

# Black
[variants.black]
	name = "Black"
	lut_index = 2
	default_unlocked = true

# Brown
[variants.brown]
	name = "Brown"
	lut_index = 3
	default_unlocked = true

# Snowy
[variants.snowy]
	name = "Snowy"
	tier = 2
	lut_index = 4

# Desert
[variants.desert]
	name = "Desert"
	tier = 2
	lut_index = 5

# Indigo
[variants.indigo]
	name = "Indigo"
	tier = 2
	lut_index = 6

# Blue
[variants.blue]
	name = "Blue"
	tier = 3
	lut_index = 7

# Purple
[variants.purple]
	name = "Purple"
	tier = 3
	lut_index = 8

# Pink
[variants.pink]
	name = "Pink"
	tier = 3
	lut_index = 9

# Silver
[variants.silver]
	name = "Silver"
	tier = 4
	lut_index = 10

# Gold
[variants.gold]
	name = "Gold"
	tier = 5
	lut_index = 11

# Spring
[variants.spring]
	name = "Spring"
	tier = 6
	born_in = "spring"
	lut_index = 12
	default_cosmetic = "flower_crown"

# Summer
[variants.summer]
	name = "Summer"
	tier = 6
	born_in = "summer"
	lut_index = 13
	default_cosmetic = "sunglasses"

# Fall
[variants.fall]
	name = "Fall"
	tier = 6
	born_in = "fall"
	lut = "<n/a>"
	default_cosmetic = "horns"

	[variants.fall.male]
		key = "fall_base"
		ui_key = "fall"
		top_key = "fall_top"

	[variants.fall.female]
		key = "fall_base"
		ui_key = "fall"
		top_key = "fall_top"

	[variants.fall.baby]
		key = "fall_baby_cria"

# Winter
[variants.winter]
	name = "Winter"
	tier = 6
	born_in = "winter"
	lut_index = 15
	default_cosmetic = "winter_hat"

[cosmetics.default.male]
	key = "base"
	top_key = "top"

[cosmetics.default.female]
	key = "base"
	top_key = "top"

[cosmetics.beaded_necklace]
	name = "Alpaca Beaded Necklace"

[cosmetics.bowtie]
	name = "Alpaca Bowtie"

[cosmetics.flower_crown]
	name = "Alpaca Flower Crown"

[cosmetics.gold_pendant]
	name = "Alpaca Gold Pendant"

[cosmetics.horns]
	name = "Alpaca Horns"

[cosmetics.ribbon_blue]
	name = "Alpaca Blue Ribbon"

[cosmetics.ribbon_red]
	name = "Alpaca Red Ribbon"

[cosmetics.ribbon_white]
	name = "Alpaca White Ribbon"

[cosmetics.scarf]
	name = "Alpaca Scarf"

[cosmetics.spiked_collar]
	name = "Alpaca Spiked Collar"

[cosmetics.sunglasses]
	name = "Alpaca Sunglasses"

[cosmetics.winter_hat]
	name = "Alpaca Winter Hat"

[cosmetics.beret]
	name = "Alpaca Beret"

[cosmetics.lacy_collar]
	name = "Alpaca Lacy Collar"
