[eiland_six_hearts]
kind = "gameplay_triggered"
speaker = "eiland"
portrait = "neutral"
local = "Thank you for coming, [Ari]."
prompts = [
	{ local = "Where are we off to? Ancient ruins? A forgotten temple?", next = "1" },
	{ local = "Let me guess, you found a secret labyrinth in the Manor!", next = "2" }
]

[eiland_six_hearts.1]
speaker = "eiland"
portrait = "embarrassed"
local = "Haha... about that..."
next = "3"

[eiland_six_hearts.2]
speaker = "eiland"
portrait = "embarrassed"
local = "Haha, well... in a sense?"
next = "3"

[eiland_six_hearts.3]
speaker = "eiland"
portrait = "neutral"
local = "After translating the text and putting the clues together, I have become convinced that the next piece of the armor is..."
next = "4"

[eiland_six_hearts.4]
speaker = "eiland"
portrait = "ugh"
local = "In this very house."
next = "5"

[eiland_six_hearts.5]
speaker = "eiland"
portrait = "think"
local = """I believe we are looking for the $Dragonsworn Cloak$, a truly excellent example of "Dynweaving" that imparted the cloth with incredible durability."""
next = "6"

[eiland_six_hearts.6]
speaker = "eiland"
portrait = "neutral"
local = "Legends say it could turn aside swords, and even arrows couldn't pierce it."
next = "7"

[eiland_six_hearts.7]
speaker = "eiland"
portrait = "think"
local = "However, at some point the cloak became a symbol of the leader of Mistria. As fashion sensibilities changed, well..."
next = "8"

[eiland_six_hearts.8]
speaker = "eiland"
portrait = "sad"
local = "Frankly, I think it ended up tucked away in some odd corner of the house."
next = "9"

[eiland_six_hearts.9]
speaker = "eiland"
portrait = "neutral"
local = "Luckily for us, nothing ever gets thrown away around here."
next = "10"

[eiland_six_hearts.10]
speaker = "eiland"
portrait = "ugh"
local = "It's hardly an adventure, but can I count on you to help me search?"
prompts = [
	{ local = "I'm in! What are friends for?", next = "11" },
	{ local = "Maybe we'll leave today's adventure out of the history books...", next = "12" }
]

[eiland_six_hearts.11]
speaker = "eiland"
portrait = "happy"
local = "Thank you, [Ari]!"
next = "13"

[eiland_six_hearts.12]
speaker = "eiland"
portrait = "embarrassed"
local = "Haha... I was thinking the same thing."
next = "13"

[eiland_six_hearts.13]
speaker = "eiland"
portrait = "neutral"
local = "Now as you might imagine, I've already done a thorough job of combing through my own rooms. So we'll start with my sister's office."
next = "14"

[eiland_six_hearts.14]
speaker = "adeline"
portrait = "happy"
local = "Hey, you two!"
next = "15"

[eiland_six_hearts.15]
speaker = "adeline"
portrait = "neutral"
local = "Let me guess, you heard I was consolidating old council minutes and want in on the action?"
next = "16"

[eiland_six_hearts.16]
speaker = "elsie"
portrait = "wink"
local = "Don't feel bad saying no. I'm just keeping Adeline company."
next = "17"

[eiland_six_hearts.17]
speaker = "eiland"
portrait = "neutral"
local = "[Ari] and I are on an important mission, hunting for the cloak of the $Dragonsworn$."
next = "18"

[eiland_six_hearts.18]
speaker = "eiland"
portrait = "mad"
local = "I believe it may be somewhere in this very building!"
next = "19"

[eiland_six_hearts.19]
speaker = "elsie"
portrait = "happy"
local = "Oh my, how exciting!"
next = "20"

[eiland_six_hearts.20]
speaker = "adeline"
portrait = "think"
local = "Well feel free to search my office, but I don't think that I've seen anything like that here."
next = "21"

[eiland_six_hearts.21]
speaker = "elsie"
portrait = "think"
local = "I suppose I should conduct a search of my own room then."
next = "22"

[eiland_six_hearts.22]
speaker = "eiland"
portrait = "neutral"
local = "Oh, I'd be happy to help-"
next = "23"

[eiland_six_hearts.23]
speaker = "elsie"
portrait = "wink"
local = "Let's leave your auntie some privacy, eh?"
next = "24"

[eiland_six_hearts.24]
speaker = "adeline"
portrait = "neutral"
local = "This takes me back. It's a bit like the signet ring all over again, isn't it?"
next = "25"

[eiland_six_hearts.25]
speaker = "adeline"
portrait = "happy"
local = "When we were kids, Eiland found an old ring down in the basement."
next = "26"

[eiland_six_hearts.26]
speaker = "adeline"
portrait = "neutral"
local = "He liked it so much he and Mother did a bunch of research to find out whose crest was on it."
next = "27"

[eiland_six_hearts.27]
speaker = "eiland"
portrait = "neutral"
local = "It turned out to be the signet ring of a very, very old Caldosian dynasty, long thought lost."
next = "28"

[eiland_six_hearts.28]
speaker = "adeline"
portrait = "think"
local = "Well Mother was so proud, she had it sent off to the Capital to be verified, and then the Caldosians got word of it..."
prompts = [
	{ local = "The Caldosians must have been thrilled!", next = "29" },
	{ local = "Let me guess, you didn't get your ring back?", next = "30" }
]

[eiland_six_hearts.29]
speaker = "eiland"
portrait = "sad"
local = "It ended up being a bit of an international incident, actually."
next = "31"

[eiland_six_hearts.30]
speaker = "eiland"
portrait = "sad"
local = "It would have ended up in a museum regardless, but no."
next = "31"

[eiland_six_hearts.31]
speaker = "adeline"
portrait = "happy"
local = "Well, it certainly gave you your taste for archaeology at any rate."
next = "32"

[eiland_six_hearts.32]
speaker = "eiland"
portrait = "think"
local = "And the Caldosians got their ring back eventually. I even got an official thank you letter from their Emperor."
next = "33"

[eiland_six_hearts.33]
speaker = "elsie"
portrait = "happy"
local = "Fooooound it!"
effect = "music_notes"
next = "34"

[eiland_six_hearts.34]
speaker = "eiland"
portrait = "think"
local = "Aunt Elsie, perhaps you should let a certified archaeologist check first-"
next = "35"

[eiland_six_hearts.35]
speaker = "eiland"
portrait = "happy"
local = "It really IS the $Dragonsworn Cloak$! It certainly doesn't look that ancient, does it?"
next = "36"

[eiland_six_hearts.36]
speaker = "adeline"
portrait = "neutral"
local = "Wherever did you find it?"
next = "37"

[eiland_six_hearts.37]
speaker = "elsie"
portrait = "neutral"
local = "In my wardrobe. When I moved in I just shoved everything still in there as far back as it would go."
next = "38"

[eiland_six_hearts.38]
speaker = "eiland"
portrait = "neutral"
local = "Can you believe it, [Ari]? The third piece of the $Dragonsworn Armor$! Were there any notes with it? A storage box?"
next = "39"

[eiland_six_hearts.39]
speaker = "elsie"
portrait = "think"
local = "Oh no, it was folded up among a pile of old blankets."
next = "40"

[eiland_six_hearts.40]
speaker = "eiland"
portrait = "ugh"
local = "I was afraid of this."
next = "41"

[eiland_six_hearts.41]
speaker = "eiland"
portrait = "think"
local = "With no clues, it will make the next piece that much harder to find."
next = "42"

[eiland_six_hearts.42]
speaker = "adeline"
portrait = "think"
local = "Maybe it's recorded somewhere in the annals of the house? Those go back hundreds of years."
next = "43"

[eiland_six_hearts.43]
speaker = "eiland"
portrait = "sad"
local = "I think that might be our best bet."
next = "44"

[eiland_six_hearts.44]
speaker = "eiland"
portrait = "neutral"
local = "Let's hope our quest doesn't end here, [Ari]."
prompts = [
	{ local = "We won't stop till we complete the armor!", next = "45" },
	{ local = "Three out of however many ain't bad!", next = "46" }
]

[eiland_six_hearts.45]
speaker = "eiland"
portrait = "happy"
local = "You're right! This is just another challenge to overcome."
next = "47"

[eiland_six_hearts.46]
speaker = "eiland"
portrait = "happy"
local = "It's true, what we've recovered so far is amazing."
next = "47"

[eiland_six_hearts.47]
speaker = "elsie"
portrait = "neutral"
local = "Whatever comes next, I say it's high time to celebrate what you two have achieved."
next = "48"

[eiland_six_hearts.48]
speaker = "eiland"
portrait = "neutral"
local = "And you!"
next = "49"

[eiland_six_hearts.49]
speaker = "elsie"
portrait = "happy"
local = "Just so! I'm going to get a bottle of that very old wine from down cellar."
next = "50"

[eiland_six_hearts.50]
speaker = "adeline"
portrait = "happy"
local = "Cheers everyone!"
